#pragma once
#ifndef SRC_DESIGNERC_LIBABSTRACTRESOURCEBROWSER_H
#define SRC_DESIGNERC_LIBABSTRACTRESOURCEBROWSER_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDesignerResourceBrowserInterface QDesignerResourceBrowserInterface;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QDesignerResourceBrowserInterface* QDesignerResourceBrowserInterface_new(QWidget* parent);
QDesignerResourceBrowserInterface* QDesignerResourceBrowserInterface_new2();
QMetaObject* QDesignerResourceBrowserInterface_MetaObject(const QDesignerResourceBrowserInterface* self);
void* QDesignerResourceBrowserInterface_Metacast(QDesignerResourceBrowserInterface* self, const char* param1);
int QDesignerResourceBrowserInterface_Metacall(QDesignerResourceBrowserInterface* self, int param1, int param2, void** param3);
void QDesignerResourceBrowserInterface_SetCurrentPath(QDesignerResourceBrowserInterface* self, const libqt_string filePath);
libqt_string QDesignerResourceBrowserInterface_CurrentPath(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_CurrentPathChanged(QDesignerResourceBrowserInterface* self, const libqt_string filePath);
void QDesignerResourceBrowserInterface_Connect_CurrentPathChanged(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_PathActivated(QDesignerResourceBrowserInterface* self, const libqt_string filePath);
void QDesignerResourceBrowserInterface_Connect_PathActivated(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_OnMetaObject(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QMetaObject* QDesignerResourceBrowserInterface_QBaseMetaObject(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnMetacast(QDesignerResourceBrowserInterface* self, intptr_t slot);
void* QDesignerResourceBrowserInterface_QBaseMetacast(QDesignerResourceBrowserInterface* self, const char* param1);
void QDesignerResourceBrowserInterface_OnMetacall(QDesignerResourceBrowserInterface* self, intptr_t slot);
int QDesignerResourceBrowserInterface_QBaseMetacall(QDesignerResourceBrowserInterface* self, int param1, int param2, void** param3);
void QDesignerResourceBrowserInterface_OnSetCurrentPath(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseSetCurrentPath(QDesignerResourceBrowserInterface* self, const libqt_string filePath);
void QDesignerResourceBrowserInterface_OnCurrentPath(const QDesignerResourceBrowserInterface* self, intptr_t slot);
libqt_string QDesignerResourceBrowserInterface_QBaseCurrentPath(const QDesignerResourceBrowserInterface* self);
int QDesignerResourceBrowserInterface_DevType(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnDevType(const QDesignerResourceBrowserInterface* self, intptr_t slot);
int QDesignerResourceBrowserInterface_QBaseDevType(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_SetVisible(QDesignerResourceBrowserInterface* self, bool visible);
void QDesignerResourceBrowserInterface_OnSetVisible(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseSetVisible(QDesignerResourceBrowserInterface* self, bool visible);
QSize* QDesignerResourceBrowserInterface_SizeHint(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnSizeHint(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QSize* QDesignerResourceBrowserInterface_QBaseSizeHint(const QDesignerResourceBrowserInterface* self);
QSize* QDesignerResourceBrowserInterface_MinimumSizeHint(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnMinimumSizeHint(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QSize* QDesignerResourceBrowserInterface_QBaseMinimumSizeHint(const QDesignerResourceBrowserInterface* self);
int QDesignerResourceBrowserInterface_HeightForWidth(const QDesignerResourceBrowserInterface* self, int param1);
void QDesignerResourceBrowserInterface_OnHeightForWidth(const QDesignerResourceBrowserInterface* self, intptr_t slot);
int QDesignerResourceBrowserInterface_QBaseHeightForWidth(const QDesignerResourceBrowserInterface* self, int param1);
bool QDesignerResourceBrowserInterface_HasHeightForWidth(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnHasHeightForWidth(const QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseHasHeightForWidth(const QDesignerResourceBrowserInterface* self);
QPaintEngine* QDesignerResourceBrowserInterface_PaintEngine(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnPaintEngine(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QPaintEngine* QDesignerResourceBrowserInterface_QBasePaintEngine(const QDesignerResourceBrowserInterface* self);
bool QDesignerResourceBrowserInterface_Event(QDesignerResourceBrowserInterface* self, QEvent* event);
void QDesignerResourceBrowserInterface_OnEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseEvent(QDesignerResourceBrowserInterface* self, QEvent* event);
void QDesignerResourceBrowserInterface_MousePressEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_OnMousePressEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseMousePressEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_MouseReleaseEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_OnMouseReleaseEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseMouseReleaseEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_MouseDoubleClickEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_OnMouseDoubleClickEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseMouseDoubleClickEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_MouseMoveEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_OnMouseMoveEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseMouseMoveEvent(QDesignerResourceBrowserInterface* self, QMouseEvent* event);
void QDesignerResourceBrowserInterface_WheelEvent(QDesignerResourceBrowserInterface* self, QWheelEvent* event);
void QDesignerResourceBrowserInterface_OnWheelEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseWheelEvent(QDesignerResourceBrowserInterface* self, QWheelEvent* event);
void QDesignerResourceBrowserInterface_KeyPressEvent(QDesignerResourceBrowserInterface* self, QKeyEvent* event);
void QDesignerResourceBrowserInterface_OnKeyPressEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseKeyPressEvent(QDesignerResourceBrowserInterface* self, QKeyEvent* event);
void QDesignerResourceBrowserInterface_KeyReleaseEvent(QDesignerResourceBrowserInterface* self, QKeyEvent* event);
void QDesignerResourceBrowserInterface_OnKeyReleaseEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseKeyReleaseEvent(QDesignerResourceBrowserInterface* self, QKeyEvent* event);
void QDesignerResourceBrowserInterface_FocusInEvent(QDesignerResourceBrowserInterface* self, QFocusEvent* event);
void QDesignerResourceBrowserInterface_OnFocusInEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseFocusInEvent(QDesignerResourceBrowserInterface* self, QFocusEvent* event);
void QDesignerResourceBrowserInterface_FocusOutEvent(QDesignerResourceBrowserInterface* self, QFocusEvent* event);
void QDesignerResourceBrowserInterface_OnFocusOutEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseFocusOutEvent(QDesignerResourceBrowserInterface* self, QFocusEvent* event);
void QDesignerResourceBrowserInterface_EnterEvent(QDesignerResourceBrowserInterface* self, QEnterEvent* event);
void QDesignerResourceBrowserInterface_OnEnterEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseEnterEvent(QDesignerResourceBrowserInterface* self, QEnterEvent* event);
void QDesignerResourceBrowserInterface_LeaveEvent(QDesignerResourceBrowserInterface* self, QEvent* event);
void QDesignerResourceBrowserInterface_OnLeaveEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseLeaveEvent(QDesignerResourceBrowserInterface* self, QEvent* event);
void QDesignerResourceBrowserInterface_PaintEvent(QDesignerResourceBrowserInterface* self, QPaintEvent* event);
void QDesignerResourceBrowserInterface_OnPaintEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBasePaintEvent(QDesignerResourceBrowserInterface* self, QPaintEvent* event);
void QDesignerResourceBrowserInterface_MoveEvent(QDesignerResourceBrowserInterface* self, QMoveEvent* event);
void QDesignerResourceBrowserInterface_OnMoveEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseMoveEvent(QDesignerResourceBrowserInterface* self, QMoveEvent* event);
void QDesignerResourceBrowserInterface_ResizeEvent(QDesignerResourceBrowserInterface* self, QResizeEvent* event);
void QDesignerResourceBrowserInterface_OnResizeEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseResizeEvent(QDesignerResourceBrowserInterface* self, QResizeEvent* event);
void QDesignerResourceBrowserInterface_CloseEvent(QDesignerResourceBrowserInterface* self, QCloseEvent* event);
void QDesignerResourceBrowserInterface_OnCloseEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseCloseEvent(QDesignerResourceBrowserInterface* self, QCloseEvent* event);
void QDesignerResourceBrowserInterface_ContextMenuEvent(QDesignerResourceBrowserInterface* self, QContextMenuEvent* event);
void QDesignerResourceBrowserInterface_OnContextMenuEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseContextMenuEvent(QDesignerResourceBrowserInterface* self, QContextMenuEvent* event);
void QDesignerResourceBrowserInterface_TabletEvent(QDesignerResourceBrowserInterface* self, QTabletEvent* event);
void QDesignerResourceBrowserInterface_OnTabletEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseTabletEvent(QDesignerResourceBrowserInterface* self, QTabletEvent* event);
void QDesignerResourceBrowserInterface_ActionEvent(QDesignerResourceBrowserInterface* self, QActionEvent* event);
void QDesignerResourceBrowserInterface_OnActionEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseActionEvent(QDesignerResourceBrowserInterface* self, QActionEvent* event);
void QDesignerResourceBrowserInterface_DragEnterEvent(QDesignerResourceBrowserInterface* self, QDragEnterEvent* event);
void QDesignerResourceBrowserInterface_OnDragEnterEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseDragEnterEvent(QDesignerResourceBrowserInterface* self, QDragEnterEvent* event);
void QDesignerResourceBrowserInterface_DragMoveEvent(QDesignerResourceBrowserInterface* self, QDragMoveEvent* event);
void QDesignerResourceBrowserInterface_OnDragMoveEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseDragMoveEvent(QDesignerResourceBrowserInterface* self, QDragMoveEvent* event);
void QDesignerResourceBrowserInterface_DragLeaveEvent(QDesignerResourceBrowserInterface* self, QDragLeaveEvent* event);
void QDesignerResourceBrowserInterface_OnDragLeaveEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseDragLeaveEvent(QDesignerResourceBrowserInterface* self, QDragLeaveEvent* event);
void QDesignerResourceBrowserInterface_DropEvent(QDesignerResourceBrowserInterface* self, QDropEvent* event);
void QDesignerResourceBrowserInterface_OnDropEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseDropEvent(QDesignerResourceBrowserInterface* self, QDropEvent* event);
void QDesignerResourceBrowserInterface_ShowEvent(QDesignerResourceBrowserInterface* self, QShowEvent* event);
void QDesignerResourceBrowserInterface_OnShowEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseShowEvent(QDesignerResourceBrowserInterface* self, QShowEvent* event);
void QDesignerResourceBrowserInterface_HideEvent(QDesignerResourceBrowserInterface* self, QHideEvent* event);
void QDesignerResourceBrowserInterface_OnHideEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseHideEvent(QDesignerResourceBrowserInterface* self, QHideEvent* event);
bool QDesignerResourceBrowserInterface_NativeEvent(QDesignerResourceBrowserInterface* self, const libqt_string eventType, void* message, intptr_t* result);
void QDesignerResourceBrowserInterface_OnNativeEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseNativeEvent(QDesignerResourceBrowserInterface* self, const libqt_string eventType, void* message, intptr_t* result);
void QDesignerResourceBrowserInterface_ChangeEvent(QDesignerResourceBrowserInterface* self, QEvent* param1);
void QDesignerResourceBrowserInterface_OnChangeEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseChangeEvent(QDesignerResourceBrowserInterface* self, QEvent* param1);
int QDesignerResourceBrowserInterface_Metric(const QDesignerResourceBrowserInterface* self, int param1);
void QDesignerResourceBrowserInterface_OnMetric(const QDesignerResourceBrowserInterface* self, intptr_t slot);
int QDesignerResourceBrowserInterface_QBaseMetric(const QDesignerResourceBrowserInterface* self, int param1);
void QDesignerResourceBrowserInterface_InitPainter(const QDesignerResourceBrowserInterface* self, QPainter* painter);
void QDesignerResourceBrowserInterface_OnInitPainter(const QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseInitPainter(const QDesignerResourceBrowserInterface* self, QPainter* painter);
QPaintDevice* QDesignerResourceBrowserInterface_Redirected(const QDesignerResourceBrowserInterface* self, QPoint* offset);
void QDesignerResourceBrowserInterface_OnRedirected(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QPaintDevice* QDesignerResourceBrowserInterface_QBaseRedirected(const QDesignerResourceBrowserInterface* self, QPoint* offset);
QPainter* QDesignerResourceBrowserInterface_SharedPainter(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnSharedPainter(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QPainter* QDesignerResourceBrowserInterface_QBaseSharedPainter(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_InputMethodEvent(QDesignerResourceBrowserInterface* self, QInputMethodEvent* param1);
void QDesignerResourceBrowserInterface_OnInputMethodEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseInputMethodEvent(QDesignerResourceBrowserInterface* self, QInputMethodEvent* param1);
QVariant* QDesignerResourceBrowserInterface_InputMethodQuery(const QDesignerResourceBrowserInterface* self, int param1);
void QDesignerResourceBrowserInterface_OnInputMethodQuery(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QVariant* QDesignerResourceBrowserInterface_QBaseInputMethodQuery(const QDesignerResourceBrowserInterface* self, int param1);
bool QDesignerResourceBrowserInterface_FocusNextPrevChild(QDesignerResourceBrowserInterface* self, bool next);
void QDesignerResourceBrowserInterface_OnFocusNextPrevChild(QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseFocusNextPrevChild(QDesignerResourceBrowserInterface* self, bool next);
bool QDesignerResourceBrowserInterface_EventFilter(QDesignerResourceBrowserInterface* self, QObject* watched, QEvent* event);
void QDesignerResourceBrowserInterface_OnEventFilter(QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseEventFilter(QDesignerResourceBrowserInterface* self, QObject* watched, QEvent* event);
void QDesignerResourceBrowserInterface_TimerEvent(QDesignerResourceBrowserInterface* self, QTimerEvent* event);
void QDesignerResourceBrowserInterface_OnTimerEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseTimerEvent(QDesignerResourceBrowserInterface* self, QTimerEvent* event);
void QDesignerResourceBrowserInterface_ChildEvent(QDesignerResourceBrowserInterface* self, QChildEvent* event);
void QDesignerResourceBrowserInterface_OnChildEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseChildEvent(QDesignerResourceBrowserInterface* self, QChildEvent* event);
void QDesignerResourceBrowserInterface_CustomEvent(QDesignerResourceBrowserInterface* self, QEvent* event);
void QDesignerResourceBrowserInterface_OnCustomEvent(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseCustomEvent(QDesignerResourceBrowserInterface* self, QEvent* event);
void QDesignerResourceBrowserInterface_ConnectNotify(QDesignerResourceBrowserInterface* self, const QMetaMethod* signal);
void QDesignerResourceBrowserInterface_OnConnectNotify(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseConnectNotify(QDesignerResourceBrowserInterface* self, const QMetaMethod* signal);
void QDesignerResourceBrowserInterface_DisconnectNotify(QDesignerResourceBrowserInterface* self, const QMetaMethod* signal);
void QDesignerResourceBrowserInterface_OnDisconnectNotify(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseDisconnectNotify(QDesignerResourceBrowserInterface* self, const QMetaMethod* signal);
void QDesignerResourceBrowserInterface_UpdateMicroFocus(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnUpdateMicroFocus(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseUpdateMicroFocus(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_Create(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnCreate(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseCreate(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_Destroy(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnDestroy(QDesignerResourceBrowserInterface* self, intptr_t slot);
void QDesignerResourceBrowserInterface_QBaseDestroy(QDesignerResourceBrowserInterface* self);
bool QDesignerResourceBrowserInterface_FocusNextChild(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnFocusNextChild(QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseFocusNextChild(QDesignerResourceBrowserInterface* self);
bool QDesignerResourceBrowserInterface_FocusPreviousChild(QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnFocusPreviousChild(QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseFocusPreviousChild(QDesignerResourceBrowserInterface* self);
QObject* QDesignerResourceBrowserInterface_Sender(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnSender(const QDesignerResourceBrowserInterface* self, intptr_t slot);
QObject* QDesignerResourceBrowserInterface_QBaseSender(const QDesignerResourceBrowserInterface* self);
int QDesignerResourceBrowserInterface_SenderSignalIndex(const QDesignerResourceBrowserInterface* self);
void QDesignerResourceBrowserInterface_OnSenderSignalIndex(const QDesignerResourceBrowserInterface* self, intptr_t slot);
int QDesignerResourceBrowserInterface_QBaseSenderSignalIndex(const QDesignerResourceBrowserInterface* self);
int QDesignerResourceBrowserInterface_Receivers(const QDesignerResourceBrowserInterface* self, const char* signal);
void QDesignerResourceBrowserInterface_OnReceivers(const QDesignerResourceBrowserInterface* self, intptr_t slot);
int QDesignerResourceBrowserInterface_QBaseReceivers(const QDesignerResourceBrowserInterface* self, const char* signal);
bool QDesignerResourceBrowserInterface_IsSignalConnected(const QDesignerResourceBrowserInterface* self, const QMetaMethod* signal);
void QDesignerResourceBrowserInterface_OnIsSignalConnected(const QDesignerResourceBrowserInterface* self, intptr_t slot);
bool QDesignerResourceBrowserInterface_QBaseIsSignalConnected(const QDesignerResourceBrowserInterface* self, const QMetaMethod* signal);
double QDesignerResourceBrowserInterface_GetDecodedMetricF(const QDesignerResourceBrowserInterface* self, int metricA, int metricB);
void QDesignerResourceBrowserInterface_OnGetDecodedMetricF(const QDesignerResourceBrowserInterface* self, intptr_t slot);
double QDesignerResourceBrowserInterface_QBaseGetDecodedMetricF(const QDesignerResourceBrowserInterface* self, int metricA, int metricB);
void QDesignerResourceBrowserInterface_Delete(QDesignerResourceBrowserInterface* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
