#pragma once
#ifndef SRC_EXTRAS_KITEMMODELSC_LIBKEXTRACOLUMNSPROXYMODEL_H
#define SRC_EXTRAS_KITEMMODELSC_LIBKEXTRACOLUMNSPROXYMODEL_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KExtraColumnsProxyModel KExtraColumnsProxyModel;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractProxyModel QAbstractProxyModel;
typedef struct QChildEvent QChildEvent;
typedef struct QDataStream QDataStream;
typedef struct QEvent QEvent;
typedef struct QIdentityProxyModel QIdentityProxyModel;
typedef struct QItemSelection QItemSelection;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QModelRoleDataSpan QModelRoleDataSpan;
typedef struct QObject QObject;
typedef struct QSize QSize;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
#endif

KExtraColumnsProxyModel* KExtraColumnsProxyModel_new();
KExtraColumnsProxyModel* KExtraColumnsProxyModel_new2(QObject* parent);
QMetaObject* KExtraColumnsProxyModel_MetaObject(const KExtraColumnsProxyModel* self);
void* KExtraColumnsProxyModel_Metacast(KExtraColumnsProxyModel* self, const char* param1);
int KExtraColumnsProxyModel_Metacall(KExtraColumnsProxyModel* self, int param1, int param2, void** param3);
void KExtraColumnsProxyModel_AppendColumn(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_RemoveExtraColumn(KExtraColumnsProxyModel* self, int idx);
QVariant* KExtraColumnsProxyModel_ExtraColumnData(const KExtraColumnsProxyModel* self, const QModelIndex* parent, int row, int extraColumn, int role);
bool KExtraColumnsProxyModel_SetExtraColumnData(KExtraColumnsProxyModel* self, const QModelIndex* parent, int row, int extraColumn, const QVariant* data, int role);
void KExtraColumnsProxyModel_ExtraColumnDataChanged(KExtraColumnsProxyModel* self, const QModelIndex* parent, int row, int extraColumn, const libqt_list /* of int */ roles);
int KExtraColumnsProxyModel_ExtraColumnForProxyColumn(const KExtraColumnsProxyModel* self, int proxyColumn);
int KExtraColumnsProxyModel_ProxyColumnForExtraColumn(const KExtraColumnsProxyModel* self, int extraColumn);
void KExtraColumnsProxyModel_SetSourceModel(KExtraColumnsProxyModel* self, QAbstractItemModel* model);
QModelIndex* KExtraColumnsProxyModel_MapToSource(const KExtraColumnsProxyModel* self, const QModelIndex* proxyIndex);
QItemSelection* KExtraColumnsProxyModel_MapSelectionToSource(const KExtraColumnsProxyModel* self, const QItemSelection* selection);
int KExtraColumnsProxyModel_ColumnCount(const KExtraColumnsProxyModel* self, const QModelIndex* parent);
QVariant* KExtraColumnsProxyModel_Data(const KExtraColumnsProxyModel* self, const QModelIndex* index, int role);
bool KExtraColumnsProxyModel_SetData(KExtraColumnsProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
QModelIndex* KExtraColumnsProxyModel_Sibling(const KExtraColumnsProxyModel* self, int row, int column, const QModelIndex* idx);
QModelIndex* KExtraColumnsProxyModel_Buddy(const KExtraColumnsProxyModel* self, const QModelIndex* index);
int KExtraColumnsProxyModel_Flags(const KExtraColumnsProxyModel* self, const QModelIndex* index);
bool KExtraColumnsProxyModel_HasChildren(const KExtraColumnsProxyModel* self, const QModelIndex* index);
QVariant* KExtraColumnsProxyModel_HeaderData(const KExtraColumnsProxyModel* self, int section, int orientation, int role);
QModelIndex* KExtraColumnsProxyModel_Index(const KExtraColumnsProxyModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* KExtraColumnsProxyModel_Parent(const KExtraColumnsProxyModel* self, const QModelIndex* child);
void KExtraColumnsProxyModel_AppendColumn1(KExtraColumnsProxyModel* self, const libqt_string header);
void KExtraColumnsProxyModel_OnMetaObject(const KExtraColumnsProxyModel* self, intptr_t slot);
QMetaObject* KExtraColumnsProxyModel_SuperMetaObject(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnMetacast(KExtraColumnsProxyModel* self, intptr_t slot);
void* KExtraColumnsProxyModel_SuperMetacast(KExtraColumnsProxyModel* self, const char* param1);
void KExtraColumnsProxyModel_OnMetacall(KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperMetacall(KExtraColumnsProxyModel* self, int param1, int param2, void** param3);
void KExtraColumnsProxyModel_OnExtraColumnData(const KExtraColumnsProxyModel* self, intptr_t slot);
QVariant* KExtraColumnsProxyModel_SuperExtraColumnData(const KExtraColumnsProxyModel* self, const QModelIndex* parent, int row, int extraColumn, int role);
void KExtraColumnsProxyModel_OnSetExtraColumnData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperSetExtraColumnData(KExtraColumnsProxyModel* self, const QModelIndex* parent, int row, int extraColumn, const QVariant* data, int role);
void KExtraColumnsProxyModel_OnSetSourceModel(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperSetSourceModel(KExtraColumnsProxyModel* self, QAbstractItemModel* model);
void KExtraColumnsProxyModel_OnMapToSource(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperMapToSource(const KExtraColumnsProxyModel* self, const QModelIndex* proxyIndex);
void KExtraColumnsProxyModel_OnMapSelectionToSource(const KExtraColumnsProxyModel* self, intptr_t slot);
QItemSelection* KExtraColumnsProxyModel_SuperMapSelectionToSource(const KExtraColumnsProxyModel* self, const QItemSelection* selection);
void KExtraColumnsProxyModel_OnColumnCount(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperColumnCount(const KExtraColumnsProxyModel* self, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnData(const KExtraColumnsProxyModel* self, intptr_t slot);
QVariant* KExtraColumnsProxyModel_SuperData(const KExtraColumnsProxyModel* self, const QModelIndex* index, int role);
void KExtraColumnsProxyModel_OnSetData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperSetData(KExtraColumnsProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
void KExtraColumnsProxyModel_OnSibling(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperSibling(const KExtraColumnsProxyModel* self, int row, int column, const QModelIndex* idx);
void KExtraColumnsProxyModel_OnBuddy(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperBuddy(const KExtraColumnsProxyModel* self, const QModelIndex* index);
void KExtraColumnsProxyModel_OnFlags(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperFlags(const KExtraColumnsProxyModel* self, const QModelIndex* index);
void KExtraColumnsProxyModel_OnHasChildren(const KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperHasChildren(const KExtraColumnsProxyModel* self, const QModelIndex* index);
void KExtraColumnsProxyModel_OnHeaderData(const KExtraColumnsProxyModel* self, intptr_t slot);
QVariant* KExtraColumnsProxyModel_SuperHeaderData(const KExtraColumnsProxyModel* self, int section, int orientation, int role);
void KExtraColumnsProxyModel_OnIndex(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperIndex(const KExtraColumnsProxyModel* self, int row, int column, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnParent(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperParent(const KExtraColumnsProxyModel* self, const QModelIndex* child);
QModelIndex* KExtraColumnsProxyModel_MapFromSource(const KExtraColumnsProxyModel* self, const QModelIndex* sourceIndex);
void KExtraColumnsProxyModel_OnMapFromSource(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperMapFromSource(const KExtraColumnsProxyModel* self, const QModelIndex* sourceIndex);
int KExtraColumnsProxyModel_RowCount(const KExtraColumnsProxyModel* self, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnRowCount(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperRowCount(const KExtraColumnsProxyModel* self, const QModelIndex* parent);
bool KExtraColumnsProxyModel_DropMimeData(KExtraColumnsProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnDropMimeData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperDropMimeData(KExtraColumnsProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
QItemSelection* KExtraColumnsProxyModel_MapSelectionFromSource(const KExtraColumnsProxyModel* self, const QItemSelection* selection);
void KExtraColumnsProxyModel_OnMapSelectionFromSource(const KExtraColumnsProxyModel* self, intptr_t slot);
QItemSelection* KExtraColumnsProxyModel_SuperMapSelectionFromSource(const KExtraColumnsProxyModel* self, const QItemSelection* selection);
libqt_list /* of QModelIndex* */ KExtraColumnsProxyModel_Match(const KExtraColumnsProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
void KExtraColumnsProxyModel_OnMatch(const KExtraColumnsProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ KExtraColumnsProxyModel_SuperMatch(const KExtraColumnsProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
bool KExtraColumnsProxyModel_InsertColumns(KExtraColumnsProxyModel* self, int column, int count, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnInsertColumns(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperInsertColumns(KExtraColumnsProxyModel* self, int column, int count, const QModelIndex* parent);
bool KExtraColumnsProxyModel_InsertRows(KExtraColumnsProxyModel* self, int row, int count, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnInsertRows(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperInsertRows(KExtraColumnsProxyModel* self, int row, int count, const QModelIndex* parent);
bool KExtraColumnsProxyModel_RemoveColumns(KExtraColumnsProxyModel* self, int column, int count, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnRemoveColumns(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperRemoveColumns(KExtraColumnsProxyModel* self, int column, int count, const QModelIndex* parent);
bool KExtraColumnsProxyModel_RemoveRows(KExtraColumnsProxyModel* self, int row, int count, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnRemoveRows(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperRemoveRows(KExtraColumnsProxyModel* self, int row, int count, const QModelIndex* parent);
bool KExtraColumnsProxyModel_MoveRows(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
void KExtraColumnsProxyModel_OnMoveRows(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperMoveRows(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
bool KExtraColumnsProxyModel_MoveColumns(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void KExtraColumnsProxyModel_OnMoveColumns(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperMoveColumns(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
bool KExtraColumnsProxyModel_Submit(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnSubmit(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperSubmit(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_Revert(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnRevert(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperRevert(KExtraColumnsProxyModel* self);
libqt_map /* of int to QVariant* */ KExtraColumnsProxyModel_ItemData(const KExtraColumnsProxyModel* self, const QModelIndex* index);
void KExtraColumnsProxyModel_OnItemData(const KExtraColumnsProxyModel* self, intptr_t slot);
libqt_map /* of int to QVariant* */ KExtraColumnsProxyModel_SuperItemData(const KExtraColumnsProxyModel* self, const QModelIndex* index);
bool KExtraColumnsProxyModel_SetItemData(KExtraColumnsProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
void KExtraColumnsProxyModel_OnSetItemData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperSetItemData(KExtraColumnsProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
bool KExtraColumnsProxyModel_SetHeaderData(KExtraColumnsProxyModel* self, int section, int orientation, const QVariant* value, int role);
void KExtraColumnsProxyModel_OnSetHeaderData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperSetHeaderData(KExtraColumnsProxyModel* self, int section, int orientation, const QVariant* value, int role);
bool KExtraColumnsProxyModel_ClearItemData(KExtraColumnsProxyModel* self, const QModelIndex* index);
void KExtraColumnsProxyModel_OnClearItemData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperClearItemData(KExtraColumnsProxyModel* self, const QModelIndex* index);
bool KExtraColumnsProxyModel_CanFetchMore(const KExtraColumnsProxyModel* self, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnCanFetchMore(const KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperCanFetchMore(const KExtraColumnsProxyModel* self, const QModelIndex* parent);
void KExtraColumnsProxyModel_FetchMore(KExtraColumnsProxyModel* self, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnFetchMore(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperFetchMore(KExtraColumnsProxyModel* self, const QModelIndex* parent);
void KExtraColumnsProxyModel_Sort(KExtraColumnsProxyModel* self, int column, int order);
void KExtraColumnsProxyModel_OnSort(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperSort(KExtraColumnsProxyModel* self, int column, int order);
QSize* KExtraColumnsProxyModel_Span(const KExtraColumnsProxyModel* self, const QModelIndex* index);
void KExtraColumnsProxyModel_OnSpan(const KExtraColumnsProxyModel* self, intptr_t slot);
QSize* KExtraColumnsProxyModel_SuperSpan(const KExtraColumnsProxyModel* self, const QModelIndex* index);
QMimeData* KExtraColumnsProxyModel_MimeData(const KExtraColumnsProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
void KExtraColumnsProxyModel_OnMimeData(const KExtraColumnsProxyModel* self, intptr_t slot);
QMimeData* KExtraColumnsProxyModel_SuperMimeData(const KExtraColumnsProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
bool KExtraColumnsProxyModel_CanDropMimeData(const KExtraColumnsProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void KExtraColumnsProxyModel_OnCanDropMimeData(const KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperCanDropMimeData(const KExtraColumnsProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
libqt_list /* of libqt_string */ KExtraColumnsProxyModel_MimeTypes(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnMimeTypes(const KExtraColumnsProxyModel* self, intptr_t slot);
libqt_list /* of libqt_string */ KExtraColumnsProxyModel_SuperMimeTypes(const KExtraColumnsProxyModel* self);
int KExtraColumnsProxyModel_SupportedDragActions(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnSupportedDragActions(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperSupportedDragActions(const KExtraColumnsProxyModel* self);
int KExtraColumnsProxyModel_SupportedDropActions(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnSupportedDropActions(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperSupportedDropActions(const KExtraColumnsProxyModel* self);
libqt_map /* of int to libqt_string */ KExtraColumnsProxyModel_RoleNames(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnRoleNames(const KExtraColumnsProxyModel* self, intptr_t slot);
libqt_map /* of int to libqt_string */ KExtraColumnsProxyModel_SuperRoleNames(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_MultiData(const KExtraColumnsProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void KExtraColumnsProxyModel_OnMultiData(const KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperMultiData(const KExtraColumnsProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void KExtraColumnsProxyModel_ResetInternalData(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnResetInternalData(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperResetInternalData(KExtraColumnsProxyModel* self);
bool KExtraColumnsProxyModel_Event(KExtraColumnsProxyModel* self, QEvent* event);
void KExtraColumnsProxyModel_OnEvent(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperEvent(KExtraColumnsProxyModel* self, QEvent* event);
bool KExtraColumnsProxyModel_EventFilter(KExtraColumnsProxyModel* self, QObject* watched, QEvent* event);
void KExtraColumnsProxyModel_OnEventFilter(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperEventFilter(KExtraColumnsProxyModel* self, QObject* watched, QEvent* event);
void KExtraColumnsProxyModel_TimerEvent(KExtraColumnsProxyModel* self, QTimerEvent* event);
void KExtraColumnsProxyModel_OnTimerEvent(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperTimerEvent(KExtraColumnsProxyModel* self, QTimerEvent* event);
void KExtraColumnsProxyModel_ChildEvent(KExtraColumnsProxyModel* self, QChildEvent* event);
void KExtraColumnsProxyModel_OnChildEvent(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperChildEvent(KExtraColumnsProxyModel* self, QChildEvent* event);
void KExtraColumnsProxyModel_CustomEvent(KExtraColumnsProxyModel* self, QEvent* event);
void KExtraColumnsProxyModel_OnCustomEvent(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperCustomEvent(KExtraColumnsProxyModel* self, QEvent* event);
void KExtraColumnsProxyModel_ConnectNotify(KExtraColumnsProxyModel* self, const QMetaMethod* signal);
void KExtraColumnsProxyModel_OnConnectNotify(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperConnectNotify(KExtraColumnsProxyModel* self, const QMetaMethod* signal);
void KExtraColumnsProxyModel_DisconnectNotify(KExtraColumnsProxyModel* self, const QMetaMethod* signal);
void KExtraColumnsProxyModel_OnDisconnectNotify(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperDisconnectNotify(KExtraColumnsProxyModel* self, const QMetaMethod* signal);
void KExtraColumnsProxyModel_SetHandleSourceLayoutChanges(KExtraColumnsProxyModel* self, bool handleSourceLayoutChanges);
void KExtraColumnsProxyModel_OnSetHandleSourceLayoutChanges(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperSetHandleSourceLayoutChanges(KExtraColumnsProxyModel* self, bool handleSourceLayoutChanges);
void KExtraColumnsProxyModel_SetHandleSourceDataChanges(KExtraColumnsProxyModel* self, bool handleSourceDataChanges);
void KExtraColumnsProxyModel_OnSetHandleSourceDataChanges(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperSetHandleSourceDataChanges(KExtraColumnsProxyModel* self, bool handleSourceDataChanges);
QModelIndex* KExtraColumnsProxyModel_CreateSourceIndex(const KExtraColumnsProxyModel* self, int row, int col, void* internalPtr);
void KExtraColumnsProxyModel_OnCreateSourceIndex(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperCreateSourceIndex(const KExtraColumnsProxyModel* self, int row, int col, void* internalPtr);
QModelIndex* KExtraColumnsProxyModel_CreateIndex(const KExtraColumnsProxyModel* self, int row, int column);
void KExtraColumnsProxyModel_OnCreateIndex(const KExtraColumnsProxyModel* self, intptr_t slot);
QModelIndex* KExtraColumnsProxyModel_SuperCreateIndex(const KExtraColumnsProxyModel* self, int row, int column);
void KExtraColumnsProxyModel_EncodeData(const KExtraColumnsProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
void KExtraColumnsProxyModel_OnEncodeData(const KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEncodeData(const KExtraColumnsProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
bool KExtraColumnsProxyModel_DecodeData(KExtraColumnsProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void KExtraColumnsProxyModel_OnDecodeData(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperDecodeData(KExtraColumnsProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void KExtraColumnsProxyModel_BeginInsertRows(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_OnBeginInsertRows(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperBeginInsertRows(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_EndInsertRows(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndInsertRows(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndInsertRows(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_BeginRemoveRows(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_OnBeginRemoveRows(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperBeginRemoveRows(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_EndRemoveRows(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndRemoveRows(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndRemoveRows(KExtraColumnsProxyModel* self);
bool KExtraColumnsProxyModel_BeginMoveRows(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void KExtraColumnsProxyModel_OnBeginMoveRows(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperBeginMoveRows(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void KExtraColumnsProxyModel_EndMoveRows(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndMoveRows(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndMoveRows(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_BeginInsertColumns(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_OnBeginInsertColumns(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperBeginInsertColumns(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_EndInsertColumns(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndInsertColumns(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndInsertColumns(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_BeginRemoveColumns(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_OnBeginRemoveColumns(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperBeginRemoveColumns(KExtraColumnsProxyModel* self, const QModelIndex* parent, int first, int last);
void KExtraColumnsProxyModel_EndRemoveColumns(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndRemoveColumns(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndRemoveColumns(KExtraColumnsProxyModel* self);
bool KExtraColumnsProxyModel_BeginMoveColumns(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void KExtraColumnsProxyModel_OnBeginMoveColumns(KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperBeginMoveColumns(KExtraColumnsProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void KExtraColumnsProxyModel_EndMoveColumns(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndMoveColumns(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndMoveColumns(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_BeginResetModel(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnBeginResetModel(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperBeginResetModel(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_EndResetModel(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnEndResetModel(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperEndResetModel(KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_ChangePersistentIndex(KExtraColumnsProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void KExtraColumnsProxyModel_OnChangePersistentIndex(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperChangePersistentIndex(KExtraColumnsProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void KExtraColumnsProxyModel_ChangePersistentIndexList(KExtraColumnsProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
void KExtraColumnsProxyModel_OnChangePersistentIndexList(KExtraColumnsProxyModel* self, intptr_t slot);
void KExtraColumnsProxyModel_SuperChangePersistentIndexList(KExtraColumnsProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
libqt_list /* of QModelIndex* */ KExtraColumnsProxyModel_PersistentIndexList(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnPersistentIndexList(const KExtraColumnsProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ KExtraColumnsProxyModel_SuperPersistentIndexList(const KExtraColumnsProxyModel* self);
QObject* KExtraColumnsProxyModel_Sender(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnSender(const KExtraColumnsProxyModel* self, intptr_t slot);
QObject* KExtraColumnsProxyModel_SuperSender(const KExtraColumnsProxyModel* self);
int KExtraColumnsProxyModel_SenderSignalIndex(const KExtraColumnsProxyModel* self);
void KExtraColumnsProxyModel_OnSenderSignalIndex(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperSenderSignalIndex(const KExtraColumnsProxyModel* self);
int KExtraColumnsProxyModel_Receivers(const KExtraColumnsProxyModel* self, const char* signal);
void KExtraColumnsProxyModel_OnReceivers(const KExtraColumnsProxyModel* self, intptr_t slot);
int KExtraColumnsProxyModel_SuperReceivers(const KExtraColumnsProxyModel* self, const char* signal);
bool KExtraColumnsProxyModel_IsSignalConnected(const KExtraColumnsProxyModel* self, const QMetaMethod* signal);
void KExtraColumnsProxyModel_OnIsSignalConnected(const KExtraColumnsProxyModel* self, intptr_t slot);
bool KExtraColumnsProxyModel_SuperIsSignalConnected(const KExtraColumnsProxyModel* self, const QMetaMethod* signal);
void KExtraColumnsProxyModel_Delete(KExtraColumnsProxyModel* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
