#pragma once
#ifndef SRC_EXTRAS_KPARTSC_LIBMAINWINDOW_H
#define SRC_EXTRAS_KPARTSC_LIBMAINWINDOW_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
typedef KParts::MainWindow KParts__MainWindow;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_KParts__Part)
typedef KParts::Part KParts__Part;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_KParts__PartBase)
typedef KParts::PartBase KParts__PartBase;
#endif
#else
typedef struct KActionCollection KActionCollection;
typedef struct KConfig KConfig;
typedef struct KConfigGroup KConfigGroup;
typedef struct KMainWindow KMainWindow;
typedef struct KParts__MainWindow KParts__MainWindow;
typedef struct KParts__Part KParts__Part;
typedef struct KParts__PartBase KParts__PartBase;
typedef struct KXMLGUIBuilder KXMLGUIBuilder;
typedef struct KXMLGUIClient KXMLGUIClient;
typedef struct KXMLGUIFactory KXMLGUIFactory;
typedef struct KXmlGuiWindow KXmlGuiWindow;
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDomDocument QDomDocument;
typedef struct QDomElement QDomElement;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMainWindow QMainWindow;
typedef struct QMenu QMenu;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KParts__MainWindow* KParts__MainWindow_new(QWidget* parent);
KParts__MainWindow* KParts__MainWindow_new2();
KParts__MainWindow* KParts__MainWindow_new3(QWidget* parent, int f);
QMetaObject* KParts__MainWindow_MetaObject(const KParts__MainWindow* self);
void* KParts__MainWindow_Metacast(KParts__MainWindow* self, const char* param1);
int KParts__MainWindow_Metacall(KParts__MainWindow* self, int param1, int param2, void** param3);
void KParts__MainWindow_ConfigureToolbars(KParts__MainWindow* self);
void KParts__MainWindow_SlotSetStatusBarText(KParts__MainWindow* self, const libqt_string param1);
void KParts__MainWindow_SaveNewToolbarConfig(KParts__MainWindow* self);
void KParts__MainWindow_CreateShellGUI(KParts__MainWindow* self, bool create);
void KParts__MainWindow_OnMetaObject(const KParts__MainWindow* self, intptr_t slot);
QMetaObject* KParts__MainWindow_SuperMetaObject(const KParts__MainWindow* self);
void KParts__MainWindow_OnMetacast(KParts__MainWindow* self, intptr_t slot);
void* KParts__MainWindow_SuperMetacast(KParts__MainWindow* self, const char* param1);
void KParts__MainWindow_OnMetacall(KParts__MainWindow* self, intptr_t slot);
int KParts__MainWindow_SuperMetacall(KParts__MainWindow* self, int param1, int param2, void** param3);
void KParts__MainWindow_OnConfigureToolbars(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperConfigureToolbars(KParts__MainWindow* self);
void KParts__MainWindow_OnSlotSetStatusBarText(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSlotSetStatusBarText(KParts__MainWindow* self, const libqt_string param1);
void KParts__MainWindow_OnSaveNewToolbarConfig(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSaveNewToolbarConfig(KParts__MainWindow* self);
void KParts__MainWindow_OnCreateShellGUI(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperCreateShellGUI(KParts__MainWindow* self, bool create);
KXMLGUIFactory* KParts__MainWindow_GuiFactory(KParts__MainWindow* self);
void KParts__MainWindow_OnGuiFactory(KParts__MainWindow* self, intptr_t slot);
KXMLGUIFactory* KParts__MainWindow_SuperGuiFactory(KParts__MainWindow* self);
void KParts__MainWindow_ApplyMainWindowSettings(KParts__MainWindow* self, const KConfigGroup* config);
void KParts__MainWindow_OnApplyMainWindowSettings(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperApplyMainWindowSettings(KParts__MainWindow* self, const KConfigGroup* config);
void KParts__MainWindow_SlotStateChanged(KParts__MainWindow* self, const libqt_string newstate);
void KParts__MainWindow_OnSlotStateChanged(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSlotStateChanged(KParts__MainWindow* self, const libqt_string newstate);
bool KParts__MainWindow_Event(KParts__MainWindow* self, QEvent* event);
void KParts__MainWindow_OnEvent(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperEvent(KParts__MainWindow* self, QEvent* event);
void KParts__MainWindow_SetCaption(KParts__MainWindow* self, const libqt_string caption);
void KParts__MainWindow_OnSetCaption(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetCaption(KParts__MainWindow* self, const libqt_string caption);
void KParts__MainWindow_SetPlainCaption(KParts__MainWindow* self, const libqt_string caption);
void KParts__MainWindow_OnSetPlainCaption(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetPlainCaption(KParts__MainWindow* self, const libqt_string caption);
void KParts__MainWindow_KeyPressEvent(KParts__MainWindow* self, QKeyEvent* keyEvent);
void KParts__MainWindow_OnKeyPressEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperKeyPressEvent(KParts__MainWindow* self, QKeyEvent* keyEvent);
void KParts__MainWindow_CloseEvent(KParts__MainWindow* self, QCloseEvent* param1);
void KParts__MainWindow_OnCloseEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperCloseEvent(KParts__MainWindow* self, QCloseEvent* param1);
bool KParts__MainWindow_QueryClose(KParts__MainWindow* self);
void KParts__MainWindow_OnQueryClose(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperQueryClose(KParts__MainWindow* self);
void KParts__MainWindow_SaveProperties(KParts__MainWindow* self, KConfigGroup* param1);
void KParts__MainWindow_OnSaveProperties(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSaveProperties(KParts__MainWindow* self, KConfigGroup* param1);
void KParts__MainWindow_ReadProperties(KParts__MainWindow* self, const KConfigGroup* param1);
void KParts__MainWindow_OnReadProperties(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperReadProperties(KParts__MainWindow* self, const KConfigGroup* param1);
void KParts__MainWindow_SaveGlobalProperties(KParts__MainWindow* self, KConfig* sessionConfig);
void KParts__MainWindow_OnSaveGlobalProperties(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSaveGlobalProperties(KParts__MainWindow* self, KConfig* sessionConfig);
void KParts__MainWindow_ReadGlobalProperties(KParts__MainWindow* self, KConfig* sessionConfig);
void KParts__MainWindow_OnReadGlobalProperties(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperReadGlobalProperties(KParts__MainWindow* self, KConfig* sessionConfig);
QMenu* KParts__MainWindow_CreatePopupMenu(KParts__MainWindow* self);
void KParts__MainWindow_OnCreatePopupMenu(KParts__MainWindow* self, intptr_t slot);
QMenu* KParts__MainWindow_SuperCreatePopupMenu(KParts__MainWindow* self);
void KParts__MainWindow_ContextMenuEvent(KParts__MainWindow* self, QContextMenuEvent* event);
void KParts__MainWindow_OnContextMenuEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperContextMenuEvent(KParts__MainWindow* self, QContextMenuEvent* event);
int KParts__MainWindow_DevType(const KParts__MainWindow* self);
void KParts__MainWindow_OnDevType(const KParts__MainWindow* self, intptr_t slot);
int KParts__MainWindow_SuperDevType(const KParts__MainWindow* self);
void KParts__MainWindow_SetVisible(KParts__MainWindow* self, bool visible);
void KParts__MainWindow_OnSetVisible(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetVisible(KParts__MainWindow* self, bool visible);
QSize* KParts__MainWindow_SizeHint(const KParts__MainWindow* self);
void KParts__MainWindow_OnSizeHint(const KParts__MainWindow* self, intptr_t slot);
QSize* KParts__MainWindow_SuperSizeHint(const KParts__MainWindow* self);
QSize* KParts__MainWindow_MinimumSizeHint(const KParts__MainWindow* self);
void KParts__MainWindow_OnMinimumSizeHint(const KParts__MainWindow* self, intptr_t slot);
QSize* KParts__MainWindow_SuperMinimumSizeHint(const KParts__MainWindow* self);
int KParts__MainWindow_HeightForWidth(const KParts__MainWindow* self, int param1);
void KParts__MainWindow_OnHeightForWidth(const KParts__MainWindow* self, intptr_t slot);
int KParts__MainWindow_SuperHeightForWidth(const KParts__MainWindow* self, int param1);
bool KParts__MainWindow_HasHeightForWidth(const KParts__MainWindow* self);
void KParts__MainWindow_OnHasHeightForWidth(const KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperHasHeightForWidth(const KParts__MainWindow* self);
QPaintEngine* KParts__MainWindow_PaintEngine(const KParts__MainWindow* self);
void KParts__MainWindow_OnPaintEngine(const KParts__MainWindow* self, intptr_t slot);
QPaintEngine* KParts__MainWindow_SuperPaintEngine(const KParts__MainWindow* self);
void KParts__MainWindow_MousePressEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_OnMousePressEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperMousePressEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_MouseReleaseEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_OnMouseReleaseEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperMouseReleaseEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_MouseDoubleClickEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_OnMouseDoubleClickEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperMouseDoubleClickEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_MouseMoveEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_OnMouseMoveEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperMouseMoveEvent(KParts__MainWindow* self, QMouseEvent* event);
void KParts__MainWindow_WheelEvent(KParts__MainWindow* self, QWheelEvent* event);
void KParts__MainWindow_OnWheelEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperWheelEvent(KParts__MainWindow* self, QWheelEvent* event);
void KParts__MainWindow_KeyReleaseEvent(KParts__MainWindow* self, QKeyEvent* event);
void KParts__MainWindow_OnKeyReleaseEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperKeyReleaseEvent(KParts__MainWindow* self, QKeyEvent* event);
void KParts__MainWindow_FocusInEvent(KParts__MainWindow* self, QFocusEvent* event);
void KParts__MainWindow_OnFocusInEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperFocusInEvent(KParts__MainWindow* self, QFocusEvent* event);
void KParts__MainWindow_FocusOutEvent(KParts__MainWindow* self, QFocusEvent* event);
void KParts__MainWindow_OnFocusOutEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperFocusOutEvent(KParts__MainWindow* self, QFocusEvent* event);
void KParts__MainWindow_EnterEvent(KParts__MainWindow* self, QEnterEvent* event);
void KParts__MainWindow_OnEnterEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperEnterEvent(KParts__MainWindow* self, QEnterEvent* event);
void KParts__MainWindow_LeaveEvent(KParts__MainWindow* self, QEvent* event);
void KParts__MainWindow_OnLeaveEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperLeaveEvent(KParts__MainWindow* self, QEvent* event);
void KParts__MainWindow_PaintEvent(KParts__MainWindow* self, QPaintEvent* event);
void KParts__MainWindow_OnPaintEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperPaintEvent(KParts__MainWindow* self, QPaintEvent* event);
void KParts__MainWindow_MoveEvent(KParts__MainWindow* self, QMoveEvent* event);
void KParts__MainWindow_OnMoveEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperMoveEvent(KParts__MainWindow* self, QMoveEvent* event);
void KParts__MainWindow_ResizeEvent(KParts__MainWindow* self, QResizeEvent* event);
void KParts__MainWindow_OnResizeEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperResizeEvent(KParts__MainWindow* self, QResizeEvent* event);
void KParts__MainWindow_TabletEvent(KParts__MainWindow* self, QTabletEvent* event);
void KParts__MainWindow_OnTabletEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperTabletEvent(KParts__MainWindow* self, QTabletEvent* event);
void KParts__MainWindow_ActionEvent(KParts__MainWindow* self, QActionEvent* event);
void KParts__MainWindow_OnActionEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperActionEvent(KParts__MainWindow* self, QActionEvent* event);
void KParts__MainWindow_DragEnterEvent(KParts__MainWindow* self, QDragEnterEvent* event);
void KParts__MainWindow_OnDragEnterEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperDragEnterEvent(KParts__MainWindow* self, QDragEnterEvent* event);
void KParts__MainWindow_DragMoveEvent(KParts__MainWindow* self, QDragMoveEvent* event);
void KParts__MainWindow_OnDragMoveEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperDragMoveEvent(KParts__MainWindow* self, QDragMoveEvent* event);
void KParts__MainWindow_DragLeaveEvent(KParts__MainWindow* self, QDragLeaveEvent* event);
void KParts__MainWindow_OnDragLeaveEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperDragLeaveEvent(KParts__MainWindow* self, QDragLeaveEvent* event);
void KParts__MainWindow_DropEvent(KParts__MainWindow* self, QDropEvent* event);
void KParts__MainWindow_OnDropEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperDropEvent(KParts__MainWindow* self, QDropEvent* event);
void KParts__MainWindow_ShowEvent(KParts__MainWindow* self, QShowEvent* event);
void KParts__MainWindow_OnShowEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperShowEvent(KParts__MainWindow* self, QShowEvent* event);
void KParts__MainWindow_HideEvent(KParts__MainWindow* self, QHideEvent* event);
void KParts__MainWindow_OnHideEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperHideEvent(KParts__MainWindow* self, QHideEvent* event);
bool KParts__MainWindow_NativeEvent(KParts__MainWindow* self, const libqt_string eventType, void* message, intptr_t* result);
void KParts__MainWindow_OnNativeEvent(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperNativeEvent(KParts__MainWindow* self, const libqt_string eventType, void* message, intptr_t* result);
void KParts__MainWindow_ChangeEvent(KParts__MainWindow* self, QEvent* param1);
void KParts__MainWindow_OnChangeEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperChangeEvent(KParts__MainWindow* self, QEvent* param1);
int KParts__MainWindow_Metric(const KParts__MainWindow* self, int param1);
void KParts__MainWindow_OnMetric(const KParts__MainWindow* self, intptr_t slot);
int KParts__MainWindow_SuperMetric(const KParts__MainWindow* self, int param1);
void KParts__MainWindow_InitPainter(const KParts__MainWindow* self, QPainter* painter);
void KParts__MainWindow_OnInitPainter(const KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperInitPainter(const KParts__MainWindow* self, QPainter* painter);
QPaintDevice* KParts__MainWindow_Redirected(const KParts__MainWindow* self, QPoint* offset);
void KParts__MainWindow_OnRedirected(const KParts__MainWindow* self, intptr_t slot);
QPaintDevice* KParts__MainWindow_SuperRedirected(const KParts__MainWindow* self, QPoint* offset);
QPainter* KParts__MainWindow_SharedPainter(const KParts__MainWindow* self);
void KParts__MainWindow_OnSharedPainter(const KParts__MainWindow* self, intptr_t slot);
QPainter* KParts__MainWindow_SuperSharedPainter(const KParts__MainWindow* self);
void KParts__MainWindow_InputMethodEvent(KParts__MainWindow* self, QInputMethodEvent* param1);
void KParts__MainWindow_OnInputMethodEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperInputMethodEvent(KParts__MainWindow* self, QInputMethodEvent* param1);
QVariant* KParts__MainWindow_InputMethodQuery(const KParts__MainWindow* self, int param1);
void KParts__MainWindow_OnInputMethodQuery(const KParts__MainWindow* self, intptr_t slot);
QVariant* KParts__MainWindow_SuperInputMethodQuery(const KParts__MainWindow* self, int param1);
bool KParts__MainWindow_FocusNextPrevChild(KParts__MainWindow* self, bool next);
void KParts__MainWindow_OnFocusNextPrevChild(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperFocusNextPrevChild(KParts__MainWindow* self, bool next);
bool KParts__MainWindow_EventFilter(KParts__MainWindow* self, QObject* watched, QEvent* event);
void KParts__MainWindow_OnEventFilter(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperEventFilter(KParts__MainWindow* self, QObject* watched, QEvent* event);
void KParts__MainWindow_TimerEvent(KParts__MainWindow* self, QTimerEvent* event);
void KParts__MainWindow_OnTimerEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperTimerEvent(KParts__MainWindow* self, QTimerEvent* event);
void KParts__MainWindow_ChildEvent(KParts__MainWindow* self, QChildEvent* event);
void KParts__MainWindow_OnChildEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperChildEvent(KParts__MainWindow* self, QChildEvent* event);
void KParts__MainWindow_CustomEvent(KParts__MainWindow* self, QEvent* event);
void KParts__MainWindow_OnCustomEvent(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperCustomEvent(KParts__MainWindow* self, QEvent* event);
void KParts__MainWindow_ConnectNotify(KParts__MainWindow* self, const QMetaMethod* signal);
void KParts__MainWindow_OnConnectNotify(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperConnectNotify(KParts__MainWindow* self, const QMetaMethod* signal);
void KParts__MainWindow_DisconnectNotify(KParts__MainWindow* self, const QMetaMethod* signal);
void KParts__MainWindow_OnDisconnectNotify(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperDisconnectNotify(KParts__MainWindow* self, const QMetaMethod* signal);
libqt_list /* of libqt_string */ KParts__MainWindow_ContainerTags(const KParts__MainWindow* self);
void KParts__MainWindow_OnContainerTags(const KParts__MainWindow* self, intptr_t slot);
libqt_list /* of libqt_string */ KParts__MainWindow_SuperContainerTags(const KParts__MainWindow* self);
QWidget* KParts__MainWindow_CreateContainer(KParts__MainWindow* self, QWidget* parent, int index, const QDomElement* element, QAction** containerAction);
void KParts__MainWindow_OnCreateContainer(KParts__MainWindow* self, intptr_t slot);
QWidget* KParts__MainWindow_SuperCreateContainer(KParts__MainWindow* self, QWidget* parent, int index, const QDomElement* element, QAction** containerAction);
void KParts__MainWindow_RemoveContainer(KParts__MainWindow* self, QWidget* container, QWidget* parent, QDomElement* element, QAction* containerAction);
void KParts__MainWindow_OnRemoveContainer(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperRemoveContainer(KParts__MainWindow* self, QWidget* container, QWidget* parent, QDomElement* element, QAction* containerAction);
libqt_list /* of libqt_string */ KParts__MainWindow_CustomTags(const KParts__MainWindow* self);
void KParts__MainWindow_OnCustomTags(const KParts__MainWindow* self, intptr_t slot);
libqt_list /* of libqt_string */ KParts__MainWindow_SuperCustomTags(const KParts__MainWindow* self);
QAction* KParts__MainWindow_CreateCustomElement(KParts__MainWindow* self, QWidget* parent, int index, const QDomElement* element);
void KParts__MainWindow_OnCreateCustomElement(KParts__MainWindow* self, intptr_t slot);
QAction* KParts__MainWindow_SuperCreateCustomElement(KParts__MainWindow* self, QWidget* parent, int index, const QDomElement* element);
void KParts__MainWindow_FinalizeGUI(KParts__MainWindow* self, KXMLGUIClient* client);
void KParts__MainWindow_OnFinalizeGUI(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperFinalizeGUI(KParts__MainWindow* self, KXMLGUIClient* client);
QAction* KParts__MainWindow_Action2(const KParts__MainWindow* self, const QDomElement* element);
void KParts__MainWindow_OnAction2(const KParts__MainWindow* self, intptr_t slot);
QAction* KParts__MainWindow_SuperAction2(const KParts__MainWindow* self, const QDomElement* element);
KActionCollection* KParts__MainWindow_ActionCollection(const KParts__MainWindow* self);
void KParts__MainWindow_OnActionCollection(const KParts__MainWindow* self, intptr_t slot);
KActionCollection* KParts__MainWindow_SuperActionCollection(const KParts__MainWindow* self);
libqt_string KParts__MainWindow_ComponentName(const KParts__MainWindow* self);
void KParts__MainWindow_OnComponentName(const KParts__MainWindow* self, intptr_t slot);
libqt_string KParts__MainWindow_SuperComponentName(const KParts__MainWindow* self);
QDomDocument* KParts__MainWindow_DomDocument(const KParts__MainWindow* self);
void KParts__MainWindow_OnDomDocument(const KParts__MainWindow* self, intptr_t slot);
QDomDocument* KParts__MainWindow_SuperDomDocument(const KParts__MainWindow* self);
libqt_string KParts__MainWindow_XmlFile(const KParts__MainWindow* self);
void KParts__MainWindow_OnXmlFile(const KParts__MainWindow* self, intptr_t slot);
libqt_string KParts__MainWindow_SuperXmlFile(const KParts__MainWindow* self);
libqt_string KParts__MainWindow_LocalXMLFile(const KParts__MainWindow* self);
void KParts__MainWindow_OnLocalXMLFile(const KParts__MainWindow* self, intptr_t slot);
libqt_string KParts__MainWindow_SuperLocalXMLFile(const KParts__MainWindow* self);
void KParts__MainWindow_SetComponentName(KParts__MainWindow* self, const libqt_string componentName, const libqt_string componentDisplayName);
void KParts__MainWindow_OnSetComponentName(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetComponentName(KParts__MainWindow* self, const libqt_string componentName, const libqt_string componentDisplayName);
void KParts__MainWindow_SetXMLFile(KParts__MainWindow* self, const libqt_string file, bool merge, bool setXMLDoc);
void KParts__MainWindow_OnSetXMLFile(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetXMLFile(KParts__MainWindow* self, const libqt_string file, bool merge, bool setXMLDoc);
void KParts__MainWindow_SetLocalXMLFile(KParts__MainWindow* self, const libqt_string file);
void KParts__MainWindow_OnSetLocalXMLFile(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetLocalXMLFile(KParts__MainWindow* self, const libqt_string file);
void KParts__MainWindow_SetXML(KParts__MainWindow* self, const libqt_string document, bool merge);
void KParts__MainWindow_OnSetXML(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetXML(KParts__MainWindow* self, const libqt_string document, bool merge);
void KParts__MainWindow_SetDOMDocument(KParts__MainWindow* self, const QDomDocument* document, bool merge);
void KParts__MainWindow_OnSetDOMDocument(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetDOMDocument(KParts__MainWindow* self, const QDomDocument* document, bool merge);
void KParts__MainWindow_StateChanged(KParts__MainWindow* self, const libqt_string newstate, int reverse);
void KParts__MainWindow_OnStateChanged(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperStateChanged(KParts__MainWindow* self, const libqt_string newstate, int reverse);
void KParts__MainWindow_CreateGUI(KParts__MainWindow* self, KParts__Part* part);
void KParts__MainWindow_OnCreateGUI(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperCreateGUI(KParts__MainWindow* self, KParts__Part* part);
void KParts__MainWindow_SetWindowTitleHandling(KParts__MainWindow* self, bool enabled);
void KParts__MainWindow_OnSetWindowTitleHandling(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSetWindowTitleHandling(KParts__MainWindow* self, bool enabled);
void KParts__MainWindow_CheckAmbiguousShortcuts(KParts__MainWindow* self);
void KParts__MainWindow_OnCheckAmbiguousShortcuts(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperCheckAmbiguousShortcuts(KParts__MainWindow* self);
void KParts__MainWindow_SavePropertiesInternal(KParts__MainWindow* self, KConfig* param1, int param2);
void KParts__MainWindow_OnSavePropertiesInternal(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSavePropertiesInternal(KParts__MainWindow* self, KConfig* param1, int param2);
bool KParts__MainWindow_ReadPropertiesInternal(KParts__MainWindow* self, KConfig* param1, int param2);
void KParts__MainWindow_OnReadPropertiesInternal(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperReadPropertiesInternal(KParts__MainWindow* self, KConfig* param1, int param2);
bool KParts__MainWindow_SettingsDirty(const KParts__MainWindow* self);
void KParts__MainWindow_OnSettingsDirty(const KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperSettingsDirty(const KParts__MainWindow* self);
void KParts__MainWindow_SaveAutoSaveSettings(KParts__MainWindow* self);
void KParts__MainWindow_OnSaveAutoSaveSettings(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperSaveAutoSaveSettings(KParts__MainWindow* self);
void KParts__MainWindow_UpdateMicroFocus(KParts__MainWindow* self);
void KParts__MainWindow_OnUpdateMicroFocus(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperUpdateMicroFocus(KParts__MainWindow* self);
void KParts__MainWindow_Create(KParts__MainWindow* self);
void KParts__MainWindow_OnCreate(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperCreate(KParts__MainWindow* self);
void KParts__MainWindow_Destroy(KParts__MainWindow* self);
void KParts__MainWindow_OnDestroy(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperDestroy(KParts__MainWindow* self);
bool KParts__MainWindow_FocusNextChild(KParts__MainWindow* self);
void KParts__MainWindow_OnFocusNextChild(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperFocusNextChild(KParts__MainWindow* self);
bool KParts__MainWindow_FocusPreviousChild(KParts__MainWindow* self);
void KParts__MainWindow_OnFocusPreviousChild(KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperFocusPreviousChild(KParts__MainWindow* self);
QObject* KParts__MainWindow_Sender(const KParts__MainWindow* self);
void KParts__MainWindow_OnSender(const KParts__MainWindow* self, intptr_t slot);
QObject* KParts__MainWindow_SuperSender(const KParts__MainWindow* self);
int KParts__MainWindow_SenderSignalIndex(const KParts__MainWindow* self);
void KParts__MainWindow_OnSenderSignalIndex(const KParts__MainWindow* self, intptr_t slot);
int KParts__MainWindow_SuperSenderSignalIndex(const KParts__MainWindow* self);
int KParts__MainWindow_Receivers(const KParts__MainWindow* self, const char* signal);
void KParts__MainWindow_OnReceivers(const KParts__MainWindow* self, intptr_t slot);
int KParts__MainWindow_SuperReceivers(const KParts__MainWindow* self, const char* signal);
bool KParts__MainWindow_IsSignalConnected(const KParts__MainWindow* self, const QMetaMethod* signal);
void KParts__MainWindow_OnIsSignalConnected(const KParts__MainWindow* self, intptr_t slot);
bool KParts__MainWindow_SuperIsSignalConnected(const KParts__MainWindow* self, const QMetaMethod* signal);
double KParts__MainWindow_GetDecodedMetricF(const KParts__MainWindow* self, int metricA, int metricB);
void KParts__MainWindow_OnGetDecodedMetricF(const KParts__MainWindow* self, intptr_t slot);
double KParts__MainWindow_SuperGetDecodedMetricF(const KParts__MainWindow* self, int metricA, int metricB);
libqt_string KParts__MainWindow_StandardsXmlFileLocation(KParts__MainWindow* self);
void KParts__MainWindow_OnStandardsXmlFileLocation(KParts__MainWindow* self, intptr_t slot);
libqt_string KParts__MainWindow_SuperStandardsXmlFileLocation(KParts__MainWindow* self);
void KParts__MainWindow_LoadStandardsXmlFile(KParts__MainWindow* self);
void KParts__MainWindow_OnLoadStandardsXmlFile(KParts__MainWindow* self, intptr_t slot);
void KParts__MainWindow_SuperLoadStandardsXmlFile(KParts__MainWindow* self);
void KParts__MainWindow_Delete(KParts__MainWindow* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
