#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKTIMECOMBOBOX_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKTIMECOMBOBOX_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KTimeComboBox KTimeComboBox;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTime QTime;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KTimeComboBox* KTimeComboBox_new(QWidget* parent);
KTimeComboBox* KTimeComboBox_new2();
QMetaObject* KTimeComboBox_MetaObject(const KTimeComboBox* self);
void* KTimeComboBox_Metacast(KTimeComboBox* self, const char* param1);
int KTimeComboBox_Metacall(KTimeComboBox* self, int param1, int param2, void** param3);
QTime* KTimeComboBox_Time(const KTimeComboBox* self);
bool KTimeComboBox_IsValid(const KTimeComboBox* self);
bool KTimeComboBox_IsNull(const KTimeComboBox* self);
int KTimeComboBox_Options(const KTimeComboBox* self);
int KTimeComboBox_DisplayFormat(const KTimeComboBox* self);
QTime* KTimeComboBox_MinimumTime(const KTimeComboBox* self);
void KTimeComboBox_ResetMinimumTime(KTimeComboBox* self);
QTime* KTimeComboBox_MaximumTime(const KTimeComboBox* self);
void KTimeComboBox_ResetMaximumTime(KTimeComboBox* self);
void KTimeComboBox_SetTimeRange(KTimeComboBox* self, const QTime* minTime, const QTime* maxTime);
void KTimeComboBox_ResetTimeRange(KTimeComboBox* self);
int KTimeComboBox_TimeListInterval(const KTimeComboBox* self);
libqt_list /* of QTime* */ KTimeComboBox_TimeList(const KTimeComboBox* self);
void KTimeComboBox_TimeEntered(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_Connect_TimeEntered(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_TimeChanged(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_Connect_TimeChanged(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_TimeEdited(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_Connect_TimeEdited(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SetTime(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_SetOptions(KTimeComboBox* self, int options);
void KTimeComboBox_SetDisplayFormat(KTimeComboBox* self, int format);
void KTimeComboBox_SetMinimumTime(KTimeComboBox* self, const QTime* minTime);
void KTimeComboBox_SetMaximumTime(KTimeComboBox* self, const QTime* maxTime);
void KTimeComboBox_SetTimeListInterval(KTimeComboBox* self, int minutes);
void KTimeComboBox_SetTimeList(KTimeComboBox* self, libqt_list /* of QTime* */ timeList);
bool KTimeComboBox_EventFilter(KTimeComboBox* self, QObject* object, QEvent* event);
void KTimeComboBox_ShowPopup(KTimeComboBox* self);
void KTimeComboBox_HidePopup(KTimeComboBox* self);
void KTimeComboBox_MousePressEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_WheelEvent(KTimeComboBox* self, QWheelEvent* event);
void KTimeComboBox_KeyPressEvent(KTimeComboBox* self, QKeyEvent* event);
void KTimeComboBox_FocusInEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_FocusOutEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_ResizeEvent(KTimeComboBox* self, QResizeEvent* event);
void KTimeComboBox_AssignTime(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_SetTimeRange3(KTimeComboBox* self, const QTime* minTime, const QTime* maxTime, const libqt_string minWarnMsg);
void KTimeComboBox_SetTimeRange4(KTimeComboBox* self, const QTime* minTime, const QTime* maxTime, const libqt_string minWarnMsg, const libqt_string maxWarnMsg);
void KTimeComboBox_SetMinimumTime2(KTimeComboBox* self, const QTime* minTime, const libqt_string minWarnMsg);
void KTimeComboBox_SetMaximumTime2(KTimeComboBox* self, const QTime* maxTime, const libqt_string maxWarnMsg);
void KTimeComboBox_SetTimeList2(KTimeComboBox* self, libqt_list /* of QTime* */ timeList, const libqt_string minWarnMsg);
void KTimeComboBox_SetTimeList3(KTimeComboBox* self, libqt_list /* of QTime* */ timeList, const libqt_string minWarnMsg, const libqt_string maxWarnMsg);
void KTimeComboBox_OnMetaObject(const KTimeComboBox* self, intptr_t slot);
QMetaObject* KTimeComboBox_SuperMetaObject(const KTimeComboBox* self);
void KTimeComboBox_OnMetacast(KTimeComboBox* self, intptr_t slot);
void* KTimeComboBox_SuperMetacast(KTimeComboBox* self, const char* param1);
void KTimeComboBox_OnMetacall(KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_SuperMetacall(KTimeComboBox* self, int param1, int param2, void** param3);
void KTimeComboBox_OnEventFilter(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperEventFilter(KTimeComboBox* self, QObject* object, QEvent* event);
void KTimeComboBox_OnShowPopup(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperShowPopup(KTimeComboBox* self);
void KTimeComboBox_OnHidePopup(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperHidePopup(KTimeComboBox* self);
void KTimeComboBox_OnMousePressEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperMousePressEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_OnWheelEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperWheelEvent(KTimeComboBox* self, QWheelEvent* event);
void KTimeComboBox_OnKeyPressEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperKeyPressEvent(KTimeComboBox* self, QKeyEvent* event);
void KTimeComboBox_OnFocusInEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperFocusInEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_OnFocusOutEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperFocusOutEvent(KTimeComboBox* self, QFocusEvent* event);
void KTimeComboBox_OnResizeEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperResizeEvent(KTimeComboBox* self, QResizeEvent* event);
void KTimeComboBox_OnAssignTime(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperAssignTime(KTimeComboBox* self, const QTime* time);
void KTimeComboBox_SetModel(KTimeComboBox* self, QAbstractItemModel* model);
void KTimeComboBox_OnSetModel(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperSetModel(KTimeComboBox* self, QAbstractItemModel* model);
QSize* KTimeComboBox_SizeHint(const KTimeComboBox* self);
void KTimeComboBox_OnSizeHint(const KTimeComboBox* self, intptr_t slot);
QSize* KTimeComboBox_SuperSizeHint(const KTimeComboBox* self);
QSize* KTimeComboBox_MinimumSizeHint(const KTimeComboBox* self);
void KTimeComboBox_OnMinimumSizeHint(const KTimeComboBox* self, intptr_t slot);
QSize* KTimeComboBox_SuperMinimumSizeHint(const KTimeComboBox* self);
bool KTimeComboBox_Event(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_OnEvent(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperEvent(KTimeComboBox* self, QEvent* event);
QVariant* KTimeComboBox_InputMethodQuery(const KTimeComboBox* self, int param1);
void KTimeComboBox_OnInputMethodQuery(const KTimeComboBox* self, intptr_t slot);
QVariant* KTimeComboBox_SuperInputMethodQuery(const KTimeComboBox* self, int param1);
void KTimeComboBox_ChangeEvent(KTimeComboBox* self, QEvent* e);
void KTimeComboBox_OnChangeEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperChangeEvent(KTimeComboBox* self, QEvent* e);
void KTimeComboBox_PaintEvent(KTimeComboBox* self, QPaintEvent* e);
void KTimeComboBox_OnPaintEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperPaintEvent(KTimeComboBox* self, QPaintEvent* e);
void KTimeComboBox_ShowEvent(KTimeComboBox* self, QShowEvent* e);
void KTimeComboBox_OnShowEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperShowEvent(KTimeComboBox* self, QShowEvent* e);
void KTimeComboBox_HideEvent(KTimeComboBox* self, QHideEvent* e);
void KTimeComboBox_OnHideEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperHideEvent(KTimeComboBox* self, QHideEvent* e);
void KTimeComboBox_MouseReleaseEvent(KTimeComboBox* self, QMouseEvent* e);
void KTimeComboBox_OnMouseReleaseEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperMouseReleaseEvent(KTimeComboBox* self, QMouseEvent* e);
void KTimeComboBox_KeyReleaseEvent(KTimeComboBox* self, QKeyEvent* e);
void KTimeComboBox_OnKeyReleaseEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperKeyReleaseEvent(KTimeComboBox* self, QKeyEvent* e);
void KTimeComboBox_ContextMenuEvent(KTimeComboBox* self, QContextMenuEvent* e);
void KTimeComboBox_OnContextMenuEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperContextMenuEvent(KTimeComboBox* self, QContextMenuEvent* e);
void KTimeComboBox_InputMethodEvent(KTimeComboBox* self, QInputMethodEvent* param1);
void KTimeComboBox_OnInputMethodEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperInputMethodEvent(KTimeComboBox* self, QInputMethodEvent* param1);
void KTimeComboBox_InitStyleOption(const KTimeComboBox* self, QStyleOptionComboBox* option);
void KTimeComboBox_OnInitStyleOption(const KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperInitStyleOption(const KTimeComboBox* self, QStyleOptionComboBox* option);
int KTimeComboBox_DevType(const KTimeComboBox* self);
void KTimeComboBox_OnDevType(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_SuperDevType(const KTimeComboBox* self);
void KTimeComboBox_SetVisible(KTimeComboBox* self, bool visible);
void KTimeComboBox_OnSetVisible(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperSetVisible(KTimeComboBox* self, bool visible);
int KTimeComboBox_HeightForWidth(const KTimeComboBox* self, int param1);
void KTimeComboBox_OnHeightForWidth(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_SuperHeightForWidth(const KTimeComboBox* self, int param1);
bool KTimeComboBox_HasHeightForWidth(const KTimeComboBox* self);
void KTimeComboBox_OnHasHeightForWidth(const KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperHasHeightForWidth(const KTimeComboBox* self);
QPaintEngine* KTimeComboBox_PaintEngine(const KTimeComboBox* self);
void KTimeComboBox_OnPaintEngine(const KTimeComboBox* self, intptr_t slot);
QPaintEngine* KTimeComboBox_SuperPaintEngine(const KTimeComboBox* self);
void KTimeComboBox_MouseDoubleClickEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_OnMouseDoubleClickEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperMouseDoubleClickEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_MouseMoveEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_OnMouseMoveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperMouseMoveEvent(KTimeComboBox* self, QMouseEvent* event);
void KTimeComboBox_EnterEvent(KTimeComboBox* self, QEnterEvent* event);
void KTimeComboBox_OnEnterEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperEnterEvent(KTimeComboBox* self, QEnterEvent* event);
void KTimeComboBox_LeaveEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_OnLeaveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperLeaveEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_MoveEvent(KTimeComboBox* self, QMoveEvent* event);
void KTimeComboBox_OnMoveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperMoveEvent(KTimeComboBox* self, QMoveEvent* event);
void KTimeComboBox_CloseEvent(KTimeComboBox* self, QCloseEvent* event);
void KTimeComboBox_OnCloseEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperCloseEvent(KTimeComboBox* self, QCloseEvent* event);
void KTimeComboBox_TabletEvent(KTimeComboBox* self, QTabletEvent* event);
void KTimeComboBox_OnTabletEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperTabletEvent(KTimeComboBox* self, QTabletEvent* event);
void KTimeComboBox_ActionEvent(KTimeComboBox* self, QActionEvent* event);
void KTimeComboBox_OnActionEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperActionEvent(KTimeComboBox* self, QActionEvent* event);
void KTimeComboBox_DragEnterEvent(KTimeComboBox* self, QDragEnterEvent* event);
void KTimeComboBox_OnDragEnterEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperDragEnterEvent(KTimeComboBox* self, QDragEnterEvent* event);
void KTimeComboBox_DragMoveEvent(KTimeComboBox* self, QDragMoveEvent* event);
void KTimeComboBox_OnDragMoveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperDragMoveEvent(KTimeComboBox* self, QDragMoveEvent* event);
void KTimeComboBox_DragLeaveEvent(KTimeComboBox* self, QDragLeaveEvent* event);
void KTimeComboBox_OnDragLeaveEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperDragLeaveEvent(KTimeComboBox* self, QDragLeaveEvent* event);
void KTimeComboBox_DropEvent(KTimeComboBox* self, QDropEvent* event);
void KTimeComboBox_OnDropEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperDropEvent(KTimeComboBox* self, QDropEvent* event);
bool KTimeComboBox_NativeEvent(KTimeComboBox* self, const libqt_string eventType, void* message, intptr_t* result);
void KTimeComboBox_OnNativeEvent(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperNativeEvent(KTimeComboBox* self, const libqt_string eventType, void* message, intptr_t* result);
int KTimeComboBox_Metric(const KTimeComboBox* self, int param1);
void KTimeComboBox_OnMetric(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_SuperMetric(const KTimeComboBox* self, int param1);
void KTimeComboBox_InitPainter(const KTimeComboBox* self, QPainter* painter);
void KTimeComboBox_OnInitPainter(const KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperInitPainter(const KTimeComboBox* self, QPainter* painter);
QPaintDevice* KTimeComboBox_Redirected(const KTimeComboBox* self, QPoint* offset);
void KTimeComboBox_OnRedirected(const KTimeComboBox* self, intptr_t slot);
QPaintDevice* KTimeComboBox_SuperRedirected(const KTimeComboBox* self, QPoint* offset);
QPainter* KTimeComboBox_SharedPainter(const KTimeComboBox* self);
void KTimeComboBox_OnSharedPainter(const KTimeComboBox* self, intptr_t slot);
QPainter* KTimeComboBox_SuperSharedPainter(const KTimeComboBox* self);
bool KTimeComboBox_FocusNextPrevChild(KTimeComboBox* self, bool next);
void KTimeComboBox_OnFocusNextPrevChild(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperFocusNextPrevChild(KTimeComboBox* self, bool next);
void KTimeComboBox_TimerEvent(KTimeComboBox* self, QTimerEvent* event);
void KTimeComboBox_OnTimerEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperTimerEvent(KTimeComboBox* self, QTimerEvent* event);
void KTimeComboBox_ChildEvent(KTimeComboBox* self, QChildEvent* event);
void KTimeComboBox_OnChildEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperChildEvent(KTimeComboBox* self, QChildEvent* event);
void KTimeComboBox_CustomEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_OnCustomEvent(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperCustomEvent(KTimeComboBox* self, QEvent* event);
void KTimeComboBox_ConnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_OnConnectNotify(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperConnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_DisconnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_OnDisconnectNotify(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperDisconnectNotify(KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_UpdateMicroFocus(KTimeComboBox* self);
void KTimeComboBox_OnUpdateMicroFocus(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperUpdateMicroFocus(KTimeComboBox* self);
void KTimeComboBox_Create(KTimeComboBox* self);
void KTimeComboBox_OnCreate(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperCreate(KTimeComboBox* self);
void KTimeComboBox_Destroy(KTimeComboBox* self);
void KTimeComboBox_OnDestroy(KTimeComboBox* self, intptr_t slot);
void KTimeComboBox_SuperDestroy(KTimeComboBox* self);
bool KTimeComboBox_FocusNextChild(KTimeComboBox* self);
void KTimeComboBox_OnFocusNextChild(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperFocusNextChild(KTimeComboBox* self);
bool KTimeComboBox_FocusPreviousChild(KTimeComboBox* self);
void KTimeComboBox_OnFocusPreviousChild(KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperFocusPreviousChild(KTimeComboBox* self);
QObject* KTimeComboBox_Sender(const KTimeComboBox* self);
void KTimeComboBox_OnSender(const KTimeComboBox* self, intptr_t slot);
QObject* KTimeComboBox_SuperSender(const KTimeComboBox* self);
int KTimeComboBox_SenderSignalIndex(const KTimeComboBox* self);
void KTimeComboBox_OnSenderSignalIndex(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_SuperSenderSignalIndex(const KTimeComboBox* self);
int KTimeComboBox_Receivers(const KTimeComboBox* self, const char* signal);
void KTimeComboBox_OnReceivers(const KTimeComboBox* self, intptr_t slot);
int KTimeComboBox_SuperReceivers(const KTimeComboBox* self, const char* signal);
bool KTimeComboBox_IsSignalConnected(const KTimeComboBox* self, const QMetaMethod* signal);
void KTimeComboBox_OnIsSignalConnected(const KTimeComboBox* self, intptr_t slot);
bool KTimeComboBox_SuperIsSignalConnected(const KTimeComboBox* self, const QMetaMethod* signal);
double KTimeComboBox_GetDecodedMetricF(const KTimeComboBox* self, int metricA, int metricB);
void KTimeComboBox_OnGetDecodedMetricF(const KTimeComboBox* self, intptr_t slot);
double KTimeComboBox_SuperGetDecodedMetricF(const KTimeComboBox* self, int metricA, int metricB);
void KTimeComboBox_Delete(KTimeComboBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
