#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKDATEPICKER_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKDATEPICKER_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KDatePicker KDatePicker;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDate QDate;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KDatePicker* KDatePicker_new(QWidget* parent);
KDatePicker* KDatePicker_new2();
KDatePicker* KDatePicker_new3(const QDate* dt);
KDatePicker* KDatePicker_new4(const QDate* dt, QWidget* parent);
QMetaObject* KDatePicker_MetaObject(const KDatePicker* self);
void* KDatePicker_Metacast(KDatePicker* self, const char* param1);
int KDatePicker_Metacall(KDatePicker* self, int param1, int param2, void** param3);
QSize* KDatePicker_SizeHint(const KDatePicker* self);
bool KDatePicker_SetDate(KDatePicker* self, const QDate* date);
QDate* KDatePicker_Date(const KDatePicker* self);
void KDatePicker_SetFontSize(KDatePicker* self, int fontSize);
int KDatePicker_FontSize(const KDatePicker* self);
void KDatePicker_SetCloseButton(KDatePicker* self, bool enable);
bool KDatePicker_HasCloseButton(const KDatePicker* self);
void KDatePicker_SetDateRange(KDatePicker* self, const QDate* minDate);
bool KDatePicker_EventFilter(KDatePicker* self, QObject* o, QEvent* e);
void KDatePicker_ResizeEvent(KDatePicker* self, QResizeEvent* param1);
void KDatePicker_ChangeEvent(KDatePicker* self, QEvent* event);
void KDatePicker_DateChanged(KDatePicker* self, const QDate* date);
void KDatePicker_Connect_DateChanged(KDatePicker* self, intptr_t slot);
void KDatePicker_DateSelected(KDatePicker* self, const QDate* date);
void KDatePicker_Connect_DateSelected(KDatePicker* self, intptr_t slot);
void KDatePicker_DateEntered(KDatePicker* self, const QDate* date);
void KDatePicker_Connect_DateEntered(KDatePicker* self, intptr_t slot);
void KDatePicker_TableClicked(KDatePicker* self);
void KDatePicker_Connect_TableClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SetDateRange2(KDatePicker* self, const QDate* minDate, const QDate* maxDate);
void KDatePicker_OnMetaObject(const KDatePicker* self, intptr_t slot);
QMetaObject* KDatePicker_SuperMetaObject(const KDatePicker* self);
void KDatePicker_OnMetacast(KDatePicker* self, intptr_t slot);
void* KDatePicker_SuperMetacast(KDatePicker* self, const char* param1);
void KDatePicker_OnMetacall(KDatePicker* self, intptr_t slot);
int KDatePicker_SuperMetacall(KDatePicker* self, int param1, int param2, void** param3);
void KDatePicker_OnSizeHint(const KDatePicker* self, intptr_t slot);
QSize* KDatePicker_SuperSizeHint(const KDatePicker* self);
void KDatePicker_OnEventFilter(KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperEventFilter(KDatePicker* self, QObject* o, QEvent* e);
void KDatePicker_OnResizeEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperResizeEvent(KDatePicker* self, QResizeEvent* param1);
void KDatePicker_OnChangeEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperChangeEvent(KDatePicker* self, QEvent* event);
bool KDatePicker_Event(KDatePicker* self, QEvent* e);
void KDatePicker_OnEvent(KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperEvent(KDatePicker* self, QEvent* e);
void KDatePicker_PaintEvent(KDatePicker* self, QPaintEvent* param1);
void KDatePicker_OnPaintEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperPaintEvent(KDatePicker* self, QPaintEvent* param1);
void KDatePicker_InitStyleOption(const KDatePicker* self, QStyleOptionFrame* option);
void KDatePicker_OnInitStyleOption(const KDatePicker* self, intptr_t slot);
void KDatePicker_SuperInitStyleOption(const KDatePicker* self, QStyleOptionFrame* option);
int KDatePicker_DevType(const KDatePicker* self);
void KDatePicker_OnDevType(const KDatePicker* self, intptr_t slot);
int KDatePicker_SuperDevType(const KDatePicker* self);
void KDatePicker_SetVisible(KDatePicker* self, bool visible);
void KDatePicker_OnSetVisible(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperSetVisible(KDatePicker* self, bool visible);
QSize* KDatePicker_MinimumSizeHint(const KDatePicker* self);
void KDatePicker_OnMinimumSizeHint(const KDatePicker* self, intptr_t slot);
QSize* KDatePicker_SuperMinimumSizeHint(const KDatePicker* self);
int KDatePicker_HeightForWidth(const KDatePicker* self, int param1);
void KDatePicker_OnHeightForWidth(const KDatePicker* self, intptr_t slot);
int KDatePicker_SuperHeightForWidth(const KDatePicker* self, int param1);
bool KDatePicker_HasHeightForWidth(const KDatePicker* self);
void KDatePicker_OnHasHeightForWidth(const KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperHasHeightForWidth(const KDatePicker* self);
QPaintEngine* KDatePicker_PaintEngine(const KDatePicker* self);
void KDatePicker_OnPaintEngine(const KDatePicker* self, intptr_t slot);
QPaintEngine* KDatePicker_SuperPaintEngine(const KDatePicker* self);
void KDatePicker_MousePressEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_OnMousePressEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMousePressEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_MouseReleaseEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_OnMouseReleaseEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMouseReleaseEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_MouseDoubleClickEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_OnMouseDoubleClickEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMouseDoubleClickEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_MouseMoveEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_OnMouseMoveEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMouseMoveEvent(KDatePicker* self, QMouseEvent* event);
void KDatePicker_WheelEvent(KDatePicker* self, QWheelEvent* event);
void KDatePicker_OnWheelEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperWheelEvent(KDatePicker* self, QWheelEvent* event);
void KDatePicker_KeyPressEvent(KDatePicker* self, QKeyEvent* event);
void KDatePicker_OnKeyPressEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperKeyPressEvent(KDatePicker* self, QKeyEvent* event);
void KDatePicker_KeyReleaseEvent(KDatePicker* self, QKeyEvent* event);
void KDatePicker_OnKeyReleaseEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperKeyReleaseEvent(KDatePicker* self, QKeyEvent* event);
void KDatePicker_FocusInEvent(KDatePicker* self, QFocusEvent* event);
void KDatePicker_OnFocusInEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperFocusInEvent(KDatePicker* self, QFocusEvent* event);
void KDatePicker_FocusOutEvent(KDatePicker* self, QFocusEvent* event);
void KDatePicker_OnFocusOutEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperFocusOutEvent(KDatePicker* self, QFocusEvent* event);
void KDatePicker_EnterEvent(KDatePicker* self, QEnterEvent* event);
void KDatePicker_OnEnterEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperEnterEvent(KDatePicker* self, QEnterEvent* event);
void KDatePicker_LeaveEvent(KDatePicker* self, QEvent* event);
void KDatePicker_OnLeaveEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperLeaveEvent(KDatePicker* self, QEvent* event);
void KDatePicker_MoveEvent(KDatePicker* self, QMoveEvent* event);
void KDatePicker_OnMoveEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMoveEvent(KDatePicker* self, QMoveEvent* event);
void KDatePicker_CloseEvent(KDatePicker* self, QCloseEvent* event);
void KDatePicker_OnCloseEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperCloseEvent(KDatePicker* self, QCloseEvent* event);
void KDatePicker_ContextMenuEvent(KDatePicker* self, QContextMenuEvent* event);
void KDatePicker_OnContextMenuEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperContextMenuEvent(KDatePicker* self, QContextMenuEvent* event);
void KDatePicker_TabletEvent(KDatePicker* self, QTabletEvent* event);
void KDatePicker_OnTabletEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperTabletEvent(KDatePicker* self, QTabletEvent* event);
void KDatePicker_ActionEvent(KDatePicker* self, QActionEvent* event);
void KDatePicker_OnActionEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperActionEvent(KDatePicker* self, QActionEvent* event);
void KDatePicker_DragEnterEvent(KDatePicker* self, QDragEnterEvent* event);
void KDatePicker_OnDragEnterEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDragEnterEvent(KDatePicker* self, QDragEnterEvent* event);
void KDatePicker_DragMoveEvent(KDatePicker* self, QDragMoveEvent* event);
void KDatePicker_OnDragMoveEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDragMoveEvent(KDatePicker* self, QDragMoveEvent* event);
void KDatePicker_DragLeaveEvent(KDatePicker* self, QDragLeaveEvent* event);
void KDatePicker_OnDragLeaveEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDragLeaveEvent(KDatePicker* self, QDragLeaveEvent* event);
void KDatePicker_DropEvent(KDatePicker* self, QDropEvent* event);
void KDatePicker_OnDropEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDropEvent(KDatePicker* self, QDropEvent* event);
void KDatePicker_ShowEvent(KDatePicker* self, QShowEvent* event);
void KDatePicker_OnShowEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperShowEvent(KDatePicker* self, QShowEvent* event);
void KDatePicker_HideEvent(KDatePicker* self, QHideEvent* event);
void KDatePicker_OnHideEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperHideEvent(KDatePicker* self, QHideEvent* event);
bool KDatePicker_NativeEvent(KDatePicker* self, const libqt_string eventType, void* message, intptr_t* result);
void KDatePicker_OnNativeEvent(KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperNativeEvent(KDatePicker* self, const libqt_string eventType, void* message, intptr_t* result);
int KDatePicker_Metric(const KDatePicker* self, int param1);
void KDatePicker_OnMetric(const KDatePicker* self, intptr_t slot);
int KDatePicker_SuperMetric(const KDatePicker* self, int param1);
void KDatePicker_InitPainter(const KDatePicker* self, QPainter* painter);
void KDatePicker_OnInitPainter(const KDatePicker* self, intptr_t slot);
void KDatePicker_SuperInitPainter(const KDatePicker* self, QPainter* painter);
QPaintDevice* KDatePicker_Redirected(const KDatePicker* self, QPoint* offset);
void KDatePicker_OnRedirected(const KDatePicker* self, intptr_t slot);
QPaintDevice* KDatePicker_SuperRedirected(const KDatePicker* self, QPoint* offset);
QPainter* KDatePicker_SharedPainter(const KDatePicker* self);
void KDatePicker_OnSharedPainter(const KDatePicker* self, intptr_t slot);
QPainter* KDatePicker_SuperSharedPainter(const KDatePicker* self);
void KDatePicker_InputMethodEvent(KDatePicker* self, QInputMethodEvent* param1);
void KDatePicker_OnInputMethodEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperInputMethodEvent(KDatePicker* self, QInputMethodEvent* param1);
QVariant* KDatePicker_InputMethodQuery(const KDatePicker* self, int param1);
void KDatePicker_OnInputMethodQuery(const KDatePicker* self, intptr_t slot);
QVariant* KDatePicker_SuperInputMethodQuery(const KDatePicker* self, int param1);
bool KDatePicker_FocusNextPrevChild(KDatePicker* self, bool next);
void KDatePicker_OnFocusNextPrevChild(KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperFocusNextPrevChild(KDatePicker* self, bool next);
void KDatePicker_TimerEvent(KDatePicker* self, QTimerEvent* event);
void KDatePicker_OnTimerEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperTimerEvent(KDatePicker* self, QTimerEvent* event);
void KDatePicker_ChildEvent(KDatePicker* self, QChildEvent* event);
void KDatePicker_OnChildEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperChildEvent(KDatePicker* self, QChildEvent* event);
void KDatePicker_CustomEvent(KDatePicker* self, QEvent* event);
void KDatePicker_OnCustomEvent(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperCustomEvent(KDatePicker* self, QEvent* event);
void KDatePicker_ConnectNotify(KDatePicker* self, const QMetaMethod* signal);
void KDatePicker_OnConnectNotify(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperConnectNotify(KDatePicker* self, const QMetaMethod* signal);
void KDatePicker_DisconnectNotify(KDatePicker* self, const QMetaMethod* signal);
void KDatePicker_OnDisconnectNotify(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDisconnectNotify(KDatePicker* self, const QMetaMethod* signal);
void KDatePicker_DateChangedSlot(KDatePicker* self, const QDate* date);
void KDatePicker_OnDateChangedSlot(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDateChangedSlot(KDatePicker* self, const QDate* date);
void KDatePicker_TableClickedSlot(KDatePicker* self);
void KDatePicker_OnTableClickedSlot(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperTableClickedSlot(KDatePicker* self);
void KDatePicker_MonthForwardClicked(KDatePicker* self);
void KDatePicker_OnMonthForwardClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMonthForwardClicked(KDatePicker* self);
void KDatePicker_MonthBackwardClicked(KDatePicker* self);
void KDatePicker_OnMonthBackwardClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperMonthBackwardClicked(KDatePicker* self);
void KDatePicker_YearForwardClicked(KDatePicker* self);
void KDatePicker_OnYearForwardClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperYearForwardClicked(KDatePicker* self);
void KDatePicker_YearBackwardClicked(KDatePicker* self);
void KDatePicker_OnYearBackwardClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperYearBackwardClicked(KDatePicker* self);
void KDatePicker_SelectMonthClicked(KDatePicker* self);
void KDatePicker_OnSelectMonthClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperSelectMonthClicked(KDatePicker* self);
void KDatePicker_SelectYearClicked(KDatePicker* self);
void KDatePicker_OnSelectYearClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperSelectYearClicked(KDatePicker* self);
void KDatePicker_UncheckYearSelector(KDatePicker* self);
void KDatePicker_OnUncheckYearSelector(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperUncheckYearSelector(KDatePicker* self);
void KDatePicker_LineEnterPressed(KDatePicker* self);
void KDatePicker_OnLineEnterPressed(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperLineEnterPressed(KDatePicker* self);
void KDatePicker_TodayButtonClicked(KDatePicker* self);
void KDatePicker_OnTodayButtonClicked(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperTodayButtonClicked(KDatePicker* self);
void KDatePicker_WeekSelected(KDatePicker* self, int param1);
void KDatePicker_OnWeekSelected(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperWeekSelected(KDatePicker* self, int param1);
void KDatePicker_DrawFrame(KDatePicker* self, QPainter* param1);
void KDatePicker_OnDrawFrame(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDrawFrame(KDatePicker* self, QPainter* param1);
void KDatePicker_UpdateMicroFocus(KDatePicker* self);
void KDatePicker_OnUpdateMicroFocus(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperUpdateMicroFocus(KDatePicker* self);
void KDatePicker_Create(KDatePicker* self);
void KDatePicker_OnCreate(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperCreate(KDatePicker* self);
void KDatePicker_Destroy(KDatePicker* self);
void KDatePicker_OnDestroy(KDatePicker* self, intptr_t slot);
void KDatePicker_SuperDestroy(KDatePicker* self);
bool KDatePicker_FocusNextChild(KDatePicker* self);
void KDatePicker_OnFocusNextChild(KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperFocusNextChild(KDatePicker* self);
bool KDatePicker_FocusPreviousChild(KDatePicker* self);
void KDatePicker_OnFocusPreviousChild(KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperFocusPreviousChild(KDatePicker* self);
QObject* KDatePicker_Sender(const KDatePicker* self);
void KDatePicker_OnSender(const KDatePicker* self, intptr_t slot);
QObject* KDatePicker_SuperSender(const KDatePicker* self);
int KDatePicker_SenderSignalIndex(const KDatePicker* self);
void KDatePicker_OnSenderSignalIndex(const KDatePicker* self, intptr_t slot);
int KDatePicker_SuperSenderSignalIndex(const KDatePicker* self);
int KDatePicker_Receivers(const KDatePicker* self, const char* signal);
void KDatePicker_OnReceivers(const KDatePicker* self, intptr_t slot);
int KDatePicker_SuperReceivers(const KDatePicker* self, const char* signal);
bool KDatePicker_IsSignalConnected(const KDatePicker* self, const QMetaMethod* signal);
void KDatePicker_OnIsSignalConnected(const KDatePicker* self, intptr_t slot);
bool KDatePicker_SuperIsSignalConnected(const KDatePicker* self, const QMetaMethod* signal);
double KDatePicker_GetDecodedMetricF(const KDatePicker* self, int metricA, int metricB);
void KDatePicker_OnGetDecodedMetricF(const KDatePicker* self, intptr_t slot);
double KDatePicker_SuperGetDecodedMetricF(const KDatePicker* self, int metricA, int metricB);
void KDatePicker_Delete(KDatePicker* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
