#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKPIXMAPREGIONSELECTORDIALOG_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKPIXMAPREGIONSELECTORDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KPixmapRegionSelectorDialog KPixmapRegionSelectorDialog;
typedef struct KPixmapRegionSelectorWidget KPixmapRegionSelectorWidget;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KPixmapRegionSelectorDialog* KPixmapRegionSelectorDialog_new(QWidget* parent);
KPixmapRegionSelectorDialog* KPixmapRegionSelectorDialog_new2();
QMetaObject* KPixmapRegionSelectorDialog_MetaObject(const KPixmapRegionSelectorDialog* self);
void* KPixmapRegionSelectorDialog_Metacast(KPixmapRegionSelectorDialog* self, const char* param1);
int KPixmapRegionSelectorDialog_Metacall(KPixmapRegionSelectorDialog* self, int param1, int param2, void** param3);
KPixmapRegionSelectorWidget* KPixmapRegionSelectorDialog_PixmapRegionSelectorWidget(const KPixmapRegionSelectorDialog* self);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion(const QPixmap* pixmap);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion2(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage(const QPixmap* pixmap);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage2(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight);
void KPixmapRegionSelectorDialog_AdjustRegionSelectorWidgetSizeToFitScreen(KPixmapRegionSelectorDialog* self);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion22(const QPixmap* pixmap, QWidget* parent);
QRect* KPixmapRegionSelectorDialog_GetSelectedRegion4(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight, QWidget* parent);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage22(const QPixmap* pixmap, QWidget* parent);
QImage* KPixmapRegionSelectorDialog_GetSelectedImage4(const QPixmap* pixmap, int aspectRatioWidth, int aspectRatioHeight, QWidget* parent);
void KPixmapRegionSelectorDialog_OnMetaObject(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QMetaObject* KPixmapRegionSelectorDialog_SuperMetaObject(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnMetacast(KPixmapRegionSelectorDialog* self, intptr_t slot);
void* KPixmapRegionSelectorDialog_SuperMetacast(KPixmapRegionSelectorDialog* self, const char* param1);
void KPixmapRegionSelectorDialog_OnMetacall(KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperMetacall(KPixmapRegionSelectorDialog* self, int param1, int param2, void** param3);
void KPixmapRegionSelectorDialog_SetVisible(KPixmapRegionSelectorDialog* self, bool visible);
void KPixmapRegionSelectorDialog_OnSetVisible(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperSetVisible(KPixmapRegionSelectorDialog* self, bool visible);
QSize* KPixmapRegionSelectorDialog_SizeHint(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSizeHint(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QSize* KPixmapRegionSelectorDialog_SuperSizeHint(const KPixmapRegionSelectorDialog* self);
QSize* KPixmapRegionSelectorDialog_MinimumSizeHint(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnMinimumSizeHint(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QSize* KPixmapRegionSelectorDialog_SuperMinimumSizeHint(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Open(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnOpen(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperOpen(KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_Exec(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnExec(KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperExec(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Done(KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnDone(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDone(KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_Accept(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnAccept(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperAccept(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Reject(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnReject(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperReject(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_KeyPressEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* param1);
void KPixmapRegionSelectorDialog_OnKeyPressEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperKeyPressEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* param1);
void KPixmapRegionSelectorDialog_CloseEvent(KPixmapRegionSelectorDialog* self, QCloseEvent* param1);
void KPixmapRegionSelectorDialog_OnCloseEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperCloseEvent(KPixmapRegionSelectorDialog* self, QCloseEvent* param1);
void KPixmapRegionSelectorDialog_ShowEvent(KPixmapRegionSelectorDialog* self, QShowEvent* param1);
void KPixmapRegionSelectorDialog_OnShowEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperShowEvent(KPixmapRegionSelectorDialog* self, QShowEvent* param1);
void KPixmapRegionSelectorDialog_ResizeEvent(KPixmapRegionSelectorDialog* self, QResizeEvent* param1);
void KPixmapRegionSelectorDialog_OnResizeEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperResizeEvent(KPixmapRegionSelectorDialog* self, QResizeEvent* param1);
void KPixmapRegionSelectorDialog_ContextMenuEvent(KPixmapRegionSelectorDialog* self, QContextMenuEvent* param1);
void KPixmapRegionSelectorDialog_OnContextMenuEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperContextMenuEvent(KPixmapRegionSelectorDialog* self, QContextMenuEvent* param1);
bool KPixmapRegionSelectorDialog_EventFilter(KPixmapRegionSelectorDialog* self, QObject* param1, QEvent* param2);
void KPixmapRegionSelectorDialog_OnEventFilter(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperEventFilter(KPixmapRegionSelectorDialog* self, QObject* param1, QEvent* param2);
int KPixmapRegionSelectorDialog_DevType(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnDevType(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperDevType(const KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_HeightForWidth(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnHeightForWidth(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperHeightForWidth(const KPixmapRegionSelectorDialog* self, int param1);
bool KPixmapRegionSelectorDialog_HasHeightForWidth(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnHasHeightForWidth(const KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperHasHeightForWidth(const KPixmapRegionSelectorDialog* self);
QPaintEngine* KPixmapRegionSelectorDialog_PaintEngine(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnPaintEngine(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QPaintEngine* KPixmapRegionSelectorDialog_SuperPaintEngine(const KPixmapRegionSelectorDialog* self);
bool KPixmapRegionSelectorDialog_Event(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_OnEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_MousePressEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMousePressEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperMousePressEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_MouseReleaseEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMouseReleaseEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperMouseReleaseEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_MouseDoubleClickEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMouseDoubleClickEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperMouseDoubleClickEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_MouseMoveEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_OnMouseMoveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperMouseMoveEvent(KPixmapRegionSelectorDialog* self, QMouseEvent* event);
void KPixmapRegionSelectorDialog_WheelEvent(KPixmapRegionSelectorDialog* self, QWheelEvent* event);
void KPixmapRegionSelectorDialog_OnWheelEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperWheelEvent(KPixmapRegionSelectorDialog* self, QWheelEvent* event);
void KPixmapRegionSelectorDialog_KeyReleaseEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* event);
void KPixmapRegionSelectorDialog_OnKeyReleaseEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperKeyReleaseEvent(KPixmapRegionSelectorDialog* self, QKeyEvent* event);
void KPixmapRegionSelectorDialog_FocusInEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_OnFocusInEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperFocusInEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_FocusOutEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_OnFocusOutEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperFocusOutEvent(KPixmapRegionSelectorDialog* self, QFocusEvent* event);
void KPixmapRegionSelectorDialog_EnterEvent(KPixmapRegionSelectorDialog* self, QEnterEvent* event);
void KPixmapRegionSelectorDialog_OnEnterEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperEnterEvent(KPixmapRegionSelectorDialog* self, QEnterEvent* event);
void KPixmapRegionSelectorDialog_LeaveEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_OnLeaveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperLeaveEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_PaintEvent(KPixmapRegionSelectorDialog* self, QPaintEvent* event);
void KPixmapRegionSelectorDialog_OnPaintEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperPaintEvent(KPixmapRegionSelectorDialog* self, QPaintEvent* event);
void KPixmapRegionSelectorDialog_MoveEvent(KPixmapRegionSelectorDialog* self, QMoveEvent* event);
void KPixmapRegionSelectorDialog_OnMoveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperMoveEvent(KPixmapRegionSelectorDialog* self, QMoveEvent* event);
void KPixmapRegionSelectorDialog_TabletEvent(KPixmapRegionSelectorDialog* self, QTabletEvent* event);
void KPixmapRegionSelectorDialog_OnTabletEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperTabletEvent(KPixmapRegionSelectorDialog* self, QTabletEvent* event);
void KPixmapRegionSelectorDialog_ActionEvent(KPixmapRegionSelectorDialog* self, QActionEvent* event);
void KPixmapRegionSelectorDialog_OnActionEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperActionEvent(KPixmapRegionSelectorDialog* self, QActionEvent* event);
void KPixmapRegionSelectorDialog_DragEnterEvent(KPixmapRegionSelectorDialog* self, QDragEnterEvent* event);
void KPixmapRegionSelectorDialog_OnDragEnterEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDragEnterEvent(KPixmapRegionSelectorDialog* self, QDragEnterEvent* event);
void KPixmapRegionSelectorDialog_DragMoveEvent(KPixmapRegionSelectorDialog* self, QDragMoveEvent* event);
void KPixmapRegionSelectorDialog_OnDragMoveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDragMoveEvent(KPixmapRegionSelectorDialog* self, QDragMoveEvent* event);
void KPixmapRegionSelectorDialog_DragLeaveEvent(KPixmapRegionSelectorDialog* self, QDragLeaveEvent* event);
void KPixmapRegionSelectorDialog_OnDragLeaveEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDragLeaveEvent(KPixmapRegionSelectorDialog* self, QDragLeaveEvent* event);
void KPixmapRegionSelectorDialog_DropEvent(KPixmapRegionSelectorDialog* self, QDropEvent* event);
void KPixmapRegionSelectorDialog_OnDropEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDropEvent(KPixmapRegionSelectorDialog* self, QDropEvent* event);
void KPixmapRegionSelectorDialog_HideEvent(KPixmapRegionSelectorDialog* self, QHideEvent* event);
void KPixmapRegionSelectorDialog_OnHideEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperHideEvent(KPixmapRegionSelectorDialog* self, QHideEvent* event);
bool KPixmapRegionSelectorDialog_NativeEvent(KPixmapRegionSelectorDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KPixmapRegionSelectorDialog_OnNativeEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperNativeEvent(KPixmapRegionSelectorDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KPixmapRegionSelectorDialog_ChangeEvent(KPixmapRegionSelectorDialog* self, QEvent* param1);
void KPixmapRegionSelectorDialog_OnChangeEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperChangeEvent(KPixmapRegionSelectorDialog* self, QEvent* param1);
int KPixmapRegionSelectorDialog_Metric(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnMetric(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperMetric(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_InitPainter(const KPixmapRegionSelectorDialog* self, QPainter* painter);
void KPixmapRegionSelectorDialog_OnInitPainter(const KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperInitPainter(const KPixmapRegionSelectorDialog* self, QPainter* painter);
QPaintDevice* KPixmapRegionSelectorDialog_Redirected(const KPixmapRegionSelectorDialog* self, QPoint* offset);
void KPixmapRegionSelectorDialog_OnRedirected(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QPaintDevice* KPixmapRegionSelectorDialog_SuperRedirected(const KPixmapRegionSelectorDialog* self, QPoint* offset);
QPainter* KPixmapRegionSelectorDialog_SharedPainter(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSharedPainter(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QPainter* KPixmapRegionSelectorDialog_SuperSharedPainter(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_InputMethodEvent(KPixmapRegionSelectorDialog* self, QInputMethodEvent* param1);
void KPixmapRegionSelectorDialog_OnInputMethodEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperInputMethodEvent(KPixmapRegionSelectorDialog* self, QInputMethodEvent* param1);
QVariant* KPixmapRegionSelectorDialog_InputMethodQuery(const KPixmapRegionSelectorDialog* self, int param1);
void KPixmapRegionSelectorDialog_OnInputMethodQuery(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QVariant* KPixmapRegionSelectorDialog_SuperInputMethodQuery(const KPixmapRegionSelectorDialog* self, int param1);
bool KPixmapRegionSelectorDialog_FocusNextPrevChild(KPixmapRegionSelectorDialog* self, bool next);
void KPixmapRegionSelectorDialog_OnFocusNextPrevChild(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperFocusNextPrevChild(KPixmapRegionSelectorDialog* self, bool next);
void KPixmapRegionSelectorDialog_TimerEvent(KPixmapRegionSelectorDialog* self, QTimerEvent* event);
void KPixmapRegionSelectorDialog_OnTimerEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperTimerEvent(KPixmapRegionSelectorDialog* self, QTimerEvent* event);
void KPixmapRegionSelectorDialog_ChildEvent(KPixmapRegionSelectorDialog* self, QChildEvent* event);
void KPixmapRegionSelectorDialog_OnChildEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperChildEvent(KPixmapRegionSelectorDialog* self, QChildEvent* event);
void KPixmapRegionSelectorDialog_CustomEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_OnCustomEvent(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperCustomEvent(KPixmapRegionSelectorDialog* self, QEvent* event);
void KPixmapRegionSelectorDialog_ConnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_OnConnectNotify(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperConnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_DisconnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_OnDisconnectNotify(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDisconnectNotify(KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_AdjustPosition(KPixmapRegionSelectorDialog* self, QWidget* param1);
void KPixmapRegionSelectorDialog_OnAdjustPosition(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperAdjustPosition(KPixmapRegionSelectorDialog* self, QWidget* param1);
void KPixmapRegionSelectorDialog_UpdateMicroFocus(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnUpdateMicroFocus(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperUpdateMicroFocus(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Create(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnCreate(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperCreate(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_Destroy(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnDestroy(KPixmapRegionSelectorDialog* self, intptr_t slot);
void KPixmapRegionSelectorDialog_SuperDestroy(KPixmapRegionSelectorDialog* self);
bool KPixmapRegionSelectorDialog_FocusNextChild(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnFocusNextChild(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperFocusNextChild(KPixmapRegionSelectorDialog* self);
bool KPixmapRegionSelectorDialog_FocusPreviousChild(KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnFocusPreviousChild(KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperFocusPreviousChild(KPixmapRegionSelectorDialog* self);
QObject* KPixmapRegionSelectorDialog_Sender(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSender(const KPixmapRegionSelectorDialog* self, intptr_t slot);
QObject* KPixmapRegionSelectorDialog_SuperSender(const KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_SenderSignalIndex(const KPixmapRegionSelectorDialog* self);
void KPixmapRegionSelectorDialog_OnSenderSignalIndex(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperSenderSignalIndex(const KPixmapRegionSelectorDialog* self);
int KPixmapRegionSelectorDialog_Receivers(const KPixmapRegionSelectorDialog* self, const char* signal);
void KPixmapRegionSelectorDialog_OnReceivers(const KPixmapRegionSelectorDialog* self, intptr_t slot);
int KPixmapRegionSelectorDialog_SuperReceivers(const KPixmapRegionSelectorDialog* self, const char* signal);
bool KPixmapRegionSelectorDialog_IsSignalConnected(const KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
void KPixmapRegionSelectorDialog_OnIsSignalConnected(const KPixmapRegionSelectorDialog* self, intptr_t slot);
bool KPixmapRegionSelectorDialog_SuperIsSignalConnected(const KPixmapRegionSelectorDialog* self, const QMetaMethod* signal);
double KPixmapRegionSelectorDialog_GetDecodedMetricF(const KPixmapRegionSelectorDialog* self, int metricA, int metricB);
void KPixmapRegionSelectorDialog_OnGetDecodedMetricF(const KPixmapRegionSelectorDialog* self, intptr_t slot);
double KPixmapRegionSelectorDialog_SuperGetDecodedMetricF(const KPixmapRegionSelectorDialog* self, int metricA, int metricB);
void KPixmapRegionSelectorDialog_Delete(KPixmapRegionSelectorDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
