#pragma once
#ifndef SRC_EXTRAS_KIOC_LIBKFILEFILTERCOMBO_H
#define SRC_EXTRAS_KIOC_LIBKFILEFILTERCOMBO_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KComboBox KComboBox;
typedef struct KCompletion KCompletion;
typedef struct KCompletionBase KCompletionBase;
typedef struct KFileFilter KFileFilter;
typedef struct KFileFilterCombo KFileFilterCombo;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QKeySequence QKeySequence;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KFileFilterCombo* KFileFilterCombo_new(QWidget* parent);
KFileFilterCombo* KFileFilterCombo_new2();
QMetaObject* KFileFilterCombo_MetaObject(const KFileFilterCombo* self);
void* KFileFilterCombo_Metacast(KFileFilterCombo* self, const char* param1);
int KFileFilterCombo_Metacall(KFileFilterCombo* self, int param1, int param2, void** param3);
void KFileFilterCombo_SetFilters(KFileFilterCombo* self, const libqt_list /* of KFileFilter* */ filters);
KFileFilter* KFileFilterCombo_CurrentFilter(const KFileFilterCombo* self);
libqt_list /* of KFileFilter* */ KFileFilterCombo_Filters(const KFileFilterCombo* self);
void KFileFilterCombo_SetDefaultFilter(KFileFilterCombo* self, const KFileFilter* filter);
KFileFilter* KFileFilterCombo_DefaultFilter(const KFileFilterCombo* self);
void KFileFilterCombo_SetCurrentFilter(KFileFilterCombo* self, const KFileFilter* filter);
bool KFileFilterCombo_ShowsAllTypes(const KFileFilterCombo* self);
bool KFileFilterCombo_EventFilter(KFileFilterCombo* self, QObject* param1, QEvent* param2);
void KFileFilterCombo_FilterChanged(KFileFilterCombo* self);
void KFileFilterCombo_Connect_FilterChanged(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SetFilters2(KFileFilterCombo* self, const libqt_list /* of KFileFilter* */ filters, const KFileFilter* defaultFilter);
void KFileFilterCombo_OnMetaObject(const KFileFilterCombo* self, intptr_t slot);
QMetaObject* KFileFilterCombo_SuperMetaObject(const KFileFilterCombo* self);
void KFileFilterCombo_OnMetacast(KFileFilterCombo* self, intptr_t slot);
void* KFileFilterCombo_SuperMetacast(KFileFilterCombo* self, const char* param1);
void KFileFilterCombo_OnMetacall(KFileFilterCombo* self, intptr_t slot);
int KFileFilterCombo_SuperMetacall(KFileFilterCombo* self, int param1, int param2, void** param3);
void KFileFilterCombo_OnEventFilter(KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperEventFilter(KFileFilterCombo* self, QObject* param1, QEvent* param2);
void KFileFilterCombo_SetAutoCompletion(KFileFilterCombo* self, bool autocomplete);
void KFileFilterCombo_OnSetAutoCompletion(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetAutoCompletion(KFileFilterCombo* self, bool autocomplete);
void KFileFilterCombo_SetLineEdit(KFileFilterCombo* self, QLineEdit* lineEdit);
void KFileFilterCombo_OnSetLineEdit(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetLineEdit(KFileFilterCombo* self, QLineEdit* lineEdit);
QSize* KFileFilterCombo_MinimumSizeHint(const KFileFilterCombo* self);
void KFileFilterCombo_OnMinimumSizeHint(const KFileFilterCombo* self, intptr_t slot);
QSize* KFileFilterCombo_SuperMinimumSizeHint(const KFileFilterCombo* self);
void KFileFilterCombo_SetCompletedText(KFileFilterCombo* self, const libqt_string completedText);
void KFileFilterCombo_OnSetCompletedText(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetCompletedText(KFileFilterCombo* self, const libqt_string completedText);
void KFileFilterCombo_SetCompletedItems(KFileFilterCombo* self, const libqt_list /* of libqt_string */ items, bool autoSuggest);
void KFileFilterCombo_OnSetCompletedItems(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetCompletedItems(KFileFilterCombo* self, const libqt_list /* of libqt_string */ items, bool autoSuggest);
void KFileFilterCombo_MakeCompletion(KFileFilterCombo* self, const libqt_string param1);
void KFileFilterCombo_OnMakeCompletion(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperMakeCompletion(KFileFilterCombo* self, const libqt_string param1);
void KFileFilterCombo_SetModel(KFileFilterCombo* self, QAbstractItemModel* model);
void KFileFilterCombo_OnSetModel(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetModel(KFileFilterCombo* self, QAbstractItemModel* model);
QSize* KFileFilterCombo_SizeHint(const KFileFilterCombo* self);
void KFileFilterCombo_OnSizeHint(const KFileFilterCombo* self, intptr_t slot);
QSize* KFileFilterCombo_SuperSizeHint(const KFileFilterCombo* self);
void KFileFilterCombo_ShowPopup(KFileFilterCombo* self);
void KFileFilterCombo_OnShowPopup(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperShowPopup(KFileFilterCombo* self);
void KFileFilterCombo_HidePopup(KFileFilterCombo* self);
void KFileFilterCombo_OnHidePopup(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperHidePopup(KFileFilterCombo* self);
bool KFileFilterCombo_Event(KFileFilterCombo* self, QEvent* event);
void KFileFilterCombo_OnEvent(KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperEvent(KFileFilterCombo* self, QEvent* event);
QVariant* KFileFilterCombo_InputMethodQuery(const KFileFilterCombo* self, int param1);
void KFileFilterCombo_OnInputMethodQuery(const KFileFilterCombo* self, intptr_t slot);
QVariant* KFileFilterCombo_SuperInputMethodQuery(const KFileFilterCombo* self, int param1);
void KFileFilterCombo_FocusInEvent(KFileFilterCombo* self, QFocusEvent* e);
void KFileFilterCombo_OnFocusInEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperFocusInEvent(KFileFilterCombo* self, QFocusEvent* e);
void KFileFilterCombo_FocusOutEvent(KFileFilterCombo* self, QFocusEvent* e);
void KFileFilterCombo_OnFocusOutEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperFocusOutEvent(KFileFilterCombo* self, QFocusEvent* e);
void KFileFilterCombo_ChangeEvent(KFileFilterCombo* self, QEvent* e);
void KFileFilterCombo_OnChangeEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperChangeEvent(KFileFilterCombo* self, QEvent* e);
void KFileFilterCombo_ResizeEvent(KFileFilterCombo* self, QResizeEvent* e);
void KFileFilterCombo_OnResizeEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperResizeEvent(KFileFilterCombo* self, QResizeEvent* e);
void KFileFilterCombo_PaintEvent(KFileFilterCombo* self, QPaintEvent* e);
void KFileFilterCombo_OnPaintEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperPaintEvent(KFileFilterCombo* self, QPaintEvent* e);
void KFileFilterCombo_ShowEvent(KFileFilterCombo* self, QShowEvent* e);
void KFileFilterCombo_OnShowEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperShowEvent(KFileFilterCombo* self, QShowEvent* e);
void KFileFilterCombo_HideEvent(KFileFilterCombo* self, QHideEvent* e);
void KFileFilterCombo_OnHideEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperHideEvent(KFileFilterCombo* self, QHideEvent* e);
void KFileFilterCombo_MousePressEvent(KFileFilterCombo* self, QMouseEvent* e);
void KFileFilterCombo_OnMousePressEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperMousePressEvent(KFileFilterCombo* self, QMouseEvent* e);
void KFileFilterCombo_MouseReleaseEvent(KFileFilterCombo* self, QMouseEvent* e);
void KFileFilterCombo_OnMouseReleaseEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperMouseReleaseEvent(KFileFilterCombo* self, QMouseEvent* e);
void KFileFilterCombo_KeyPressEvent(KFileFilterCombo* self, QKeyEvent* e);
void KFileFilterCombo_OnKeyPressEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperKeyPressEvent(KFileFilterCombo* self, QKeyEvent* e);
void KFileFilterCombo_KeyReleaseEvent(KFileFilterCombo* self, QKeyEvent* e);
void KFileFilterCombo_OnKeyReleaseEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperKeyReleaseEvent(KFileFilterCombo* self, QKeyEvent* e);
void KFileFilterCombo_WheelEvent(KFileFilterCombo* self, QWheelEvent* e);
void KFileFilterCombo_OnWheelEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperWheelEvent(KFileFilterCombo* self, QWheelEvent* e);
void KFileFilterCombo_ContextMenuEvent(KFileFilterCombo* self, QContextMenuEvent* e);
void KFileFilterCombo_OnContextMenuEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperContextMenuEvent(KFileFilterCombo* self, QContextMenuEvent* e);
void KFileFilterCombo_InputMethodEvent(KFileFilterCombo* self, QInputMethodEvent* param1);
void KFileFilterCombo_OnInputMethodEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperInputMethodEvent(KFileFilterCombo* self, QInputMethodEvent* param1);
void KFileFilterCombo_InitStyleOption(const KFileFilterCombo* self, QStyleOptionComboBox* option);
void KFileFilterCombo_OnInitStyleOption(const KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperInitStyleOption(const KFileFilterCombo* self, QStyleOptionComboBox* option);
int KFileFilterCombo_DevType(const KFileFilterCombo* self);
void KFileFilterCombo_OnDevType(const KFileFilterCombo* self, intptr_t slot);
int KFileFilterCombo_SuperDevType(const KFileFilterCombo* self);
void KFileFilterCombo_SetVisible(KFileFilterCombo* self, bool visible);
void KFileFilterCombo_OnSetVisible(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetVisible(KFileFilterCombo* self, bool visible);
int KFileFilterCombo_HeightForWidth(const KFileFilterCombo* self, int param1);
void KFileFilterCombo_OnHeightForWidth(const KFileFilterCombo* self, intptr_t slot);
int KFileFilterCombo_SuperHeightForWidth(const KFileFilterCombo* self, int param1);
bool KFileFilterCombo_HasHeightForWidth(const KFileFilterCombo* self);
void KFileFilterCombo_OnHasHeightForWidth(const KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperHasHeightForWidth(const KFileFilterCombo* self);
QPaintEngine* KFileFilterCombo_PaintEngine(const KFileFilterCombo* self);
void KFileFilterCombo_OnPaintEngine(const KFileFilterCombo* self, intptr_t slot);
QPaintEngine* KFileFilterCombo_SuperPaintEngine(const KFileFilterCombo* self);
void KFileFilterCombo_MouseDoubleClickEvent(KFileFilterCombo* self, QMouseEvent* event);
void KFileFilterCombo_OnMouseDoubleClickEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperMouseDoubleClickEvent(KFileFilterCombo* self, QMouseEvent* event);
void KFileFilterCombo_MouseMoveEvent(KFileFilterCombo* self, QMouseEvent* event);
void KFileFilterCombo_OnMouseMoveEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperMouseMoveEvent(KFileFilterCombo* self, QMouseEvent* event);
void KFileFilterCombo_EnterEvent(KFileFilterCombo* self, QEnterEvent* event);
void KFileFilterCombo_OnEnterEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperEnterEvent(KFileFilterCombo* self, QEnterEvent* event);
void KFileFilterCombo_LeaveEvent(KFileFilterCombo* self, QEvent* event);
void KFileFilterCombo_OnLeaveEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperLeaveEvent(KFileFilterCombo* self, QEvent* event);
void KFileFilterCombo_MoveEvent(KFileFilterCombo* self, QMoveEvent* event);
void KFileFilterCombo_OnMoveEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperMoveEvent(KFileFilterCombo* self, QMoveEvent* event);
void KFileFilterCombo_CloseEvent(KFileFilterCombo* self, QCloseEvent* event);
void KFileFilterCombo_OnCloseEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperCloseEvent(KFileFilterCombo* self, QCloseEvent* event);
void KFileFilterCombo_TabletEvent(KFileFilterCombo* self, QTabletEvent* event);
void KFileFilterCombo_OnTabletEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperTabletEvent(KFileFilterCombo* self, QTabletEvent* event);
void KFileFilterCombo_ActionEvent(KFileFilterCombo* self, QActionEvent* event);
void KFileFilterCombo_OnActionEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperActionEvent(KFileFilterCombo* self, QActionEvent* event);
void KFileFilterCombo_DragEnterEvent(KFileFilterCombo* self, QDragEnterEvent* event);
void KFileFilterCombo_OnDragEnterEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperDragEnterEvent(KFileFilterCombo* self, QDragEnterEvent* event);
void KFileFilterCombo_DragMoveEvent(KFileFilterCombo* self, QDragMoveEvent* event);
void KFileFilterCombo_OnDragMoveEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperDragMoveEvent(KFileFilterCombo* self, QDragMoveEvent* event);
void KFileFilterCombo_DragLeaveEvent(KFileFilterCombo* self, QDragLeaveEvent* event);
void KFileFilterCombo_OnDragLeaveEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperDragLeaveEvent(KFileFilterCombo* self, QDragLeaveEvent* event);
void KFileFilterCombo_DropEvent(KFileFilterCombo* self, QDropEvent* event);
void KFileFilterCombo_OnDropEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperDropEvent(KFileFilterCombo* self, QDropEvent* event);
bool KFileFilterCombo_NativeEvent(KFileFilterCombo* self, const libqt_string eventType, void* message, intptr_t* result);
void KFileFilterCombo_OnNativeEvent(KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperNativeEvent(KFileFilterCombo* self, const libqt_string eventType, void* message, intptr_t* result);
int KFileFilterCombo_Metric(const KFileFilterCombo* self, int param1);
void KFileFilterCombo_OnMetric(const KFileFilterCombo* self, intptr_t slot);
int KFileFilterCombo_SuperMetric(const KFileFilterCombo* self, int param1);
void KFileFilterCombo_InitPainter(const KFileFilterCombo* self, QPainter* painter);
void KFileFilterCombo_OnInitPainter(const KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperInitPainter(const KFileFilterCombo* self, QPainter* painter);
QPaintDevice* KFileFilterCombo_Redirected(const KFileFilterCombo* self, QPoint* offset);
void KFileFilterCombo_OnRedirected(const KFileFilterCombo* self, intptr_t slot);
QPaintDevice* KFileFilterCombo_SuperRedirected(const KFileFilterCombo* self, QPoint* offset);
QPainter* KFileFilterCombo_SharedPainter(const KFileFilterCombo* self);
void KFileFilterCombo_OnSharedPainter(const KFileFilterCombo* self, intptr_t slot);
QPainter* KFileFilterCombo_SuperSharedPainter(const KFileFilterCombo* self);
bool KFileFilterCombo_FocusNextPrevChild(KFileFilterCombo* self, bool next);
void KFileFilterCombo_OnFocusNextPrevChild(KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperFocusNextPrevChild(KFileFilterCombo* self, bool next);
void KFileFilterCombo_TimerEvent(KFileFilterCombo* self, QTimerEvent* event);
void KFileFilterCombo_OnTimerEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperTimerEvent(KFileFilterCombo* self, QTimerEvent* event);
void KFileFilterCombo_ChildEvent(KFileFilterCombo* self, QChildEvent* event);
void KFileFilterCombo_OnChildEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperChildEvent(KFileFilterCombo* self, QChildEvent* event);
void KFileFilterCombo_CustomEvent(KFileFilterCombo* self, QEvent* event);
void KFileFilterCombo_OnCustomEvent(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperCustomEvent(KFileFilterCombo* self, QEvent* event);
void KFileFilterCombo_ConnectNotify(KFileFilterCombo* self, const QMetaMethod* signal);
void KFileFilterCombo_OnConnectNotify(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperConnectNotify(KFileFilterCombo* self, const QMetaMethod* signal);
void KFileFilterCombo_DisconnectNotify(KFileFilterCombo* self, const QMetaMethod* signal);
void KFileFilterCombo_OnDisconnectNotify(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperDisconnectNotify(KFileFilterCombo* self, const QMetaMethod* signal);
void KFileFilterCombo_SetCompletionObject(KFileFilterCombo* self, KCompletion* completionObject, bool handleSignals);
void KFileFilterCombo_OnSetCompletionObject(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetCompletionObject(KFileFilterCombo* self, KCompletion* completionObject, bool handleSignals);
void KFileFilterCombo_SetHandleSignals(KFileFilterCombo* self, bool handle);
void KFileFilterCombo_OnSetHandleSignals(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetHandleSignals(KFileFilterCombo* self, bool handle);
void KFileFilterCombo_SetCompletionMode(KFileFilterCombo* self, int mode);
void KFileFilterCombo_OnSetCompletionMode(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetCompletionMode(KFileFilterCombo* self, int mode);
void KFileFilterCombo_VirtualHook(KFileFilterCombo* self, int id, void* data);
void KFileFilterCombo_OnVirtualHook(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperVirtualHook(KFileFilterCombo* self, int id, void* data);
void KFileFilterCombo_UpdateMicroFocus(KFileFilterCombo* self);
void KFileFilterCombo_OnUpdateMicroFocus(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperUpdateMicroFocus(KFileFilterCombo* self);
void KFileFilterCombo_Create(KFileFilterCombo* self);
void KFileFilterCombo_OnCreate(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperCreate(KFileFilterCombo* self);
void KFileFilterCombo_Destroy(KFileFilterCombo* self);
void KFileFilterCombo_OnDestroy(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperDestroy(KFileFilterCombo* self);
bool KFileFilterCombo_FocusNextChild(KFileFilterCombo* self);
void KFileFilterCombo_OnFocusNextChild(KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperFocusNextChild(KFileFilterCombo* self);
bool KFileFilterCombo_FocusPreviousChild(KFileFilterCombo* self);
void KFileFilterCombo_OnFocusPreviousChild(KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperFocusPreviousChild(KFileFilterCombo* self);
QObject* KFileFilterCombo_Sender(const KFileFilterCombo* self);
void KFileFilterCombo_OnSender(const KFileFilterCombo* self, intptr_t slot);
QObject* KFileFilterCombo_SuperSender(const KFileFilterCombo* self);
int KFileFilterCombo_SenderSignalIndex(const KFileFilterCombo* self);
void KFileFilterCombo_OnSenderSignalIndex(const KFileFilterCombo* self, intptr_t slot);
int KFileFilterCombo_SuperSenderSignalIndex(const KFileFilterCombo* self);
int KFileFilterCombo_Receivers(const KFileFilterCombo* self, const char* signal);
void KFileFilterCombo_OnReceivers(const KFileFilterCombo* self, intptr_t slot);
int KFileFilterCombo_SuperReceivers(const KFileFilterCombo* self, const char* signal);
bool KFileFilterCombo_IsSignalConnected(const KFileFilterCombo* self, const QMetaMethod* signal);
void KFileFilterCombo_OnIsSignalConnected(const KFileFilterCombo* self, intptr_t slot);
bool KFileFilterCombo_SuperIsSignalConnected(const KFileFilterCombo* self, const QMetaMethod* signal);
double KFileFilterCombo_GetDecodedMetricF(const KFileFilterCombo* self, int metricA, int metricB);
void KFileFilterCombo_OnGetDecodedMetricF(const KFileFilterCombo* self, intptr_t slot);
double KFileFilterCombo_SuperGetDecodedMetricF(const KFileFilterCombo* self, int metricA, int metricB);
libqt_map /* of int to libqt_list of QKeySequence* */ KFileFilterCombo_KeyBindingMap(const KFileFilterCombo* self);
void KFileFilterCombo_OnKeyBindingMap(const KFileFilterCombo* self, intptr_t slot);
libqt_map /* of int to libqt_list of QKeySequence* */ KFileFilterCombo_SuperKeyBindingMap(const KFileFilterCombo* self);
void KFileFilterCombo_SetKeyBindingMap(KFileFilterCombo* self, libqt_map /* of int to libqt_list of QKeySequence* */ keyBindingMap);
void KFileFilterCombo_OnSetKeyBindingMap(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetKeyBindingMap(KFileFilterCombo* self, libqt_map /* of int to libqt_list of QKeySequence* */ keyBindingMap);
void KFileFilterCombo_SetDelegate(KFileFilterCombo* self, KCompletionBase* delegate);
void KFileFilterCombo_OnSetDelegate(KFileFilterCombo* self, intptr_t slot);
void KFileFilterCombo_SuperSetDelegate(KFileFilterCombo* self, KCompletionBase* delegate);
KCompletionBase* KFileFilterCombo_Delegate(const KFileFilterCombo* self);
void KFileFilterCombo_OnDelegate(const KFileFilterCombo* self, intptr_t slot);
KCompletionBase* KFileFilterCombo_SuperDelegate(const KFileFilterCombo* self);
void KFileFilterCombo_Delete(KFileFilterCombo* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
