#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBAUTOCORRECTIONSETTINGS_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBAUTOCORRECTIONSETTINGS_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAutoCorrectionCore__AutoCorrectionSettings)
typedef TextAutoCorrectionCore::AutoCorrectionSettings TextAutoCorrectionCore__AutoCorrectionSettings;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes)
typedef TextAutoCorrectionCore::AutoCorrectionUtils::TypographicQuotes TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes;
#endif
#else
typedef struct QChar QChar;
typedef struct TextAutoCorrectionCore__AutoCorrectionSettings TextAutoCorrectionCore__AutoCorrectionSettings;
typedef struct TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes;
#endif

TextAutoCorrectionCore__AutoCorrectionSettings* TextAutoCorrectionCore__AutoCorrectionSettings_new();
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsEnabledAutoCorrection(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsUppercaseFirstCharOfSentence(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsFixTwoUppercaseChars(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsSingleSpaces(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsAutoFractions(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsCapitalizeWeekDays(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsReplaceDoubleQuotes(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsReplaceSingleQuotes(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsAdvancedAutocorrect(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsAutoFormatUrl(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsAutoBoldUnderline(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsSuperScript(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsAddNonBreakingSpace(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsReplaceDoubleQuotesByFrenchQuotes(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* TextAutoCorrectionCore__AutoCorrectionSettings_TypographicSingleQuotes(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* TextAutoCorrectionCore__AutoCorrectionSettings_TypographicDoubleQuotes(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetTypographicSingleQuotes(TextAutoCorrectionCore__AutoCorrectionSettings* self, TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* singleQuote);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetTypographicDoubleQuotes(TextAutoCorrectionCore__AutoCorrectionSettings* self, TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* doubleQuote);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetAutoFormatUrl(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetAutoBoldUnderline(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetSuperScript(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetAddNonBreakingSpace(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetCapitalizeWeekDays(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetReplaceDoubleQuotes(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetReplaceSingleQuotes(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetAdvancedAutocorrect(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetEnabledAutoCorrection(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetReplaceDoubleQuotesByFrenchQuotes(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool b);
void TextAutoCorrectionCore__AutoCorrectionSettings_ReadConfig(TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_WriteConfig(TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetAutoFractions(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool newAutoFractions);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetSingleSpaces(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool newSingleSpaces);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetFixTwoUppercaseChars(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool newFixTwoUppercaseChars);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetUppercaseFirstCharOfSentence(TextAutoCorrectionCore__AutoCorrectionSettings* self, bool newUppercaseFirstCharOfSentence);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetUpperCaseExceptions(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_list /* set of libqt_string */ exceptions);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetTwoUpperLetterExceptions(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_list /* set of libqt_string */ exceptions);
libqt_list /* set of libqt_string */ TextAutoCorrectionCore__AutoCorrectionSettings_UpperCaseExceptions(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
libqt_list /* set of libqt_string */ TextAutoCorrectionCore__AutoCorrectionSettings_TwoUpperLetterExceptions(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetLanguage(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string lang);
libqt_string TextAutoCorrectionCore__AutoCorrectionSettings_Language(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_IsFrenchLanguage(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetAutocorrectEntries(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_map /* of libqt_string to libqt_string */ entries);
libqt_map /* of libqt_string to libqt_string */ TextAutoCorrectionCore__AutoCorrectionSettings_AutocorrectEntries(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
bool TextAutoCorrectionCore__AutoCorrectionSettings_AddAutoCorrect(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string currentWord, const libqt_string replaceWord);
QChar* TextAutoCorrectionCore__AutoCorrectionSettings_NonBreakingSpace(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetNonBreakingSpace(TextAutoCorrectionCore__AutoCorrectionSettings* self, const QChar* newNonBreakingSpace);
libqt_map /* of libqt_string to libqt_string */ TextAutoCorrectionCore__AutoCorrectionSettings_SuperScriptEntries(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetSuperScriptEntries(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_map /* of libqt_string to libqt_string */ newSuperScriptEntries);
void TextAutoCorrectionCore__AutoCorrectionSettings_WriteAutoCorrectionFile(TextAutoCorrectionCore__AutoCorrectionSettings* self);
int TextAutoCorrectionCore__AutoCorrectionSettings_MaxFindStringLength(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
int TextAutoCorrectionCore__AutoCorrectionSettings_MinFindStringLength(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_LoadLocalFileName(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string localFileName, const libqt_string fname);
void TextAutoCorrectionCore__AutoCorrectionSettings_LoadGlobalFileName(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string fname);
TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* TextAutoCorrectionCore__AutoCorrectionSettings_DoubleFrenchQuotes(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetDoubleFrenchQuotes(TextAutoCorrectionCore__AutoCorrectionSettings* self, const TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* newDoubleFrenchQuotes);
libqt_string TextAutoCorrectionCore__AutoCorrectionSettings_CustomWritablePath(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetCustomWritablePath(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string path);
libqt_string TextAutoCorrectionCore__AutoCorrectionSettings_CustomSystemPath(const TextAutoCorrectionCore__AutoCorrectionSettings* self);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetCustomSystemPath(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string path);
void TextAutoCorrectionCore__AutoCorrectionSettings_SetLanguage2(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string lang, bool forceGlobal);
void TextAutoCorrectionCore__AutoCorrectionSettings_WriteAutoCorrectionFile1(TextAutoCorrectionCore__AutoCorrectionSettings* self, const libqt_string filename);
void TextAutoCorrectionCore__AutoCorrectionSettings_Delete(TextAutoCorrectionCore__AutoCorrectionSettings* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
