#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBAUTOCORRECTIONLANGUAGE_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBAUTOCORRECTIONLANGUAGE_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAutoCorrectionWidgets__AutoCorrectionLanguage)
typedef TextAutoCorrectionWidgets::AutoCorrectionLanguage TextAutoCorrectionWidgets__AutoCorrectionLanguage;
#endif
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QComboBox QComboBox;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionComboBox QStyleOptionComboBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextAutoCorrectionWidgets__AutoCorrectionLanguage TextAutoCorrectionWidgets__AutoCorrectionLanguage;
#endif

TextAutoCorrectionWidgets__AutoCorrectionLanguage* TextAutoCorrectionWidgets__AutoCorrectionLanguage_new(QWidget* parent);
libqt_string TextAutoCorrectionWidgets__AutoCorrectionLanguage_Language(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int index);
libqt_string TextAutoCorrectionWidgets__AutoCorrectionLanguage_Language2(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SetLanguage(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const libqt_string language);
QMetaObject* TextAutoCorrectionWidgets__AutoCorrectionLanguage_MetaObject(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMetaObject(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QMetaObject* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMetaObject(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void* TextAutoCorrectionWidgets__AutoCorrectionLanguage_Metacast(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const char* param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMetacast(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMetacast(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const char* param1);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_Metacall(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1, int param2, void** param3);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMetacall(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMetacall(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1, int param2, void** param3);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SetModel(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QAbstractItemModel* model);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnSetModel(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperSetModel(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QAbstractItemModel* model);
QSize* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SizeHint(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnSizeHint(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QSize* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperSizeHint(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
QSize* TextAutoCorrectionWidgets__AutoCorrectionLanguage_MinimumSizeHint(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMinimumSizeHint(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QSize* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMinimumSizeHint(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ShowPopup(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnShowPopup(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperShowPopup(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_HidePopup(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnHidePopup(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperHidePopup(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_Event(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* event);
QVariant* TextAutoCorrectionWidgets__AutoCorrectionLanguage_InputMethodQuery(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnInputMethodQuery(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QVariant* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperInputMethodQuery(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_FocusInEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QFocusEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnFocusInEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperFocusInEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QFocusEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_FocusOutEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QFocusEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnFocusOutEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperFocusOutEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QFocusEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ChangeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnChangeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperChangeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ResizeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QResizeEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnResizeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperResizeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QResizeEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_PaintEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QPaintEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnPaintEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperPaintEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QPaintEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ShowEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QShowEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnShowEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperShowEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QShowEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_HideEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QHideEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnHideEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperHideEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QHideEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_MousePressEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMousePressEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMousePressEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_MouseReleaseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMouseReleaseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMouseReleaseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_KeyPressEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QKeyEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnKeyPressEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperKeyPressEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QKeyEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_KeyReleaseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QKeyEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnKeyReleaseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperKeyReleaseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QKeyEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_WheelEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QWheelEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnWheelEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperWheelEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QWheelEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ContextMenuEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QContextMenuEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnContextMenuEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperContextMenuEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QContextMenuEvent* e);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_InputMethodEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QInputMethodEvent* param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnInputMethodEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperInputMethodEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QInputMethodEvent* param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_InitStyleOption(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QStyleOptionComboBox* option);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnInitStyleOption(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperInitStyleOption(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QStyleOptionComboBox* option);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_DevType(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDevType(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDevType(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SetVisible(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, bool visible);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnSetVisible(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperSetVisible(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, bool visible);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_HeightForWidth(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnHeightForWidth(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperHeightForWidth(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_HasHeightForWidth(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnHasHeightForWidth(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperHasHeightForWidth(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
QPaintEngine* TextAutoCorrectionWidgets__AutoCorrectionLanguage_PaintEngine(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnPaintEngine(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QPaintEngine* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperPaintEngine(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_MouseDoubleClickEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMouseDoubleClickEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMouseDoubleClickEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_MouseMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMouseMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMouseMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMouseEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_EnterEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEnterEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnEnterEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperEnterEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEnterEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_LeaveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnLeaveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperLeaveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_MoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMoveEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QMoveEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_CloseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QCloseEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnCloseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperCloseEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QCloseEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_TabletEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QTabletEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnTabletEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperTabletEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QTabletEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ActionEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QActionEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnActionEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperActionEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QActionEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_DragEnterEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDragEnterEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDragEnterEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDragEnterEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDragEnterEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_DragMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDragMoveEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDragMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDragMoveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDragMoveEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_DragLeaveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDragLeaveEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDragLeaveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDragLeaveEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDragLeaveEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_DropEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDropEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDropEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDropEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QDropEvent* event);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_NativeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const libqt_string eventType, void* message, intptr_t* result);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnNativeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperNativeEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const libqt_string eventType, void* message, intptr_t* result);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_Metric(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnMetric(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperMetric(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int param1);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_InitPainter(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QPainter* painter);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnInitPainter(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperInitPainter(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QPainter* painter);
QPaintDevice* TextAutoCorrectionWidgets__AutoCorrectionLanguage_Redirected(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QPoint* offset);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnRedirected(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QPaintDevice* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperRedirected(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QPoint* offset);
QPainter* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SharedPainter(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnSharedPainter(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QPainter* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperSharedPainter(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_FocusNextPrevChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, bool next);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnFocusNextPrevChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperFocusNextPrevChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, bool next);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_EventFilter(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QObject* watched, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnEventFilter(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperEventFilter(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QObject* watched, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_TimerEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QTimerEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnTimerEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperTimerEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QTimerEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ChildEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QChildEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnChildEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperChildEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QChildEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_CustomEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnCustomEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperCustomEvent(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, QEvent* event);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_ConnectNotify(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const QMetaMethod* signal);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnConnectNotify(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperConnectNotify(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const QMetaMethod* signal);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_DisconnectNotify(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const QMetaMethod* signal);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDisconnectNotify(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDisconnectNotify(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const QMetaMethod* signal);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_UpdateMicroFocus(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnUpdateMicroFocus(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperUpdateMicroFocus(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_Create(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnCreate(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperCreate(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_Destroy(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnDestroy(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperDestroy(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_FocusNextChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnFocusNextChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperFocusNextChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_FocusPreviousChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnFocusPreviousChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperFocusPreviousChild(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
QObject* TextAutoCorrectionWidgets__AutoCorrectionLanguage_Sender(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnSender(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
QObject* TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperSender(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SenderSignalIndex(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnSenderSignalIndex(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperSenderSignalIndex(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_Receivers(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const char* signal);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnReceivers(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
int TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperReceivers(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const char* signal);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_IsSignalConnected(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const QMetaMethod* signal);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnIsSignalConnected(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
bool TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperIsSignalConnected(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, const QMetaMethod* signal);
double TextAutoCorrectionWidgets__AutoCorrectionLanguage_GetDecodedMetricF(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int metricA, int metricB);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_OnGetDecodedMetricF(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, intptr_t slot);
double TextAutoCorrectionWidgets__AutoCorrectionLanguage_SuperGetDecodedMetricF(const TextAutoCorrectionWidgets__AutoCorrectionLanguage* self, int metricA, int metricB);
void TextAutoCorrectionWidgets__AutoCorrectionLanguage_Delete(TextAutoCorrectionWidgets__AutoCorrectionLanguage* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
