#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBEMOJIPROXYMODEL_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBEMOJIPROXYMODEL_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEmoticonsCore__EmojiProxyModel)
typedef TextEmoticonsCore::EmojiProxyModel TextEmoticonsCore__EmojiProxyModel;
#endif
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractProxyModel QAbstractProxyModel;
typedef struct QChildEvent QChildEvent;
typedef struct QDataStream QDataStream;
typedef struct QEvent QEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QModelRoleDataSpan QModelRoleDataSpan;
typedef struct QObject QObject;
typedef struct QSize QSize;
typedef struct QSortFilterProxyModel QSortFilterProxyModel;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct TextEmoticonsCore__EmojiProxyModel TextEmoticonsCore__EmojiProxyModel;
#endif

TextEmoticonsCore__EmojiProxyModel* TextEmoticonsCore__EmojiProxyModel_new();
TextEmoticonsCore__EmojiProxyModel* TextEmoticonsCore__EmojiProxyModel_new2(QObject* parent);
QMetaObject* TextEmoticonsCore__EmojiProxyModel_MetaObject(const TextEmoticonsCore__EmojiProxyModel* self);
void* TextEmoticonsCore__EmojiProxyModel_Metacast(TextEmoticonsCore__EmojiProxyModel* self, const char* param1);
int TextEmoticonsCore__EmojiProxyModel_Metacall(TextEmoticonsCore__EmojiProxyModel* self, int param1, int param2, void** param3);
libqt_string TextEmoticonsCore__EmojiProxyModel_Category(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_SetCategory(TextEmoticonsCore__EmojiProxyModel* self, const libqt_string newCategories);
libqt_list /* of libqt_string */ TextEmoticonsCore__EmojiProxyModel_RecentEmoticons(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_SetRecentEmoticons(TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of libqt_string */ newRecentEmoticons);
libqt_string TextEmoticonsCore__EmojiProxyModel_SearchIdentifier(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_SetSearchIdentifier(TextEmoticonsCore__EmojiProxyModel* self, const libqt_string newSearchIdentifier);
bool TextEmoticonsCore__EmojiProxyModel_FilterAcceptsRow(const TextEmoticonsCore__EmojiProxyModel* self, int source_row, const QModelIndex* source_parent);
bool TextEmoticonsCore__EmojiProxyModel_LessThan(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* left, const QModelIndex* right);
void TextEmoticonsCore__EmojiProxyModel_OnMetaObject(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QMetaObject* TextEmoticonsCore__EmojiProxyModel_SuperMetaObject(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnMetacast(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void* TextEmoticonsCore__EmojiProxyModel_SuperMetacast(TextEmoticonsCore__EmojiProxyModel* self, const char* param1);
void TextEmoticonsCore__EmojiProxyModel_OnMetacall(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperMetacall(TextEmoticonsCore__EmojiProxyModel* self, int param1, int param2, void** param3);
void TextEmoticonsCore__EmojiProxyModel_OnFilterAcceptsRow(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperFilterAcceptsRow(const TextEmoticonsCore__EmojiProxyModel* self, int source_row, const QModelIndex* source_parent);
void TextEmoticonsCore__EmojiProxyModel_OnLessThan(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperLessThan(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* left, const QModelIndex* right);
void TextEmoticonsCore__EmojiProxyModel_SetSourceModel(TextEmoticonsCore__EmojiProxyModel* self, QAbstractItemModel* sourceModel);
void TextEmoticonsCore__EmojiProxyModel_OnSetSourceModel(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperSetSourceModel(TextEmoticonsCore__EmojiProxyModel* self, QAbstractItemModel* sourceModel);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_MapToSource(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* proxyIndex);
void TextEmoticonsCore__EmojiProxyModel_OnMapToSource(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperMapToSource(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* proxyIndex);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_MapFromSource(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceIndex);
void TextEmoticonsCore__EmojiProxyModel_OnMapFromSource(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperMapFromSource(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceIndex);
QItemSelection* TextEmoticonsCore__EmojiProxyModel_MapSelectionToSource(const TextEmoticonsCore__EmojiProxyModel* self, const QItemSelection* proxySelection);
void TextEmoticonsCore__EmojiProxyModel_OnMapSelectionToSource(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QItemSelection* TextEmoticonsCore__EmojiProxyModel_SuperMapSelectionToSource(const TextEmoticonsCore__EmojiProxyModel* self, const QItemSelection* proxySelection);
QItemSelection* TextEmoticonsCore__EmojiProxyModel_MapSelectionFromSource(const TextEmoticonsCore__EmojiProxyModel* self, const QItemSelection* sourceSelection);
void TextEmoticonsCore__EmojiProxyModel_OnMapSelectionFromSource(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QItemSelection* TextEmoticonsCore__EmojiProxyModel_SuperMapSelectionFromSource(const TextEmoticonsCore__EmojiProxyModel* self, const QItemSelection* sourceSelection);
bool TextEmoticonsCore__EmojiProxyModel_FilterAcceptsColumn(const TextEmoticonsCore__EmojiProxyModel* self, int source_column, const QModelIndex* source_parent);
void TextEmoticonsCore__EmojiProxyModel_OnFilterAcceptsColumn(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperFilterAcceptsColumn(const TextEmoticonsCore__EmojiProxyModel* self, int source_column, const QModelIndex* source_parent);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_Index(const TextEmoticonsCore__EmojiProxyModel* self, int row, int column, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnIndex(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperIndex(const TextEmoticonsCore__EmojiProxyModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_Parent(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* child);
void TextEmoticonsCore__EmojiProxyModel_OnParent(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperParent(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* child);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_Sibling(const TextEmoticonsCore__EmojiProxyModel* self, int row, int column, const QModelIndex* idx);
void TextEmoticonsCore__EmojiProxyModel_OnSibling(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperSibling(const TextEmoticonsCore__EmojiProxyModel* self, int row, int column, const QModelIndex* idx);
int TextEmoticonsCore__EmojiProxyModel_RowCount(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnRowCount(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperRowCount(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
int TextEmoticonsCore__EmojiProxyModel_ColumnCount(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnColumnCount(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperColumnCount(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
bool TextEmoticonsCore__EmojiProxyModel_HasChildren(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnHasChildren(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperHasChildren(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
QVariant* TextEmoticonsCore__EmojiProxyModel_Data(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, int role);
void TextEmoticonsCore__EmojiProxyModel_OnData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QVariant* TextEmoticonsCore__EmojiProxyModel_SuperData(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, int role);
bool TextEmoticonsCore__EmojiProxyModel_SetData(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
void TextEmoticonsCore__EmojiProxyModel_OnSetData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperSetData(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
QVariant* TextEmoticonsCore__EmojiProxyModel_HeaderData(const TextEmoticonsCore__EmojiProxyModel* self, int section, int orientation, int role);
void TextEmoticonsCore__EmojiProxyModel_OnHeaderData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QVariant* TextEmoticonsCore__EmojiProxyModel_SuperHeaderData(const TextEmoticonsCore__EmojiProxyModel* self, int section, int orientation, int role);
bool TextEmoticonsCore__EmojiProxyModel_SetHeaderData(TextEmoticonsCore__EmojiProxyModel* self, int section, int orientation, const QVariant* value, int role);
void TextEmoticonsCore__EmojiProxyModel_OnSetHeaderData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperSetHeaderData(TextEmoticonsCore__EmojiProxyModel* self, int section, int orientation, const QVariant* value, int role);
QMimeData* TextEmoticonsCore__EmojiProxyModel_MimeData(const TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
void TextEmoticonsCore__EmojiProxyModel_OnMimeData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QMimeData* TextEmoticonsCore__EmojiProxyModel_SuperMimeData(const TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
bool TextEmoticonsCore__EmojiProxyModel_DropMimeData(TextEmoticonsCore__EmojiProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnDropMimeData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperDropMimeData(TextEmoticonsCore__EmojiProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
bool TextEmoticonsCore__EmojiProxyModel_InsertRows(TextEmoticonsCore__EmojiProxyModel* self, int row, int count, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnInsertRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperInsertRows(TextEmoticonsCore__EmojiProxyModel* self, int row, int count, const QModelIndex* parent);
bool TextEmoticonsCore__EmojiProxyModel_InsertColumns(TextEmoticonsCore__EmojiProxyModel* self, int column, int count, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnInsertColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperInsertColumns(TextEmoticonsCore__EmojiProxyModel* self, int column, int count, const QModelIndex* parent);
bool TextEmoticonsCore__EmojiProxyModel_RemoveRows(TextEmoticonsCore__EmojiProxyModel* self, int row, int count, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnRemoveRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperRemoveRows(TextEmoticonsCore__EmojiProxyModel* self, int row, int count, const QModelIndex* parent);
bool TextEmoticonsCore__EmojiProxyModel_RemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, int column, int count, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, int column, int count, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_FetchMore(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnFetchMore(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperFetchMore(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
bool TextEmoticonsCore__EmojiProxyModel_CanFetchMore(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnCanFetchMore(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperCanFetchMore(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent);
int TextEmoticonsCore__EmojiProxyModel_Flags(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
void TextEmoticonsCore__EmojiProxyModel_OnFlags(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperFlags(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_Buddy(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
void TextEmoticonsCore__EmojiProxyModel_OnBuddy(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperBuddy(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
libqt_list /* of QModelIndex* */ TextEmoticonsCore__EmojiProxyModel_Match(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
void TextEmoticonsCore__EmojiProxyModel_OnMatch(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ TextEmoticonsCore__EmojiProxyModel_SuperMatch(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
QSize* TextEmoticonsCore__EmojiProxyModel_Span(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
void TextEmoticonsCore__EmojiProxyModel_OnSpan(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QSize* TextEmoticonsCore__EmojiProxyModel_SuperSpan(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
void TextEmoticonsCore__EmojiProxyModel_Sort(TextEmoticonsCore__EmojiProxyModel* self, int column, int order);
void TextEmoticonsCore__EmojiProxyModel_OnSort(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperSort(TextEmoticonsCore__EmojiProxyModel* self, int column, int order);
libqt_list /* of libqt_string */ TextEmoticonsCore__EmojiProxyModel_MimeTypes(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnMimeTypes(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
libqt_list /* of libqt_string */ TextEmoticonsCore__EmojiProxyModel_SuperMimeTypes(const TextEmoticonsCore__EmojiProxyModel* self);
int TextEmoticonsCore__EmojiProxyModel_SupportedDropActions(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnSupportedDropActions(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperSupportedDropActions(const TextEmoticonsCore__EmojiProxyModel* self);
bool TextEmoticonsCore__EmojiProxyModel_Submit(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnSubmit(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperSubmit(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_Revert(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnRevert(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperRevert(TextEmoticonsCore__EmojiProxyModel* self);
libqt_map /* of int to QVariant* */ TextEmoticonsCore__EmojiProxyModel_ItemData(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
void TextEmoticonsCore__EmojiProxyModel_OnItemData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
libqt_map /* of int to QVariant* */ TextEmoticonsCore__EmojiProxyModel_SuperItemData(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
bool TextEmoticonsCore__EmojiProxyModel_SetItemData(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
void TextEmoticonsCore__EmojiProxyModel_OnSetItemData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperSetItemData(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
bool TextEmoticonsCore__EmojiProxyModel_ClearItemData(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
void TextEmoticonsCore__EmojiProxyModel_OnClearItemData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperClearItemData(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index);
bool TextEmoticonsCore__EmojiProxyModel_CanDropMimeData(const TextEmoticonsCore__EmojiProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void TextEmoticonsCore__EmojiProxyModel_OnCanDropMimeData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperCanDropMimeData(const TextEmoticonsCore__EmojiProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
int TextEmoticonsCore__EmojiProxyModel_SupportedDragActions(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnSupportedDragActions(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperSupportedDragActions(const TextEmoticonsCore__EmojiProxyModel* self);
libqt_map /* of int to libqt_string */ TextEmoticonsCore__EmojiProxyModel_RoleNames(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnRoleNames(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
libqt_map /* of int to libqt_string */ TextEmoticonsCore__EmojiProxyModel_SuperRoleNames(const TextEmoticonsCore__EmojiProxyModel* self);
bool TextEmoticonsCore__EmojiProxyModel_MoveRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
void TextEmoticonsCore__EmojiProxyModel_OnMoveRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperMoveRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
bool TextEmoticonsCore__EmojiProxyModel_MoveColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void TextEmoticonsCore__EmojiProxyModel_OnMoveColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperMoveColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void TextEmoticonsCore__EmojiProxyModel_MultiData(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void TextEmoticonsCore__EmojiProxyModel_OnMultiData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperMultiData(const TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void TextEmoticonsCore__EmojiProxyModel_ResetInternalData(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnResetInternalData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperResetInternalData(TextEmoticonsCore__EmojiProxyModel* self);
bool TextEmoticonsCore__EmojiProxyModel_Event(TextEmoticonsCore__EmojiProxyModel* self, QEvent* event);
void TextEmoticonsCore__EmojiProxyModel_OnEvent(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperEvent(TextEmoticonsCore__EmojiProxyModel* self, QEvent* event);
bool TextEmoticonsCore__EmojiProxyModel_EventFilter(TextEmoticonsCore__EmojiProxyModel* self, QObject* watched, QEvent* event);
void TextEmoticonsCore__EmojiProxyModel_OnEventFilter(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperEventFilter(TextEmoticonsCore__EmojiProxyModel* self, QObject* watched, QEvent* event);
void TextEmoticonsCore__EmojiProxyModel_TimerEvent(TextEmoticonsCore__EmojiProxyModel* self, QTimerEvent* event);
void TextEmoticonsCore__EmojiProxyModel_OnTimerEvent(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperTimerEvent(TextEmoticonsCore__EmojiProxyModel* self, QTimerEvent* event);
void TextEmoticonsCore__EmojiProxyModel_ChildEvent(TextEmoticonsCore__EmojiProxyModel* self, QChildEvent* event);
void TextEmoticonsCore__EmojiProxyModel_OnChildEvent(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperChildEvent(TextEmoticonsCore__EmojiProxyModel* self, QChildEvent* event);
void TextEmoticonsCore__EmojiProxyModel_CustomEvent(TextEmoticonsCore__EmojiProxyModel* self, QEvent* event);
void TextEmoticonsCore__EmojiProxyModel_OnCustomEvent(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperCustomEvent(TextEmoticonsCore__EmojiProxyModel* self, QEvent* event);
void TextEmoticonsCore__EmojiProxyModel_ConnectNotify(TextEmoticonsCore__EmojiProxyModel* self, const QMetaMethod* signal);
void TextEmoticonsCore__EmojiProxyModel_OnConnectNotify(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperConnectNotify(TextEmoticonsCore__EmojiProxyModel* self, const QMetaMethod* signal);
void TextEmoticonsCore__EmojiProxyModel_DisconnectNotify(TextEmoticonsCore__EmojiProxyModel* self, const QMetaMethod* signal);
void TextEmoticonsCore__EmojiProxyModel_OnDisconnectNotify(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperDisconnectNotify(TextEmoticonsCore__EmojiProxyModel* self, const QMetaMethod* signal);
void TextEmoticonsCore__EmojiProxyModel_InvalidateFilter(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnInvalidateFilter(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperInvalidateFilter(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_InvalidateRowsFilter(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnInvalidateRowsFilter(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperInvalidateRowsFilter(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_InvalidateColumnsFilter(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnInvalidateColumnsFilter(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperInvalidateColumnsFilter(TextEmoticonsCore__EmojiProxyModel* self);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_CreateSourceIndex(const TextEmoticonsCore__EmojiProxyModel* self, int row, int col, void* internalPtr);
void TextEmoticonsCore__EmojiProxyModel_OnCreateSourceIndex(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperCreateSourceIndex(const TextEmoticonsCore__EmojiProxyModel* self, int row, int col, void* internalPtr);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_CreateIndex(const TextEmoticonsCore__EmojiProxyModel* self, int row, int column);
void TextEmoticonsCore__EmojiProxyModel_OnCreateIndex(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QModelIndex* TextEmoticonsCore__EmojiProxyModel_SuperCreateIndex(const TextEmoticonsCore__EmojiProxyModel* self, int row, int column);
void TextEmoticonsCore__EmojiProxyModel_EncodeData(const TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
void TextEmoticonsCore__EmojiProxyModel_OnEncodeData(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEncodeData(const TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
bool TextEmoticonsCore__EmojiProxyModel_DecodeData(TextEmoticonsCore__EmojiProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void TextEmoticonsCore__EmojiProxyModel_OnDecodeData(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperDecodeData(TextEmoticonsCore__EmojiProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void TextEmoticonsCore__EmojiProxyModel_BeginInsertRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_OnBeginInsertRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperBeginInsertRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_EndInsertRows(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndInsertRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndInsertRows(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_BeginRemoveRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_OnBeginRemoveRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperBeginRemoveRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_EndRemoveRows(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndRemoveRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndRemoveRows(TextEmoticonsCore__EmojiProxyModel* self);
bool TextEmoticonsCore__EmojiProxyModel_BeginMoveRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void TextEmoticonsCore__EmojiProxyModel_OnBeginMoveRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperBeginMoveRows(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void TextEmoticonsCore__EmojiProxyModel_EndMoveRows(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndMoveRows(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndMoveRows(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_BeginInsertColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_OnBeginInsertColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperBeginInsertColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_EndInsertColumns(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndInsertColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndInsertColumns(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_BeginRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_OnBeginRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperBeginRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* parent, int first, int last);
void TextEmoticonsCore__EmojiProxyModel_EndRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndRemoveColumns(TextEmoticonsCore__EmojiProxyModel* self);
bool TextEmoticonsCore__EmojiProxyModel_BeginMoveColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void TextEmoticonsCore__EmojiProxyModel_OnBeginMoveColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperBeginMoveColumns(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void TextEmoticonsCore__EmojiProxyModel_EndMoveColumns(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndMoveColumns(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndMoveColumns(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_BeginResetModel(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnBeginResetModel(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperBeginResetModel(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_EndResetModel(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnEndResetModel(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperEndResetModel(TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_ChangePersistentIndex(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void TextEmoticonsCore__EmojiProxyModel_OnChangePersistentIndex(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperChangePersistentIndex(TextEmoticonsCore__EmojiProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void TextEmoticonsCore__EmojiProxyModel_ChangePersistentIndexList(TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
void TextEmoticonsCore__EmojiProxyModel_OnChangePersistentIndexList(TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
void TextEmoticonsCore__EmojiProxyModel_SuperChangePersistentIndexList(TextEmoticonsCore__EmojiProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
libqt_list /* of QModelIndex* */ TextEmoticonsCore__EmojiProxyModel_PersistentIndexList(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnPersistentIndexList(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ TextEmoticonsCore__EmojiProxyModel_SuperPersistentIndexList(const TextEmoticonsCore__EmojiProxyModel* self);
QObject* TextEmoticonsCore__EmojiProxyModel_Sender(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnSender(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
QObject* TextEmoticonsCore__EmojiProxyModel_SuperSender(const TextEmoticonsCore__EmojiProxyModel* self);
int TextEmoticonsCore__EmojiProxyModel_SenderSignalIndex(const TextEmoticonsCore__EmojiProxyModel* self);
void TextEmoticonsCore__EmojiProxyModel_OnSenderSignalIndex(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperSenderSignalIndex(const TextEmoticonsCore__EmojiProxyModel* self);
int TextEmoticonsCore__EmojiProxyModel_Receivers(const TextEmoticonsCore__EmojiProxyModel* self, const char* signal);
void TextEmoticonsCore__EmojiProxyModel_OnReceivers(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
int TextEmoticonsCore__EmojiProxyModel_SuperReceivers(const TextEmoticonsCore__EmojiProxyModel* self, const char* signal);
bool TextEmoticonsCore__EmojiProxyModel_IsSignalConnected(const TextEmoticonsCore__EmojiProxyModel* self, const QMetaMethod* signal);
void TextEmoticonsCore__EmojiProxyModel_OnIsSignalConnected(const TextEmoticonsCore__EmojiProxyModel* self, intptr_t slot);
bool TextEmoticonsCore__EmojiProxyModel_SuperIsSignalConnected(const TextEmoticonsCore__EmojiProxyModel* self, const QMetaMethod* signal);
void TextEmoticonsCore__EmojiProxyModel_Delete(TextEmoticonsCore__EmojiProxyModel* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
