#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMARRESULTWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMARRESULTWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarAction)
typedef TextGrammarCheck::GrammarAction TextGrammarCheck__GrammarAction;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarError)
typedef TextGrammarCheck::GrammarError TextGrammarCheck__GrammarError;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarResultWidget)
typedef TextGrammarCheck::GrammarResultWidget TextGrammarCheck__GrammarResultWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextGrammarCheck__GrammarAction TextGrammarCheck__GrammarAction;
typedef struct TextGrammarCheck__GrammarError TextGrammarCheck__GrammarError;
typedef struct TextGrammarCheck__GrammarResultWidget TextGrammarCheck__GrammarResultWidget;
#endif

TextGrammarCheck__GrammarResultWidget* TextGrammarCheck__GrammarResultWidget_new(QWidget* parent);
TextGrammarCheck__GrammarResultWidget* TextGrammarCheck__GrammarResultWidget_new2();
QMetaObject* TextGrammarCheck__GrammarResultWidget_MetaObject(const TextGrammarCheck__GrammarResultWidget* self);
void* TextGrammarCheck__GrammarResultWidget_Metacast(TextGrammarCheck__GrammarResultWidget* self, const char* param1);
int TextGrammarCheck__GrammarResultWidget_Metacall(TextGrammarCheck__GrammarResultWidget* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammarResultWidget_SetText(TextGrammarCheck__GrammarResultWidget* self, const libqt_string str);
void TextGrammarCheck__GrammarResultWidget_CheckGrammar(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_ApplyGrammarResult(TextGrammarCheck__GrammarResultWidget* self, const libqt_list /* of TextGrammarCheck__GrammarError* */ infos);
void TextGrammarCheck__GrammarResultWidget_ReplaceText(TextGrammarCheck__GrammarResultWidget* self, const TextGrammarCheck__GrammarAction* act);
void TextGrammarCheck__GrammarResultWidget_Connect_ReplaceText(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_CheckAgain(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_Connect_CheckAgain(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_CloseChecker(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_Connect_CloseChecker(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_Configure(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_Connect_Configure(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_AddExtraWidget(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnMetaObject(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QMetaObject* TextGrammarCheck__GrammarResultWidget_SuperMetaObject(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnMetacast(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void* TextGrammarCheck__GrammarResultWidget_SuperMetacast(TextGrammarCheck__GrammarResultWidget* self, const char* param1);
void TextGrammarCheck__GrammarResultWidget_OnMetacall(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammarResultWidget_SuperMetacall(TextGrammarCheck__GrammarResultWidget* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammarResultWidget_OnCheckGrammar(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperCheckGrammar(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnAddExtraWidget(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperAddExtraWidget(TextGrammarCheck__GrammarResultWidget* self);
int TextGrammarCheck__GrammarResultWidget_DevType(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnDevType(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammarResultWidget_SuperDevType(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_SetVisible(TextGrammarCheck__GrammarResultWidget* self, bool visible);
void TextGrammarCheck__GrammarResultWidget_OnSetVisible(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperSetVisible(TextGrammarCheck__GrammarResultWidget* self, bool visible);
QSize* TextGrammarCheck__GrammarResultWidget_SizeHint(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnSizeHint(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QSize* TextGrammarCheck__GrammarResultWidget_SuperSizeHint(const TextGrammarCheck__GrammarResultWidget* self);
QSize* TextGrammarCheck__GrammarResultWidget_MinimumSizeHint(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnMinimumSizeHint(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QSize* TextGrammarCheck__GrammarResultWidget_SuperMinimumSizeHint(const TextGrammarCheck__GrammarResultWidget* self);
int TextGrammarCheck__GrammarResultWidget_HeightForWidth(const TextGrammarCheck__GrammarResultWidget* self, int param1);
void TextGrammarCheck__GrammarResultWidget_OnHeightForWidth(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammarResultWidget_SuperHeightForWidth(const TextGrammarCheck__GrammarResultWidget* self, int param1);
bool TextGrammarCheck__GrammarResultWidget_HasHeightForWidth(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnHasHeightForWidth(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperHasHeightForWidth(const TextGrammarCheck__GrammarResultWidget* self);
QPaintEngine* TextGrammarCheck__GrammarResultWidget_PaintEngine(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnPaintEngine(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QPaintEngine* TextGrammarCheck__GrammarResultWidget_SuperPaintEngine(const TextGrammarCheck__GrammarResultWidget* self);
bool TextGrammarCheck__GrammarResultWidget_Event(TextGrammarCheck__GrammarResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_MousePressEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnMousePressEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperMousePressEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_MouseReleaseEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnMouseReleaseEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperMouseReleaseEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_MouseDoubleClickEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnMouseDoubleClickEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperMouseDoubleClickEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_MouseMoveEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnMouseMoveEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperMouseMoveEvent(TextGrammarCheck__GrammarResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammarResultWidget_WheelEvent(TextGrammarCheck__GrammarResultWidget* self, QWheelEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnWheelEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperWheelEvent(TextGrammarCheck__GrammarResultWidget* self, QWheelEvent* event);
void TextGrammarCheck__GrammarResultWidget_KeyPressEvent(TextGrammarCheck__GrammarResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnKeyPressEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperKeyPressEvent(TextGrammarCheck__GrammarResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammarResultWidget_KeyReleaseEvent(TextGrammarCheck__GrammarResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnKeyReleaseEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperKeyReleaseEvent(TextGrammarCheck__GrammarResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammarResultWidget_FocusInEvent(TextGrammarCheck__GrammarResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnFocusInEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperFocusInEvent(TextGrammarCheck__GrammarResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammarResultWidget_FocusOutEvent(TextGrammarCheck__GrammarResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnFocusOutEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperFocusOutEvent(TextGrammarCheck__GrammarResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammarResultWidget_EnterEvent(TextGrammarCheck__GrammarResultWidget* self, QEnterEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnEnterEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperEnterEvent(TextGrammarCheck__GrammarResultWidget* self, QEnterEvent* event);
void TextGrammarCheck__GrammarResultWidget_LeaveEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnLeaveEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperLeaveEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_PaintEvent(TextGrammarCheck__GrammarResultWidget* self, QPaintEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnPaintEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperPaintEvent(TextGrammarCheck__GrammarResultWidget* self, QPaintEvent* event);
void TextGrammarCheck__GrammarResultWidget_MoveEvent(TextGrammarCheck__GrammarResultWidget* self, QMoveEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnMoveEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperMoveEvent(TextGrammarCheck__GrammarResultWidget* self, QMoveEvent* event);
void TextGrammarCheck__GrammarResultWidget_ResizeEvent(TextGrammarCheck__GrammarResultWidget* self, QResizeEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnResizeEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperResizeEvent(TextGrammarCheck__GrammarResultWidget* self, QResizeEvent* event);
void TextGrammarCheck__GrammarResultWidget_CloseEvent(TextGrammarCheck__GrammarResultWidget* self, QCloseEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnCloseEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperCloseEvent(TextGrammarCheck__GrammarResultWidget* self, QCloseEvent* event);
void TextGrammarCheck__GrammarResultWidget_ContextMenuEvent(TextGrammarCheck__GrammarResultWidget* self, QContextMenuEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnContextMenuEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperContextMenuEvent(TextGrammarCheck__GrammarResultWidget* self, QContextMenuEvent* event);
void TextGrammarCheck__GrammarResultWidget_TabletEvent(TextGrammarCheck__GrammarResultWidget* self, QTabletEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnTabletEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperTabletEvent(TextGrammarCheck__GrammarResultWidget* self, QTabletEvent* event);
void TextGrammarCheck__GrammarResultWidget_ActionEvent(TextGrammarCheck__GrammarResultWidget* self, QActionEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnActionEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperActionEvent(TextGrammarCheck__GrammarResultWidget* self, QActionEvent* event);
void TextGrammarCheck__GrammarResultWidget_DragEnterEvent(TextGrammarCheck__GrammarResultWidget* self, QDragEnterEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnDragEnterEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperDragEnterEvent(TextGrammarCheck__GrammarResultWidget* self, QDragEnterEvent* event);
void TextGrammarCheck__GrammarResultWidget_DragMoveEvent(TextGrammarCheck__GrammarResultWidget* self, QDragMoveEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnDragMoveEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperDragMoveEvent(TextGrammarCheck__GrammarResultWidget* self, QDragMoveEvent* event);
void TextGrammarCheck__GrammarResultWidget_DragLeaveEvent(TextGrammarCheck__GrammarResultWidget* self, QDragLeaveEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnDragLeaveEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperDragLeaveEvent(TextGrammarCheck__GrammarResultWidget* self, QDragLeaveEvent* event);
void TextGrammarCheck__GrammarResultWidget_DropEvent(TextGrammarCheck__GrammarResultWidget* self, QDropEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnDropEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperDropEvent(TextGrammarCheck__GrammarResultWidget* self, QDropEvent* event);
void TextGrammarCheck__GrammarResultWidget_ShowEvent(TextGrammarCheck__GrammarResultWidget* self, QShowEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnShowEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperShowEvent(TextGrammarCheck__GrammarResultWidget* self, QShowEvent* event);
void TextGrammarCheck__GrammarResultWidget_HideEvent(TextGrammarCheck__GrammarResultWidget* self, QHideEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnHideEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperHideEvent(TextGrammarCheck__GrammarResultWidget* self, QHideEvent* event);
bool TextGrammarCheck__GrammarResultWidget_NativeEvent(TextGrammarCheck__GrammarResultWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammarResultWidget_OnNativeEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperNativeEvent(TextGrammarCheck__GrammarResultWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammarResultWidget_ChangeEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* param1);
void TextGrammarCheck__GrammarResultWidget_OnChangeEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperChangeEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* param1);
int TextGrammarCheck__GrammarResultWidget_Metric(const TextGrammarCheck__GrammarResultWidget* self, int param1);
void TextGrammarCheck__GrammarResultWidget_OnMetric(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammarResultWidget_SuperMetric(const TextGrammarCheck__GrammarResultWidget* self, int param1);
void TextGrammarCheck__GrammarResultWidget_InitPainter(const TextGrammarCheck__GrammarResultWidget* self, QPainter* painter);
void TextGrammarCheck__GrammarResultWidget_OnInitPainter(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperInitPainter(const TextGrammarCheck__GrammarResultWidget* self, QPainter* painter);
QPaintDevice* TextGrammarCheck__GrammarResultWidget_Redirected(const TextGrammarCheck__GrammarResultWidget* self, QPoint* offset);
void TextGrammarCheck__GrammarResultWidget_OnRedirected(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QPaintDevice* TextGrammarCheck__GrammarResultWidget_SuperRedirected(const TextGrammarCheck__GrammarResultWidget* self, QPoint* offset);
QPainter* TextGrammarCheck__GrammarResultWidget_SharedPainter(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnSharedPainter(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QPainter* TextGrammarCheck__GrammarResultWidget_SuperSharedPainter(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_InputMethodEvent(TextGrammarCheck__GrammarResultWidget* self, QInputMethodEvent* param1);
void TextGrammarCheck__GrammarResultWidget_OnInputMethodEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperInputMethodEvent(TextGrammarCheck__GrammarResultWidget* self, QInputMethodEvent* param1);
QVariant* TextGrammarCheck__GrammarResultWidget_InputMethodQuery(const TextGrammarCheck__GrammarResultWidget* self, int param1);
void TextGrammarCheck__GrammarResultWidget_OnInputMethodQuery(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QVariant* TextGrammarCheck__GrammarResultWidget_SuperInputMethodQuery(const TextGrammarCheck__GrammarResultWidget* self, int param1);
bool TextGrammarCheck__GrammarResultWidget_FocusNextPrevChild(TextGrammarCheck__GrammarResultWidget* self, bool next);
void TextGrammarCheck__GrammarResultWidget_OnFocusNextPrevChild(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperFocusNextPrevChild(TextGrammarCheck__GrammarResultWidget* self, bool next);
bool TextGrammarCheck__GrammarResultWidget_EventFilter(TextGrammarCheck__GrammarResultWidget* self, QObject* watched, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnEventFilter(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperEventFilter(TextGrammarCheck__GrammarResultWidget* self, QObject* watched, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_TimerEvent(TextGrammarCheck__GrammarResultWidget* self, QTimerEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnTimerEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperTimerEvent(TextGrammarCheck__GrammarResultWidget* self, QTimerEvent* event);
void TextGrammarCheck__GrammarResultWidget_ChildEvent(TextGrammarCheck__GrammarResultWidget* self, QChildEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnChildEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperChildEvent(TextGrammarCheck__GrammarResultWidget* self, QChildEvent* event);
void TextGrammarCheck__GrammarResultWidget_CustomEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_OnCustomEvent(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperCustomEvent(TextGrammarCheck__GrammarResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammarResultWidget_ConnectNotify(TextGrammarCheck__GrammarResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultWidget_OnConnectNotify(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperConnectNotify(TextGrammarCheck__GrammarResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultWidget_DisconnectNotify(TextGrammarCheck__GrammarResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultWidget_OnDisconnectNotify(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperDisconnectNotify(TextGrammarCheck__GrammarResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultWidget_UpdateMicroFocus(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnUpdateMicroFocus(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperUpdateMicroFocus(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_Create(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnCreate(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperCreate(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_Destroy(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnDestroy(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammarResultWidget_SuperDestroy(TextGrammarCheck__GrammarResultWidget* self);
bool TextGrammarCheck__GrammarResultWidget_FocusNextChild(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnFocusNextChild(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperFocusNextChild(TextGrammarCheck__GrammarResultWidget* self);
bool TextGrammarCheck__GrammarResultWidget_FocusPreviousChild(TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnFocusPreviousChild(TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperFocusPreviousChild(TextGrammarCheck__GrammarResultWidget* self);
QObject* TextGrammarCheck__GrammarResultWidget_Sender(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnSender(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
QObject* TextGrammarCheck__GrammarResultWidget_SuperSender(const TextGrammarCheck__GrammarResultWidget* self);
int TextGrammarCheck__GrammarResultWidget_SenderSignalIndex(const TextGrammarCheck__GrammarResultWidget* self);
void TextGrammarCheck__GrammarResultWidget_OnSenderSignalIndex(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammarResultWidget_SuperSenderSignalIndex(const TextGrammarCheck__GrammarResultWidget* self);
int TextGrammarCheck__GrammarResultWidget_Receivers(const TextGrammarCheck__GrammarResultWidget* self, const char* signal);
void TextGrammarCheck__GrammarResultWidget_OnReceivers(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammarResultWidget_SuperReceivers(const TextGrammarCheck__GrammarResultWidget* self, const char* signal);
bool TextGrammarCheck__GrammarResultWidget_IsSignalConnected(const TextGrammarCheck__GrammarResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultWidget_OnIsSignalConnected(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultWidget_SuperIsSignalConnected(const TextGrammarCheck__GrammarResultWidget* self, const QMetaMethod* signal);
double TextGrammarCheck__GrammarResultWidget_GetDecodedMetricF(const TextGrammarCheck__GrammarResultWidget* self, int metricA, int metricB);
void TextGrammarCheck__GrammarResultWidget_OnGetDecodedMetricF(const TextGrammarCheck__GrammarResultWidget* self, intptr_t slot);
double TextGrammarCheck__GrammarResultWidget_SuperGetDecodedMetricF(const TextGrammarCheck__GrammarResultWidget* self, int metricA, int metricB);
void TextGrammarCheck__GrammarResultWidget_Delete(TextGrammarCheck__GrammarResultWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
