#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBIMPORTABSTRACTAUTOCORRECTION_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBIMPORTABSTRACTAUTOCORRECTION_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes)
typedef TextAutoCorrectionCore::AutoCorrectionUtils::TypographicQuotes TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAutoCorrectionCore__ImportAbstractAutocorrection)
typedef TextAutoCorrectionCore::ImportAbstractAutocorrection TextAutoCorrectionCore__ImportAbstractAutocorrection;
#endif
#else
typedef struct TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes;
typedef struct TextAutoCorrectionCore__ImportAbstractAutocorrection TextAutoCorrectionCore__ImportAbstractAutocorrection;
#endif

TextAutoCorrectionCore__ImportAbstractAutocorrection* TextAutoCorrectionCore__ImportAbstractAutocorrection_new();
TextAutoCorrectionCore__ImportAbstractAutocorrection* TextAutoCorrectionCore__ImportAbstractAutocorrection_new2(const TextAutoCorrectionCore__ImportAbstractAutocorrection* param1);
bool TextAutoCorrectionCore__ImportAbstractAutocorrection_Import(TextAutoCorrectionCore__ImportAbstractAutocorrection* self, const libqt_string fileName, libqt_string errorMessage, int loadAttribute);
libqt_list /* set of libqt_string */ TextAutoCorrectionCore__ImportAbstractAutocorrection_UpperCaseExceptions(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
libqt_list /* set of libqt_string */ TextAutoCorrectionCore__ImportAbstractAutocorrection_TwoUpperLetterExceptions(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
libqt_map /* of libqt_string to libqt_string */ TextAutoCorrectionCore__ImportAbstractAutocorrection_AutocorrectEntries(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
libqt_map /* of libqt_string to libqt_string */ TextAutoCorrectionCore__ImportAbstractAutocorrection_SuperScriptEntries(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* TextAutoCorrectionCore__ImportAbstractAutocorrection_TypographicSingleQuotes(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
TextAutoCorrectionCore__AutoCorrectionUtils__TypographicQuotes* TextAutoCorrectionCore__ImportAbstractAutocorrection_TypographicDoubleQuotes(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
int TextAutoCorrectionCore__ImportAbstractAutocorrection_MaxFindStringLenght(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
int TextAutoCorrectionCore__ImportAbstractAutocorrection_MinFindStringLenght(const TextAutoCorrectionCore__ImportAbstractAutocorrection* self);
void TextAutoCorrectionCore__ImportAbstractAutocorrection_OnImport(TextAutoCorrectionCore__ImportAbstractAutocorrection* self, intptr_t slot);
bool TextAutoCorrectionCore__ImportAbstractAutocorrection_SuperImport(TextAutoCorrectionCore__ImportAbstractAutocorrection* self, const libqt_string fileName, libqt_string errorMessage, int loadAttribute);
void TextAutoCorrectionCore__ImportAbstractAutocorrection_OperatorAssign(TextAutoCorrectionCore__ImportAbstractAutocorrection* self, const TextAutoCorrectionCore__ImportAbstractAutocorrection* param1);
void TextAutoCorrectionCore__ImportAbstractAutocorrection_OnOperatorAssign(TextAutoCorrectionCore__ImportAbstractAutocorrection* self, intptr_t slot);
void TextAutoCorrectionCore__ImportAbstractAutocorrection_SuperOperatorAssign(TextAutoCorrectionCore__ImportAbstractAutocorrection* self, const TextAutoCorrectionCore__ImportAbstractAutocorrection* param1);
void TextAutoCorrectionCore__ImportAbstractAutocorrection_Delete(TextAutoCorrectionCore__ImportAbstractAutocorrection* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
