#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBPLAINTEXTEDITFINDBAR_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBPLAINTEXTEDITFINDBAR_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__PlainTextEditFindBar)
typedef TextCustomEditor::PlainTextEditFindBar TextCustomEditor__PlainTextEditFindBar;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__TextEditFindBarBase)
typedef TextCustomEditor::TextEditFindBarBase TextCustomEditor__TextEditFindBarBase;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPlainTextEdit QPlainTextEdit;
typedef struct QPoint QPoint;
typedef struct QRegularExpression QRegularExpression;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextCustomEditor__PlainTextEditFindBar TextCustomEditor__PlainTextEditFindBar;
typedef struct TextCustomEditor__TextEditFindBarBase TextCustomEditor__TextEditFindBarBase;
#endif

TextCustomEditor__PlainTextEditFindBar* TextCustomEditor__PlainTextEditFindBar_new(QPlainTextEdit* view);
TextCustomEditor__PlainTextEditFindBar* TextCustomEditor__PlainTextEditFindBar_new2(QPlainTextEdit* view, QWidget* parent);
QMetaObject* TextCustomEditor__PlainTextEditFindBar_MetaObject(const TextCustomEditor__PlainTextEditFindBar* self);
void* TextCustomEditor__PlainTextEditFindBar_Metacast(TextCustomEditor__PlainTextEditFindBar* self, const char* param1);
int TextCustomEditor__PlainTextEditFindBar_Metacall(TextCustomEditor__PlainTextEditFindBar* self, int param1, int param2, void** param3);
bool TextCustomEditor__PlainTextEditFindBar_ViewIsReadOnly(const TextCustomEditor__PlainTextEditFindBar* self);
bool TextCustomEditor__PlainTextEditFindBar_DocumentIsEmpty(const TextCustomEditor__PlainTextEditFindBar* self);
bool TextCustomEditor__PlainTextEditFindBar_SearchInDocument(TextCustomEditor__PlainTextEditFindBar* self, const libqt_string text, int searchOptions);
bool TextCustomEditor__PlainTextEditFindBar_SearchInDocument2(TextCustomEditor__PlainTextEditFindBar* self, const QRegularExpression* regExp, int searchOptions);
void TextCustomEditor__PlainTextEditFindBar_AutoSearchMoveCursor(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_SlotSearchText(TextCustomEditor__PlainTextEditFindBar* self, bool backward, bool isAutoSearch);
void TextCustomEditor__PlainTextEditFindBar_OnMetaObject(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QMetaObject* TextCustomEditor__PlainTextEditFindBar_SuperMetaObject(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnMetacast(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void* TextCustomEditor__PlainTextEditFindBar_SuperMetacast(TextCustomEditor__PlainTextEditFindBar* self, const char* param1);
void TextCustomEditor__PlainTextEditFindBar_OnMetacall(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
int TextCustomEditor__PlainTextEditFindBar_SuperMetacall(TextCustomEditor__PlainTextEditFindBar* self, int param1, int param2, void** param3);
void TextCustomEditor__PlainTextEditFindBar_OnViewIsReadOnly(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperViewIsReadOnly(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnDocumentIsEmpty(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperDocumentIsEmpty(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnSearchInDocument(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperSearchInDocument(TextCustomEditor__PlainTextEditFindBar* self, const libqt_string text, int searchOptions);
void TextCustomEditor__PlainTextEditFindBar_OnSearchInDocument2(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperSearchInDocument2(TextCustomEditor__PlainTextEditFindBar* self, const QRegularExpression* regExp, int searchOptions);
void TextCustomEditor__PlainTextEditFindBar_OnAutoSearchMoveCursor(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperAutoSearchMoveCursor(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnSlotSearchText(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperSlotSearchText(TextCustomEditor__PlainTextEditFindBar* self, bool backward, bool isAutoSearch);
bool TextCustomEditor__PlainTextEditFindBar_Event(TextCustomEditor__PlainTextEditFindBar* self, QEvent* e);
void TextCustomEditor__PlainTextEditFindBar_OnEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* e);
int TextCustomEditor__PlainTextEditFindBar_DevType(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnDevType(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
int TextCustomEditor__PlainTextEditFindBar_SuperDevType(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_SetVisible(TextCustomEditor__PlainTextEditFindBar* self, bool visible);
void TextCustomEditor__PlainTextEditFindBar_OnSetVisible(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperSetVisible(TextCustomEditor__PlainTextEditFindBar* self, bool visible);
QSize* TextCustomEditor__PlainTextEditFindBar_SizeHint(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnSizeHint(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QSize* TextCustomEditor__PlainTextEditFindBar_SuperSizeHint(const TextCustomEditor__PlainTextEditFindBar* self);
QSize* TextCustomEditor__PlainTextEditFindBar_MinimumSizeHint(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnMinimumSizeHint(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QSize* TextCustomEditor__PlainTextEditFindBar_SuperMinimumSizeHint(const TextCustomEditor__PlainTextEditFindBar* self);
int TextCustomEditor__PlainTextEditFindBar_HeightForWidth(const TextCustomEditor__PlainTextEditFindBar* self, int param1);
void TextCustomEditor__PlainTextEditFindBar_OnHeightForWidth(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
int TextCustomEditor__PlainTextEditFindBar_SuperHeightForWidth(const TextCustomEditor__PlainTextEditFindBar* self, int param1);
bool TextCustomEditor__PlainTextEditFindBar_HasHeightForWidth(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnHasHeightForWidth(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperHasHeightForWidth(const TextCustomEditor__PlainTextEditFindBar* self);
QPaintEngine* TextCustomEditor__PlainTextEditFindBar_PaintEngine(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnPaintEngine(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QPaintEngine* TextCustomEditor__PlainTextEditFindBar_SuperPaintEngine(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_MousePressEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnMousePressEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperMousePressEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_MouseReleaseEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnMouseReleaseEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperMouseReleaseEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_MouseDoubleClickEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnMouseDoubleClickEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperMouseDoubleClickEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_MouseMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnMouseMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperMouseMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_WheelEvent(TextCustomEditor__PlainTextEditFindBar* self, QWheelEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnWheelEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperWheelEvent(TextCustomEditor__PlainTextEditFindBar* self, QWheelEvent* event);
void TextCustomEditor__PlainTextEditFindBar_KeyPressEvent(TextCustomEditor__PlainTextEditFindBar* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnKeyPressEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperKeyPressEvent(TextCustomEditor__PlainTextEditFindBar* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditFindBar_KeyReleaseEvent(TextCustomEditor__PlainTextEditFindBar* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnKeyReleaseEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperKeyReleaseEvent(TextCustomEditor__PlainTextEditFindBar* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditFindBar_FocusInEvent(TextCustomEditor__PlainTextEditFindBar* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnFocusInEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperFocusInEvent(TextCustomEditor__PlainTextEditFindBar* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditFindBar_FocusOutEvent(TextCustomEditor__PlainTextEditFindBar* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnFocusOutEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperFocusOutEvent(TextCustomEditor__PlainTextEditFindBar* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditFindBar_EnterEvent(TextCustomEditor__PlainTextEditFindBar* self, QEnterEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnEnterEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperEnterEvent(TextCustomEditor__PlainTextEditFindBar* self, QEnterEvent* event);
void TextCustomEditor__PlainTextEditFindBar_LeaveEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnLeaveEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperLeaveEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* event);
void TextCustomEditor__PlainTextEditFindBar_PaintEvent(TextCustomEditor__PlainTextEditFindBar* self, QPaintEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnPaintEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperPaintEvent(TextCustomEditor__PlainTextEditFindBar* self, QPaintEvent* event);
void TextCustomEditor__PlainTextEditFindBar_MoveEvent(TextCustomEditor__PlainTextEditFindBar* self, QMoveEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, QMoveEvent* event);
void TextCustomEditor__PlainTextEditFindBar_ResizeEvent(TextCustomEditor__PlainTextEditFindBar* self, QResizeEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnResizeEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperResizeEvent(TextCustomEditor__PlainTextEditFindBar* self, QResizeEvent* event);
void TextCustomEditor__PlainTextEditFindBar_CloseEvent(TextCustomEditor__PlainTextEditFindBar* self, QCloseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnCloseEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperCloseEvent(TextCustomEditor__PlainTextEditFindBar* self, QCloseEvent* event);
void TextCustomEditor__PlainTextEditFindBar_ContextMenuEvent(TextCustomEditor__PlainTextEditFindBar* self, QContextMenuEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnContextMenuEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperContextMenuEvent(TextCustomEditor__PlainTextEditFindBar* self, QContextMenuEvent* event);
void TextCustomEditor__PlainTextEditFindBar_TabletEvent(TextCustomEditor__PlainTextEditFindBar* self, QTabletEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnTabletEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperTabletEvent(TextCustomEditor__PlainTextEditFindBar* self, QTabletEvent* event);
void TextCustomEditor__PlainTextEditFindBar_ActionEvent(TextCustomEditor__PlainTextEditFindBar* self, QActionEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnActionEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperActionEvent(TextCustomEditor__PlainTextEditFindBar* self, QActionEvent* event);
void TextCustomEditor__PlainTextEditFindBar_DragEnterEvent(TextCustomEditor__PlainTextEditFindBar* self, QDragEnterEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnDragEnterEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperDragEnterEvent(TextCustomEditor__PlainTextEditFindBar* self, QDragEnterEvent* event);
void TextCustomEditor__PlainTextEditFindBar_DragMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, QDragMoveEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnDragMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperDragMoveEvent(TextCustomEditor__PlainTextEditFindBar* self, QDragMoveEvent* event);
void TextCustomEditor__PlainTextEditFindBar_DragLeaveEvent(TextCustomEditor__PlainTextEditFindBar* self, QDragLeaveEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnDragLeaveEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperDragLeaveEvent(TextCustomEditor__PlainTextEditFindBar* self, QDragLeaveEvent* event);
void TextCustomEditor__PlainTextEditFindBar_DropEvent(TextCustomEditor__PlainTextEditFindBar* self, QDropEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnDropEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperDropEvent(TextCustomEditor__PlainTextEditFindBar* self, QDropEvent* event);
void TextCustomEditor__PlainTextEditFindBar_ShowEvent(TextCustomEditor__PlainTextEditFindBar* self, QShowEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnShowEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperShowEvent(TextCustomEditor__PlainTextEditFindBar* self, QShowEvent* event);
void TextCustomEditor__PlainTextEditFindBar_HideEvent(TextCustomEditor__PlainTextEditFindBar* self, QHideEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnHideEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperHideEvent(TextCustomEditor__PlainTextEditFindBar* self, QHideEvent* event);
bool TextCustomEditor__PlainTextEditFindBar_NativeEvent(TextCustomEditor__PlainTextEditFindBar* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__PlainTextEditFindBar_OnNativeEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperNativeEvent(TextCustomEditor__PlainTextEditFindBar* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__PlainTextEditFindBar_ChangeEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* param1);
void TextCustomEditor__PlainTextEditFindBar_OnChangeEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperChangeEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* param1);
int TextCustomEditor__PlainTextEditFindBar_Metric(const TextCustomEditor__PlainTextEditFindBar* self, int param1);
void TextCustomEditor__PlainTextEditFindBar_OnMetric(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
int TextCustomEditor__PlainTextEditFindBar_SuperMetric(const TextCustomEditor__PlainTextEditFindBar* self, int param1);
void TextCustomEditor__PlainTextEditFindBar_InitPainter(const TextCustomEditor__PlainTextEditFindBar* self, QPainter* painter);
void TextCustomEditor__PlainTextEditFindBar_OnInitPainter(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperInitPainter(const TextCustomEditor__PlainTextEditFindBar* self, QPainter* painter);
QPaintDevice* TextCustomEditor__PlainTextEditFindBar_Redirected(const TextCustomEditor__PlainTextEditFindBar* self, QPoint* offset);
void TextCustomEditor__PlainTextEditFindBar_OnRedirected(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QPaintDevice* TextCustomEditor__PlainTextEditFindBar_SuperRedirected(const TextCustomEditor__PlainTextEditFindBar* self, QPoint* offset);
QPainter* TextCustomEditor__PlainTextEditFindBar_SharedPainter(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnSharedPainter(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QPainter* TextCustomEditor__PlainTextEditFindBar_SuperSharedPainter(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_InputMethodEvent(TextCustomEditor__PlainTextEditFindBar* self, QInputMethodEvent* param1);
void TextCustomEditor__PlainTextEditFindBar_OnInputMethodEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperInputMethodEvent(TextCustomEditor__PlainTextEditFindBar* self, QInputMethodEvent* param1);
QVariant* TextCustomEditor__PlainTextEditFindBar_InputMethodQuery(const TextCustomEditor__PlainTextEditFindBar* self, int param1);
void TextCustomEditor__PlainTextEditFindBar_OnInputMethodQuery(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QVariant* TextCustomEditor__PlainTextEditFindBar_SuperInputMethodQuery(const TextCustomEditor__PlainTextEditFindBar* self, int param1);
bool TextCustomEditor__PlainTextEditFindBar_FocusNextPrevChild(TextCustomEditor__PlainTextEditFindBar* self, bool next);
void TextCustomEditor__PlainTextEditFindBar_OnFocusNextPrevChild(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperFocusNextPrevChild(TextCustomEditor__PlainTextEditFindBar* self, bool next);
bool TextCustomEditor__PlainTextEditFindBar_EventFilter(TextCustomEditor__PlainTextEditFindBar* self, QObject* watched, QEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnEventFilter(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperEventFilter(TextCustomEditor__PlainTextEditFindBar* self, QObject* watched, QEvent* event);
void TextCustomEditor__PlainTextEditFindBar_TimerEvent(TextCustomEditor__PlainTextEditFindBar* self, QTimerEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnTimerEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperTimerEvent(TextCustomEditor__PlainTextEditFindBar* self, QTimerEvent* event);
void TextCustomEditor__PlainTextEditFindBar_ChildEvent(TextCustomEditor__PlainTextEditFindBar* self, QChildEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnChildEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperChildEvent(TextCustomEditor__PlainTextEditFindBar* self, QChildEvent* event);
void TextCustomEditor__PlainTextEditFindBar_CustomEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* event);
void TextCustomEditor__PlainTextEditFindBar_OnCustomEvent(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperCustomEvent(TextCustomEditor__PlainTextEditFindBar* self, QEvent* event);
void TextCustomEditor__PlainTextEditFindBar_ConnectNotify(TextCustomEditor__PlainTextEditFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditFindBar_OnConnectNotify(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperConnectNotify(TextCustomEditor__PlainTextEditFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditFindBar_DisconnectNotify(TextCustomEditor__PlainTextEditFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditFindBar_OnDisconnectNotify(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperDisconnectNotify(TextCustomEditor__PlainTextEditFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditFindBar_ClearSelections(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnClearSelections(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperClearSelections(TextCustomEditor__PlainTextEditFindBar* self);
bool TextCustomEditor__PlainTextEditFindBar_SearchText(TextCustomEditor__PlainTextEditFindBar* self, bool backward, bool isAutoSearch);
void TextCustomEditor__PlainTextEditFindBar_OnSearchText(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperSearchText(TextCustomEditor__PlainTextEditFindBar* self, bool backward, bool isAutoSearch);
void TextCustomEditor__PlainTextEditFindBar_SetFoundMatch(TextCustomEditor__PlainTextEditFindBar* self, bool match);
void TextCustomEditor__PlainTextEditFindBar_OnSetFoundMatch(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperSetFoundMatch(TextCustomEditor__PlainTextEditFindBar* self, bool match);
void TextCustomEditor__PlainTextEditFindBar_MessageInfo(TextCustomEditor__PlainTextEditFindBar* self, bool backward, bool isAutoSearch, bool found);
void TextCustomEditor__PlainTextEditFindBar_OnMessageInfo(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperMessageInfo(TextCustomEditor__PlainTextEditFindBar* self, bool backward, bool isAutoSearch, bool found);
void TextCustomEditor__PlainTextEditFindBar_UpdateMicroFocus(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnUpdateMicroFocus(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperUpdateMicroFocus(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_Create(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnCreate(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperCreate(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_Destroy(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnDestroy(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
void TextCustomEditor__PlainTextEditFindBar_SuperDestroy(TextCustomEditor__PlainTextEditFindBar* self);
bool TextCustomEditor__PlainTextEditFindBar_FocusNextChild(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnFocusNextChild(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperFocusNextChild(TextCustomEditor__PlainTextEditFindBar* self);
bool TextCustomEditor__PlainTextEditFindBar_FocusPreviousChild(TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnFocusPreviousChild(TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperFocusPreviousChild(TextCustomEditor__PlainTextEditFindBar* self);
QObject* TextCustomEditor__PlainTextEditFindBar_Sender(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnSender(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
QObject* TextCustomEditor__PlainTextEditFindBar_SuperSender(const TextCustomEditor__PlainTextEditFindBar* self);
int TextCustomEditor__PlainTextEditFindBar_SenderSignalIndex(const TextCustomEditor__PlainTextEditFindBar* self);
void TextCustomEditor__PlainTextEditFindBar_OnSenderSignalIndex(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
int TextCustomEditor__PlainTextEditFindBar_SuperSenderSignalIndex(const TextCustomEditor__PlainTextEditFindBar* self);
int TextCustomEditor__PlainTextEditFindBar_Receivers(const TextCustomEditor__PlainTextEditFindBar* self, const char* signal);
void TextCustomEditor__PlainTextEditFindBar_OnReceivers(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
int TextCustomEditor__PlainTextEditFindBar_SuperReceivers(const TextCustomEditor__PlainTextEditFindBar* self, const char* signal);
bool TextCustomEditor__PlainTextEditFindBar_IsSignalConnected(const TextCustomEditor__PlainTextEditFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditFindBar_OnIsSignalConnected(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditFindBar_SuperIsSignalConnected(const TextCustomEditor__PlainTextEditFindBar* self, const QMetaMethod* signal);
double TextCustomEditor__PlainTextEditFindBar_GetDecodedMetricF(const TextCustomEditor__PlainTextEditFindBar* self, int metricA, int metricB);
void TextCustomEditor__PlainTextEditFindBar_OnGetDecodedMetricF(const TextCustomEditor__PlainTextEditFindBar* self, intptr_t slot);
double TextCustomEditor__PlainTextEditFindBar_SuperGetDecodedMetricF(const TextCustomEditor__PlainTextEditFindBar* self, int metricA, int metricB);
void TextCustomEditor__PlainTextEditFindBar_Delete(TextCustomEditor__PlainTextEditFindBar* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
