#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBSELECTSPECIALCHARDIALOG_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBSELECTSPECIALCHARDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAddonsWidgets__SelectSpecialCharDialog)
typedef TextAddonsWidgets::SelectSpecialCharDialog TextAddonsWidgets__SelectSpecialCharDialog;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChar QChar;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextAddonsWidgets__SelectSpecialCharDialog TextAddonsWidgets__SelectSpecialCharDialog;
#endif

TextAddonsWidgets__SelectSpecialCharDialog* TextAddonsWidgets__SelectSpecialCharDialog_new(QWidget* parent);
QMetaObject* TextAddonsWidgets__SelectSpecialCharDialog_MetaObject(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void* TextAddonsWidgets__SelectSpecialCharDialog_Metacast(TextAddonsWidgets__SelectSpecialCharDialog* self, const char* param1);
int TextAddonsWidgets__SelectSpecialCharDialog_Metacall(TextAddonsWidgets__SelectSpecialCharDialog* self, int param1, int param2, void** param3);
void TextAddonsWidgets__SelectSpecialCharDialog_SetCurrentChar(TextAddonsWidgets__SelectSpecialCharDialog* self, QChar* c);
QChar* TextAddonsWidgets__SelectSpecialCharDialog_CurrentChar(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_SetOkButtonText(TextAddonsWidgets__SelectSpecialCharDialog* self, const libqt_string text);
void TextAddonsWidgets__SelectSpecialCharDialog_ShowSelectButton(TextAddonsWidgets__SelectSpecialCharDialog* self, bool show);
void TextAddonsWidgets__SelectSpecialCharDialog_AutoInsertChar(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_CharSelected(TextAddonsWidgets__SelectSpecialCharDialog* self, QChar* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_Connect_CharSelected(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMetaObject(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QMetaObject* TextAddonsWidgets__SelectSpecialCharDialog_SuperMetaObject(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMetacast(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void* TextAddonsWidgets__SelectSpecialCharDialog_SuperMetacast(TextAddonsWidgets__SelectSpecialCharDialog* self, const char* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMetacall(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperMetacall(TextAddonsWidgets__SelectSpecialCharDialog* self, int param1, int param2, void** param3);
void TextAddonsWidgets__SelectSpecialCharDialog_SetVisible(TextAddonsWidgets__SelectSpecialCharDialog* self, bool visible);
void TextAddonsWidgets__SelectSpecialCharDialog_OnSetVisible(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperSetVisible(TextAddonsWidgets__SelectSpecialCharDialog* self, bool visible);
QSize* TextAddonsWidgets__SelectSpecialCharDialog_SizeHint(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnSizeHint(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QSize* TextAddonsWidgets__SelectSpecialCharDialog_SuperSizeHint(const TextAddonsWidgets__SelectSpecialCharDialog* self);
QSize* TextAddonsWidgets__SelectSpecialCharDialog_MinimumSizeHint(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMinimumSizeHint(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QSize* TextAddonsWidgets__SelectSpecialCharDialog_SuperMinimumSizeHint(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_Open(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnOpen(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperOpen(TextAddonsWidgets__SelectSpecialCharDialog* self);
int TextAddonsWidgets__SelectSpecialCharDialog_Exec(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnExec(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperExec(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_Done(TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDone(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDone(TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
void TextAddonsWidgets__SelectSpecialCharDialog_Accept(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnAccept(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperAccept(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_Reject(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnReject(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperReject(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_KeyPressEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QKeyEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnKeyPressEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperKeyPressEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QKeyEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_CloseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QCloseEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnCloseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperCloseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QCloseEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_ShowEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QShowEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnShowEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperShowEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QShowEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_ResizeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QResizeEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnResizeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperResizeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QResizeEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_ContextMenuEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QContextMenuEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnContextMenuEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperContextMenuEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QContextMenuEvent* param1);
bool TextAddonsWidgets__SelectSpecialCharDialog_EventFilter(TextAddonsWidgets__SelectSpecialCharDialog* self, QObject* param1, QEvent* param2);
void TextAddonsWidgets__SelectSpecialCharDialog_OnEventFilter(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperEventFilter(TextAddonsWidgets__SelectSpecialCharDialog* self, QObject* param1, QEvent* param2);
int TextAddonsWidgets__SelectSpecialCharDialog_DevType(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDevType(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperDevType(const TextAddonsWidgets__SelectSpecialCharDialog* self);
int TextAddonsWidgets__SelectSpecialCharDialog_HeightForWidth(const TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnHeightForWidth(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperHeightForWidth(const TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
bool TextAddonsWidgets__SelectSpecialCharDialog_HasHeightForWidth(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnHasHeightForWidth(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperHasHeightForWidth(const TextAddonsWidgets__SelectSpecialCharDialog* self);
QPaintEngine* TextAddonsWidgets__SelectSpecialCharDialog_PaintEngine(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnPaintEngine(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QPaintEngine* TextAddonsWidgets__SelectSpecialCharDialog_SuperPaintEngine(const TextAddonsWidgets__SelectSpecialCharDialog* self);
bool TextAddonsWidgets__SelectSpecialCharDialog_Event(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_MousePressEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMousePressEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperMousePressEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_MouseReleaseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMouseReleaseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperMouseReleaseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_MouseDoubleClickEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMouseDoubleClickEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperMouseDoubleClickEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_MouseMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMouseMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperMouseMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMouseEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_WheelEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QWheelEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnWheelEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperWheelEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QWheelEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_KeyReleaseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QKeyEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnKeyReleaseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperKeyReleaseEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QKeyEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_FocusInEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QFocusEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnFocusInEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperFocusInEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QFocusEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_FocusOutEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QFocusEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnFocusOutEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperFocusOutEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QFocusEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_EnterEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEnterEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnEnterEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperEnterEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEnterEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_LeaveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnLeaveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperLeaveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_PaintEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QPaintEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnPaintEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperPaintEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QPaintEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_MoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMoveEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QMoveEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_TabletEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QTabletEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnTabletEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperTabletEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QTabletEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_ActionEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QActionEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnActionEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperActionEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QActionEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_DragEnterEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDragEnterEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDragEnterEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDragEnterEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDragEnterEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_DragMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDragMoveEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDragMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDragMoveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDragMoveEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_DragLeaveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDragLeaveEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDragLeaveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDragLeaveEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDragLeaveEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_DropEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDropEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDropEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDropEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QDropEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_HideEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QHideEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnHideEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperHideEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QHideEvent* event);
bool TextAddonsWidgets__SelectSpecialCharDialog_NativeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextAddonsWidgets__SelectSpecialCharDialog_OnNativeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperNativeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextAddonsWidgets__SelectSpecialCharDialog_ChangeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnChangeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperChangeEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* param1);
int TextAddonsWidgets__SelectSpecialCharDialog_Metric(const TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnMetric(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperMetric(const TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
void TextAddonsWidgets__SelectSpecialCharDialog_InitPainter(const TextAddonsWidgets__SelectSpecialCharDialog* self, QPainter* painter);
void TextAddonsWidgets__SelectSpecialCharDialog_OnInitPainter(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperInitPainter(const TextAddonsWidgets__SelectSpecialCharDialog* self, QPainter* painter);
QPaintDevice* TextAddonsWidgets__SelectSpecialCharDialog_Redirected(const TextAddonsWidgets__SelectSpecialCharDialog* self, QPoint* offset);
void TextAddonsWidgets__SelectSpecialCharDialog_OnRedirected(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QPaintDevice* TextAddonsWidgets__SelectSpecialCharDialog_SuperRedirected(const TextAddonsWidgets__SelectSpecialCharDialog* self, QPoint* offset);
QPainter* TextAddonsWidgets__SelectSpecialCharDialog_SharedPainter(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnSharedPainter(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QPainter* TextAddonsWidgets__SelectSpecialCharDialog_SuperSharedPainter(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_InputMethodEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QInputMethodEvent* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnInputMethodEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperInputMethodEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QInputMethodEvent* param1);
QVariant* TextAddonsWidgets__SelectSpecialCharDialog_InputMethodQuery(const TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnInputMethodQuery(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QVariant* TextAddonsWidgets__SelectSpecialCharDialog_SuperInputMethodQuery(const TextAddonsWidgets__SelectSpecialCharDialog* self, int param1);
bool TextAddonsWidgets__SelectSpecialCharDialog_FocusNextPrevChild(TextAddonsWidgets__SelectSpecialCharDialog* self, bool next);
void TextAddonsWidgets__SelectSpecialCharDialog_OnFocusNextPrevChild(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperFocusNextPrevChild(TextAddonsWidgets__SelectSpecialCharDialog* self, bool next);
void TextAddonsWidgets__SelectSpecialCharDialog_TimerEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QTimerEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnTimerEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperTimerEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QTimerEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_ChildEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QChildEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnChildEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperChildEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QChildEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_CustomEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_OnCustomEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperCustomEvent(TextAddonsWidgets__SelectSpecialCharDialog* self, QEvent* event);
void TextAddonsWidgets__SelectSpecialCharDialog_ConnectNotify(TextAddonsWidgets__SelectSpecialCharDialog* self, const QMetaMethod* signal);
void TextAddonsWidgets__SelectSpecialCharDialog_OnConnectNotify(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperConnectNotify(TextAddonsWidgets__SelectSpecialCharDialog* self, const QMetaMethod* signal);
void TextAddonsWidgets__SelectSpecialCharDialog_DisconnectNotify(TextAddonsWidgets__SelectSpecialCharDialog* self, const QMetaMethod* signal);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDisconnectNotify(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDisconnectNotify(TextAddonsWidgets__SelectSpecialCharDialog* self, const QMetaMethod* signal);
void TextAddonsWidgets__SelectSpecialCharDialog_AdjustPosition(TextAddonsWidgets__SelectSpecialCharDialog* self, QWidget* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_OnAdjustPosition(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperAdjustPosition(TextAddonsWidgets__SelectSpecialCharDialog* self, QWidget* param1);
void TextAddonsWidgets__SelectSpecialCharDialog_UpdateMicroFocus(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnUpdateMicroFocus(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperUpdateMicroFocus(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_Create(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnCreate(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperCreate(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_Destroy(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnDestroy(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
void TextAddonsWidgets__SelectSpecialCharDialog_SuperDestroy(TextAddonsWidgets__SelectSpecialCharDialog* self);
bool TextAddonsWidgets__SelectSpecialCharDialog_FocusNextChild(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnFocusNextChild(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperFocusNextChild(TextAddonsWidgets__SelectSpecialCharDialog* self);
bool TextAddonsWidgets__SelectSpecialCharDialog_FocusPreviousChild(TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnFocusPreviousChild(TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperFocusPreviousChild(TextAddonsWidgets__SelectSpecialCharDialog* self);
QObject* TextAddonsWidgets__SelectSpecialCharDialog_Sender(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnSender(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
QObject* TextAddonsWidgets__SelectSpecialCharDialog_SuperSender(const TextAddonsWidgets__SelectSpecialCharDialog* self);
int TextAddonsWidgets__SelectSpecialCharDialog_SenderSignalIndex(const TextAddonsWidgets__SelectSpecialCharDialog* self);
void TextAddonsWidgets__SelectSpecialCharDialog_OnSenderSignalIndex(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperSenderSignalIndex(const TextAddonsWidgets__SelectSpecialCharDialog* self);
int TextAddonsWidgets__SelectSpecialCharDialog_Receivers(const TextAddonsWidgets__SelectSpecialCharDialog* self, const char* signal);
void TextAddonsWidgets__SelectSpecialCharDialog_OnReceivers(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
int TextAddonsWidgets__SelectSpecialCharDialog_SuperReceivers(const TextAddonsWidgets__SelectSpecialCharDialog* self, const char* signal);
bool TextAddonsWidgets__SelectSpecialCharDialog_IsSignalConnected(const TextAddonsWidgets__SelectSpecialCharDialog* self, const QMetaMethod* signal);
void TextAddonsWidgets__SelectSpecialCharDialog_OnIsSignalConnected(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
bool TextAddonsWidgets__SelectSpecialCharDialog_SuperIsSignalConnected(const TextAddonsWidgets__SelectSpecialCharDialog* self, const QMetaMethod* signal);
double TextAddonsWidgets__SelectSpecialCharDialog_GetDecodedMetricF(const TextAddonsWidgets__SelectSpecialCharDialog* self, int metricA, int metricB);
void TextAddonsWidgets__SelectSpecialCharDialog_OnGetDecodedMetricF(const TextAddonsWidgets__SelectSpecialCharDialog* self, intptr_t slot);
double TextAddonsWidgets__SelectSpecialCharDialog_SuperGetDecodedMetricF(const TextAddonsWidgets__SelectSpecialCharDialog* self, int metricA, int metricB);
void TextAddonsWidgets__SelectSpecialCharDialog_Delete(TextAddonsWidgets__SelectSpecialCharDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
