#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHCONFIGDIALOG_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHCONFIGDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechConfigDialog)
typedef TextEditTextToSpeech::TextToSpeechConfigDialog TextEditTextToSpeech__TextToSpeechConfigDialog;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextEditTextToSpeech__TextToSpeechConfigDialog TextEditTextToSpeech__TextToSpeechConfigDialog;
#endif

TextEditTextToSpeech__TextToSpeechConfigDialog* TextEditTextToSpeech__TextToSpeechConfigDialog_new(QWidget* parent);
TextEditTextToSpeech__TextToSpeechConfigDialog* TextEditTextToSpeech__TextToSpeechConfigDialog_new2();
QMetaObject* TextEditTextToSpeech__TextToSpeechConfigDialog_MetaObject(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void* TextEditTextToSpeech__TextToSpeechConfigDialog_Metacast(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const char* param1);
int TextEditTextToSpeech__TextToSpeechConfigDialog_Metacall(TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1, int param2, void** param3);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMetaObject(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QMetaObject* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMetaObject(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMetacast(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMetacast(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const char* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMetacall(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMetacall(TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1, int param2, void** param3);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SetVisible(TextEditTextToSpeech__TextToSpeechConfigDialog* self, bool visible);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnSetVisible(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperSetVisible(TextEditTextToSpeech__TextToSpeechConfigDialog* self, bool visible);
QSize* TextEditTextToSpeech__TextToSpeechConfigDialog_SizeHint(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnSizeHint(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperSizeHint(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
QSize* TextEditTextToSpeech__TextToSpeechConfigDialog_MinimumSizeHint(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Open(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnOpen(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperOpen(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
int TextEditTextToSpeech__TextToSpeechConfigDialog_Exec(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnExec(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperExec(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Done(TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDone(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDone(TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Accept(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnAccept(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperAccept(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Reject(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnReject(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperReject(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_KeyPressEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QKeyEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnKeyPressEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperKeyPressEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QKeyEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_CloseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QCloseEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnCloseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperCloseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QCloseEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ShowEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QShowEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnShowEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperShowEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QShowEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ResizeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QResizeEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnResizeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperResizeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QResizeEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ContextMenuEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QContextMenuEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnContextMenuEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperContextMenuEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QContextMenuEvent* param1);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_EventFilter(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QObject* param1, QEvent* param2);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnEventFilter(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperEventFilter(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QObject* param1, QEvent* param2);
int TextEditTextToSpeech__TextToSpeechConfigDialog_DevType(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDevType(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDevType(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
int TextEditTextToSpeech__TextToSpeechConfigDialog_HeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_HasHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
QPaintEngine* TextEditTextToSpeech__TextToSpeechConfigDialog_PaintEngine(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnPaintEngine(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QPaintEngine* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperPaintEngine(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_Event(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_MousePressEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMousePressEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMousePressEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_MouseReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_MouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_MouseMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMouseMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMouseMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_WheelEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnWheelEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperWheelEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_KeyReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_FocusInEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnFocusInEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperFocusInEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_FocusOutEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnFocusOutEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperFocusOutEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_EnterEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnEnterEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperEnterEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_LeaveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_PaintEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnPaintEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperPaintEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_MoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_TabletEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnTabletEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperTabletEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ActionEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnActionEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperActionEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_DragEnterEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDragEnterEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDragEnterEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_DragMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDragMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDragMoveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_DragLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDragLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDragLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_DropEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDropEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDropEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_HideEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QHideEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnHideEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperHideEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QHideEvent* event);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_NativeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnNativeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperNativeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ChangeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnChangeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperChangeEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* param1);
int TextEditTextToSpeech__TextToSpeechConfigDialog_Metric(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnMetric(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperMetric(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_InitPainter(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, QPainter* painter);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnInitPainter(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperInitPainter(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, QPainter* painter);
QPaintDevice* TextEditTextToSpeech__TextToSpeechConfigDialog_Redirected(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, QPoint* offset);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnRedirected(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QPaintDevice* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperRedirected(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, QPoint* offset);
QPainter* TextEditTextToSpeech__TextToSpeechConfigDialog_SharedPainter(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnSharedPainter(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QPainter* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperSharedPainter(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_InputMethodEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QInputMethodEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnInputMethodEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperInputMethodEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QInputMethodEvent* param1);
QVariant* TextEditTextToSpeech__TextToSpeechConfigDialog_InputMethodQuery(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnInputMethodQuery(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QVariant* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperInputMethodQuery(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int param1);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_FocusNextPrevChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self, bool next);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self, bool next);
void TextEditTextToSpeech__TextToSpeechConfigDialog_TimerEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnTimerEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperTimerEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ChildEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnChildEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperChildEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_CustomEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnCustomEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperCustomEvent(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigDialog_ConnectNotify(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnConnectNotify(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperConnectNotify(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigDialog_DisconnectNotify(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDisconnectNotify(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDisconnectNotify(TextEditTextToSpeech__TextToSpeechConfigDialog* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigDialog_AdjustPosition(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QWidget* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnAdjustPosition(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperAdjustPosition(TextEditTextToSpeech__TextToSpeechConfigDialog* self, QWidget* param1);
void TextEditTextToSpeech__TextToSpeechConfigDialog_UpdateMicroFocus(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Create(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnCreate(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperCreate(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Destroy(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnDestroy(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigDialog_SuperDestroy(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_FocusNextChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnFocusNextChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperFocusNextChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_FocusPreviousChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnFocusPreviousChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperFocusPreviousChild(TextEditTextToSpeech__TextToSpeechConfigDialog* self);
QObject* TextEditTextToSpeech__TextToSpeechConfigDialog_Sender(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnSender(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
QObject* TextEditTextToSpeech__TextToSpeechConfigDialog_SuperSender(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SenderSignalIndex(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechConfigDialog* self);
int TextEditTextToSpeech__TextToSpeechConfigDialog_Receivers(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, const char* signal);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnReceivers(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigDialog_SuperReceivers(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, const char* signal);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_IsSignalConnected(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnIsSignalConnected(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigDialog_SuperIsSignalConnected(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, const QMetaMethod* signal);
double TextEditTextToSpeech__TextToSpeechConfigDialog_GetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechConfigDialog_OnGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, intptr_t slot);
double TextEditTextToSpeech__TextToSpeechConfigDialog_SuperGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechConfigDialog* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechConfigDialog_Delete(TextEditTextToSpeech__TextToSpeechConfigDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
