#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHCONTAINERWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHCONTAINERWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechContainerWidget)
typedef TextEditTextToSpeech::TextToSpeechContainerWidget TextEditTextToSpeech__TextToSpeechContainerWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextEditTextToSpeech__TextToSpeechContainerWidget TextEditTextToSpeech__TextToSpeechContainerWidget;
#endif

TextEditTextToSpeech__TextToSpeechContainerWidget* TextEditTextToSpeech__TextToSpeechContainerWidget_new(QWidget* parent);
TextEditTextToSpeech__TextToSpeechContainerWidget* TextEditTextToSpeech__TextToSpeechContainerWidget_new2();
QMetaObject* TextEditTextToSpeech__TextToSpeechContainerWidget_MetaObject(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void* TextEditTextToSpeech__TextToSpeechContainerWidget_Metacast(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const char* param1);
int TextEditTextToSpeech__TextToSpeechContainerWidget_Metacall(TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1, int param2, void** param3);
void TextEditTextToSpeech__TextToSpeechContainerWidget_Say(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const libqt_string text);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMetaObject(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QMetaObject* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMetaObject(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMetacast(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMetacast(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const char* param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMetacall(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMetacall(TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1, int param2, void** param3);
int TextEditTextToSpeech__TextToSpeechContainerWidget_DevType(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDevType(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDevType(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SetVisible(TextEditTextToSpeech__TextToSpeechContainerWidget* self, bool visible);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnSetVisible(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperSetVisible(TextEditTextToSpeech__TextToSpeechContainerWidget* self, bool visible);
QSize* TextEditTextToSpeech__TextToSpeechContainerWidget_SizeHint(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnSizeHint(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperSizeHint(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
QSize* TextEditTextToSpeech__TextToSpeechContainerWidget_MinimumSizeHint(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
int TextEditTextToSpeech__TextToSpeechContainerWidget_HeightForWidth(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnHeightForWidth(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SuperHeightForWidth(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_HasHeightForWidth(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
QPaintEngine* TextEditTextToSpeech__TextToSpeechContainerWidget_PaintEngine(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnPaintEngine(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QPaintEngine* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperPaintEngine(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_Event(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_MousePressEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMousePressEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMousePressEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_MouseReleaseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_MouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_MouseMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMouseMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMouseMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_WheelEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnWheelEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperWheelEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_KeyPressEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnKeyPressEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperKeyPressEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_KeyReleaseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_FocusInEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnFocusInEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperFocusInEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_FocusOutEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnFocusOutEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperFocusOutEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_EnterEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnEnterEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperEnterEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_LeaveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnLeaveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperLeaveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_PaintEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnPaintEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperPaintEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_MoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ResizeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QResizeEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnResizeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperResizeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QResizeEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_CloseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QCloseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnCloseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperCloseEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QCloseEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ContextMenuEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QContextMenuEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnContextMenuEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperContextMenuEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QContextMenuEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_TabletEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnTabletEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperTabletEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ActionEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnActionEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperActionEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_DragEnterEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDragEnterEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDragEnterEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_DragMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDragMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDragMoveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_DragLeaveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDragLeaveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDragLeaveEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_DropEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDropEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDropEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ShowEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QShowEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnShowEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperShowEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QShowEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_HideEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QHideEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnHideEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperHideEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QHideEvent* event);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_NativeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnNativeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperNativeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ChangeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnChangeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperChangeEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* param1);
int TextEditTextToSpeech__TextToSpeechContainerWidget_Metric(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnMetric(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SuperMetric(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_InitPainter(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, QPainter* painter);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnInitPainter(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperInitPainter(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, QPainter* painter);
QPaintDevice* TextEditTextToSpeech__TextToSpeechContainerWidget_Redirected(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, QPoint* offset);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnRedirected(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QPaintDevice* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperRedirected(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, QPoint* offset);
QPainter* TextEditTextToSpeech__TextToSpeechContainerWidget_SharedPainter(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnSharedPainter(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QPainter* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperSharedPainter(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_InputMethodEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QInputMethodEvent* param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnInputMethodEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperInputMethodEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QInputMethodEvent* param1);
QVariant* TextEditTextToSpeech__TextToSpeechContainerWidget_InputMethodQuery(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnInputMethodQuery(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QVariant* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperInputMethodQuery(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int param1);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_FocusNextPrevChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self, bool next);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self, bool next);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_EventFilter(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnEventFilter(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperEventFilter(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_TimerEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnTimerEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperTimerEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ChildEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnChildEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperChildEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_CustomEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnCustomEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperCustomEvent(TextEditTextToSpeech__TextToSpeechContainerWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechContainerWidget_ConnectNotify(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnConnectNotify(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperConnectNotify(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechContainerWidget_DisconnectNotify(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDisconnectNotify(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDisconnectNotify(TextEditTextToSpeech__TextToSpeechContainerWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechContainerWidget_UpdateMicroFocus(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_Create(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnCreate(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperCreate(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_Destroy(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnDestroy(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechContainerWidget_SuperDestroy(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_FocusNextChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnFocusNextChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperFocusNextChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_FocusPreviousChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnFocusPreviousChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperFocusPreviousChild(TextEditTextToSpeech__TextToSpeechContainerWidget* self);
QObject* TextEditTextToSpeech__TextToSpeechContainerWidget_Sender(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnSender(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
QObject* TextEditTextToSpeech__TextToSpeechContainerWidget_SuperSender(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SenderSignalIndex(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SuperSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechContainerWidget* self);
int TextEditTextToSpeech__TextToSpeechContainerWidget_Receivers(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, const char* signal);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnReceivers(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechContainerWidget_SuperReceivers(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, const char* signal);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_IsSignalConnected(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnIsSignalConnected(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechContainerWidget_SuperIsSignalConnected(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, const QMetaMethod* signal);
double TextEditTextToSpeech__TextToSpeechContainerWidget_GetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechContainerWidget_OnGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, intptr_t slot);
double TextEditTextToSpeech__TextToSpeechContainerWidget_SuperGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechContainerWidget* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechContainerWidget_Delete(TextEditTextToSpeech__TextToSpeechContainerWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
