#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHINTERFACE_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHINTERFACE_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechInterface)
typedef TextEditTextToSpeech::TextToSpeechInterface TextEditTextToSpeech__TextToSpeechInterface;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechWidget)
typedef TextEditTextToSpeech::TextToSpeechWidget TextEditTextToSpeech__TextToSpeechWidget;
#endif
#else
typedef struct QChildEvent QChildEvent;
typedef struct QEvent QEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QTimerEvent QTimerEvent;
typedef struct TextEditTextToSpeech__TextToSpeechInterface TextEditTextToSpeech__TextToSpeechInterface;
typedef struct TextEditTextToSpeech__TextToSpeechWidget TextEditTextToSpeech__TextToSpeechWidget;
#endif

TextEditTextToSpeech__TextToSpeechInterface* TextEditTextToSpeech__TextToSpeechInterface_new(TextEditTextToSpeech__TextToSpeechWidget* textToSpeechWidget);
TextEditTextToSpeech__TextToSpeechInterface* TextEditTextToSpeech__TextToSpeechInterface_new2(TextEditTextToSpeech__TextToSpeechWidget* textToSpeechWidget, QObject* parent);
QMetaObject* TextEditTextToSpeech__TextToSpeechInterface_MetaObject(const TextEditTextToSpeech__TextToSpeechInterface* self);
void* TextEditTextToSpeech__TextToSpeechInterface_Metacast(TextEditTextToSpeech__TextToSpeechInterface* self, const char* param1);
int TextEditTextToSpeech__TextToSpeechInterface_Metacall(TextEditTextToSpeech__TextToSpeechInterface* self, int param1, int param2, void** param3);
bool TextEditTextToSpeech__TextToSpeechInterface_IsReady(const TextEditTextToSpeech__TextToSpeechInterface* self);
void TextEditTextToSpeech__TextToSpeechInterface_Say(TextEditTextToSpeech__TextToSpeechInterface* self, const libqt_string text);
double TextEditTextToSpeech__TextToSpeechInterface_Volume(const TextEditTextToSpeech__TextToSpeechInterface* self);
void TextEditTextToSpeech__TextToSpeechInterface_SetVolume(TextEditTextToSpeech__TextToSpeechInterface* self, double value);
void TextEditTextToSpeech__TextToSpeechInterface_ReloadSettings(TextEditTextToSpeech__TextToSpeechInterface* self);
void TextEditTextToSpeech__TextToSpeechInterface_OnMetaObject(const TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
QMetaObject* TextEditTextToSpeech__TextToSpeechInterface_SuperMetaObject(const TextEditTextToSpeech__TextToSpeechInterface* self);
void TextEditTextToSpeech__TextToSpeechInterface_OnMetacast(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
void* TextEditTextToSpeech__TextToSpeechInterface_SuperMetacast(TextEditTextToSpeech__TextToSpeechInterface* self, const char* param1);
void TextEditTextToSpeech__TextToSpeechInterface_OnMetacall(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechInterface_SuperMetacall(TextEditTextToSpeech__TextToSpeechInterface* self, int param1, int param2, void** param3);
bool TextEditTextToSpeech__TextToSpeechInterface_Event(TextEditTextToSpeech__TextToSpeechInterface* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_OnEvent(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechInterface_SuperEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QEvent* event);
bool TextEditTextToSpeech__TextToSpeechInterface_EventFilter(TextEditTextToSpeech__TextToSpeechInterface* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_OnEventFilter(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechInterface_SuperEventFilter(TextEditTextToSpeech__TextToSpeechInterface* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_TimerEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_OnTimerEvent(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechInterface_SuperTimerEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_ChildEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_OnChildEvent(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechInterface_SuperChildEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_CustomEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_OnCustomEvent(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechInterface_SuperCustomEvent(TextEditTextToSpeech__TextToSpeechInterface* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechInterface_ConnectNotify(TextEditTextToSpeech__TextToSpeechInterface* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechInterface_OnConnectNotify(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechInterface_SuperConnectNotify(TextEditTextToSpeech__TextToSpeechInterface* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechInterface_DisconnectNotify(TextEditTextToSpeech__TextToSpeechInterface* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechInterface_OnDisconnectNotify(TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechInterface_SuperDisconnectNotify(TextEditTextToSpeech__TextToSpeechInterface* self, const QMetaMethod* signal);
QObject* TextEditTextToSpeech__TextToSpeechInterface_Sender(const TextEditTextToSpeech__TextToSpeechInterface* self);
void TextEditTextToSpeech__TextToSpeechInterface_OnSender(const TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
QObject* TextEditTextToSpeech__TextToSpeechInterface_SuperSender(const TextEditTextToSpeech__TextToSpeechInterface* self);
int TextEditTextToSpeech__TextToSpeechInterface_SenderSignalIndex(const TextEditTextToSpeech__TextToSpeechInterface* self);
void TextEditTextToSpeech__TextToSpeechInterface_OnSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechInterface_SuperSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechInterface* self);
int TextEditTextToSpeech__TextToSpeechInterface_Receivers(const TextEditTextToSpeech__TextToSpeechInterface* self, const char* signal);
void TextEditTextToSpeech__TextToSpeechInterface_OnReceivers(const TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechInterface_SuperReceivers(const TextEditTextToSpeech__TextToSpeechInterface* self, const char* signal);
bool TextEditTextToSpeech__TextToSpeechInterface_IsSignalConnected(const TextEditTextToSpeech__TextToSpeechInterface* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechInterface_OnIsSignalConnected(const TextEditTextToSpeech__TextToSpeechInterface* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechInterface_SuperIsSignalConnected(const TextEditTextToSpeech__TextToSpeechInterface* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechInterface_Delete(TextEditTextToSpeech__TextToSpeechInterface* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
