#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTAUTOCORRECTIONSETTING_BASE_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTAUTOCORRECTIONSETTING_BASE_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_KCoreConfigSkeleton__ItemBool)
typedef KCoreConfigSkeleton::ItemBool KCoreConfigSkeleton__ItemBool;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_KCoreConfigSkeleton__ItemString)
typedef KCoreConfigSkeleton::ItemString KCoreConfigSkeleton__ItemString;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAutoCorrectionCore__TextAutoCorrectionSettingsBase)
typedef TextAutoCorrectionCore::TextAutoCorrectionSettingsBase TextAutoCorrectionCore__TextAutoCorrectionSettingsBase;
#endif
#else
typedef struct KConfigSkeleton KConfigSkeleton;
typedef struct KCoreConfigSkeleton KCoreConfigSkeleton;
typedef struct KCoreConfigSkeleton__ItemBool KCoreConfigSkeleton__ItemBool;
typedef struct KCoreConfigSkeleton__ItemString KCoreConfigSkeleton__ItemString;
typedef struct QMetaMethod QMetaMethod;
typedef struct QObject QObject;
typedef struct TextAutoCorrectionCore__TextAutoCorrectionSettingsBase TextAutoCorrectionCore__TextAutoCorrectionSettingsBase;
#endif

TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_Self();
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetEnabled(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_Enabled();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsEnabledImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_EnabledItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetUppercaseFirstCharOfSentence(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_UppercaseFirstCharOfSentence();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsUppercaseFirstCharOfSentenceImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_UppercaseFirstCharOfSentenceItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetFixTwoUppercaseChars(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_FixTwoUppercaseChars();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsFixTwoUppercaseCharsImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_FixTwoUppercaseCharsItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetSingleSpaces(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SingleSpaces();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsSingleSpacesImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SingleSpacesItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetAutoFractions(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AutoFractions();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsAutoFractionsImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AutoFractionsItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetCapitalizeWeekDays(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_CapitalizeWeekDays();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsCapitalizeWeekDaysImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_CapitalizeWeekDaysItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetAdvancedAutocorrect(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AdvancedAutocorrect();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsAdvancedAutocorrectImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AdvancedAutocorrectItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetReplaceDoubleQuotes(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_ReplaceDoubleQuotes();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsReplaceDoubleQuotesImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_ReplaceDoubleQuotesItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetReplaceSingleQuotes(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_ReplaceSingleQuotes();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsReplaceSingleQuotesImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_ReplaceSingleQuotesItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetAutoFormatUrl(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AutoFormatUrl();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsAutoFormatUrlImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AutoFormatUrlItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetAutoBoldUnderline(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AutoBoldUnderline();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsAutoBoldUnderlineImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AutoBoldUnderlineItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetSuperScript(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SuperScript();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsSuperScriptImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SuperScriptItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetAddNonBreakingSpaceInFrench(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AddNonBreakingSpaceInFrench();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsAddNonBreakingSpaceInFrenchImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_AddNonBreakingSpaceInFrenchItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetReplaceDoubleQuotesByFrenchQuotes(bool v);
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_ReplaceDoubleQuotesByFrenchQuotes();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsReplaceDoubleQuotesByFrenchQuotesImmutable();
KCoreConfigSkeleton__ItemBool* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_ReplaceDoubleQuotesByFrenchQuotesItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetTypographicSingleQuotes(const libqt_string v);
libqt_string TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_TypographicSingleQuotes();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsTypographicSingleQuotesImmutable();
KCoreConfigSkeleton__ItemString* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_TypographicSingleQuotesItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetTypographicDoubleQuotes(const libqt_string v);
libqt_string TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_TypographicDoubleQuotes();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsTypographicDoubleQuotesImmutable();
KCoreConfigSkeleton__ItemString* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_TypographicDoubleQuotesItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetCustomWritablePath(const libqt_string v);
libqt_string TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_CustomWritablePath();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsCustomWritablePathImmutable();
KCoreConfigSkeleton__ItemString* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_CustomWritablePathItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_SetCustomSystemPath(const libqt_string v);
libqt_string TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_CustomSystemPath();
bool TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_IsCustomSystemPathImmutable();
KCoreConfigSkeleton__ItemString* TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_CustomSystemPathItem(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);
void TextAutoCorrectionCore__TextAutoCorrectionSettingsBase_Delete(TextAutoCorrectionCore__TextAutoCorrectionSettingsBase* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
