#pragma once
#ifndef SRC_PDFC_LIBQPDFVIEW_H
#define SRC_PDFC_LIBQPDFVIEW_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPdfDocument QPdfDocument;
typedef struct QPdfPageNavigator QPdfPageNavigator;
typedef struct QPdfSearchModel QPdfSearchModel;
typedef struct QPdfView QPdfView;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QPdfView* QPdfView_new(QWidget* parent);
QPdfView* QPdfView_new2();
QMetaObject* QPdfView_MetaObject(const QPdfView* self);
void* QPdfView_Metacast(QPdfView* self, const char* param1);
int QPdfView_Metacall(QPdfView* self, int param1, int param2, void** param3);
void QPdfView_SetDocument(QPdfView* self, QPdfDocument* document);
QPdfDocument* QPdfView_Document(const QPdfView* self);
QPdfSearchModel* QPdfView_SearchModel(const QPdfView* self);
void QPdfView_SetSearchModel(QPdfView* self, QPdfSearchModel* searchModel);
int QPdfView_CurrentSearchResultIndex(const QPdfView* self);
QPdfPageNavigator* QPdfView_PageNavigator(const QPdfView* self);
int QPdfView_PageMode(const QPdfView* self);
int QPdfView_ZoomMode(const QPdfView* self);
double QPdfView_ZoomFactor(const QPdfView* self);
int QPdfView_PageSpacing(const QPdfView* self);
void QPdfView_SetPageSpacing(QPdfView* self, int spacing);
QMargins* QPdfView_DocumentMargins(const QPdfView* self);
void QPdfView_SetDocumentMargins(QPdfView* self, QMargins* margins);
void QPdfView_SetPageMode(QPdfView* self, int mode);
void QPdfView_SetZoomMode(QPdfView* self, int mode);
void QPdfView_SetZoomFactor(QPdfView* self, double factor);
void QPdfView_SetCurrentSearchResultIndex(QPdfView* self, int currentResult);
void QPdfView_DocumentChanged(QPdfView* self, QPdfDocument* document);
void QPdfView_Connect_DocumentChanged(QPdfView* self, intptr_t slot);
void QPdfView_PageModeChanged(QPdfView* self, int pageMode);
void QPdfView_Connect_PageModeChanged(QPdfView* self, intptr_t slot);
void QPdfView_ZoomModeChanged(QPdfView* self, int zoomMode);
void QPdfView_Connect_ZoomModeChanged(QPdfView* self, intptr_t slot);
void QPdfView_ZoomFactorChanged(QPdfView* self, double zoomFactor);
void QPdfView_Connect_ZoomFactorChanged(QPdfView* self, intptr_t slot);
void QPdfView_PageSpacingChanged(QPdfView* self, int pageSpacing);
void QPdfView_Connect_PageSpacingChanged(QPdfView* self, intptr_t slot);
void QPdfView_DocumentMarginsChanged(QPdfView* self, QMargins* documentMargins);
void QPdfView_Connect_DocumentMarginsChanged(QPdfView* self, intptr_t slot);
void QPdfView_SearchModelChanged(QPdfView* self, QPdfSearchModel* searchModel);
void QPdfView_Connect_SearchModelChanged(QPdfView* self, intptr_t slot);
void QPdfView_CurrentSearchResultIndexChanged(QPdfView* self, int currentResult);
void QPdfView_Connect_CurrentSearchResultIndexChanged(QPdfView* self, intptr_t slot);
void QPdfView_PaintEvent(QPdfView* self, QPaintEvent* event);
void QPdfView_ResizeEvent(QPdfView* self, QResizeEvent* event);
void QPdfView_ScrollContentsBy(QPdfView* self, int dx, int dy);
void QPdfView_MousePressEvent(QPdfView* self, QMouseEvent* event);
void QPdfView_MouseMoveEvent(QPdfView* self, QMouseEvent* event);
void QPdfView_MouseReleaseEvent(QPdfView* self, QMouseEvent* event);
void QPdfView_OnMetaObject(const QPdfView* self, intptr_t slot);
QMetaObject* QPdfView_SuperMetaObject(const QPdfView* self);
void QPdfView_OnMetacast(QPdfView* self, intptr_t slot);
void* QPdfView_SuperMetacast(QPdfView* self, const char* param1);
void QPdfView_OnMetacall(QPdfView* self, intptr_t slot);
int QPdfView_SuperMetacall(QPdfView* self, int param1, int param2, void** param3);
void QPdfView_OnPaintEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperPaintEvent(QPdfView* self, QPaintEvent* event);
void QPdfView_OnResizeEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperResizeEvent(QPdfView* self, QResizeEvent* event);
void QPdfView_OnScrollContentsBy(QPdfView* self, intptr_t slot);
void QPdfView_SuperScrollContentsBy(QPdfView* self, int dx, int dy);
void QPdfView_OnMousePressEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperMousePressEvent(QPdfView* self, QMouseEvent* event);
void QPdfView_OnMouseMoveEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperMouseMoveEvent(QPdfView* self, QMouseEvent* event);
void QPdfView_OnMouseReleaseEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperMouseReleaseEvent(QPdfView* self, QMouseEvent* event);
QSize* QPdfView_MinimumSizeHint(const QPdfView* self);
void QPdfView_OnMinimumSizeHint(const QPdfView* self, intptr_t slot);
QSize* QPdfView_SuperMinimumSizeHint(const QPdfView* self);
QSize* QPdfView_SizeHint(const QPdfView* self);
void QPdfView_OnSizeHint(const QPdfView* self, intptr_t slot);
QSize* QPdfView_SuperSizeHint(const QPdfView* self);
void QPdfView_SetupViewport(QPdfView* self, QWidget* viewport);
void QPdfView_OnSetupViewport(QPdfView* self, intptr_t slot);
void QPdfView_SuperSetupViewport(QPdfView* self, QWidget* viewport);
bool QPdfView_EventFilter(QPdfView* self, QObject* param1, QEvent* param2);
void QPdfView_OnEventFilter(QPdfView* self, intptr_t slot);
bool QPdfView_SuperEventFilter(QPdfView* self, QObject* param1, QEvent* param2);
bool QPdfView_Event(QPdfView* self, QEvent* param1);
void QPdfView_OnEvent(QPdfView* self, intptr_t slot);
bool QPdfView_SuperEvent(QPdfView* self, QEvent* param1);
bool QPdfView_ViewportEvent(QPdfView* self, QEvent* param1);
void QPdfView_OnViewportEvent(QPdfView* self, intptr_t slot);
bool QPdfView_SuperViewportEvent(QPdfView* self, QEvent* param1);
void QPdfView_MouseDoubleClickEvent(QPdfView* self, QMouseEvent* param1);
void QPdfView_OnMouseDoubleClickEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperMouseDoubleClickEvent(QPdfView* self, QMouseEvent* param1);
void QPdfView_WheelEvent(QPdfView* self, QWheelEvent* param1);
void QPdfView_OnWheelEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperWheelEvent(QPdfView* self, QWheelEvent* param1);
void QPdfView_ContextMenuEvent(QPdfView* self, QContextMenuEvent* param1);
void QPdfView_OnContextMenuEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperContextMenuEvent(QPdfView* self, QContextMenuEvent* param1);
void QPdfView_DragEnterEvent(QPdfView* self, QDragEnterEvent* param1);
void QPdfView_OnDragEnterEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperDragEnterEvent(QPdfView* self, QDragEnterEvent* param1);
void QPdfView_DragMoveEvent(QPdfView* self, QDragMoveEvent* param1);
void QPdfView_OnDragMoveEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperDragMoveEvent(QPdfView* self, QDragMoveEvent* param1);
void QPdfView_DragLeaveEvent(QPdfView* self, QDragLeaveEvent* param1);
void QPdfView_OnDragLeaveEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperDragLeaveEvent(QPdfView* self, QDragLeaveEvent* param1);
void QPdfView_DropEvent(QPdfView* self, QDropEvent* param1);
void QPdfView_OnDropEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperDropEvent(QPdfView* self, QDropEvent* param1);
void QPdfView_KeyPressEvent(QPdfView* self, QKeyEvent* param1);
void QPdfView_OnKeyPressEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperKeyPressEvent(QPdfView* self, QKeyEvent* param1);
QSize* QPdfView_ViewportSizeHint(const QPdfView* self);
void QPdfView_OnViewportSizeHint(const QPdfView* self, intptr_t slot);
QSize* QPdfView_SuperViewportSizeHint(const QPdfView* self);
void QPdfView_ChangeEvent(QPdfView* self, QEvent* param1);
void QPdfView_OnChangeEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperChangeEvent(QPdfView* self, QEvent* param1);
void QPdfView_InitStyleOption(const QPdfView* self, QStyleOptionFrame* option);
void QPdfView_OnInitStyleOption(const QPdfView* self, intptr_t slot);
void QPdfView_SuperInitStyleOption(const QPdfView* self, QStyleOptionFrame* option);
int QPdfView_DevType(const QPdfView* self);
void QPdfView_OnDevType(const QPdfView* self, intptr_t slot);
int QPdfView_SuperDevType(const QPdfView* self);
void QPdfView_SetVisible(QPdfView* self, bool visible);
void QPdfView_OnSetVisible(QPdfView* self, intptr_t slot);
void QPdfView_SuperSetVisible(QPdfView* self, bool visible);
int QPdfView_HeightForWidth(const QPdfView* self, int param1);
void QPdfView_OnHeightForWidth(const QPdfView* self, intptr_t slot);
int QPdfView_SuperHeightForWidth(const QPdfView* self, int param1);
bool QPdfView_HasHeightForWidth(const QPdfView* self);
void QPdfView_OnHasHeightForWidth(const QPdfView* self, intptr_t slot);
bool QPdfView_SuperHasHeightForWidth(const QPdfView* self);
QPaintEngine* QPdfView_PaintEngine(const QPdfView* self);
void QPdfView_OnPaintEngine(const QPdfView* self, intptr_t slot);
QPaintEngine* QPdfView_SuperPaintEngine(const QPdfView* self);
void QPdfView_KeyReleaseEvent(QPdfView* self, QKeyEvent* event);
void QPdfView_OnKeyReleaseEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperKeyReleaseEvent(QPdfView* self, QKeyEvent* event);
void QPdfView_FocusInEvent(QPdfView* self, QFocusEvent* event);
void QPdfView_OnFocusInEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperFocusInEvent(QPdfView* self, QFocusEvent* event);
void QPdfView_FocusOutEvent(QPdfView* self, QFocusEvent* event);
void QPdfView_OnFocusOutEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperFocusOutEvent(QPdfView* self, QFocusEvent* event);
void QPdfView_EnterEvent(QPdfView* self, QEnterEvent* event);
void QPdfView_OnEnterEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperEnterEvent(QPdfView* self, QEnterEvent* event);
void QPdfView_LeaveEvent(QPdfView* self, QEvent* event);
void QPdfView_OnLeaveEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperLeaveEvent(QPdfView* self, QEvent* event);
void QPdfView_MoveEvent(QPdfView* self, QMoveEvent* event);
void QPdfView_OnMoveEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperMoveEvent(QPdfView* self, QMoveEvent* event);
void QPdfView_CloseEvent(QPdfView* self, QCloseEvent* event);
void QPdfView_OnCloseEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperCloseEvent(QPdfView* self, QCloseEvent* event);
void QPdfView_TabletEvent(QPdfView* self, QTabletEvent* event);
void QPdfView_OnTabletEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperTabletEvent(QPdfView* self, QTabletEvent* event);
void QPdfView_ActionEvent(QPdfView* self, QActionEvent* event);
void QPdfView_OnActionEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperActionEvent(QPdfView* self, QActionEvent* event);
void QPdfView_ShowEvent(QPdfView* self, QShowEvent* event);
void QPdfView_OnShowEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperShowEvent(QPdfView* self, QShowEvent* event);
void QPdfView_HideEvent(QPdfView* self, QHideEvent* event);
void QPdfView_OnHideEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperHideEvent(QPdfView* self, QHideEvent* event);
bool QPdfView_NativeEvent(QPdfView* self, const libqt_string eventType, void* message, intptr_t* result);
void QPdfView_OnNativeEvent(QPdfView* self, intptr_t slot);
bool QPdfView_SuperNativeEvent(QPdfView* self, const libqt_string eventType, void* message, intptr_t* result);
int QPdfView_Metric(const QPdfView* self, int param1);
void QPdfView_OnMetric(const QPdfView* self, intptr_t slot);
int QPdfView_SuperMetric(const QPdfView* self, int param1);
void QPdfView_InitPainter(const QPdfView* self, QPainter* painter);
void QPdfView_OnInitPainter(const QPdfView* self, intptr_t slot);
void QPdfView_SuperInitPainter(const QPdfView* self, QPainter* painter);
QPaintDevice* QPdfView_Redirected(const QPdfView* self, QPoint* offset);
void QPdfView_OnRedirected(const QPdfView* self, intptr_t slot);
QPaintDevice* QPdfView_SuperRedirected(const QPdfView* self, QPoint* offset);
QPainter* QPdfView_SharedPainter(const QPdfView* self);
void QPdfView_OnSharedPainter(const QPdfView* self, intptr_t slot);
QPainter* QPdfView_SuperSharedPainter(const QPdfView* self);
void QPdfView_InputMethodEvent(QPdfView* self, QInputMethodEvent* param1);
void QPdfView_OnInputMethodEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperInputMethodEvent(QPdfView* self, QInputMethodEvent* param1);
QVariant* QPdfView_InputMethodQuery(const QPdfView* self, int param1);
void QPdfView_OnInputMethodQuery(const QPdfView* self, intptr_t slot);
QVariant* QPdfView_SuperInputMethodQuery(const QPdfView* self, int param1);
bool QPdfView_FocusNextPrevChild(QPdfView* self, bool next);
void QPdfView_OnFocusNextPrevChild(QPdfView* self, intptr_t slot);
bool QPdfView_SuperFocusNextPrevChild(QPdfView* self, bool next);
void QPdfView_TimerEvent(QPdfView* self, QTimerEvent* event);
void QPdfView_OnTimerEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperTimerEvent(QPdfView* self, QTimerEvent* event);
void QPdfView_ChildEvent(QPdfView* self, QChildEvent* event);
void QPdfView_OnChildEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperChildEvent(QPdfView* self, QChildEvent* event);
void QPdfView_CustomEvent(QPdfView* self, QEvent* event);
void QPdfView_OnCustomEvent(QPdfView* self, intptr_t slot);
void QPdfView_SuperCustomEvent(QPdfView* self, QEvent* event);
void QPdfView_ConnectNotify(QPdfView* self, const QMetaMethod* signal);
void QPdfView_OnConnectNotify(QPdfView* self, intptr_t slot);
void QPdfView_SuperConnectNotify(QPdfView* self, const QMetaMethod* signal);
void QPdfView_DisconnectNotify(QPdfView* self, const QMetaMethod* signal);
void QPdfView_OnDisconnectNotify(QPdfView* self, intptr_t slot);
void QPdfView_SuperDisconnectNotify(QPdfView* self, const QMetaMethod* signal);
void QPdfView_SetViewportMargins(QPdfView* self, int left, int top, int right, int bottom);
void QPdfView_OnSetViewportMargins(QPdfView* self, intptr_t slot);
void QPdfView_SuperSetViewportMargins(QPdfView* self, int left, int top, int right, int bottom);
QMargins* QPdfView_ViewportMargins(const QPdfView* self);
void QPdfView_OnViewportMargins(const QPdfView* self, intptr_t slot);
QMargins* QPdfView_SuperViewportMargins(const QPdfView* self);
void QPdfView_DrawFrame(QPdfView* self, QPainter* param1);
void QPdfView_OnDrawFrame(QPdfView* self, intptr_t slot);
void QPdfView_SuperDrawFrame(QPdfView* self, QPainter* param1);
void QPdfView_UpdateMicroFocus(QPdfView* self);
void QPdfView_OnUpdateMicroFocus(QPdfView* self, intptr_t slot);
void QPdfView_SuperUpdateMicroFocus(QPdfView* self);
void QPdfView_Create(QPdfView* self);
void QPdfView_OnCreate(QPdfView* self, intptr_t slot);
void QPdfView_SuperCreate(QPdfView* self);
void QPdfView_Destroy(QPdfView* self);
void QPdfView_OnDestroy(QPdfView* self, intptr_t slot);
void QPdfView_SuperDestroy(QPdfView* self);
bool QPdfView_FocusNextChild(QPdfView* self);
void QPdfView_OnFocusNextChild(QPdfView* self, intptr_t slot);
bool QPdfView_SuperFocusNextChild(QPdfView* self);
bool QPdfView_FocusPreviousChild(QPdfView* self);
void QPdfView_OnFocusPreviousChild(QPdfView* self, intptr_t slot);
bool QPdfView_SuperFocusPreviousChild(QPdfView* self);
QObject* QPdfView_Sender(const QPdfView* self);
void QPdfView_OnSender(const QPdfView* self, intptr_t slot);
QObject* QPdfView_SuperSender(const QPdfView* self);
int QPdfView_SenderSignalIndex(const QPdfView* self);
void QPdfView_OnSenderSignalIndex(const QPdfView* self, intptr_t slot);
int QPdfView_SuperSenderSignalIndex(const QPdfView* self);
int QPdfView_Receivers(const QPdfView* self, const char* signal);
void QPdfView_OnReceivers(const QPdfView* self, intptr_t slot);
int QPdfView_SuperReceivers(const QPdfView* self, const char* signal);
bool QPdfView_IsSignalConnected(const QPdfView* self, const QMetaMethod* signal);
void QPdfView_OnIsSignalConnected(const QPdfView* self, intptr_t slot);
bool QPdfView_SuperIsSignalConnected(const QPdfView* self, const QMetaMethod* signal);
double QPdfView_GetDecodedMetricF(const QPdfView* self, int metricA, int metricB);
void QPdfView_OnGetDecodedMetricF(const QPdfView* self, intptr_t slot);
double QPdfView_SuperGetDecodedMetricF(const QPdfView* self, int metricA, int metricB);
void QPdfView_Delete(QPdfView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
