#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_CHARTSC_LIBQPOLARCHART_H
#define SRC_RESTRICTED_EXTRAS_CHARTSC_LIBQPOLARCHART_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractAxis QAbstractAxis;
typedef struct QAbstractSeries QAbstractSeries;
typedef struct QChart QChart;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsLayoutItem QGraphicsLayoutItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneMoveEvent QGraphicsSceneMoveEvent;
typedef struct QGraphicsSceneResizeEvent QGraphicsSceneResizeEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPointF QPointF;
typedef struct QPolarChart QPolarChart;
typedef struct QRectF QRectF;
typedef struct QShowEvent QShowEvent;
typedef struct QSizeF QSizeF;
typedef struct QStyleOption QStyleOption;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

QPolarChart* QPolarChart_new();
QPolarChart* QPolarChart_new2(QGraphicsItem* parent);
QPolarChart* QPolarChart_new3(QGraphicsItem* parent, int wFlags);
QMetaObject* QPolarChart_MetaObject(const QPolarChart* self);
void* QPolarChart_Metacast(QPolarChart* self, const char* param1);
int QPolarChart_Metacall(QPolarChart* self, int param1, int param2, void** param3);
void QPolarChart_AddAxis(QPolarChart* self, QAbstractAxis* axis, int polarOrientation);
libqt_list /* of QAbstractAxis* */ QPolarChart_Axes(const QPolarChart* self);
int QPolarChart_AxisPolarOrientation(QAbstractAxis* axis);
libqt_list /* of QAbstractAxis* */ QPolarChart_Axes1(const QPolarChart* self, int polarOrientation);
libqt_list /* of QAbstractAxis* */ QPolarChart_Axes2(const QPolarChart* self, int polarOrientation, QAbstractSeries* series);
void QPolarChart_OnMetaObject(const QPolarChart* self, intptr_t slot);
QMetaObject* QPolarChart_SuperMetaObject(const QPolarChart* self);
void QPolarChart_OnMetacast(QPolarChart* self, intptr_t slot);
void* QPolarChart_SuperMetacast(QPolarChart* self, const char* param1);
void QPolarChart_OnMetacall(QPolarChart* self, intptr_t slot);
int QPolarChart_SuperMetacall(QPolarChart* self, int param1, int param2, void** param3);
void QPolarChart_SetGeometry(QPolarChart* self, const QRectF* rect);
void QPolarChart_OnSetGeometry(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperSetGeometry(QPolarChart* self, const QRectF* rect);
void QPolarChart_GetContentsMargins(const QPolarChart* self, double* left, double* top, double* right, double* bottom);
void QPolarChart_OnGetContentsMargins(const QPolarChart* self, intptr_t slot);
void QPolarChart_SuperGetContentsMargins(const QPolarChart* self, double* left, double* top, double* right, double* bottom);
int QPolarChart_Type(const QPolarChart* self);
void QPolarChart_OnType(const QPolarChart* self, intptr_t slot);
int QPolarChart_SuperType(const QPolarChart* self);
void QPolarChart_Paint(QPolarChart* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QPolarChart_OnPaint(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperPaint(QPolarChart* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QPolarChart_PaintWindowFrame(QPolarChart* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QPolarChart_OnPaintWindowFrame(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperPaintWindowFrame(QPolarChart* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
QRectF* QPolarChart_BoundingRect(const QPolarChart* self);
void QPolarChart_OnBoundingRect(const QPolarChart* self, intptr_t slot);
QRectF* QPolarChart_SuperBoundingRect(const QPolarChart* self);
QPainterPath* QPolarChart_Shape(const QPolarChart* self);
void QPolarChart_OnShape(const QPolarChart* self, intptr_t slot);
QPainterPath* QPolarChart_SuperShape(const QPolarChart* self);
void QPolarChart_InitStyleOption(const QPolarChart* self, QStyleOption* option);
void QPolarChart_OnInitStyleOption(const QPolarChart* self, intptr_t slot);
void QPolarChart_SuperInitStyleOption(const QPolarChart* self, QStyleOption* option);
QSizeF* QPolarChart_SizeHint(const QPolarChart* self, int which, const QSizeF* constraint);
void QPolarChart_OnSizeHint(const QPolarChart* self, intptr_t slot);
QSizeF* QPolarChart_SuperSizeHint(const QPolarChart* self, int which, const QSizeF* constraint);
void QPolarChart_UpdateGeometry(QPolarChart* self);
void QPolarChart_OnUpdateGeometry(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperUpdateGeometry(QPolarChart* self);
QVariant* QPolarChart_ItemChange(QPolarChart* self, int change, const QVariant* value);
void QPolarChart_OnItemChange(QPolarChart* self, intptr_t slot);
QVariant* QPolarChart_SuperItemChange(QPolarChart* self, int change, const QVariant* value);
QVariant* QPolarChart_PropertyChange(QPolarChart* self, const libqt_string propertyName, const QVariant* value);
void QPolarChart_OnPropertyChange(QPolarChart* self, intptr_t slot);
QVariant* QPolarChart_SuperPropertyChange(QPolarChart* self, const libqt_string propertyName, const QVariant* value);
bool QPolarChart_SceneEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnSceneEvent(QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperSceneEvent(QPolarChart* self, QEvent* event);
bool QPolarChart_WindowFrameEvent(QPolarChart* self, QEvent* e);
void QPolarChart_OnWindowFrameEvent(QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperWindowFrameEvent(QPolarChart* self, QEvent* e);
int QPolarChart_WindowFrameSectionAt(const QPolarChart* self, const QPointF* pos);
void QPolarChart_OnWindowFrameSectionAt(const QPolarChart* self, intptr_t slot);
int QPolarChart_SuperWindowFrameSectionAt(const QPolarChart* self, const QPointF* pos);
bool QPolarChart_Event(QPolarChart* self, QEvent* event);
void QPolarChart_OnEvent(QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperEvent(QPolarChart* self, QEvent* event);
void QPolarChart_ChangeEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnChangeEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperChangeEvent(QPolarChart* self, QEvent* event);
void QPolarChart_CloseEvent(QPolarChart* self, QCloseEvent* event);
void QPolarChart_OnCloseEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperCloseEvent(QPolarChart* self, QCloseEvent* event);
void QPolarChart_FocusInEvent(QPolarChart* self, QFocusEvent* event);
void QPolarChart_OnFocusInEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperFocusInEvent(QPolarChart* self, QFocusEvent* event);
bool QPolarChart_FocusNextPrevChild(QPolarChart* self, bool next);
void QPolarChart_OnFocusNextPrevChild(QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperFocusNextPrevChild(QPolarChart* self, bool next);
void QPolarChart_FocusOutEvent(QPolarChart* self, QFocusEvent* event);
void QPolarChart_OnFocusOutEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperFocusOutEvent(QPolarChart* self, QFocusEvent* event);
void QPolarChart_HideEvent(QPolarChart* self, QHideEvent* event);
void QPolarChart_OnHideEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperHideEvent(QPolarChart* self, QHideEvent* event);
void QPolarChart_MoveEvent(QPolarChart* self, QGraphicsSceneMoveEvent* event);
void QPolarChart_OnMoveEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperMoveEvent(QPolarChart* self, QGraphicsSceneMoveEvent* event);
void QPolarChart_PolishEvent(QPolarChart* self);
void QPolarChart_OnPolishEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperPolishEvent(QPolarChart* self);
void QPolarChart_ResizeEvent(QPolarChart* self, QGraphicsSceneResizeEvent* event);
void QPolarChart_OnResizeEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperResizeEvent(QPolarChart* self, QGraphicsSceneResizeEvent* event);
void QPolarChart_ShowEvent(QPolarChart* self, QShowEvent* event);
void QPolarChart_OnShowEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperShowEvent(QPolarChart* self, QShowEvent* event);
void QPolarChart_HoverMoveEvent(QPolarChart* self, QGraphicsSceneHoverEvent* event);
void QPolarChart_OnHoverMoveEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperHoverMoveEvent(QPolarChart* self, QGraphicsSceneHoverEvent* event);
void QPolarChart_HoverLeaveEvent(QPolarChart* self, QGraphicsSceneHoverEvent* event);
void QPolarChart_OnHoverLeaveEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperHoverLeaveEvent(QPolarChart* self, QGraphicsSceneHoverEvent* event);
void QPolarChart_GrabMouseEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnGrabMouseEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperGrabMouseEvent(QPolarChart* self, QEvent* event);
void QPolarChart_UngrabMouseEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnUngrabMouseEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperUngrabMouseEvent(QPolarChart* self, QEvent* event);
void QPolarChart_GrabKeyboardEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnGrabKeyboardEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperGrabKeyboardEvent(QPolarChart* self, QEvent* event);
void QPolarChart_UngrabKeyboardEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnUngrabKeyboardEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperUngrabKeyboardEvent(QPolarChart* self, QEvent* event);
bool QPolarChart_EventFilter(QPolarChart* self, QObject* watched, QEvent* event);
void QPolarChart_OnEventFilter(QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperEventFilter(QPolarChart* self, QObject* watched, QEvent* event);
void QPolarChart_TimerEvent(QPolarChart* self, QTimerEvent* event);
void QPolarChart_OnTimerEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperTimerEvent(QPolarChart* self, QTimerEvent* event);
void QPolarChart_ChildEvent(QPolarChart* self, QChildEvent* event);
void QPolarChart_OnChildEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperChildEvent(QPolarChart* self, QChildEvent* event);
void QPolarChart_CustomEvent(QPolarChart* self, QEvent* event);
void QPolarChart_OnCustomEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperCustomEvent(QPolarChart* self, QEvent* event);
void QPolarChart_ConnectNotify(QPolarChart* self, const QMetaMethod* signal);
void QPolarChart_OnConnectNotify(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperConnectNotify(QPolarChart* self, const QMetaMethod* signal);
void QPolarChart_DisconnectNotify(QPolarChart* self, const QMetaMethod* signal);
void QPolarChart_OnDisconnectNotify(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperDisconnectNotify(QPolarChart* self, const QMetaMethod* signal);
void QPolarChart_Advance(QPolarChart* self, int phase);
void QPolarChart_OnAdvance(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperAdvance(QPolarChart* self, int phase);
bool QPolarChart_Contains(const QPolarChart* self, const QPointF* point);
void QPolarChart_OnContains(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperContains(const QPolarChart* self, const QPointF* point);
bool QPolarChart_CollidesWithItem(const QPolarChart* self, const QGraphicsItem* other, int mode);
void QPolarChart_OnCollidesWithItem(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperCollidesWithItem(const QPolarChart* self, const QGraphicsItem* other, int mode);
bool QPolarChart_CollidesWithPath(const QPolarChart* self, const QPainterPath* path, int mode);
void QPolarChart_OnCollidesWithPath(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperCollidesWithPath(const QPolarChart* self, const QPainterPath* path, int mode);
bool QPolarChart_IsObscuredBy(const QPolarChart* self, const QGraphicsItem* item);
void QPolarChart_OnIsObscuredBy(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperIsObscuredBy(const QPolarChart* self, const QGraphicsItem* item);
QPainterPath* QPolarChart_OpaqueArea(const QPolarChart* self);
void QPolarChart_OnOpaqueArea(const QPolarChart* self, intptr_t slot);
QPainterPath* QPolarChart_SuperOpaqueArea(const QPolarChart* self);
bool QPolarChart_SceneEventFilter(QPolarChart* self, QGraphicsItem* watched, QEvent* event);
void QPolarChart_OnSceneEventFilter(QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperSceneEventFilter(QPolarChart* self, QGraphicsItem* watched, QEvent* event);
void QPolarChart_ContextMenuEvent(QPolarChart* self, QGraphicsSceneContextMenuEvent* event);
void QPolarChart_OnContextMenuEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperContextMenuEvent(QPolarChart* self, QGraphicsSceneContextMenuEvent* event);
void QPolarChart_DragEnterEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_OnDragEnterEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperDragEnterEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_DragLeaveEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_OnDragLeaveEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperDragLeaveEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_DragMoveEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_OnDragMoveEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperDragMoveEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_DropEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_OnDropEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperDropEvent(QPolarChart* self, QGraphicsSceneDragDropEvent* event);
void QPolarChart_HoverEnterEvent(QPolarChart* self, QGraphicsSceneHoverEvent* event);
void QPolarChart_OnHoverEnterEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperHoverEnterEvent(QPolarChart* self, QGraphicsSceneHoverEvent* event);
void QPolarChart_KeyPressEvent(QPolarChart* self, QKeyEvent* event);
void QPolarChart_OnKeyPressEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperKeyPressEvent(QPolarChart* self, QKeyEvent* event);
void QPolarChart_KeyReleaseEvent(QPolarChart* self, QKeyEvent* event);
void QPolarChart_OnKeyReleaseEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperKeyReleaseEvent(QPolarChart* self, QKeyEvent* event);
void QPolarChart_MousePressEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_OnMousePressEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperMousePressEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_MouseMoveEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_OnMouseMoveEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperMouseMoveEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_MouseReleaseEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_OnMouseReleaseEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperMouseReleaseEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_MouseDoubleClickEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_OnMouseDoubleClickEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperMouseDoubleClickEvent(QPolarChart* self, QGraphicsSceneMouseEvent* event);
void QPolarChart_WheelEvent(QPolarChart* self, QGraphicsSceneWheelEvent* event);
void QPolarChart_OnWheelEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperWheelEvent(QPolarChart* self, QGraphicsSceneWheelEvent* event);
void QPolarChart_InputMethodEvent(QPolarChart* self, QInputMethodEvent* event);
void QPolarChart_OnInputMethodEvent(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperInputMethodEvent(QPolarChart* self, QInputMethodEvent* event);
QVariant* QPolarChart_InputMethodQuery(const QPolarChart* self, int query);
void QPolarChart_OnInputMethodQuery(const QPolarChart* self, intptr_t slot);
QVariant* QPolarChart_SuperInputMethodQuery(const QPolarChart* self, int query);
bool QPolarChart_SupportsExtension(const QPolarChart* self, int extension);
void QPolarChart_OnSupportsExtension(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperSupportsExtension(const QPolarChart* self, int extension);
void QPolarChart_SetExtension(QPolarChart* self, int extension, const QVariant* variant);
void QPolarChart_OnSetExtension(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperSetExtension(QPolarChart* self, int extension, const QVariant* variant);
QVariant* QPolarChart_Extension(const QPolarChart* self, const QVariant* variant);
void QPolarChart_OnExtension(const QPolarChart* self, intptr_t slot);
QVariant* QPolarChart_SuperExtension(const QPolarChart* self, const QVariant* variant);
bool QPolarChart_IsEmpty(const QPolarChart* self);
void QPolarChart_OnIsEmpty(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperIsEmpty(const QPolarChart* self);
void QPolarChart_UpdateMicroFocus(QPolarChart* self);
void QPolarChart_OnUpdateMicroFocus(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperUpdateMicroFocus(QPolarChart* self);
QObject* QPolarChart_Sender(const QPolarChart* self);
void QPolarChart_OnSender(const QPolarChart* self, intptr_t slot);
QObject* QPolarChart_SuperSender(const QPolarChart* self);
int QPolarChart_SenderSignalIndex(const QPolarChart* self);
void QPolarChart_OnSenderSignalIndex(const QPolarChart* self, intptr_t slot);
int QPolarChart_SuperSenderSignalIndex(const QPolarChart* self);
int QPolarChart_Receivers(const QPolarChart* self, const char* signal);
void QPolarChart_OnReceivers(const QPolarChart* self, intptr_t slot);
int QPolarChart_SuperReceivers(const QPolarChart* self, const char* signal);
bool QPolarChart_IsSignalConnected(const QPolarChart* self, const QMetaMethod* signal);
void QPolarChart_OnIsSignalConnected(const QPolarChart* self, intptr_t slot);
bool QPolarChart_SuperIsSignalConnected(const QPolarChart* self, const QMetaMethod* signal);
void QPolarChart_AddToIndex(QPolarChart* self);
void QPolarChart_OnAddToIndex(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperAddToIndex(QPolarChart* self);
void QPolarChart_RemoveFromIndex(QPolarChart* self);
void QPolarChart_OnRemoveFromIndex(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperRemoveFromIndex(QPolarChart* self);
void QPolarChart_PrepareGeometryChange(QPolarChart* self);
void QPolarChart_OnPrepareGeometryChange(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperPrepareGeometryChange(QPolarChart* self);
void QPolarChart_SetGraphicsItem(QPolarChart* self, QGraphicsItem* item);
void QPolarChart_OnSetGraphicsItem(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperSetGraphicsItem(QPolarChart* self, QGraphicsItem* item);
void QPolarChart_SetOwnedByLayout(QPolarChart* self, bool ownedByLayout);
void QPolarChart_OnSetOwnedByLayout(QPolarChart* self, intptr_t slot);
void QPolarChart_SuperSetOwnedByLayout(QPolarChart* self, bool ownedByLayout);
void QPolarChart_Delete(QPolarChart* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
