#pragma once
#ifndef SRC_EXTRAS_KTEXTWIDGETSC_LIBKPLURALHANDLINGSPINBOX_H
#define SRC_EXTRAS_KTEXTWIDGETSC_LIBKPLURALHANDLINGSPINBOX_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KLocalizedString KLocalizedString;
typedef struct KPluralHandlingSpinBox KPluralHandlingSpinBox;
typedef struct QAbstractSpinBox QAbstractSpinBox;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSpinBox QSpinBox;
typedef struct QStyleOptionSpinBox QStyleOptionSpinBox;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KPluralHandlingSpinBox* KPluralHandlingSpinBox_new(QWidget* parent);
KPluralHandlingSpinBox* KPluralHandlingSpinBox_new2();
QMetaObject* KPluralHandlingSpinBox_MetaObject(const KPluralHandlingSpinBox* self);
void* KPluralHandlingSpinBox_Metacast(KPluralHandlingSpinBox* self, const char* param1);
int KPluralHandlingSpinBox_Metacall(KPluralHandlingSpinBox* self, int param1, int param2, void** param3);
void KPluralHandlingSpinBox_SetSuffix(KPluralHandlingSpinBox* self, const KLocalizedString* suffix);
void KPluralHandlingSpinBox_OnMetaObject(const KPluralHandlingSpinBox* self, intptr_t slot);
QMetaObject* KPluralHandlingSpinBox_SuperMetaObject(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnMetacast(KPluralHandlingSpinBox* self, intptr_t slot);
void* KPluralHandlingSpinBox_SuperMetacast(KPluralHandlingSpinBox* self, const char* param1);
void KPluralHandlingSpinBox_OnMetacall(KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperMetacall(KPluralHandlingSpinBox* self, int param1, int param2, void** param3);
bool KPluralHandlingSpinBox_Event(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_OnEvent(KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperEvent(KPluralHandlingSpinBox* self, QEvent* event);
int KPluralHandlingSpinBox_Validate(const KPluralHandlingSpinBox* self, libqt_string input, int* pos);
void KPluralHandlingSpinBox_OnValidate(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperValidate(const KPluralHandlingSpinBox* self, libqt_string input, int* pos);
int KPluralHandlingSpinBox_ValueFromText(const KPluralHandlingSpinBox* self, const libqt_string text);
void KPluralHandlingSpinBox_OnValueFromText(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperValueFromText(const KPluralHandlingSpinBox* self, const libqt_string text);
libqt_string KPluralHandlingSpinBox_TextFromValue(const KPluralHandlingSpinBox* self, int val);
void KPluralHandlingSpinBox_OnTextFromValue(const KPluralHandlingSpinBox* self, intptr_t slot);
libqt_string KPluralHandlingSpinBox_SuperTextFromValue(const KPluralHandlingSpinBox* self, int val);
void KPluralHandlingSpinBox_Fixup(const KPluralHandlingSpinBox* self, libqt_string str);
void KPluralHandlingSpinBox_OnFixup(const KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperFixup(const KPluralHandlingSpinBox* self, libqt_string str);
QSize* KPluralHandlingSpinBox_SizeHint(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnSizeHint(const KPluralHandlingSpinBox* self, intptr_t slot);
QSize* KPluralHandlingSpinBox_SuperSizeHint(const KPluralHandlingSpinBox* self);
QSize* KPluralHandlingSpinBox_MinimumSizeHint(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnMinimumSizeHint(const KPluralHandlingSpinBox* self, intptr_t slot);
QSize* KPluralHandlingSpinBox_SuperMinimumSizeHint(const KPluralHandlingSpinBox* self);
QVariant* KPluralHandlingSpinBox_InputMethodQuery(const KPluralHandlingSpinBox* self, int param1);
void KPluralHandlingSpinBox_OnInputMethodQuery(const KPluralHandlingSpinBox* self, intptr_t slot);
QVariant* KPluralHandlingSpinBox_SuperInputMethodQuery(const KPluralHandlingSpinBox* self, int param1);
void KPluralHandlingSpinBox_StepBy(KPluralHandlingSpinBox* self, int steps);
void KPluralHandlingSpinBox_OnStepBy(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperStepBy(KPluralHandlingSpinBox* self, int steps);
void KPluralHandlingSpinBox_Clear(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnClear(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperClear(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_ResizeEvent(KPluralHandlingSpinBox* self, QResizeEvent* event);
void KPluralHandlingSpinBox_OnResizeEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperResizeEvent(KPluralHandlingSpinBox* self, QResizeEvent* event);
void KPluralHandlingSpinBox_KeyPressEvent(KPluralHandlingSpinBox* self, QKeyEvent* event);
void KPluralHandlingSpinBox_OnKeyPressEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperKeyPressEvent(KPluralHandlingSpinBox* self, QKeyEvent* event);
void KPluralHandlingSpinBox_KeyReleaseEvent(KPluralHandlingSpinBox* self, QKeyEvent* event);
void KPluralHandlingSpinBox_OnKeyReleaseEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperKeyReleaseEvent(KPluralHandlingSpinBox* self, QKeyEvent* event);
void KPluralHandlingSpinBox_WheelEvent(KPluralHandlingSpinBox* self, QWheelEvent* event);
void KPluralHandlingSpinBox_OnWheelEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperWheelEvent(KPluralHandlingSpinBox* self, QWheelEvent* event);
void KPluralHandlingSpinBox_FocusInEvent(KPluralHandlingSpinBox* self, QFocusEvent* event);
void KPluralHandlingSpinBox_OnFocusInEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperFocusInEvent(KPluralHandlingSpinBox* self, QFocusEvent* event);
void KPluralHandlingSpinBox_FocusOutEvent(KPluralHandlingSpinBox* self, QFocusEvent* event);
void KPluralHandlingSpinBox_OnFocusOutEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperFocusOutEvent(KPluralHandlingSpinBox* self, QFocusEvent* event);
void KPluralHandlingSpinBox_ContextMenuEvent(KPluralHandlingSpinBox* self, QContextMenuEvent* event);
void KPluralHandlingSpinBox_OnContextMenuEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperContextMenuEvent(KPluralHandlingSpinBox* self, QContextMenuEvent* event);
void KPluralHandlingSpinBox_ChangeEvent(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_OnChangeEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperChangeEvent(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_CloseEvent(KPluralHandlingSpinBox* self, QCloseEvent* event);
void KPluralHandlingSpinBox_OnCloseEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperCloseEvent(KPluralHandlingSpinBox* self, QCloseEvent* event);
void KPluralHandlingSpinBox_HideEvent(KPluralHandlingSpinBox* self, QHideEvent* event);
void KPluralHandlingSpinBox_OnHideEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperHideEvent(KPluralHandlingSpinBox* self, QHideEvent* event);
void KPluralHandlingSpinBox_MousePressEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_OnMousePressEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperMousePressEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_MouseReleaseEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_OnMouseReleaseEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperMouseReleaseEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_MouseMoveEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_OnMouseMoveEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperMouseMoveEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_TimerEvent(KPluralHandlingSpinBox* self, QTimerEvent* event);
void KPluralHandlingSpinBox_OnTimerEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperTimerEvent(KPluralHandlingSpinBox* self, QTimerEvent* event);
void KPluralHandlingSpinBox_PaintEvent(KPluralHandlingSpinBox* self, QPaintEvent* event);
void KPluralHandlingSpinBox_OnPaintEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperPaintEvent(KPluralHandlingSpinBox* self, QPaintEvent* event);
void KPluralHandlingSpinBox_ShowEvent(KPluralHandlingSpinBox* self, QShowEvent* event);
void KPluralHandlingSpinBox_OnShowEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperShowEvent(KPluralHandlingSpinBox* self, QShowEvent* event);
void KPluralHandlingSpinBox_InitStyleOption(const KPluralHandlingSpinBox* self, QStyleOptionSpinBox* option);
void KPluralHandlingSpinBox_OnInitStyleOption(const KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperInitStyleOption(const KPluralHandlingSpinBox* self, QStyleOptionSpinBox* option);
int KPluralHandlingSpinBox_StepEnabled(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnStepEnabled(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperStepEnabled(const KPluralHandlingSpinBox* self);
int KPluralHandlingSpinBox_DevType(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnDevType(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperDevType(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_SetVisible(KPluralHandlingSpinBox* self, bool visible);
void KPluralHandlingSpinBox_OnSetVisible(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperSetVisible(KPluralHandlingSpinBox* self, bool visible);
int KPluralHandlingSpinBox_HeightForWidth(const KPluralHandlingSpinBox* self, int param1);
void KPluralHandlingSpinBox_OnHeightForWidth(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperHeightForWidth(const KPluralHandlingSpinBox* self, int param1);
bool KPluralHandlingSpinBox_HasHeightForWidth(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnHasHeightForWidth(const KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperHasHeightForWidth(const KPluralHandlingSpinBox* self);
QPaintEngine* KPluralHandlingSpinBox_PaintEngine(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnPaintEngine(const KPluralHandlingSpinBox* self, intptr_t slot);
QPaintEngine* KPluralHandlingSpinBox_SuperPaintEngine(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_MouseDoubleClickEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_OnMouseDoubleClickEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperMouseDoubleClickEvent(KPluralHandlingSpinBox* self, QMouseEvent* event);
void KPluralHandlingSpinBox_EnterEvent(KPluralHandlingSpinBox* self, QEnterEvent* event);
void KPluralHandlingSpinBox_OnEnterEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperEnterEvent(KPluralHandlingSpinBox* self, QEnterEvent* event);
void KPluralHandlingSpinBox_LeaveEvent(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_OnLeaveEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperLeaveEvent(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_MoveEvent(KPluralHandlingSpinBox* self, QMoveEvent* event);
void KPluralHandlingSpinBox_OnMoveEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperMoveEvent(KPluralHandlingSpinBox* self, QMoveEvent* event);
void KPluralHandlingSpinBox_TabletEvent(KPluralHandlingSpinBox* self, QTabletEvent* event);
void KPluralHandlingSpinBox_OnTabletEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperTabletEvent(KPluralHandlingSpinBox* self, QTabletEvent* event);
void KPluralHandlingSpinBox_ActionEvent(KPluralHandlingSpinBox* self, QActionEvent* event);
void KPluralHandlingSpinBox_OnActionEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperActionEvent(KPluralHandlingSpinBox* self, QActionEvent* event);
void KPluralHandlingSpinBox_DragEnterEvent(KPluralHandlingSpinBox* self, QDragEnterEvent* event);
void KPluralHandlingSpinBox_OnDragEnterEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperDragEnterEvent(KPluralHandlingSpinBox* self, QDragEnterEvent* event);
void KPluralHandlingSpinBox_DragMoveEvent(KPluralHandlingSpinBox* self, QDragMoveEvent* event);
void KPluralHandlingSpinBox_OnDragMoveEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperDragMoveEvent(KPluralHandlingSpinBox* self, QDragMoveEvent* event);
void KPluralHandlingSpinBox_DragLeaveEvent(KPluralHandlingSpinBox* self, QDragLeaveEvent* event);
void KPluralHandlingSpinBox_OnDragLeaveEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperDragLeaveEvent(KPluralHandlingSpinBox* self, QDragLeaveEvent* event);
void KPluralHandlingSpinBox_DropEvent(KPluralHandlingSpinBox* self, QDropEvent* event);
void KPluralHandlingSpinBox_OnDropEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperDropEvent(KPluralHandlingSpinBox* self, QDropEvent* event);
bool KPluralHandlingSpinBox_NativeEvent(KPluralHandlingSpinBox* self, const libqt_string eventType, void* message, intptr_t* result);
void KPluralHandlingSpinBox_OnNativeEvent(KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperNativeEvent(KPluralHandlingSpinBox* self, const libqt_string eventType, void* message, intptr_t* result);
int KPluralHandlingSpinBox_Metric(const KPluralHandlingSpinBox* self, int param1);
void KPluralHandlingSpinBox_OnMetric(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperMetric(const KPluralHandlingSpinBox* self, int param1);
void KPluralHandlingSpinBox_InitPainter(const KPluralHandlingSpinBox* self, QPainter* painter);
void KPluralHandlingSpinBox_OnInitPainter(const KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperInitPainter(const KPluralHandlingSpinBox* self, QPainter* painter);
QPaintDevice* KPluralHandlingSpinBox_Redirected(const KPluralHandlingSpinBox* self, QPoint* offset);
void KPluralHandlingSpinBox_OnRedirected(const KPluralHandlingSpinBox* self, intptr_t slot);
QPaintDevice* KPluralHandlingSpinBox_SuperRedirected(const KPluralHandlingSpinBox* self, QPoint* offset);
QPainter* KPluralHandlingSpinBox_SharedPainter(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnSharedPainter(const KPluralHandlingSpinBox* self, intptr_t slot);
QPainter* KPluralHandlingSpinBox_SuperSharedPainter(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_InputMethodEvent(KPluralHandlingSpinBox* self, QInputMethodEvent* param1);
void KPluralHandlingSpinBox_OnInputMethodEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperInputMethodEvent(KPluralHandlingSpinBox* self, QInputMethodEvent* param1);
bool KPluralHandlingSpinBox_FocusNextPrevChild(KPluralHandlingSpinBox* self, bool next);
void KPluralHandlingSpinBox_OnFocusNextPrevChild(KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperFocusNextPrevChild(KPluralHandlingSpinBox* self, bool next);
bool KPluralHandlingSpinBox_EventFilter(KPluralHandlingSpinBox* self, QObject* watched, QEvent* event);
void KPluralHandlingSpinBox_OnEventFilter(KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperEventFilter(KPluralHandlingSpinBox* self, QObject* watched, QEvent* event);
void KPluralHandlingSpinBox_ChildEvent(KPluralHandlingSpinBox* self, QChildEvent* event);
void KPluralHandlingSpinBox_OnChildEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperChildEvent(KPluralHandlingSpinBox* self, QChildEvent* event);
void KPluralHandlingSpinBox_CustomEvent(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_OnCustomEvent(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperCustomEvent(KPluralHandlingSpinBox* self, QEvent* event);
void KPluralHandlingSpinBox_ConnectNotify(KPluralHandlingSpinBox* self, const QMetaMethod* signal);
void KPluralHandlingSpinBox_OnConnectNotify(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperConnectNotify(KPluralHandlingSpinBox* self, const QMetaMethod* signal);
void KPluralHandlingSpinBox_DisconnectNotify(KPluralHandlingSpinBox* self, const QMetaMethod* signal);
void KPluralHandlingSpinBox_OnDisconnectNotify(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperDisconnectNotify(KPluralHandlingSpinBox* self, const QMetaMethod* signal);
QLineEdit* KPluralHandlingSpinBox_LineEdit(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnLineEdit(const KPluralHandlingSpinBox* self, intptr_t slot);
QLineEdit* KPluralHandlingSpinBox_SuperLineEdit(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_SetLineEdit(KPluralHandlingSpinBox* self, QLineEdit* edit);
void KPluralHandlingSpinBox_OnSetLineEdit(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperSetLineEdit(KPluralHandlingSpinBox* self, QLineEdit* edit);
void KPluralHandlingSpinBox_UpdateMicroFocus(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnUpdateMicroFocus(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperUpdateMicroFocus(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_Create(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnCreate(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperCreate(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_Destroy(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnDestroy(KPluralHandlingSpinBox* self, intptr_t slot);
void KPluralHandlingSpinBox_SuperDestroy(KPluralHandlingSpinBox* self);
bool KPluralHandlingSpinBox_FocusNextChild(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnFocusNextChild(KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperFocusNextChild(KPluralHandlingSpinBox* self);
bool KPluralHandlingSpinBox_FocusPreviousChild(KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnFocusPreviousChild(KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperFocusPreviousChild(KPluralHandlingSpinBox* self);
QObject* KPluralHandlingSpinBox_Sender(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnSender(const KPluralHandlingSpinBox* self, intptr_t slot);
QObject* KPluralHandlingSpinBox_SuperSender(const KPluralHandlingSpinBox* self);
int KPluralHandlingSpinBox_SenderSignalIndex(const KPluralHandlingSpinBox* self);
void KPluralHandlingSpinBox_OnSenderSignalIndex(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperSenderSignalIndex(const KPluralHandlingSpinBox* self);
int KPluralHandlingSpinBox_Receivers(const KPluralHandlingSpinBox* self, const char* signal);
void KPluralHandlingSpinBox_OnReceivers(const KPluralHandlingSpinBox* self, intptr_t slot);
int KPluralHandlingSpinBox_SuperReceivers(const KPluralHandlingSpinBox* self, const char* signal);
bool KPluralHandlingSpinBox_IsSignalConnected(const KPluralHandlingSpinBox* self, const QMetaMethod* signal);
void KPluralHandlingSpinBox_OnIsSignalConnected(const KPluralHandlingSpinBox* self, intptr_t slot);
bool KPluralHandlingSpinBox_SuperIsSignalConnected(const KPluralHandlingSpinBox* self, const QMetaMethod* signal);
double KPluralHandlingSpinBox_GetDecodedMetricF(const KPluralHandlingSpinBox* self, int metricA, int metricB);
void KPluralHandlingSpinBox_OnGetDecodedMetricF(const KPluralHandlingSpinBox* self, intptr_t slot);
double KPluralHandlingSpinBox_SuperGetDecodedMetricF(const KPluralHandlingSpinBox* self, int metricA, int metricB);
void KPluralHandlingSpinBox_Delete(KPluralHandlingSpinBox* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
