#pragma once
#ifndef SRC_EXTRAS_KTEXTWIDGETSC_LIBKRICHTEXTWIDGET_H
#define SRC_EXTRAS_KTEXTWIDGETSC_LIBKRICHTEXTWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KRichTextEdit KRichTextEdit;
typedef struct KRichTextWidget KRichTextWidget;
typedef struct KTextEdit KTextEdit;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMenu QMenu;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTextCursor QTextCursor;
typedef struct QTextEdit QTextEdit;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KRichTextWidget* KRichTextWidget_new(QWidget* parent);
KRichTextWidget* KRichTextWidget_new2(const libqt_string text);
KRichTextWidget* KRichTextWidget_new3(const libqt_string text, QWidget* parent);
QMetaObject* KRichTextWidget_MetaObject(const KRichTextWidget* self);
void* KRichTextWidget_Metacast(KRichTextWidget* self, const char* param1);
int KRichTextWidget_Metacall(KRichTextWidget* self, int param1, int param2, void** param3);
libqt_list /* of QAction* */ KRichTextWidget_CreateActions(KRichTextWidget* self);
void KRichTextWidget_SetRichTextSupport(KRichTextWidget* self, const int* support);
int KRichTextWidget_RichTextSupport(const KRichTextWidget* self);
void KRichTextWidget_UpdateActionStates(KRichTextWidget* self);
void KRichTextWidget_SetActionsEnabled(KRichTextWidget* self, bool enabled);
void KRichTextWidget_MouseReleaseEvent(KRichTextWidget* self, QMouseEvent* event);
void KRichTextWidget_OnMetaObject(const KRichTextWidget* self, intptr_t slot);
QMetaObject* KRichTextWidget_SuperMetaObject(const KRichTextWidget* self);
void KRichTextWidget_OnMetacast(KRichTextWidget* self, intptr_t slot);
void* KRichTextWidget_SuperMetacast(KRichTextWidget* self, const char* param1);
void KRichTextWidget_OnMetacall(KRichTextWidget* self, intptr_t slot);
int KRichTextWidget_SuperMetacall(KRichTextWidget* self, int param1, int param2, void** param3);
void KRichTextWidget_OnCreateActions(KRichTextWidget* self, intptr_t slot);
libqt_list /* of QAction* */ KRichTextWidget_SuperCreateActions(KRichTextWidget* self);
void KRichTextWidget_OnMouseReleaseEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperMouseReleaseEvent(KRichTextWidget* self, QMouseEvent* event);
void KRichTextWidget_KeyPressEvent(KRichTextWidget* self, QKeyEvent* event);
void KRichTextWidget_OnKeyPressEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperKeyPressEvent(KRichTextWidget* self, QKeyEvent* event);
void KRichTextWidget_SetReadOnly(KRichTextWidget* self, bool readOnly);
void KRichTextWidget_OnSetReadOnly(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSetReadOnly(KRichTextWidget* self, bool readOnly);
void KRichTextWidget_SetCheckSpellingEnabled(KRichTextWidget* self, bool check);
void KRichTextWidget_OnSetCheckSpellingEnabled(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSetCheckSpellingEnabled(KRichTextWidget* self, bool check);
bool KRichTextWidget_CheckSpellingEnabled(const KRichTextWidget* self);
void KRichTextWidget_OnCheckSpellingEnabled(const KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperCheckSpellingEnabled(const KRichTextWidget* self);
bool KRichTextWidget_ShouldBlockBeSpellChecked(const KRichTextWidget* self, const libqt_string block);
void KRichTextWidget_OnShouldBlockBeSpellChecked(const KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperShouldBlockBeSpellChecked(const KRichTextWidget* self, const libqt_string block);
void KRichTextWidget_CreateHighlighter(KRichTextWidget* self);
void KRichTextWidget_OnCreateHighlighter(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperCreateHighlighter(KRichTextWidget* self);
QMenu* KRichTextWidget_MousePopupMenu(KRichTextWidget* self);
void KRichTextWidget_OnMousePopupMenu(KRichTextWidget* self, intptr_t slot);
QMenu* KRichTextWidget_SuperMousePopupMenu(KRichTextWidget* self);
bool KRichTextWidget_Event(KRichTextWidget* self, QEvent* param1);
void KRichTextWidget_OnEvent(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperEvent(KRichTextWidget* self, QEvent* param1);
void KRichTextWidget_FocusInEvent(KRichTextWidget* self, QFocusEvent* param1);
void KRichTextWidget_OnFocusInEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperFocusInEvent(KRichTextWidget* self, QFocusEvent* param1);
void KRichTextWidget_DeleteWordBack(KRichTextWidget* self);
void KRichTextWidget_OnDeleteWordBack(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDeleteWordBack(KRichTextWidget* self);
void KRichTextWidget_DeleteWordForward(KRichTextWidget* self);
void KRichTextWidget_OnDeleteWordForward(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDeleteWordForward(KRichTextWidget* self);
void KRichTextWidget_ContextMenuEvent(KRichTextWidget* self, QContextMenuEvent* param1);
void KRichTextWidget_OnContextMenuEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperContextMenuEvent(KRichTextWidget* self, QContextMenuEvent* param1);
QVariant* KRichTextWidget_LoadResource(KRichTextWidget* self, int typeVal, const QUrl* name);
void KRichTextWidget_OnLoadResource(KRichTextWidget* self, intptr_t slot);
QVariant* KRichTextWidget_SuperLoadResource(KRichTextWidget* self, int typeVal, const QUrl* name);
QVariant* KRichTextWidget_InputMethodQuery(const KRichTextWidget* self, int property);
void KRichTextWidget_OnInputMethodQuery(const KRichTextWidget* self, intptr_t slot);
QVariant* KRichTextWidget_SuperInputMethodQuery(const KRichTextWidget* self, int property);
void KRichTextWidget_TimerEvent(KRichTextWidget* self, QTimerEvent* e);
void KRichTextWidget_OnTimerEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperTimerEvent(KRichTextWidget* self, QTimerEvent* e);
void KRichTextWidget_KeyReleaseEvent(KRichTextWidget* self, QKeyEvent* e);
void KRichTextWidget_OnKeyReleaseEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperKeyReleaseEvent(KRichTextWidget* self, QKeyEvent* e);
void KRichTextWidget_ResizeEvent(KRichTextWidget* self, QResizeEvent* e);
void KRichTextWidget_OnResizeEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperResizeEvent(KRichTextWidget* self, QResizeEvent* e);
void KRichTextWidget_PaintEvent(KRichTextWidget* self, QPaintEvent* e);
void KRichTextWidget_OnPaintEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperPaintEvent(KRichTextWidget* self, QPaintEvent* e);
void KRichTextWidget_MousePressEvent(KRichTextWidget* self, QMouseEvent* e);
void KRichTextWidget_OnMousePressEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperMousePressEvent(KRichTextWidget* self, QMouseEvent* e);
void KRichTextWidget_MouseMoveEvent(KRichTextWidget* self, QMouseEvent* e);
void KRichTextWidget_OnMouseMoveEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperMouseMoveEvent(KRichTextWidget* self, QMouseEvent* e);
void KRichTextWidget_MouseDoubleClickEvent(KRichTextWidget* self, QMouseEvent* e);
void KRichTextWidget_OnMouseDoubleClickEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperMouseDoubleClickEvent(KRichTextWidget* self, QMouseEvent* e);
bool KRichTextWidget_FocusNextPrevChild(KRichTextWidget* self, bool next);
void KRichTextWidget_OnFocusNextPrevChild(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperFocusNextPrevChild(KRichTextWidget* self, bool next);
void KRichTextWidget_DragEnterEvent(KRichTextWidget* self, QDragEnterEvent* e);
void KRichTextWidget_OnDragEnterEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDragEnterEvent(KRichTextWidget* self, QDragEnterEvent* e);
void KRichTextWidget_DragLeaveEvent(KRichTextWidget* self, QDragLeaveEvent* e);
void KRichTextWidget_OnDragLeaveEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDragLeaveEvent(KRichTextWidget* self, QDragLeaveEvent* e);
void KRichTextWidget_DragMoveEvent(KRichTextWidget* self, QDragMoveEvent* e);
void KRichTextWidget_OnDragMoveEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDragMoveEvent(KRichTextWidget* self, QDragMoveEvent* e);
void KRichTextWidget_DropEvent(KRichTextWidget* self, QDropEvent* e);
void KRichTextWidget_OnDropEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDropEvent(KRichTextWidget* self, QDropEvent* e);
void KRichTextWidget_FocusOutEvent(KRichTextWidget* self, QFocusEvent* e);
void KRichTextWidget_OnFocusOutEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperFocusOutEvent(KRichTextWidget* self, QFocusEvent* e);
void KRichTextWidget_ShowEvent(KRichTextWidget* self, QShowEvent* param1);
void KRichTextWidget_OnShowEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperShowEvent(KRichTextWidget* self, QShowEvent* param1);
void KRichTextWidget_ChangeEvent(KRichTextWidget* self, QEvent* e);
void KRichTextWidget_OnChangeEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperChangeEvent(KRichTextWidget* self, QEvent* e);
void KRichTextWidget_WheelEvent(KRichTextWidget* self, QWheelEvent* e);
void KRichTextWidget_OnWheelEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperWheelEvent(KRichTextWidget* self, QWheelEvent* e);
QMimeData* KRichTextWidget_CreateMimeDataFromSelection(const KRichTextWidget* self);
void KRichTextWidget_OnCreateMimeDataFromSelection(const KRichTextWidget* self, intptr_t slot);
QMimeData* KRichTextWidget_SuperCreateMimeDataFromSelection(const KRichTextWidget* self);
bool KRichTextWidget_CanInsertFromMimeData(const KRichTextWidget* self, const QMimeData* source);
void KRichTextWidget_OnCanInsertFromMimeData(const KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperCanInsertFromMimeData(const KRichTextWidget* self, const QMimeData* source);
void KRichTextWidget_InsertFromMimeData(KRichTextWidget* self, const QMimeData* source);
void KRichTextWidget_OnInsertFromMimeData(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperInsertFromMimeData(KRichTextWidget* self, const QMimeData* source);
void KRichTextWidget_InputMethodEvent(KRichTextWidget* self, QInputMethodEvent* param1);
void KRichTextWidget_OnInputMethodEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperInputMethodEvent(KRichTextWidget* self, QInputMethodEvent* param1);
void KRichTextWidget_ScrollContentsBy(KRichTextWidget* self, int dx, int dy);
void KRichTextWidget_OnScrollContentsBy(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperScrollContentsBy(KRichTextWidget* self, int dx, int dy);
void KRichTextWidget_DoSetTextCursor(KRichTextWidget* self, const QTextCursor* cursor);
void KRichTextWidget_OnDoSetTextCursor(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDoSetTextCursor(KRichTextWidget* self, const QTextCursor* cursor);
QSize* KRichTextWidget_MinimumSizeHint(const KRichTextWidget* self);
void KRichTextWidget_OnMinimumSizeHint(const KRichTextWidget* self, intptr_t slot);
QSize* KRichTextWidget_SuperMinimumSizeHint(const KRichTextWidget* self);
QSize* KRichTextWidget_SizeHint(const KRichTextWidget* self);
void KRichTextWidget_OnSizeHint(const KRichTextWidget* self, intptr_t slot);
QSize* KRichTextWidget_SuperSizeHint(const KRichTextWidget* self);
void KRichTextWidget_SetupViewport(KRichTextWidget* self, QWidget* viewport);
void KRichTextWidget_OnSetupViewport(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSetupViewport(KRichTextWidget* self, QWidget* viewport);
bool KRichTextWidget_EventFilter(KRichTextWidget* self, QObject* param1, QEvent* param2);
void KRichTextWidget_OnEventFilter(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperEventFilter(KRichTextWidget* self, QObject* param1, QEvent* param2);
bool KRichTextWidget_ViewportEvent(KRichTextWidget* self, QEvent* param1);
void KRichTextWidget_OnViewportEvent(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperViewportEvent(KRichTextWidget* self, QEvent* param1);
QSize* KRichTextWidget_ViewportSizeHint(const KRichTextWidget* self);
void KRichTextWidget_OnViewportSizeHint(const KRichTextWidget* self, intptr_t slot);
QSize* KRichTextWidget_SuperViewportSizeHint(const KRichTextWidget* self);
void KRichTextWidget_InitStyleOption(const KRichTextWidget* self, QStyleOptionFrame* option);
void KRichTextWidget_OnInitStyleOption(const KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperInitStyleOption(const KRichTextWidget* self, QStyleOptionFrame* option);
int KRichTextWidget_DevType(const KRichTextWidget* self);
void KRichTextWidget_OnDevType(const KRichTextWidget* self, intptr_t slot);
int KRichTextWidget_SuperDevType(const KRichTextWidget* self);
void KRichTextWidget_SetVisible(KRichTextWidget* self, bool visible);
void KRichTextWidget_OnSetVisible(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSetVisible(KRichTextWidget* self, bool visible);
int KRichTextWidget_HeightForWidth(const KRichTextWidget* self, int param1);
void KRichTextWidget_OnHeightForWidth(const KRichTextWidget* self, intptr_t slot);
int KRichTextWidget_SuperHeightForWidth(const KRichTextWidget* self, int param1);
bool KRichTextWidget_HasHeightForWidth(const KRichTextWidget* self);
void KRichTextWidget_OnHasHeightForWidth(const KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperHasHeightForWidth(const KRichTextWidget* self);
QPaintEngine* KRichTextWidget_PaintEngine(const KRichTextWidget* self);
void KRichTextWidget_OnPaintEngine(const KRichTextWidget* self, intptr_t slot);
QPaintEngine* KRichTextWidget_SuperPaintEngine(const KRichTextWidget* self);
void KRichTextWidget_EnterEvent(KRichTextWidget* self, QEnterEvent* event);
void KRichTextWidget_OnEnterEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperEnterEvent(KRichTextWidget* self, QEnterEvent* event);
void KRichTextWidget_LeaveEvent(KRichTextWidget* self, QEvent* event);
void KRichTextWidget_OnLeaveEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperLeaveEvent(KRichTextWidget* self, QEvent* event);
void KRichTextWidget_MoveEvent(KRichTextWidget* self, QMoveEvent* event);
void KRichTextWidget_OnMoveEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperMoveEvent(KRichTextWidget* self, QMoveEvent* event);
void KRichTextWidget_CloseEvent(KRichTextWidget* self, QCloseEvent* event);
void KRichTextWidget_OnCloseEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperCloseEvent(KRichTextWidget* self, QCloseEvent* event);
void KRichTextWidget_TabletEvent(KRichTextWidget* self, QTabletEvent* event);
void KRichTextWidget_OnTabletEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperTabletEvent(KRichTextWidget* self, QTabletEvent* event);
void KRichTextWidget_ActionEvent(KRichTextWidget* self, QActionEvent* event);
void KRichTextWidget_OnActionEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperActionEvent(KRichTextWidget* self, QActionEvent* event);
void KRichTextWidget_HideEvent(KRichTextWidget* self, QHideEvent* event);
void KRichTextWidget_OnHideEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperHideEvent(KRichTextWidget* self, QHideEvent* event);
bool KRichTextWidget_NativeEvent(KRichTextWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void KRichTextWidget_OnNativeEvent(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperNativeEvent(KRichTextWidget* self, const libqt_string eventType, void* message, intptr_t* result);
int KRichTextWidget_Metric(const KRichTextWidget* self, int param1);
void KRichTextWidget_OnMetric(const KRichTextWidget* self, intptr_t slot);
int KRichTextWidget_SuperMetric(const KRichTextWidget* self, int param1);
void KRichTextWidget_InitPainter(const KRichTextWidget* self, QPainter* painter);
void KRichTextWidget_OnInitPainter(const KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperInitPainter(const KRichTextWidget* self, QPainter* painter);
QPaintDevice* KRichTextWidget_Redirected(const KRichTextWidget* self, QPoint* offset);
void KRichTextWidget_OnRedirected(const KRichTextWidget* self, intptr_t slot);
QPaintDevice* KRichTextWidget_SuperRedirected(const KRichTextWidget* self, QPoint* offset);
QPainter* KRichTextWidget_SharedPainter(const KRichTextWidget* self);
void KRichTextWidget_OnSharedPainter(const KRichTextWidget* self, intptr_t slot);
QPainter* KRichTextWidget_SuperSharedPainter(const KRichTextWidget* self);
void KRichTextWidget_ChildEvent(KRichTextWidget* self, QChildEvent* event);
void KRichTextWidget_OnChildEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperChildEvent(KRichTextWidget* self, QChildEvent* event);
void KRichTextWidget_CustomEvent(KRichTextWidget* self, QEvent* event);
void KRichTextWidget_OnCustomEvent(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperCustomEvent(KRichTextWidget* self, QEvent* event);
void KRichTextWidget_ConnectNotify(KRichTextWidget* self, const QMetaMethod* signal);
void KRichTextWidget_OnConnectNotify(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperConnectNotify(KRichTextWidget* self, const QMetaMethod* signal);
void KRichTextWidget_DisconnectNotify(KRichTextWidget* self, const QMetaMethod* signal);
void KRichTextWidget_OnDisconnectNotify(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDisconnectNotify(KRichTextWidget* self, const QMetaMethod* signal);
void KRichTextWidget_SlotDoReplace(KRichTextWidget* self);
void KRichTextWidget_OnSlotDoReplace(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotDoReplace(KRichTextWidget* self);
void KRichTextWidget_SlotReplaceNext(KRichTextWidget* self);
void KRichTextWidget_OnSlotReplaceNext(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotReplaceNext(KRichTextWidget* self);
void KRichTextWidget_SlotDoFind(KRichTextWidget* self);
void KRichTextWidget_OnSlotDoFind(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotDoFind(KRichTextWidget* self);
void KRichTextWidget_SlotFind(KRichTextWidget* self);
void KRichTextWidget_OnSlotFind(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotFind(KRichTextWidget* self);
void KRichTextWidget_SlotFindNext(KRichTextWidget* self);
void KRichTextWidget_OnSlotFindNext(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotFindNext(KRichTextWidget* self);
void KRichTextWidget_SlotFindPrevious(KRichTextWidget* self);
void KRichTextWidget_OnSlotFindPrevious(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotFindPrevious(KRichTextWidget* self);
void KRichTextWidget_SlotReplace(KRichTextWidget* self);
void KRichTextWidget_OnSlotReplace(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotReplace(KRichTextWidget* self);
void KRichTextWidget_SlotSpeakText(KRichTextWidget* self);
void KRichTextWidget_OnSlotSpeakText(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSlotSpeakText(KRichTextWidget* self);
void KRichTextWidget_ZoomInF(KRichTextWidget* self, float range);
void KRichTextWidget_OnZoomInF(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperZoomInF(KRichTextWidget* self, float range);
void KRichTextWidget_SetViewportMargins(KRichTextWidget* self, int left, int top, int right, int bottom);
void KRichTextWidget_OnSetViewportMargins(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperSetViewportMargins(KRichTextWidget* self, int left, int top, int right, int bottom);
QMargins* KRichTextWidget_ViewportMargins(const KRichTextWidget* self);
void KRichTextWidget_OnViewportMargins(const KRichTextWidget* self, intptr_t slot);
QMargins* KRichTextWidget_SuperViewportMargins(const KRichTextWidget* self);
void KRichTextWidget_DrawFrame(KRichTextWidget* self, QPainter* param1);
void KRichTextWidget_OnDrawFrame(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDrawFrame(KRichTextWidget* self, QPainter* param1);
void KRichTextWidget_UpdateMicroFocus(KRichTextWidget* self);
void KRichTextWidget_OnUpdateMicroFocus(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperUpdateMicroFocus(KRichTextWidget* self);
void KRichTextWidget_Create(KRichTextWidget* self);
void KRichTextWidget_OnCreate(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperCreate(KRichTextWidget* self);
void KRichTextWidget_Destroy(KRichTextWidget* self);
void KRichTextWidget_OnDestroy(KRichTextWidget* self, intptr_t slot);
void KRichTextWidget_SuperDestroy(KRichTextWidget* self);
bool KRichTextWidget_FocusNextChild(KRichTextWidget* self);
void KRichTextWidget_OnFocusNextChild(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperFocusNextChild(KRichTextWidget* self);
bool KRichTextWidget_FocusPreviousChild(KRichTextWidget* self);
void KRichTextWidget_OnFocusPreviousChild(KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperFocusPreviousChild(KRichTextWidget* self);
QObject* KRichTextWidget_Sender(const KRichTextWidget* self);
void KRichTextWidget_OnSender(const KRichTextWidget* self, intptr_t slot);
QObject* KRichTextWidget_SuperSender(const KRichTextWidget* self);
int KRichTextWidget_SenderSignalIndex(const KRichTextWidget* self);
void KRichTextWidget_OnSenderSignalIndex(const KRichTextWidget* self, intptr_t slot);
int KRichTextWidget_SuperSenderSignalIndex(const KRichTextWidget* self);
int KRichTextWidget_Receivers(const KRichTextWidget* self, const char* signal);
void KRichTextWidget_OnReceivers(const KRichTextWidget* self, intptr_t slot);
int KRichTextWidget_SuperReceivers(const KRichTextWidget* self, const char* signal);
bool KRichTextWidget_IsSignalConnected(const KRichTextWidget* self, const QMetaMethod* signal);
void KRichTextWidget_OnIsSignalConnected(const KRichTextWidget* self, intptr_t slot);
bool KRichTextWidget_SuperIsSignalConnected(const KRichTextWidget* self, const QMetaMethod* signal);
double KRichTextWidget_GetDecodedMetricF(const KRichTextWidget* self, int metricA, int metricB);
void KRichTextWidget_OnGetDecodedMetricF(const KRichTextWidget* self, intptr_t slot);
double KRichTextWidget_SuperGetDecodedMetricF(const KRichTextWidget* self, int metricA, int metricB);
void KRichTextWidget_Delete(KRichTextWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
