#pragma once
#ifndef SRC_EXTRAS_KITEMVIEWSC_LIBKCATEGORIZEDVIEW_H
#define SRC_EXTRAS_KITEMVIEWSC_LIBKCATEGORIZEDVIEW_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KCategorizedView KCategorizedView;
typedef struct KCategoryDrawer KCategoryDrawer;
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QItemSelectionModel QItemSelectionModel;
typedef struct QKeyEvent QKeyEvent;
typedef struct QListView QListView;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QRegion QRegion;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QStyleOptionViewItem QStyleOptionViewItem;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KCategorizedView* KCategorizedView_new(QWidget* parent);
KCategorizedView* KCategorizedView_new2();
QMetaObject* KCategorizedView_MetaObject(const KCategorizedView* self);
void* KCategorizedView_Metacast(KCategorizedView* self, const char* param1);
int KCategorizedView_Metacall(KCategorizedView* self, int param1, int param2, void** param3);
void KCategorizedView_SetModel(KCategorizedView* self, QAbstractItemModel* model);
void KCategorizedView_SetGridSize(KCategorizedView* self, const QSize* size);
void KCategorizedView_SetGridSizeOwn(KCategorizedView* self, const QSize* size);
QRect* KCategorizedView_VisualRect(const KCategorizedView* self, const QModelIndex* index);
KCategoryDrawer* KCategorizedView_CategoryDrawer(const KCategorizedView* self);
void KCategorizedView_SetCategoryDrawer(KCategorizedView* self, KCategoryDrawer* categoryDrawer);
int KCategorizedView_CategorySpacing(const KCategorizedView* self);
void KCategorizedView_SetCategorySpacing(KCategorizedView* self, int categorySpacing);
bool KCategorizedView_AlternatingBlockColors(const KCategorizedView* self);
void KCategorizedView_SetAlternatingBlockColors(KCategorizedView* self, bool enable);
bool KCategorizedView_CollapsibleBlocks(const KCategorizedView* self);
void KCategorizedView_SetCollapsibleBlocks(KCategorizedView* self, bool enable);
libqt_list /* of QModelIndex* */ KCategorizedView_Block(KCategorizedView* self, const libqt_string category);
libqt_list /* of QModelIndex* */ KCategorizedView_Block2(KCategorizedView* self, const QModelIndex* representative);
QModelIndex* KCategorizedView_IndexAt(const KCategorizedView* self, const QPoint* point);
void KCategorizedView_Reset(KCategorizedView* self);
void KCategorizedView_CategorySpacingChanged(KCategorizedView* self, int spacing);
void KCategorizedView_Connect_CategorySpacingChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_AlternatingBlockColorsChanged(KCategorizedView* self, bool enable);
void KCategorizedView_Connect_AlternatingBlockColorsChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_CollapsibleBlocksChanged(KCategorizedView* self, bool enable);
void KCategorizedView_Connect_CollapsibleBlocksChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_PaintEvent(KCategorizedView* self, QPaintEvent* event);
void KCategorizedView_ResizeEvent(KCategorizedView* self, QResizeEvent* event);
void KCategorizedView_SetSelection(KCategorizedView* self, const QRect* rect, int flags);
void KCategorizedView_MouseMoveEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_MousePressEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_MouseReleaseEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_LeaveEvent(KCategorizedView* self, QEvent* event);
void KCategorizedView_StartDrag(KCategorizedView* self, int supportedActions);
void KCategorizedView_DragMoveEvent(KCategorizedView* self, QDragMoveEvent* event);
void KCategorizedView_DragEnterEvent(KCategorizedView* self, QDragEnterEvent* event);
void KCategorizedView_DragLeaveEvent(KCategorizedView* self, QDragLeaveEvent* event);
void KCategorizedView_DropEvent(KCategorizedView* self, QDropEvent* event);
QModelIndex* KCategorizedView_MoveCursor(KCategorizedView* self, int cursorAction, int modifiers);
void KCategorizedView_RowsAboutToBeRemoved(KCategorizedView* self, const QModelIndex* parent, int start, int end);
void KCategorizedView_UpdateGeometries(KCategorizedView* self);
void KCategorizedView_CurrentChanged(KCategorizedView* self, const QModelIndex* current, const QModelIndex* previous);
void KCategorizedView_DataChanged(KCategorizedView* self, const QModelIndex* topLeft, const QModelIndex* bottomRight, const libqt_list /* of int */ roles);
void KCategorizedView_RowsInserted(KCategorizedView* self, const QModelIndex* parent, int start, int end);
void KCategorizedView_SlotLayoutChanged(KCategorizedView* self);
void KCategorizedView_OnMetaObject(const KCategorizedView* self, intptr_t slot);
QMetaObject* KCategorizedView_SuperMetaObject(const KCategorizedView* self);
void KCategorizedView_OnMetacast(KCategorizedView* self, intptr_t slot);
void* KCategorizedView_SuperMetacast(KCategorizedView* self, const char* param1);
void KCategorizedView_OnMetacall(KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperMetacall(KCategorizedView* self, int param1, int param2, void** param3);
void KCategorizedView_OnSetModel(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetModel(KCategorizedView* self, QAbstractItemModel* model);
void KCategorizedView_OnVisualRect(const KCategorizedView* self, intptr_t slot);
QRect* KCategorizedView_SuperVisualRect(const KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_OnIndexAt(const KCategorizedView* self, intptr_t slot);
QModelIndex* KCategorizedView_SuperIndexAt(const KCategorizedView* self, const QPoint* point);
void KCategorizedView_OnReset(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperReset(KCategorizedView* self);
void KCategorizedView_OnPaintEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperPaintEvent(KCategorizedView* self, QPaintEvent* event);
void KCategorizedView_OnResizeEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperResizeEvent(KCategorizedView* self, QResizeEvent* event);
void KCategorizedView_OnSetSelection(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetSelection(KCategorizedView* self, const QRect* rect, int flags);
void KCategorizedView_OnMouseMoveEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperMouseMoveEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_OnMousePressEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperMousePressEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_OnMouseReleaseEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperMouseReleaseEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_OnLeaveEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperLeaveEvent(KCategorizedView* self, QEvent* event);
void KCategorizedView_OnStartDrag(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperStartDrag(KCategorizedView* self, int supportedActions);
void KCategorizedView_OnDragMoveEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDragMoveEvent(KCategorizedView* self, QDragMoveEvent* event);
void KCategorizedView_OnDragEnterEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDragEnterEvent(KCategorizedView* self, QDragEnterEvent* event);
void KCategorizedView_OnDragLeaveEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDragLeaveEvent(KCategorizedView* self, QDragLeaveEvent* event);
void KCategorizedView_OnDropEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDropEvent(KCategorizedView* self, QDropEvent* event);
void KCategorizedView_OnMoveCursor(KCategorizedView* self, intptr_t slot);
QModelIndex* KCategorizedView_SuperMoveCursor(KCategorizedView* self, int cursorAction, int modifiers);
void KCategorizedView_OnRowsAboutToBeRemoved(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperRowsAboutToBeRemoved(KCategorizedView* self, const QModelIndex* parent, int start, int end);
void KCategorizedView_OnUpdateGeometries(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperUpdateGeometries(KCategorizedView* self);
void KCategorizedView_OnCurrentChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperCurrentChanged(KCategorizedView* self, const QModelIndex* current, const QModelIndex* previous);
void KCategorizedView_OnDataChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDataChanged(KCategorizedView* self, const QModelIndex* topLeft, const QModelIndex* bottomRight, const libqt_list /* of int */ roles);
void KCategorizedView_OnRowsInserted(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperRowsInserted(KCategorizedView* self, const QModelIndex* parent, int start, int end);
void KCategorizedView_OnSlotLayoutChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSlotLayoutChanged(KCategorizedView* self);
void KCategorizedView_ScrollTo(KCategorizedView* self, const QModelIndex* index, int hint);
void KCategorizedView_OnScrollTo(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperScrollTo(KCategorizedView* self, const QModelIndex* index, int hint);
void KCategorizedView_DoItemsLayout(KCategorizedView* self);
void KCategorizedView_OnDoItemsLayout(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDoItemsLayout(KCategorizedView* self);
void KCategorizedView_SetRootIndex(KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_OnSetRootIndex(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetRootIndex(KCategorizedView* self, const QModelIndex* index);
bool KCategorizedView_Event(KCategorizedView* self, QEvent* e);
void KCategorizedView_OnEvent(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperEvent(KCategorizedView* self, QEvent* e);
void KCategorizedView_ScrollContentsBy(KCategorizedView* self, int dx, int dy);
void KCategorizedView_OnScrollContentsBy(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperScrollContentsBy(KCategorizedView* self, int dx, int dy);
void KCategorizedView_WheelEvent(KCategorizedView* self, QWheelEvent* e);
void KCategorizedView_OnWheelEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperWheelEvent(KCategorizedView* self, QWheelEvent* e);
void KCategorizedView_TimerEvent(KCategorizedView* self, QTimerEvent* e);
void KCategorizedView_OnTimerEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperTimerEvent(KCategorizedView* self, QTimerEvent* e);
void KCategorizedView_InitViewItemOption(const KCategorizedView* self, QStyleOptionViewItem* option);
void KCategorizedView_OnInitViewItemOption(const KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperInitViewItemOption(const KCategorizedView* self, QStyleOptionViewItem* option);
int KCategorizedView_HorizontalOffset(const KCategorizedView* self);
void KCategorizedView_OnHorizontalOffset(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperHorizontalOffset(const KCategorizedView* self);
int KCategorizedView_VerticalOffset(const KCategorizedView* self);
void KCategorizedView_OnVerticalOffset(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperVerticalOffset(const KCategorizedView* self);
QRegion* KCategorizedView_VisualRegionForSelection(const KCategorizedView* self, const QItemSelection* selection);
void KCategorizedView_OnVisualRegionForSelection(const KCategorizedView* self, intptr_t slot);
QRegion* KCategorizedView_SuperVisualRegionForSelection(const KCategorizedView* self, const QItemSelection* selection);
libqt_list /* of QModelIndex* */ KCategorizedView_SelectedIndexes(const KCategorizedView* self);
void KCategorizedView_OnSelectedIndexes(const KCategorizedView* self, intptr_t slot);
libqt_list /* of QModelIndex* */ KCategorizedView_SuperSelectedIndexes(const KCategorizedView* self);
bool KCategorizedView_IsIndexHidden(const KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_OnIsIndexHidden(const KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperIsIndexHidden(const KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_SelectionChanged(KCategorizedView* self, const QItemSelection* selected, const QItemSelection* deselected);
void KCategorizedView_OnSelectionChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSelectionChanged(KCategorizedView* self, const QItemSelection* selected, const QItemSelection* deselected);
QSize* KCategorizedView_ViewportSizeHint(const KCategorizedView* self);
void KCategorizedView_OnViewportSizeHint(const KCategorizedView* self, intptr_t slot);
QSize* KCategorizedView_SuperViewportSizeHint(const KCategorizedView* self);
void KCategorizedView_SetSelectionModel(KCategorizedView* self, QItemSelectionModel* selectionModel);
void KCategorizedView_OnSetSelectionModel(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetSelectionModel(KCategorizedView* self, QItemSelectionModel* selectionModel);
void KCategorizedView_KeyboardSearch(KCategorizedView* self, const libqt_string search);
void KCategorizedView_OnKeyboardSearch(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperKeyboardSearch(KCategorizedView* self, const libqt_string search);
int KCategorizedView_SizeHintForRow(const KCategorizedView* self, int row);
void KCategorizedView_OnSizeHintForRow(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperSizeHintForRow(const KCategorizedView* self, int row);
int KCategorizedView_SizeHintForColumn(const KCategorizedView* self, int column);
void KCategorizedView_OnSizeHintForColumn(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperSizeHintForColumn(const KCategorizedView* self, int column);
QAbstractItemDelegate* KCategorizedView_ItemDelegateForIndex(const KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_OnItemDelegateForIndex(const KCategorizedView* self, intptr_t slot);
QAbstractItemDelegate* KCategorizedView_SuperItemDelegateForIndex(const KCategorizedView* self, const QModelIndex* index);
QVariant* KCategorizedView_InputMethodQuery(const KCategorizedView* self, int query);
void KCategorizedView_OnInputMethodQuery(const KCategorizedView* self, intptr_t slot);
QVariant* KCategorizedView_SuperInputMethodQuery(const KCategorizedView* self, int query);
void KCategorizedView_SelectAll(KCategorizedView* self);
void KCategorizedView_OnSelectAll(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSelectAll(KCategorizedView* self);
void KCategorizedView_UpdateEditorData(KCategorizedView* self);
void KCategorizedView_OnUpdateEditorData(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperUpdateEditorData(KCategorizedView* self);
void KCategorizedView_UpdateEditorGeometries(KCategorizedView* self);
void KCategorizedView_OnUpdateEditorGeometries(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperUpdateEditorGeometries(KCategorizedView* self);
void KCategorizedView_VerticalScrollbarAction(KCategorizedView* self, int action);
void KCategorizedView_OnVerticalScrollbarAction(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperVerticalScrollbarAction(KCategorizedView* self, int action);
void KCategorizedView_HorizontalScrollbarAction(KCategorizedView* self, int action);
void KCategorizedView_OnHorizontalScrollbarAction(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperHorizontalScrollbarAction(KCategorizedView* self, int action);
void KCategorizedView_VerticalScrollbarValueChanged(KCategorizedView* self, int value);
void KCategorizedView_OnVerticalScrollbarValueChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperVerticalScrollbarValueChanged(KCategorizedView* self, int value);
void KCategorizedView_HorizontalScrollbarValueChanged(KCategorizedView* self, int value);
void KCategorizedView_OnHorizontalScrollbarValueChanged(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperHorizontalScrollbarValueChanged(KCategorizedView* self, int value);
void KCategorizedView_CloseEditor(KCategorizedView* self, QWidget* editor, int hint);
void KCategorizedView_OnCloseEditor(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperCloseEditor(KCategorizedView* self, QWidget* editor, int hint);
void KCategorizedView_CommitData(KCategorizedView* self, QWidget* editor);
void KCategorizedView_OnCommitData(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperCommitData(KCategorizedView* self, QWidget* editor);
void KCategorizedView_EditorDestroyed(KCategorizedView* self, QObject* editor);
void KCategorizedView_OnEditorDestroyed(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperEditorDestroyed(KCategorizedView* self, QObject* editor);
bool KCategorizedView_Edit2(KCategorizedView* self, const QModelIndex* index, int trigger, QEvent* event);
void KCategorizedView_OnEdit2(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperEdit2(KCategorizedView* self, const QModelIndex* index, int trigger, QEvent* event);
int KCategorizedView_SelectionCommand(const KCategorizedView* self, const QModelIndex* index, const QEvent* event);
void KCategorizedView_OnSelectionCommand(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperSelectionCommand(const KCategorizedView* self, const QModelIndex* index, const QEvent* event);
bool KCategorizedView_FocusNextPrevChild(KCategorizedView* self, bool next);
void KCategorizedView_OnFocusNextPrevChild(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperFocusNextPrevChild(KCategorizedView* self, bool next);
bool KCategorizedView_ViewportEvent(KCategorizedView* self, QEvent* event);
void KCategorizedView_OnViewportEvent(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperViewportEvent(KCategorizedView* self, QEvent* event);
void KCategorizedView_MouseDoubleClickEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_OnMouseDoubleClickEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperMouseDoubleClickEvent(KCategorizedView* self, QMouseEvent* event);
void KCategorizedView_FocusInEvent(KCategorizedView* self, QFocusEvent* event);
void KCategorizedView_OnFocusInEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperFocusInEvent(KCategorizedView* self, QFocusEvent* event);
void KCategorizedView_FocusOutEvent(KCategorizedView* self, QFocusEvent* event);
void KCategorizedView_OnFocusOutEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperFocusOutEvent(KCategorizedView* self, QFocusEvent* event);
void KCategorizedView_KeyPressEvent(KCategorizedView* self, QKeyEvent* event);
void KCategorizedView_OnKeyPressEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperKeyPressEvent(KCategorizedView* self, QKeyEvent* event);
void KCategorizedView_InputMethodEvent(KCategorizedView* self, QInputMethodEvent* event);
void KCategorizedView_OnInputMethodEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperInputMethodEvent(KCategorizedView* self, QInputMethodEvent* event);
bool KCategorizedView_EventFilter(KCategorizedView* self, QObject* object, QEvent* event);
void KCategorizedView_OnEventFilter(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperEventFilter(KCategorizedView* self, QObject* object, QEvent* event);
QSize* KCategorizedView_MinimumSizeHint(const KCategorizedView* self);
void KCategorizedView_OnMinimumSizeHint(const KCategorizedView* self, intptr_t slot);
QSize* KCategorizedView_SuperMinimumSizeHint(const KCategorizedView* self);
QSize* KCategorizedView_SizeHint(const KCategorizedView* self);
void KCategorizedView_OnSizeHint(const KCategorizedView* self, intptr_t slot);
QSize* KCategorizedView_SuperSizeHint(const KCategorizedView* self);
void KCategorizedView_SetupViewport(KCategorizedView* self, QWidget* viewport);
void KCategorizedView_OnSetupViewport(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetupViewport(KCategorizedView* self, QWidget* viewport);
void KCategorizedView_ContextMenuEvent(KCategorizedView* self, QContextMenuEvent* param1);
void KCategorizedView_OnContextMenuEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperContextMenuEvent(KCategorizedView* self, QContextMenuEvent* param1);
void KCategorizedView_ChangeEvent(KCategorizedView* self, QEvent* param1);
void KCategorizedView_OnChangeEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperChangeEvent(KCategorizedView* self, QEvent* param1);
void KCategorizedView_InitStyleOption(const KCategorizedView* self, QStyleOptionFrame* option);
void KCategorizedView_OnInitStyleOption(const KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperInitStyleOption(const KCategorizedView* self, QStyleOptionFrame* option);
int KCategorizedView_DevType(const KCategorizedView* self);
void KCategorizedView_OnDevType(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperDevType(const KCategorizedView* self);
void KCategorizedView_SetVisible(KCategorizedView* self, bool visible);
void KCategorizedView_OnSetVisible(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetVisible(KCategorizedView* self, bool visible);
int KCategorizedView_HeightForWidth(const KCategorizedView* self, int param1);
void KCategorizedView_OnHeightForWidth(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperHeightForWidth(const KCategorizedView* self, int param1);
bool KCategorizedView_HasHeightForWidth(const KCategorizedView* self);
void KCategorizedView_OnHasHeightForWidth(const KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperHasHeightForWidth(const KCategorizedView* self);
QPaintEngine* KCategorizedView_PaintEngine(const KCategorizedView* self);
void KCategorizedView_OnPaintEngine(const KCategorizedView* self, intptr_t slot);
QPaintEngine* KCategorizedView_SuperPaintEngine(const KCategorizedView* self);
void KCategorizedView_KeyReleaseEvent(KCategorizedView* self, QKeyEvent* event);
void KCategorizedView_OnKeyReleaseEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperKeyReleaseEvent(KCategorizedView* self, QKeyEvent* event);
void KCategorizedView_EnterEvent(KCategorizedView* self, QEnterEvent* event);
void KCategorizedView_OnEnterEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperEnterEvent(KCategorizedView* self, QEnterEvent* event);
void KCategorizedView_MoveEvent(KCategorizedView* self, QMoveEvent* event);
void KCategorizedView_OnMoveEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperMoveEvent(KCategorizedView* self, QMoveEvent* event);
void KCategorizedView_CloseEvent(KCategorizedView* self, QCloseEvent* event);
void KCategorizedView_OnCloseEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperCloseEvent(KCategorizedView* self, QCloseEvent* event);
void KCategorizedView_TabletEvent(KCategorizedView* self, QTabletEvent* event);
void KCategorizedView_OnTabletEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperTabletEvent(KCategorizedView* self, QTabletEvent* event);
void KCategorizedView_ActionEvent(KCategorizedView* self, QActionEvent* event);
void KCategorizedView_OnActionEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperActionEvent(KCategorizedView* self, QActionEvent* event);
void KCategorizedView_ShowEvent(KCategorizedView* self, QShowEvent* event);
void KCategorizedView_OnShowEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperShowEvent(KCategorizedView* self, QShowEvent* event);
void KCategorizedView_HideEvent(KCategorizedView* self, QHideEvent* event);
void KCategorizedView_OnHideEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperHideEvent(KCategorizedView* self, QHideEvent* event);
bool KCategorizedView_NativeEvent(KCategorizedView* self, const libqt_string eventType, void* message, intptr_t* result);
void KCategorizedView_OnNativeEvent(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperNativeEvent(KCategorizedView* self, const libqt_string eventType, void* message, intptr_t* result);
int KCategorizedView_Metric(const KCategorizedView* self, int param1);
void KCategorizedView_OnMetric(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperMetric(const KCategorizedView* self, int param1);
void KCategorizedView_InitPainter(const KCategorizedView* self, QPainter* painter);
void KCategorizedView_OnInitPainter(const KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperInitPainter(const KCategorizedView* self, QPainter* painter);
QPaintDevice* KCategorizedView_Redirected(const KCategorizedView* self, QPoint* offset);
void KCategorizedView_OnRedirected(const KCategorizedView* self, intptr_t slot);
QPaintDevice* KCategorizedView_SuperRedirected(const KCategorizedView* self, QPoint* offset);
QPainter* KCategorizedView_SharedPainter(const KCategorizedView* self);
void KCategorizedView_OnSharedPainter(const KCategorizedView* self, intptr_t slot);
QPainter* KCategorizedView_SuperSharedPainter(const KCategorizedView* self);
void KCategorizedView_ChildEvent(KCategorizedView* self, QChildEvent* event);
void KCategorizedView_OnChildEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperChildEvent(KCategorizedView* self, QChildEvent* event);
void KCategorizedView_CustomEvent(KCategorizedView* self, QEvent* event);
void KCategorizedView_OnCustomEvent(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperCustomEvent(KCategorizedView* self, QEvent* event);
void KCategorizedView_ConnectNotify(KCategorizedView* self, const QMetaMethod* signal);
void KCategorizedView_OnConnectNotify(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperConnectNotify(KCategorizedView* self, const QMetaMethod* signal);
void KCategorizedView_DisconnectNotify(KCategorizedView* self, const QMetaMethod* signal);
void KCategorizedView_OnDisconnectNotify(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDisconnectNotify(KCategorizedView* self, const QMetaMethod* signal);
void KCategorizedView_ResizeContents(KCategorizedView* self, int width, int height);
void KCategorizedView_OnResizeContents(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperResizeContents(KCategorizedView* self, int width, int height);
QSize* KCategorizedView_ContentsSize(const KCategorizedView* self);
void KCategorizedView_OnContentsSize(const KCategorizedView* self, intptr_t slot);
QSize* KCategorizedView_SuperContentsSize(const KCategorizedView* self);
QRect* KCategorizedView_RectForIndex(const KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_OnRectForIndex(const KCategorizedView* self, intptr_t slot);
QRect* KCategorizedView_SuperRectForIndex(const KCategorizedView* self, const QModelIndex* index);
void KCategorizedView_SetPositionForIndex(KCategorizedView* self, const QPoint* position, const QModelIndex* index);
void KCategorizedView_OnSetPositionForIndex(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetPositionForIndex(KCategorizedView* self, const QPoint* position, const QModelIndex* index);
int KCategorizedView_State(const KCategorizedView* self);
void KCategorizedView_OnState(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperState(const KCategorizedView* self);
void KCategorizedView_SetState(KCategorizedView* self, int state);
void KCategorizedView_OnSetState(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetState(KCategorizedView* self, int state);
void KCategorizedView_ScheduleDelayedItemsLayout(KCategorizedView* self);
void KCategorizedView_OnScheduleDelayedItemsLayout(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperScheduleDelayedItemsLayout(KCategorizedView* self);
void KCategorizedView_ExecuteDelayedItemsLayout(KCategorizedView* self);
void KCategorizedView_OnExecuteDelayedItemsLayout(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperExecuteDelayedItemsLayout(KCategorizedView* self);
void KCategorizedView_SetDirtyRegion(KCategorizedView* self, const QRegion* region);
void KCategorizedView_OnSetDirtyRegion(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetDirtyRegion(KCategorizedView* self, const QRegion* region);
void KCategorizedView_ScrollDirtyRegion(KCategorizedView* self, int dx, int dy);
void KCategorizedView_OnScrollDirtyRegion(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperScrollDirtyRegion(KCategorizedView* self, int dx, int dy);
QPoint* KCategorizedView_DirtyRegionOffset(const KCategorizedView* self);
void KCategorizedView_OnDirtyRegionOffset(const KCategorizedView* self, intptr_t slot);
QPoint* KCategorizedView_SuperDirtyRegionOffset(const KCategorizedView* self);
void KCategorizedView_StartAutoScroll(KCategorizedView* self);
void KCategorizedView_OnStartAutoScroll(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperStartAutoScroll(KCategorizedView* self);
void KCategorizedView_StopAutoScroll(KCategorizedView* self);
void KCategorizedView_OnStopAutoScroll(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperStopAutoScroll(KCategorizedView* self);
void KCategorizedView_DoAutoScroll(KCategorizedView* self);
void KCategorizedView_OnDoAutoScroll(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDoAutoScroll(KCategorizedView* self);
int KCategorizedView_DropIndicatorPosition(const KCategorizedView* self);
void KCategorizedView_OnDropIndicatorPosition(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperDropIndicatorPosition(const KCategorizedView* self);
void KCategorizedView_SetViewportMargins(KCategorizedView* self, int left, int top, int right, int bottom);
void KCategorizedView_OnSetViewportMargins(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperSetViewportMargins(KCategorizedView* self, int left, int top, int right, int bottom);
QMargins* KCategorizedView_ViewportMargins(const KCategorizedView* self);
void KCategorizedView_OnViewportMargins(const KCategorizedView* self, intptr_t slot);
QMargins* KCategorizedView_SuperViewportMargins(const KCategorizedView* self);
void KCategorizedView_DrawFrame(KCategorizedView* self, QPainter* param1);
void KCategorizedView_OnDrawFrame(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDrawFrame(KCategorizedView* self, QPainter* param1);
void KCategorizedView_UpdateMicroFocus(KCategorizedView* self);
void KCategorizedView_OnUpdateMicroFocus(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperUpdateMicroFocus(KCategorizedView* self);
void KCategorizedView_Create(KCategorizedView* self);
void KCategorizedView_OnCreate(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperCreate(KCategorizedView* self);
void KCategorizedView_Destroy(KCategorizedView* self);
void KCategorizedView_OnDestroy(KCategorizedView* self, intptr_t slot);
void KCategorizedView_SuperDestroy(KCategorizedView* self);
bool KCategorizedView_FocusNextChild(KCategorizedView* self);
void KCategorizedView_OnFocusNextChild(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperFocusNextChild(KCategorizedView* self);
bool KCategorizedView_FocusPreviousChild(KCategorizedView* self);
void KCategorizedView_OnFocusPreviousChild(KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperFocusPreviousChild(KCategorizedView* self);
QObject* KCategorizedView_Sender(const KCategorizedView* self);
void KCategorizedView_OnSender(const KCategorizedView* self, intptr_t slot);
QObject* KCategorizedView_SuperSender(const KCategorizedView* self);
int KCategorizedView_SenderSignalIndex(const KCategorizedView* self);
void KCategorizedView_OnSenderSignalIndex(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperSenderSignalIndex(const KCategorizedView* self);
int KCategorizedView_Receivers(const KCategorizedView* self, const char* signal);
void KCategorizedView_OnReceivers(const KCategorizedView* self, intptr_t slot);
int KCategorizedView_SuperReceivers(const KCategorizedView* self, const char* signal);
bool KCategorizedView_IsSignalConnected(const KCategorizedView* self, const QMetaMethod* signal);
void KCategorizedView_OnIsSignalConnected(const KCategorizedView* self, intptr_t slot);
bool KCategorizedView_SuperIsSignalConnected(const KCategorizedView* self, const QMetaMethod* signal);
double KCategorizedView_GetDecodedMetricF(const KCategorizedView* self, int metricA, int metricB);
void KCategorizedView_OnGetDecodedMetricF(const KCategorizedView* self, intptr_t slot);
double KCategorizedView_SuperGetDecodedMetricF(const KCategorizedView* self, int metricA, int metricB);
void KCategorizedView_Delete(KCategorizedView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
