#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMALECTECONFIGDIALOG_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMALECTECONFIGDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammalecteConfigDialog)
typedef TextGrammarCheck::GrammalecteConfigDialog TextGrammarCheck__GrammalecteConfigDialog;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextGrammarCheck__GrammalecteConfigDialog TextGrammarCheck__GrammalecteConfigDialog;
#endif

TextGrammarCheck__GrammalecteConfigDialog* TextGrammarCheck__GrammalecteConfigDialog_new(QWidget* parent);
TextGrammarCheck__GrammalecteConfigDialog* TextGrammarCheck__GrammalecteConfigDialog_new2();
TextGrammarCheck__GrammalecteConfigDialog* TextGrammarCheck__GrammalecteConfigDialog_new3(QWidget* parent, bool disableMessageBox);
QMetaObject* TextGrammarCheck__GrammalecteConfigDialog_MetaObject(const TextGrammarCheck__GrammalecteConfigDialog* self);
void* TextGrammarCheck__GrammalecteConfigDialog_Metacast(TextGrammarCheck__GrammalecteConfigDialog* self, const char* param1);
int TextGrammarCheck__GrammalecteConfigDialog_Metacall(TextGrammarCheck__GrammalecteConfigDialog* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammalecteConfigDialog_OnMetaObject(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QMetaObject* TextGrammarCheck__GrammalecteConfigDialog_SuperMetaObject(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnMetacast(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void* TextGrammarCheck__GrammalecteConfigDialog_SuperMetacast(TextGrammarCheck__GrammalecteConfigDialog* self, const char* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnMetacall(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperMetacall(TextGrammarCheck__GrammalecteConfigDialog* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammalecteConfigDialog_SetVisible(TextGrammarCheck__GrammalecteConfigDialog* self, bool visible);
void TextGrammarCheck__GrammalecteConfigDialog_OnSetVisible(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperSetVisible(TextGrammarCheck__GrammalecteConfigDialog* self, bool visible);
QSize* TextGrammarCheck__GrammalecteConfigDialog_SizeHint(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnSizeHint(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QSize* TextGrammarCheck__GrammalecteConfigDialog_SuperSizeHint(const TextGrammarCheck__GrammalecteConfigDialog* self);
QSize* TextGrammarCheck__GrammalecteConfigDialog_MinimumSizeHint(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnMinimumSizeHint(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QSize* TextGrammarCheck__GrammalecteConfigDialog_SuperMinimumSizeHint(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_Open(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnOpen(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperOpen(TextGrammarCheck__GrammalecteConfigDialog* self);
int TextGrammarCheck__GrammalecteConfigDialog_Exec(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnExec(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperExec(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_Done(TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnDone(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDone(TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
void TextGrammarCheck__GrammalecteConfigDialog_Accept(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnAccept(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperAccept(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_Reject(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnReject(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperReject(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_KeyPressEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QKeyEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnKeyPressEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperKeyPressEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QKeyEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_CloseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QCloseEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnCloseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperCloseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QCloseEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_ShowEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QShowEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnShowEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperShowEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QShowEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_ResizeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QResizeEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnResizeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperResizeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QResizeEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_ContextMenuEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QContextMenuEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnContextMenuEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperContextMenuEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QContextMenuEvent* param1);
bool TextGrammarCheck__GrammalecteConfigDialog_EventFilter(TextGrammarCheck__GrammalecteConfigDialog* self, QObject* param1, QEvent* param2);
void TextGrammarCheck__GrammalecteConfigDialog_OnEventFilter(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperEventFilter(TextGrammarCheck__GrammalecteConfigDialog* self, QObject* param1, QEvent* param2);
int TextGrammarCheck__GrammalecteConfigDialog_DevType(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnDevType(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperDevType(const TextGrammarCheck__GrammalecteConfigDialog* self);
int TextGrammarCheck__GrammalecteConfigDialog_HeightForWidth(const TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnHeightForWidth(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperHeightForWidth(const TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
bool TextGrammarCheck__GrammalecteConfigDialog_HasHeightForWidth(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnHasHeightForWidth(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperHasHeightForWidth(const TextGrammarCheck__GrammalecteConfigDialog* self);
QPaintEngine* TextGrammarCheck__GrammalecteConfigDialog_PaintEngine(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnPaintEngine(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QPaintEngine* TextGrammarCheck__GrammalecteConfigDialog_SuperPaintEngine(const TextGrammarCheck__GrammalecteConfigDialog* self);
bool TextGrammarCheck__GrammalecteConfigDialog_Event(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_MousePressEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnMousePressEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperMousePressEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_MouseReleaseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnMouseReleaseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperMouseReleaseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_MouseDoubleClickEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnMouseDoubleClickEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperMouseDoubleClickEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_MouseMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnMouseMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperMouseMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_WheelEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QWheelEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnWheelEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperWheelEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QWheelEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_KeyReleaseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QKeyEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnKeyReleaseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperKeyReleaseEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QKeyEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_FocusInEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnFocusInEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperFocusInEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_FocusOutEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnFocusOutEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperFocusOutEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_EnterEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEnterEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnEnterEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperEnterEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEnterEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_LeaveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnLeaveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperLeaveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_PaintEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QPaintEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnPaintEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperPaintEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QPaintEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_MoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMoveEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QMoveEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_TabletEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QTabletEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnTabletEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperTabletEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QTabletEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_ActionEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QActionEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnActionEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperActionEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QActionEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_DragEnterEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDragEnterEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnDragEnterEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDragEnterEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDragEnterEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_DragMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDragMoveEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnDragMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDragMoveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDragMoveEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_DragLeaveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDragLeaveEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnDragLeaveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDragLeaveEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDragLeaveEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_DropEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDropEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnDropEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDropEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QDropEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_HideEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QHideEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnHideEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperHideEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QHideEvent* event);
bool TextGrammarCheck__GrammalecteConfigDialog_NativeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammalecteConfigDialog_OnNativeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperNativeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammalecteConfigDialog_ChangeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnChangeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperChangeEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* param1);
int TextGrammarCheck__GrammalecteConfigDialog_Metric(const TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnMetric(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperMetric(const TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
void TextGrammarCheck__GrammalecteConfigDialog_InitPainter(const TextGrammarCheck__GrammalecteConfigDialog* self, QPainter* painter);
void TextGrammarCheck__GrammalecteConfigDialog_OnInitPainter(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperInitPainter(const TextGrammarCheck__GrammalecteConfigDialog* self, QPainter* painter);
QPaintDevice* TextGrammarCheck__GrammalecteConfigDialog_Redirected(const TextGrammarCheck__GrammalecteConfigDialog* self, QPoint* offset);
void TextGrammarCheck__GrammalecteConfigDialog_OnRedirected(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QPaintDevice* TextGrammarCheck__GrammalecteConfigDialog_SuperRedirected(const TextGrammarCheck__GrammalecteConfigDialog* self, QPoint* offset);
QPainter* TextGrammarCheck__GrammalecteConfigDialog_SharedPainter(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnSharedPainter(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QPainter* TextGrammarCheck__GrammalecteConfigDialog_SuperSharedPainter(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_InputMethodEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QInputMethodEvent* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnInputMethodEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperInputMethodEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QInputMethodEvent* param1);
QVariant* TextGrammarCheck__GrammalecteConfigDialog_InputMethodQuery(const TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnInputMethodQuery(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QVariant* TextGrammarCheck__GrammalecteConfigDialog_SuperInputMethodQuery(const TextGrammarCheck__GrammalecteConfigDialog* self, int param1);
bool TextGrammarCheck__GrammalecteConfigDialog_FocusNextPrevChild(TextGrammarCheck__GrammalecteConfigDialog* self, bool next);
void TextGrammarCheck__GrammalecteConfigDialog_OnFocusNextPrevChild(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperFocusNextPrevChild(TextGrammarCheck__GrammalecteConfigDialog* self, bool next);
void TextGrammarCheck__GrammalecteConfigDialog_TimerEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QTimerEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnTimerEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperTimerEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QTimerEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_ChildEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QChildEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnChildEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperChildEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QChildEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_CustomEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_OnCustomEvent(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperCustomEvent(TextGrammarCheck__GrammalecteConfigDialog* self, QEvent* event);
void TextGrammarCheck__GrammalecteConfigDialog_ConnectNotify(TextGrammarCheck__GrammalecteConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteConfigDialog_OnConnectNotify(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperConnectNotify(TextGrammarCheck__GrammalecteConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteConfigDialog_DisconnectNotify(TextGrammarCheck__GrammalecteConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteConfigDialog_OnDisconnectNotify(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDisconnectNotify(TextGrammarCheck__GrammalecteConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteConfigDialog_AdjustPosition(TextGrammarCheck__GrammalecteConfigDialog* self, QWidget* param1);
void TextGrammarCheck__GrammalecteConfigDialog_OnAdjustPosition(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperAdjustPosition(TextGrammarCheck__GrammalecteConfigDialog* self, QWidget* param1);
void TextGrammarCheck__GrammalecteConfigDialog_UpdateMicroFocus(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnUpdateMicroFocus(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperUpdateMicroFocus(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_Create(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnCreate(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperCreate(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_Destroy(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnDestroy(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
void TextGrammarCheck__GrammalecteConfigDialog_SuperDestroy(TextGrammarCheck__GrammalecteConfigDialog* self);
bool TextGrammarCheck__GrammalecteConfigDialog_FocusNextChild(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnFocusNextChild(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperFocusNextChild(TextGrammarCheck__GrammalecteConfigDialog* self);
bool TextGrammarCheck__GrammalecteConfigDialog_FocusPreviousChild(TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnFocusPreviousChild(TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperFocusPreviousChild(TextGrammarCheck__GrammalecteConfigDialog* self);
QObject* TextGrammarCheck__GrammalecteConfigDialog_Sender(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnSender(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
QObject* TextGrammarCheck__GrammalecteConfigDialog_SuperSender(const TextGrammarCheck__GrammalecteConfigDialog* self);
int TextGrammarCheck__GrammalecteConfigDialog_SenderSignalIndex(const TextGrammarCheck__GrammalecteConfigDialog* self);
void TextGrammarCheck__GrammalecteConfigDialog_OnSenderSignalIndex(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperSenderSignalIndex(const TextGrammarCheck__GrammalecteConfigDialog* self);
int TextGrammarCheck__GrammalecteConfigDialog_Receivers(const TextGrammarCheck__GrammalecteConfigDialog* self, const char* signal);
void TextGrammarCheck__GrammalecteConfigDialog_OnReceivers(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
int TextGrammarCheck__GrammalecteConfigDialog_SuperReceivers(const TextGrammarCheck__GrammalecteConfigDialog* self, const char* signal);
bool TextGrammarCheck__GrammalecteConfigDialog_IsSignalConnected(const TextGrammarCheck__GrammalecteConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteConfigDialog_OnIsSignalConnected(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteConfigDialog_SuperIsSignalConnected(const TextGrammarCheck__GrammalecteConfigDialog* self, const QMetaMethod* signal);
double TextGrammarCheck__GrammalecteConfigDialog_GetDecodedMetricF(const TextGrammarCheck__GrammalecteConfigDialog* self, int metricA, int metricB);
void TextGrammarCheck__GrammalecteConfigDialog_OnGetDecodedMetricF(const TextGrammarCheck__GrammalecteConfigDialog* self, intptr_t slot);
double TextGrammarCheck__GrammalecteConfigDialog_SuperGetDecodedMetricF(const TextGrammarCheck__GrammalecteConfigDialog* self, int metricA, int metricB);
void TextGrammarCheck__GrammalecteConfigDialog_Delete(TextGrammarCheck__GrammalecteConfigDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
