#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMALECTERESULTWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMALECTERESULTWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammalecteResultWidget)
typedef TextGrammarCheck::GrammalecteResultWidget TextGrammarCheck__GrammalecteResultWidget;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarResultWidget)
typedef TextGrammarCheck::GrammarResultWidget TextGrammarCheck__GrammarResultWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextGrammarCheck__GrammalecteResultWidget TextGrammarCheck__GrammalecteResultWidget;
typedef struct TextGrammarCheck__GrammarResultWidget TextGrammarCheck__GrammarResultWidget;
#endif

TextGrammarCheck__GrammalecteResultWidget* TextGrammarCheck__GrammalecteResultWidget_new(QWidget* parent);
TextGrammarCheck__GrammalecteResultWidget* TextGrammarCheck__GrammalecteResultWidget_new2();
QMetaObject* TextGrammarCheck__GrammalecteResultWidget_MetaObject(const TextGrammarCheck__GrammalecteResultWidget* self);
void* TextGrammarCheck__GrammalecteResultWidget_Metacast(TextGrammarCheck__GrammalecteResultWidget* self, const char* param1);
int TextGrammarCheck__GrammalecteResultWidget_Metacall(TextGrammarCheck__GrammalecteResultWidget* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammalecteResultWidget_CheckGrammar(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnMetaObject(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QMetaObject* TextGrammarCheck__GrammalecteResultWidget_SuperMetaObject(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnMetacast(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void* TextGrammarCheck__GrammalecteResultWidget_SuperMetacast(TextGrammarCheck__GrammalecteResultWidget* self, const char* param1);
void TextGrammarCheck__GrammalecteResultWidget_OnMetacall(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammalecteResultWidget_SuperMetacall(TextGrammarCheck__GrammalecteResultWidget* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammalecteResultWidget_OnCheckGrammar(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperCheckGrammar(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_AddExtraWidget(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnAddExtraWidget(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperAddExtraWidget(TextGrammarCheck__GrammalecteResultWidget* self);
int TextGrammarCheck__GrammalecteResultWidget_DevType(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnDevType(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammalecteResultWidget_SuperDevType(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_SetVisible(TextGrammarCheck__GrammalecteResultWidget* self, bool visible);
void TextGrammarCheck__GrammalecteResultWidget_OnSetVisible(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperSetVisible(TextGrammarCheck__GrammalecteResultWidget* self, bool visible);
QSize* TextGrammarCheck__GrammalecteResultWidget_SizeHint(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnSizeHint(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QSize* TextGrammarCheck__GrammalecteResultWidget_SuperSizeHint(const TextGrammarCheck__GrammalecteResultWidget* self);
QSize* TextGrammarCheck__GrammalecteResultWidget_MinimumSizeHint(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnMinimumSizeHint(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QSize* TextGrammarCheck__GrammalecteResultWidget_SuperMinimumSizeHint(const TextGrammarCheck__GrammalecteResultWidget* self);
int TextGrammarCheck__GrammalecteResultWidget_HeightForWidth(const TextGrammarCheck__GrammalecteResultWidget* self, int param1);
void TextGrammarCheck__GrammalecteResultWidget_OnHeightForWidth(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammalecteResultWidget_SuperHeightForWidth(const TextGrammarCheck__GrammalecteResultWidget* self, int param1);
bool TextGrammarCheck__GrammalecteResultWidget_HasHeightForWidth(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnHasHeightForWidth(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperHasHeightForWidth(const TextGrammarCheck__GrammalecteResultWidget* self);
QPaintEngine* TextGrammarCheck__GrammalecteResultWidget_PaintEngine(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnPaintEngine(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QPaintEngine* TextGrammarCheck__GrammalecteResultWidget_SuperPaintEngine(const TextGrammarCheck__GrammalecteResultWidget* self);
bool TextGrammarCheck__GrammalecteResultWidget_Event(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_MousePressEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnMousePressEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperMousePressEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_MouseReleaseEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnMouseReleaseEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperMouseReleaseEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_MouseDoubleClickEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnMouseDoubleClickEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperMouseDoubleClickEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_MouseMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnMouseMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperMouseMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_WheelEvent(TextGrammarCheck__GrammalecteResultWidget* self, QWheelEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnWheelEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperWheelEvent(TextGrammarCheck__GrammalecteResultWidget* self, QWheelEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_KeyPressEvent(TextGrammarCheck__GrammalecteResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnKeyPressEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperKeyPressEvent(TextGrammarCheck__GrammalecteResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_KeyReleaseEvent(TextGrammarCheck__GrammalecteResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnKeyReleaseEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperKeyReleaseEvent(TextGrammarCheck__GrammalecteResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_FocusInEvent(TextGrammarCheck__GrammalecteResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnFocusInEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperFocusInEvent(TextGrammarCheck__GrammalecteResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_FocusOutEvent(TextGrammarCheck__GrammalecteResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnFocusOutEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperFocusOutEvent(TextGrammarCheck__GrammalecteResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_EnterEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEnterEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnEnterEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperEnterEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEnterEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_LeaveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnLeaveEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperLeaveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_PaintEvent(TextGrammarCheck__GrammalecteResultWidget* self, QPaintEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnPaintEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperPaintEvent(TextGrammarCheck__GrammalecteResultWidget* self, QPaintEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_MoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMoveEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QMoveEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_ResizeEvent(TextGrammarCheck__GrammalecteResultWidget* self, QResizeEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnResizeEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperResizeEvent(TextGrammarCheck__GrammalecteResultWidget* self, QResizeEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_CloseEvent(TextGrammarCheck__GrammalecteResultWidget* self, QCloseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnCloseEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperCloseEvent(TextGrammarCheck__GrammalecteResultWidget* self, QCloseEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_ContextMenuEvent(TextGrammarCheck__GrammalecteResultWidget* self, QContextMenuEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnContextMenuEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperContextMenuEvent(TextGrammarCheck__GrammalecteResultWidget* self, QContextMenuEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_TabletEvent(TextGrammarCheck__GrammalecteResultWidget* self, QTabletEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnTabletEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperTabletEvent(TextGrammarCheck__GrammalecteResultWidget* self, QTabletEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_ActionEvent(TextGrammarCheck__GrammalecteResultWidget* self, QActionEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnActionEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperActionEvent(TextGrammarCheck__GrammalecteResultWidget* self, QActionEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_DragEnterEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDragEnterEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnDragEnterEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperDragEnterEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDragEnterEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_DragMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDragMoveEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnDragMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperDragMoveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDragMoveEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_DragLeaveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDragLeaveEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnDragLeaveEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperDragLeaveEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDragLeaveEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_DropEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDropEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnDropEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperDropEvent(TextGrammarCheck__GrammalecteResultWidget* self, QDropEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_ShowEvent(TextGrammarCheck__GrammalecteResultWidget* self, QShowEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnShowEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperShowEvent(TextGrammarCheck__GrammalecteResultWidget* self, QShowEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_HideEvent(TextGrammarCheck__GrammalecteResultWidget* self, QHideEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnHideEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperHideEvent(TextGrammarCheck__GrammalecteResultWidget* self, QHideEvent* event);
bool TextGrammarCheck__GrammalecteResultWidget_NativeEvent(TextGrammarCheck__GrammalecteResultWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammalecteResultWidget_OnNativeEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperNativeEvent(TextGrammarCheck__GrammalecteResultWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammalecteResultWidget_ChangeEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* param1);
void TextGrammarCheck__GrammalecteResultWidget_OnChangeEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperChangeEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* param1);
int TextGrammarCheck__GrammalecteResultWidget_Metric(const TextGrammarCheck__GrammalecteResultWidget* self, int param1);
void TextGrammarCheck__GrammalecteResultWidget_OnMetric(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammalecteResultWidget_SuperMetric(const TextGrammarCheck__GrammalecteResultWidget* self, int param1);
void TextGrammarCheck__GrammalecteResultWidget_InitPainter(const TextGrammarCheck__GrammalecteResultWidget* self, QPainter* painter);
void TextGrammarCheck__GrammalecteResultWidget_OnInitPainter(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperInitPainter(const TextGrammarCheck__GrammalecteResultWidget* self, QPainter* painter);
QPaintDevice* TextGrammarCheck__GrammalecteResultWidget_Redirected(const TextGrammarCheck__GrammalecteResultWidget* self, QPoint* offset);
void TextGrammarCheck__GrammalecteResultWidget_OnRedirected(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QPaintDevice* TextGrammarCheck__GrammalecteResultWidget_SuperRedirected(const TextGrammarCheck__GrammalecteResultWidget* self, QPoint* offset);
QPainter* TextGrammarCheck__GrammalecteResultWidget_SharedPainter(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnSharedPainter(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QPainter* TextGrammarCheck__GrammalecteResultWidget_SuperSharedPainter(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_InputMethodEvent(TextGrammarCheck__GrammalecteResultWidget* self, QInputMethodEvent* param1);
void TextGrammarCheck__GrammalecteResultWidget_OnInputMethodEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperInputMethodEvent(TextGrammarCheck__GrammalecteResultWidget* self, QInputMethodEvent* param1);
QVariant* TextGrammarCheck__GrammalecteResultWidget_InputMethodQuery(const TextGrammarCheck__GrammalecteResultWidget* self, int param1);
void TextGrammarCheck__GrammalecteResultWidget_OnInputMethodQuery(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QVariant* TextGrammarCheck__GrammalecteResultWidget_SuperInputMethodQuery(const TextGrammarCheck__GrammalecteResultWidget* self, int param1);
bool TextGrammarCheck__GrammalecteResultWidget_FocusNextPrevChild(TextGrammarCheck__GrammalecteResultWidget* self, bool next);
void TextGrammarCheck__GrammalecteResultWidget_OnFocusNextPrevChild(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperFocusNextPrevChild(TextGrammarCheck__GrammalecteResultWidget* self, bool next);
bool TextGrammarCheck__GrammalecteResultWidget_EventFilter(TextGrammarCheck__GrammalecteResultWidget* self, QObject* watched, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnEventFilter(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperEventFilter(TextGrammarCheck__GrammalecteResultWidget* self, QObject* watched, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_TimerEvent(TextGrammarCheck__GrammalecteResultWidget* self, QTimerEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnTimerEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperTimerEvent(TextGrammarCheck__GrammalecteResultWidget* self, QTimerEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_ChildEvent(TextGrammarCheck__GrammalecteResultWidget* self, QChildEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnChildEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperChildEvent(TextGrammarCheck__GrammalecteResultWidget* self, QChildEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_CustomEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_OnCustomEvent(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperCustomEvent(TextGrammarCheck__GrammalecteResultWidget* self, QEvent* event);
void TextGrammarCheck__GrammalecteResultWidget_ConnectNotify(TextGrammarCheck__GrammalecteResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteResultWidget_OnConnectNotify(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperConnectNotify(TextGrammarCheck__GrammalecteResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteResultWidget_DisconnectNotify(TextGrammarCheck__GrammalecteResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteResultWidget_OnDisconnectNotify(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperDisconnectNotify(TextGrammarCheck__GrammalecteResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteResultWidget_UpdateMicroFocus(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnUpdateMicroFocus(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperUpdateMicroFocus(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_Create(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnCreate(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperCreate(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_Destroy(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnDestroy(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
void TextGrammarCheck__GrammalecteResultWidget_SuperDestroy(TextGrammarCheck__GrammalecteResultWidget* self);
bool TextGrammarCheck__GrammalecteResultWidget_FocusNextChild(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnFocusNextChild(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperFocusNextChild(TextGrammarCheck__GrammalecteResultWidget* self);
bool TextGrammarCheck__GrammalecteResultWidget_FocusPreviousChild(TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnFocusPreviousChild(TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperFocusPreviousChild(TextGrammarCheck__GrammalecteResultWidget* self);
QObject* TextGrammarCheck__GrammalecteResultWidget_Sender(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnSender(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
QObject* TextGrammarCheck__GrammalecteResultWidget_SuperSender(const TextGrammarCheck__GrammalecteResultWidget* self);
int TextGrammarCheck__GrammalecteResultWidget_SenderSignalIndex(const TextGrammarCheck__GrammalecteResultWidget* self);
void TextGrammarCheck__GrammalecteResultWidget_OnSenderSignalIndex(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammalecteResultWidget_SuperSenderSignalIndex(const TextGrammarCheck__GrammalecteResultWidget* self);
int TextGrammarCheck__GrammalecteResultWidget_Receivers(const TextGrammarCheck__GrammalecteResultWidget* self, const char* signal);
void TextGrammarCheck__GrammalecteResultWidget_OnReceivers(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
int TextGrammarCheck__GrammalecteResultWidget_SuperReceivers(const TextGrammarCheck__GrammalecteResultWidget* self, const char* signal);
bool TextGrammarCheck__GrammalecteResultWidget_IsSignalConnected(const TextGrammarCheck__GrammalecteResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteResultWidget_OnIsSignalConnected(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteResultWidget_SuperIsSignalConnected(const TextGrammarCheck__GrammalecteResultWidget* self, const QMetaMethod* signal);
double TextGrammarCheck__GrammalecteResultWidget_GetDecodedMetricF(const TextGrammarCheck__GrammalecteResultWidget* self, int metricA, int metricB);
void TextGrammarCheck__GrammalecteResultWidget_OnGetDecodedMetricF(const TextGrammarCheck__GrammalecteResultWidget* self, intptr_t slot);
double TextGrammarCheck__GrammalecteResultWidget_SuperGetDecodedMetricF(const TextGrammarCheck__GrammalecteResultWidget* self, int metricA, int metricB);
void TextGrammarCheck__GrammalecteResultWidget_Delete(TextGrammarCheck__GrammalecteResultWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
