#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMARRESULTTEXTEDIT_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMARRESULTTEXTEDIT_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarAction)
typedef TextGrammarCheck::GrammarAction TextGrammarCheck__GrammarAction;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarError)
typedef TextGrammarCheck::GrammarError TextGrammarCheck__GrammarError;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarResultTextEdit)
typedef TextGrammarCheck::GrammarResultTextEdit TextGrammarCheck__GrammarResultTextEdit;
#endif
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMargins QMargins;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTextCursor QTextCursor;
typedef struct QTextEdit QTextEdit;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextGrammarCheck__GrammarAction TextGrammarCheck__GrammarAction;
typedef struct TextGrammarCheck__GrammarError TextGrammarCheck__GrammarError;
typedef struct TextGrammarCheck__GrammarResultTextEdit TextGrammarCheck__GrammarResultTextEdit;
#endif

TextGrammarCheck__GrammarResultTextEdit* TextGrammarCheck__GrammarResultTextEdit_new(QWidget* parent);
TextGrammarCheck__GrammarResultTextEdit* TextGrammarCheck__GrammarResultTextEdit_new2();
QMetaObject* TextGrammarCheck__GrammarResultTextEdit_MetaObject(const TextGrammarCheck__GrammarResultTextEdit* self);
void* TextGrammarCheck__GrammarResultTextEdit_Metacast(TextGrammarCheck__GrammarResultTextEdit* self, const char* param1);
int TextGrammarCheck__GrammarResultTextEdit_Metacall(TextGrammarCheck__GrammarResultTextEdit* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammarResultTextEdit_ApplyGrammarResult(TextGrammarCheck__GrammarResultTextEdit* self, const libqt_list /* of TextGrammarCheck__GrammarError* */ infos);
void TextGrammarCheck__GrammarResultTextEdit_ContextMenuEvent(TextGrammarCheck__GrammarResultTextEdit* self, QContextMenuEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_PaintEvent(TextGrammarCheck__GrammarResultTextEdit* self, QPaintEvent* event);
bool TextGrammarCheck__GrammarResultTextEdit_Event(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* ev);
void TextGrammarCheck__GrammarResultTextEdit_ReplaceText(TextGrammarCheck__GrammarResultTextEdit* self, const TextGrammarCheck__GrammarAction* act);
void TextGrammarCheck__GrammarResultTextEdit_Connect_ReplaceText(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_CheckAgain(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_Connect_CheckAgain(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_CloseChecker(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_Connect_CloseChecker(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_Configure(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_Connect_Configure(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_OnMetaObject(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QMetaObject* TextGrammarCheck__GrammarResultTextEdit_SuperMetaObject(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnMetacast(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void* TextGrammarCheck__GrammarResultTextEdit_SuperMetacast(TextGrammarCheck__GrammarResultTextEdit* self, const char* param1);
void TextGrammarCheck__GrammarResultTextEdit_OnMetacall(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
int TextGrammarCheck__GrammarResultTextEdit_SuperMetacall(TextGrammarCheck__GrammarResultTextEdit* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammarResultTextEdit_OnContextMenuEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperContextMenuEvent(TextGrammarCheck__GrammarResultTextEdit* self, QContextMenuEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnPaintEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperPaintEvent(TextGrammarCheck__GrammarResultTextEdit* self, QPaintEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* ev);
QVariant* TextGrammarCheck__GrammarResultTextEdit_LoadResource(TextGrammarCheck__GrammarResultTextEdit* self, int typeVal, const QUrl* name);
void TextGrammarCheck__GrammarResultTextEdit_OnLoadResource(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QVariant* TextGrammarCheck__GrammarResultTextEdit_SuperLoadResource(TextGrammarCheck__GrammarResultTextEdit* self, int typeVal, const QUrl* name);
QVariant* TextGrammarCheck__GrammarResultTextEdit_InputMethodQuery(const TextGrammarCheck__GrammarResultTextEdit* self, int property);
void TextGrammarCheck__GrammarResultTextEdit_OnInputMethodQuery(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QVariant* TextGrammarCheck__GrammarResultTextEdit_SuperInputMethodQuery(const TextGrammarCheck__GrammarResultTextEdit* self, int property);
void TextGrammarCheck__GrammarResultTextEdit_TimerEvent(TextGrammarCheck__GrammarResultTextEdit* self, QTimerEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnTimerEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperTimerEvent(TextGrammarCheck__GrammarResultTextEdit* self, QTimerEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_KeyPressEvent(TextGrammarCheck__GrammarResultTextEdit* self, QKeyEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnKeyPressEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperKeyPressEvent(TextGrammarCheck__GrammarResultTextEdit* self, QKeyEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_KeyReleaseEvent(TextGrammarCheck__GrammarResultTextEdit* self, QKeyEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnKeyReleaseEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperKeyReleaseEvent(TextGrammarCheck__GrammarResultTextEdit* self, QKeyEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_ResizeEvent(TextGrammarCheck__GrammarResultTextEdit* self, QResizeEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnResizeEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperResizeEvent(TextGrammarCheck__GrammarResultTextEdit* self, QResizeEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_MousePressEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnMousePressEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperMousePressEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_MouseMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnMouseMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperMouseMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_MouseReleaseEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnMouseReleaseEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperMouseReleaseEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_MouseDoubleClickEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnMouseDoubleClickEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperMouseDoubleClickEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMouseEvent* e);
bool TextGrammarCheck__GrammarResultTextEdit_FocusNextPrevChild(TextGrammarCheck__GrammarResultTextEdit* self, bool next);
void TextGrammarCheck__GrammarResultTextEdit_OnFocusNextPrevChild(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperFocusNextPrevChild(TextGrammarCheck__GrammarResultTextEdit* self, bool next);
void TextGrammarCheck__GrammarResultTextEdit_DragEnterEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDragEnterEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnDragEnterEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDragEnterEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDragEnterEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_DragLeaveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDragLeaveEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnDragLeaveEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDragLeaveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDragLeaveEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_DragMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDragMoveEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnDragMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDragMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDragMoveEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_DropEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDropEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnDropEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDropEvent(TextGrammarCheck__GrammarResultTextEdit* self, QDropEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_FocusInEvent(TextGrammarCheck__GrammarResultTextEdit* self, QFocusEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnFocusInEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperFocusInEvent(TextGrammarCheck__GrammarResultTextEdit* self, QFocusEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_FocusOutEvent(TextGrammarCheck__GrammarResultTextEdit* self, QFocusEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnFocusOutEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperFocusOutEvent(TextGrammarCheck__GrammarResultTextEdit* self, QFocusEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_ShowEvent(TextGrammarCheck__GrammarResultTextEdit* self, QShowEvent* param1);
void TextGrammarCheck__GrammarResultTextEdit_OnShowEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperShowEvent(TextGrammarCheck__GrammarResultTextEdit* self, QShowEvent* param1);
void TextGrammarCheck__GrammarResultTextEdit_ChangeEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnChangeEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperChangeEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_WheelEvent(TextGrammarCheck__GrammarResultTextEdit* self, QWheelEvent* e);
void TextGrammarCheck__GrammarResultTextEdit_OnWheelEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperWheelEvent(TextGrammarCheck__GrammarResultTextEdit* self, QWheelEvent* e);
QMimeData* TextGrammarCheck__GrammarResultTextEdit_CreateMimeDataFromSelection(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnCreateMimeDataFromSelection(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QMimeData* TextGrammarCheck__GrammarResultTextEdit_SuperCreateMimeDataFromSelection(const TextGrammarCheck__GrammarResultTextEdit* self);
bool TextGrammarCheck__GrammarResultTextEdit_CanInsertFromMimeData(const TextGrammarCheck__GrammarResultTextEdit* self, const QMimeData* source);
void TextGrammarCheck__GrammarResultTextEdit_OnCanInsertFromMimeData(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperCanInsertFromMimeData(const TextGrammarCheck__GrammarResultTextEdit* self, const QMimeData* source);
void TextGrammarCheck__GrammarResultTextEdit_InsertFromMimeData(TextGrammarCheck__GrammarResultTextEdit* self, const QMimeData* source);
void TextGrammarCheck__GrammarResultTextEdit_OnInsertFromMimeData(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperInsertFromMimeData(TextGrammarCheck__GrammarResultTextEdit* self, const QMimeData* source);
void TextGrammarCheck__GrammarResultTextEdit_InputMethodEvent(TextGrammarCheck__GrammarResultTextEdit* self, QInputMethodEvent* param1);
void TextGrammarCheck__GrammarResultTextEdit_OnInputMethodEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperInputMethodEvent(TextGrammarCheck__GrammarResultTextEdit* self, QInputMethodEvent* param1);
void TextGrammarCheck__GrammarResultTextEdit_ScrollContentsBy(TextGrammarCheck__GrammarResultTextEdit* self, int dx, int dy);
void TextGrammarCheck__GrammarResultTextEdit_OnScrollContentsBy(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperScrollContentsBy(TextGrammarCheck__GrammarResultTextEdit* self, int dx, int dy);
void TextGrammarCheck__GrammarResultTextEdit_DoSetTextCursor(TextGrammarCheck__GrammarResultTextEdit* self, const QTextCursor* cursor);
void TextGrammarCheck__GrammarResultTextEdit_OnDoSetTextCursor(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDoSetTextCursor(TextGrammarCheck__GrammarResultTextEdit* self, const QTextCursor* cursor);
QSize* TextGrammarCheck__GrammarResultTextEdit_MinimumSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnMinimumSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QSize* TextGrammarCheck__GrammarResultTextEdit_SuperMinimumSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self);
QSize* TextGrammarCheck__GrammarResultTextEdit_SizeHint(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QSize* TextGrammarCheck__GrammarResultTextEdit_SuperSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_SetupViewport(TextGrammarCheck__GrammarResultTextEdit* self, QWidget* viewport);
void TextGrammarCheck__GrammarResultTextEdit_OnSetupViewport(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperSetupViewport(TextGrammarCheck__GrammarResultTextEdit* self, QWidget* viewport);
bool TextGrammarCheck__GrammarResultTextEdit_EventFilter(TextGrammarCheck__GrammarResultTextEdit* self, QObject* param1, QEvent* param2);
void TextGrammarCheck__GrammarResultTextEdit_OnEventFilter(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperEventFilter(TextGrammarCheck__GrammarResultTextEdit* self, QObject* param1, QEvent* param2);
bool TextGrammarCheck__GrammarResultTextEdit_ViewportEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* param1);
void TextGrammarCheck__GrammarResultTextEdit_OnViewportEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperViewportEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* param1);
QSize* TextGrammarCheck__GrammarResultTextEdit_ViewportSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnViewportSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QSize* TextGrammarCheck__GrammarResultTextEdit_SuperViewportSizeHint(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_InitStyleOption(const TextGrammarCheck__GrammarResultTextEdit* self, QStyleOptionFrame* option);
void TextGrammarCheck__GrammarResultTextEdit_OnInitStyleOption(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperInitStyleOption(const TextGrammarCheck__GrammarResultTextEdit* self, QStyleOptionFrame* option);
int TextGrammarCheck__GrammarResultTextEdit_DevType(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnDevType(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
int TextGrammarCheck__GrammarResultTextEdit_SuperDevType(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_SetVisible(TextGrammarCheck__GrammarResultTextEdit* self, bool visible);
void TextGrammarCheck__GrammarResultTextEdit_OnSetVisible(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperSetVisible(TextGrammarCheck__GrammarResultTextEdit* self, bool visible);
int TextGrammarCheck__GrammarResultTextEdit_HeightForWidth(const TextGrammarCheck__GrammarResultTextEdit* self, int param1);
void TextGrammarCheck__GrammarResultTextEdit_OnHeightForWidth(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
int TextGrammarCheck__GrammarResultTextEdit_SuperHeightForWidth(const TextGrammarCheck__GrammarResultTextEdit* self, int param1);
bool TextGrammarCheck__GrammarResultTextEdit_HasHeightForWidth(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnHasHeightForWidth(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperHasHeightForWidth(const TextGrammarCheck__GrammarResultTextEdit* self);
QPaintEngine* TextGrammarCheck__GrammarResultTextEdit_PaintEngine(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnPaintEngine(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QPaintEngine* TextGrammarCheck__GrammarResultTextEdit_SuperPaintEngine(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_EnterEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEnterEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnEnterEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperEnterEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEnterEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_LeaveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnLeaveEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperLeaveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_MoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMoveEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperMoveEvent(TextGrammarCheck__GrammarResultTextEdit* self, QMoveEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_CloseEvent(TextGrammarCheck__GrammarResultTextEdit* self, QCloseEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnCloseEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperCloseEvent(TextGrammarCheck__GrammarResultTextEdit* self, QCloseEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_TabletEvent(TextGrammarCheck__GrammarResultTextEdit* self, QTabletEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnTabletEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperTabletEvent(TextGrammarCheck__GrammarResultTextEdit* self, QTabletEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_ActionEvent(TextGrammarCheck__GrammarResultTextEdit* self, QActionEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnActionEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperActionEvent(TextGrammarCheck__GrammarResultTextEdit* self, QActionEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_HideEvent(TextGrammarCheck__GrammarResultTextEdit* self, QHideEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnHideEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperHideEvent(TextGrammarCheck__GrammarResultTextEdit* self, QHideEvent* event);
bool TextGrammarCheck__GrammarResultTextEdit_NativeEvent(TextGrammarCheck__GrammarResultTextEdit* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__GrammarResultTextEdit_OnNativeEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperNativeEvent(TextGrammarCheck__GrammarResultTextEdit* self, const libqt_string eventType, void* message, intptr_t* result);
int TextGrammarCheck__GrammarResultTextEdit_Metric(const TextGrammarCheck__GrammarResultTextEdit* self, int param1);
void TextGrammarCheck__GrammarResultTextEdit_OnMetric(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
int TextGrammarCheck__GrammarResultTextEdit_SuperMetric(const TextGrammarCheck__GrammarResultTextEdit* self, int param1);
void TextGrammarCheck__GrammarResultTextEdit_InitPainter(const TextGrammarCheck__GrammarResultTextEdit* self, QPainter* painter);
void TextGrammarCheck__GrammarResultTextEdit_OnInitPainter(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperInitPainter(const TextGrammarCheck__GrammarResultTextEdit* self, QPainter* painter);
QPaintDevice* TextGrammarCheck__GrammarResultTextEdit_Redirected(const TextGrammarCheck__GrammarResultTextEdit* self, QPoint* offset);
void TextGrammarCheck__GrammarResultTextEdit_OnRedirected(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QPaintDevice* TextGrammarCheck__GrammarResultTextEdit_SuperRedirected(const TextGrammarCheck__GrammarResultTextEdit* self, QPoint* offset);
QPainter* TextGrammarCheck__GrammarResultTextEdit_SharedPainter(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnSharedPainter(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QPainter* TextGrammarCheck__GrammarResultTextEdit_SuperSharedPainter(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_ChildEvent(TextGrammarCheck__GrammarResultTextEdit* self, QChildEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnChildEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperChildEvent(TextGrammarCheck__GrammarResultTextEdit* self, QChildEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_CustomEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_OnCustomEvent(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperCustomEvent(TextGrammarCheck__GrammarResultTextEdit* self, QEvent* event);
void TextGrammarCheck__GrammarResultTextEdit_ConnectNotify(TextGrammarCheck__GrammarResultTextEdit* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultTextEdit_OnConnectNotify(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperConnectNotify(TextGrammarCheck__GrammarResultTextEdit* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultTextEdit_DisconnectNotify(TextGrammarCheck__GrammarResultTextEdit* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultTextEdit_OnDisconnectNotify(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDisconnectNotify(TextGrammarCheck__GrammarResultTextEdit* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultTextEdit_ZoomInF(TextGrammarCheck__GrammarResultTextEdit* self, float range);
void TextGrammarCheck__GrammarResultTextEdit_OnZoomInF(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperZoomInF(TextGrammarCheck__GrammarResultTextEdit* self, float range);
void TextGrammarCheck__GrammarResultTextEdit_SetViewportMargins(TextGrammarCheck__GrammarResultTextEdit* self, int left, int top, int right, int bottom);
void TextGrammarCheck__GrammarResultTextEdit_OnSetViewportMargins(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperSetViewportMargins(TextGrammarCheck__GrammarResultTextEdit* self, int left, int top, int right, int bottom);
QMargins* TextGrammarCheck__GrammarResultTextEdit_ViewportMargins(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnViewportMargins(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QMargins* TextGrammarCheck__GrammarResultTextEdit_SuperViewportMargins(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_DrawFrame(TextGrammarCheck__GrammarResultTextEdit* self, QPainter* param1);
void TextGrammarCheck__GrammarResultTextEdit_OnDrawFrame(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDrawFrame(TextGrammarCheck__GrammarResultTextEdit* self, QPainter* param1);
void TextGrammarCheck__GrammarResultTextEdit_UpdateMicroFocus(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnUpdateMicroFocus(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperUpdateMicroFocus(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_Create(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnCreate(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperCreate(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_Destroy(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnDestroy(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
void TextGrammarCheck__GrammarResultTextEdit_SuperDestroy(TextGrammarCheck__GrammarResultTextEdit* self);
bool TextGrammarCheck__GrammarResultTextEdit_FocusNextChild(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnFocusNextChild(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperFocusNextChild(TextGrammarCheck__GrammarResultTextEdit* self);
bool TextGrammarCheck__GrammarResultTextEdit_FocusPreviousChild(TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnFocusPreviousChild(TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperFocusPreviousChild(TextGrammarCheck__GrammarResultTextEdit* self);
QObject* TextGrammarCheck__GrammarResultTextEdit_Sender(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnSender(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
QObject* TextGrammarCheck__GrammarResultTextEdit_SuperSender(const TextGrammarCheck__GrammarResultTextEdit* self);
int TextGrammarCheck__GrammarResultTextEdit_SenderSignalIndex(const TextGrammarCheck__GrammarResultTextEdit* self);
void TextGrammarCheck__GrammarResultTextEdit_OnSenderSignalIndex(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
int TextGrammarCheck__GrammarResultTextEdit_SuperSenderSignalIndex(const TextGrammarCheck__GrammarResultTextEdit* self);
int TextGrammarCheck__GrammarResultTextEdit_Receivers(const TextGrammarCheck__GrammarResultTextEdit* self, const char* signal);
void TextGrammarCheck__GrammarResultTextEdit_OnReceivers(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
int TextGrammarCheck__GrammarResultTextEdit_SuperReceivers(const TextGrammarCheck__GrammarResultTextEdit* self, const char* signal);
bool TextGrammarCheck__GrammarResultTextEdit_IsSignalConnected(const TextGrammarCheck__GrammarResultTextEdit* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammarResultTextEdit_OnIsSignalConnected(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
bool TextGrammarCheck__GrammarResultTextEdit_SuperIsSignalConnected(const TextGrammarCheck__GrammarResultTextEdit* self, const QMetaMethod* signal);
double TextGrammarCheck__GrammarResultTextEdit_GetDecodedMetricF(const TextGrammarCheck__GrammarResultTextEdit* self, int metricA, int metricB);
void TextGrammarCheck__GrammarResultTextEdit_OnGetDecodedMetricF(const TextGrammarCheck__GrammarResultTextEdit* self, intptr_t slot);
double TextGrammarCheck__GrammarResultTextEdit_SuperGetDecodedMetricF(const TextGrammarCheck__GrammarResultTextEdit* self, int metricA, int metricB);
void TextGrammarCheck__GrammarResultTextEdit_Delete(TextGrammarCheck__GrammarResultTextEdit* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
