#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMALECTEGENERATECONFIGOPTIONJOB_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBGRAMMALECTEGENERATECONFIGOPTIONJOB_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammalecteGenerateConfigOptionJob)
typedef TextGrammarCheck::GrammalecteGenerateConfigOptionJob TextGrammarCheck__GrammalecteGenerateConfigOptionJob;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option)
typedef TextGrammarCheck::GrammalecteGenerateConfigOptionJob::Option TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option;
#endif
#else
typedef struct QChildEvent QChildEvent;
typedef struct QEvent QEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QTimerEvent QTimerEvent;
typedef struct TextGrammarCheck__GrammalecteGenerateConfigOptionJob TextGrammarCheck__GrammalecteGenerateConfigOptionJob;
typedef struct TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option;
#endif

TextGrammarCheck__GrammalecteGenerateConfigOptionJob* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_new();
TextGrammarCheck__GrammalecteGenerateConfigOptionJob* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_new2(QObject* parent);
QMetaObject* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_MetaObject(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Metacast(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const char* param1);
int TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Metacall(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, int param1, int param2, void** param3);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Start(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_CanStart(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
libqt_string TextGrammarCheck__GrammalecteGenerateConfigOptionJob_PythonPath(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SetPythonPath(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const libqt_string pythonPath);
libqt_string TextGrammarCheck__GrammalecteGenerateConfigOptionJob_GrammarlecteCliPath(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SetGrammarlecteCliPath(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const libqt_string grammarlecteCliPath);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Error(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Connect_Error(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Finished(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const libqt_list /* of TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* */ result);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Connect_Finished(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnMetaObject(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
QMetaObject* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperMetaObject(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnMetacast(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperMetacast(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const char* param1);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnMetacall(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
int TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperMetacall(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, int param1, int param2, void** param3);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Event(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QEvent* event);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_EventFilter(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QObject* watched, QEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnEventFilter(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperEventFilter(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QObject* watched, QEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_TimerEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QTimerEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnTimerEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperTimerEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QTimerEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_ChildEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QChildEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnChildEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperChildEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QChildEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_CustomEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnCustomEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperCustomEvent(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, QEvent* event);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_ConnectNotify(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnConnectNotify(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperConnectNotify(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_DisconnectNotify(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnDisconnectNotify(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperDisconnectNotify(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const QMetaMethod* signal);
QObject* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Sender(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnSender(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
QObject* TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperSender(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
int TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SenderSignalIndex(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnSenderSignalIndex(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
int TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperSenderSignalIndex(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);
int TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Receivers(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const char* signal);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnReceivers(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
int TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperReceivers(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const char* signal);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_IsSignalConnected(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_OnIsSignalConnected(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, intptr_t slot);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob_SuperIsSignalConnected(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self, const QMetaMethod* signal);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob_Delete(TextGrammarCheck__GrammalecteGenerateConfigOptionJob* self);

TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_new(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* param1);
TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_new2();
libqt_string TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_OptionName(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_SetOptionName(TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self, libqt_string optionName);
libqt_string TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_Description(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_SetDescription(TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self, libqt_string description);
bool TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_DefaultValue(const TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_SetDefaultValue(TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self, bool defaultValue);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_OperatorAssign(TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self, const TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* param1);
void TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option_Delete(TextGrammarCheck__GrammalecteGenerateConfigOptionJob__Option* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
