#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBLANGUAGETOOLRESULTWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBLANGUAGETOOLRESULTWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__GrammarResultWidget)
typedef TextGrammarCheck::GrammarResultWidget TextGrammarCheck__GrammarResultWidget;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__LanguageToolResultWidget)
typedef TextGrammarCheck::LanguageToolResultWidget TextGrammarCheck__LanguageToolResultWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextGrammarCheck__GrammarResultWidget TextGrammarCheck__GrammarResultWidget;
typedef struct TextGrammarCheck__LanguageToolResultWidget TextGrammarCheck__LanguageToolResultWidget;
#endif

TextGrammarCheck__LanguageToolResultWidget* TextGrammarCheck__LanguageToolResultWidget_new(QWidget* parent);
TextGrammarCheck__LanguageToolResultWidget* TextGrammarCheck__LanguageToolResultWidget_new2();
QMetaObject* TextGrammarCheck__LanguageToolResultWidget_MetaObject(const TextGrammarCheck__LanguageToolResultWidget* self);
void* TextGrammarCheck__LanguageToolResultWidget_Metacast(TextGrammarCheck__LanguageToolResultWidget* self, const char* param1);
int TextGrammarCheck__LanguageToolResultWidget_Metacall(TextGrammarCheck__LanguageToolResultWidget* self, int param1, int param2, void** param3);
void TextGrammarCheck__LanguageToolResultWidget_CheckGrammar(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_AddExtraWidget(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnMetaObject(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QMetaObject* TextGrammarCheck__LanguageToolResultWidget_SuperMetaObject(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnMetacast(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void* TextGrammarCheck__LanguageToolResultWidget_SuperMetacast(TextGrammarCheck__LanguageToolResultWidget* self, const char* param1);
void TextGrammarCheck__LanguageToolResultWidget_OnMetacall(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
int TextGrammarCheck__LanguageToolResultWidget_SuperMetacall(TextGrammarCheck__LanguageToolResultWidget* self, int param1, int param2, void** param3);
void TextGrammarCheck__LanguageToolResultWidget_OnCheckGrammar(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperCheckGrammar(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnAddExtraWidget(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperAddExtraWidget(TextGrammarCheck__LanguageToolResultWidget* self);
int TextGrammarCheck__LanguageToolResultWidget_DevType(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnDevType(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
int TextGrammarCheck__LanguageToolResultWidget_SuperDevType(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_SetVisible(TextGrammarCheck__LanguageToolResultWidget* self, bool visible);
void TextGrammarCheck__LanguageToolResultWidget_OnSetVisible(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperSetVisible(TextGrammarCheck__LanguageToolResultWidget* self, bool visible);
QSize* TextGrammarCheck__LanguageToolResultWidget_SizeHint(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnSizeHint(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QSize* TextGrammarCheck__LanguageToolResultWidget_SuperSizeHint(const TextGrammarCheck__LanguageToolResultWidget* self);
QSize* TextGrammarCheck__LanguageToolResultWidget_MinimumSizeHint(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnMinimumSizeHint(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QSize* TextGrammarCheck__LanguageToolResultWidget_SuperMinimumSizeHint(const TextGrammarCheck__LanguageToolResultWidget* self);
int TextGrammarCheck__LanguageToolResultWidget_HeightForWidth(const TextGrammarCheck__LanguageToolResultWidget* self, int param1);
void TextGrammarCheck__LanguageToolResultWidget_OnHeightForWidth(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
int TextGrammarCheck__LanguageToolResultWidget_SuperHeightForWidth(const TextGrammarCheck__LanguageToolResultWidget* self, int param1);
bool TextGrammarCheck__LanguageToolResultWidget_HasHeightForWidth(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnHasHeightForWidth(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperHasHeightForWidth(const TextGrammarCheck__LanguageToolResultWidget* self);
QPaintEngine* TextGrammarCheck__LanguageToolResultWidget_PaintEngine(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnPaintEngine(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QPaintEngine* TextGrammarCheck__LanguageToolResultWidget_SuperPaintEngine(const TextGrammarCheck__LanguageToolResultWidget* self);
bool TextGrammarCheck__LanguageToolResultWidget_Event(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_MousePressEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnMousePressEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperMousePressEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_MouseReleaseEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnMouseReleaseEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperMouseReleaseEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_MouseDoubleClickEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnMouseDoubleClickEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperMouseDoubleClickEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_MouseMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnMouseMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperMouseMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_WheelEvent(TextGrammarCheck__LanguageToolResultWidget* self, QWheelEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnWheelEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperWheelEvent(TextGrammarCheck__LanguageToolResultWidget* self, QWheelEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_KeyPressEvent(TextGrammarCheck__LanguageToolResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnKeyPressEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperKeyPressEvent(TextGrammarCheck__LanguageToolResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_KeyReleaseEvent(TextGrammarCheck__LanguageToolResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnKeyReleaseEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperKeyReleaseEvent(TextGrammarCheck__LanguageToolResultWidget* self, QKeyEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_FocusInEvent(TextGrammarCheck__LanguageToolResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnFocusInEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperFocusInEvent(TextGrammarCheck__LanguageToolResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_FocusOutEvent(TextGrammarCheck__LanguageToolResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnFocusOutEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperFocusOutEvent(TextGrammarCheck__LanguageToolResultWidget* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_EnterEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEnterEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnEnterEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperEnterEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEnterEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_LeaveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnLeaveEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperLeaveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_PaintEvent(TextGrammarCheck__LanguageToolResultWidget* self, QPaintEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnPaintEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperPaintEvent(TextGrammarCheck__LanguageToolResultWidget* self, QPaintEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_MoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMoveEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QMoveEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_ResizeEvent(TextGrammarCheck__LanguageToolResultWidget* self, QResizeEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnResizeEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperResizeEvent(TextGrammarCheck__LanguageToolResultWidget* self, QResizeEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_CloseEvent(TextGrammarCheck__LanguageToolResultWidget* self, QCloseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnCloseEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperCloseEvent(TextGrammarCheck__LanguageToolResultWidget* self, QCloseEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_ContextMenuEvent(TextGrammarCheck__LanguageToolResultWidget* self, QContextMenuEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnContextMenuEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperContextMenuEvent(TextGrammarCheck__LanguageToolResultWidget* self, QContextMenuEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_TabletEvent(TextGrammarCheck__LanguageToolResultWidget* self, QTabletEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnTabletEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperTabletEvent(TextGrammarCheck__LanguageToolResultWidget* self, QTabletEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_ActionEvent(TextGrammarCheck__LanguageToolResultWidget* self, QActionEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnActionEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperActionEvent(TextGrammarCheck__LanguageToolResultWidget* self, QActionEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_DragEnterEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDragEnterEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnDragEnterEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperDragEnterEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDragEnterEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_DragMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDragMoveEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnDragMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperDragMoveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDragMoveEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_DragLeaveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDragLeaveEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnDragLeaveEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperDragLeaveEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDragLeaveEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_DropEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDropEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnDropEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperDropEvent(TextGrammarCheck__LanguageToolResultWidget* self, QDropEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_ShowEvent(TextGrammarCheck__LanguageToolResultWidget* self, QShowEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnShowEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperShowEvent(TextGrammarCheck__LanguageToolResultWidget* self, QShowEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_HideEvent(TextGrammarCheck__LanguageToolResultWidget* self, QHideEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnHideEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperHideEvent(TextGrammarCheck__LanguageToolResultWidget* self, QHideEvent* event);
bool TextGrammarCheck__LanguageToolResultWidget_NativeEvent(TextGrammarCheck__LanguageToolResultWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__LanguageToolResultWidget_OnNativeEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperNativeEvent(TextGrammarCheck__LanguageToolResultWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__LanguageToolResultWidget_ChangeEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* param1);
void TextGrammarCheck__LanguageToolResultWidget_OnChangeEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperChangeEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* param1);
int TextGrammarCheck__LanguageToolResultWidget_Metric(const TextGrammarCheck__LanguageToolResultWidget* self, int param1);
void TextGrammarCheck__LanguageToolResultWidget_OnMetric(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
int TextGrammarCheck__LanguageToolResultWidget_SuperMetric(const TextGrammarCheck__LanguageToolResultWidget* self, int param1);
void TextGrammarCheck__LanguageToolResultWidget_InitPainter(const TextGrammarCheck__LanguageToolResultWidget* self, QPainter* painter);
void TextGrammarCheck__LanguageToolResultWidget_OnInitPainter(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperInitPainter(const TextGrammarCheck__LanguageToolResultWidget* self, QPainter* painter);
QPaintDevice* TextGrammarCheck__LanguageToolResultWidget_Redirected(const TextGrammarCheck__LanguageToolResultWidget* self, QPoint* offset);
void TextGrammarCheck__LanguageToolResultWidget_OnRedirected(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QPaintDevice* TextGrammarCheck__LanguageToolResultWidget_SuperRedirected(const TextGrammarCheck__LanguageToolResultWidget* self, QPoint* offset);
QPainter* TextGrammarCheck__LanguageToolResultWidget_SharedPainter(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnSharedPainter(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QPainter* TextGrammarCheck__LanguageToolResultWidget_SuperSharedPainter(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_InputMethodEvent(TextGrammarCheck__LanguageToolResultWidget* self, QInputMethodEvent* param1);
void TextGrammarCheck__LanguageToolResultWidget_OnInputMethodEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperInputMethodEvent(TextGrammarCheck__LanguageToolResultWidget* self, QInputMethodEvent* param1);
QVariant* TextGrammarCheck__LanguageToolResultWidget_InputMethodQuery(const TextGrammarCheck__LanguageToolResultWidget* self, int param1);
void TextGrammarCheck__LanguageToolResultWidget_OnInputMethodQuery(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QVariant* TextGrammarCheck__LanguageToolResultWidget_SuperInputMethodQuery(const TextGrammarCheck__LanguageToolResultWidget* self, int param1);
bool TextGrammarCheck__LanguageToolResultWidget_FocusNextPrevChild(TextGrammarCheck__LanguageToolResultWidget* self, bool next);
void TextGrammarCheck__LanguageToolResultWidget_OnFocusNextPrevChild(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperFocusNextPrevChild(TextGrammarCheck__LanguageToolResultWidget* self, bool next);
bool TextGrammarCheck__LanguageToolResultWidget_EventFilter(TextGrammarCheck__LanguageToolResultWidget* self, QObject* watched, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnEventFilter(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperEventFilter(TextGrammarCheck__LanguageToolResultWidget* self, QObject* watched, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_TimerEvent(TextGrammarCheck__LanguageToolResultWidget* self, QTimerEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnTimerEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperTimerEvent(TextGrammarCheck__LanguageToolResultWidget* self, QTimerEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_ChildEvent(TextGrammarCheck__LanguageToolResultWidget* self, QChildEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnChildEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperChildEvent(TextGrammarCheck__LanguageToolResultWidget* self, QChildEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_CustomEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_OnCustomEvent(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperCustomEvent(TextGrammarCheck__LanguageToolResultWidget* self, QEvent* event);
void TextGrammarCheck__LanguageToolResultWidget_ConnectNotify(TextGrammarCheck__LanguageToolResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolResultWidget_OnConnectNotify(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperConnectNotify(TextGrammarCheck__LanguageToolResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolResultWidget_DisconnectNotify(TextGrammarCheck__LanguageToolResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolResultWidget_OnDisconnectNotify(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperDisconnectNotify(TextGrammarCheck__LanguageToolResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolResultWidget_UpdateMicroFocus(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnUpdateMicroFocus(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperUpdateMicroFocus(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_Create(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnCreate(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperCreate(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_Destroy(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnDestroy(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
void TextGrammarCheck__LanguageToolResultWidget_SuperDestroy(TextGrammarCheck__LanguageToolResultWidget* self);
bool TextGrammarCheck__LanguageToolResultWidget_FocusNextChild(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnFocusNextChild(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperFocusNextChild(TextGrammarCheck__LanguageToolResultWidget* self);
bool TextGrammarCheck__LanguageToolResultWidget_FocusPreviousChild(TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnFocusPreviousChild(TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperFocusPreviousChild(TextGrammarCheck__LanguageToolResultWidget* self);
QObject* TextGrammarCheck__LanguageToolResultWidget_Sender(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnSender(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
QObject* TextGrammarCheck__LanguageToolResultWidget_SuperSender(const TextGrammarCheck__LanguageToolResultWidget* self);
int TextGrammarCheck__LanguageToolResultWidget_SenderSignalIndex(const TextGrammarCheck__LanguageToolResultWidget* self);
void TextGrammarCheck__LanguageToolResultWidget_OnSenderSignalIndex(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
int TextGrammarCheck__LanguageToolResultWidget_SuperSenderSignalIndex(const TextGrammarCheck__LanguageToolResultWidget* self);
int TextGrammarCheck__LanguageToolResultWidget_Receivers(const TextGrammarCheck__LanguageToolResultWidget* self, const char* signal);
void TextGrammarCheck__LanguageToolResultWidget_OnReceivers(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
int TextGrammarCheck__LanguageToolResultWidget_SuperReceivers(const TextGrammarCheck__LanguageToolResultWidget* self, const char* signal);
bool TextGrammarCheck__LanguageToolResultWidget_IsSignalConnected(const TextGrammarCheck__LanguageToolResultWidget* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolResultWidget_OnIsSignalConnected(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolResultWidget_SuperIsSignalConnected(const TextGrammarCheck__LanguageToolResultWidget* self, const QMetaMethod* signal);
double TextGrammarCheck__LanguageToolResultWidget_GetDecodedMetricF(const TextGrammarCheck__LanguageToolResultWidget* self, int metricA, int metricB);
void TextGrammarCheck__LanguageToolResultWidget_OnGetDecodedMetricF(const TextGrammarCheck__LanguageToolResultWidget* self, intptr_t slot);
double TextGrammarCheck__LanguageToolResultWidget_SuperGetDecodedMetricF(const TextGrammarCheck__LanguageToolResultWidget* self, int metricA, int metricB);
void TextGrammarCheck__LanguageToolResultWidget_Delete(TextGrammarCheck__LanguageToolResultWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
