#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBLANGUAGETOOLCONFIGDIALOG_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBLANGUAGETOOLCONFIGDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__LanguageToolConfigDialog)
typedef TextGrammarCheck::LanguageToolConfigDialog TextGrammarCheck__LanguageToolConfigDialog;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextGrammarCheck__LanguageToolConfigDialog TextGrammarCheck__LanguageToolConfigDialog;
#endif

TextGrammarCheck__LanguageToolConfigDialog* TextGrammarCheck__LanguageToolConfigDialog_new(QWidget* parent);
TextGrammarCheck__LanguageToolConfigDialog* TextGrammarCheck__LanguageToolConfigDialog_new2();
QMetaObject* TextGrammarCheck__LanguageToolConfigDialog_MetaObject(const TextGrammarCheck__LanguageToolConfigDialog* self);
void* TextGrammarCheck__LanguageToolConfigDialog_Metacast(TextGrammarCheck__LanguageToolConfigDialog* self, const char* param1);
int TextGrammarCheck__LanguageToolConfigDialog_Metacall(TextGrammarCheck__LanguageToolConfigDialog* self, int param1, int param2, void** param3);
void TextGrammarCheck__LanguageToolConfigDialog_OnMetaObject(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QMetaObject* TextGrammarCheck__LanguageToolConfigDialog_SuperMetaObject(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnMetacast(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void* TextGrammarCheck__LanguageToolConfigDialog_SuperMetacast(TextGrammarCheck__LanguageToolConfigDialog* self, const char* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnMetacall(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperMetacall(TextGrammarCheck__LanguageToolConfigDialog* self, int param1, int param2, void** param3);
void TextGrammarCheck__LanguageToolConfigDialog_SetVisible(TextGrammarCheck__LanguageToolConfigDialog* self, bool visible);
void TextGrammarCheck__LanguageToolConfigDialog_OnSetVisible(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperSetVisible(TextGrammarCheck__LanguageToolConfigDialog* self, bool visible);
QSize* TextGrammarCheck__LanguageToolConfigDialog_SizeHint(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnSizeHint(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QSize* TextGrammarCheck__LanguageToolConfigDialog_SuperSizeHint(const TextGrammarCheck__LanguageToolConfigDialog* self);
QSize* TextGrammarCheck__LanguageToolConfigDialog_MinimumSizeHint(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnMinimumSizeHint(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QSize* TextGrammarCheck__LanguageToolConfigDialog_SuperMinimumSizeHint(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_Open(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnOpen(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperOpen(TextGrammarCheck__LanguageToolConfigDialog* self);
int TextGrammarCheck__LanguageToolConfigDialog_Exec(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnExec(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperExec(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_Done(TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnDone(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDone(TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
void TextGrammarCheck__LanguageToolConfigDialog_Accept(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnAccept(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperAccept(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_Reject(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnReject(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperReject(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_KeyPressEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QKeyEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnKeyPressEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperKeyPressEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QKeyEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_CloseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QCloseEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnCloseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperCloseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QCloseEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_ShowEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QShowEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnShowEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperShowEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QShowEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_ResizeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QResizeEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnResizeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperResizeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QResizeEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_ContextMenuEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QContextMenuEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnContextMenuEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperContextMenuEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QContextMenuEvent* param1);
bool TextGrammarCheck__LanguageToolConfigDialog_EventFilter(TextGrammarCheck__LanguageToolConfigDialog* self, QObject* param1, QEvent* param2);
void TextGrammarCheck__LanguageToolConfigDialog_OnEventFilter(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperEventFilter(TextGrammarCheck__LanguageToolConfigDialog* self, QObject* param1, QEvent* param2);
int TextGrammarCheck__LanguageToolConfigDialog_DevType(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnDevType(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperDevType(const TextGrammarCheck__LanguageToolConfigDialog* self);
int TextGrammarCheck__LanguageToolConfigDialog_HeightForWidth(const TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnHeightForWidth(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperHeightForWidth(const TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
bool TextGrammarCheck__LanguageToolConfigDialog_HasHeightForWidth(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnHasHeightForWidth(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperHasHeightForWidth(const TextGrammarCheck__LanguageToolConfigDialog* self);
QPaintEngine* TextGrammarCheck__LanguageToolConfigDialog_PaintEngine(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnPaintEngine(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QPaintEngine* TextGrammarCheck__LanguageToolConfigDialog_SuperPaintEngine(const TextGrammarCheck__LanguageToolConfigDialog* self);
bool TextGrammarCheck__LanguageToolConfigDialog_Event(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_MousePressEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnMousePressEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperMousePressEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_MouseReleaseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnMouseReleaseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperMouseReleaseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_MouseDoubleClickEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnMouseDoubleClickEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperMouseDoubleClickEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_MouseMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnMouseMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperMouseMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMouseEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_WheelEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QWheelEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnWheelEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperWheelEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QWheelEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_KeyReleaseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QKeyEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnKeyReleaseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperKeyReleaseEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QKeyEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_FocusInEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnFocusInEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperFocusInEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_FocusOutEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnFocusOutEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperFocusOutEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QFocusEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_EnterEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEnterEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnEnterEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperEnterEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEnterEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_LeaveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnLeaveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperLeaveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_PaintEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QPaintEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnPaintEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperPaintEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QPaintEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_MoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMoveEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QMoveEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_TabletEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QTabletEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnTabletEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperTabletEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QTabletEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_ActionEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QActionEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnActionEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperActionEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QActionEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_DragEnterEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDragEnterEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnDragEnterEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDragEnterEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDragEnterEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_DragMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDragMoveEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnDragMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDragMoveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDragMoveEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_DragLeaveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDragLeaveEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnDragLeaveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDragLeaveEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDragLeaveEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_DropEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDropEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnDropEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDropEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QDropEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_HideEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QHideEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnHideEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperHideEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QHideEvent* event);
bool TextGrammarCheck__LanguageToolConfigDialog_NativeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__LanguageToolConfigDialog_OnNativeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperNativeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void TextGrammarCheck__LanguageToolConfigDialog_ChangeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnChangeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperChangeEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* param1);
int TextGrammarCheck__LanguageToolConfigDialog_Metric(const TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnMetric(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperMetric(const TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
void TextGrammarCheck__LanguageToolConfigDialog_InitPainter(const TextGrammarCheck__LanguageToolConfigDialog* self, QPainter* painter);
void TextGrammarCheck__LanguageToolConfigDialog_OnInitPainter(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperInitPainter(const TextGrammarCheck__LanguageToolConfigDialog* self, QPainter* painter);
QPaintDevice* TextGrammarCheck__LanguageToolConfigDialog_Redirected(const TextGrammarCheck__LanguageToolConfigDialog* self, QPoint* offset);
void TextGrammarCheck__LanguageToolConfigDialog_OnRedirected(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QPaintDevice* TextGrammarCheck__LanguageToolConfigDialog_SuperRedirected(const TextGrammarCheck__LanguageToolConfigDialog* self, QPoint* offset);
QPainter* TextGrammarCheck__LanguageToolConfigDialog_SharedPainter(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnSharedPainter(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QPainter* TextGrammarCheck__LanguageToolConfigDialog_SuperSharedPainter(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_InputMethodEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QInputMethodEvent* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnInputMethodEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperInputMethodEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QInputMethodEvent* param1);
QVariant* TextGrammarCheck__LanguageToolConfigDialog_InputMethodQuery(const TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnInputMethodQuery(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QVariant* TextGrammarCheck__LanguageToolConfigDialog_SuperInputMethodQuery(const TextGrammarCheck__LanguageToolConfigDialog* self, int param1);
bool TextGrammarCheck__LanguageToolConfigDialog_FocusNextPrevChild(TextGrammarCheck__LanguageToolConfigDialog* self, bool next);
void TextGrammarCheck__LanguageToolConfigDialog_OnFocusNextPrevChild(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperFocusNextPrevChild(TextGrammarCheck__LanguageToolConfigDialog* self, bool next);
void TextGrammarCheck__LanguageToolConfigDialog_TimerEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QTimerEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnTimerEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperTimerEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QTimerEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_ChildEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QChildEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnChildEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperChildEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QChildEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_CustomEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_OnCustomEvent(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperCustomEvent(TextGrammarCheck__LanguageToolConfigDialog* self, QEvent* event);
void TextGrammarCheck__LanguageToolConfigDialog_ConnectNotify(TextGrammarCheck__LanguageToolConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolConfigDialog_OnConnectNotify(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperConnectNotify(TextGrammarCheck__LanguageToolConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolConfigDialog_DisconnectNotify(TextGrammarCheck__LanguageToolConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolConfigDialog_OnDisconnectNotify(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDisconnectNotify(TextGrammarCheck__LanguageToolConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolConfigDialog_AdjustPosition(TextGrammarCheck__LanguageToolConfigDialog* self, QWidget* param1);
void TextGrammarCheck__LanguageToolConfigDialog_OnAdjustPosition(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperAdjustPosition(TextGrammarCheck__LanguageToolConfigDialog* self, QWidget* param1);
void TextGrammarCheck__LanguageToolConfigDialog_UpdateMicroFocus(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnUpdateMicroFocus(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperUpdateMicroFocus(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_Create(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnCreate(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperCreate(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_Destroy(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnDestroy(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
void TextGrammarCheck__LanguageToolConfigDialog_SuperDestroy(TextGrammarCheck__LanguageToolConfigDialog* self);
bool TextGrammarCheck__LanguageToolConfigDialog_FocusNextChild(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnFocusNextChild(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperFocusNextChild(TextGrammarCheck__LanguageToolConfigDialog* self);
bool TextGrammarCheck__LanguageToolConfigDialog_FocusPreviousChild(TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnFocusPreviousChild(TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperFocusPreviousChild(TextGrammarCheck__LanguageToolConfigDialog* self);
QObject* TextGrammarCheck__LanguageToolConfigDialog_Sender(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnSender(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
QObject* TextGrammarCheck__LanguageToolConfigDialog_SuperSender(const TextGrammarCheck__LanguageToolConfigDialog* self);
int TextGrammarCheck__LanguageToolConfigDialog_SenderSignalIndex(const TextGrammarCheck__LanguageToolConfigDialog* self);
void TextGrammarCheck__LanguageToolConfigDialog_OnSenderSignalIndex(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperSenderSignalIndex(const TextGrammarCheck__LanguageToolConfigDialog* self);
int TextGrammarCheck__LanguageToolConfigDialog_Receivers(const TextGrammarCheck__LanguageToolConfigDialog* self, const char* signal);
void TextGrammarCheck__LanguageToolConfigDialog_OnReceivers(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
int TextGrammarCheck__LanguageToolConfigDialog_SuperReceivers(const TextGrammarCheck__LanguageToolConfigDialog* self, const char* signal);
bool TextGrammarCheck__LanguageToolConfigDialog_IsSignalConnected(const TextGrammarCheck__LanguageToolConfigDialog* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolConfigDialog_OnIsSignalConnected(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolConfigDialog_SuperIsSignalConnected(const TextGrammarCheck__LanguageToolConfigDialog* self, const QMetaMethod* signal);
double TextGrammarCheck__LanguageToolConfigDialog_GetDecodedMetricF(const TextGrammarCheck__LanguageToolConfigDialog* self, int metricA, int metricB);
void TextGrammarCheck__LanguageToolConfigDialog_OnGetDecodedMetricF(const TextGrammarCheck__LanguageToolConfigDialog* self, intptr_t slot);
double TextGrammarCheck__LanguageToolConfigDialog_SuperGetDecodedMetricF(const TextGrammarCheck__LanguageToolConfigDialog* self, int metricA, int metricB);
void TextGrammarCheck__LanguageToolConfigDialog_Delete(TextGrammarCheck__LanguageToolConfigDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
