#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBLANGUAGETOOLGETLISTOFLANGUAGEJOB_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBLANGUAGETOOLGETLISTOFLANGUAGEJOB_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextGrammarCheck__LanguageToolGetListOfLanguageJob)
typedef TextGrammarCheck::LanguageToolGetListOfLanguageJob TextGrammarCheck__LanguageToolGetListOfLanguageJob;
#endif
#else
typedef struct QChildEvent QChildEvent;
typedef struct QEvent QEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QNetworkAccessManager QNetworkAccessManager;
typedef struct QObject QObject;
typedef struct QTimerEvent QTimerEvent;
typedef struct TextGrammarCheck__LanguageToolGetListOfLanguageJob TextGrammarCheck__LanguageToolGetListOfLanguageJob;
#endif

TextGrammarCheck__LanguageToolGetListOfLanguageJob* TextGrammarCheck__LanguageToolGetListOfLanguageJob_new();
TextGrammarCheck__LanguageToolGetListOfLanguageJob* TextGrammarCheck__LanguageToolGetListOfLanguageJob_new2(QObject* parent);
QMetaObject* TextGrammarCheck__LanguageToolGetListOfLanguageJob_MetaObject(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void* TextGrammarCheck__LanguageToolGetListOfLanguageJob_Metacast(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const char* param1);
int TextGrammarCheck__LanguageToolGetListOfLanguageJob_Metacall(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, int param1, int param2, void** param3);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_CanStart(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_Start(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
libqt_string TextGrammarCheck__LanguageToolGetListOfLanguageJob_ListOfLanguagePath(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SetListOfLanguagePath(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const libqt_string listOfLanguagePath);
QNetworkAccessManager* TextGrammarCheck__LanguageToolGetListOfLanguageJob_NetworkAccessManager(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SetNetworkAccessManager(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QNetworkAccessManager* networkAccessManager);
libqt_string TextGrammarCheck__LanguageToolGetListOfLanguageJob_Url(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SetUrl(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const libqt_string url);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_Finished(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const libqt_string result);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_Connect_Finished(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_Error(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const libqt_string errorStr);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_Connect_Error(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnMetaObject(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
QMetaObject* TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperMetaObject(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnMetacast(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void* TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperMetacast(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const char* param1);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnMetacall(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
int TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperMetacall(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, int param1, int param2, void** param3);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_Event(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QEvent* event);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_EventFilter(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QObject* watched, QEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnEventFilter(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperEventFilter(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QObject* watched, QEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_TimerEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QTimerEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnTimerEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperTimerEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QTimerEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_ChildEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QChildEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnChildEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperChildEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QChildEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_CustomEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnCustomEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperCustomEvent(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, QEvent* event);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_ConnectNotify(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnConnectNotify(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperConnectNotify(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_DisconnectNotify(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnDisconnectNotify(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperDisconnectNotify(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const QMetaMethod* signal);
QObject* TextGrammarCheck__LanguageToolGetListOfLanguageJob_Sender(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnSender(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
QObject* TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperSender(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
int TextGrammarCheck__LanguageToolGetListOfLanguageJob_SenderSignalIndex(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnSenderSignalIndex(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
int TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperSenderSignalIndex(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);
int TextGrammarCheck__LanguageToolGetListOfLanguageJob_Receivers(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const char* signal);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnReceivers(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
int TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperReceivers(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const char* signal);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_IsSignalConnected(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_OnIsSignalConnected(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, intptr_t slot);
bool TextGrammarCheck__LanguageToolGetListOfLanguageJob_SuperIsSignalConnected(const TextGrammarCheck__LanguageToolGetListOfLanguageJob* self, const QMetaMethod* signal);
void TextGrammarCheck__LanguageToolGetListOfLanguageJob_Delete(TextGrammarCheck__LanguageToolGetListOfLanguageJob* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
