#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBPLAINTEXTEDITORWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBPLAINTEXTEDITORWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__PlainTextEditor)
typedef TextCustomEditor::PlainTextEditor TextCustomEditor__PlainTextEditor;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__PlainTextEditorWidget)
typedef TextCustomEditor::PlainTextEditorWidget TextCustomEditor__PlainTextEditorWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextCustomEditor__PlainTextEditor TextCustomEditor__PlainTextEditor;
typedef struct TextCustomEditor__PlainTextEditorWidget TextCustomEditor__PlainTextEditorWidget;
#endif

TextCustomEditor__PlainTextEditorWidget* TextCustomEditor__PlainTextEditorWidget_new(QWidget* parent);
TextCustomEditor__PlainTextEditorWidget* TextCustomEditor__PlainTextEditorWidget_new2();
TextCustomEditor__PlainTextEditorWidget* TextCustomEditor__PlainTextEditorWidget_new3(TextCustomEditor__PlainTextEditor* customEditor);
TextCustomEditor__PlainTextEditorWidget* TextCustomEditor__PlainTextEditorWidget_new4(TextCustomEditor__PlainTextEditor* customEditor, QWidget* parent);
QMetaObject* TextCustomEditor__PlainTextEditorWidget_MetaObject(const TextCustomEditor__PlainTextEditorWidget* self);
void* TextCustomEditor__PlainTextEditorWidget_Metacast(TextCustomEditor__PlainTextEditorWidget* self, const char* param1);
int TextCustomEditor__PlainTextEditorWidget_Metacall(TextCustomEditor__PlainTextEditorWidget* self, int param1, int param2, void** param3);
TextCustomEditor__PlainTextEditor* TextCustomEditor__PlainTextEditorWidget_Editor(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_SetReadOnly(TextCustomEditor__PlainTextEditorWidget* self, bool readOnly);
bool TextCustomEditor__PlainTextEditorWidget_IsReadOnly(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_SetPlainText(TextCustomEditor__PlainTextEditorWidget* self, const libqt_string text);
libqt_string TextCustomEditor__PlainTextEditorWidget_ToPlainText(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_Clear(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_SetSpellCheckingConfigFileName(TextCustomEditor__PlainTextEditorWidget* self, const libqt_string _fileName);
bool TextCustomEditor__PlainTextEditorWidget_IsEmpty(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnMetaObject(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QMetaObject* TextCustomEditor__PlainTextEditorWidget_SuperMetaObject(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnMetacast(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void* TextCustomEditor__PlainTextEditorWidget_SuperMetacast(TextCustomEditor__PlainTextEditorWidget* self, const char* param1);
void TextCustomEditor__PlainTextEditorWidget_OnMetacall(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__PlainTextEditorWidget_SuperMetacall(TextCustomEditor__PlainTextEditorWidget* self, int param1, int param2, void** param3);
int TextCustomEditor__PlainTextEditorWidget_DevType(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnDevType(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__PlainTextEditorWidget_SuperDevType(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_SetVisible(TextCustomEditor__PlainTextEditorWidget* self, bool visible);
void TextCustomEditor__PlainTextEditorWidget_OnSetVisible(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperSetVisible(TextCustomEditor__PlainTextEditorWidget* self, bool visible);
QSize* TextCustomEditor__PlainTextEditorWidget_SizeHint(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnSizeHint(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QSize* TextCustomEditor__PlainTextEditorWidget_SuperSizeHint(const TextCustomEditor__PlainTextEditorWidget* self);
QSize* TextCustomEditor__PlainTextEditorWidget_MinimumSizeHint(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnMinimumSizeHint(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QSize* TextCustomEditor__PlainTextEditorWidget_SuperMinimumSizeHint(const TextCustomEditor__PlainTextEditorWidget* self);
int TextCustomEditor__PlainTextEditorWidget_HeightForWidth(const TextCustomEditor__PlainTextEditorWidget* self, int param1);
void TextCustomEditor__PlainTextEditorWidget_OnHeightForWidth(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__PlainTextEditorWidget_SuperHeightForWidth(const TextCustomEditor__PlainTextEditorWidget* self, int param1);
bool TextCustomEditor__PlainTextEditorWidget_HasHeightForWidth(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnHasHeightForWidth(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperHasHeightForWidth(const TextCustomEditor__PlainTextEditorWidget* self);
QPaintEngine* TextCustomEditor__PlainTextEditorWidget_PaintEngine(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnPaintEngine(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QPaintEngine* TextCustomEditor__PlainTextEditorWidget_SuperPaintEngine(const TextCustomEditor__PlainTextEditorWidget* self);
bool TextCustomEditor__PlainTextEditorWidget_Event(TextCustomEditor__PlainTextEditorWidget* self, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_MousePressEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnMousePressEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperMousePressEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_MouseReleaseEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnMouseReleaseEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperMouseReleaseEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_MouseDoubleClickEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnMouseDoubleClickEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperMouseDoubleClickEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_MouseMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnMouseMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperMouseMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_WheelEvent(TextCustomEditor__PlainTextEditorWidget* self, QWheelEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnWheelEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperWheelEvent(TextCustomEditor__PlainTextEditorWidget* self, QWheelEvent* event);
void TextCustomEditor__PlainTextEditorWidget_KeyPressEvent(TextCustomEditor__PlainTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnKeyPressEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperKeyPressEvent(TextCustomEditor__PlainTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditorWidget_KeyReleaseEvent(TextCustomEditor__PlainTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnKeyReleaseEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperKeyReleaseEvent(TextCustomEditor__PlainTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__PlainTextEditorWidget_FocusInEvent(TextCustomEditor__PlainTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnFocusInEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperFocusInEvent(TextCustomEditor__PlainTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditorWidget_FocusOutEvent(TextCustomEditor__PlainTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnFocusOutEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperFocusOutEvent(TextCustomEditor__PlainTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__PlainTextEditorWidget_EnterEvent(TextCustomEditor__PlainTextEditorWidget* self, QEnterEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnEnterEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperEnterEvent(TextCustomEditor__PlainTextEditorWidget* self, QEnterEvent* event);
void TextCustomEditor__PlainTextEditorWidget_LeaveEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnLeaveEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperLeaveEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_PaintEvent(TextCustomEditor__PlainTextEditorWidget* self, QPaintEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnPaintEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperPaintEvent(TextCustomEditor__PlainTextEditorWidget* self, QPaintEvent* event);
void TextCustomEditor__PlainTextEditorWidget_MoveEvent(TextCustomEditor__PlainTextEditorWidget* self, QMoveEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, QMoveEvent* event);
void TextCustomEditor__PlainTextEditorWidget_ResizeEvent(TextCustomEditor__PlainTextEditorWidget* self, QResizeEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnResizeEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperResizeEvent(TextCustomEditor__PlainTextEditorWidget* self, QResizeEvent* event);
void TextCustomEditor__PlainTextEditorWidget_CloseEvent(TextCustomEditor__PlainTextEditorWidget* self, QCloseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnCloseEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperCloseEvent(TextCustomEditor__PlainTextEditorWidget* self, QCloseEvent* event);
void TextCustomEditor__PlainTextEditorWidget_ContextMenuEvent(TextCustomEditor__PlainTextEditorWidget* self, QContextMenuEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnContextMenuEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperContextMenuEvent(TextCustomEditor__PlainTextEditorWidget* self, QContextMenuEvent* event);
void TextCustomEditor__PlainTextEditorWidget_TabletEvent(TextCustomEditor__PlainTextEditorWidget* self, QTabletEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnTabletEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperTabletEvent(TextCustomEditor__PlainTextEditorWidget* self, QTabletEvent* event);
void TextCustomEditor__PlainTextEditorWidget_ActionEvent(TextCustomEditor__PlainTextEditorWidget* self, QActionEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnActionEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperActionEvent(TextCustomEditor__PlainTextEditorWidget* self, QActionEvent* event);
void TextCustomEditor__PlainTextEditorWidget_DragEnterEvent(TextCustomEditor__PlainTextEditorWidget* self, QDragEnterEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnDragEnterEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperDragEnterEvent(TextCustomEditor__PlainTextEditorWidget* self, QDragEnterEvent* event);
void TextCustomEditor__PlainTextEditorWidget_DragMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, QDragMoveEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnDragMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperDragMoveEvent(TextCustomEditor__PlainTextEditorWidget* self, QDragMoveEvent* event);
void TextCustomEditor__PlainTextEditorWidget_DragLeaveEvent(TextCustomEditor__PlainTextEditorWidget* self, QDragLeaveEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnDragLeaveEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperDragLeaveEvent(TextCustomEditor__PlainTextEditorWidget* self, QDragLeaveEvent* event);
void TextCustomEditor__PlainTextEditorWidget_DropEvent(TextCustomEditor__PlainTextEditorWidget* self, QDropEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnDropEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperDropEvent(TextCustomEditor__PlainTextEditorWidget* self, QDropEvent* event);
void TextCustomEditor__PlainTextEditorWidget_ShowEvent(TextCustomEditor__PlainTextEditorWidget* self, QShowEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnShowEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperShowEvent(TextCustomEditor__PlainTextEditorWidget* self, QShowEvent* event);
void TextCustomEditor__PlainTextEditorWidget_HideEvent(TextCustomEditor__PlainTextEditorWidget* self, QHideEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnHideEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperHideEvent(TextCustomEditor__PlainTextEditorWidget* self, QHideEvent* event);
bool TextCustomEditor__PlainTextEditorWidget_NativeEvent(TextCustomEditor__PlainTextEditorWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__PlainTextEditorWidget_OnNativeEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperNativeEvent(TextCustomEditor__PlainTextEditorWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__PlainTextEditorWidget_ChangeEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* param1);
void TextCustomEditor__PlainTextEditorWidget_OnChangeEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperChangeEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* param1);
int TextCustomEditor__PlainTextEditorWidget_Metric(const TextCustomEditor__PlainTextEditorWidget* self, int param1);
void TextCustomEditor__PlainTextEditorWidget_OnMetric(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__PlainTextEditorWidget_SuperMetric(const TextCustomEditor__PlainTextEditorWidget* self, int param1);
void TextCustomEditor__PlainTextEditorWidget_InitPainter(const TextCustomEditor__PlainTextEditorWidget* self, QPainter* painter);
void TextCustomEditor__PlainTextEditorWidget_OnInitPainter(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperInitPainter(const TextCustomEditor__PlainTextEditorWidget* self, QPainter* painter);
QPaintDevice* TextCustomEditor__PlainTextEditorWidget_Redirected(const TextCustomEditor__PlainTextEditorWidget* self, QPoint* offset);
void TextCustomEditor__PlainTextEditorWidget_OnRedirected(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QPaintDevice* TextCustomEditor__PlainTextEditorWidget_SuperRedirected(const TextCustomEditor__PlainTextEditorWidget* self, QPoint* offset);
QPainter* TextCustomEditor__PlainTextEditorWidget_SharedPainter(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnSharedPainter(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QPainter* TextCustomEditor__PlainTextEditorWidget_SuperSharedPainter(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_InputMethodEvent(TextCustomEditor__PlainTextEditorWidget* self, QInputMethodEvent* param1);
void TextCustomEditor__PlainTextEditorWidget_OnInputMethodEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperInputMethodEvent(TextCustomEditor__PlainTextEditorWidget* self, QInputMethodEvent* param1);
QVariant* TextCustomEditor__PlainTextEditorWidget_InputMethodQuery(const TextCustomEditor__PlainTextEditorWidget* self, int param1);
void TextCustomEditor__PlainTextEditorWidget_OnInputMethodQuery(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QVariant* TextCustomEditor__PlainTextEditorWidget_SuperInputMethodQuery(const TextCustomEditor__PlainTextEditorWidget* self, int param1);
bool TextCustomEditor__PlainTextEditorWidget_FocusNextPrevChild(TextCustomEditor__PlainTextEditorWidget* self, bool next);
void TextCustomEditor__PlainTextEditorWidget_OnFocusNextPrevChild(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperFocusNextPrevChild(TextCustomEditor__PlainTextEditorWidget* self, bool next);
bool TextCustomEditor__PlainTextEditorWidget_EventFilter(TextCustomEditor__PlainTextEditorWidget* self, QObject* watched, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnEventFilter(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperEventFilter(TextCustomEditor__PlainTextEditorWidget* self, QObject* watched, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_TimerEvent(TextCustomEditor__PlainTextEditorWidget* self, QTimerEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnTimerEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperTimerEvent(TextCustomEditor__PlainTextEditorWidget* self, QTimerEvent* event);
void TextCustomEditor__PlainTextEditorWidget_ChildEvent(TextCustomEditor__PlainTextEditorWidget* self, QChildEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnChildEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperChildEvent(TextCustomEditor__PlainTextEditorWidget* self, QChildEvent* event);
void TextCustomEditor__PlainTextEditorWidget_CustomEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_OnCustomEvent(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperCustomEvent(TextCustomEditor__PlainTextEditorWidget* self, QEvent* event);
void TextCustomEditor__PlainTextEditorWidget_ConnectNotify(TextCustomEditor__PlainTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditorWidget_OnConnectNotify(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperConnectNotify(TextCustomEditor__PlainTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditorWidget_DisconnectNotify(TextCustomEditor__PlainTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditorWidget_OnDisconnectNotify(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperDisconnectNotify(TextCustomEditor__PlainTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditorWidget_UpdateMicroFocus(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnUpdateMicroFocus(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperUpdateMicroFocus(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_Create(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnCreate(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperCreate(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_Destroy(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnDestroy(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__PlainTextEditorWidget_SuperDestroy(TextCustomEditor__PlainTextEditorWidget* self);
bool TextCustomEditor__PlainTextEditorWidget_FocusNextChild(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnFocusNextChild(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperFocusNextChild(TextCustomEditor__PlainTextEditorWidget* self);
bool TextCustomEditor__PlainTextEditorWidget_FocusPreviousChild(TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnFocusPreviousChild(TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperFocusPreviousChild(TextCustomEditor__PlainTextEditorWidget* self);
QObject* TextCustomEditor__PlainTextEditorWidget_Sender(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnSender(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
QObject* TextCustomEditor__PlainTextEditorWidget_SuperSender(const TextCustomEditor__PlainTextEditorWidget* self);
int TextCustomEditor__PlainTextEditorWidget_SenderSignalIndex(const TextCustomEditor__PlainTextEditorWidget* self);
void TextCustomEditor__PlainTextEditorWidget_OnSenderSignalIndex(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__PlainTextEditorWidget_SuperSenderSignalIndex(const TextCustomEditor__PlainTextEditorWidget* self);
int TextCustomEditor__PlainTextEditorWidget_Receivers(const TextCustomEditor__PlainTextEditorWidget* self, const char* signal);
void TextCustomEditor__PlainTextEditorWidget_OnReceivers(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__PlainTextEditorWidget_SuperReceivers(const TextCustomEditor__PlainTextEditorWidget* self, const char* signal);
bool TextCustomEditor__PlainTextEditorWidget_IsSignalConnected(const TextCustomEditor__PlainTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextEditorWidget_OnIsSignalConnected(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__PlainTextEditorWidget_SuperIsSignalConnected(const TextCustomEditor__PlainTextEditorWidget* self, const QMetaMethod* signal);
double TextCustomEditor__PlainTextEditorWidget_GetDecodedMetricF(const TextCustomEditor__PlainTextEditorWidget* self, int metricA, int metricB);
void TextCustomEditor__PlainTextEditorWidget_OnGetDecodedMetricF(const TextCustomEditor__PlainTextEditorWidget* self, intptr_t slot);
double TextCustomEditor__PlainTextEditorWidget_SuperGetDecodedMetricF(const TextCustomEditor__PlainTextEditorWidget* self, int metricA, int metricB);
void TextCustomEditor__PlainTextEditorWidget_Delete(TextCustomEditor__PlainTextEditorWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
