#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBPLAINTEXTSYNTAXSPELLCHECKINGHIGHLIGHTER_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBPLAINTEXTSYNTAXSPELLCHECKINGHIGHLIGHTER_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_KSyntaxHighlighting__AbstractHighlighter)
typedef KSyntaxHighlighting::AbstractHighlighter KSyntaxHighlighting__AbstractHighlighter;
#endif
typedef KSyntaxHighlighting::Definition KSyntaxHighlighting__Definition;
typedef KSyntaxHighlighting::FoldingRegion KSyntaxHighlighting__FoldingRegion;
typedef KSyntaxHighlighting::Format KSyntaxHighlighting__Format;
typedef KSyntaxHighlighting::State KSyntaxHighlighting__State;
typedef KSyntaxHighlighting::Theme KSyntaxHighlighting__Theme;
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_Sonnet__Highlighter)
typedef Sonnet::Highlighter Sonnet__Highlighter;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__PlainTextEditor)
typedef TextCustomEditor::PlainTextEditor TextCustomEditor__PlainTextEditor;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter)
typedef TextCustomEditor::PlainTextSyntaxSpellCheckingHighlighter TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter;
#endif
#else
typedef struct KSyntaxHighlighting__AbstractHighlighter KSyntaxHighlighting__AbstractHighlighter;
typedef struct KSyntaxHighlighting__Definition KSyntaxHighlighting__Definition;
typedef struct KSyntaxHighlighting__FoldingRegion KSyntaxHighlighting__FoldingRegion;
typedef struct KSyntaxHighlighting__Format KSyntaxHighlighting__Format;
typedef struct KSyntaxHighlighting__State KSyntaxHighlighting__State;
typedef struct KSyntaxHighlighting__Theme KSyntaxHighlighting__Theme;
typedef struct QChildEvent QChildEvent;
typedef struct QColor QColor;
typedef struct QEvent QEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QSyntaxHighlighter QSyntaxHighlighter;
typedef struct QTextBlock QTextBlock;
typedef struct QTextBlockUserData QTextBlockUserData;
typedef struct QTextCharFormat QTextCharFormat;
typedef struct QTimerEvent QTimerEvent;
typedef struct Sonnet__Highlighter Sonnet__Highlighter;
typedef struct TextCustomEditor__PlainTextEditor TextCustomEditor__PlainTextEditor;
typedef struct TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter;
#endif

TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_new(TextCustomEditor__PlainTextEditor* plainText);
TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_new2(TextCustomEditor__PlainTextEditor* plainText, const QColor* misspelledColor);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_ToggleSpellHighlighting(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, bool on);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetDefinition(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const KSyntaxHighlighting__Definition* def);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_HighlightBlock(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const libqt_string text);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_UnsetMisspelled(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int start, int count);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetMisspelled(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int start, int count);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_ApplyFormat(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int offset, int length, const KSyntaxHighlighting__Format* format);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetDefinition(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetDefinition(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const KSyntaxHighlighting__Definition* def);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnHighlightBlock(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperHighlightBlock(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const libqt_string text);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnUnsetMisspelled(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperUnsetMisspelled(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int start, int count);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetMisspelled(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetMisspelled(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int start, int count);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnApplyFormat(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperApplyFormat(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int offset, int length, const KSyntaxHighlighting__Format* format);
QMetaObject* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_MetaObject(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnMetaObject(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
QMetaObject* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperMetaObject(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Metacast(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const char* param1);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnMetacast(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperMetacast(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const char* param1);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Metacall(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int param1, int param2, void** param3);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnMetacall(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperMetacall(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int param1, int param2, void** param3);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_EventFilter(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QObject* o, QEvent* e);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnEventFilter(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperEventFilter(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QObject* o, QEvent* e);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Event(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_TimerEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QTimerEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnTimerEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperTimerEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QTimerEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_ChildEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QChildEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnChildEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperChildEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QChildEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_CustomEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnCustomEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperCustomEvent(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QEvent* event);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_ConnectNotify(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnConnectNotify(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperConnectNotify(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_DisconnectNotify(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnDisconnectNotify(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperDisconnectNotify(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetTheme(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const KSyntaxHighlighting__Theme* theme);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetTheme(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetTheme(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const KSyntaxHighlighting__Theme* theme);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_ApplyFolding(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int offset, int length, KSyntaxHighlighting__FoldingRegion* region);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnApplyFolding(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperApplyFolding(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int offset, int length, KSyntaxHighlighting__FoldingRegion* region);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_IntraWordEditing(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnIntraWordEditing(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperIntraWordEditing(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetIntraWordEditing(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, bool editing);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetIntraWordEditing(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetIntraWordEditing(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, bool editing);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetFormat(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int start, int count, const QTextCharFormat* format);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetFormat(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetFormat(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int start, int count, const QTextCharFormat* format);
QTextCharFormat* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Format(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int pos);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnFormat(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
QTextCharFormat* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperFormat(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int pos);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_PreviousBlockState(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnPreviousBlockState(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperPreviousBlockState(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_CurrentBlockState(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnCurrentBlockState(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperCurrentBlockState(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetCurrentBlockState(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int newState);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetCurrentBlockState(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetCurrentBlockState(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, int newState);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SetCurrentBlockUserData(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QTextBlockUserData* data);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSetCurrentBlockUserData(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSetCurrentBlockUserData(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, QTextBlockUserData* data);
QTextBlockUserData* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_CurrentBlockUserData(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnCurrentBlockUserData(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
QTextBlockUserData* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperCurrentBlockUserData(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
QTextBlock* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_CurrentBlock(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnCurrentBlock(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
QTextBlock* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperCurrentBlock(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
QObject* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Sender(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSender(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
QObject* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSender(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SenderSignalIndex(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnSenderSignalIndex(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperSenderSignalIndex(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Receivers(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const char* signal);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnReceivers(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
int TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperReceivers(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const char* signal);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_IsSignalConnected(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const QMetaMethod* signal);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnIsSignalConnected(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
bool TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperIsSignalConnected(const TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, const QMetaMethod* signal);
KSyntaxHighlighting__State* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_HighlightLine(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, libqt_string text, const KSyntaxHighlighting__State* state);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_OnHighlightLine(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, intptr_t slot);
KSyntaxHighlighting__State* TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_SuperHighlightLine(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self, libqt_string text, const KSyntaxHighlighting__State* state);
void TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter_Delete(TextCustomEditor__PlainTextSyntaxSpellCheckingHighlighter* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
