#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBRICHTEXTEDITORWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBRICHTEXTEDITORWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__RichTextEditor)
typedef TextCustomEditor::RichTextEditor TextCustomEditor__RichTextEditor;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__RichTextEditorWidget)
typedef TextCustomEditor::RichTextEditorWidget TextCustomEditor__RichTextEditorWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextCustomEditor__RichTextEditor TextCustomEditor__RichTextEditor;
typedef struct TextCustomEditor__RichTextEditorWidget TextCustomEditor__RichTextEditorWidget;
#endif

TextCustomEditor__RichTextEditorWidget* TextCustomEditor__RichTextEditorWidget_new(QWidget* parent);
TextCustomEditor__RichTextEditorWidget* TextCustomEditor__RichTextEditorWidget_new2();
TextCustomEditor__RichTextEditorWidget* TextCustomEditor__RichTextEditorWidget_new3(TextCustomEditor__RichTextEditor* customEditor);
TextCustomEditor__RichTextEditorWidget* TextCustomEditor__RichTextEditorWidget_new4(TextCustomEditor__RichTextEditor* customEditor, QWidget* parent);
QMetaObject* TextCustomEditor__RichTextEditorWidget_MetaObject(const TextCustomEditor__RichTextEditorWidget* self);
void* TextCustomEditor__RichTextEditorWidget_Metacast(TextCustomEditor__RichTextEditorWidget* self, const char* param1);
int TextCustomEditor__RichTextEditorWidget_Metacall(TextCustomEditor__RichTextEditorWidget* self, int param1, int param2, void** param3);
void TextCustomEditor__RichTextEditorWidget_Clear(TextCustomEditor__RichTextEditorWidget* self);
TextCustomEditor__RichTextEditor* TextCustomEditor__RichTextEditorWidget_Editor(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SetReadOnly(TextCustomEditor__RichTextEditorWidget* self, bool readOnly);
bool TextCustomEditor__RichTextEditorWidget_IsReadOnly(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SetHtml(TextCustomEditor__RichTextEditorWidget* self, const libqt_string html);
libqt_string TextCustomEditor__RichTextEditorWidget_ToHtml(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SetPlainText(TextCustomEditor__RichTextEditorWidget* self, const libqt_string text);
libqt_string TextCustomEditor__RichTextEditorWidget_ToPlainText(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SetAcceptRichText(TextCustomEditor__RichTextEditorWidget* self, bool b);
bool TextCustomEditor__RichTextEditorWidget_AcceptRichText(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SetSpellCheckingConfigFileName(TextCustomEditor__RichTextEditorWidget* self, const libqt_string _fileName);
bool TextCustomEditor__RichTextEditorWidget_IsEmpty(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SlotFindNext(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SlotFind(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SlotReplace(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnMetaObject(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QMetaObject* TextCustomEditor__RichTextEditorWidget_SuperMetaObject(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnMetacast(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void* TextCustomEditor__RichTextEditorWidget_SuperMetacast(TextCustomEditor__RichTextEditorWidget* self, const char* param1);
void TextCustomEditor__RichTextEditorWidget_OnMetacall(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__RichTextEditorWidget_SuperMetacall(TextCustomEditor__RichTextEditorWidget* self, int param1, int param2, void** param3);
int TextCustomEditor__RichTextEditorWidget_DevType(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnDevType(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__RichTextEditorWidget_SuperDevType(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_SetVisible(TextCustomEditor__RichTextEditorWidget* self, bool visible);
void TextCustomEditor__RichTextEditorWidget_OnSetVisible(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperSetVisible(TextCustomEditor__RichTextEditorWidget* self, bool visible);
QSize* TextCustomEditor__RichTextEditorWidget_SizeHint(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnSizeHint(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QSize* TextCustomEditor__RichTextEditorWidget_SuperSizeHint(const TextCustomEditor__RichTextEditorWidget* self);
QSize* TextCustomEditor__RichTextEditorWidget_MinimumSizeHint(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnMinimumSizeHint(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QSize* TextCustomEditor__RichTextEditorWidget_SuperMinimumSizeHint(const TextCustomEditor__RichTextEditorWidget* self);
int TextCustomEditor__RichTextEditorWidget_HeightForWidth(const TextCustomEditor__RichTextEditorWidget* self, int param1);
void TextCustomEditor__RichTextEditorWidget_OnHeightForWidth(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__RichTextEditorWidget_SuperHeightForWidth(const TextCustomEditor__RichTextEditorWidget* self, int param1);
bool TextCustomEditor__RichTextEditorWidget_HasHeightForWidth(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnHasHeightForWidth(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperHasHeightForWidth(const TextCustomEditor__RichTextEditorWidget* self);
QPaintEngine* TextCustomEditor__RichTextEditorWidget_PaintEngine(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnPaintEngine(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QPaintEngine* TextCustomEditor__RichTextEditorWidget_SuperPaintEngine(const TextCustomEditor__RichTextEditorWidget* self);
bool TextCustomEditor__RichTextEditorWidget_Event(TextCustomEditor__RichTextEditorWidget* self, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_MousePressEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnMousePressEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperMousePressEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_MouseReleaseEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnMouseReleaseEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperMouseReleaseEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_MouseDoubleClickEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnMouseDoubleClickEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperMouseDoubleClickEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_MouseMoveEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnMouseMoveEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperMouseMoveEvent(TextCustomEditor__RichTextEditorWidget* self, QMouseEvent* event);
void TextCustomEditor__RichTextEditorWidget_WheelEvent(TextCustomEditor__RichTextEditorWidget* self, QWheelEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnWheelEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperWheelEvent(TextCustomEditor__RichTextEditorWidget* self, QWheelEvent* event);
void TextCustomEditor__RichTextEditorWidget_KeyPressEvent(TextCustomEditor__RichTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnKeyPressEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperKeyPressEvent(TextCustomEditor__RichTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__RichTextEditorWidget_KeyReleaseEvent(TextCustomEditor__RichTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnKeyReleaseEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperKeyReleaseEvent(TextCustomEditor__RichTextEditorWidget* self, QKeyEvent* event);
void TextCustomEditor__RichTextEditorWidget_FocusInEvent(TextCustomEditor__RichTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnFocusInEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperFocusInEvent(TextCustomEditor__RichTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__RichTextEditorWidget_FocusOutEvent(TextCustomEditor__RichTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnFocusOutEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperFocusOutEvent(TextCustomEditor__RichTextEditorWidget* self, QFocusEvent* event);
void TextCustomEditor__RichTextEditorWidget_EnterEvent(TextCustomEditor__RichTextEditorWidget* self, QEnterEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnEnterEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperEnterEvent(TextCustomEditor__RichTextEditorWidget* self, QEnterEvent* event);
void TextCustomEditor__RichTextEditorWidget_LeaveEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnLeaveEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperLeaveEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_PaintEvent(TextCustomEditor__RichTextEditorWidget* self, QPaintEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnPaintEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperPaintEvent(TextCustomEditor__RichTextEditorWidget* self, QPaintEvent* event);
void TextCustomEditor__RichTextEditorWidget_MoveEvent(TextCustomEditor__RichTextEditorWidget* self, QMoveEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnMoveEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperMoveEvent(TextCustomEditor__RichTextEditorWidget* self, QMoveEvent* event);
void TextCustomEditor__RichTextEditorWidget_ResizeEvent(TextCustomEditor__RichTextEditorWidget* self, QResizeEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnResizeEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperResizeEvent(TextCustomEditor__RichTextEditorWidget* self, QResizeEvent* event);
void TextCustomEditor__RichTextEditorWidget_CloseEvent(TextCustomEditor__RichTextEditorWidget* self, QCloseEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnCloseEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperCloseEvent(TextCustomEditor__RichTextEditorWidget* self, QCloseEvent* event);
void TextCustomEditor__RichTextEditorWidget_ContextMenuEvent(TextCustomEditor__RichTextEditorWidget* self, QContextMenuEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnContextMenuEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperContextMenuEvent(TextCustomEditor__RichTextEditorWidget* self, QContextMenuEvent* event);
void TextCustomEditor__RichTextEditorWidget_TabletEvent(TextCustomEditor__RichTextEditorWidget* self, QTabletEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnTabletEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperTabletEvent(TextCustomEditor__RichTextEditorWidget* self, QTabletEvent* event);
void TextCustomEditor__RichTextEditorWidget_ActionEvent(TextCustomEditor__RichTextEditorWidget* self, QActionEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnActionEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperActionEvent(TextCustomEditor__RichTextEditorWidget* self, QActionEvent* event);
void TextCustomEditor__RichTextEditorWidget_DragEnterEvent(TextCustomEditor__RichTextEditorWidget* self, QDragEnterEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnDragEnterEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperDragEnterEvent(TextCustomEditor__RichTextEditorWidget* self, QDragEnterEvent* event);
void TextCustomEditor__RichTextEditorWidget_DragMoveEvent(TextCustomEditor__RichTextEditorWidget* self, QDragMoveEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnDragMoveEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperDragMoveEvent(TextCustomEditor__RichTextEditorWidget* self, QDragMoveEvent* event);
void TextCustomEditor__RichTextEditorWidget_DragLeaveEvent(TextCustomEditor__RichTextEditorWidget* self, QDragLeaveEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnDragLeaveEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperDragLeaveEvent(TextCustomEditor__RichTextEditorWidget* self, QDragLeaveEvent* event);
void TextCustomEditor__RichTextEditorWidget_DropEvent(TextCustomEditor__RichTextEditorWidget* self, QDropEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnDropEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperDropEvent(TextCustomEditor__RichTextEditorWidget* self, QDropEvent* event);
void TextCustomEditor__RichTextEditorWidget_ShowEvent(TextCustomEditor__RichTextEditorWidget* self, QShowEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnShowEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperShowEvent(TextCustomEditor__RichTextEditorWidget* self, QShowEvent* event);
void TextCustomEditor__RichTextEditorWidget_HideEvent(TextCustomEditor__RichTextEditorWidget* self, QHideEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnHideEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperHideEvent(TextCustomEditor__RichTextEditorWidget* self, QHideEvent* event);
bool TextCustomEditor__RichTextEditorWidget_NativeEvent(TextCustomEditor__RichTextEditorWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__RichTextEditorWidget_OnNativeEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperNativeEvent(TextCustomEditor__RichTextEditorWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__RichTextEditorWidget_ChangeEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* param1);
void TextCustomEditor__RichTextEditorWidget_OnChangeEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperChangeEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* param1);
int TextCustomEditor__RichTextEditorWidget_Metric(const TextCustomEditor__RichTextEditorWidget* self, int param1);
void TextCustomEditor__RichTextEditorWidget_OnMetric(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__RichTextEditorWidget_SuperMetric(const TextCustomEditor__RichTextEditorWidget* self, int param1);
void TextCustomEditor__RichTextEditorWidget_InitPainter(const TextCustomEditor__RichTextEditorWidget* self, QPainter* painter);
void TextCustomEditor__RichTextEditorWidget_OnInitPainter(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperInitPainter(const TextCustomEditor__RichTextEditorWidget* self, QPainter* painter);
QPaintDevice* TextCustomEditor__RichTextEditorWidget_Redirected(const TextCustomEditor__RichTextEditorWidget* self, QPoint* offset);
void TextCustomEditor__RichTextEditorWidget_OnRedirected(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QPaintDevice* TextCustomEditor__RichTextEditorWidget_SuperRedirected(const TextCustomEditor__RichTextEditorWidget* self, QPoint* offset);
QPainter* TextCustomEditor__RichTextEditorWidget_SharedPainter(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnSharedPainter(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QPainter* TextCustomEditor__RichTextEditorWidget_SuperSharedPainter(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_InputMethodEvent(TextCustomEditor__RichTextEditorWidget* self, QInputMethodEvent* param1);
void TextCustomEditor__RichTextEditorWidget_OnInputMethodEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperInputMethodEvent(TextCustomEditor__RichTextEditorWidget* self, QInputMethodEvent* param1);
QVariant* TextCustomEditor__RichTextEditorWidget_InputMethodQuery(const TextCustomEditor__RichTextEditorWidget* self, int param1);
void TextCustomEditor__RichTextEditorWidget_OnInputMethodQuery(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QVariant* TextCustomEditor__RichTextEditorWidget_SuperInputMethodQuery(const TextCustomEditor__RichTextEditorWidget* self, int param1);
bool TextCustomEditor__RichTextEditorWidget_FocusNextPrevChild(TextCustomEditor__RichTextEditorWidget* self, bool next);
void TextCustomEditor__RichTextEditorWidget_OnFocusNextPrevChild(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperFocusNextPrevChild(TextCustomEditor__RichTextEditorWidget* self, bool next);
bool TextCustomEditor__RichTextEditorWidget_EventFilter(TextCustomEditor__RichTextEditorWidget* self, QObject* watched, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnEventFilter(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperEventFilter(TextCustomEditor__RichTextEditorWidget* self, QObject* watched, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_TimerEvent(TextCustomEditor__RichTextEditorWidget* self, QTimerEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnTimerEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperTimerEvent(TextCustomEditor__RichTextEditorWidget* self, QTimerEvent* event);
void TextCustomEditor__RichTextEditorWidget_ChildEvent(TextCustomEditor__RichTextEditorWidget* self, QChildEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnChildEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperChildEvent(TextCustomEditor__RichTextEditorWidget* self, QChildEvent* event);
void TextCustomEditor__RichTextEditorWidget_CustomEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_OnCustomEvent(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperCustomEvent(TextCustomEditor__RichTextEditorWidget* self, QEvent* event);
void TextCustomEditor__RichTextEditorWidget_ConnectNotify(TextCustomEditor__RichTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextEditorWidget_OnConnectNotify(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperConnectNotify(TextCustomEditor__RichTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextEditorWidget_DisconnectNotify(TextCustomEditor__RichTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextEditorWidget_OnDisconnectNotify(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperDisconnectNotify(TextCustomEditor__RichTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextEditorWidget_UpdateMicroFocus(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnUpdateMicroFocus(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperUpdateMicroFocus(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_Create(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnCreate(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperCreate(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_Destroy(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnDestroy(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
void TextCustomEditor__RichTextEditorWidget_SuperDestroy(TextCustomEditor__RichTextEditorWidget* self);
bool TextCustomEditor__RichTextEditorWidget_FocusNextChild(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnFocusNextChild(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperFocusNextChild(TextCustomEditor__RichTextEditorWidget* self);
bool TextCustomEditor__RichTextEditorWidget_FocusPreviousChild(TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnFocusPreviousChild(TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperFocusPreviousChild(TextCustomEditor__RichTextEditorWidget* self);
QObject* TextCustomEditor__RichTextEditorWidget_Sender(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnSender(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
QObject* TextCustomEditor__RichTextEditorWidget_SuperSender(const TextCustomEditor__RichTextEditorWidget* self);
int TextCustomEditor__RichTextEditorWidget_SenderSignalIndex(const TextCustomEditor__RichTextEditorWidget* self);
void TextCustomEditor__RichTextEditorWidget_OnSenderSignalIndex(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__RichTextEditorWidget_SuperSenderSignalIndex(const TextCustomEditor__RichTextEditorWidget* self);
int TextCustomEditor__RichTextEditorWidget_Receivers(const TextCustomEditor__RichTextEditorWidget* self, const char* signal);
void TextCustomEditor__RichTextEditorWidget_OnReceivers(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
int TextCustomEditor__RichTextEditorWidget_SuperReceivers(const TextCustomEditor__RichTextEditorWidget* self, const char* signal);
bool TextCustomEditor__RichTextEditorWidget_IsSignalConnected(const TextCustomEditor__RichTextEditorWidget* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextEditorWidget_OnIsSignalConnected(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
bool TextCustomEditor__RichTextEditorWidget_SuperIsSignalConnected(const TextCustomEditor__RichTextEditorWidget* self, const QMetaMethod* signal);
double TextCustomEditor__RichTextEditorWidget_GetDecodedMetricF(const TextCustomEditor__RichTextEditorWidget* self, int metricA, int metricB);
void TextCustomEditor__RichTextEditorWidget_OnGetDecodedMetricF(const TextCustomEditor__RichTextEditorWidget* self, intptr_t slot);
double TextCustomEditor__RichTextEditorWidget_SuperGetDecodedMetricF(const TextCustomEditor__RichTextEditorWidget* self, int metricA, int metricB);
void TextCustomEditor__RichTextEditorWidget_Delete(TextCustomEditor__RichTextEditorWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
