#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBRICHTEXTBROWSERFINDBAR_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBRICHTEXTBROWSERFINDBAR_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__RichTextBrowserFindBar)
typedef TextCustomEditor::RichTextBrowserFindBar TextCustomEditor__RichTextBrowserFindBar;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextCustomEditor__TextEditFindBarBase)
typedef TextCustomEditor::TextEditFindBarBase TextCustomEditor__TextEditFindBarBase;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRegularExpression QRegularExpression;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTextBrowser QTextBrowser;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextCustomEditor__RichTextBrowserFindBar TextCustomEditor__RichTextBrowserFindBar;
typedef struct TextCustomEditor__TextEditFindBarBase TextCustomEditor__TextEditFindBarBase;
#endif

TextCustomEditor__RichTextBrowserFindBar* TextCustomEditor__RichTextBrowserFindBar_new(QTextBrowser* view);
TextCustomEditor__RichTextBrowserFindBar* TextCustomEditor__RichTextBrowserFindBar_new2(QTextBrowser* view, QWidget* parent);
QMetaObject* TextCustomEditor__RichTextBrowserFindBar_MetaObject(const TextCustomEditor__RichTextBrowserFindBar* self);
void* TextCustomEditor__RichTextBrowserFindBar_Metacast(TextCustomEditor__RichTextBrowserFindBar* self, const char* param1);
int TextCustomEditor__RichTextBrowserFindBar_Metacall(TextCustomEditor__RichTextBrowserFindBar* self, int param1, int param2, void** param3);
bool TextCustomEditor__RichTextBrowserFindBar_ViewIsReadOnly(const TextCustomEditor__RichTextBrowserFindBar* self);
bool TextCustomEditor__RichTextBrowserFindBar_DocumentIsEmpty(const TextCustomEditor__RichTextBrowserFindBar* self);
bool TextCustomEditor__RichTextBrowserFindBar_SearchInDocument(TextCustomEditor__RichTextBrowserFindBar* self, const libqt_string text, int searchOptions);
bool TextCustomEditor__RichTextBrowserFindBar_SearchInDocument2(TextCustomEditor__RichTextBrowserFindBar* self, const QRegularExpression* regExp, int searchOptions);
void TextCustomEditor__RichTextBrowserFindBar_AutoSearchMoveCursor(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_SlotSearchText(TextCustomEditor__RichTextBrowserFindBar* self, bool backward, bool isAutoSearch);
void TextCustomEditor__RichTextBrowserFindBar_OnMetaObject(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QMetaObject* TextCustomEditor__RichTextBrowserFindBar_SuperMetaObject(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnMetacast(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void* TextCustomEditor__RichTextBrowserFindBar_SuperMetacast(TextCustomEditor__RichTextBrowserFindBar* self, const char* param1);
void TextCustomEditor__RichTextBrowserFindBar_OnMetacall(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
int TextCustomEditor__RichTextBrowserFindBar_SuperMetacall(TextCustomEditor__RichTextBrowserFindBar* self, int param1, int param2, void** param3);
void TextCustomEditor__RichTextBrowserFindBar_OnViewIsReadOnly(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperViewIsReadOnly(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnDocumentIsEmpty(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperDocumentIsEmpty(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnSearchInDocument(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperSearchInDocument(TextCustomEditor__RichTextBrowserFindBar* self, const libqt_string text, int searchOptions);
void TextCustomEditor__RichTextBrowserFindBar_OnSearchInDocument2(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperSearchInDocument2(TextCustomEditor__RichTextBrowserFindBar* self, const QRegularExpression* regExp, int searchOptions);
void TextCustomEditor__RichTextBrowserFindBar_OnAutoSearchMoveCursor(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperAutoSearchMoveCursor(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnSlotSearchText(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperSlotSearchText(TextCustomEditor__RichTextBrowserFindBar* self, bool backward, bool isAutoSearch);
bool TextCustomEditor__RichTextBrowserFindBar_Event(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* e);
void TextCustomEditor__RichTextBrowserFindBar_OnEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* e);
int TextCustomEditor__RichTextBrowserFindBar_DevType(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnDevType(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
int TextCustomEditor__RichTextBrowserFindBar_SuperDevType(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_SetVisible(TextCustomEditor__RichTextBrowserFindBar* self, bool visible);
void TextCustomEditor__RichTextBrowserFindBar_OnSetVisible(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperSetVisible(TextCustomEditor__RichTextBrowserFindBar* self, bool visible);
QSize* TextCustomEditor__RichTextBrowserFindBar_SizeHint(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnSizeHint(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QSize* TextCustomEditor__RichTextBrowserFindBar_SuperSizeHint(const TextCustomEditor__RichTextBrowserFindBar* self);
QSize* TextCustomEditor__RichTextBrowserFindBar_MinimumSizeHint(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnMinimumSizeHint(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QSize* TextCustomEditor__RichTextBrowserFindBar_SuperMinimumSizeHint(const TextCustomEditor__RichTextBrowserFindBar* self);
int TextCustomEditor__RichTextBrowserFindBar_HeightForWidth(const TextCustomEditor__RichTextBrowserFindBar* self, int param1);
void TextCustomEditor__RichTextBrowserFindBar_OnHeightForWidth(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
int TextCustomEditor__RichTextBrowserFindBar_SuperHeightForWidth(const TextCustomEditor__RichTextBrowserFindBar* self, int param1);
bool TextCustomEditor__RichTextBrowserFindBar_HasHeightForWidth(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnHasHeightForWidth(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperHasHeightForWidth(const TextCustomEditor__RichTextBrowserFindBar* self);
QPaintEngine* TextCustomEditor__RichTextBrowserFindBar_PaintEngine(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnPaintEngine(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QPaintEngine* TextCustomEditor__RichTextBrowserFindBar_SuperPaintEngine(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_MousePressEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnMousePressEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperMousePressEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_MouseReleaseEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnMouseReleaseEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperMouseReleaseEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_MouseDoubleClickEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnMouseDoubleClickEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperMouseDoubleClickEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_MouseMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnMouseMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperMouseMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMouseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_WheelEvent(TextCustomEditor__RichTextBrowserFindBar* self, QWheelEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnWheelEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperWheelEvent(TextCustomEditor__RichTextBrowserFindBar* self, QWheelEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_KeyPressEvent(TextCustomEditor__RichTextBrowserFindBar* self, QKeyEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnKeyPressEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperKeyPressEvent(TextCustomEditor__RichTextBrowserFindBar* self, QKeyEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_KeyReleaseEvent(TextCustomEditor__RichTextBrowserFindBar* self, QKeyEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnKeyReleaseEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperKeyReleaseEvent(TextCustomEditor__RichTextBrowserFindBar* self, QKeyEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_FocusInEvent(TextCustomEditor__RichTextBrowserFindBar* self, QFocusEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnFocusInEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperFocusInEvent(TextCustomEditor__RichTextBrowserFindBar* self, QFocusEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_FocusOutEvent(TextCustomEditor__RichTextBrowserFindBar* self, QFocusEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnFocusOutEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperFocusOutEvent(TextCustomEditor__RichTextBrowserFindBar* self, QFocusEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_EnterEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEnterEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnEnterEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperEnterEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEnterEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_LeaveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnLeaveEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperLeaveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_PaintEvent(TextCustomEditor__RichTextBrowserFindBar* self, QPaintEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnPaintEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperPaintEvent(TextCustomEditor__RichTextBrowserFindBar* self, QPaintEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_MoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMoveEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QMoveEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_ResizeEvent(TextCustomEditor__RichTextBrowserFindBar* self, QResizeEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnResizeEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperResizeEvent(TextCustomEditor__RichTextBrowserFindBar* self, QResizeEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_CloseEvent(TextCustomEditor__RichTextBrowserFindBar* self, QCloseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnCloseEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperCloseEvent(TextCustomEditor__RichTextBrowserFindBar* self, QCloseEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_ContextMenuEvent(TextCustomEditor__RichTextBrowserFindBar* self, QContextMenuEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnContextMenuEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperContextMenuEvent(TextCustomEditor__RichTextBrowserFindBar* self, QContextMenuEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_TabletEvent(TextCustomEditor__RichTextBrowserFindBar* self, QTabletEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnTabletEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperTabletEvent(TextCustomEditor__RichTextBrowserFindBar* self, QTabletEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_ActionEvent(TextCustomEditor__RichTextBrowserFindBar* self, QActionEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnActionEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperActionEvent(TextCustomEditor__RichTextBrowserFindBar* self, QActionEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_DragEnterEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDragEnterEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnDragEnterEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperDragEnterEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDragEnterEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_DragMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDragMoveEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnDragMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperDragMoveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDragMoveEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_DragLeaveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDragLeaveEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnDragLeaveEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperDragLeaveEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDragLeaveEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_DropEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDropEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnDropEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperDropEvent(TextCustomEditor__RichTextBrowserFindBar* self, QDropEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_ShowEvent(TextCustomEditor__RichTextBrowserFindBar* self, QShowEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnShowEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperShowEvent(TextCustomEditor__RichTextBrowserFindBar* self, QShowEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_HideEvent(TextCustomEditor__RichTextBrowserFindBar* self, QHideEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnHideEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperHideEvent(TextCustomEditor__RichTextBrowserFindBar* self, QHideEvent* event);
bool TextCustomEditor__RichTextBrowserFindBar_NativeEvent(TextCustomEditor__RichTextBrowserFindBar* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__RichTextBrowserFindBar_OnNativeEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperNativeEvent(TextCustomEditor__RichTextBrowserFindBar* self, const libqt_string eventType, void* message, intptr_t* result);
void TextCustomEditor__RichTextBrowserFindBar_ChangeEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* param1);
void TextCustomEditor__RichTextBrowserFindBar_OnChangeEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperChangeEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* param1);
int TextCustomEditor__RichTextBrowserFindBar_Metric(const TextCustomEditor__RichTextBrowserFindBar* self, int param1);
void TextCustomEditor__RichTextBrowserFindBar_OnMetric(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
int TextCustomEditor__RichTextBrowserFindBar_SuperMetric(const TextCustomEditor__RichTextBrowserFindBar* self, int param1);
void TextCustomEditor__RichTextBrowserFindBar_InitPainter(const TextCustomEditor__RichTextBrowserFindBar* self, QPainter* painter);
void TextCustomEditor__RichTextBrowserFindBar_OnInitPainter(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperInitPainter(const TextCustomEditor__RichTextBrowserFindBar* self, QPainter* painter);
QPaintDevice* TextCustomEditor__RichTextBrowserFindBar_Redirected(const TextCustomEditor__RichTextBrowserFindBar* self, QPoint* offset);
void TextCustomEditor__RichTextBrowserFindBar_OnRedirected(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QPaintDevice* TextCustomEditor__RichTextBrowserFindBar_SuperRedirected(const TextCustomEditor__RichTextBrowserFindBar* self, QPoint* offset);
QPainter* TextCustomEditor__RichTextBrowserFindBar_SharedPainter(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnSharedPainter(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QPainter* TextCustomEditor__RichTextBrowserFindBar_SuperSharedPainter(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_InputMethodEvent(TextCustomEditor__RichTextBrowserFindBar* self, QInputMethodEvent* param1);
void TextCustomEditor__RichTextBrowserFindBar_OnInputMethodEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperInputMethodEvent(TextCustomEditor__RichTextBrowserFindBar* self, QInputMethodEvent* param1);
QVariant* TextCustomEditor__RichTextBrowserFindBar_InputMethodQuery(const TextCustomEditor__RichTextBrowserFindBar* self, int param1);
void TextCustomEditor__RichTextBrowserFindBar_OnInputMethodQuery(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QVariant* TextCustomEditor__RichTextBrowserFindBar_SuperInputMethodQuery(const TextCustomEditor__RichTextBrowserFindBar* self, int param1);
bool TextCustomEditor__RichTextBrowserFindBar_FocusNextPrevChild(TextCustomEditor__RichTextBrowserFindBar* self, bool next);
void TextCustomEditor__RichTextBrowserFindBar_OnFocusNextPrevChild(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperFocusNextPrevChild(TextCustomEditor__RichTextBrowserFindBar* self, bool next);
bool TextCustomEditor__RichTextBrowserFindBar_EventFilter(TextCustomEditor__RichTextBrowserFindBar* self, QObject* watched, QEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnEventFilter(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperEventFilter(TextCustomEditor__RichTextBrowserFindBar* self, QObject* watched, QEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_TimerEvent(TextCustomEditor__RichTextBrowserFindBar* self, QTimerEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnTimerEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperTimerEvent(TextCustomEditor__RichTextBrowserFindBar* self, QTimerEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_ChildEvent(TextCustomEditor__RichTextBrowserFindBar* self, QChildEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnChildEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperChildEvent(TextCustomEditor__RichTextBrowserFindBar* self, QChildEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_CustomEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_OnCustomEvent(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperCustomEvent(TextCustomEditor__RichTextBrowserFindBar* self, QEvent* event);
void TextCustomEditor__RichTextBrowserFindBar_ConnectNotify(TextCustomEditor__RichTextBrowserFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextBrowserFindBar_OnConnectNotify(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperConnectNotify(TextCustomEditor__RichTextBrowserFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextBrowserFindBar_DisconnectNotify(TextCustomEditor__RichTextBrowserFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextBrowserFindBar_OnDisconnectNotify(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperDisconnectNotify(TextCustomEditor__RichTextBrowserFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextBrowserFindBar_ClearSelections(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnClearSelections(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperClearSelections(TextCustomEditor__RichTextBrowserFindBar* self);
bool TextCustomEditor__RichTextBrowserFindBar_SearchText(TextCustomEditor__RichTextBrowserFindBar* self, bool backward, bool isAutoSearch);
void TextCustomEditor__RichTextBrowserFindBar_OnSearchText(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperSearchText(TextCustomEditor__RichTextBrowserFindBar* self, bool backward, bool isAutoSearch);
void TextCustomEditor__RichTextBrowserFindBar_SetFoundMatch(TextCustomEditor__RichTextBrowserFindBar* self, bool match);
void TextCustomEditor__RichTextBrowserFindBar_OnSetFoundMatch(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperSetFoundMatch(TextCustomEditor__RichTextBrowserFindBar* self, bool match);
void TextCustomEditor__RichTextBrowserFindBar_MessageInfo(TextCustomEditor__RichTextBrowserFindBar* self, bool backward, bool isAutoSearch, bool found);
void TextCustomEditor__RichTextBrowserFindBar_OnMessageInfo(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperMessageInfo(TextCustomEditor__RichTextBrowserFindBar* self, bool backward, bool isAutoSearch, bool found);
void TextCustomEditor__RichTextBrowserFindBar_UpdateMicroFocus(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnUpdateMicroFocus(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperUpdateMicroFocus(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_Create(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnCreate(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperCreate(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_Destroy(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnDestroy(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
void TextCustomEditor__RichTextBrowserFindBar_SuperDestroy(TextCustomEditor__RichTextBrowserFindBar* self);
bool TextCustomEditor__RichTextBrowserFindBar_FocusNextChild(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnFocusNextChild(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperFocusNextChild(TextCustomEditor__RichTextBrowserFindBar* self);
bool TextCustomEditor__RichTextBrowserFindBar_FocusPreviousChild(TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnFocusPreviousChild(TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperFocusPreviousChild(TextCustomEditor__RichTextBrowserFindBar* self);
QObject* TextCustomEditor__RichTextBrowserFindBar_Sender(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnSender(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
QObject* TextCustomEditor__RichTextBrowserFindBar_SuperSender(const TextCustomEditor__RichTextBrowserFindBar* self);
int TextCustomEditor__RichTextBrowserFindBar_SenderSignalIndex(const TextCustomEditor__RichTextBrowserFindBar* self);
void TextCustomEditor__RichTextBrowserFindBar_OnSenderSignalIndex(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
int TextCustomEditor__RichTextBrowserFindBar_SuperSenderSignalIndex(const TextCustomEditor__RichTextBrowserFindBar* self);
int TextCustomEditor__RichTextBrowserFindBar_Receivers(const TextCustomEditor__RichTextBrowserFindBar* self, const char* signal);
void TextCustomEditor__RichTextBrowserFindBar_OnReceivers(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
int TextCustomEditor__RichTextBrowserFindBar_SuperReceivers(const TextCustomEditor__RichTextBrowserFindBar* self, const char* signal);
bool TextCustomEditor__RichTextBrowserFindBar_IsSignalConnected(const TextCustomEditor__RichTextBrowserFindBar* self, const QMetaMethod* signal);
void TextCustomEditor__RichTextBrowserFindBar_OnIsSignalConnected(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
bool TextCustomEditor__RichTextBrowserFindBar_SuperIsSignalConnected(const TextCustomEditor__RichTextBrowserFindBar* self, const QMetaMethod* signal);
double TextCustomEditor__RichTextBrowserFindBar_GetDecodedMetricF(const TextCustomEditor__RichTextBrowserFindBar* self, int metricA, int metricB);
void TextCustomEditor__RichTextBrowserFindBar_OnGetDecodedMetricF(const TextCustomEditor__RichTextBrowserFindBar* self, intptr_t slot);
double TextCustomEditor__RichTextBrowserFindBar_SuperGetDecodedMetricF(const TextCustomEditor__RichTextBrowserFindBar* self, int metricA, int metricB);
void TextCustomEditor__RichTextBrowserFindBar_Delete(TextCustomEditor__RichTextBrowserFindBar* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
