#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBSLIDECONTAINER_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBSLIDECONTAINER_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextAddonsWidgets__SlideContainer)
typedef TextAddonsWidgets::SlideContainer TextAddonsWidgets__SlideContainer;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextAddonsWidgets__SlideContainer TextAddonsWidgets__SlideContainer;
#endif

TextAddonsWidgets__SlideContainer* TextAddonsWidgets__SlideContainer_new(QWidget* parent);
TextAddonsWidgets__SlideContainer* TextAddonsWidgets__SlideContainer_new2();
QMetaObject* TextAddonsWidgets__SlideContainer_MetaObject(const TextAddonsWidgets__SlideContainer* self);
void* TextAddonsWidgets__SlideContainer_Metacast(TextAddonsWidgets__SlideContainer* self, const char* param1);
int TextAddonsWidgets__SlideContainer_Metacall(TextAddonsWidgets__SlideContainer* self, int param1, int param2, void** param3);
QWidget* TextAddonsWidgets__SlideContainer_Content(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_SetContent(TextAddonsWidgets__SlideContainer* self, QWidget* content);
QSize* TextAddonsWidgets__SlideContainer_SizeHint(const TextAddonsWidgets__SlideContainer* self);
QSize* TextAddonsWidgets__SlideContainer_MinimumSizeHint(const TextAddonsWidgets__SlideContainer* self);
int TextAddonsWidgets__SlideContainer_SlideHeight(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_SetSlideHeight(TextAddonsWidgets__SlideContainer* self, int height);
void TextAddonsWidgets__SlideContainer_SlideIn(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_SlideOut(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_SlidedIn(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_Connect_SlidedIn(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SlidedOut(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_Connect_SlidedOut(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_ResizeEvent(TextAddonsWidgets__SlideContainer* self, QResizeEvent* param1);
bool TextAddonsWidgets__SlideContainer_EventFilter(TextAddonsWidgets__SlideContainer* self, QObject* param1, QEvent* event);
void TextAddonsWidgets__SlideContainer_OnMetaObject(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QMetaObject* TextAddonsWidgets__SlideContainer_SuperMetaObject(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnMetacast(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void* TextAddonsWidgets__SlideContainer_SuperMetacast(TextAddonsWidgets__SlideContainer* self, const char* param1);
void TextAddonsWidgets__SlideContainer_OnMetacall(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
int TextAddonsWidgets__SlideContainer_SuperMetacall(TextAddonsWidgets__SlideContainer* self, int param1, int param2, void** param3);
void TextAddonsWidgets__SlideContainer_OnSizeHint(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QSize* TextAddonsWidgets__SlideContainer_SuperSizeHint(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnMinimumSizeHint(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QSize* TextAddonsWidgets__SlideContainer_SuperMinimumSizeHint(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnResizeEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperResizeEvent(TextAddonsWidgets__SlideContainer* self, QResizeEvent* param1);
void TextAddonsWidgets__SlideContainer_OnEventFilter(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperEventFilter(TextAddonsWidgets__SlideContainer* self, QObject* param1, QEvent* event);
bool TextAddonsWidgets__SlideContainer_Event(TextAddonsWidgets__SlideContainer* self, QEvent* e);
void TextAddonsWidgets__SlideContainer_OnEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperEvent(TextAddonsWidgets__SlideContainer* self, QEvent* e);
void TextAddonsWidgets__SlideContainer_PaintEvent(TextAddonsWidgets__SlideContainer* self, QPaintEvent* param1);
void TextAddonsWidgets__SlideContainer_OnPaintEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperPaintEvent(TextAddonsWidgets__SlideContainer* self, QPaintEvent* param1);
void TextAddonsWidgets__SlideContainer_ChangeEvent(TextAddonsWidgets__SlideContainer* self, QEvent* param1);
void TextAddonsWidgets__SlideContainer_OnChangeEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperChangeEvent(TextAddonsWidgets__SlideContainer* self, QEvent* param1);
void TextAddonsWidgets__SlideContainer_InitStyleOption(const TextAddonsWidgets__SlideContainer* self, QStyleOptionFrame* option);
void TextAddonsWidgets__SlideContainer_OnInitStyleOption(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperInitStyleOption(const TextAddonsWidgets__SlideContainer* self, QStyleOptionFrame* option);
int TextAddonsWidgets__SlideContainer_DevType(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnDevType(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
int TextAddonsWidgets__SlideContainer_SuperDevType(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_SetVisible(TextAddonsWidgets__SlideContainer* self, bool visible);
void TextAddonsWidgets__SlideContainer_OnSetVisible(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperSetVisible(TextAddonsWidgets__SlideContainer* self, bool visible);
int TextAddonsWidgets__SlideContainer_HeightForWidth(const TextAddonsWidgets__SlideContainer* self, int param1);
void TextAddonsWidgets__SlideContainer_OnHeightForWidth(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
int TextAddonsWidgets__SlideContainer_SuperHeightForWidth(const TextAddonsWidgets__SlideContainer* self, int param1);
bool TextAddonsWidgets__SlideContainer_HasHeightForWidth(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnHasHeightForWidth(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperHasHeightForWidth(const TextAddonsWidgets__SlideContainer* self);
QPaintEngine* TextAddonsWidgets__SlideContainer_PaintEngine(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnPaintEngine(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QPaintEngine* TextAddonsWidgets__SlideContainer_SuperPaintEngine(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_MousePressEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_OnMousePressEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperMousePressEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_MouseReleaseEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_OnMouseReleaseEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperMouseReleaseEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_MouseDoubleClickEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_OnMouseDoubleClickEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperMouseDoubleClickEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_MouseMoveEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_OnMouseMoveEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperMouseMoveEvent(TextAddonsWidgets__SlideContainer* self, QMouseEvent* event);
void TextAddonsWidgets__SlideContainer_WheelEvent(TextAddonsWidgets__SlideContainer* self, QWheelEvent* event);
void TextAddonsWidgets__SlideContainer_OnWheelEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperWheelEvent(TextAddonsWidgets__SlideContainer* self, QWheelEvent* event);
void TextAddonsWidgets__SlideContainer_KeyPressEvent(TextAddonsWidgets__SlideContainer* self, QKeyEvent* event);
void TextAddonsWidgets__SlideContainer_OnKeyPressEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperKeyPressEvent(TextAddonsWidgets__SlideContainer* self, QKeyEvent* event);
void TextAddonsWidgets__SlideContainer_KeyReleaseEvent(TextAddonsWidgets__SlideContainer* self, QKeyEvent* event);
void TextAddonsWidgets__SlideContainer_OnKeyReleaseEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperKeyReleaseEvent(TextAddonsWidgets__SlideContainer* self, QKeyEvent* event);
void TextAddonsWidgets__SlideContainer_FocusInEvent(TextAddonsWidgets__SlideContainer* self, QFocusEvent* event);
void TextAddonsWidgets__SlideContainer_OnFocusInEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperFocusInEvent(TextAddonsWidgets__SlideContainer* self, QFocusEvent* event);
void TextAddonsWidgets__SlideContainer_FocusOutEvent(TextAddonsWidgets__SlideContainer* self, QFocusEvent* event);
void TextAddonsWidgets__SlideContainer_OnFocusOutEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperFocusOutEvent(TextAddonsWidgets__SlideContainer* self, QFocusEvent* event);
void TextAddonsWidgets__SlideContainer_EnterEvent(TextAddonsWidgets__SlideContainer* self, QEnterEvent* event);
void TextAddonsWidgets__SlideContainer_OnEnterEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperEnterEvent(TextAddonsWidgets__SlideContainer* self, QEnterEvent* event);
void TextAddonsWidgets__SlideContainer_LeaveEvent(TextAddonsWidgets__SlideContainer* self, QEvent* event);
void TextAddonsWidgets__SlideContainer_OnLeaveEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperLeaveEvent(TextAddonsWidgets__SlideContainer* self, QEvent* event);
void TextAddonsWidgets__SlideContainer_MoveEvent(TextAddonsWidgets__SlideContainer* self, QMoveEvent* event);
void TextAddonsWidgets__SlideContainer_OnMoveEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperMoveEvent(TextAddonsWidgets__SlideContainer* self, QMoveEvent* event);
void TextAddonsWidgets__SlideContainer_CloseEvent(TextAddonsWidgets__SlideContainer* self, QCloseEvent* event);
void TextAddonsWidgets__SlideContainer_OnCloseEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperCloseEvent(TextAddonsWidgets__SlideContainer* self, QCloseEvent* event);
void TextAddonsWidgets__SlideContainer_ContextMenuEvent(TextAddonsWidgets__SlideContainer* self, QContextMenuEvent* event);
void TextAddonsWidgets__SlideContainer_OnContextMenuEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperContextMenuEvent(TextAddonsWidgets__SlideContainer* self, QContextMenuEvent* event);
void TextAddonsWidgets__SlideContainer_TabletEvent(TextAddonsWidgets__SlideContainer* self, QTabletEvent* event);
void TextAddonsWidgets__SlideContainer_OnTabletEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperTabletEvent(TextAddonsWidgets__SlideContainer* self, QTabletEvent* event);
void TextAddonsWidgets__SlideContainer_ActionEvent(TextAddonsWidgets__SlideContainer* self, QActionEvent* event);
void TextAddonsWidgets__SlideContainer_OnActionEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperActionEvent(TextAddonsWidgets__SlideContainer* self, QActionEvent* event);
void TextAddonsWidgets__SlideContainer_DragEnterEvent(TextAddonsWidgets__SlideContainer* self, QDragEnterEvent* event);
void TextAddonsWidgets__SlideContainer_OnDragEnterEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDragEnterEvent(TextAddonsWidgets__SlideContainer* self, QDragEnterEvent* event);
void TextAddonsWidgets__SlideContainer_DragMoveEvent(TextAddonsWidgets__SlideContainer* self, QDragMoveEvent* event);
void TextAddonsWidgets__SlideContainer_OnDragMoveEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDragMoveEvent(TextAddonsWidgets__SlideContainer* self, QDragMoveEvent* event);
void TextAddonsWidgets__SlideContainer_DragLeaveEvent(TextAddonsWidgets__SlideContainer* self, QDragLeaveEvent* event);
void TextAddonsWidgets__SlideContainer_OnDragLeaveEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDragLeaveEvent(TextAddonsWidgets__SlideContainer* self, QDragLeaveEvent* event);
void TextAddonsWidgets__SlideContainer_DropEvent(TextAddonsWidgets__SlideContainer* self, QDropEvent* event);
void TextAddonsWidgets__SlideContainer_OnDropEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDropEvent(TextAddonsWidgets__SlideContainer* self, QDropEvent* event);
void TextAddonsWidgets__SlideContainer_ShowEvent(TextAddonsWidgets__SlideContainer* self, QShowEvent* event);
void TextAddonsWidgets__SlideContainer_OnShowEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperShowEvent(TextAddonsWidgets__SlideContainer* self, QShowEvent* event);
void TextAddonsWidgets__SlideContainer_HideEvent(TextAddonsWidgets__SlideContainer* self, QHideEvent* event);
void TextAddonsWidgets__SlideContainer_OnHideEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperHideEvent(TextAddonsWidgets__SlideContainer* self, QHideEvent* event);
bool TextAddonsWidgets__SlideContainer_NativeEvent(TextAddonsWidgets__SlideContainer* self, const libqt_string eventType, void* message, intptr_t* result);
void TextAddonsWidgets__SlideContainer_OnNativeEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperNativeEvent(TextAddonsWidgets__SlideContainer* self, const libqt_string eventType, void* message, intptr_t* result);
int TextAddonsWidgets__SlideContainer_Metric(const TextAddonsWidgets__SlideContainer* self, int param1);
void TextAddonsWidgets__SlideContainer_OnMetric(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
int TextAddonsWidgets__SlideContainer_SuperMetric(const TextAddonsWidgets__SlideContainer* self, int param1);
void TextAddonsWidgets__SlideContainer_InitPainter(const TextAddonsWidgets__SlideContainer* self, QPainter* painter);
void TextAddonsWidgets__SlideContainer_OnInitPainter(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperInitPainter(const TextAddonsWidgets__SlideContainer* self, QPainter* painter);
QPaintDevice* TextAddonsWidgets__SlideContainer_Redirected(const TextAddonsWidgets__SlideContainer* self, QPoint* offset);
void TextAddonsWidgets__SlideContainer_OnRedirected(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QPaintDevice* TextAddonsWidgets__SlideContainer_SuperRedirected(const TextAddonsWidgets__SlideContainer* self, QPoint* offset);
QPainter* TextAddonsWidgets__SlideContainer_SharedPainter(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnSharedPainter(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QPainter* TextAddonsWidgets__SlideContainer_SuperSharedPainter(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_InputMethodEvent(TextAddonsWidgets__SlideContainer* self, QInputMethodEvent* param1);
void TextAddonsWidgets__SlideContainer_OnInputMethodEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperInputMethodEvent(TextAddonsWidgets__SlideContainer* self, QInputMethodEvent* param1);
QVariant* TextAddonsWidgets__SlideContainer_InputMethodQuery(const TextAddonsWidgets__SlideContainer* self, int param1);
void TextAddonsWidgets__SlideContainer_OnInputMethodQuery(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QVariant* TextAddonsWidgets__SlideContainer_SuperInputMethodQuery(const TextAddonsWidgets__SlideContainer* self, int param1);
bool TextAddonsWidgets__SlideContainer_FocusNextPrevChild(TextAddonsWidgets__SlideContainer* self, bool next);
void TextAddonsWidgets__SlideContainer_OnFocusNextPrevChild(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperFocusNextPrevChild(TextAddonsWidgets__SlideContainer* self, bool next);
void TextAddonsWidgets__SlideContainer_TimerEvent(TextAddonsWidgets__SlideContainer* self, QTimerEvent* event);
void TextAddonsWidgets__SlideContainer_OnTimerEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperTimerEvent(TextAddonsWidgets__SlideContainer* self, QTimerEvent* event);
void TextAddonsWidgets__SlideContainer_ChildEvent(TextAddonsWidgets__SlideContainer* self, QChildEvent* event);
void TextAddonsWidgets__SlideContainer_OnChildEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperChildEvent(TextAddonsWidgets__SlideContainer* self, QChildEvent* event);
void TextAddonsWidgets__SlideContainer_CustomEvent(TextAddonsWidgets__SlideContainer* self, QEvent* event);
void TextAddonsWidgets__SlideContainer_OnCustomEvent(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperCustomEvent(TextAddonsWidgets__SlideContainer* self, QEvent* event);
void TextAddonsWidgets__SlideContainer_ConnectNotify(TextAddonsWidgets__SlideContainer* self, const QMetaMethod* signal);
void TextAddonsWidgets__SlideContainer_OnConnectNotify(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperConnectNotify(TextAddonsWidgets__SlideContainer* self, const QMetaMethod* signal);
void TextAddonsWidgets__SlideContainer_DisconnectNotify(TextAddonsWidgets__SlideContainer* self, const QMetaMethod* signal);
void TextAddonsWidgets__SlideContainer_OnDisconnectNotify(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDisconnectNotify(TextAddonsWidgets__SlideContainer* self, const QMetaMethod* signal);
void TextAddonsWidgets__SlideContainer_DrawFrame(TextAddonsWidgets__SlideContainer* self, QPainter* param1);
void TextAddonsWidgets__SlideContainer_OnDrawFrame(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDrawFrame(TextAddonsWidgets__SlideContainer* self, QPainter* param1);
void TextAddonsWidgets__SlideContainer_UpdateMicroFocus(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnUpdateMicroFocus(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperUpdateMicroFocus(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_Create(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnCreate(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperCreate(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_Destroy(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnDestroy(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
void TextAddonsWidgets__SlideContainer_SuperDestroy(TextAddonsWidgets__SlideContainer* self);
bool TextAddonsWidgets__SlideContainer_FocusNextChild(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnFocusNextChild(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperFocusNextChild(TextAddonsWidgets__SlideContainer* self);
bool TextAddonsWidgets__SlideContainer_FocusPreviousChild(TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnFocusPreviousChild(TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperFocusPreviousChild(TextAddonsWidgets__SlideContainer* self);
QObject* TextAddonsWidgets__SlideContainer_Sender(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnSender(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
QObject* TextAddonsWidgets__SlideContainer_SuperSender(const TextAddonsWidgets__SlideContainer* self);
int TextAddonsWidgets__SlideContainer_SenderSignalIndex(const TextAddonsWidgets__SlideContainer* self);
void TextAddonsWidgets__SlideContainer_OnSenderSignalIndex(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
int TextAddonsWidgets__SlideContainer_SuperSenderSignalIndex(const TextAddonsWidgets__SlideContainer* self);
int TextAddonsWidgets__SlideContainer_Receivers(const TextAddonsWidgets__SlideContainer* self, const char* signal);
void TextAddonsWidgets__SlideContainer_OnReceivers(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
int TextAddonsWidgets__SlideContainer_SuperReceivers(const TextAddonsWidgets__SlideContainer* self, const char* signal);
bool TextAddonsWidgets__SlideContainer_IsSignalConnected(const TextAddonsWidgets__SlideContainer* self, const QMetaMethod* signal);
void TextAddonsWidgets__SlideContainer_OnIsSignalConnected(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
bool TextAddonsWidgets__SlideContainer_SuperIsSignalConnected(const TextAddonsWidgets__SlideContainer* self, const QMetaMethod* signal);
double TextAddonsWidgets__SlideContainer_GetDecodedMetricF(const TextAddonsWidgets__SlideContainer* self, int metricA, int metricB);
void TextAddonsWidgets__SlideContainer_OnGetDecodedMetricF(const TextAddonsWidgets__SlideContainer* self, intptr_t slot);
double TextAddonsWidgets__SlideContainer_SuperGetDecodedMetricF(const TextAddonsWidgets__SlideContainer* self, int metricA, int metricB);
void TextAddonsWidgets__SlideContainer_Delete(TextAddonsWidgets__SlideContainer* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
