#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechInterface)
typedef TextEditTextToSpeech::TextToSpeechInterface TextEditTextToSpeech__TextToSpeechInterface;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechWidget)
typedef TextEditTextToSpeech::TextToSpeechWidget TextEditTextToSpeech__TextToSpeechWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextEditTextToSpeech__TextToSpeechInterface TextEditTextToSpeech__TextToSpeechInterface;
typedef struct TextEditTextToSpeech__TextToSpeechWidget TextEditTextToSpeech__TextToSpeechWidget;
#endif

TextEditTextToSpeech__TextToSpeechWidget* TextEditTextToSpeech__TextToSpeechWidget_new(QWidget* parent);
TextEditTextToSpeech__TextToSpeechWidget* TextEditTextToSpeech__TextToSpeechWidget_new2();
QMetaObject* TextEditTextToSpeech__TextToSpeechWidget_MetaObject(const TextEditTextToSpeech__TextToSpeechWidget* self);
void* TextEditTextToSpeech__TextToSpeechWidget_Metacast(TextEditTextToSpeech__TextToSpeechWidget* self, const char* param1);
int TextEditTextToSpeech__TextToSpeechWidget_Metacall(TextEditTextToSpeech__TextToSpeechWidget* self, int param1, int param2, void** param3);
int TextEditTextToSpeech__TextToSpeechWidget_State(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_SetState(TextEditTextToSpeech__TextToSpeechWidget* self, int state);
void TextEditTextToSpeech__TextToSpeechWidget_SetTextToSpeechInterface(TextEditTextToSpeech__TextToSpeechWidget* self, TextEditTextToSpeech__TextToSpeechInterface* interface);
bool TextEditTextToSpeech__TextToSpeechWidget_IsReady(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_ShowWidget(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_Say(TextEditTextToSpeech__TextToSpeechWidget* self, const libqt_string text);
void TextEditTextToSpeech__TextToSpeechWidget_SlotStateChanged(TextEditTextToSpeech__TextToSpeechWidget* self, int state);
void TextEditTextToSpeech__TextToSpeechWidget_StateChanged(TextEditTextToSpeech__TextToSpeechWidget* self, int state);
void TextEditTextToSpeech__TextToSpeechWidget_Connect_StateChanged(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_ChangeVisibility(TextEditTextToSpeech__TextToSpeechWidget* self, bool state);
void TextEditTextToSpeech__TextToSpeechWidget_Connect_ChangeVisibility(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_OnMetaObject(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QMetaObject* TextEditTextToSpeech__TextToSpeechWidget_SuperMetaObject(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnMetacast(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void* TextEditTextToSpeech__TextToSpeechWidget_SuperMetacast(TextEditTextToSpeech__TextToSpeechWidget* self, const char* param1);
void TextEditTextToSpeech__TextToSpeechWidget_OnMetacall(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechWidget_SuperMetacall(TextEditTextToSpeech__TextToSpeechWidget* self, int param1, int param2, void** param3);
int TextEditTextToSpeech__TextToSpeechWidget_DevType(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnDevType(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechWidget_SuperDevType(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_SetVisible(TextEditTextToSpeech__TextToSpeechWidget* self, bool visible);
void TextEditTextToSpeech__TextToSpeechWidget_OnSetVisible(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperSetVisible(TextEditTextToSpeech__TextToSpeechWidget* self, bool visible);
QSize* TextEditTextToSpeech__TextToSpeechWidget_SizeHint(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnSizeHint(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechWidget_SuperSizeHint(const TextEditTextToSpeech__TextToSpeechWidget* self);
QSize* TextEditTextToSpeech__TextToSpeechWidget_MinimumSizeHint(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechWidget_SuperMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechWidget* self);
int TextEditTextToSpeech__TextToSpeechWidget_HeightForWidth(const TextEditTextToSpeech__TextToSpeechWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechWidget_OnHeightForWidth(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechWidget_SuperHeightForWidth(const TextEditTextToSpeech__TextToSpeechWidget* self, int param1);
bool TextEditTextToSpeech__TextToSpeechWidget_HasHeightForWidth(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechWidget* self);
QPaintEngine* TextEditTextToSpeech__TextToSpeechWidget_PaintEngine(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnPaintEngine(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QPaintEngine* TextEditTextToSpeech__TextToSpeechWidget_SuperPaintEngine(const TextEditTextToSpeech__TextToSpeechWidget* self);
bool TextEditTextToSpeech__TextToSpeechWidget_Event(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_MousePressEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnMousePressEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperMousePressEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_MouseReleaseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_MouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_MouseMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnMouseMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperMouseMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_WheelEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnWheelEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperWheelEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_KeyPressEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnKeyPressEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperKeyPressEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_KeyReleaseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_FocusInEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnFocusInEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperFocusInEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_FocusOutEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnFocusOutEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperFocusOutEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_EnterEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnEnterEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperEnterEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_LeaveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnLeaveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperLeaveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_PaintEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnPaintEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperPaintEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_MoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_ResizeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QResizeEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnResizeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperResizeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QResizeEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_CloseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QCloseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnCloseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperCloseEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QCloseEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_ContextMenuEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QContextMenuEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnContextMenuEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperContextMenuEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QContextMenuEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_TabletEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnTabletEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperTabletEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_ActionEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnActionEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperActionEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_DragEnterEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnDragEnterEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperDragEnterEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_DragMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnDragMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperDragMoveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_DragLeaveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnDragLeaveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperDragLeaveEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_DropEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnDropEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperDropEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_ShowEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QShowEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnShowEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperShowEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QShowEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_HideEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QHideEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnHideEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperHideEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QHideEvent* event);
bool TextEditTextToSpeech__TextToSpeechWidget_NativeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechWidget_OnNativeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperNativeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechWidget_ChangeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* param1);
void TextEditTextToSpeech__TextToSpeechWidget_OnChangeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperChangeEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* param1);
int TextEditTextToSpeech__TextToSpeechWidget_Metric(const TextEditTextToSpeech__TextToSpeechWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechWidget_OnMetric(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechWidget_SuperMetric(const TextEditTextToSpeech__TextToSpeechWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechWidget_InitPainter(const TextEditTextToSpeech__TextToSpeechWidget* self, QPainter* painter);
void TextEditTextToSpeech__TextToSpeechWidget_OnInitPainter(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperInitPainter(const TextEditTextToSpeech__TextToSpeechWidget* self, QPainter* painter);
QPaintDevice* TextEditTextToSpeech__TextToSpeechWidget_Redirected(const TextEditTextToSpeech__TextToSpeechWidget* self, QPoint* offset);
void TextEditTextToSpeech__TextToSpeechWidget_OnRedirected(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QPaintDevice* TextEditTextToSpeech__TextToSpeechWidget_SuperRedirected(const TextEditTextToSpeech__TextToSpeechWidget* self, QPoint* offset);
QPainter* TextEditTextToSpeech__TextToSpeechWidget_SharedPainter(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnSharedPainter(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QPainter* TextEditTextToSpeech__TextToSpeechWidget_SuperSharedPainter(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_InputMethodEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QInputMethodEvent* param1);
void TextEditTextToSpeech__TextToSpeechWidget_OnInputMethodEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperInputMethodEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QInputMethodEvent* param1);
QVariant* TextEditTextToSpeech__TextToSpeechWidget_InputMethodQuery(const TextEditTextToSpeech__TextToSpeechWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechWidget_OnInputMethodQuery(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QVariant* TextEditTextToSpeech__TextToSpeechWidget_SuperInputMethodQuery(const TextEditTextToSpeech__TextToSpeechWidget* self, int param1);
bool TextEditTextToSpeech__TextToSpeechWidget_FocusNextPrevChild(TextEditTextToSpeech__TextToSpeechWidget* self, bool next);
void TextEditTextToSpeech__TextToSpeechWidget_OnFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechWidget* self, bool next);
bool TextEditTextToSpeech__TextToSpeechWidget_EventFilter(TextEditTextToSpeech__TextToSpeechWidget* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnEventFilter(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperEventFilter(TextEditTextToSpeech__TextToSpeechWidget* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_TimerEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnTimerEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperTimerEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_ChildEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnChildEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperChildEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_CustomEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_OnCustomEvent(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperCustomEvent(TextEditTextToSpeech__TextToSpeechWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechWidget_ConnectNotify(TextEditTextToSpeech__TextToSpeechWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechWidget_OnConnectNotify(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperConnectNotify(TextEditTextToSpeech__TextToSpeechWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechWidget_DisconnectNotify(TextEditTextToSpeech__TextToSpeechWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechWidget_OnDisconnectNotify(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperDisconnectNotify(TextEditTextToSpeech__TextToSpeechWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechWidget_UpdateMicroFocus(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_Create(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnCreate(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperCreate(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_Destroy(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnDestroy(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechWidget_SuperDestroy(TextEditTextToSpeech__TextToSpeechWidget* self);
bool TextEditTextToSpeech__TextToSpeechWidget_FocusNextChild(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnFocusNextChild(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperFocusNextChild(TextEditTextToSpeech__TextToSpeechWidget* self);
bool TextEditTextToSpeech__TextToSpeechWidget_FocusPreviousChild(TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnFocusPreviousChild(TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperFocusPreviousChild(TextEditTextToSpeech__TextToSpeechWidget* self);
QObject* TextEditTextToSpeech__TextToSpeechWidget_Sender(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnSender(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
QObject* TextEditTextToSpeech__TextToSpeechWidget_SuperSender(const TextEditTextToSpeech__TextToSpeechWidget* self);
int TextEditTextToSpeech__TextToSpeechWidget_SenderSignalIndex(const TextEditTextToSpeech__TextToSpeechWidget* self);
void TextEditTextToSpeech__TextToSpeechWidget_OnSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechWidget_SuperSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechWidget* self);
int TextEditTextToSpeech__TextToSpeechWidget_Receivers(const TextEditTextToSpeech__TextToSpeechWidget* self, const char* signal);
void TextEditTextToSpeech__TextToSpeechWidget_OnReceivers(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechWidget_SuperReceivers(const TextEditTextToSpeech__TextToSpeechWidget* self, const char* signal);
bool TextEditTextToSpeech__TextToSpeechWidget_IsSignalConnected(const TextEditTextToSpeech__TextToSpeechWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechWidget_OnIsSignalConnected(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechWidget_SuperIsSignalConnected(const TextEditTextToSpeech__TextToSpeechWidget* self, const QMetaMethod* signal);
double TextEditTextToSpeech__TextToSpeechWidget_GetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechWidget* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechWidget_OnGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechWidget* self, intptr_t slot);
double TextEditTextToSpeech__TextToSpeechWidget_SuperGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechWidget* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechWidget_Delete(TextEditTextToSpeech__TextToSpeechWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
