#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHCONFIGWIDGET_H
#define SRC_RESTRICTED_EXTRAS_KTEXTADDONSC_LIBTEXTTOSPEECHCONFIGWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_TextEditTextToSpeech__TextToSpeechConfigWidget)
typedef TextEditTextToSpeech::TextToSpeechConfigWidget TextEditTextToSpeech__TextToSpeechConfigWidget;
#endif
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct TextEditTextToSpeech__TextToSpeechConfigWidget TextEditTextToSpeech__TextToSpeechConfigWidget;
#endif

TextEditTextToSpeech__TextToSpeechConfigWidget* TextEditTextToSpeech__TextToSpeechConfigWidget_new(QWidget* parent);
TextEditTextToSpeech__TextToSpeechConfigWidget* TextEditTextToSpeech__TextToSpeechConfigWidget_new2();
QMetaObject* TextEditTextToSpeech__TextToSpeechConfigWidget_MetaObject(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void* TextEditTextToSpeech__TextToSpeechConfigWidget_Metacast(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const char* param1);
int TextEditTextToSpeech__TextToSpeechConfigWidget_Metacall(TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1, int param2, void** param3);
void TextEditTextToSpeech__TextToSpeechConfigWidget_InitializeSettings(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_WriteConfig(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ReadConfig(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_RestoreDefaults(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ConfigChanged(TextEditTextToSpeech__TextToSpeechConfigWidget* self, bool state);
void TextEditTextToSpeech__TextToSpeechConfigWidget_Connect_ConfigChanged(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMetaObject(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QMetaObject* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMetaObject(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMetacast(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMetacast(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const char* param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMetacall(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMetacall(TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1, int param2, void** param3);
int TextEditTextToSpeech__TextToSpeechConfigWidget_DevType(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDevType(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDevType(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SetVisible(TextEditTextToSpeech__TextToSpeechConfigWidget* self, bool visible);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnSetVisible(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperSetVisible(TextEditTextToSpeech__TextToSpeechConfigWidget* self, bool visible);
QSize* TextEditTextToSpeech__TextToSpeechConfigWidget_SizeHint(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnSizeHint(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperSizeHint(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
QSize* TextEditTextToSpeech__TextToSpeechConfigWidget_MinimumSizeHint(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QSize* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMinimumSizeHint(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
int TextEditTextToSpeech__TextToSpeechConfigWidget_HeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SuperHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_HasHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperHasHeightForWidth(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
QPaintEngine* TextEditTextToSpeech__TextToSpeechConfigWidget_PaintEngine(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnPaintEngine(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QPaintEngine* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperPaintEngine(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_Event(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_MousePressEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMousePressEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMousePressEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_MouseReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMouseReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_MouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMouseDoubleClickEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_MouseMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMouseMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMouseMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMouseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_WheelEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnWheelEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperWheelEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QWheelEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_KeyPressEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnKeyPressEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperKeyPressEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_KeyReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperKeyReleaseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QKeyEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_FocusInEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnFocusInEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperFocusInEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_FocusOutEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnFocusOutEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperFocusOutEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QFocusEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_EnterEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnEnterEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperEnterEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_LeaveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_PaintEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnPaintEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperPaintEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QPaintEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_MoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ResizeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QResizeEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnResizeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperResizeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QResizeEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_CloseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QCloseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnCloseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperCloseEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QCloseEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ContextMenuEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QContextMenuEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnContextMenuEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperContextMenuEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QContextMenuEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_TabletEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnTabletEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperTabletEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QTabletEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ActionEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnActionEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperActionEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QActionEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_DragEnterEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDragEnterEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDragEnterEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDragEnterEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_DragMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDragMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDragMoveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDragMoveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_DragLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDragLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDragLeaveEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDragLeaveEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_DropEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDropEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDropEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QDropEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ShowEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QShowEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnShowEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperShowEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QShowEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_HideEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QHideEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnHideEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperHideEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QHideEvent* event);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_NativeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnNativeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperNativeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ChangeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnChangeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperChangeEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* param1);
int TextEditTextToSpeech__TextToSpeechConfigWidget_Metric(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnMetric(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SuperMetric(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_InitPainter(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, QPainter* painter);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnInitPainter(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperInitPainter(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, QPainter* painter);
QPaintDevice* TextEditTextToSpeech__TextToSpeechConfigWidget_Redirected(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, QPoint* offset);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnRedirected(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QPaintDevice* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperRedirected(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, QPoint* offset);
QPainter* TextEditTextToSpeech__TextToSpeechConfigWidget_SharedPainter(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnSharedPainter(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QPainter* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperSharedPainter(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_InputMethodEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QInputMethodEvent* param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnInputMethodEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperInputMethodEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QInputMethodEvent* param1);
QVariant* TextEditTextToSpeech__TextToSpeechConfigWidget_InputMethodQuery(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnInputMethodQuery(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QVariant* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperInputMethodQuery(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int param1);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_FocusNextPrevChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self, bool next);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperFocusNextPrevChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self, bool next);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_EventFilter(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnEventFilter(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperEventFilter(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QObject* watched, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_TimerEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnTimerEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperTimerEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QTimerEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ChildEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnChildEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperChildEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QChildEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_CustomEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnCustomEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperCustomEvent(TextEditTextToSpeech__TextToSpeechConfigWidget* self, QEvent* event);
void TextEditTextToSpeech__TextToSpeechConfigWidget_ConnectNotify(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnConnectNotify(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperConnectNotify(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigWidget_DisconnectNotify(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDisconnectNotify(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDisconnectNotify(TextEditTextToSpeech__TextToSpeechConfigWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigWidget_UpdateMicroFocus(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperUpdateMicroFocus(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_Create(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnCreate(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperCreate(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_Destroy(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnDestroy(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
void TextEditTextToSpeech__TextToSpeechConfigWidget_SuperDestroy(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_FocusNextChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnFocusNextChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperFocusNextChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_FocusPreviousChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnFocusPreviousChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperFocusPreviousChild(TextEditTextToSpeech__TextToSpeechConfigWidget* self);
QObject* TextEditTextToSpeech__TextToSpeechConfigWidget_Sender(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnSender(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
QObject* TextEditTextToSpeech__TextToSpeechConfigWidget_SuperSender(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SenderSignalIndex(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SuperSenderSignalIndex(const TextEditTextToSpeech__TextToSpeechConfigWidget* self);
int TextEditTextToSpeech__TextToSpeechConfigWidget_Receivers(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, const char* signal);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnReceivers(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
int TextEditTextToSpeech__TextToSpeechConfigWidget_SuperReceivers(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, const char* signal);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_IsSignalConnected(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, const QMetaMethod* signal);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnIsSignalConnected(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
bool TextEditTextToSpeech__TextToSpeechConfigWidget_SuperIsSignalConnected(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, const QMetaMethod* signal);
double TextEditTextToSpeech__TextToSpeechConfigWidget_GetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechConfigWidget_OnGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, intptr_t slot);
double TextEditTextToSpeech__TextToSpeechConfigWidget_SuperGetDecodedMetricF(const TextEditTextToSpeech__TextToSpeechConfigWidget* self, int metricA, int metricB);
void TextEditTextToSpeech__TextToSpeechConfigWidget_Delete(TextEditTextToSpeech__TextToSpeechConfigWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
