#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKFONTCHOOSERDIALOG_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKFONTCHOOSERDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KFontChooserDialog KFontChooserDialog;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KFontChooserDialog* KFontChooserDialog_new();
KFontChooserDialog* KFontChooserDialog_new2(const int* flags);
KFontChooserDialog* KFontChooserDialog_new3(const int* flags, QWidget* parent);
QMetaObject* KFontChooserDialog_MetaObject(const KFontChooserDialog* self);
void* KFontChooserDialog_Metacast(KFontChooserDialog* self, const char* param1);
int KFontChooserDialog_Metacall(KFontChooserDialog* self, int param1, int param2, void** param3);
void KFontChooserDialog_SetFont(KFontChooserDialog* self, const QFont* font);
QFont* KFontChooserDialog_Font(const KFontChooserDialog* self);
int KFontChooserDialog_GetFont(QFont* theFont);
int KFontChooserDialog_GetFontDiff(QFont* theFont, int* diffFlags);
void KFontChooserDialog_FontSelected(KFontChooserDialog* self, const QFont* font);
void KFontChooserDialog_Connect_FontSelected(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SetFont2(KFontChooserDialog* self, const QFont* font, bool onlyFixed);
int KFontChooserDialog_GetFont2(QFont* theFont, const int* flags);
int KFontChooserDialog_GetFont3(QFont* theFont, const int* flags, QWidget* parent);
int KFontChooserDialog_GetFontDiff3(QFont* theFont, int* diffFlags, const int* flags);
int KFontChooserDialog_GetFontDiff4(QFont* theFont, int* diffFlags, const int* flags, QWidget* parent);
void KFontChooserDialog_OnMetaObject(const KFontChooserDialog* self, intptr_t slot);
QMetaObject* KFontChooserDialog_SuperMetaObject(const KFontChooserDialog* self);
void KFontChooserDialog_OnMetacast(KFontChooserDialog* self, intptr_t slot);
void* KFontChooserDialog_SuperMetacast(KFontChooserDialog* self, const char* param1);
void KFontChooserDialog_OnMetacall(KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperMetacall(KFontChooserDialog* self, int param1, int param2, void** param3);
void KFontChooserDialog_SetVisible(KFontChooserDialog* self, bool visible);
void KFontChooserDialog_OnSetVisible(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperSetVisible(KFontChooserDialog* self, bool visible);
QSize* KFontChooserDialog_SizeHint(const KFontChooserDialog* self);
void KFontChooserDialog_OnSizeHint(const KFontChooserDialog* self, intptr_t slot);
QSize* KFontChooserDialog_SuperSizeHint(const KFontChooserDialog* self);
QSize* KFontChooserDialog_MinimumSizeHint(const KFontChooserDialog* self);
void KFontChooserDialog_OnMinimumSizeHint(const KFontChooserDialog* self, intptr_t slot);
QSize* KFontChooserDialog_SuperMinimumSizeHint(const KFontChooserDialog* self);
void KFontChooserDialog_Open(KFontChooserDialog* self);
void KFontChooserDialog_OnOpen(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperOpen(KFontChooserDialog* self);
int KFontChooserDialog_Exec(KFontChooserDialog* self);
void KFontChooserDialog_OnExec(KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperExec(KFontChooserDialog* self);
void KFontChooserDialog_Done(KFontChooserDialog* self, int param1);
void KFontChooserDialog_OnDone(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDone(KFontChooserDialog* self, int param1);
void KFontChooserDialog_Accept(KFontChooserDialog* self);
void KFontChooserDialog_OnAccept(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperAccept(KFontChooserDialog* self);
void KFontChooserDialog_Reject(KFontChooserDialog* self);
void KFontChooserDialog_OnReject(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperReject(KFontChooserDialog* self);
void KFontChooserDialog_KeyPressEvent(KFontChooserDialog* self, QKeyEvent* param1);
void KFontChooserDialog_OnKeyPressEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperKeyPressEvent(KFontChooserDialog* self, QKeyEvent* param1);
void KFontChooserDialog_CloseEvent(KFontChooserDialog* self, QCloseEvent* param1);
void KFontChooserDialog_OnCloseEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperCloseEvent(KFontChooserDialog* self, QCloseEvent* param1);
void KFontChooserDialog_ShowEvent(KFontChooserDialog* self, QShowEvent* param1);
void KFontChooserDialog_OnShowEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperShowEvent(KFontChooserDialog* self, QShowEvent* param1);
void KFontChooserDialog_ResizeEvent(KFontChooserDialog* self, QResizeEvent* param1);
void KFontChooserDialog_OnResizeEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperResizeEvent(KFontChooserDialog* self, QResizeEvent* param1);
void KFontChooserDialog_ContextMenuEvent(KFontChooserDialog* self, QContextMenuEvent* param1);
void KFontChooserDialog_OnContextMenuEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperContextMenuEvent(KFontChooserDialog* self, QContextMenuEvent* param1);
bool KFontChooserDialog_EventFilter(KFontChooserDialog* self, QObject* param1, QEvent* param2);
void KFontChooserDialog_OnEventFilter(KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperEventFilter(KFontChooserDialog* self, QObject* param1, QEvent* param2);
int KFontChooserDialog_DevType(const KFontChooserDialog* self);
void KFontChooserDialog_OnDevType(const KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperDevType(const KFontChooserDialog* self);
int KFontChooserDialog_HeightForWidth(const KFontChooserDialog* self, int param1);
void KFontChooserDialog_OnHeightForWidth(const KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperHeightForWidth(const KFontChooserDialog* self, int param1);
bool KFontChooserDialog_HasHeightForWidth(const KFontChooserDialog* self);
void KFontChooserDialog_OnHasHeightForWidth(const KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperHasHeightForWidth(const KFontChooserDialog* self);
QPaintEngine* KFontChooserDialog_PaintEngine(const KFontChooserDialog* self);
void KFontChooserDialog_OnPaintEngine(const KFontChooserDialog* self, intptr_t slot);
QPaintEngine* KFontChooserDialog_SuperPaintEngine(const KFontChooserDialog* self);
bool KFontChooserDialog_Event(KFontChooserDialog* self, QEvent* event);
void KFontChooserDialog_OnEvent(KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperEvent(KFontChooserDialog* self, QEvent* event);
void KFontChooserDialog_MousePressEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_OnMousePressEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperMousePressEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_MouseReleaseEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_OnMouseReleaseEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperMouseReleaseEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_MouseDoubleClickEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_OnMouseDoubleClickEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperMouseDoubleClickEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_MouseMoveEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_OnMouseMoveEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperMouseMoveEvent(KFontChooserDialog* self, QMouseEvent* event);
void KFontChooserDialog_WheelEvent(KFontChooserDialog* self, QWheelEvent* event);
void KFontChooserDialog_OnWheelEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperWheelEvent(KFontChooserDialog* self, QWheelEvent* event);
void KFontChooserDialog_KeyReleaseEvent(KFontChooserDialog* self, QKeyEvent* event);
void KFontChooserDialog_OnKeyReleaseEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperKeyReleaseEvent(KFontChooserDialog* self, QKeyEvent* event);
void KFontChooserDialog_FocusInEvent(KFontChooserDialog* self, QFocusEvent* event);
void KFontChooserDialog_OnFocusInEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperFocusInEvent(KFontChooserDialog* self, QFocusEvent* event);
void KFontChooserDialog_FocusOutEvent(KFontChooserDialog* self, QFocusEvent* event);
void KFontChooserDialog_OnFocusOutEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperFocusOutEvent(KFontChooserDialog* self, QFocusEvent* event);
void KFontChooserDialog_EnterEvent(KFontChooserDialog* self, QEnterEvent* event);
void KFontChooserDialog_OnEnterEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperEnterEvent(KFontChooserDialog* self, QEnterEvent* event);
void KFontChooserDialog_LeaveEvent(KFontChooserDialog* self, QEvent* event);
void KFontChooserDialog_OnLeaveEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperLeaveEvent(KFontChooserDialog* self, QEvent* event);
void KFontChooserDialog_PaintEvent(KFontChooserDialog* self, QPaintEvent* event);
void KFontChooserDialog_OnPaintEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperPaintEvent(KFontChooserDialog* self, QPaintEvent* event);
void KFontChooserDialog_MoveEvent(KFontChooserDialog* self, QMoveEvent* event);
void KFontChooserDialog_OnMoveEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperMoveEvent(KFontChooserDialog* self, QMoveEvent* event);
void KFontChooserDialog_TabletEvent(KFontChooserDialog* self, QTabletEvent* event);
void KFontChooserDialog_OnTabletEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperTabletEvent(KFontChooserDialog* self, QTabletEvent* event);
void KFontChooserDialog_ActionEvent(KFontChooserDialog* self, QActionEvent* event);
void KFontChooserDialog_OnActionEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperActionEvent(KFontChooserDialog* self, QActionEvent* event);
void KFontChooserDialog_DragEnterEvent(KFontChooserDialog* self, QDragEnterEvent* event);
void KFontChooserDialog_OnDragEnterEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDragEnterEvent(KFontChooserDialog* self, QDragEnterEvent* event);
void KFontChooserDialog_DragMoveEvent(KFontChooserDialog* self, QDragMoveEvent* event);
void KFontChooserDialog_OnDragMoveEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDragMoveEvent(KFontChooserDialog* self, QDragMoveEvent* event);
void KFontChooserDialog_DragLeaveEvent(KFontChooserDialog* self, QDragLeaveEvent* event);
void KFontChooserDialog_OnDragLeaveEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDragLeaveEvent(KFontChooserDialog* self, QDragLeaveEvent* event);
void KFontChooserDialog_DropEvent(KFontChooserDialog* self, QDropEvent* event);
void KFontChooserDialog_OnDropEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDropEvent(KFontChooserDialog* self, QDropEvent* event);
void KFontChooserDialog_HideEvent(KFontChooserDialog* self, QHideEvent* event);
void KFontChooserDialog_OnHideEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperHideEvent(KFontChooserDialog* self, QHideEvent* event);
bool KFontChooserDialog_NativeEvent(KFontChooserDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KFontChooserDialog_OnNativeEvent(KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperNativeEvent(KFontChooserDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KFontChooserDialog_ChangeEvent(KFontChooserDialog* self, QEvent* param1);
void KFontChooserDialog_OnChangeEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperChangeEvent(KFontChooserDialog* self, QEvent* param1);
int KFontChooserDialog_Metric(const KFontChooserDialog* self, int param1);
void KFontChooserDialog_OnMetric(const KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperMetric(const KFontChooserDialog* self, int param1);
void KFontChooserDialog_InitPainter(const KFontChooserDialog* self, QPainter* painter);
void KFontChooserDialog_OnInitPainter(const KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperInitPainter(const KFontChooserDialog* self, QPainter* painter);
QPaintDevice* KFontChooserDialog_Redirected(const KFontChooserDialog* self, QPoint* offset);
void KFontChooserDialog_OnRedirected(const KFontChooserDialog* self, intptr_t slot);
QPaintDevice* KFontChooserDialog_SuperRedirected(const KFontChooserDialog* self, QPoint* offset);
QPainter* KFontChooserDialog_SharedPainter(const KFontChooserDialog* self);
void KFontChooserDialog_OnSharedPainter(const KFontChooserDialog* self, intptr_t slot);
QPainter* KFontChooserDialog_SuperSharedPainter(const KFontChooserDialog* self);
void KFontChooserDialog_InputMethodEvent(KFontChooserDialog* self, QInputMethodEvent* param1);
void KFontChooserDialog_OnInputMethodEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperInputMethodEvent(KFontChooserDialog* self, QInputMethodEvent* param1);
QVariant* KFontChooserDialog_InputMethodQuery(const KFontChooserDialog* self, int param1);
void KFontChooserDialog_OnInputMethodQuery(const KFontChooserDialog* self, intptr_t slot);
QVariant* KFontChooserDialog_SuperInputMethodQuery(const KFontChooserDialog* self, int param1);
bool KFontChooserDialog_FocusNextPrevChild(KFontChooserDialog* self, bool next);
void KFontChooserDialog_OnFocusNextPrevChild(KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperFocusNextPrevChild(KFontChooserDialog* self, bool next);
void KFontChooserDialog_TimerEvent(KFontChooserDialog* self, QTimerEvent* event);
void KFontChooserDialog_OnTimerEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperTimerEvent(KFontChooserDialog* self, QTimerEvent* event);
void KFontChooserDialog_ChildEvent(KFontChooserDialog* self, QChildEvent* event);
void KFontChooserDialog_OnChildEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperChildEvent(KFontChooserDialog* self, QChildEvent* event);
void KFontChooserDialog_CustomEvent(KFontChooserDialog* self, QEvent* event);
void KFontChooserDialog_OnCustomEvent(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperCustomEvent(KFontChooserDialog* self, QEvent* event);
void KFontChooserDialog_ConnectNotify(KFontChooserDialog* self, const QMetaMethod* signal);
void KFontChooserDialog_OnConnectNotify(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperConnectNotify(KFontChooserDialog* self, const QMetaMethod* signal);
void KFontChooserDialog_DisconnectNotify(KFontChooserDialog* self, const QMetaMethod* signal);
void KFontChooserDialog_OnDisconnectNotify(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDisconnectNotify(KFontChooserDialog* self, const QMetaMethod* signal);
void KFontChooserDialog_AdjustPosition(KFontChooserDialog* self, QWidget* param1);
void KFontChooserDialog_OnAdjustPosition(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperAdjustPosition(KFontChooserDialog* self, QWidget* param1);
void KFontChooserDialog_UpdateMicroFocus(KFontChooserDialog* self);
void KFontChooserDialog_OnUpdateMicroFocus(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperUpdateMicroFocus(KFontChooserDialog* self);
void KFontChooserDialog_Create(KFontChooserDialog* self);
void KFontChooserDialog_OnCreate(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperCreate(KFontChooserDialog* self);
void KFontChooserDialog_Destroy(KFontChooserDialog* self);
void KFontChooserDialog_OnDestroy(KFontChooserDialog* self, intptr_t slot);
void KFontChooserDialog_SuperDestroy(KFontChooserDialog* self);
bool KFontChooserDialog_FocusNextChild(KFontChooserDialog* self);
void KFontChooserDialog_OnFocusNextChild(KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperFocusNextChild(KFontChooserDialog* self);
bool KFontChooserDialog_FocusPreviousChild(KFontChooserDialog* self);
void KFontChooserDialog_OnFocusPreviousChild(KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperFocusPreviousChild(KFontChooserDialog* self);
QObject* KFontChooserDialog_Sender(const KFontChooserDialog* self);
void KFontChooserDialog_OnSender(const KFontChooserDialog* self, intptr_t slot);
QObject* KFontChooserDialog_SuperSender(const KFontChooserDialog* self);
int KFontChooserDialog_SenderSignalIndex(const KFontChooserDialog* self);
void KFontChooserDialog_OnSenderSignalIndex(const KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperSenderSignalIndex(const KFontChooserDialog* self);
int KFontChooserDialog_Receivers(const KFontChooserDialog* self, const char* signal);
void KFontChooserDialog_OnReceivers(const KFontChooserDialog* self, intptr_t slot);
int KFontChooserDialog_SuperReceivers(const KFontChooserDialog* self, const char* signal);
bool KFontChooserDialog_IsSignalConnected(const KFontChooserDialog* self, const QMetaMethod* signal);
void KFontChooserDialog_OnIsSignalConnected(const KFontChooserDialog* self, intptr_t slot);
bool KFontChooserDialog_SuperIsSignalConnected(const KFontChooserDialog* self, const QMetaMethod* signal);
double KFontChooserDialog_GetDecodedMetricF(const KFontChooserDialog* self, int metricA, int metricB);
void KFontChooserDialog_OnGetDecodedMetricF(const KFontChooserDialog* self, intptr_t slot);
double KFontChooserDialog_SuperGetDecodedMetricF(const KFontChooserDialog* self, int metricA, int metricB);
void KFontChooserDialog_Delete(KFontChooserDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
