#pragma once
#ifndef SRC_EXTRAS_KWIDGETSADDONSC_LIBKPAGEVIEW_H
#define SRC_EXTRAS_KWIDGETSADDONSC_LIBKPAGEVIEW_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KPageView KPageView;
typedef struct QAbstractItemDelegate QAbstractItemDelegate;
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractItemView QAbstractItemView;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QModelIndex QModelIndex;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KPageView* KPageView_new(QWidget* parent);
KPageView* KPageView_new2();
QMetaObject* KPageView_MetaObject(const KPageView* self);
void* KPageView_Metacast(KPageView* self, const char* param1);
int KPageView_Metacall(KPageView* self, int param1, int param2, void** param3);
void KPageView_SetModel(KPageView* self, QAbstractItemModel* model);
QAbstractItemModel* KPageView_Model(const KPageView* self);
void KPageView_SetFaceType(KPageView* self, int faceType);
int KPageView_FaceType(const KPageView* self);
void KPageView_SetCurrentPage(KPageView* self, const QModelIndex* index);
QModelIndex* KPageView_CurrentPage(const KPageView* self);
void KPageView_SetItemDelegate(KPageView* self, QAbstractItemDelegate* delegate);
QAbstractItemDelegate* KPageView_ItemDelegate(const KPageView* self);
void KPageView_SetDefaultWidget(KPageView* self, QWidget* widget);
void KPageView_SetPageHeader(KPageView* self, QWidget* header);
QWidget* KPageView_PageHeader(const KPageView* self);
void KPageView_SetPageFooter(KPageView* self, QWidget* footer);
QWidget* KPageView_PageFooter(const KPageView* self);
void KPageView_CurrentPageChanged(KPageView* self, const QModelIndex* current, const QModelIndex* previous);
void KPageView_Connect_CurrentPageChanged(KPageView* self, intptr_t slot);
QAbstractItemView* KPageView_CreateView(KPageView* self);
bool KPageView_ShowPageHeader(const KPageView* self);
int KPageView_ViewPosition(const KPageView* self);
void KPageView_OnMetaObject(const KPageView* self, intptr_t slot);
QMetaObject* KPageView_SuperMetaObject(const KPageView* self);
void KPageView_OnMetacast(KPageView* self, intptr_t slot);
void* KPageView_SuperMetacast(KPageView* self, const char* param1);
void KPageView_OnMetacall(KPageView* self, intptr_t slot);
int KPageView_SuperMetacall(KPageView* self, int param1, int param2, void** param3);
void KPageView_OnCreateView(KPageView* self, intptr_t slot);
QAbstractItemView* KPageView_SuperCreateView(KPageView* self);
void KPageView_OnShowPageHeader(const KPageView* self, intptr_t slot);
bool KPageView_SuperShowPageHeader(const KPageView* self);
void KPageView_OnViewPosition(const KPageView* self, intptr_t slot);
int KPageView_SuperViewPosition(const KPageView* self);
int KPageView_DevType(const KPageView* self);
void KPageView_OnDevType(const KPageView* self, intptr_t slot);
int KPageView_SuperDevType(const KPageView* self);
void KPageView_SetVisible(KPageView* self, bool visible);
void KPageView_OnSetVisible(KPageView* self, intptr_t slot);
void KPageView_SuperSetVisible(KPageView* self, bool visible);
QSize* KPageView_SizeHint(const KPageView* self);
void KPageView_OnSizeHint(const KPageView* self, intptr_t slot);
QSize* KPageView_SuperSizeHint(const KPageView* self);
QSize* KPageView_MinimumSizeHint(const KPageView* self);
void KPageView_OnMinimumSizeHint(const KPageView* self, intptr_t slot);
QSize* KPageView_SuperMinimumSizeHint(const KPageView* self);
int KPageView_HeightForWidth(const KPageView* self, int param1);
void KPageView_OnHeightForWidth(const KPageView* self, intptr_t slot);
int KPageView_SuperHeightForWidth(const KPageView* self, int param1);
bool KPageView_HasHeightForWidth(const KPageView* self);
void KPageView_OnHasHeightForWidth(const KPageView* self, intptr_t slot);
bool KPageView_SuperHasHeightForWidth(const KPageView* self);
QPaintEngine* KPageView_PaintEngine(const KPageView* self);
void KPageView_OnPaintEngine(const KPageView* self, intptr_t slot);
QPaintEngine* KPageView_SuperPaintEngine(const KPageView* self);
bool KPageView_Event(KPageView* self, QEvent* event);
void KPageView_OnEvent(KPageView* self, intptr_t slot);
bool KPageView_SuperEvent(KPageView* self, QEvent* event);
void KPageView_MousePressEvent(KPageView* self, QMouseEvent* event);
void KPageView_OnMousePressEvent(KPageView* self, intptr_t slot);
void KPageView_SuperMousePressEvent(KPageView* self, QMouseEvent* event);
void KPageView_MouseReleaseEvent(KPageView* self, QMouseEvent* event);
void KPageView_OnMouseReleaseEvent(KPageView* self, intptr_t slot);
void KPageView_SuperMouseReleaseEvent(KPageView* self, QMouseEvent* event);
void KPageView_MouseDoubleClickEvent(KPageView* self, QMouseEvent* event);
void KPageView_OnMouseDoubleClickEvent(KPageView* self, intptr_t slot);
void KPageView_SuperMouseDoubleClickEvent(KPageView* self, QMouseEvent* event);
void KPageView_MouseMoveEvent(KPageView* self, QMouseEvent* event);
void KPageView_OnMouseMoveEvent(KPageView* self, intptr_t slot);
void KPageView_SuperMouseMoveEvent(KPageView* self, QMouseEvent* event);
void KPageView_WheelEvent(KPageView* self, QWheelEvent* event);
void KPageView_OnWheelEvent(KPageView* self, intptr_t slot);
void KPageView_SuperWheelEvent(KPageView* self, QWheelEvent* event);
void KPageView_KeyPressEvent(KPageView* self, QKeyEvent* event);
void KPageView_OnKeyPressEvent(KPageView* self, intptr_t slot);
void KPageView_SuperKeyPressEvent(KPageView* self, QKeyEvent* event);
void KPageView_KeyReleaseEvent(KPageView* self, QKeyEvent* event);
void KPageView_OnKeyReleaseEvent(KPageView* self, intptr_t slot);
void KPageView_SuperKeyReleaseEvent(KPageView* self, QKeyEvent* event);
void KPageView_FocusInEvent(KPageView* self, QFocusEvent* event);
void KPageView_OnFocusInEvent(KPageView* self, intptr_t slot);
void KPageView_SuperFocusInEvent(KPageView* self, QFocusEvent* event);
void KPageView_FocusOutEvent(KPageView* self, QFocusEvent* event);
void KPageView_OnFocusOutEvent(KPageView* self, intptr_t slot);
void KPageView_SuperFocusOutEvent(KPageView* self, QFocusEvent* event);
void KPageView_EnterEvent(KPageView* self, QEnterEvent* event);
void KPageView_OnEnterEvent(KPageView* self, intptr_t slot);
void KPageView_SuperEnterEvent(KPageView* self, QEnterEvent* event);
void KPageView_LeaveEvent(KPageView* self, QEvent* event);
void KPageView_OnLeaveEvent(KPageView* self, intptr_t slot);
void KPageView_SuperLeaveEvent(KPageView* self, QEvent* event);
void KPageView_PaintEvent(KPageView* self, QPaintEvent* event);
void KPageView_OnPaintEvent(KPageView* self, intptr_t slot);
void KPageView_SuperPaintEvent(KPageView* self, QPaintEvent* event);
void KPageView_MoveEvent(KPageView* self, QMoveEvent* event);
void KPageView_OnMoveEvent(KPageView* self, intptr_t slot);
void KPageView_SuperMoveEvent(KPageView* self, QMoveEvent* event);
void KPageView_ResizeEvent(KPageView* self, QResizeEvent* event);
void KPageView_OnResizeEvent(KPageView* self, intptr_t slot);
void KPageView_SuperResizeEvent(KPageView* self, QResizeEvent* event);
void KPageView_CloseEvent(KPageView* self, QCloseEvent* event);
void KPageView_OnCloseEvent(KPageView* self, intptr_t slot);
void KPageView_SuperCloseEvent(KPageView* self, QCloseEvent* event);
void KPageView_ContextMenuEvent(KPageView* self, QContextMenuEvent* event);
void KPageView_OnContextMenuEvent(KPageView* self, intptr_t slot);
void KPageView_SuperContextMenuEvent(KPageView* self, QContextMenuEvent* event);
void KPageView_TabletEvent(KPageView* self, QTabletEvent* event);
void KPageView_OnTabletEvent(KPageView* self, intptr_t slot);
void KPageView_SuperTabletEvent(KPageView* self, QTabletEvent* event);
void KPageView_ActionEvent(KPageView* self, QActionEvent* event);
void KPageView_OnActionEvent(KPageView* self, intptr_t slot);
void KPageView_SuperActionEvent(KPageView* self, QActionEvent* event);
void KPageView_DragEnterEvent(KPageView* self, QDragEnterEvent* event);
void KPageView_OnDragEnterEvent(KPageView* self, intptr_t slot);
void KPageView_SuperDragEnterEvent(KPageView* self, QDragEnterEvent* event);
void KPageView_DragMoveEvent(KPageView* self, QDragMoveEvent* event);
void KPageView_OnDragMoveEvent(KPageView* self, intptr_t slot);
void KPageView_SuperDragMoveEvent(KPageView* self, QDragMoveEvent* event);
void KPageView_DragLeaveEvent(KPageView* self, QDragLeaveEvent* event);
void KPageView_OnDragLeaveEvent(KPageView* self, intptr_t slot);
void KPageView_SuperDragLeaveEvent(KPageView* self, QDragLeaveEvent* event);
void KPageView_DropEvent(KPageView* self, QDropEvent* event);
void KPageView_OnDropEvent(KPageView* self, intptr_t slot);
void KPageView_SuperDropEvent(KPageView* self, QDropEvent* event);
void KPageView_ShowEvent(KPageView* self, QShowEvent* event);
void KPageView_OnShowEvent(KPageView* self, intptr_t slot);
void KPageView_SuperShowEvent(KPageView* self, QShowEvent* event);
void KPageView_HideEvent(KPageView* self, QHideEvent* event);
void KPageView_OnHideEvent(KPageView* self, intptr_t slot);
void KPageView_SuperHideEvent(KPageView* self, QHideEvent* event);
bool KPageView_NativeEvent(KPageView* self, const libqt_string eventType, void* message, intptr_t* result);
void KPageView_OnNativeEvent(KPageView* self, intptr_t slot);
bool KPageView_SuperNativeEvent(KPageView* self, const libqt_string eventType, void* message, intptr_t* result);
void KPageView_ChangeEvent(KPageView* self, QEvent* param1);
void KPageView_OnChangeEvent(KPageView* self, intptr_t slot);
void KPageView_SuperChangeEvent(KPageView* self, QEvent* param1);
int KPageView_Metric(const KPageView* self, int param1);
void KPageView_OnMetric(const KPageView* self, intptr_t slot);
int KPageView_SuperMetric(const KPageView* self, int param1);
void KPageView_InitPainter(const KPageView* self, QPainter* painter);
void KPageView_OnInitPainter(const KPageView* self, intptr_t slot);
void KPageView_SuperInitPainter(const KPageView* self, QPainter* painter);
QPaintDevice* KPageView_Redirected(const KPageView* self, QPoint* offset);
void KPageView_OnRedirected(const KPageView* self, intptr_t slot);
QPaintDevice* KPageView_SuperRedirected(const KPageView* self, QPoint* offset);
QPainter* KPageView_SharedPainter(const KPageView* self);
void KPageView_OnSharedPainter(const KPageView* self, intptr_t slot);
QPainter* KPageView_SuperSharedPainter(const KPageView* self);
void KPageView_InputMethodEvent(KPageView* self, QInputMethodEvent* param1);
void KPageView_OnInputMethodEvent(KPageView* self, intptr_t slot);
void KPageView_SuperInputMethodEvent(KPageView* self, QInputMethodEvent* param1);
QVariant* KPageView_InputMethodQuery(const KPageView* self, int param1);
void KPageView_OnInputMethodQuery(const KPageView* self, intptr_t slot);
QVariant* KPageView_SuperInputMethodQuery(const KPageView* self, int param1);
bool KPageView_FocusNextPrevChild(KPageView* self, bool next);
void KPageView_OnFocusNextPrevChild(KPageView* self, intptr_t slot);
bool KPageView_SuperFocusNextPrevChild(KPageView* self, bool next);
bool KPageView_EventFilter(KPageView* self, QObject* watched, QEvent* event);
void KPageView_OnEventFilter(KPageView* self, intptr_t slot);
bool KPageView_SuperEventFilter(KPageView* self, QObject* watched, QEvent* event);
void KPageView_TimerEvent(KPageView* self, QTimerEvent* event);
void KPageView_OnTimerEvent(KPageView* self, intptr_t slot);
void KPageView_SuperTimerEvent(KPageView* self, QTimerEvent* event);
void KPageView_ChildEvent(KPageView* self, QChildEvent* event);
void KPageView_OnChildEvent(KPageView* self, intptr_t slot);
void KPageView_SuperChildEvent(KPageView* self, QChildEvent* event);
void KPageView_CustomEvent(KPageView* self, QEvent* event);
void KPageView_OnCustomEvent(KPageView* self, intptr_t slot);
void KPageView_SuperCustomEvent(KPageView* self, QEvent* event);
void KPageView_ConnectNotify(KPageView* self, const QMetaMethod* signal);
void KPageView_OnConnectNotify(KPageView* self, intptr_t slot);
void KPageView_SuperConnectNotify(KPageView* self, const QMetaMethod* signal);
void KPageView_DisconnectNotify(KPageView* self, const QMetaMethod* signal);
void KPageView_OnDisconnectNotify(KPageView* self, intptr_t slot);
void KPageView_SuperDisconnectNotify(KPageView* self, const QMetaMethod* signal);
void KPageView_UpdateMicroFocus(KPageView* self);
void KPageView_OnUpdateMicroFocus(KPageView* self, intptr_t slot);
void KPageView_SuperUpdateMicroFocus(KPageView* self);
void KPageView_Create(KPageView* self);
void KPageView_OnCreate(KPageView* self, intptr_t slot);
void KPageView_SuperCreate(KPageView* self);
void KPageView_Destroy(KPageView* self);
void KPageView_OnDestroy(KPageView* self, intptr_t slot);
void KPageView_SuperDestroy(KPageView* self);
bool KPageView_FocusNextChild(KPageView* self);
void KPageView_OnFocusNextChild(KPageView* self, intptr_t slot);
bool KPageView_SuperFocusNextChild(KPageView* self);
bool KPageView_FocusPreviousChild(KPageView* self);
void KPageView_OnFocusPreviousChild(KPageView* self, intptr_t slot);
bool KPageView_SuperFocusPreviousChild(KPageView* self);
QObject* KPageView_Sender(const KPageView* self);
void KPageView_OnSender(const KPageView* self, intptr_t slot);
QObject* KPageView_SuperSender(const KPageView* self);
int KPageView_SenderSignalIndex(const KPageView* self);
void KPageView_OnSenderSignalIndex(const KPageView* self, intptr_t slot);
int KPageView_SuperSenderSignalIndex(const KPageView* self);
int KPageView_Receivers(const KPageView* self, const char* signal);
void KPageView_OnReceivers(const KPageView* self, intptr_t slot);
int KPageView_SuperReceivers(const KPageView* self, const char* signal);
bool KPageView_IsSignalConnected(const KPageView* self, const QMetaMethod* signal);
void KPageView_OnIsSignalConnected(const KPageView* self, intptr_t slot);
bool KPageView_SuperIsSignalConnected(const KPageView* self, const QMetaMethod* signal);
double KPageView_GetDecodedMetricF(const KPageView* self, int metricA, int metricB);
void KPageView_OnGetDecodedMetricF(const KPageView* self, intptr_t slot);
double KPageView_SuperGetDecodedMetricF(const KPageView* self, int metricA, int metricB);
void KPageView_Delete(KPageView* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
