#pragma once
#ifndef SRC_EXTRAS_KXMLGUIC_LIBKXMLGUIWINDOW_H
#define SRC_EXTRAS_KXMLGUIC_LIBKXMLGUIWINDOW_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KActionCollection KActionCollection;
typedef struct KConfig KConfig;
typedef struct KConfigGroup KConfigGroup;
typedef struct KMainWindow KMainWindow;
typedef struct KXMLGUIBuilder KXMLGUIBuilder;
typedef struct KXMLGUIClient KXMLGUIClient;
typedef struct KXMLGUIFactory KXMLGUIFactory;
typedef struct KXmlGuiWindow KXmlGuiWindow;
typedef struct QAction QAction;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDomDocument QDomDocument;
typedef struct QDomElement QDomElement;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMainWindow QMainWindow;
typedef struct QMenu QMenu;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KXmlGuiWindow* KXmlGuiWindow_new(QWidget* parent);
KXmlGuiWindow* KXmlGuiWindow_new2();
KXmlGuiWindow* KXmlGuiWindow_new3(QWidget* parent, int flags);
QMetaObject* KXmlGuiWindow_MetaObject(const KXmlGuiWindow* self);
void* KXmlGuiWindow_Metacast(KXmlGuiWindow* self, const char* param1);
int KXmlGuiWindow_Metacall(KXmlGuiWindow* self, int param1, int param2, void** param3);
void KXmlGuiWindow_SetHelpMenuEnabled(KXmlGuiWindow* self);
bool KXmlGuiWindow_IsHelpMenuEnabled(const KXmlGuiWindow* self);
KXMLGUIFactory* KXmlGuiWindow_GuiFactory(KXmlGuiWindow* self);
void KXmlGuiWindow_CreateGUI(KXmlGuiWindow* self);
void KXmlGuiWindow_SetStandardToolBarMenuEnabled(KXmlGuiWindow* self, bool showToolBarMenu);
bool KXmlGuiWindow_IsStandardToolBarMenuEnabled(const KXmlGuiWindow* self);
void KXmlGuiWindow_CreateStandardStatusBarAction(KXmlGuiWindow* self);
void KXmlGuiWindow_SetupGUI(KXmlGuiWindow* self);
void KXmlGuiWindow_SetupGUI2(KXmlGuiWindow* self, const QSize* defaultSize);
QAction* KXmlGuiWindow_ToolBarMenuAction(KXmlGuiWindow* self);
void KXmlGuiWindow_SetupToolbarMenuActions(KXmlGuiWindow* self);
libqt_list /* of libqt_string */ KXmlGuiWindow_ToolBarNames(const KXmlGuiWindow* self);
void KXmlGuiWindow_FinalizeGUI(KXmlGuiWindow* self, bool force);
void KXmlGuiWindow_ApplyMainWindowSettings(KXmlGuiWindow* self, const KConfigGroup* config);
void KXmlGuiWindow_SetCommandBarEnabled(KXmlGuiWindow* self, bool showCommandBar);
bool KXmlGuiWindow_IsCommandBarEnabled(const KXmlGuiWindow* self);
void KXmlGuiWindow_ConfigureToolbars(KXmlGuiWindow* self);
void KXmlGuiWindow_SlotStateChanged(KXmlGuiWindow* self, const libqt_string newstate);
void KXmlGuiWindow_SlotStateChanged2(KXmlGuiWindow* self, const libqt_string newstate, bool reverse);
bool KXmlGuiWindow_IsToolBarVisible(KXmlGuiWindow* self, const libqt_string name);
void KXmlGuiWindow_SetToolBarVisible(KXmlGuiWindow* self, const libqt_string name, bool visible);
bool KXmlGuiWindow_Event(KXmlGuiWindow* self, QEvent* event);
void KXmlGuiWindow_SaveNewToolbarConfig(KXmlGuiWindow* self);
void KXmlGuiWindow_SetHelpMenuEnabled1(KXmlGuiWindow* self, bool showHelpMenu);
void KXmlGuiWindow_CreateGUI1(KXmlGuiWindow* self, const libqt_string xmlfile);
void KXmlGuiWindow_SetupGUI1(KXmlGuiWindow* self, int options);
void KXmlGuiWindow_SetupGUI22(KXmlGuiWindow* self, int options, const libqt_string xmlfile);
void KXmlGuiWindow_SetupGUI23(KXmlGuiWindow* self, const QSize* defaultSize, int options);
void KXmlGuiWindow_SetupGUI3(KXmlGuiWindow* self, const QSize* defaultSize, int options, const libqt_string xmlfile);
void KXmlGuiWindow_OnMetaObject(const KXmlGuiWindow* self, intptr_t slot);
QMetaObject* KXmlGuiWindow_SuperMetaObject(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnMetacast(KXmlGuiWindow* self, intptr_t slot);
void* KXmlGuiWindow_SuperMetacast(KXmlGuiWindow* self, const char* param1);
void KXmlGuiWindow_OnMetacall(KXmlGuiWindow* self, intptr_t slot);
int KXmlGuiWindow_SuperMetacall(KXmlGuiWindow* self, int param1, int param2, void** param3);
void KXmlGuiWindow_OnGuiFactory(KXmlGuiWindow* self, intptr_t slot);
KXMLGUIFactory* KXmlGuiWindow_SuperGuiFactory(KXmlGuiWindow* self);
void KXmlGuiWindow_OnApplyMainWindowSettings(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperApplyMainWindowSettings(KXmlGuiWindow* self, const KConfigGroup* config);
void KXmlGuiWindow_OnConfigureToolbars(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperConfigureToolbars(KXmlGuiWindow* self);
void KXmlGuiWindow_OnSlotStateChanged(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSlotStateChanged(KXmlGuiWindow* self, const libqt_string newstate);
void KXmlGuiWindow_OnEvent(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperEvent(KXmlGuiWindow* self, QEvent* event);
void KXmlGuiWindow_OnSaveNewToolbarConfig(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSaveNewToolbarConfig(KXmlGuiWindow* self);
void KXmlGuiWindow_SetCaption(KXmlGuiWindow* self, const libqt_string caption);
void KXmlGuiWindow_OnSetCaption(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetCaption(KXmlGuiWindow* self, const libqt_string caption);
void KXmlGuiWindow_SetPlainCaption(KXmlGuiWindow* self, const libqt_string caption);
void KXmlGuiWindow_OnSetPlainCaption(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetPlainCaption(KXmlGuiWindow* self, const libqt_string caption);
void KXmlGuiWindow_KeyPressEvent(KXmlGuiWindow* self, QKeyEvent* keyEvent);
void KXmlGuiWindow_OnKeyPressEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperKeyPressEvent(KXmlGuiWindow* self, QKeyEvent* keyEvent);
void KXmlGuiWindow_CloseEvent(KXmlGuiWindow* self, QCloseEvent* param1);
void KXmlGuiWindow_OnCloseEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperCloseEvent(KXmlGuiWindow* self, QCloseEvent* param1);
bool KXmlGuiWindow_QueryClose(KXmlGuiWindow* self);
void KXmlGuiWindow_OnQueryClose(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperQueryClose(KXmlGuiWindow* self);
void KXmlGuiWindow_SaveProperties(KXmlGuiWindow* self, KConfigGroup* param1);
void KXmlGuiWindow_OnSaveProperties(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSaveProperties(KXmlGuiWindow* self, KConfigGroup* param1);
void KXmlGuiWindow_ReadProperties(KXmlGuiWindow* self, const KConfigGroup* param1);
void KXmlGuiWindow_OnReadProperties(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperReadProperties(KXmlGuiWindow* self, const KConfigGroup* param1);
void KXmlGuiWindow_SaveGlobalProperties(KXmlGuiWindow* self, KConfig* sessionConfig);
void KXmlGuiWindow_OnSaveGlobalProperties(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSaveGlobalProperties(KXmlGuiWindow* self, KConfig* sessionConfig);
void KXmlGuiWindow_ReadGlobalProperties(KXmlGuiWindow* self, KConfig* sessionConfig);
void KXmlGuiWindow_OnReadGlobalProperties(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperReadGlobalProperties(KXmlGuiWindow* self, KConfig* sessionConfig);
QMenu* KXmlGuiWindow_CreatePopupMenu(KXmlGuiWindow* self);
void KXmlGuiWindow_OnCreatePopupMenu(KXmlGuiWindow* self, intptr_t slot);
QMenu* KXmlGuiWindow_SuperCreatePopupMenu(KXmlGuiWindow* self);
void KXmlGuiWindow_ContextMenuEvent(KXmlGuiWindow* self, QContextMenuEvent* event);
void KXmlGuiWindow_OnContextMenuEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperContextMenuEvent(KXmlGuiWindow* self, QContextMenuEvent* event);
int KXmlGuiWindow_DevType(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnDevType(const KXmlGuiWindow* self, intptr_t slot);
int KXmlGuiWindow_SuperDevType(const KXmlGuiWindow* self);
void KXmlGuiWindow_SetVisible(KXmlGuiWindow* self, bool visible);
void KXmlGuiWindow_OnSetVisible(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetVisible(KXmlGuiWindow* self, bool visible);
QSize* KXmlGuiWindow_SizeHint(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnSizeHint(const KXmlGuiWindow* self, intptr_t slot);
QSize* KXmlGuiWindow_SuperSizeHint(const KXmlGuiWindow* self);
QSize* KXmlGuiWindow_MinimumSizeHint(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnMinimumSizeHint(const KXmlGuiWindow* self, intptr_t slot);
QSize* KXmlGuiWindow_SuperMinimumSizeHint(const KXmlGuiWindow* self);
int KXmlGuiWindow_HeightForWidth(const KXmlGuiWindow* self, int param1);
void KXmlGuiWindow_OnHeightForWidth(const KXmlGuiWindow* self, intptr_t slot);
int KXmlGuiWindow_SuperHeightForWidth(const KXmlGuiWindow* self, int param1);
bool KXmlGuiWindow_HasHeightForWidth(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnHasHeightForWidth(const KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperHasHeightForWidth(const KXmlGuiWindow* self);
QPaintEngine* KXmlGuiWindow_PaintEngine(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnPaintEngine(const KXmlGuiWindow* self, intptr_t slot);
QPaintEngine* KXmlGuiWindow_SuperPaintEngine(const KXmlGuiWindow* self);
void KXmlGuiWindow_MousePressEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_OnMousePressEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperMousePressEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_MouseReleaseEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_OnMouseReleaseEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperMouseReleaseEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_MouseDoubleClickEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_OnMouseDoubleClickEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperMouseDoubleClickEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_MouseMoveEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_OnMouseMoveEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperMouseMoveEvent(KXmlGuiWindow* self, QMouseEvent* event);
void KXmlGuiWindow_WheelEvent(KXmlGuiWindow* self, QWheelEvent* event);
void KXmlGuiWindow_OnWheelEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperWheelEvent(KXmlGuiWindow* self, QWheelEvent* event);
void KXmlGuiWindow_KeyReleaseEvent(KXmlGuiWindow* self, QKeyEvent* event);
void KXmlGuiWindow_OnKeyReleaseEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperKeyReleaseEvent(KXmlGuiWindow* self, QKeyEvent* event);
void KXmlGuiWindow_FocusInEvent(KXmlGuiWindow* self, QFocusEvent* event);
void KXmlGuiWindow_OnFocusInEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperFocusInEvent(KXmlGuiWindow* self, QFocusEvent* event);
void KXmlGuiWindow_FocusOutEvent(KXmlGuiWindow* self, QFocusEvent* event);
void KXmlGuiWindow_OnFocusOutEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperFocusOutEvent(KXmlGuiWindow* self, QFocusEvent* event);
void KXmlGuiWindow_EnterEvent(KXmlGuiWindow* self, QEnterEvent* event);
void KXmlGuiWindow_OnEnterEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperEnterEvent(KXmlGuiWindow* self, QEnterEvent* event);
void KXmlGuiWindow_LeaveEvent(KXmlGuiWindow* self, QEvent* event);
void KXmlGuiWindow_OnLeaveEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperLeaveEvent(KXmlGuiWindow* self, QEvent* event);
void KXmlGuiWindow_PaintEvent(KXmlGuiWindow* self, QPaintEvent* event);
void KXmlGuiWindow_OnPaintEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperPaintEvent(KXmlGuiWindow* self, QPaintEvent* event);
void KXmlGuiWindow_MoveEvent(KXmlGuiWindow* self, QMoveEvent* event);
void KXmlGuiWindow_OnMoveEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperMoveEvent(KXmlGuiWindow* self, QMoveEvent* event);
void KXmlGuiWindow_ResizeEvent(KXmlGuiWindow* self, QResizeEvent* event);
void KXmlGuiWindow_OnResizeEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperResizeEvent(KXmlGuiWindow* self, QResizeEvent* event);
void KXmlGuiWindow_TabletEvent(KXmlGuiWindow* self, QTabletEvent* event);
void KXmlGuiWindow_OnTabletEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperTabletEvent(KXmlGuiWindow* self, QTabletEvent* event);
void KXmlGuiWindow_ActionEvent(KXmlGuiWindow* self, QActionEvent* event);
void KXmlGuiWindow_OnActionEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperActionEvent(KXmlGuiWindow* self, QActionEvent* event);
void KXmlGuiWindow_DragEnterEvent(KXmlGuiWindow* self, QDragEnterEvent* event);
void KXmlGuiWindow_OnDragEnterEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperDragEnterEvent(KXmlGuiWindow* self, QDragEnterEvent* event);
void KXmlGuiWindow_DragMoveEvent(KXmlGuiWindow* self, QDragMoveEvent* event);
void KXmlGuiWindow_OnDragMoveEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperDragMoveEvent(KXmlGuiWindow* self, QDragMoveEvent* event);
void KXmlGuiWindow_DragLeaveEvent(KXmlGuiWindow* self, QDragLeaveEvent* event);
void KXmlGuiWindow_OnDragLeaveEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperDragLeaveEvent(KXmlGuiWindow* self, QDragLeaveEvent* event);
void KXmlGuiWindow_DropEvent(KXmlGuiWindow* self, QDropEvent* event);
void KXmlGuiWindow_OnDropEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperDropEvent(KXmlGuiWindow* self, QDropEvent* event);
void KXmlGuiWindow_ShowEvent(KXmlGuiWindow* self, QShowEvent* event);
void KXmlGuiWindow_OnShowEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperShowEvent(KXmlGuiWindow* self, QShowEvent* event);
void KXmlGuiWindow_HideEvent(KXmlGuiWindow* self, QHideEvent* event);
void KXmlGuiWindow_OnHideEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperHideEvent(KXmlGuiWindow* self, QHideEvent* event);
bool KXmlGuiWindow_NativeEvent(KXmlGuiWindow* self, const libqt_string eventType, void* message, intptr_t* result);
void KXmlGuiWindow_OnNativeEvent(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperNativeEvent(KXmlGuiWindow* self, const libqt_string eventType, void* message, intptr_t* result);
void KXmlGuiWindow_ChangeEvent(KXmlGuiWindow* self, QEvent* param1);
void KXmlGuiWindow_OnChangeEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperChangeEvent(KXmlGuiWindow* self, QEvent* param1);
int KXmlGuiWindow_Metric(const KXmlGuiWindow* self, int param1);
void KXmlGuiWindow_OnMetric(const KXmlGuiWindow* self, intptr_t slot);
int KXmlGuiWindow_SuperMetric(const KXmlGuiWindow* self, int param1);
void KXmlGuiWindow_InitPainter(const KXmlGuiWindow* self, QPainter* painter);
void KXmlGuiWindow_OnInitPainter(const KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperInitPainter(const KXmlGuiWindow* self, QPainter* painter);
QPaintDevice* KXmlGuiWindow_Redirected(const KXmlGuiWindow* self, QPoint* offset);
void KXmlGuiWindow_OnRedirected(const KXmlGuiWindow* self, intptr_t slot);
QPaintDevice* KXmlGuiWindow_SuperRedirected(const KXmlGuiWindow* self, QPoint* offset);
QPainter* KXmlGuiWindow_SharedPainter(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnSharedPainter(const KXmlGuiWindow* self, intptr_t slot);
QPainter* KXmlGuiWindow_SuperSharedPainter(const KXmlGuiWindow* self);
void KXmlGuiWindow_InputMethodEvent(KXmlGuiWindow* self, QInputMethodEvent* param1);
void KXmlGuiWindow_OnInputMethodEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperInputMethodEvent(KXmlGuiWindow* self, QInputMethodEvent* param1);
QVariant* KXmlGuiWindow_InputMethodQuery(const KXmlGuiWindow* self, int param1);
void KXmlGuiWindow_OnInputMethodQuery(const KXmlGuiWindow* self, intptr_t slot);
QVariant* KXmlGuiWindow_SuperInputMethodQuery(const KXmlGuiWindow* self, int param1);
bool KXmlGuiWindow_FocusNextPrevChild(KXmlGuiWindow* self, bool next);
void KXmlGuiWindow_OnFocusNextPrevChild(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperFocusNextPrevChild(KXmlGuiWindow* self, bool next);
bool KXmlGuiWindow_EventFilter(KXmlGuiWindow* self, QObject* watched, QEvent* event);
void KXmlGuiWindow_OnEventFilter(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperEventFilter(KXmlGuiWindow* self, QObject* watched, QEvent* event);
void KXmlGuiWindow_TimerEvent(KXmlGuiWindow* self, QTimerEvent* event);
void KXmlGuiWindow_OnTimerEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperTimerEvent(KXmlGuiWindow* self, QTimerEvent* event);
void KXmlGuiWindow_ChildEvent(KXmlGuiWindow* self, QChildEvent* event);
void KXmlGuiWindow_OnChildEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperChildEvent(KXmlGuiWindow* self, QChildEvent* event);
void KXmlGuiWindow_CustomEvent(KXmlGuiWindow* self, QEvent* event);
void KXmlGuiWindow_OnCustomEvent(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperCustomEvent(KXmlGuiWindow* self, QEvent* event);
void KXmlGuiWindow_ConnectNotify(KXmlGuiWindow* self, const QMetaMethod* signal);
void KXmlGuiWindow_OnConnectNotify(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperConnectNotify(KXmlGuiWindow* self, const QMetaMethod* signal);
void KXmlGuiWindow_DisconnectNotify(KXmlGuiWindow* self, const QMetaMethod* signal);
void KXmlGuiWindow_OnDisconnectNotify(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperDisconnectNotify(KXmlGuiWindow* self, const QMetaMethod* signal);
libqt_list /* of libqt_string */ KXmlGuiWindow_ContainerTags(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnContainerTags(const KXmlGuiWindow* self, intptr_t slot);
libqt_list /* of libqt_string */ KXmlGuiWindow_SuperContainerTags(const KXmlGuiWindow* self);
QWidget* KXmlGuiWindow_CreateContainer(KXmlGuiWindow* self, QWidget* parent, int index, const QDomElement* element, QAction** containerAction);
void KXmlGuiWindow_OnCreateContainer(KXmlGuiWindow* self, intptr_t slot);
QWidget* KXmlGuiWindow_SuperCreateContainer(KXmlGuiWindow* self, QWidget* parent, int index, const QDomElement* element, QAction** containerAction);
void KXmlGuiWindow_RemoveContainer(KXmlGuiWindow* self, QWidget* container, QWidget* parent, QDomElement* element, QAction* containerAction);
void KXmlGuiWindow_OnRemoveContainer(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperRemoveContainer(KXmlGuiWindow* self, QWidget* container, QWidget* parent, QDomElement* element, QAction* containerAction);
libqt_list /* of libqt_string */ KXmlGuiWindow_CustomTags(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnCustomTags(const KXmlGuiWindow* self, intptr_t slot);
libqt_list /* of libqt_string */ KXmlGuiWindow_SuperCustomTags(const KXmlGuiWindow* self);
QAction* KXmlGuiWindow_CreateCustomElement(KXmlGuiWindow* self, QWidget* parent, int index, const QDomElement* element);
void KXmlGuiWindow_OnCreateCustomElement(KXmlGuiWindow* self, intptr_t slot);
QAction* KXmlGuiWindow_SuperCreateCustomElement(KXmlGuiWindow* self, QWidget* parent, int index, const QDomElement* element);
QAction* KXmlGuiWindow_Action2(const KXmlGuiWindow* self, const QDomElement* element);
void KXmlGuiWindow_OnAction2(const KXmlGuiWindow* self, intptr_t slot);
QAction* KXmlGuiWindow_SuperAction2(const KXmlGuiWindow* self, const QDomElement* element);
KActionCollection* KXmlGuiWindow_ActionCollection(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnActionCollection(const KXmlGuiWindow* self, intptr_t slot);
KActionCollection* KXmlGuiWindow_SuperActionCollection(const KXmlGuiWindow* self);
libqt_string KXmlGuiWindow_ComponentName(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnComponentName(const KXmlGuiWindow* self, intptr_t slot);
libqt_string KXmlGuiWindow_SuperComponentName(const KXmlGuiWindow* self);
QDomDocument* KXmlGuiWindow_DomDocument(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnDomDocument(const KXmlGuiWindow* self, intptr_t slot);
QDomDocument* KXmlGuiWindow_SuperDomDocument(const KXmlGuiWindow* self);
libqt_string KXmlGuiWindow_XmlFile(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnXmlFile(const KXmlGuiWindow* self, intptr_t slot);
libqt_string KXmlGuiWindow_SuperXmlFile(const KXmlGuiWindow* self);
libqt_string KXmlGuiWindow_LocalXMLFile(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnLocalXMLFile(const KXmlGuiWindow* self, intptr_t slot);
libqt_string KXmlGuiWindow_SuperLocalXMLFile(const KXmlGuiWindow* self);
void KXmlGuiWindow_SetComponentName(KXmlGuiWindow* self, const libqt_string componentName, const libqt_string componentDisplayName);
void KXmlGuiWindow_OnSetComponentName(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetComponentName(KXmlGuiWindow* self, const libqt_string componentName, const libqt_string componentDisplayName);
void KXmlGuiWindow_SetXMLFile(KXmlGuiWindow* self, const libqt_string file, bool merge, bool setXMLDoc);
void KXmlGuiWindow_OnSetXMLFile(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetXMLFile(KXmlGuiWindow* self, const libqt_string file, bool merge, bool setXMLDoc);
void KXmlGuiWindow_SetLocalXMLFile(KXmlGuiWindow* self, const libqt_string file);
void KXmlGuiWindow_OnSetLocalXMLFile(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetLocalXMLFile(KXmlGuiWindow* self, const libqt_string file);
void KXmlGuiWindow_SetXML(KXmlGuiWindow* self, const libqt_string document, bool merge);
void KXmlGuiWindow_OnSetXML(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetXML(KXmlGuiWindow* self, const libqt_string document, bool merge);
void KXmlGuiWindow_SetDOMDocument(KXmlGuiWindow* self, const QDomDocument* document, bool merge);
void KXmlGuiWindow_OnSetDOMDocument(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSetDOMDocument(KXmlGuiWindow* self, const QDomDocument* document, bool merge);
void KXmlGuiWindow_StateChanged(KXmlGuiWindow* self, const libqt_string newstate, int reverse);
void KXmlGuiWindow_OnStateChanged(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperStateChanged(KXmlGuiWindow* self, const libqt_string newstate, int reverse);
void KXmlGuiWindow_CheckAmbiguousShortcuts(KXmlGuiWindow* self);
void KXmlGuiWindow_OnCheckAmbiguousShortcuts(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperCheckAmbiguousShortcuts(KXmlGuiWindow* self);
void KXmlGuiWindow_SavePropertiesInternal(KXmlGuiWindow* self, KConfig* param1, int param2);
void KXmlGuiWindow_OnSavePropertiesInternal(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSavePropertiesInternal(KXmlGuiWindow* self, KConfig* param1, int param2);
bool KXmlGuiWindow_ReadPropertiesInternal(KXmlGuiWindow* self, KConfig* param1, int param2);
void KXmlGuiWindow_OnReadPropertiesInternal(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperReadPropertiesInternal(KXmlGuiWindow* self, KConfig* param1, int param2);
bool KXmlGuiWindow_SettingsDirty(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnSettingsDirty(const KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperSettingsDirty(const KXmlGuiWindow* self);
void KXmlGuiWindow_SaveAutoSaveSettings(KXmlGuiWindow* self);
void KXmlGuiWindow_OnSaveAutoSaveSettings(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperSaveAutoSaveSettings(KXmlGuiWindow* self);
void KXmlGuiWindow_UpdateMicroFocus(KXmlGuiWindow* self);
void KXmlGuiWindow_OnUpdateMicroFocus(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperUpdateMicroFocus(KXmlGuiWindow* self);
void KXmlGuiWindow_Create(KXmlGuiWindow* self);
void KXmlGuiWindow_OnCreate(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperCreate(KXmlGuiWindow* self);
void KXmlGuiWindow_Destroy(KXmlGuiWindow* self);
void KXmlGuiWindow_OnDestroy(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperDestroy(KXmlGuiWindow* self);
bool KXmlGuiWindow_FocusNextChild(KXmlGuiWindow* self);
void KXmlGuiWindow_OnFocusNextChild(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperFocusNextChild(KXmlGuiWindow* self);
bool KXmlGuiWindow_FocusPreviousChild(KXmlGuiWindow* self);
void KXmlGuiWindow_OnFocusPreviousChild(KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperFocusPreviousChild(KXmlGuiWindow* self);
QObject* KXmlGuiWindow_Sender(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnSender(const KXmlGuiWindow* self, intptr_t slot);
QObject* KXmlGuiWindow_SuperSender(const KXmlGuiWindow* self);
int KXmlGuiWindow_SenderSignalIndex(const KXmlGuiWindow* self);
void KXmlGuiWindow_OnSenderSignalIndex(const KXmlGuiWindow* self, intptr_t slot);
int KXmlGuiWindow_SuperSenderSignalIndex(const KXmlGuiWindow* self);
int KXmlGuiWindow_Receivers(const KXmlGuiWindow* self, const char* signal);
void KXmlGuiWindow_OnReceivers(const KXmlGuiWindow* self, intptr_t slot);
int KXmlGuiWindow_SuperReceivers(const KXmlGuiWindow* self, const char* signal);
bool KXmlGuiWindow_IsSignalConnected(const KXmlGuiWindow* self, const QMetaMethod* signal);
void KXmlGuiWindow_OnIsSignalConnected(const KXmlGuiWindow* self, intptr_t slot);
bool KXmlGuiWindow_SuperIsSignalConnected(const KXmlGuiWindow* self, const QMetaMethod* signal);
double KXmlGuiWindow_GetDecodedMetricF(const KXmlGuiWindow* self, int metricA, int metricB);
void KXmlGuiWindow_OnGetDecodedMetricF(const KXmlGuiWindow* self, intptr_t slot);
double KXmlGuiWindow_SuperGetDecodedMetricF(const KXmlGuiWindow* self, int metricA, int metricB);
libqt_string KXmlGuiWindow_StandardsXmlFileLocation(KXmlGuiWindow* self);
void KXmlGuiWindow_OnStandardsXmlFileLocation(KXmlGuiWindow* self, intptr_t slot);
libqt_string KXmlGuiWindow_SuperStandardsXmlFileLocation(KXmlGuiWindow* self);
void KXmlGuiWindow_LoadStandardsXmlFile(KXmlGuiWindow* self);
void KXmlGuiWindow_OnLoadStandardsXmlFile(KXmlGuiWindow* self, intptr_t slot);
void KXmlGuiWindow_SuperLoadStandardsXmlFile(KXmlGuiWindow* self);
void KXmlGuiWindow_Delete(KXmlGuiWindow* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
