#pragma once
#ifndef SRC_OPENGLC_LIBQOPENGLVERSIONFUNCTIONS_H
#define SRC_OPENGLC_LIBQOPENGLVERSIONFUNCTIONS_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_0_CoreBackend__Functions)
typedef QOpenGLFunctions_1_0_CoreBackend::Functions QOpenGLFunctions_1_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_0_DeprecatedBackend::Functions QOpenGLFunctions_1_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_1_CoreBackend__Functions)
typedef QOpenGLFunctions_1_1_CoreBackend::Functions QOpenGLFunctions_1_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_1_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_1_DeprecatedBackend::Functions QOpenGLFunctions_1_1_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_2_CoreBackend__Functions)
typedef QOpenGLFunctions_1_2_CoreBackend::Functions QOpenGLFunctions_1_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_2_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_2_DeprecatedBackend::Functions QOpenGLFunctions_1_2_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_3_CoreBackend__Functions)
typedef QOpenGLFunctions_1_3_CoreBackend::Functions QOpenGLFunctions_1_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_3_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_3_DeprecatedBackend::Functions QOpenGLFunctions_1_3_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_4_CoreBackend__Functions)
typedef QOpenGLFunctions_1_4_CoreBackend::Functions QOpenGLFunctions_1_4_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_4_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_1_4_DeprecatedBackend::Functions QOpenGLFunctions_1_4_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_1_5_CoreBackend__Functions)
typedef QOpenGLFunctions_1_5_CoreBackend::Functions QOpenGLFunctions_1_5_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_0_CoreBackend__Functions)
typedef QOpenGLFunctions_2_0_CoreBackend::Functions QOpenGLFunctions_2_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_2_0_DeprecatedBackend::Functions QOpenGLFunctions_2_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_2_1_CoreBackend__Functions)
typedef QOpenGLFunctions_2_1_CoreBackend::Functions QOpenGLFunctions_2_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_0_CoreBackend__Functions)
typedef QOpenGLFunctions_3_0_CoreBackend::Functions QOpenGLFunctions_3_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_0_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_3_0_DeprecatedBackend::Functions QOpenGLFunctions_3_0_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_1_CoreBackend__Functions)
typedef QOpenGLFunctions_3_1_CoreBackend::Functions QOpenGLFunctions_3_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_2_CoreBackend__Functions)
typedef QOpenGLFunctions_3_2_CoreBackend::Functions QOpenGLFunctions_3_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_3_CoreBackend__Functions)
typedef QOpenGLFunctions_3_3_CoreBackend::Functions QOpenGLFunctions_3_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_3_3_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_3_3_DeprecatedBackend::Functions QOpenGLFunctions_3_3_DeprecatedBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_0_CoreBackend__Functions)
typedef QOpenGLFunctions_4_0_CoreBackend::Functions QOpenGLFunctions_4_0_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_1_CoreBackend__Functions)
typedef QOpenGLFunctions_4_1_CoreBackend::Functions QOpenGLFunctions_4_1_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_2_CoreBackend__Functions)
typedef QOpenGLFunctions_4_2_CoreBackend::Functions QOpenGLFunctions_4_2_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_3_CoreBackend__Functions)
typedef QOpenGLFunctions_4_3_CoreBackend::Functions QOpenGLFunctions_4_3_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_4_CoreBackend__Functions)
typedef QOpenGLFunctions_4_4_CoreBackend::Functions QOpenGLFunctions_4_4_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_5_CoreBackend__Functions)
typedef QOpenGLFunctions_4_5_CoreBackend::Functions QOpenGLFunctions_4_5_CoreBackend__Functions;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QOpenGLFunctions_4_5_DeprecatedBackend__Functions)
typedef QOpenGLFunctions_4_5_DeprecatedBackend::Functions QOpenGLFunctions_4_5_DeprecatedBackend__Functions;
#endif
#else
typedef struct QAbstractOpenGLFunctions QAbstractOpenGLFunctions;
typedef struct QOpenGLContext QOpenGLContext;
typedef struct QOpenGLFunctions_1_0_CoreBackend QOpenGLFunctions_1_0_CoreBackend;
typedef struct QOpenGLFunctions_1_0_CoreBackend__Functions QOpenGLFunctions_1_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_0_DeprecatedBackend QOpenGLFunctions_1_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_0_DeprecatedBackend__Functions QOpenGLFunctions_1_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_1_CoreBackend QOpenGLFunctions_1_1_CoreBackend;
typedef struct QOpenGLFunctions_1_1_CoreBackend__Functions QOpenGLFunctions_1_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_1_DeprecatedBackend QOpenGLFunctions_1_1_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_1_DeprecatedBackend__Functions QOpenGLFunctions_1_1_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_2_CoreBackend QOpenGLFunctions_1_2_CoreBackend;
typedef struct QOpenGLFunctions_1_2_CoreBackend__Functions QOpenGLFunctions_1_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_2_DeprecatedBackend QOpenGLFunctions_1_2_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_2_DeprecatedBackend__Functions QOpenGLFunctions_1_2_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_3_CoreBackend QOpenGLFunctions_1_3_CoreBackend;
typedef struct QOpenGLFunctions_1_3_CoreBackend__Functions QOpenGLFunctions_1_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_3_DeprecatedBackend QOpenGLFunctions_1_3_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_3_DeprecatedBackend__Functions QOpenGLFunctions_1_3_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_4_CoreBackend QOpenGLFunctions_1_4_CoreBackend;
typedef struct QOpenGLFunctions_1_4_CoreBackend__Functions QOpenGLFunctions_1_4_CoreBackend__Functions;
typedef struct QOpenGLFunctions_1_4_DeprecatedBackend QOpenGLFunctions_1_4_DeprecatedBackend;
typedef struct QOpenGLFunctions_1_4_DeprecatedBackend__Functions QOpenGLFunctions_1_4_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_1_5_CoreBackend QOpenGLFunctions_1_5_CoreBackend;
typedef struct QOpenGLFunctions_1_5_CoreBackend__Functions QOpenGLFunctions_1_5_CoreBackend__Functions;
typedef struct QOpenGLFunctions_2_0_CoreBackend QOpenGLFunctions_2_0_CoreBackend;
typedef struct QOpenGLFunctions_2_0_CoreBackend__Functions QOpenGLFunctions_2_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_2_0_DeprecatedBackend QOpenGLFunctions_2_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_2_0_DeprecatedBackend__Functions QOpenGLFunctions_2_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_2_1_CoreBackend QOpenGLFunctions_2_1_CoreBackend;
typedef struct QOpenGLFunctions_2_1_CoreBackend__Functions QOpenGLFunctions_2_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_0_CoreBackend QOpenGLFunctions_3_0_CoreBackend;
typedef struct QOpenGLFunctions_3_0_CoreBackend__Functions QOpenGLFunctions_3_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_0_DeprecatedBackend QOpenGLFunctions_3_0_DeprecatedBackend;
typedef struct QOpenGLFunctions_3_0_DeprecatedBackend__Functions QOpenGLFunctions_3_0_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_3_1_CoreBackend QOpenGLFunctions_3_1_CoreBackend;
typedef struct QOpenGLFunctions_3_1_CoreBackend__Functions QOpenGLFunctions_3_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_2_CoreBackend QOpenGLFunctions_3_2_CoreBackend;
typedef struct QOpenGLFunctions_3_2_CoreBackend__Functions QOpenGLFunctions_3_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_3_CoreBackend QOpenGLFunctions_3_3_CoreBackend;
typedef struct QOpenGLFunctions_3_3_CoreBackend__Functions QOpenGLFunctions_3_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_3_3_DeprecatedBackend QOpenGLFunctions_3_3_DeprecatedBackend;
typedef struct QOpenGLFunctions_3_3_DeprecatedBackend__Functions QOpenGLFunctions_3_3_DeprecatedBackend__Functions;
typedef struct QOpenGLFunctions_4_0_CoreBackend QOpenGLFunctions_4_0_CoreBackend;
typedef struct QOpenGLFunctions_4_0_CoreBackend__Functions QOpenGLFunctions_4_0_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_1_CoreBackend QOpenGLFunctions_4_1_CoreBackend;
typedef struct QOpenGLFunctions_4_1_CoreBackend__Functions QOpenGLFunctions_4_1_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_2_CoreBackend QOpenGLFunctions_4_2_CoreBackend;
typedef struct QOpenGLFunctions_4_2_CoreBackend__Functions QOpenGLFunctions_4_2_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_3_CoreBackend QOpenGLFunctions_4_3_CoreBackend;
typedef struct QOpenGLFunctions_4_3_CoreBackend__Functions QOpenGLFunctions_4_3_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_4_CoreBackend QOpenGLFunctions_4_4_CoreBackend;
typedef struct QOpenGLFunctions_4_4_CoreBackend__Functions QOpenGLFunctions_4_4_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_5_CoreBackend QOpenGLFunctions_4_5_CoreBackend;
typedef struct QOpenGLFunctions_4_5_CoreBackend__Functions QOpenGLFunctions_4_5_CoreBackend__Functions;
typedef struct QOpenGLFunctions_4_5_DeprecatedBackend QOpenGLFunctions_4_5_DeprecatedBackend;
typedef struct QOpenGLFunctions_4_5_DeprecatedBackend__Functions QOpenGLFunctions_4_5_DeprecatedBackend__Functions;
typedef struct QOpenGLVersionFunctionsBackend QOpenGLVersionFunctionsBackend;
typedef struct QOpenGLVersionFunctionsStorage QOpenGLVersionFunctionsStorage;
typedef struct QOpenGLVersionStatus QOpenGLVersionStatus;
#endif

struct pair_int_int;

typedef struct pair_int_int pair_int_int;

#ifndef PAIR_INT_INT
#define PAIR_INT_INT
struct pair_int_int {
    int first;
    int second;
};
#endif

QOpenGLVersionStatus* QOpenGLVersionStatus_new(const QOpenGLVersionStatus* other);
QOpenGLVersionStatus* QOpenGLVersionStatus_new2(QOpenGLVersionStatus* other);
QOpenGLVersionStatus* QOpenGLVersionStatus_new3();
QOpenGLVersionStatus* QOpenGLVersionStatus_new4(int majorVersion, int minorVersion, int functionStatus);
QOpenGLVersionStatus* QOpenGLVersionStatus_new5(const QOpenGLVersionStatus* param1);
pair_int_int /* tuple of int and int */ QOpenGLVersionStatus_Version(const QOpenGLVersionStatus* self);
void QOpenGLVersionStatus_SetVersion(QOpenGLVersionStatus* self, pair_int_int /* tuple of int and int */ version);
int QOpenGLVersionStatus_Status(const QOpenGLVersionStatus* self);
void QOpenGLVersionStatus_SetStatus(QOpenGLVersionStatus* self, int status);
void QOpenGLVersionStatus_OperatorAssign(QOpenGLVersionStatus* self, const QOpenGLVersionStatus* param1);
void QOpenGLVersionStatus_Delete(QOpenGLVersionStatus* self);

QOpenGLContext* QOpenGLVersionFunctionsBackend_Context(const QOpenGLVersionFunctionsBackend* self);
void QOpenGLVersionFunctionsBackend_SetContext(QOpenGLVersionFunctionsBackend* self, QOpenGLContext* context);
void QOpenGLVersionFunctionsBackend_Delete(QOpenGLVersionFunctionsBackend* self);

QOpenGLVersionFunctionsBackend** QOpenGLVersionFunctionsStorage_Backends(const QOpenGLVersionFunctionsStorage* self);
void QOpenGLVersionFunctionsStorage_SetBackends(QOpenGLVersionFunctionsStorage* self, QOpenGLVersionFunctionsBackend** backends);
void QOpenGLVersionFunctionsStorage_Delete(QOpenGLVersionFunctionsStorage* self);

bool QAbstractOpenGLFunctions_InitializeOpenGLFunctions(QAbstractOpenGLFunctions* self);
void QAbstractOpenGLFunctions_Delete(QAbstractOpenGLFunctions* self);

intptr_t QOpenGLFunctions_1_0_CoreBackend__Functions_IsEnabled(const QOpenGLFunctions_1_0_CoreBackend__Functions* self);
void QOpenGLFunctions_1_0_CoreBackend__Functions_SetIsEnabled(QOpenGLFunctions_1_0_CoreBackend__Functions* self, intptr_t isEnabled);
void QOpenGLFunctions_1_0_CoreBackend__Functions_Delete(QOpenGLFunctions_1_0_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_1_1_CoreBackend__Functions_IsTexture(const QOpenGLFunctions_1_1_CoreBackend__Functions* self);
void QOpenGLFunctions_1_1_CoreBackend__Functions_SetIsTexture(QOpenGLFunctions_1_1_CoreBackend__Functions* self, intptr_t isTexture);
void QOpenGLFunctions_1_1_CoreBackend__Functions_Delete(QOpenGLFunctions_1_1_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_1_5_CoreBackend__Functions_UnmapBuffer(const QOpenGLFunctions_1_5_CoreBackend__Functions* self);
void QOpenGLFunctions_1_5_CoreBackend__Functions_SetUnmapBuffer(QOpenGLFunctions_1_5_CoreBackend__Functions* self, intptr_t unmapBuffer);
intptr_t QOpenGLFunctions_1_5_CoreBackend__Functions_IsBuffer(const QOpenGLFunctions_1_5_CoreBackend__Functions* self);
void QOpenGLFunctions_1_5_CoreBackend__Functions_SetIsBuffer(QOpenGLFunctions_1_5_CoreBackend__Functions* self, intptr_t isBuffer);
intptr_t QOpenGLFunctions_1_5_CoreBackend__Functions_IsQuery(const QOpenGLFunctions_1_5_CoreBackend__Functions* self);
void QOpenGLFunctions_1_5_CoreBackend__Functions_SetIsQuery(QOpenGLFunctions_1_5_CoreBackend__Functions* self, intptr_t isQuery);
void QOpenGLFunctions_1_5_CoreBackend__Functions_Delete(QOpenGLFunctions_1_5_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_2_0_CoreBackend__Functions_IsShader(const QOpenGLFunctions_2_0_CoreBackend__Functions* self);
void QOpenGLFunctions_2_0_CoreBackend__Functions_SetIsShader(QOpenGLFunctions_2_0_CoreBackend__Functions* self, intptr_t isShader);
intptr_t QOpenGLFunctions_2_0_CoreBackend__Functions_IsProgram(const QOpenGLFunctions_2_0_CoreBackend__Functions* self);
void QOpenGLFunctions_2_0_CoreBackend__Functions_SetIsProgram(QOpenGLFunctions_2_0_CoreBackend__Functions* self, intptr_t isProgram);
intptr_t QOpenGLFunctions_2_0_CoreBackend__Functions_CreateShader(const QOpenGLFunctions_2_0_CoreBackend__Functions* self);
void QOpenGLFunctions_2_0_CoreBackend__Functions_SetCreateShader(QOpenGLFunctions_2_0_CoreBackend__Functions* self, intptr_t createShader);
intptr_t QOpenGLFunctions_2_0_CoreBackend__Functions_CreateProgram(const QOpenGLFunctions_2_0_CoreBackend__Functions* self);
void QOpenGLFunctions_2_0_CoreBackend__Functions_SetCreateProgram(QOpenGLFunctions_2_0_CoreBackend__Functions* self, intptr_t createProgram);
void QOpenGLFunctions_2_0_CoreBackend__Functions_Delete(QOpenGLFunctions_2_0_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_3_0_CoreBackend__Functions_IsVertexArray(const QOpenGLFunctions_3_0_CoreBackend__Functions* self);
void QOpenGLFunctions_3_0_CoreBackend__Functions_SetIsVertexArray(QOpenGLFunctions_3_0_CoreBackend__Functions* self, intptr_t isVertexArray);
intptr_t QOpenGLFunctions_3_0_CoreBackend__Functions_IsFramebuffer(const QOpenGLFunctions_3_0_CoreBackend__Functions* self);
void QOpenGLFunctions_3_0_CoreBackend__Functions_SetIsFramebuffer(QOpenGLFunctions_3_0_CoreBackend__Functions* self, intptr_t isFramebuffer);
intptr_t QOpenGLFunctions_3_0_CoreBackend__Functions_IsRenderbuffer(const QOpenGLFunctions_3_0_CoreBackend__Functions* self);
void QOpenGLFunctions_3_0_CoreBackend__Functions_SetIsRenderbuffer(QOpenGLFunctions_3_0_CoreBackend__Functions* self, intptr_t isRenderbuffer);
intptr_t QOpenGLFunctions_3_0_CoreBackend__Functions_IsEnabledi(const QOpenGLFunctions_3_0_CoreBackend__Functions* self);
void QOpenGLFunctions_3_0_CoreBackend__Functions_SetIsEnabledi(QOpenGLFunctions_3_0_CoreBackend__Functions* self, intptr_t isEnabledi);
void QOpenGLFunctions_3_0_CoreBackend__Functions_Delete(QOpenGLFunctions_3_0_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_3_3_CoreBackend__Functions_IsSampler(const QOpenGLFunctions_3_3_CoreBackend__Functions* self);
void QOpenGLFunctions_3_3_CoreBackend__Functions_SetIsSampler(QOpenGLFunctions_3_3_CoreBackend__Functions* self, intptr_t isSampler);
void QOpenGLFunctions_3_3_CoreBackend__Functions_Delete(QOpenGLFunctions_3_3_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_4_0_CoreBackend__Functions_IsTransformFeedback(const QOpenGLFunctions_4_0_CoreBackend__Functions* self);
void QOpenGLFunctions_4_0_CoreBackend__Functions_SetIsTransformFeedback(QOpenGLFunctions_4_0_CoreBackend__Functions* self, intptr_t isTransformFeedback);
void QOpenGLFunctions_4_0_CoreBackend__Functions_Delete(QOpenGLFunctions_4_0_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_4_1_CoreBackend__Functions_IsProgramPipeline(const QOpenGLFunctions_4_1_CoreBackend__Functions* self);
void QOpenGLFunctions_4_1_CoreBackend__Functions_SetIsProgramPipeline(QOpenGLFunctions_4_1_CoreBackend__Functions* self, intptr_t isProgramPipeline);
void QOpenGLFunctions_4_1_CoreBackend__Functions_Delete(QOpenGLFunctions_4_1_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_4_5_CoreBackend__Functions_UnmapNamedBuffer(const QOpenGLFunctions_4_5_CoreBackend__Functions* self);
void QOpenGLFunctions_4_5_CoreBackend__Functions_SetUnmapNamedBuffer(QOpenGLFunctions_4_5_CoreBackend__Functions* self, intptr_t unmapNamedBuffer);
void QOpenGLFunctions_4_5_CoreBackend__Functions_Delete(QOpenGLFunctions_4_5_CoreBackend__Functions* self);

intptr_t QOpenGLFunctions_1_0_DeprecatedBackend__Functions_IsList(const QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self);
void QOpenGLFunctions_1_0_DeprecatedBackend__Functions_SetIsList(QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self, intptr_t isList);
intptr_t QOpenGLFunctions_1_0_DeprecatedBackend__Functions_RenderMode(const QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self);
void QOpenGLFunctions_1_0_DeprecatedBackend__Functions_SetRenderMode(QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self, intptr_t renderMode);
intptr_t QOpenGLFunctions_1_0_DeprecatedBackend__Functions_GenLists(const QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self);
void QOpenGLFunctions_1_0_DeprecatedBackend__Functions_SetGenLists(QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self, intptr_t genLists);
void QOpenGLFunctions_1_0_DeprecatedBackend__Functions_Delete(QOpenGLFunctions_1_0_DeprecatedBackend__Functions* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
