#pragma once
#ifndef SRCC_LIBQGRAPHICSEFFECT_H
#define SRCC_LIBQGRAPHICSEFFECT_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QColor QColor;
typedef struct QEvent QEvent;
typedef struct QGraphicsBlurEffect QGraphicsBlurEffect;
typedef struct QGraphicsColorizeEffect QGraphicsColorizeEffect;
typedef struct QGraphicsDropShadowEffect QGraphicsDropShadowEffect;
typedef struct QGraphicsEffect QGraphicsEffect;
typedef struct QGraphicsOpacityEffect QGraphicsOpacityEffect;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QTimerEvent QTimerEvent;
#endif

QGraphicsEffect* QGraphicsEffect_new();
QGraphicsEffect* QGraphicsEffect_new2(QObject* parent);
QMetaObject* QGraphicsEffect_MetaObject(const QGraphicsEffect* self);
void* QGraphicsEffect_Metacast(QGraphicsEffect* self, const char* param1);
int QGraphicsEffect_Metacall(QGraphicsEffect* self, int param1, int param2, void** param3);
QRectF* QGraphicsEffect_BoundingRectFor(const QGraphicsEffect* self, const QRectF* sourceRect);
QRectF* QGraphicsEffect_BoundingRect(const QGraphicsEffect* self);
bool QGraphicsEffect_IsEnabled(const QGraphicsEffect* self);
void QGraphicsEffect_SetEnabled(QGraphicsEffect* self, bool enable);
void QGraphicsEffect_Update(QGraphicsEffect* self);
void QGraphicsEffect_EnabledChanged(QGraphicsEffect* self, bool enabled);
void QGraphicsEffect_Connect_EnabledChanged(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_Draw(QGraphicsEffect* self, QPainter* painter);
void QGraphicsEffect_SourceChanged(QGraphicsEffect* self, int flags);
void QGraphicsEffect_OnMetaObject(const QGraphicsEffect* self, intptr_t slot);
QMetaObject* QGraphicsEffect_SuperMetaObject(const QGraphicsEffect* self);
void QGraphicsEffect_OnMetacast(QGraphicsEffect* self, intptr_t slot);
void* QGraphicsEffect_SuperMetacast(QGraphicsEffect* self, const char* param1);
void QGraphicsEffect_OnMetacall(QGraphicsEffect* self, intptr_t slot);
int QGraphicsEffect_SuperMetacall(QGraphicsEffect* self, int param1, int param2, void** param3);
void QGraphicsEffect_OnBoundingRectFor(const QGraphicsEffect* self, intptr_t slot);
QRectF* QGraphicsEffect_SuperBoundingRectFor(const QGraphicsEffect* self, const QRectF* sourceRect);
void QGraphicsEffect_OnDraw(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperDraw(QGraphicsEffect* self, QPainter* painter);
void QGraphicsEffect_OnSourceChanged(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperSourceChanged(QGraphicsEffect* self, int flags);
bool QGraphicsEffect_Event(QGraphicsEffect* self, QEvent* event);
void QGraphicsEffect_OnEvent(QGraphicsEffect* self, intptr_t slot);
bool QGraphicsEffect_SuperEvent(QGraphicsEffect* self, QEvent* event);
bool QGraphicsEffect_EventFilter(QGraphicsEffect* self, QObject* watched, QEvent* event);
void QGraphicsEffect_OnEventFilter(QGraphicsEffect* self, intptr_t slot);
bool QGraphicsEffect_SuperEventFilter(QGraphicsEffect* self, QObject* watched, QEvent* event);
void QGraphicsEffect_TimerEvent(QGraphicsEffect* self, QTimerEvent* event);
void QGraphicsEffect_OnTimerEvent(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperTimerEvent(QGraphicsEffect* self, QTimerEvent* event);
void QGraphicsEffect_ChildEvent(QGraphicsEffect* self, QChildEvent* event);
void QGraphicsEffect_OnChildEvent(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperChildEvent(QGraphicsEffect* self, QChildEvent* event);
void QGraphicsEffect_CustomEvent(QGraphicsEffect* self, QEvent* event);
void QGraphicsEffect_OnCustomEvent(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperCustomEvent(QGraphicsEffect* self, QEvent* event);
void QGraphicsEffect_ConnectNotify(QGraphicsEffect* self, const QMetaMethod* signal);
void QGraphicsEffect_OnConnectNotify(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperConnectNotify(QGraphicsEffect* self, const QMetaMethod* signal);
void QGraphicsEffect_DisconnectNotify(QGraphicsEffect* self, const QMetaMethod* signal);
void QGraphicsEffect_OnDisconnectNotify(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperDisconnectNotify(QGraphicsEffect* self, const QMetaMethod* signal);
void QGraphicsEffect_UpdateBoundingRect(QGraphicsEffect* self);
void QGraphicsEffect_OnUpdateBoundingRect(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperUpdateBoundingRect(QGraphicsEffect* self);
bool QGraphicsEffect_SourceIsPixmap(const QGraphicsEffect* self);
void QGraphicsEffect_OnSourceIsPixmap(const QGraphicsEffect* self, intptr_t slot);
bool QGraphicsEffect_SuperSourceIsPixmap(const QGraphicsEffect* self);
QRectF* QGraphicsEffect_SourceBoundingRect(const QGraphicsEffect* self);
void QGraphicsEffect_OnSourceBoundingRect(const QGraphicsEffect* self, intptr_t slot);
QRectF* QGraphicsEffect_SuperSourceBoundingRect(const QGraphicsEffect* self);
void QGraphicsEffect_DrawSource(QGraphicsEffect* self, QPainter* painter);
void QGraphicsEffect_OnDrawSource(QGraphicsEffect* self, intptr_t slot);
void QGraphicsEffect_SuperDrawSource(QGraphicsEffect* self, QPainter* painter);
QPixmap* QGraphicsEffect_SourcePixmap(const QGraphicsEffect* self);
void QGraphicsEffect_OnSourcePixmap(const QGraphicsEffect* self, intptr_t slot);
QPixmap* QGraphicsEffect_SuperSourcePixmap(const QGraphicsEffect* self);
QRectF* QGraphicsEffect_SourceBoundingRect1(const QGraphicsEffect* self, int system);
void QGraphicsEffect_OnSourceBoundingRect1(const QGraphicsEffect* self, intptr_t slot);
QRectF* QGraphicsEffect_SuperSourceBoundingRect1(const QGraphicsEffect* self, int system);
QPixmap* QGraphicsEffect_SourcePixmap1(const QGraphicsEffect* self, int system);
void QGraphicsEffect_OnSourcePixmap1(const QGraphicsEffect* self, intptr_t slot);
QPixmap* QGraphicsEffect_SuperSourcePixmap1(const QGraphicsEffect* self, int system);
QPixmap* QGraphicsEffect_SourcePixmap2(const QGraphicsEffect* self, int system, QPoint* offset);
void QGraphicsEffect_OnSourcePixmap2(const QGraphicsEffect* self, intptr_t slot);
QPixmap* QGraphicsEffect_SuperSourcePixmap2(const QGraphicsEffect* self, int system, QPoint* offset);
QPixmap* QGraphicsEffect_SourcePixmap3(const QGraphicsEffect* self, int system, QPoint* offset, int mode);
void QGraphicsEffect_OnSourcePixmap3(const QGraphicsEffect* self, intptr_t slot);
QPixmap* QGraphicsEffect_SuperSourcePixmap3(const QGraphicsEffect* self, int system, QPoint* offset, int mode);
QObject* QGraphicsEffect_Sender(const QGraphicsEffect* self);
void QGraphicsEffect_OnSender(const QGraphicsEffect* self, intptr_t slot);
QObject* QGraphicsEffect_SuperSender(const QGraphicsEffect* self);
int QGraphicsEffect_SenderSignalIndex(const QGraphicsEffect* self);
void QGraphicsEffect_OnSenderSignalIndex(const QGraphicsEffect* self, intptr_t slot);
int QGraphicsEffect_SuperSenderSignalIndex(const QGraphicsEffect* self);
int QGraphicsEffect_Receivers(const QGraphicsEffect* self, const char* signal);
void QGraphicsEffect_OnReceivers(const QGraphicsEffect* self, intptr_t slot);
int QGraphicsEffect_SuperReceivers(const QGraphicsEffect* self, const char* signal);
bool QGraphicsEffect_IsSignalConnected(const QGraphicsEffect* self, const QMetaMethod* signal);
void QGraphicsEffect_OnIsSignalConnected(const QGraphicsEffect* self, intptr_t slot);
bool QGraphicsEffect_SuperIsSignalConnected(const QGraphicsEffect* self, const QMetaMethod* signal);
void QGraphicsEffect_Delete(QGraphicsEffect* self);

QGraphicsColorizeEffect* QGraphicsColorizeEffect_new();
QGraphicsColorizeEffect* QGraphicsColorizeEffect_new2(QObject* parent);
QMetaObject* QGraphicsColorizeEffect_MetaObject(const QGraphicsColorizeEffect* self);
void* QGraphicsColorizeEffect_Metacast(QGraphicsColorizeEffect* self, const char* param1);
int QGraphicsColorizeEffect_Metacall(QGraphicsColorizeEffect* self, int param1, int param2, void** param3);
QColor* QGraphicsColorizeEffect_Color(const QGraphicsColorizeEffect* self);
double QGraphicsColorizeEffect_Strength(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_SetColor(QGraphicsColorizeEffect* self, const QColor* c);
void QGraphicsColorizeEffect_SetStrength(QGraphicsColorizeEffect* self, double strength);
void QGraphicsColorizeEffect_ColorChanged(QGraphicsColorizeEffect* self, const QColor* color);
void QGraphicsColorizeEffect_Connect_ColorChanged(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_StrengthChanged(QGraphicsColorizeEffect* self, double strength);
void QGraphicsColorizeEffect_Connect_StrengthChanged(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_Draw(QGraphicsColorizeEffect* self, QPainter* painter);
void QGraphicsColorizeEffect_OnMetaObject(const QGraphicsColorizeEffect* self, intptr_t slot);
QMetaObject* QGraphicsColorizeEffect_SuperMetaObject(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnMetacast(QGraphicsColorizeEffect* self, intptr_t slot);
void* QGraphicsColorizeEffect_SuperMetacast(QGraphicsColorizeEffect* self, const char* param1);
void QGraphicsColorizeEffect_OnMetacall(QGraphicsColorizeEffect* self, intptr_t slot);
int QGraphicsColorizeEffect_SuperMetacall(QGraphicsColorizeEffect* self, int param1, int param2, void** param3);
void QGraphicsColorizeEffect_OnDraw(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperDraw(QGraphicsColorizeEffect* self, QPainter* painter);
QRectF* QGraphicsColorizeEffect_BoundingRectFor(const QGraphicsColorizeEffect* self, const QRectF* sourceRect);
void QGraphicsColorizeEffect_OnBoundingRectFor(const QGraphicsColorizeEffect* self, intptr_t slot);
QRectF* QGraphicsColorizeEffect_SuperBoundingRectFor(const QGraphicsColorizeEffect* self, const QRectF* sourceRect);
void QGraphicsColorizeEffect_SourceChanged(QGraphicsColorizeEffect* self, int flags);
void QGraphicsColorizeEffect_OnSourceChanged(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperSourceChanged(QGraphicsColorizeEffect* self, int flags);
bool QGraphicsColorizeEffect_Event(QGraphicsColorizeEffect* self, QEvent* event);
void QGraphicsColorizeEffect_OnEvent(QGraphicsColorizeEffect* self, intptr_t slot);
bool QGraphicsColorizeEffect_SuperEvent(QGraphicsColorizeEffect* self, QEvent* event);
bool QGraphicsColorizeEffect_EventFilter(QGraphicsColorizeEffect* self, QObject* watched, QEvent* event);
void QGraphicsColorizeEffect_OnEventFilter(QGraphicsColorizeEffect* self, intptr_t slot);
bool QGraphicsColorizeEffect_SuperEventFilter(QGraphicsColorizeEffect* self, QObject* watched, QEvent* event);
void QGraphicsColorizeEffect_TimerEvent(QGraphicsColorizeEffect* self, QTimerEvent* event);
void QGraphicsColorizeEffect_OnTimerEvent(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperTimerEvent(QGraphicsColorizeEffect* self, QTimerEvent* event);
void QGraphicsColorizeEffect_ChildEvent(QGraphicsColorizeEffect* self, QChildEvent* event);
void QGraphicsColorizeEffect_OnChildEvent(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperChildEvent(QGraphicsColorizeEffect* self, QChildEvent* event);
void QGraphicsColorizeEffect_CustomEvent(QGraphicsColorizeEffect* self, QEvent* event);
void QGraphicsColorizeEffect_OnCustomEvent(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperCustomEvent(QGraphicsColorizeEffect* self, QEvent* event);
void QGraphicsColorizeEffect_ConnectNotify(QGraphicsColorizeEffect* self, const QMetaMethod* signal);
void QGraphicsColorizeEffect_OnConnectNotify(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperConnectNotify(QGraphicsColorizeEffect* self, const QMetaMethod* signal);
void QGraphicsColorizeEffect_DisconnectNotify(QGraphicsColorizeEffect* self, const QMetaMethod* signal);
void QGraphicsColorizeEffect_OnDisconnectNotify(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperDisconnectNotify(QGraphicsColorizeEffect* self, const QMetaMethod* signal);
void QGraphicsColorizeEffect_UpdateBoundingRect(QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnUpdateBoundingRect(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperUpdateBoundingRect(QGraphicsColorizeEffect* self);
bool QGraphicsColorizeEffect_SourceIsPixmap(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnSourceIsPixmap(const QGraphicsColorizeEffect* self, intptr_t slot);
bool QGraphicsColorizeEffect_SuperSourceIsPixmap(const QGraphicsColorizeEffect* self);
QRectF* QGraphicsColorizeEffect_SourceBoundingRect(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnSourceBoundingRect(const QGraphicsColorizeEffect* self, intptr_t slot);
QRectF* QGraphicsColorizeEffect_SuperSourceBoundingRect(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_DrawSource(QGraphicsColorizeEffect* self, QPainter* painter);
void QGraphicsColorizeEffect_OnDrawSource(QGraphicsColorizeEffect* self, intptr_t slot);
void QGraphicsColorizeEffect_SuperDrawSource(QGraphicsColorizeEffect* self, QPainter* painter);
QPixmap* QGraphicsColorizeEffect_SourcePixmap(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnSourcePixmap(const QGraphicsColorizeEffect* self, intptr_t slot);
QPixmap* QGraphicsColorizeEffect_SuperSourcePixmap(const QGraphicsColorizeEffect* self);
QObject* QGraphicsColorizeEffect_Sender(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnSender(const QGraphicsColorizeEffect* self, intptr_t slot);
QObject* QGraphicsColorizeEffect_SuperSender(const QGraphicsColorizeEffect* self);
int QGraphicsColorizeEffect_SenderSignalIndex(const QGraphicsColorizeEffect* self);
void QGraphicsColorizeEffect_OnSenderSignalIndex(const QGraphicsColorizeEffect* self, intptr_t slot);
int QGraphicsColorizeEffect_SuperSenderSignalIndex(const QGraphicsColorizeEffect* self);
int QGraphicsColorizeEffect_Receivers(const QGraphicsColorizeEffect* self, const char* signal);
void QGraphicsColorizeEffect_OnReceivers(const QGraphicsColorizeEffect* self, intptr_t slot);
int QGraphicsColorizeEffect_SuperReceivers(const QGraphicsColorizeEffect* self, const char* signal);
bool QGraphicsColorizeEffect_IsSignalConnected(const QGraphicsColorizeEffect* self, const QMetaMethod* signal);
void QGraphicsColorizeEffect_OnIsSignalConnected(const QGraphicsColorizeEffect* self, intptr_t slot);
bool QGraphicsColorizeEffect_SuperIsSignalConnected(const QGraphicsColorizeEffect* self, const QMetaMethod* signal);
void QGraphicsColorizeEffect_Delete(QGraphicsColorizeEffect* self);

QGraphicsBlurEffect* QGraphicsBlurEffect_new();
QGraphicsBlurEffect* QGraphicsBlurEffect_new2(QObject* parent);
QMetaObject* QGraphicsBlurEffect_MetaObject(const QGraphicsBlurEffect* self);
void* QGraphicsBlurEffect_Metacast(QGraphicsBlurEffect* self, const char* param1);
int QGraphicsBlurEffect_Metacall(QGraphicsBlurEffect* self, int param1, int param2, void** param3);
QRectF* QGraphicsBlurEffect_BoundingRectFor(const QGraphicsBlurEffect* self, const QRectF* rect);
double QGraphicsBlurEffect_BlurRadius(const QGraphicsBlurEffect* self);
int QGraphicsBlurEffect_BlurHints(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_SetBlurRadius(QGraphicsBlurEffect* self, double blurRadius);
void QGraphicsBlurEffect_SetBlurHints(QGraphicsBlurEffect* self, int hints);
void QGraphicsBlurEffect_BlurRadiusChanged(QGraphicsBlurEffect* self, double blurRadius);
void QGraphicsBlurEffect_Connect_BlurRadiusChanged(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_BlurHintsChanged(QGraphicsBlurEffect* self, int hints);
void QGraphicsBlurEffect_Connect_BlurHintsChanged(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_Draw(QGraphicsBlurEffect* self, QPainter* painter);
void QGraphicsBlurEffect_OnMetaObject(const QGraphicsBlurEffect* self, intptr_t slot);
QMetaObject* QGraphicsBlurEffect_SuperMetaObject(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnMetacast(QGraphicsBlurEffect* self, intptr_t slot);
void* QGraphicsBlurEffect_SuperMetacast(QGraphicsBlurEffect* self, const char* param1);
void QGraphicsBlurEffect_OnMetacall(QGraphicsBlurEffect* self, intptr_t slot);
int QGraphicsBlurEffect_SuperMetacall(QGraphicsBlurEffect* self, int param1, int param2, void** param3);
void QGraphicsBlurEffect_OnBoundingRectFor(const QGraphicsBlurEffect* self, intptr_t slot);
QRectF* QGraphicsBlurEffect_SuperBoundingRectFor(const QGraphicsBlurEffect* self, const QRectF* rect);
void QGraphicsBlurEffect_OnDraw(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperDraw(QGraphicsBlurEffect* self, QPainter* painter);
void QGraphicsBlurEffect_SourceChanged(QGraphicsBlurEffect* self, int flags);
void QGraphicsBlurEffect_OnSourceChanged(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperSourceChanged(QGraphicsBlurEffect* self, int flags);
bool QGraphicsBlurEffect_Event(QGraphicsBlurEffect* self, QEvent* event);
void QGraphicsBlurEffect_OnEvent(QGraphicsBlurEffect* self, intptr_t slot);
bool QGraphicsBlurEffect_SuperEvent(QGraphicsBlurEffect* self, QEvent* event);
bool QGraphicsBlurEffect_EventFilter(QGraphicsBlurEffect* self, QObject* watched, QEvent* event);
void QGraphicsBlurEffect_OnEventFilter(QGraphicsBlurEffect* self, intptr_t slot);
bool QGraphicsBlurEffect_SuperEventFilter(QGraphicsBlurEffect* self, QObject* watched, QEvent* event);
void QGraphicsBlurEffect_TimerEvent(QGraphicsBlurEffect* self, QTimerEvent* event);
void QGraphicsBlurEffect_OnTimerEvent(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperTimerEvent(QGraphicsBlurEffect* self, QTimerEvent* event);
void QGraphicsBlurEffect_ChildEvent(QGraphicsBlurEffect* self, QChildEvent* event);
void QGraphicsBlurEffect_OnChildEvent(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperChildEvent(QGraphicsBlurEffect* self, QChildEvent* event);
void QGraphicsBlurEffect_CustomEvent(QGraphicsBlurEffect* self, QEvent* event);
void QGraphicsBlurEffect_OnCustomEvent(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperCustomEvent(QGraphicsBlurEffect* self, QEvent* event);
void QGraphicsBlurEffect_ConnectNotify(QGraphicsBlurEffect* self, const QMetaMethod* signal);
void QGraphicsBlurEffect_OnConnectNotify(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperConnectNotify(QGraphicsBlurEffect* self, const QMetaMethod* signal);
void QGraphicsBlurEffect_DisconnectNotify(QGraphicsBlurEffect* self, const QMetaMethod* signal);
void QGraphicsBlurEffect_OnDisconnectNotify(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperDisconnectNotify(QGraphicsBlurEffect* self, const QMetaMethod* signal);
void QGraphicsBlurEffect_UpdateBoundingRect(QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnUpdateBoundingRect(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperUpdateBoundingRect(QGraphicsBlurEffect* self);
bool QGraphicsBlurEffect_SourceIsPixmap(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnSourceIsPixmap(const QGraphicsBlurEffect* self, intptr_t slot);
bool QGraphicsBlurEffect_SuperSourceIsPixmap(const QGraphicsBlurEffect* self);
QRectF* QGraphicsBlurEffect_SourceBoundingRect(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnSourceBoundingRect(const QGraphicsBlurEffect* self, intptr_t slot);
QRectF* QGraphicsBlurEffect_SuperSourceBoundingRect(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_DrawSource(QGraphicsBlurEffect* self, QPainter* painter);
void QGraphicsBlurEffect_OnDrawSource(QGraphicsBlurEffect* self, intptr_t slot);
void QGraphicsBlurEffect_SuperDrawSource(QGraphicsBlurEffect* self, QPainter* painter);
QPixmap* QGraphicsBlurEffect_SourcePixmap(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnSourcePixmap(const QGraphicsBlurEffect* self, intptr_t slot);
QPixmap* QGraphicsBlurEffect_SuperSourcePixmap(const QGraphicsBlurEffect* self);
QObject* QGraphicsBlurEffect_Sender(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnSender(const QGraphicsBlurEffect* self, intptr_t slot);
QObject* QGraphicsBlurEffect_SuperSender(const QGraphicsBlurEffect* self);
int QGraphicsBlurEffect_SenderSignalIndex(const QGraphicsBlurEffect* self);
void QGraphicsBlurEffect_OnSenderSignalIndex(const QGraphicsBlurEffect* self, intptr_t slot);
int QGraphicsBlurEffect_SuperSenderSignalIndex(const QGraphicsBlurEffect* self);
int QGraphicsBlurEffect_Receivers(const QGraphicsBlurEffect* self, const char* signal);
void QGraphicsBlurEffect_OnReceivers(const QGraphicsBlurEffect* self, intptr_t slot);
int QGraphicsBlurEffect_SuperReceivers(const QGraphicsBlurEffect* self, const char* signal);
bool QGraphicsBlurEffect_IsSignalConnected(const QGraphicsBlurEffect* self, const QMetaMethod* signal);
void QGraphicsBlurEffect_OnIsSignalConnected(const QGraphicsBlurEffect* self, intptr_t slot);
bool QGraphicsBlurEffect_SuperIsSignalConnected(const QGraphicsBlurEffect* self, const QMetaMethod* signal);
void QGraphicsBlurEffect_Delete(QGraphicsBlurEffect* self);

QGraphicsDropShadowEffect* QGraphicsDropShadowEffect_new();
QGraphicsDropShadowEffect* QGraphicsDropShadowEffect_new2(QObject* parent);
QMetaObject* QGraphicsDropShadowEffect_MetaObject(const QGraphicsDropShadowEffect* self);
void* QGraphicsDropShadowEffect_Metacast(QGraphicsDropShadowEffect* self, const char* param1);
int QGraphicsDropShadowEffect_Metacall(QGraphicsDropShadowEffect* self, int param1, int param2, void** param3);
QRectF* QGraphicsDropShadowEffect_BoundingRectFor(const QGraphicsDropShadowEffect* self, const QRectF* rect);
QPointF* QGraphicsDropShadowEffect_Offset(const QGraphicsDropShadowEffect* self);
double QGraphicsDropShadowEffect_XOffset(const QGraphicsDropShadowEffect* self);
double QGraphicsDropShadowEffect_YOffset(const QGraphicsDropShadowEffect* self);
double QGraphicsDropShadowEffect_BlurRadius(const QGraphicsDropShadowEffect* self);
QColor* QGraphicsDropShadowEffect_Color(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_SetOffset(QGraphicsDropShadowEffect* self, const QPointF* ofs);
void QGraphicsDropShadowEffect_SetOffset2(QGraphicsDropShadowEffect* self, double dx, double dy);
void QGraphicsDropShadowEffect_SetOffset3(QGraphicsDropShadowEffect* self, double d);
void QGraphicsDropShadowEffect_SetXOffset(QGraphicsDropShadowEffect* self, double dx);
void QGraphicsDropShadowEffect_SetYOffset(QGraphicsDropShadowEffect* self, double dy);
void QGraphicsDropShadowEffect_SetBlurRadius(QGraphicsDropShadowEffect* self, double blurRadius);
void QGraphicsDropShadowEffect_SetColor(QGraphicsDropShadowEffect* self, const QColor* color);
void QGraphicsDropShadowEffect_OffsetChanged(QGraphicsDropShadowEffect* self, const QPointF* offset);
void QGraphicsDropShadowEffect_Connect_OffsetChanged(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_BlurRadiusChanged(QGraphicsDropShadowEffect* self, double blurRadius);
void QGraphicsDropShadowEffect_Connect_BlurRadiusChanged(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_ColorChanged(QGraphicsDropShadowEffect* self, const QColor* color);
void QGraphicsDropShadowEffect_Connect_ColorChanged(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_Draw(QGraphicsDropShadowEffect* self, QPainter* painter);
void QGraphicsDropShadowEffect_OnMetaObject(const QGraphicsDropShadowEffect* self, intptr_t slot);
QMetaObject* QGraphicsDropShadowEffect_SuperMetaObject(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnMetacast(QGraphicsDropShadowEffect* self, intptr_t slot);
void* QGraphicsDropShadowEffect_SuperMetacast(QGraphicsDropShadowEffect* self, const char* param1);
void QGraphicsDropShadowEffect_OnMetacall(QGraphicsDropShadowEffect* self, intptr_t slot);
int QGraphicsDropShadowEffect_SuperMetacall(QGraphicsDropShadowEffect* self, int param1, int param2, void** param3);
void QGraphicsDropShadowEffect_OnBoundingRectFor(const QGraphicsDropShadowEffect* self, intptr_t slot);
QRectF* QGraphicsDropShadowEffect_SuperBoundingRectFor(const QGraphicsDropShadowEffect* self, const QRectF* rect);
void QGraphicsDropShadowEffect_OnDraw(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperDraw(QGraphicsDropShadowEffect* self, QPainter* painter);
void QGraphicsDropShadowEffect_SourceChanged(QGraphicsDropShadowEffect* self, int flags);
void QGraphicsDropShadowEffect_OnSourceChanged(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperSourceChanged(QGraphicsDropShadowEffect* self, int flags);
bool QGraphicsDropShadowEffect_Event(QGraphicsDropShadowEffect* self, QEvent* event);
void QGraphicsDropShadowEffect_OnEvent(QGraphicsDropShadowEffect* self, intptr_t slot);
bool QGraphicsDropShadowEffect_SuperEvent(QGraphicsDropShadowEffect* self, QEvent* event);
bool QGraphicsDropShadowEffect_EventFilter(QGraphicsDropShadowEffect* self, QObject* watched, QEvent* event);
void QGraphicsDropShadowEffect_OnEventFilter(QGraphicsDropShadowEffect* self, intptr_t slot);
bool QGraphicsDropShadowEffect_SuperEventFilter(QGraphicsDropShadowEffect* self, QObject* watched, QEvent* event);
void QGraphicsDropShadowEffect_TimerEvent(QGraphicsDropShadowEffect* self, QTimerEvent* event);
void QGraphicsDropShadowEffect_OnTimerEvent(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperTimerEvent(QGraphicsDropShadowEffect* self, QTimerEvent* event);
void QGraphicsDropShadowEffect_ChildEvent(QGraphicsDropShadowEffect* self, QChildEvent* event);
void QGraphicsDropShadowEffect_OnChildEvent(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperChildEvent(QGraphicsDropShadowEffect* self, QChildEvent* event);
void QGraphicsDropShadowEffect_CustomEvent(QGraphicsDropShadowEffect* self, QEvent* event);
void QGraphicsDropShadowEffect_OnCustomEvent(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperCustomEvent(QGraphicsDropShadowEffect* self, QEvent* event);
void QGraphicsDropShadowEffect_ConnectNotify(QGraphicsDropShadowEffect* self, const QMetaMethod* signal);
void QGraphicsDropShadowEffect_OnConnectNotify(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperConnectNotify(QGraphicsDropShadowEffect* self, const QMetaMethod* signal);
void QGraphicsDropShadowEffect_DisconnectNotify(QGraphicsDropShadowEffect* self, const QMetaMethod* signal);
void QGraphicsDropShadowEffect_OnDisconnectNotify(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperDisconnectNotify(QGraphicsDropShadowEffect* self, const QMetaMethod* signal);
void QGraphicsDropShadowEffect_UpdateBoundingRect(QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnUpdateBoundingRect(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperUpdateBoundingRect(QGraphicsDropShadowEffect* self);
bool QGraphicsDropShadowEffect_SourceIsPixmap(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnSourceIsPixmap(const QGraphicsDropShadowEffect* self, intptr_t slot);
bool QGraphicsDropShadowEffect_SuperSourceIsPixmap(const QGraphicsDropShadowEffect* self);
QRectF* QGraphicsDropShadowEffect_SourceBoundingRect(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnSourceBoundingRect(const QGraphicsDropShadowEffect* self, intptr_t slot);
QRectF* QGraphicsDropShadowEffect_SuperSourceBoundingRect(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_DrawSource(QGraphicsDropShadowEffect* self, QPainter* painter);
void QGraphicsDropShadowEffect_OnDrawSource(QGraphicsDropShadowEffect* self, intptr_t slot);
void QGraphicsDropShadowEffect_SuperDrawSource(QGraphicsDropShadowEffect* self, QPainter* painter);
QPixmap* QGraphicsDropShadowEffect_SourcePixmap(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnSourcePixmap(const QGraphicsDropShadowEffect* self, intptr_t slot);
QPixmap* QGraphicsDropShadowEffect_SuperSourcePixmap(const QGraphicsDropShadowEffect* self);
QObject* QGraphicsDropShadowEffect_Sender(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnSender(const QGraphicsDropShadowEffect* self, intptr_t slot);
QObject* QGraphicsDropShadowEffect_SuperSender(const QGraphicsDropShadowEffect* self);
int QGraphicsDropShadowEffect_SenderSignalIndex(const QGraphicsDropShadowEffect* self);
void QGraphicsDropShadowEffect_OnSenderSignalIndex(const QGraphicsDropShadowEffect* self, intptr_t slot);
int QGraphicsDropShadowEffect_SuperSenderSignalIndex(const QGraphicsDropShadowEffect* self);
int QGraphicsDropShadowEffect_Receivers(const QGraphicsDropShadowEffect* self, const char* signal);
void QGraphicsDropShadowEffect_OnReceivers(const QGraphicsDropShadowEffect* self, intptr_t slot);
int QGraphicsDropShadowEffect_SuperReceivers(const QGraphicsDropShadowEffect* self, const char* signal);
bool QGraphicsDropShadowEffect_IsSignalConnected(const QGraphicsDropShadowEffect* self, const QMetaMethod* signal);
void QGraphicsDropShadowEffect_OnIsSignalConnected(const QGraphicsDropShadowEffect* self, intptr_t slot);
bool QGraphicsDropShadowEffect_SuperIsSignalConnected(const QGraphicsDropShadowEffect* self, const QMetaMethod* signal);
void QGraphicsDropShadowEffect_Delete(QGraphicsDropShadowEffect* self);

QGraphicsOpacityEffect* QGraphicsOpacityEffect_new();
QGraphicsOpacityEffect* QGraphicsOpacityEffect_new2(QObject* parent);
QMetaObject* QGraphicsOpacityEffect_MetaObject(const QGraphicsOpacityEffect* self);
void* QGraphicsOpacityEffect_Metacast(QGraphicsOpacityEffect* self, const char* param1);
int QGraphicsOpacityEffect_Metacall(QGraphicsOpacityEffect* self, int param1, int param2, void** param3);
double QGraphicsOpacityEffect_Opacity(const QGraphicsOpacityEffect* self);
QBrush* QGraphicsOpacityEffect_OpacityMask(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_SetOpacity(QGraphicsOpacityEffect* self, double opacity);
void QGraphicsOpacityEffect_SetOpacityMask(QGraphicsOpacityEffect* self, const QBrush* mask);
void QGraphicsOpacityEffect_OpacityChanged(QGraphicsOpacityEffect* self, double opacity);
void QGraphicsOpacityEffect_Connect_OpacityChanged(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_OpacityMaskChanged(QGraphicsOpacityEffect* self, const QBrush* mask);
void QGraphicsOpacityEffect_Connect_OpacityMaskChanged(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_Draw(QGraphicsOpacityEffect* self, QPainter* painter);
void QGraphicsOpacityEffect_OnMetaObject(const QGraphicsOpacityEffect* self, intptr_t slot);
QMetaObject* QGraphicsOpacityEffect_SuperMetaObject(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnMetacast(QGraphicsOpacityEffect* self, intptr_t slot);
void* QGraphicsOpacityEffect_SuperMetacast(QGraphicsOpacityEffect* self, const char* param1);
void QGraphicsOpacityEffect_OnMetacall(QGraphicsOpacityEffect* self, intptr_t slot);
int QGraphicsOpacityEffect_SuperMetacall(QGraphicsOpacityEffect* self, int param1, int param2, void** param3);
void QGraphicsOpacityEffect_OnDraw(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperDraw(QGraphicsOpacityEffect* self, QPainter* painter);
QRectF* QGraphicsOpacityEffect_BoundingRectFor(const QGraphicsOpacityEffect* self, const QRectF* sourceRect);
void QGraphicsOpacityEffect_OnBoundingRectFor(const QGraphicsOpacityEffect* self, intptr_t slot);
QRectF* QGraphicsOpacityEffect_SuperBoundingRectFor(const QGraphicsOpacityEffect* self, const QRectF* sourceRect);
void QGraphicsOpacityEffect_SourceChanged(QGraphicsOpacityEffect* self, int flags);
void QGraphicsOpacityEffect_OnSourceChanged(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperSourceChanged(QGraphicsOpacityEffect* self, int flags);
bool QGraphicsOpacityEffect_Event(QGraphicsOpacityEffect* self, QEvent* event);
void QGraphicsOpacityEffect_OnEvent(QGraphicsOpacityEffect* self, intptr_t slot);
bool QGraphicsOpacityEffect_SuperEvent(QGraphicsOpacityEffect* self, QEvent* event);
bool QGraphicsOpacityEffect_EventFilter(QGraphicsOpacityEffect* self, QObject* watched, QEvent* event);
void QGraphicsOpacityEffect_OnEventFilter(QGraphicsOpacityEffect* self, intptr_t slot);
bool QGraphicsOpacityEffect_SuperEventFilter(QGraphicsOpacityEffect* self, QObject* watched, QEvent* event);
void QGraphicsOpacityEffect_TimerEvent(QGraphicsOpacityEffect* self, QTimerEvent* event);
void QGraphicsOpacityEffect_OnTimerEvent(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperTimerEvent(QGraphicsOpacityEffect* self, QTimerEvent* event);
void QGraphicsOpacityEffect_ChildEvent(QGraphicsOpacityEffect* self, QChildEvent* event);
void QGraphicsOpacityEffect_OnChildEvent(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperChildEvent(QGraphicsOpacityEffect* self, QChildEvent* event);
void QGraphicsOpacityEffect_CustomEvent(QGraphicsOpacityEffect* self, QEvent* event);
void QGraphicsOpacityEffect_OnCustomEvent(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperCustomEvent(QGraphicsOpacityEffect* self, QEvent* event);
void QGraphicsOpacityEffect_ConnectNotify(QGraphicsOpacityEffect* self, const QMetaMethod* signal);
void QGraphicsOpacityEffect_OnConnectNotify(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperConnectNotify(QGraphicsOpacityEffect* self, const QMetaMethod* signal);
void QGraphicsOpacityEffect_DisconnectNotify(QGraphicsOpacityEffect* self, const QMetaMethod* signal);
void QGraphicsOpacityEffect_OnDisconnectNotify(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperDisconnectNotify(QGraphicsOpacityEffect* self, const QMetaMethod* signal);
void QGraphicsOpacityEffect_UpdateBoundingRect(QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnUpdateBoundingRect(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperUpdateBoundingRect(QGraphicsOpacityEffect* self);
bool QGraphicsOpacityEffect_SourceIsPixmap(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnSourceIsPixmap(const QGraphicsOpacityEffect* self, intptr_t slot);
bool QGraphicsOpacityEffect_SuperSourceIsPixmap(const QGraphicsOpacityEffect* self);
QRectF* QGraphicsOpacityEffect_SourceBoundingRect(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnSourceBoundingRect(const QGraphicsOpacityEffect* self, intptr_t slot);
QRectF* QGraphicsOpacityEffect_SuperSourceBoundingRect(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_DrawSource(QGraphicsOpacityEffect* self, QPainter* painter);
void QGraphicsOpacityEffect_OnDrawSource(QGraphicsOpacityEffect* self, intptr_t slot);
void QGraphicsOpacityEffect_SuperDrawSource(QGraphicsOpacityEffect* self, QPainter* painter);
QPixmap* QGraphicsOpacityEffect_SourcePixmap(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnSourcePixmap(const QGraphicsOpacityEffect* self, intptr_t slot);
QPixmap* QGraphicsOpacityEffect_SuperSourcePixmap(const QGraphicsOpacityEffect* self);
QObject* QGraphicsOpacityEffect_Sender(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnSender(const QGraphicsOpacityEffect* self, intptr_t slot);
QObject* QGraphicsOpacityEffect_SuperSender(const QGraphicsOpacityEffect* self);
int QGraphicsOpacityEffect_SenderSignalIndex(const QGraphicsOpacityEffect* self);
void QGraphicsOpacityEffect_OnSenderSignalIndex(const QGraphicsOpacityEffect* self, intptr_t slot);
int QGraphicsOpacityEffect_SuperSenderSignalIndex(const QGraphicsOpacityEffect* self);
int QGraphicsOpacityEffect_Receivers(const QGraphicsOpacityEffect* self, const char* signal);
void QGraphicsOpacityEffect_OnReceivers(const QGraphicsOpacityEffect* self, intptr_t slot);
int QGraphicsOpacityEffect_SuperReceivers(const QGraphicsOpacityEffect* self, const char* signal);
bool QGraphicsOpacityEffect_IsSignalConnected(const QGraphicsOpacityEffect* self, const QMetaMethod* signal);
void QGraphicsOpacityEffect_OnIsSignalConnected(const QGraphicsOpacityEffect* self, intptr_t slot);
bool QGraphicsOpacityEffect_SuperIsSignalConnected(const QGraphicsOpacityEffect* self, const QMetaMethod* signal);
void QGraphicsOpacityEffect_Delete(QGraphicsOpacityEffect* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
