#pragma once
#ifndef SRCC_LIBQGRAPHICSSCENE_H
#define SRCC_LIBQGRAPHICSSCENE_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QBrush QBrush;
typedef struct QChildEvent QChildEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFont QFont;
typedef struct QGraphicsEllipseItem QGraphicsEllipseItem;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsItemGroup QGraphicsItemGroup;
typedef struct QGraphicsLineItem QGraphicsLineItem;
typedef struct QGraphicsPathItem QGraphicsPathItem;
typedef struct QGraphicsPixmapItem QGraphicsPixmapItem;
typedef struct QGraphicsProxyWidget QGraphicsProxyWidget;
typedef struct QGraphicsRectItem QGraphicsRectItem;
typedef struct QGraphicsScene QGraphicsScene;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHelpEvent QGraphicsSceneHelpEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsSimpleTextItem QGraphicsSimpleTextItem;
typedef struct QGraphicsTextItem QGraphicsTextItem;
typedef struct QGraphicsView QGraphicsView;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineF QLineF;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPalette QPalette;
typedef struct QPen QPen;
typedef struct QPixmap QPixmap;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QStyle QStyle;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTransform QTransform;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

QGraphicsScene* QGraphicsScene_new();
QGraphicsScene* QGraphicsScene_new2(const QRectF* sceneRect);
QGraphicsScene* QGraphicsScene_new3(double x, double y, double width, double height);
QGraphicsScene* QGraphicsScene_new4(QObject* parent);
QGraphicsScene* QGraphicsScene_new5(const QRectF* sceneRect, QObject* parent);
QGraphicsScene* QGraphicsScene_new6(double x, double y, double width, double height, QObject* parent);
QMetaObject* QGraphicsScene_MetaObject(const QGraphicsScene* self);
void* QGraphicsScene_Metacast(QGraphicsScene* self, const char* param1);
int QGraphicsScene_Metacall(QGraphicsScene* self, int param1, int param2, void** param3);
QRectF* QGraphicsScene_SceneRect(const QGraphicsScene* self);
double QGraphicsScene_Width(const QGraphicsScene* self);
double QGraphicsScene_Height(const QGraphicsScene* self);
void QGraphicsScene_SetSceneRect(QGraphicsScene* self, const QRectF* rect);
void QGraphicsScene_SetSceneRect2(QGraphicsScene* self, double x, double y, double w, double h);
void QGraphicsScene_Render(QGraphicsScene* self, QPainter* painter);
int QGraphicsScene_ItemIndexMethod(const QGraphicsScene* self);
void QGraphicsScene_SetItemIndexMethod(QGraphicsScene* self, int method);
int QGraphicsScene_BspTreeDepth(const QGraphicsScene* self);
void QGraphicsScene_SetBspTreeDepth(QGraphicsScene* self, int depth);
QRectF* QGraphicsScene_ItemsBoundingRect(const QGraphicsScene* self);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items(const QGraphicsScene* self);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items2(const QGraphicsScene* self, const QPointF* pos);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items3(const QGraphicsScene* self, const QRectF* rect);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items5(const QGraphicsScene* self, const QPainterPath* path);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items6(const QGraphicsScene* self, double x, double y, double w, double h, int mode, int order);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_CollidingItems(const QGraphicsScene* self, const QGraphicsItem* item);
QGraphicsItem* QGraphicsScene_ItemAt(const QGraphicsScene* self, const QPointF* pos, const QTransform* deviceTransform);
QGraphicsItem* QGraphicsScene_ItemAt2(const QGraphicsScene* self, double x, double y, const QTransform* deviceTransform);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_SelectedItems(const QGraphicsScene* self);
QPainterPath* QGraphicsScene_SelectionArea(const QGraphicsScene* self);
void QGraphicsScene_SetSelectionArea(QGraphicsScene* self, const QPainterPath* path, const QTransform* deviceTransform);
void QGraphicsScene_SetSelectionArea2(QGraphicsScene* self, const QPainterPath* path);
QGraphicsItemGroup* QGraphicsScene_CreateItemGroup(QGraphicsScene* self, const libqt_list /* of QGraphicsItem* */ items);
void QGraphicsScene_DestroyItemGroup(QGraphicsScene* self, QGraphicsItemGroup* group);
void QGraphicsScene_AddItem(QGraphicsScene* self, QGraphicsItem* item);
QGraphicsEllipseItem* QGraphicsScene_AddEllipse(QGraphicsScene* self, const QRectF* rect);
QGraphicsLineItem* QGraphicsScene_AddLine(QGraphicsScene* self, const QLineF* line);
QGraphicsPathItem* QGraphicsScene_AddPath(QGraphicsScene* self, const QPainterPath* path);
QGraphicsPixmapItem* QGraphicsScene_AddPixmap(QGraphicsScene* self, const QPixmap* pixmap);
QGraphicsRectItem* QGraphicsScene_AddRect(QGraphicsScene* self, const QRectF* rect);
QGraphicsTextItem* QGraphicsScene_AddText(QGraphicsScene* self, const libqt_string text);
QGraphicsSimpleTextItem* QGraphicsScene_AddSimpleText(QGraphicsScene* self, const libqt_string text);
QGraphicsProxyWidget* QGraphicsScene_AddWidget(QGraphicsScene* self, QWidget* widget);
QGraphicsEllipseItem* QGraphicsScene_AddEllipse2(QGraphicsScene* self, double x, double y, double w, double h);
QGraphicsLineItem* QGraphicsScene_AddLine2(QGraphicsScene* self, double x1, double y1, double x2, double y2);
QGraphicsRectItem* QGraphicsScene_AddRect2(QGraphicsScene* self, double x, double y, double w, double h);
void QGraphicsScene_RemoveItem(QGraphicsScene* self, QGraphicsItem* item);
QGraphicsItem* QGraphicsScene_FocusItem(const QGraphicsScene* self);
void QGraphicsScene_SetFocusItem(QGraphicsScene* self, QGraphicsItem* item);
bool QGraphicsScene_HasFocus(const QGraphicsScene* self);
void QGraphicsScene_SetFocus(QGraphicsScene* self);
void QGraphicsScene_ClearFocus(QGraphicsScene* self);
void QGraphicsScene_SetStickyFocus(QGraphicsScene* self, bool enabled);
bool QGraphicsScene_StickyFocus(const QGraphicsScene* self);
QGraphicsItem* QGraphicsScene_MouseGrabberItem(const QGraphicsScene* self);
QBrush* QGraphicsScene_BackgroundBrush(const QGraphicsScene* self);
void QGraphicsScene_SetBackgroundBrush(QGraphicsScene* self, const QBrush* brush);
QBrush* QGraphicsScene_ForegroundBrush(const QGraphicsScene* self);
void QGraphicsScene_SetForegroundBrush(QGraphicsScene* self, const QBrush* brush);
QVariant* QGraphicsScene_InputMethodQuery(const QGraphicsScene* self, int query);
libqt_list /* of QGraphicsView* */ QGraphicsScene_Views(const QGraphicsScene* self);
void QGraphicsScene_Update(QGraphicsScene* self, double x, double y, double w, double h);
void QGraphicsScene_Invalidate(QGraphicsScene* self, double x, double y, double w, double h);
QStyle* QGraphicsScene_Style(const QGraphicsScene* self);
void QGraphicsScene_SetStyle(QGraphicsScene* self, QStyle* style);
QFont* QGraphicsScene_Font(const QGraphicsScene* self);
void QGraphicsScene_SetFont(QGraphicsScene* self, const QFont* font);
QPalette* QGraphicsScene_Palette(const QGraphicsScene* self);
void QGraphicsScene_SetPalette(QGraphicsScene* self, const QPalette* palette);
bool QGraphicsScene_IsActive(const QGraphicsScene* self);
QGraphicsItem* QGraphicsScene_ActivePanel(const QGraphicsScene* self);
void QGraphicsScene_SetActivePanel(QGraphicsScene* self, QGraphicsItem* item);
QGraphicsWidget* QGraphicsScene_ActiveWindow(const QGraphicsScene* self);
void QGraphicsScene_SetActiveWindow(QGraphicsScene* self, QGraphicsWidget* widget);
bool QGraphicsScene_SendEvent(QGraphicsScene* self, QGraphicsItem* item, QEvent* event);
double QGraphicsScene_MinimumRenderSize(const QGraphicsScene* self);
void QGraphicsScene_SetMinimumRenderSize(QGraphicsScene* self, double minSize);
bool QGraphicsScene_FocusOnTouch(const QGraphicsScene* self);
void QGraphicsScene_SetFocusOnTouch(QGraphicsScene* self, bool enabled);
void QGraphicsScene_Update2(QGraphicsScene* self);
void QGraphicsScene_Invalidate2(QGraphicsScene* self);
void QGraphicsScene_Advance(QGraphicsScene* self);
void QGraphicsScene_ClearSelection(QGraphicsScene* self);
void QGraphicsScene_Clear(QGraphicsScene* self);
bool QGraphicsScene_Event(QGraphicsScene* self, QEvent* event);
bool QGraphicsScene_EventFilter(QGraphicsScene* self, QObject* watched, QEvent* event);
void QGraphicsScene_ContextMenuEvent(QGraphicsScene* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsScene_DragEnterEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_DragMoveEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_DragLeaveEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_DropEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_FocusInEvent(QGraphicsScene* self, QFocusEvent* event);
void QGraphicsScene_FocusOutEvent(QGraphicsScene* self, QFocusEvent* event);
void QGraphicsScene_HelpEvent(QGraphicsScene* self, QGraphicsSceneHelpEvent* event);
void QGraphicsScene_KeyPressEvent(QGraphicsScene* self, QKeyEvent* event);
void QGraphicsScene_KeyReleaseEvent(QGraphicsScene* self, QKeyEvent* event);
void QGraphicsScene_MousePressEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_MouseMoveEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_MouseReleaseEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_MouseDoubleClickEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_WheelEvent(QGraphicsScene* self, QGraphicsSceneWheelEvent* event);
void QGraphicsScene_InputMethodEvent(QGraphicsScene* self, QInputMethodEvent* event);
void QGraphicsScene_DrawBackground(QGraphicsScene* self, QPainter* painter, const QRectF* rect);
void QGraphicsScene_DrawForeground(QGraphicsScene* self, QPainter* painter, const QRectF* rect);
void QGraphicsScene_DrawItems(QGraphicsScene* self, QPainter* painter, int numItems, QGraphicsItem** items, const QStyleOptionGraphicsItem* options, QWidget* widget);
bool QGraphicsScene_FocusNextPrevChild(QGraphicsScene* self, bool next);
void QGraphicsScene_Changed(QGraphicsScene* self, const libqt_list /* of QRectF* */ region);
void QGraphicsScene_Connect_Changed(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SceneRectChanged(QGraphicsScene* self, const QRectF* rect);
void QGraphicsScene_Connect_SceneRectChanged(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SelectionChanged(QGraphicsScene* self);
void QGraphicsScene_Connect_SelectionChanged(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_FocusItemChanged(QGraphicsScene* self, QGraphicsItem* newFocus, QGraphicsItem* oldFocus, int reason);
void QGraphicsScene_Connect_FocusItemChanged(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_Render2(QGraphicsScene* self, QPainter* painter, const QRectF* target);
void QGraphicsScene_Render3(QGraphicsScene* self, QPainter* painter, const QRectF* target, const QRectF* source);
void QGraphicsScene_Render4(QGraphicsScene* self, QPainter* painter, const QRectF* target, const QRectF* source, int aspectRatioMode);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items1(const QGraphicsScene* self, int order);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items22(const QGraphicsScene* self, const QPointF* pos, int mode);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items32(const QGraphicsScene* self, const QPointF* pos, int mode, int order);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items42(const QGraphicsScene* self, const QPointF* pos, int mode, int order, const QTransform* deviceTransform);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items23(const QGraphicsScene* self, const QRectF* rect, int mode);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items33(const QGraphicsScene* self, const QRectF* rect, int mode, int order);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items43(const QGraphicsScene* self, const QRectF* rect, int mode, int order, const QTransform* deviceTransform);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items25(const QGraphicsScene* self, const QPainterPath* path, int mode);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items35(const QGraphicsScene* self, const QPainterPath* path, int mode, int order);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items45(const QGraphicsScene* self, const QPainterPath* path, int mode, int order, const QTransform* deviceTransform);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_Items7(const QGraphicsScene* self, double x, double y, double w, double h, int mode, int order, const QTransform* deviceTransform);
libqt_list /* of QGraphicsItem* */ QGraphicsScene_CollidingItems2(const QGraphicsScene* self, const QGraphicsItem* item, int mode);
void QGraphicsScene_SetSelectionArea22(QGraphicsScene* self, const QPainterPath* path, int selectionOperation);
void QGraphicsScene_SetSelectionArea3(QGraphicsScene* self, const QPainterPath* path, int selectionOperation, int mode);
void QGraphicsScene_SetSelectionArea4(QGraphicsScene* self, const QPainterPath* path, int selectionOperation, int mode, const QTransform* deviceTransform);
QGraphicsEllipseItem* QGraphicsScene_AddEllipse22(QGraphicsScene* self, const QRectF* rect, const QPen* pen);
QGraphicsEllipseItem* QGraphicsScene_AddEllipse3(QGraphicsScene* self, const QRectF* rect, const QPen* pen, const QBrush* brush);
QGraphicsLineItem* QGraphicsScene_AddLine22(QGraphicsScene* self, const QLineF* line, const QPen* pen);
QGraphicsPathItem* QGraphicsScene_AddPath2(QGraphicsScene* self, const QPainterPath* path, const QPen* pen);
QGraphicsPathItem* QGraphicsScene_AddPath3(QGraphicsScene* self, const QPainterPath* path, const QPen* pen, const QBrush* brush);
QGraphicsRectItem* QGraphicsScene_AddRect22(QGraphicsScene* self, const QRectF* rect, const QPen* pen);
QGraphicsRectItem* QGraphicsScene_AddRect3(QGraphicsScene* self, const QRectF* rect, const QPen* pen, const QBrush* brush);
QGraphicsTextItem* QGraphicsScene_AddText2(QGraphicsScene* self, const libqt_string text, const QFont* font);
QGraphicsSimpleTextItem* QGraphicsScene_AddSimpleText2(QGraphicsScene* self, const libqt_string text, const QFont* font);
QGraphicsProxyWidget* QGraphicsScene_AddWidget2(QGraphicsScene* self, QWidget* widget, int wFlags);
QGraphicsEllipseItem* QGraphicsScene_AddEllipse5(QGraphicsScene* self, double x, double y, double w, double h, const QPen* pen);
QGraphicsEllipseItem* QGraphicsScene_AddEllipse6(QGraphicsScene* self, double x, double y, double w, double h, const QPen* pen, const QBrush* brush);
QGraphicsLineItem* QGraphicsScene_AddLine5(QGraphicsScene* self, double x1, double y1, double x2, double y2, const QPen* pen);
QGraphicsRectItem* QGraphicsScene_AddRect5(QGraphicsScene* self, double x, double y, double w, double h, const QPen* pen);
QGraphicsRectItem* QGraphicsScene_AddRect6(QGraphicsScene* self, double x, double y, double w, double h, const QPen* pen, const QBrush* brush);
void QGraphicsScene_SetFocusItem2(QGraphicsScene* self, QGraphicsItem* item, int focusReason);
void QGraphicsScene_SetFocus1(QGraphicsScene* self, int focusReason);
void QGraphicsScene_Invalidate5(QGraphicsScene* self, double x, double y, double w, double h, int layers);
void QGraphicsScene_Update1(QGraphicsScene* self, const QRectF* rect);
void QGraphicsScene_Invalidate1(QGraphicsScene* self, const QRectF* rect);
void QGraphicsScene_Invalidate22(QGraphicsScene* self, const QRectF* rect, int layers);
void QGraphicsScene_OnMetaObject(const QGraphicsScene* self, intptr_t slot);
QMetaObject* QGraphicsScene_SuperMetaObject(const QGraphicsScene* self);
void QGraphicsScene_OnMetacast(QGraphicsScene* self, intptr_t slot);
void* QGraphicsScene_SuperMetacast(QGraphicsScene* self, const char* param1);
void QGraphicsScene_OnMetacall(QGraphicsScene* self, intptr_t slot);
int QGraphicsScene_SuperMetacall(QGraphicsScene* self, int param1, int param2, void** param3);
void QGraphicsScene_OnInputMethodQuery(const QGraphicsScene* self, intptr_t slot);
QVariant* QGraphicsScene_SuperInputMethodQuery(const QGraphicsScene* self, int query);
void QGraphicsScene_OnEvent(QGraphicsScene* self, intptr_t slot);
bool QGraphicsScene_SuperEvent(QGraphicsScene* self, QEvent* event);
void QGraphicsScene_OnEventFilter(QGraphicsScene* self, intptr_t slot);
bool QGraphicsScene_SuperEventFilter(QGraphicsScene* self, QObject* watched, QEvent* event);
void QGraphicsScene_OnContextMenuEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperContextMenuEvent(QGraphicsScene* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsScene_OnDragEnterEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDragEnterEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_OnDragMoveEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDragMoveEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_OnDragLeaveEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDragLeaveEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_OnDropEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDropEvent(QGraphicsScene* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsScene_OnFocusInEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperFocusInEvent(QGraphicsScene* self, QFocusEvent* event);
void QGraphicsScene_OnFocusOutEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperFocusOutEvent(QGraphicsScene* self, QFocusEvent* event);
void QGraphicsScene_OnHelpEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperHelpEvent(QGraphicsScene* self, QGraphicsSceneHelpEvent* event);
void QGraphicsScene_OnKeyPressEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperKeyPressEvent(QGraphicsScene* self, QKeyEvent* event);
void QGraphicsScene_OnKeyReleaseEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperKeyReleaseEvent(QGraphicsScene* self, QKeyEvent* event);
void QGraphicsScene_OnMousePressEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperMousePressEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_OnMouseMoveEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperMouseMoveEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_OnMouseReleaseEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperMouseReleaseEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_OnMouseDoubleClickEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperMouseDoubleClickEvent(QGraphicsScene* self, QGraphicsSceneMouseEvent* event);
void QGraphicsScene_OnWheelEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperWheelEvent(QGraphicsScene* self, QGraphicsSceneWheelEvent* event);
void QGraphicsScene_OnInputMethodEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperInputMethodEvent(QGraphicsScene* self, QInputMethodEvent* event);
void QGraphicsScene_OnDrawBackground(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDrawBackground(QGraphicsScene* self, QPainter* painter, const QRectF* rect);
void QGraphicsScene_OnDrawForeground(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDrawForeground(QGraphicsScene* self, QPainter* painter, const QRectF* rect);
void QGraphicsScene_OnDrawItems(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDrawItems(QGraphicsScene* self, QPainter* painter, int numItems, QGraphicsItem** items, const QStyleOptionGraphicsItem* options, QWidget* widget);
void QGraphicsScene_OnFocusNextPrevChild(QGraphicsScene* self, intptr_t slot);
bool QGraphicsScene_SuperFocusNextPrevChild(QGraphicsScene* self, bool next);
void QGraphicsScene_TimerEvent(QGraphicsScene* self, QTimerEvent* event);
void QGraphicsScene_OnTimerEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperTimerEvent(QGraphicsScene* self, QTimerEvent* event);
void QGraphicsScene_ChildEvent(QGraphicsScene* self, QChildEvent* event);
void QGraphicsScene_OnChildEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperChildEvent(QGraphicsScene* self, QChildEvent* event);
void QGraphicsScene_CustomEvent(QGraphicsScene* self, QEvent* event);
void QGraphicsScene_OnCustomEvent(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperCustomEvent(QGraphicsScene* self, QEvent* event);
void QGraphicsScene_ConnectNotify(QGraphicsScene* self, const QMetaMethod* signal);
void QGraphicsScene_OnConnectNotify(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperConnectNotify(QGraphicsScene* self, const QMetaMethod* signal);
void QGraphicsScene_DisconnectNotify(QGraphicsScene* self, const QMetaMethod* signal);
void QGraphicsScene_OnDisconnectNotify(QGraphicsScene* self, intptr_t slot);
void QGraphicsScene_SuperDisconnectNotify(QGraphicsScene* self, const QMetaMethod* signal);
QObject* QGraphicsScene_Sender(const QGraphicsScene* self);
void QGraphicsScene_OnSender(const QGraphicsScene* self, intptr_t slot);
QObject* QGraphicsScene_SuperSender(const QGraphicsScene* self);
int QGraphicsScene_SenderSignalIndex(const QGraphicsScene* self);
void QGraphicsScene_OnSenderSignalIndex(const QGraphicsScene* self, intptr_t slot);
int QGraphicsScene_SuperSenderSignalIndex(const QGraphicsScene* self);
int QGraphicsScene_Receivers(const QGraphicsScene* self, const char* signal);
void QGraphicsScene_OnReceivers(const QGraphicsScene* self, intptr_t slot);
int QGraphicsScene_SuperReceivers(const QGraphicsScene* self, const char* signal);
bool QGraphicsScene_IsSignalConnected(const QGraphicsScene* self, const QMetaMethod* signal);
void QGraphicsScene_OnIsSignalConnected(const QGraphicsScene* self, intptr_t slot);
bool QGraphicsScene_SuperIsSignalConnected(const QGraphicsScene* self, const QMetaMethod* signal);
void QGraphicsScene_Delete(QGraphicsScene* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
