#pragma once
#ifndef SRCC_LIBQSORTFILTERPROXYMODEL_H
#define SRCC_LIBQSORTFILTERPROXYMODEL_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractItemModel QAbstractItemModel;
typedef struct QAbstractProxyModel QAbstractProxyModel;
typedef struct QChildEvent QChildEvent;
typedef struct QDataStream QDataStream;
typedef struct QEvent QEvent;
typedef struct QItemSelection QItemSelection;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QModelIndex QModelIndex;
typedef struct QModelRoleDataSpan QModelRoleDataSpan;
typedef struct QObject QObject;
typedef struct QRegularExpression QRegularExpression;
typedef struct QSize QSize;
typedef struct QSortFilterProxyModel QSortFilterProxyModel;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
#endif

QSortFilterProxyModel* QSortFilterProxyModel_new();
QSortFilterProxyModel* QSortFilterProxyModel_new2(QObject* parent);
QMetaObject* QSortFilterProxyModel_MetaObject(const QSortFilterProxyModel* self);
void* QSortFilterProxyModel_Metacast(QSortFilterProxyModel* self, const char* param1);
int QSortFilterProxyModel_Metacall(QSortFilterProxyModel* self, int param1, int param2, void** param3);
void QSortFilterProxyModel_SetSourceModel(QSortFilterProxyModel* self, QAbstractItemModel* sourceModel);
QModelIndex* QSortFilterProxyModel_MapToSource(const QSortFilterProxyModel* self, const QModelIndex* proxyIndex);
QModelIndex* QSortFilterProxyModel_MapFromSource(const QSortFilterProxyModel* self, const QModelIndex* sourceIndex);
QItemSelection* QSortFilterProxyModel_MapSelectionToSource(const QSortFilterProxyModel* self, const QItemSelection* proxySelection);
QItemSelection* QSortFilterProxyModel_MapSelectionFromSource(const QSortFilterProxyModel* self, const QItemSelection* sourceSelection);
QRegularExpression* QSortFilterProxyModel_FilterRegularExpression(const QSortFilterProxyModel* self);
int QSortFilterProxyModel_FilterKeyColumn(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetFilterKeyColumn(QSortFilterProxyModel* self, int column);
int QSortFilterProxyModel_FilterCaseSensitivity(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetFilterCaseSensitivity(QSortFilterProxyModel* self, int cs);
int QSortFilterProxyModel_SortCaseSensitivity(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetSortCaseSensitivity(QSortFilterProxyModel* self, int cs);
bool QSortFilterProxyModel_IsSortLocaleAware(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetSortLocaleAware(QSortFilterProxyModel* self, bool on);
int QSortFilterProxyModel_SortColumn(const QSortFilterProxyModel* self);
int QSortFilterProxyModel_SortOrder(const QSortFilterProxyModel* self);
bool QSortFilterProxyModel_DynamicSortFilter(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetDynamicSortFilter(QSortFilterProxyModel* self, bool enable);
int QSortFilterProxyModel_SortRole(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetSortRole(QSortFilterProxyModel* self, int role);
int QSortFilterProxyModel_FilterRole(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetFilterRole(QSortFilterProxyModel* self, int role);
bool QSortFilterProxyModel_IsRecursiveFilteringEnabled(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetRecursiveFilteringEnabled(QSortFilterProxyModel* self, bool recursive);
bool QSortFilterProxyModel_AutoAcceptChildRows(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_SetAutoAcceptChildRows(QSortFilterProxyModel* self, bool accept);
void QSortFilterProxyModel_SetFilterRegularExpression(QSortFilterProxyModel* self, const libqt_string pattern);
void QSortFilterProxyModel_SetFilterRegularExpression2(QSortFilterProxyModel* self, const QRegularExpression* regularExpression);
void QSortFilterProxyModel_SetFilterWildcard(QSortFilterProxyModel* self, const libqt_string pattern);
void QSortFilterProxyModel_SetFilterFixedString(QSortFilterProxyModel* self, const libqt_string pattern);
void QSortFilterProxyModel_Invalidate(QSortFilterProxyModel* self);
bool QSortFilterProxyModel_FilterAcceptsRow(const QSortFilterProxyModel* self, int source_row, const QModelIndex* source_parent);
bool QSortFilterProxyModel_FilterAcceptsColumn(const QSortFilterProxyModel* self, int source_column, const QModelIndex* source_parent);
bool QSortFilterProxyModel_LessThan(const QSortFilterProxyModel* self, const QModelIndex* source_left, const QModelIndex* source_right);
QModelIndex* QSortFilterProxyModel_Index(const QSortFilterProxyModel* self, int row, int column, const QModelIndex* parent);
QModelIndex* QSortFilterProxyModel_Parent(const QSortFilterProxyModel* self, const QModelIndex* child);
QModelIndex* QSortFilterProxyModel_Sibling(const QSortFilterProxyModel* self, int row, int column, const QModelIndex* idx);
int QSortFilterProxyModel_RowCount(const QSortFilterProxyModel* self, const QModelIndex* parent);
int QSortFilterProxyModel_ColumnCount(const QSortFilterProxyModel* self, const QModelIndex* parent);
bool QSortFilterProxyModel_HasChildren(const QSortFilterProxyModel* self, const QModelIndex* parent);
QVariant* QSortFilterProxyModel_Data(const QSortFilterProxyModel* self, const QModelIndex* index, int role);
bool QSortFilterProxyModel_SetData(QSortFilterProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
QVariant* QSortFilterProxyModel_HeaderData(const QSortFilterProxyModel* self, int section, int orientation, int role);
bool QSortFilterProxyModel_SetHeaderData(QSortFilterProxyModel* self, int section, int orientation, const QVariant* value, int role);
QMimeData* QSortFilterProxyModel_MimeData(const QSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
bool QSortFilterProxyModel_DropMimeData(QSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
bool QSortFilterProxyModel_InsertRows(QSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
bool QSortFilterProxyModel_InsertColumns(QSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
bool QSortFilterProxyModel_RemoveRows(QSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
bool QSortFilterProxyModel_RemoveColumns(QSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
void QSortFilterProxyModel_FetchMore(QSortFilterProxyModel* self, const QModelIndex* parent);
bool QSortFilterProxyModel_CanFetchMore(const QSortFilterProxyModel* self, const QModelIndex* parent);
int QSortFilterProxyModel_Flags(const QSortFilterProxyModel* self, const QModelIndex* index);
QModelIndex* QSortFilterProxyModel_Buddy(const QSortFilterProxyModel* self, const QModelIndex* index);
libqt_list /* of QModelIndex* */ QSortFilterProxyModel_Match(const QSortFilterProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
QSize* QSortFilterProxyModel_Span(const QSortFilterProxyModel* self, const QModelIndex* index);
void QSortFilterProxyModel_Sort(QSortFilterProxyModel* self, int column, int order);
libqt_list /* of libqt_string */ QSortFilterProxyModel_MimeTypes(const QSortFilterProxyModel* self);
int QSortFilterProxyModel_SupportedDropActions(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_DynamicSortFilterChanged(QSortFilterProxyModel* self, bool dynamicSortFilter);
void QSortFilterProxyModel_Connect_DynamicSortFilterChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_FilterCaseSensitivityChanged(QSortFilterProxyModel* self, int filterCaseSensitivity);
void QSortFilterProxyModel_Connect_FilterCaseSensitivityChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SortCaseSensitivityChanged(QSortFilterProxyModel* self, int sortCaseSensitivity);
void QSortFilterProxyModel_Connect_SortCaseSensitivityChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SortLocaleAwareChanged(QSortFilterProxyModel* self, bool sortLocaleAware);
void QSortFilterProxyModel_Connect_SortLocaleAwareChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SortRoleChanged(QSortFilterProxyModel* self, int sortRole);
void QSortFilterProxyModel_Connect_SortRoleChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_FilterRoleChanged(QSortFilterProxyModel* self, int filterRole);
void QSortFilterProxyModel_Connect_FilterRoleChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_RecursiveFilteringEnabledChanged(QSortFilterProxyModel* self, bool recursiveFilteringEnabled);
void QSortFilterProxyModel_Connect_RecursiveFilteringEnabledChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_AutoAcceptChildRowsChanged(QSortFilterProxyModel* self, bool autoAcceptChildRows);
void QSortFilterProxyModel_Connect_AutoAcceptChildRowsChanged(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_OnMetaObject(const QSortFilterProxyModel* self, intptr_t slot);
QMetaObject* QSortFilterProxyModel_SuperMetaObject(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnMetacast(QSortFilterProxyModel* self, intptr_t slot);
void* QSortFilterProxyModel_SuperMetacast(QSortFilterProxyModel* self, const char* param1);
void QSortFilterProxyModel_OnMetacall(QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperMetacall(QSortFilterProxyModel* self, int param1, int param2, void** param3);
void QSortFilterProxyModel_OnSetSourceModel(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperSetSourceModel(QSortFilterProxyModel* self, QAbstractItemModel* sourceModel);
void QSortFilterProxyModel_OnMapToSource(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperMapToSource(const QSortFilterProxyModel* self, const QModelIndex* proxyIndex);
void QSortFilterProxyModel_OnMapFromSource(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperMapFromSource(const QSortFilterProxyModel* self, const QModelIndex* sourceIndex);
void QSortFilterProxyModel_OnMapSelectionToSource(const QSortFilterProxyModel* self, intptr_t slot);
QItemSelection* QSortFilterProxyModel_SuperMapSelectionToSource(const QSortFilterProxyModel* self, const QItemSelection* proxySelection);
void QSortFilterProxyModel_OnMapSelectionFromSource(const QSortFilterProxyModel* self, intptr_t slot);
QItemSelection* QSortFilterProxyModel_SuperMapSelectionFromSource(const QSortFilterProxyModel* self, const QItemSelection* sourceSelection);
void QSortFilterProxyModel_OnFilterAcceptsRow(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperFilterAcceptsRow(const QSortFilterProxyModel* self, int source_row, const QModelIndex* source_parent);
void QSortFilterProxyModel_OnFilterAcceptsColumn(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperFilterAcceptsColumn(const QSortFilterProxyModel* self, int source_column, const QModelIndex* source_parent);
void QSortFilterProxyModel_OnLessThan(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperLessThan(const QSortFilterProxyModel* self, const QModelIndex* source_left, const QModelIndex* source_right);
void QSortFilterProxyModel_OnIndex(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperIndex(const QSortFilterProxyModel* self, int row, int column, const QModelIndex* parent);
void QSortFilterProxyModel_OnParent(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperParent(const QSortFilterProxyModel* self, const QModelIndex* child);
void QSortFilterProxyModel_OnSibling(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperSibling(const QSortFilterProxyModel* self, int row, int column, const QModelIndex* idx);
void QSortFilterProxyModel_OnRowCount(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperRowCount(const QSortFilterProxyModel* self, const QModelIndex* parent);
void QSortFilterProxyModel_OnColumnCount(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperColumnCount(const QSortFilterProxyModel* self, const QModelIndex* parent);
void QSortFilterProxyModel_OnHasChildren(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperHasChildren(const QSortFilterProxyModel* self, const QModelIndex* parent);
void QSortFilterProxyModel_OnData(const QSortFilterProxyModel* self, intptr_t slot);
QVariant* QSortFilterProxyModel_SuperData(const QSortFilterProxyModel* self, const QModelIndex* index, int role);
void QSortFilterProxyModel_OnSetData(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperSetData(QSortFilterProxyModel* self, const QModelIndex* index, const QVariant* value, int role);
void QSortFilterProxyModel_OnHeaderData(const QSortFilterProxyModel* self, intptr_t slot);
QVariant* QSortFilterProxyModel_SuperHeaderData(const QSortFilterProxyModel* self, int section, int orientation, int role);
void QSortFilterProxyModel_OnSetHeaderData(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperSetHeaderData(QSortFilterProxyModel* self, int section, int orientation, const QVariant* value, int role);
void QSortFilterProxyModel_OnMimeData(const QSortFilterProxyModel* self, intptr_t slot);
QMimeData* QSortFilterProxyModel_SuperMimeData(const QSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes);
void QSortFilterProxyModel_OnDropMimeData(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperDropMimeData(QSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void QSortFilterProxyModel_OnInsertRows(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperInsertRows(QSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
void QSortFilterProxyModel_OnInsertColumns(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperInsertColumns(QSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
void QSortFilterProxyModel_OnRemoveRows(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperRemoveRows(QSortFilterProxyModel* self, int row, int count, const QModelIndex* parent);
void QSortFilterProxyModel_OnRemoveColumns(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperRemoveColumns(QSortFilterProxyModel* self, int column, int count, const QModelIndex* parent);
void QSortFilterProxyModel_OnFetchMore(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperFetchMore(QSortFilterProxyModel* self, const QModelIndex* parent);
void QSortFilterProxyModel_OnCanFetchMore(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperCanFetchMore(const QSortFilterProxyModel* self, const QModelIndex* parent);
void QSortFilterProxyModel_OnFlags(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperFlags(const QSortFilterProxyModel* self, const QModelIndex* index);
void QSortFilterProxyModel_OnBuddy(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperBuddy(const QSortFilterProxyModel* self, const QModelIndex* index);
void QSortFilterProxyModel_OnMatch(const QSortFilterProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ QSortFilterProxyModel_SuperMatch(const QSortFilterProxyModel* self, const QModelIndex* start, int role, const QVariant* value, int hits, int flags);
void QSortFilterProxyModel_OnSpan(const QSortFilterProxyModel* self, intptr_t slot);
QSize* QSortFilterProxyModel_SuperSpan(const QSortFilterProxyModel* self, const QModelIndex* index);
void QSortFilterProxyModel_OnSort(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperSort(QSortFilterProxyModel* self, int column, int order);
void QSortFilterProxyModel_OnMimeTypes(const QSortFilterProxyModel* self, intptr_t slot);
libqt_list /* of libqt_string */ QSortFilterProxyModel_SuperMimeTypes(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnSupportedDropActions(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperSupportedDropActions(const QSortFilterProxyModel* self);
bool QSortFilterProxyModel_Submit(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnSubmit(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperSubmit(QSortFilterProxyModel* self);
void QSortFilterProxyModel_Revert(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnRevert(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperRevert(QSortFilterProxyModel* self);
libqt_map /* of int to QVariant* */ QSortFilterProxyModel_ItemData(const QSortFilterProxyModel* self, const QModelIndex* index);
void QSortFilterProxyModel_OnItemData(const QSortFilterProxyModel* self, intptr_t slot);
libqt_map /* of int to QVariant* */ QSortFilterProxyModel_SuperItemData(const QSortFilterProxyModel* self, const QModelIndex* index);
bool QSortFilterProxyModel_SetItemData(QSortFilterProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
void QSortFilterProxyModel_OnSetItemData(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperSetItemData(QSortFilterProxyModel* self, const QModelIndex* index, const libqt_map /* of int to QVariant* */ roles);
bool QSortFilterProxyModel_ClearItemData(QSortFilterProxyModel* self, const QModelIndex* index);
void QSortFilterProxyModel_OnClearItemData(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperClearItemData(QSortFilterProxyModel* self, const QModelIndex* index);
bool QSortFilterProxyModel_CanDropMimeData(const QSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
void QSortFilterProxyModel_OnCanDropMimeData(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperCanDropMimeData(const QSortFilterProxyModel* self, const QMimeData* data, int action, int row, int column, const QModelIndex* parent);
int QSortFilterProxyModel_SupportedDragActions(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnSupportedDragActions(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperSupportedDragActions(const QSortFilterProxyModel* self);
libqt_map /* of int to libqt_string */ QSortFilterProxyModel_RoleNames(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnRoleNames(const QSortFilterProxyModel* self, intptr_t slot);
libqt_map /* of int to libqt_string */ QSortFilterProxyModel_SuperRoleNames(const QSortFilterProxyModel* self);
bool QSortFilterProxyModel_MoveRows(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
void QSortFilterProxyModel_OnMoveRows(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperMoveRows(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceRow, int count, const QModelIndex* destinationParent, int destinationChild);
bool QSortFilterProxyModel_MoveColumns(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void QSortFilterProxyModel_OnMoveColumns(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperMoveColumns(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceColumn, int count, const QModelIndex* destinationParent, int destinationChild);
void QSortFilterProxyModel_MultiData(const QSortFilterProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void QSortFilterProxyModel_OnMultiData(const QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperMultiData(const QSortFilterProxyModel* self, const QModelIndex* index, QModelRoleDataSpan* roleDataSpan);
void QSortFilterProxyModel_ResetInternalData(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnResetInternalData(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperResetInternalData(QSortFilterProxyModel* self);
bool QSortFilterProxyModel_Event(QSortFilterProxyModel* self, QEvent* event);
void QSortFilterProxyModel_OnEvent(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperEvent(QSortFilterProxyModel* self, QEvent* event);
bool QSortFilterProxyModel_EventFilter(QSortFilterProxyModel* self, QObject* watched, QEvent* event);
void QSortFilterProxyModel_OnEventFilter(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperEventFilter(QSortFilterProxyModel* self, QObject* watched, QEvent* event);
void QSortFilterProxyModel_TimerEvent(QSortFilterProxyModel* self, QTimerEvent* event);
void QSortFilterProxyModel_OnTimerEvent(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperTimerEvent(QSortFilterProxyModel* self, QTimerEvent* event);
void QSortFilterProxyModel_ChildEvent(QSortFilterProxyModel* self, QChildEvent* event);
void QSortFilterProxyModel_OnChildEvent(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperChildEvent(QSortFilterProxyModel* self, QChildEvent* event);
void QSortFilterProxyModel_CustomEvent(QSortFilterProxyModel* self, QEvent* event);
void QSortFilterProxyModel_OnCustomEvent(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperCustomEvent(QSortFilterProxyModel* self, QEvent* event);
void QSortFilterProxyModel_ConnectNotify(QSortFilterProxyModel* self, const QMetaMethod* signal);
void QSortFilterProxyModel_OnConnectNotify(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperConnectNotify(QSortFilterProxyModel* self, const QMetaMethod* signal);
void QSortFilterProxyModel_DisconnectNotify(QSortFilterProxyModel* self, const QMetaMethod* signal);
void QSortFilterProxyModel_OnDisconnectNotify(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperDisconnectNotify(QSortFilterProxyModel* self, const QMetaMethod* signal);
void QSortFilterProxyModel_InvalidateFilter(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnInvalidateFilter(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperInvalidateFilter(QSortFilterProxyModel* self);
void QSortFilterProxyModel_InvalidateRowsFilter(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnInvalidateRowsFilter(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperInvalidateRowsFilter(QSortFilterProxyModel* self);
void QSortFilterProxyModel_InvalidateColumnsFilter(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnInvalidateColumnsFilter(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperInvalidateColumnsFilter(QSortFilterProxyModel* self);
QModelIndex* QSortFilterProxyModel_CreateSourceIndex(const QSortFilterProxyModel* self, int row, int col, void* internalPtr);
void QSortFilterProxyModel_OnCreateSourceIndex(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperCreateSourceIndex(const QSortFilterProxyModel* self, int row, int col, void* internalPtr);
QModelIndex* QSortFilterProxyModel_CreateIndex(const QSortFilterProxyModel* self, int row, int column);
void QSortFilterProxyModel_OnCreateIndex(const QSortFilterProxyModel* self, intptr_t slot);
QModelIndex* QSortFilterProxyModel_SuperCreateIndex(const QSortFilterProxyModel* self, int row, int column);
void QSortFilterProxyModel_EncodeData(const QSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
void QSortFilterProxyModel_OnEncodeData(const QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEncodeData(const QSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ indexes, QDataStream* stream);
bool QSortFilterProxyModel_DecodeData(QSortFilterProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void QSortFilterProxyModel_OnDecodeData(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperDecodeData(QSortFilterProxyModel* self, int row, int column, const QModelIndex* parent, QDataStream* stream);
void QSortFilterProxyModel_BeginInsertRows(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_OnBeginInsertRows(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperBeginInsertRows(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_EndInsertRows(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndInsertRows(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndInsertRows(QSortFilterProxyModel* self);
void QSortFilterProxyModel_BeginRemoveRows(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_OnBeginRemoveRows(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperBeginRemoveRows(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_EndRemoveRows(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndRemoveRows(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndRemoveRows(QSortFilterProxyModel* self);
bool QSortFilterProxyModel_BeginMoveRows(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void QSortFilterProxyModel_OnBeginMoveRows(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperBeginMoveRows(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationRow);
void QSortFilterProxyModel_EndMoveRows(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndMoveRows(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndMoveRows(QSortFilterProxyModel* self);
void QSortFilterProxyModel_BeginInsertColumns(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_OnBeginInsertColumns(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperBeginInsertColumns(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_EndInsertColumns(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndInsertColumns(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndInsertColumns(QSortFilterProxyModel* self);
void QSortFilterProxyModel_BeginRemoveColumns(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_OnBeginRemoveColumns(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperBeginRemoveColumns(QSortFilterProxyModel* self, const QModelIndex* parent, int first, int last);
void QSortFilterProxyModel_EndRemoveColumns(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndRemoveColumns(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndRemoveColumns(QSortFilterProxyModel* self);
bool QSortFilterProxyModel_BeginMoveColumns(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void QSortFilterProxyModel_OnBeginMoveColumns(QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperBeginMoveColumns(QSortFilterProxyModel* self, const QModelIndex* sourceParent, int sourceFirst, int sourceLast, const QModelIndex* destinationParent, int destinationColumn);
void QSortFilterProxyModel_EndMoveColumns(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndMoveColumns(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndMoveColumns(QSortFilterProxyModel* self);
void QSortFilterProxyModel_BeginResetModel(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnBeginResetModel(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperBeginResetModel(QSortFilterProxyModel* self);
void QSortFilterProxyModel_EndResetModel(QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnEndResetModel(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperEndResetModel(QSortFilterProxyModel* self);
void QSortFilterProxyModel_ChangePersistentIndex(QSortFilterProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void QSortFilterProxyModel_OnChangePersistentIndex(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperChangePersistentIndex(QSortFilterProxyModel* self, const QModelIndex* from, const QModelIndex* to);
void QSortFilterProxyModel_ChangePersistentIndexList(QSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
void QSortFilterProxyModel_OnChangePersistentIndexList(QSortFilterProxyModel* self, intptr_t slot);
void QSortFilterProxyModel_SuperChangePersistentIndexList(QSortFilterProxyModel* self, const libqt_list /* of QModelIndex* */ from, const libqt_list /* of QModelIndex* */ to);
libqt_list /* of QModelIndex* */ QSortFilterProxyModel_PersistentIndexList(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnPersistentIndexList(const QSortFilterProxyModel* self, intptr_t slot);
libqt_list /* of QModelIndex* */ QSortFilterProxyModel_SuperPersistentIndexList(const QSortFilterProxyModel* self);
QObject* QSortFilterProxyModel_Sender(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnSender(const QSortFilterProxyModel* self, intptr_t slot);
QObject* QSortFilterProxyModel_SuperSender(const QSortFilterProxyModel* self);
int QSortFilterProxyModel_SenderSignalIndex(const QSortFilterProxyModel* self);
void QSortFilterProxyModel_OnSenderSignalIndex(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperSenderSignalIndex(const QSortFilterProxyModel* self);
int QSortFilterProxyModel_Receivers(const QSortFilterProxyModel* self, const char* signal);
void QSortFilterProxyModel_OnReceivers(const QSortFilterProxyModel* self, intptr_t slot);
int QSortFilterProxyModel_SuperReceivers(const QSortFilterProxyModel* self, const char* signal);
bool QSortFilterProxyModel_IsSignalConnected(const QSortFilterProxyModel* self, const QMetaMethod* signal);
void QSortFilterProxyModel_OnIsSignalConnected(const QSortFilterProxyModel* self, intptr_t slot);
bool QSortFilterProxyModel_SuperIsSignalConnected(const QSortFilterProxyModel* self, const QMetaMethod* signal);
void QSortFilterProxyModel_Delete(QSortFilterProxyModel* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
