#pragma once
#ifndef SRCC_LIBQGRAPHICSPROXYWIDGET_H
#define SRCC_LIBQGRAPHICSPROXYWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QGraphicsItem QGraphicsItem;
typedef struct QGraphicsLayoutItem QGraphicsLayoutItem;
typedef struct QGraphicsObject QGraphicsObject;
typedef struct QGraphicsProxyWidget QGraphicsProxyWidget;
typedef struct QGraphicsSceneContextMenuEvent QGraphicsSceneContextMenuEvent;
typedef struct QGraphicsSceneDragDropEvent QGraphicsSceneDragDropEvent;
typedef struct QGraphicsSceneHoverEvent QGraphicsSceneHoverEvent;
typedef struct QGraphicsSceneMouseEvent QGraphicsSceneMouseEvent;
typedef struct QGraphicsSceneMoveEvent QGraphicsSceneMoveEvent;
typedef struct QGraphicsSceneResizeEvent QGraphicsSceneResizeEvent;
typedef struct QGraphicsSceneWheelEvent QGraphicsSceneWheelEvent;
typedef struct QGraphicsWidget QGraphicsWidget;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPainter QPainter;
typedef struct QPainterPath QPainterPath;
typedef struct QPointF QPointF;
typedef struct QRectF QRectF;
typedef struct QShowEvent QShowEvent;
typedef struct QSizeF QSizeF;
typedef struct QStyleOption QStyleOption;
typedef struct QStyleOptionGraphicsItem QStyleOptionGraphicsItem;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWidget QWidget;
#endif

QGraphicsProxyWidget* QGraphicsProxyWidget_new();
QGraphicsProxyWidget* QGraphicsProxyWidget_new2(QGraphicsItem* parent);
QGraphicsProxyWidget* QGraphicsProxyWidget_new3(QGraphicsItem* parent, int wFlags);
QMetaObject* QGraphicsProxyWidget_MetaObject(const QGraphicsProxyWidget* self);
void* QGraphicsProxyWidget_Metacast(QGraphicsProxyWidget* self, const char* param1);
int QGraphicsProxyWidget_Metacall(QGraphicsProxyWidget* self, int param1, int param2, void** param3);
void QGraphicsProxyWidget_SetWidget(QGraphicsProxyWidget* self, QWidget* widget);
QWidget* QGraphicsProxyWidget_Widget(const QGraphicsProxyWidget* self);
QRectF* QGraphicsProxyWidget_SubWidgetRect(const QGraphicsProxyWidget* self, const QWidget* widget);
void QGraphicsProxyWidget_SetGeometry(QGraphicsProxyWidget* self, const QRectF* rect);
void QGraphicsProxyWidget_Paint(QGraphicsProxyWidget* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
int QGraphicsProxyWidget_Type(const QGraphicsProxyWidget* self);
QGraphicsProxyWidget* QGraphicsProxyWidget_CreateProxyForChildWidget(QGraphicsProxyWidget* self, QWidget* child);
QVariant* QGraphicsProxyWidget_ItemChange(QGraphicsProxyWidget* self, int change, const QVariant* value);
bool QGraphicsProxyWidget_Event(QGraphicsProxyWidget* self, QEvent* event);
bool QGraphicsProxyWidget_EventFilter(QGraphicsProxyWidget* self, QObject* object, QEvent* event);
void QGraphicsProxyWidget_ShowEvent(QGraphicsProxyWidget* self, QShowEvent* event);
void QGraphicsProxyWidget_HideEvent(QGraphicsProxyWidget* self, QHideEvent* event);
void QGraphicsProxyWidget_ContextMenuEvent(QGraphicsProxyWidget* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsProxyWidget_DragEnterEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_DragLeaveEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_DragMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_DropEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_HoverEnterEvent(QGraphicsProxyWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsProxyWidget_HoverLeaveEvent(QGraphicsProxyWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsProxyWidget_HoverMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsProxyWidget_GrabMouseEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_UngrabMouseEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_MouseMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_MousePressEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_MouseReleaseEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_MouseDoubleClickEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_WheelEvent(QGraphicsProxyWidget* self, QGraphicsSceneWheelEvent* event);
void QGraphicsProxyWidget_KeyPressEvent(QGraphicsProxyWidget* self, QKeyEvent* event);
void QGraphicsProxyWidget_KeyReleaseEvent(QGraphicsProxyWidget* self, QKeyEvent* event);
void QGraphicsProxyWidget_FocusInEvent(QGraphicsProxyWidget* self, QFocusEvent* event);
void QGraphicsProxyWidget_FocusOutEvent(QGraphicsProxyWidget* self, QFocusEvent* event);
bool QGraphicsProxyWidget_FocusNextPrevChild(QGraphicsProxyWidget* self, bool next);
QVariant* QGraphicsProxyWidget_InputMethodQuery(const QGraphicsProxyWidget* self, int query);
void QGraphicsProxyWidget_InputMethodEvent(QGraphicsProxyWidget* self, QInputMethodEvent* event);
QSizeF* QGraphicsProxyWidget_SizeHint(const QGraphicsProxyWidget* self, int which, const QSizeF* constraint);
void QGraphicsProxyWidget_ResizeEvent(QGraphicsProxyWidget* self, QGraphicsSceneResizeEvent* event);
void QGraphicsProxyWidget_OnMetaObject(const QGraphicsProxyWidget* self, intptr_t slot);
QMetaObject* QGraphicsProxyWidget_SuperMetaObject(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnMetacast(QGraphicsProxyWidget* self, intptr_t slot);
void* QGraphicsProxyWidget_SuperMetacast(QGraphicsProxyWidget* self, const char* param1);
void QGraphicsProxyWidget_OnMetacall(QGraphicsProxyWidget* self, intptr_t slot);
int QGraphicsProxyWidget_SuperMetacall(QGraphicsProxyWidget* self, int param1, int param2, void** param3);
void QGraphicsProxyWidget_OnSetGeometry(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperSetGeometry(QGraphicsProxyWidget* self, const QRectF* rect);
void QGraphicsProxyWidget_OnPaint(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperPaint(QGraphicsProxyWidget* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsProxyWidget_OnType(const QGraphicsProxyWidget* self, intptr_t slot);
int QGraphicsProxyWidget_SuperType(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnItemChange(QGraphicsProxyWidget* self, intptr_t slot);
QVariant* QGraphicsProxyWidget_SuperItemChange(QGraphicsProxyWidget* self, int change, const QVariant* value);
void QGraphicsProxyWidget_OnEvent(QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnEventFilter(QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperEventFilter(QGraphicsProxyWidget* self, QObject* object, QEvent* event);
void QGraphicsProxyWidget_OnShowEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperShowEvent(QGraphicsProxyWidget* self, QShowEvent* event);
void QGraphicsProxyWidget_OnHideEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperHideEvent(QGraphicsProxyWidget* self, QHideEvent* event);
void QGraphicsProxyWidget_OnContextMenuEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperContextMenuEvent(QGraphicsProxyWidget* self, QGraphicsSceneContextMenuEvent* event);
void QGraphicsProxyWidget_OnDragEnterEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperDragEnterEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_OnDragLeaveEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperDragLeaveEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_OnDragMoveEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperDragMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_OnDropEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperDropEvent(QGraphicsProxyWidget* self, QGraphicsSceneDragDropEvent* event);
void QGraphicsProxyWidget_OnHoverEnterEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperHoverEnterEvent(QGraphicsProxyWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsProxyWidget_OnHoverLeaveEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperHoverLeaveEvent(QGraphicsProxyWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsProxyWidget_OnHoverMoveEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperHoverMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneHoverEvent* event);
void QGraphicsProxyWidget_OnGrabMouseEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperGrabMouseEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnUngrabMouseEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperUngrabMouseEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnMouseMoveEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperMouseMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_OnMousePressEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperMousePressEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_OnMouseReleaseEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperMouseReleaseEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_OnMouseDoubleClickEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperMouseDoubleClickEvent(QGraphicsProxyWidget* self, QGraphicsSceneMouseEvent* event);
void QGraphicsProxyWidget_OnWheelEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperWheelEvent(QGraphicsProxyWidget* self, QGraphicsSceneWheelEvent* event);
void QGraphicsProxyWidget_OnKeyPressEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperKeyPressEvent(QGraphicsProxyWidget* self, QKeyEvent* event);
void QGraphicsProxyWidget_OnKeyReleaseEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperKeyReleaseEvent(QGraphicsProxyWidget* self, QKeyEvent* event);
void QGraphicsProxyWidget_OnFocusInEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperFocusInEvent(QGraphicsProxyWidget* self, QFocusEvent* event);
void QGraphicsProxyWidget_OnFocusOutEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperFocusOutEvent(QGraphicsProxyWidget* self, QFocusEvent* event);
void QGraphicsProxyWidget_OnFocusNextPrevChild(QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperFocusNextPrevChild(QGraphicsProxyWidget* self, bool next);
void QGraphicsProxyWidget_OnInputMethodQuery(const QGraphicsProxyWidget* self, intptr_t slot);
QVariant* QGraphicsProxyWidget_SuperInputMethodQuery(const QGraphicsProxyWidget* self, int query);
void QGraphicsProxyWidget_OnInputMethodEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperInputMethodEvent(QGraphicsProxyWidget* self, QInputMethodEvent* event);
void QGraphicsProxyWidget_OnSizeHint(const QGraphicsProxyWidget* self, intptr_t slot);
QSizeF* QGraphicsProxyWidget_SuperSizeHint(const QGraphicsProxyWidget* self, int which, const QSizeF* constraint);
void QGraphicsProxyWidget_OnResizeEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperResizeEvent(QGraphicsProxyWidget* self, QGraphicsSceneResizeEvent* event);
void QGraphicsProxyWidget_GetContentsMargins(const QGraphicsProxyWidget* self, double* left, double* top, double* right, double* bottom);
void QGraphicsProxyWidget_OnGetContentsMargins(const QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperGetContentsMargins(const QGraphicsProxyWidget* self, double* left, double* top, double* right, double* bottom);
void QGraphicsProxyWidget_PaintWindowFrame(QGraphicsProxyWidget* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
void QGraphicsProxyWidget_OnPaintWindowFrame(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperPaintWindowFrame(QGraphicsProxyWidget* self, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
QRectF* QGraphicsProxyWidget_BoundingRect(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnBoundingRect(const QGraphicsProxyWidget* self, intptr_t slot);
QRectF* QGraphicsProxyWidget_SuperBoundingRect(const QGraphicsProxyWidget* self);
QPainterPath* QGraphicsProxyWidget_Shape(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnShape(const QGraphicsProxyWidget* self, intptr_t slot);
QPainterPath* QGraphicsProxyWidget_SuperShape(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_InitStyleOption(const QGraphicsProxyWidget* self, QStyleOption* option);
void QGraphicsProxyWidget_OnInitStyleOption(const QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperInitStyleOption(const QGraphicsProxyWidget* self, QStyleOption* option);
void QGraphicsProxyWidget_UpdateGeometry(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnUpdateGeometry(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperUpdateGeometry(QGraphicsProxyWidget* self);
QVariant* QGraphicsProxyWidget_PropertyChange(QGraphicsProxyWidget* self, const libqt_string propertyName, const QVariant* value);
void QGraphicsProxyWidget_OnPropertyChange(QGraphicsProxyWidget* self, intptr_t slot);
QVariant* QGraphicsProxyWidget_SuperPropertyChange(QGraphicsProxyWidget* self, const libqt_string propertyName, const QVariant* value);
bool QGraphicsProxyWidget_SceneEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnSceneEvent(QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperSceneEvent(QGraphicsProxyWidget* self, QEvent* event);
bool QGraphicsProxyWidget_WindowFrameEvent(QGraphicsProxyWidget* self, QEvent* e);
void QGraphicsProxyWidget_OnWindowFrameEvent(QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperWindowFrameEvent(QGraphicsProxyWidget* self, QEvent* e);
int QGraphicsProxyWidget_WindowFrameSectionAt(const QGraphicsProxyWidget* self, const QPointF* pos);
void QGraphicsProxyWidget_OnWindowFrameSectionAt(const QGraphicsProxyWidget* self, intptr_t slot);
int QGraphicsProxyWidget_SuperWindowFrameSectionAt(const QGraphicsProxyWidget* self, const QPointF* pos);
void QGraphicsProxyWidget_ChangeEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnChangeEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperChangeEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_CloseEvent(QGraphicsProxyWidget* self, QCloseEvent* event);
void QGraphicsProxyWidget_OnCloseEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperCloseEvent(QGraphicsProxyWidget* self, QCloseEvent* event);
void QGraphicsProxyWidget_MoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneMoveEvent* event);
void QGraphicsProxyWidget_OnMoveEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperMoveEvent(QGraphicsProxyWidget* self, QGraphicsSceneMoveEvent* event);
void QGraphicsProxyWidget_PolishEvent(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnPolishEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperPolishEvent(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_GrabKeyboardEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnGrabKeyboardEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperGrabKeyboardEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_UngrabKeyboardEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnUngrabKeyboardEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperUngrabKeyboardEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_TimerEvent(QGraphicsProxyWidget* self, QTimerEvent* event);
void QGraphicsProxyWidget_OnTimerEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperTimerEvent(QGraphicsProxyWidget* self, QTimerEvent* event);
void QGraphicsProxyWidget_ChildEvent(QGraphicsProxyWidget* self, QChildEvent* event);
void QGraphicsProxyWidget_OnChildEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperChildEvent(QGraphicsProxyWidget* self, QChildEvent* event);
void QGraphicsProxyWidget_CustomEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_OnCustomEvent(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperCustomEvent(QGraphicsProxyWidget* self, QEvent* event);
void QGraphicsProxyWidget_ConnectNotify(QGraphicsProxyWidget* self, const QMetaMethod* signal);
void QGraphicsProxyWidget_OnConnectNotify(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperConnectNotify(QGraphicsProxyWidget* self, const QMetaMethod* signal);
void QGraphicsProxyWidget_DisconnectNotify(QGraphicsProxyWidget* self, const QMetaMethod* signal);
void QGraphicsProxyWidget_OnDisconnectNotify(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperDisconnectNotify(QGraphicsProxyWidget* self, const QMetaMethod* signal);
void QGraphicsProxyWidget_Advance(QGraphicsProxyWidget* self, int phase);
void QGraphicsProxyWidget_OnAdvance(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperAdvance(QGraphicsProxyWidget* self, int phase);
bool QGraphicsProxyWidget_Contains(const QGraphicsProxyWidget* self, const QPointF* point);
void QGraphicsProxyWidget_OnContains(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperContains(const QGraphicsProxyWidget* self, const QPointF* point);
bool QGraphicsProxyWidget_CollidesWithItem(const QGraphicsProxyWidget* self, const QGraphicsItem* other, int mode);
void QGraphicsProxyWidget_OnCollidesWithItem(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperCollidesWithItem(const QGraphicsProxyWidget* self, const QGraphicsItem* other, int mode);
bool QGraphicsProxyWidget_CollidesWithPath(const QGraphicsProxyWidget* self, const QPainterPath* path, int mode);
void QGraphicsProxyWidget_OnCollidesWithPath(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperCollidesWithPath(const QGraphicsProxyWidget* self, const QPainterPath* path, int mode);
bool QGraphicsProxyWidget_IsObscuredBy(const QGraphicsProxyWidget* self, const QGraphicsItem* item);
void QGraphicsProxyWidget_OnIsObscuredBy(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperIsObscuredBy(const QGraphicsProxyWidget* self, const QGraphicsItem* item);
QPainterPath* QGraphicsProxyWidget_OpaqueArea(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnOpaqueArea(const QGraphicsProxyWidget* self, intptr_t slot);
QPainterPath* QGraphicsProxyWidget_SuperOpaqueArea(const QGraphicsProxyWidget* self);
bool QGraphicsProxyWidget_SceneEventFilter(QGraphicsProxyWidget* self, QGraphicsItem* watched, QEvent* event);
void QGraphicsProxyWidget_OnSceneEventFilter(QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperSceneEventFilter(QGraphicsProxyWidget* self, QGraphicsItem* watched, QEvent* event);
bool QGraphicsProxyWidget_SupportsExtension(const QGraphicsProxyWidget* self, int extension);
void QGraphicsProxyWidget_OnSupportsExtension(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperSupportsExtension(const QGraphicsProxyWidget* self, int extension);
void QGraphicsProxyWidget_SetExtension(QGraphicsProxyWidget* self, int extension, const QVariant* variant);
void QGraphicsProxyWidget_OnSetExtension(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperSetExtension(QGraphicsProxyWidget* self, int extension, const QVariant* variant);
QVariant* QGraphicsProxyWidget_Extension(const QGraphicsProxyWidget* self, const QVariant* variant);
void QGraphicsProxyWidget_OnExtension(const QGraphicsProxyWidget* self, intptr_t slot);
QVariant* QGraphicsProxyWidget_SuperExtension(const QGraphicsProxyWidget* self, const QVariant* variant);
bool QGraphicsProxyWidget_IsEmpty(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnIsEmpty(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperIsEmpty(const QGraphicsProxyWidget* self);
QGraphicsProxyWidget* QGraphicsProxyWidget_NewProxyWidget(QGraphicsProxyWidget* self, const QWidget* param1);
void QGraphicsProxyWidget_OnNewProxyWidget(QGraphicsProxyWidget* self, intptr_t slot);
QGraphicsProxyWidget* QGraphicsProxyWidget_SuperNewProxyWidget(QGraphicsProxyWidget* self, const QWidget* param1);
void QGraphicsProxyWidget_UpdateMicroFocus(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnUpdateMicroFocus(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperUpdateMicroFocus(QGraphicsProxyWidget* self);
QObject* QGraphicsProxyWidget_Sender(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnSender(const QGraphicsProxyWidget* self, intptr_t slot);
QObject* QGraphicsProxyWidget_SuperSender(const QGraphicsProxyWidget* self);
int QGraphicsProxyWidget_SenderSignalIndex(const QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnSenderSignalIndex(const QGraphicsProxyWidget* self, intptr_t slot);
int QGraphicsProxyWidget_SuperSenderSignalIndex(const QGraphicsProxyWidget* self);
int QGraphicsProxyWidget_Receivers(const QGraphicsProxyWidget* self, const char* signal);
void QGraphicsProxyWidget_OnReceivers(const QGraphicsProxyWidget* self, intptr_t slot);
int QGraphicsProxyWidget_SuperReceivers(const QGraphicsProxyWidget* self, const char* signal);
bool QGraphicsProxyWidget_IsSignalConnected(const QGraphicsProxyWidget* self, const QMetaMethod* signal);
void QGraphicsProxyWidget_OnIsSignalConnected(const QGraphicsProxyWidget* self, intptr_t slot);
bool QGraphicsProxyWidget_SuperIsSignalConnected(const QGraphicsProxyWidget* self, const QMetaMethod* signal);
void QGraphicsProxyWidget_AddToIndex(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnAddToIndex(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperAddToIndex(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_RemoveFromIndex(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnRemoveFromIndex(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperRemoveFromIndex(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_PrepareGeometryChange(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_OnPrepareGeometryChange(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperPrepareGeometryChange(QGraphicsProxyWidget* self);
void QGraphicsProxyWidget_SetGraphicsItem(QGraphicsProxyWidget* self, QGraphicsItem* item);
void QGraphicsProxyWidget_OnSetGraphicsItem(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperSetGraphicsItem(QGraphicsProxyWidget* self, QGraphicsItem* item);
void QGraphicsProxyWidget_SetOwnedByLayout(QGraphicsProxyWidget* self, bool ownedByLayout);
void QGraphicsProxyWidget_OnSetOwnedByLayout(QGraphicsProxyWidget* self, intptr_t slot);
void QGraphicsProxyWidget_SuperSetOwnedByLayout(QGraphicsProxyWidget* self, bool ownedByLayout);
void QGraphicsProxyWidget_Delete(QGraphicsProxyWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
