#pragma once
#ifndef SRC_PRINTSUPPORTC_LIBQPRINTDIALOG_H
#define SRC_PRINTSUPPORTC_LIBQPRINTDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAbstractPrintDialog QAbstractPrintDialog;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QPrintDialog QPrintDialog;
typedef struct QPrinter QPrinter;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QPrintDialog* QPrintDialog_new(QWidget* parent);
QPrintDialog* QPrintDialog_new2(QPrinter* printer);
QPrintDialog* QPrintDialog_new3();
QPrintDialog* QPrintDialog_new4(QPrinter* printer, QWidget* parent);
QMetaObject* QPrintDialog_MetaObject(const QPrintDialog* self);
void* QPrintDialog_Metacast(QPrintDialog* self, const char* param1);
int QPrintDialog_Metacall(QPrintDialog* self, int param1, int param2, void** param3);
int QPrintDialog_Exec(QPrintDialog* self);
void QPrintDialog_Accept(QPrintDialog* self);
void QPrintDialog_Done(QPrintDialog* self, int result);
void QPrintDialog_SetOption(QPrintDialog* self, int option);
bool QPrintDialog_TestOption(const QPrintDialog* self, int option);
void QPrintDialog_SetOptions(QPrintDialog* self, int options);
int QPrintDialog_Options(const QPrintDialog* self);
void QPrintDialog_SetVisible(QPrintDialog* self, bool visible);
void QPrintDialog_Accepted(QPrintDialog* self, QPrinter* printer);
void QPrintDialog_SetOption2(QPrintDialog* self, int option, bool on);
void QPrintDialog_OnMetaObject(const QPrintDialog* self, intptr_t slot);
QMetaObject* QPrintDialog_SuperMetaObject(const QPrintDialog* self);
void QPrintDialog_OnMetacast(QPrintDialog* self, intptr_t slot);
void* QPrintDialog_SuperMetacast(QPrintDialog* self, const char* param1);
void QPrintDialog_OnMetacall(QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperMetacall(QPrintDialog* self, int param1, int param2, void** param3);
void QPrintDialog_OnExec(QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperExec(QPrintDialog* self);
void QPrintDialog_OnAccept(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperAccept(QPrintDialog* self);
void QPrintDialog_OnDone(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDone(QPrintDialog* self, int result);
void QPrintDialog_OnSetVisible(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperSetVisible(QPrintDialog* self, bool visible);
QSize* QPrintDialog_SizeHint(const QPrintDialog* self);
void QPrintDialog_OnSizeHint(const QPrintDialog* self, intptr_t slot);
QSize* QPrintDialog_SuperSizeHint(const QPrintDialog* self);
QSize* QPrintDialog_MinimumSizeHint(const QPrintDialog* self);
void QPrintDialog_OnMinimumSizeHint(const QPrintDialog* self, intptr_t slot);
QSize* QPrintDialog_SuperMinimumSizeHint(const QPrintDialog* self);
void QPrintDialog_Open(QPrintDialog* self);
void QPrintDialog_OnOpen(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperOpen(QPrintDialog* self);
void QPrintDialog_Reject(QPrintDialog* self);
void QPrintDialog_OnReject(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperReject(QPrintDialog* self);
void QPrintDialog_KeyPressEvent(QPrintDialog* self, QKeyEvent* param1);
void QPrintDialog_OnKeyPressEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperKeyPressEvent(QPrintDialog* self, QKeyEvent* param1);
void QPrintDialog_CloseEvent(QPrintDialog* self, QCloseEvent* param1);
void QPrintDialog_OnCloseEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperCloseEvent(QPrintDialog* self, QCloseEvent* param1);
void QPrintDialog_ShowEvent(QPrintDialog* self, QShowEvent* param1);
void QPrintDialog_OnShowEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperShowEvent(QPrintDialog* self, QShowEvent* param1);
void QPrintDialog_ResizeEvent(QPrintDialog* self, QResizeEvent* param1);
void QPrintDialog_OnResizeEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperResizeEvent(QPrintDialog* self, QResizeEvent* param1);
void QPrintDialog_ContextMenuEvent(QPrintDialog* self, QContextMenuEvent* param1);
void QPrintDialog_OnContextMenuEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperContextMenuEvent(QPrintDialog* self, QContextMenuEvent* param1);
bool QPrintDialog_EventFilter(QPrintDialog* self, QObject* param1, QEvent* param2);
void QPrintDialog_OnEventFilter(QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperEventFilter(QPrintDialog* self, QObject* param1, QEvent* param2);
int QPrintDialog_DevType(const QPrintDialog* self);
void QPrintDialog_OnDevType(const QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperDevType(const QPrintDialog* self);
int QPrintDialog_HeightForWidth(const QPrintDialog* self, int param1);
void QPrintDialog_OnHeightForWidth(const QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperHeightForWidth(const QPrintDialog* self, int param1);
bool QPrintDialog_HasHeightForWidth(const QPrintDialog* self);
void QPrintDialog_OnHasHeightForWidth(const QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperHasHeightForWidth(const QPrintDialog* self);
QPaintEngine* QPrintDialog_PaintEngine(const QPrintDialog* self);
void QPrintDialog_OnPaintEngine(const QPrintDialog* self, intptr_t slot);
QPaintEngine* QPrintDialog_SuperPaintEngine(const QPrintDialog* self);
bool QPrintDialog_Event(QPrintDialog* self, QEvent* event);
void QPrintDialog_OnEvent(QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperEvent(QPrintDialog* self, QEvent* event);
void QPrintDialog_MousePressEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_OnMousePressEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperMousePressEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_MouseReleaseEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_OnMouseReleaseEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperMouseReleaseEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_MouseDoubleClickEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_OnMouseDoubleClickEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperMouseDoubleClickEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_MouseMoveEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_OnMouseMoveEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperMouseMoveEvent(QPrintDialog* self, QMouseEvent* event);
void QPrintDialog_WheelEvent(QPrintDialog* self, QWheelEvent* event);
void QPrintDialog_OnWheelEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperWheelEvent(QPrintDialog* self, QWheelEvent* event);
void QPrintDialog_KeyReleaseEvent(QPrintDialog* self, QKeyEvent* event);
void QPrintDialog_OnKeyReleaseEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperKeyReleaseEvent(QPrintDialog* self, QKeyEvent* event);
void QPrintDialog_FocusInEvent(QPrintDialog* self, QFocusEvent* event);
void QPrintDialog_OnFocusInEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperFocusInEvent(QPrintDialog* self, QFocusEvent* event);
void QPrintDialog_FocusOutEvent(QPrintDialog* self, QFocusEvent* event);
void QPrintDialog_OnFocusOutEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperFocusOutEvent(QPrintDialog* self, QFocusEvent* event);
void QPrintDialog_EnterEvent(QPrintDialog* self, QEnterEvent* event);
void QPrintDialog_OnEnterEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperEnterEvent(QPrintDialog* self, QEnterEvent* event);
void QPrintDialog_LeaveEvent(QPrintDialog* self, QEvent* event);
void QPrintDialog_OnLeaveEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperLeaveEvent(QPrintDialog* self, QEvent* event);
void QPrintDialog_PaintEvent(QPrintDialog* self, QPaintEvent* event);
void QPrintDialog_OnPaintEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperPaintEvent(QPrintDialog* self, QPaintEvent* event);
void QPrintDialog_MoveEvent(QPrintDialog* self, QMoveEvent* event);
void QPrintDialog_OnMoveEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperMoveEvent(QPrintDialog* self, QMoveEvent* event);
void QPrintDialog_TabletEvent(QPrintDialog* self, QTabletEvent* event);
void QPrintDialog_OnTabletEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperTabletEvent(QPrintDialog* self, QTabletEvent* event);
void QPrintDialog_ActionEvent(QPrintDialog* self, QActionEvent* event);
void QPrintDialog_OnActionEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperActionEvent(QPrintDialog* self, QActionEvent* event);
void QPrintDialog_DragEnterEvent(QPrintDialog* self, QDragEnterEvent* event);
void QPrintDialog_OnDragEnterEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDragEnterEvent(QPrintDialog* self, QDragEnterEvent* event);
void QPrintDialog_DragMoveEvent(QPrintDialog* self, QDragMoveEvent* event);
void QPrintDialog_OnDragMoveEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDragMoveEvent(QPrintDialog* self, QDragMoveEvent* event);
void QPrintDialog_DragLeaveEvent(QPrintDialog* self, QDragLeaveEvent* event);
void QPrintDialog_OnDragLeaveEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDragLeaveEvent(QPrintDialog* self, QDragLeaveEvent* event);
void QPrintDialog_DropEvent(QPrintDialog* self, QDropEvent* event);
void QPrintDialog_OnDropEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDropEvent(QPrintDialog* self, QDropEvent* event);
void QPrintDialog_HideEvent(QPrintDialog* self, QHideEvent* event);
void QPrintDialog_OnHideEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperHideEvent(QPrintDialog* self, QHideEvent* event);
bool QPrintDialog_NativeEvent(QPrintDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void QPrintDialog_OnNativeEvent(QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperNativeEvent(QPrintDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void QPrintDialog_ChangeEvent(QPrintDialog* self, QEvent* param1);
void QPrintDialog_OnChangeEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperChangeEvent(QPrintDialog* self, QEvent* param1);
int QPrintDialog_Metric(const QPrintDialog* self, int param1);
void QPrintDialog_OnMetric(const QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperMetric(const QPrintDialog* self, int param1);
void QPrintDialog_InitPainter(const QPrintDialog* self, QPainter* painter);
void QPrintDialog_OnInitPainter(const QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperInitPainter(const QPrintDialog* self, QPainter* painter);
QPaintDevice* QPrintDialog_Redirected(const QPrintDialog* self, QPoint* offset);
void QPrintDialog_OnRedirected(const QPrintDialog* self, intptr_t slot);
QPaintDevice* QPrintDialog_SuperRedirected(const QPrintDialog* self, QPoint* offset);
QPainter* QPrintDialog_SharedPainter(const QPrintDialog* self);
void QPrintDialog_OnSharedPainter(const QPrintDialog* self, intptr_t slot);
QPainter* QPrintDialog_SuperSharedPainter(const QPrintDialog* self);
void QPrintDialog_InputMethodEvent(QPrintDialog* self, QInputMethodEvent* param1);
void QPrintDialog_OnInputMethodEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperInputMethodEvent(QPrintDialog* self, QInputMethodEvent* param1);
QVariant* QPrintDialog_InputMethodQuery(const QPrintDialog* self, int param1);
void QPrintDialog_OnInputMethodQuery(const QPrintDialog* self, intptr_t slot);
QVariant* QPrintDialog_SuperInputMethodQuery(const QPrintDialog* self, int param1);
bool QPrintDialog_FocusNextPrevChild(QPrintDialog* self, bool next);
void QPrintDialog_OnFocusNextPrevChild(QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperFocusNextPrevChild(QPrintDialog* self, bool next);
void QPrintDialog_TimerEvent(QPrintDialog* self, QTimerEvent* event);
void QPrintDialog_OnTimerEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperTimerEvent(QPrintDialog* self, QTimerEvent* event);
void QPrintDialog_ChildEvent(QPrintDialog* self, QChildEvent* event);
void QPrintDialog_OnChildEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperChildEvent(QPrintDialog* self, QChildEvent* event);
void QPrintDialog_CustomEvent(QPrintDialog* self, QEvent* event);
void QPrintDialog_OnCustomEvent(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperCustomEvent(QPrintDialog* self, QEvent* event);
void QPrintDialog_ConnectNotify(QPrintDialog* self, const QMetaMethod* signal);
void QPrintDialog_OnConnectNotify(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperConnectNotify(QPrintDialog* self, const QMetaMethod* signal);
void QPrintDialog_DisconnectNotify(QPrintDialog* self, const QMetaMethod* signal);
void QPrintDialog_OnDisconnectNotify(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDisconnectNotify(QPrintDialog* self, const QMetaMethod* signal);
void QPrintDialog_AdjustPosition(QPrintDialog* self, QWidget* param1);
void QPrintDialog_OnAdjustPosition(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperAdjustPosition(QPrintDialog* self, QWidget* param1);
void QPrintDialog_UpdateMicroFocus(QPrintDialog* self);
void QPrintDialog_OnUpdateMicroFocus(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperUpdateMicroFocus(QPrintDialog* self);
void QPrintDialog_Create(QPrintDialog* self);
void QPrintDialog_OnCreate(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperCreate(QPrintDialog* self);
void QPrintDialog_Destroy(QPrintDialog* self);
void QPrintDialog_OnDestroy(QPrintDialog* self, intptr_t slot);
void QPrintDialog_SuperDestroy(QPrintDialog* self);
bool QPrintDialog_FocusNextChild(QPrintDialog* self);
void QPrintDialog_OnFocusNextChild(QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperFocusNextChild(QPrintDialog* self);
bool QPrintDialog_FocusPreviousChild(QPrintDialog* self);
void QPrintDialog_OnFocusPreviousChild(QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperFocusPreviousChild(QPrintDialog* self);
QObject* QPrintDialog_Sender(const QPrintDialog* self);
void QPrintDialog_OnSender(const QPrintDialog* self, intptr_t slot);
QObject* QPrintDialog_SuperSender(const QPrintDialog* self);
int QPrintDialog_SenderSignalIndex(const QPrintDialog* self);
void QPrintDialog_OnSenderSignalIndex(const QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperSenderSignalIndex(const QPrintDialog* self);
int QPrintDialog_Receivers(const QPrintDialog* self, const char* signal);
void QPrintDialog_OnReceivers(const QPrintDialog* self, intptr_t slot);
int QPrintDialog_SuperReceivers(const QPrintDialog* self, const char* signal);
bool QPrintDialog_IsSignalConnected(const QPrintDialog* self, const QMetaMethod* signal);
void QPrintDialog_OnIsSignalConnected(const QPrintDialog* self, intptr_t slot);
bool QPrintDialog_SuperIsSignalConnected(const QPrintDialog* self, const QMetaMethod* signal);
double QPrintDialog_GetDecodedMetricF(const QPrintDialog* self, int metricA, int metricB);
void QPrintDialog_OnGetDecodedMetricF(const QPrintDialog* self, intptr_t slot);
double QPrintDialog_SuperGetDecodedMetricF(const QPrintDialog* self, int metricA, int metricB);
void QPrintDialog_Delete(QPrintDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
