#pragma once
#ifndef SRC_EXTRAS_KITEMVIEWSC_LIBKTREEWIDGETSEARCHLINE_H
#define SRC_EXTRAS_KITEMVIEWSC_LIBKTREEWIDGETSEARCHLINE_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KTreeWidgetSearchLine KTreeWidgetSearchLine;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QLineEdit QLineEdit;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QStyleOptionFrame QStyleOptionFrame;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTreeWidget QTreeWidget;
typedef struct QTreeWidgetItem QTreeWidgetItem;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KTreeWidgetSearchLine* KTreeWidgetSearchLine_new(QWidget* parent);
KTreeWidgetSearchLine* KTreeWidgetSearchLine_new2();
KTreeWidgetSearchLine* KTreeWidgetSearchLine_new3(QWidget* parent, const libqt_list /* of QTreeWidget* */ treeWidgets);
KTreeWidgetSearchLine* KTreeWidgetSearchLine_new4(QWidget* parent, QTreeWidget* treeWidget);
QMetaObject* KTreeWidgetSearchLine_MetaObject(const KTreeWidgetSearchLine* self);
void* KTreeWidgetSearchLine_Metacast(KTreeWidgetSearchLine* self, const char* param1);
int KTreeWidgetSearchLine_Metacall(KTreeWidgetSearchLine* self, int param1, int param2, void** param3);
int KTreeWidgetSearchLine_CaseSensitivity(const KTreeWidgetSearchLine* self);
libqt_list /* of int */ KTreeWidgetSearchLine_SearchColumns(const KTreeWidgetSearchLine* self);
bool KTreeWidgetSearchLine_KeepParentsVisible(const KTreeWidgetSearchLine* self);
QTreeWidget* KTreeWidgetSearchLine_TreeWidget(const KTreeWidgetSearchLine* self);
libqt_list /* of QTreeWidget* */ KTreeWidgetSearchLine_TreeWidgets(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_HiddenChanged(KTreeWidgetSearchLine* self, QTreeWidgetItem* param1, bool param2);
void KTreeWidgetSearchLine_Connect_HiddenChanged(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SearchUpdated(KTreeWidgetSearchLine* self, const libqt_string searchString);
void KTreeWidgetSearchLine_Connect_SearchUpdated(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_CaseSensitivityChanged(KTreeWidgetSearchLine* self, int caseSensitivity);
void KTreeWidgetSearchLine_Connect_CaseSensitivityChanged(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_KeepParentsVisibleChanged(KTreeWidgetSearchLine* self, bool keepParentsVisible);
void KTreeWidgetSearchLine_Connect_KeepParentsVisibleChanged(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_AddTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* treeWidget);
void KTreeWidgetSearchLine_RemoveTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* treeWidget);
void KTreeWidgetSearchLine_UpdateSearch(KTreeWidgetSearchLine* self, const libqt_string pattern);
void KTreeWidgetSearchLine_SetCaseSensitivity(KTreeWidgetSearchLine* self, int caseSensitivity);
void KTreeWidgetSearchLine_SetKeepParentsVisible(KTreeWidgetSearchLine* self, bool value);
void KTreeWidgetSearchLine_SetSearchColumns(KTreeWidgetSearchLine* self, const libqt_list /* of int */ columns);
void KTreeWidgetSearchLine_SetTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* treeWidget);
void KTreeWidgetSearchLine_SetTreeWidgets(KTreeWidgetSearchLine* self, const libqt_list /* of QTreeWidget* */ treeWidgets);
bool KTreeWidgetSearchLine_ItemMatches(const KTreeWidgetSearchLine* self, const QTreeWidgetItem* item, const libqt_string pattern);
void KTreeWidgetSearchLine_ContextMenuEvent(KTreeWidgetSearchLine* self, QContextMenuEvent* param1);
void KTreeWidgetSearchLine_UpdateSearch2(KTreeWidgetSearchLine* self, QTreeWidget* treeWidget);
void KTreeWidgetSearchLine_ConnectTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* param1);
void KTreeWidgetSearchLine_DisconnectTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* param1);
bool KTreeWidgetSearchLine_CanChooseColumnsCheck(KTreeWidgetSearchLine* self);
bool KTreeWidgetSearchLine_Event(KTreeWidgetSearchLine* self, QEvent* event);
void KTreeWidgetSearchLine_OnMetaObject(const KTreeWidgetSearchLine* self, intptr_t slot);
QMetaObject* KTreeWidgetSearchLine_SuperMetaObject(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnMetacast(KTreeWidgetSearchLine* self, intptr_t slot);
void* KTreeWidgetSearchLine_SuperMetacast(KTreeWidgetSearchLine* self, const char* param1);
void KTreeWidgetSearchLine_OnMetacall(KTreeWidgetSearchLine* self, intptr_t slot);
int KTreeWidgetSearchLine_SuperMetacall(KTreeWidgetSearchLine* self, int param1, int param2, void** param3);
void KTreeWidgetSearchLine_OnUpdateSearch(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperUpdateSearch(KTreeWidgetSearchLine* self, const libqt_string pattern);
void KTreeWidgetSearchLine_OnItemMatches(const KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperItemMatches(const KTreeWidgetSearchLine* self, const QTreeWidgetItem* item, const libqt_string pattern);
void KTreeWidgetSearchLine_OnContextMenuEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperContextMenuEvent(KTreeWidgetSearchLine* self, QContextMenuEvent* param1);
void KTreeWidgetSearchLine_OnUpdateSearch2(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperUpdateSearch2(KTreeWidgetSearchLine* self, QTreeWidget* treeWidget);
void KTreeWidgetSearchLine_OnConnectTreeWidget(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperConnectTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* param1);
void KTreeWidgetSearchLine_OnDisconnectTreeWidget(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDisconnectTreeWidget(KTreeWidgetSearchLine* self, QTreeWidget* param1);
void KTreeWidgetSearchLine_OnCanChooseColumnsCheck(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperCanChooseColumnsCheck(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnEvent(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperEvent(KTreeWidgetSearchLine* self, QEvent* event);
QSize* KTreeWidgetSearchLine_SizeHint(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnSizeHint(const KTreeWidgetSearchLine* self, intptr_t slot);
QSize* KTreeWidgetSearchLine_SuperSizeHint(const KTreeWidgetSearchLine* self);
QSize* KTreeWidgetSearchLine_MinimumSizeHint(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnMinimumSizeHint(const KTreeWidgetSearchLine* self, intptr_t slot);
QSize* KTreeWidgetSearchLine_SuperMinimumSizeHint(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_MousePressEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_OnMousePressEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperMousePressEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_MouseMoveEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_OnMouseMoveEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperMouseMoveEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_MouseReleaseEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_OnMouseReleaseEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperMouseReleaseEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_MouseDoubleClickEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_OnMouseDoubleClickEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperMouseDoubleClickEvent(KTreeWidgetSearchLine* self, QMouseEvent* param1);
void KTreeWidgetSearchLine_KeyPressEvent(KTreeWidgetSearchLine* self, QKeyEvent* param1);
void KTreeWidgetSearchLine_OnKeyPressEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperKeyPressEvent(KTreeWidgetSearchLine* self, QKeyEvent* param1);
void KTreeWidgetSearchLine_KeyReleaseEvent(KTreeWidgetSearchLine* self, QKeyEvent* param1);
void KTreeWidgetSearchLine_OnKeyReleaseEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperKeyReleaseEvent(KTreeWidgetSearchLine* self, QKeyEvent* param1);
void KTreeWidgetSearchLine_FocusInEvent(KTreeWidgetSearchLine* self, QFocusEvent* param1);
void KTreeWidgetSearchLine_OnFocusInEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperFocusInEvent(KTreeWidgetSearchLine* self, QFocusEvent* param1);
void KTreeWidgetSearchLine_FocusOutEvent(KTreeWidgetSearchLine* self, QFocusEvent* param1);
void KTreeWidgetSearchLine_OnFocusOutEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperFocusOutEvent(KTreeWidgetSearchLine* self, QFocusEvent* param1);
void KTreeWidgetSearchLine_PaintEvent(KTreeWidgetSearchLine* self, QPaintEvent* param1);
void KTreeWidgetSearchLine_OnPaintEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperPaintEvent(KTreeWidgetSearchLine* self, QPaintEvent* param1);
void KTreeWidgetSearchLine_DragEnterEvent(KTreeWidgetSearchLine* self, QDragEnterEvent* param1);
void KTreeWidgetSearchLine_OnDragEnterEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDragEnterEvent(KTreeWidgetSearchLine* self, QDragEnterEvent* param1);
void KTreeWidgetSearchLine_DragMoveEvent(KTreeWidgetSearchLine* self, QDragMoveEvent* e);
void KTreeWidgetSearchLine_OnDragMoveEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDragMoveEvent(KTreeWidgetSearchLine* self, QDragMoveEvent* e);
void KTreeWidgetSearchLine_DragLeaveEvent(KTreeWidgetSearchLine* self, QDragLeaveEvent* e);
void KTreeWidgetSearchLine_OnDragLeaveEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDragLeaveEvent(KTreeWidgetSearchLine* self, QDragLeaveEvent* e);
void KTreeWidgetSearchLine_DropEvent(KTreeWidgetSearchLine* self, QDropEvent* param1);
void KTreeWidgetSearchLine_OnDropEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDropEvent(KTreeWidgetSearchLine* self, QDropEvent* param1);
void KTreeWidgetSearchLine_ChangeEvent(KTreeWidgetSearchLine* self, QEvent* param1);
void KTreeWidgetSearchLine_OnChangeEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperChangeEvent(KTreeWidgetSearchLine* self, QEvent* param1);
void KTreeWidgetSearchLine_InputMethodEvent(KTreeWidgetSearchLine* self, QInputMethodEvent* param1);
void KTreeWidgetSearchLine_OnInputMethodEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperInputMethodEvent(KTreeWidgetSearchLine* self, QInputMethodEvent* param1);
void KTreeWidgetSearchLine_InitStyleOption(const KTreeWidgetSearchLine* self, QStyleOptionFrame* option);
void KTreeWidgetSearchLine_OnInitStyleOption(const KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperInitStyleOption(const KTreeWidgetSearchLine* self, QStyleOptionFrame* option);
QVariant* KTreeWidgetSearchLine_InputMethodQuery(const KTreeWidgetSearchLine* self, int param1);
void KTreeWidgetSearchLine_OnInputMethodQuery(const KTreeWidgetSearchLine* self, intptr_t slot);
QVariant* KTreeWidgetSearchLine_SuperInputMethodQuery(const KTreeWidgetSearchLine* self, int param1);
void KTreeWidgetSearchLine_TimerEvent(KTreeWidgetSearchLine* self, QTimerEvent* param1);
void KTreeWidgetSearchLine_OnTimerEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperTimerEvent(KTreeWidgetSearchLine* self, QTimerEvent* param1);
int KTreeWidgetSearchLine_DevType(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnDevType(const KTreeWidgetSearchLine* self, intptr_t slot);
int KTreeWidgetSearchLine_SuperDevType(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_SetVisible(KTreeWidgetSearchLine* self, bool visible);
void KTreeWidgetSearchLine_OnSetVisible(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperSetVisible(KTreeWidgetSearchLine* self, bool visible);
int KTreeWidgetSearchLine_HeightForWidth(const KTreeWidgetSearchLine* self, int param1);
void KTreeWidgetSearchLine_OnHeightForWidth(const KTreeWidgetSearchLine* self, intptr_t slot);
int KTreeWidgetSearchLine_SuperHeightForWidth(const KTreeWidgetSearchLine* self, int param1);
bool KTreeWidgetSearchLine_HasHeightForWidth(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnHasHeightForWidth(const KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperHasHeightForWidth(const KTreeWidgetSearchLine* self);
QPaintEngine* KTreeWidgetSearchLine_PaintEngine(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnPaintEngine(const KTreeWidgetSearchLine* self, intptr_t slot);
QPaintEngine* KTreeWidgetSearchLine_SuperPaintEngine(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_WheelEvent(KTreeWidgetSearchLine* self, QWheelEvent* event);
void KTreeWidgetSearchLine_OnWheelEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperWheelEvent(KTreeWidgetSearchLine* self, QWheelEvent* event);
void KTreeWidgetSearchLine_EnterEvent(KTreeWidgetSearchLine* self, QEnterEvent* event);
void KTreeWidgetSearchLine_OnEnterEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperEnterEvent(KTreeWidgetSearchLine* self, QEnterEvent* event);
void KTreeWidgetSearchLine_LeaveEvent(KTreeWidgetSearchLine* self, QEvent* event);
void KTreeWidgetSearchLine_OnLeaveEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperLeaveEvent(KTreeWidgetSearchLine* self, QEvent* event);
void KTreeWidgetSearchLine_MoveEvent(KTreeWidgetSearchLine* self, QMoveEvent* event);
void KTreeWidgetSearchLine_OnMoveEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperMoveEvent(KTreeWidgetSearchLine* self, QMoveEvent* event);
void KTreeWidgetSearchLine_ResizeEvent(KTreeWidgetSearchLine* self, QResizeEvent* event);
void KTreeWidgetSearchLine_OnResizeEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperResizeEvent(KTreeWidgetSearchLine* self, QResizeEvent* event);
void KTreeWidgetSearchLine_CloseEvent(KTreeWidgetSearchLine* self, QCloseEvent* event);
void KTreeWidgetSearchLine_OnCloseEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperCloseEvent(KTreeWidgetSearchLine* self, QCloseEvent* event);
void KTreeWidgetSearchLine_TabletEvent(KTreeWidgetSearchLine* self, QTabletEvent* event);
void KTreeWidgetSearchLine_OnTabletEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperTabletEvent(KTreeWidgetSearchLine* self, QTabletEvent* event);
void KTreeWidgetSearchLine_ActionEvent(KTreeWidgetSearchLine* self, QActionEvent* event);
void KTreeWidgetSearchLine_OnActionEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperActionEvent(KTreeWidgetSearchLine* self, QActionEvent* event);
void KTreeWidgetSearchLine_ShowEvent(KTreeWidgetSearchLine* self, QShowEvent* event);
void KTreeWidgetSearchLine_OnShowEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperShowEvent(KTreeWidgetSearchLine* self, QShowEvent* event);
void KTreeWidgetSearchLine_HideEvent(KTreeWidgetSearchLine* self, QHideEvent* event);
void KTreeWidgetSearchLine_OnHideEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperHideEvent(KTreeWidgetSearchLine* self, QHideEvent* event);
bool KTreeWidgetSearchLine_NativeEvent(KTreeWidgetSearchLine* self, const libqt_string eventType, void* message, intptr_t* result);
void KTreeWidgetSearchLine_OnNativeEvent(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperNativeEvent(KTreeWidgetSearchLine* self, const libqt_string eventType, void* message, intptr_t* result);
int KTreeWidgetSearchLine_Metric(const KTreeWidgetSearchLine* self, int param1);
void KTreeWidgetSearchLine_OnMetric(const KTreeWidgetSearchLine* self, intptr_t slot);
int KTreeWidgetSearchLine_SuperMetric(const KTreeWidgetSearchLine* self, int param1);
void KTreeWidgetSearchLine_InitPainter(const KTreeWidgetSearchLine* self, QPainter* painter);
void KTreeWidgetSearchLine_OnInitPainter(const KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperInitPainter(const KTreeWidgetSearchLine* self, QPainter* painter);
QPaintDevice* KTreeWidgetSearchLine_Redirected(const KTreeWidgetSearchLine* self, QPoint* offset);
void KTreeWidgetSearchLine_OnRedirected(const KTreeWidgetSearchLine* self, intptr_t slot);
QPaintDevice* KTreeWidgetSearchLine_SuperRedirected(const KTreeWidgetSearchLine* self, QPoint* offset);
QPainter* KTreeWidgetSearchLine_SharedPainter(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnSharedPainter(const KTreeWidgetSearchLine* self, intptr_t slot);
QPainter* KTreeWidgetSearchLine_SuperSharedPainter(const KTreeWidgetSearchLine* self);
bool KTreeWidgetSearchLine_FocusNextPrevChild(KTreeWidgetSearchLine* self, bool next);
void KTreeWidgetSearchLine_OnFocusNextPrevChild(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperFocusNextPrevChild(KTreeWidgetSearchLine* self, bool next);
bool KTreeWidgetSearchLine_EventFilter(KTreeWidgetSearchLine* self, QObject* watched, QEvent* event);
void KTreeWidgetSearchLine_OnEventFilter(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperEventFilter(KTreeWidgetSearchLine* self, QObject* watched, QEvent* event);
void KTreeWidgetSearchLine_ChildEvent(KTreeWidgetSearchLine* self, QChildEvent* event);
void KTreeWidgetSearchLine_OnChildEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperChildEvent(KTreeWidgetSearchLine* self, QChildEvent* event);
void KTreeWidgetSearchLine_CustomEvent(KTreeWidgetSearchLine* self, QEvent* event);
void KTreeWidgetSearchLine_OnCustomEvent(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperCustomEvent(KTreeWidgetSearchLine* self, QEvent* event);
void KTreeWidgetSearchLine_ConnectNotify(KTreeWidgetSearchLine* self, const QMetaMethod* signal);
void KTreeWidgetSearchLine_OnConnectNotify(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperConnectNotify(KTreeWidgetSearchLine* self, const QMetaMethod* signal);
void KTreeWidgetSearchLine_DisconnectNotify(KTreeWidgetSearchLine* self, const QMetaMethod* signal);
void KTreeWidgetSearchLine_OnDisconnectNotify(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDisconnectNotify(KTreeWidgetSearchLine* self, const QMetaMethod* signal);
QRect* KTreeWidgetSearchLine_CursorRect(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnCursorRect(const KTreeWidgetSearchLine* self, intptr_t slot);
QRect* KTreeWidgetSearchLine_SuperCursorRect(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_UpdateMicroFocus(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnUpdateMicroFocus(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperUpdateMicroFocus(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_Create(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnCreate(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperCreate(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_Destroy(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnDestroy(KTreeWidgetSearchLine* self, intptr_t slot);
void KTreeWidgetSearchLine_SuperDestroy(KTreeWidgetSearchLine* self);
bool KTreeWidgetSearchLine_FocusNextChild(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnFocusNextChild(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperFocusNextChild(KTreeWidgetSearchLine* self);
bool KTreeWidgetSearchLine_FocusPreviousChild(KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnFocusPreviousChild(KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperFocusPreviousChild(KTreeWidgetSearchLine* self);
QObject* KTreeWidgetSearchLine_Sender(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnSender(const KTreeWidgetSearchLine* self, intptr_t slot);
QObject* KTreeWidgetSearchLine_SuperSender(const KTreeWidgetSearchLine* self);
int KTreeWidgetSearchLine_SenderSignalIndex(const KTreeWidgetSearchLine* self);
void KTreeWidgetSearchLine_OnSenderSignalIndex(const KTreeWidgetSearchLine* self, intptr_t slot);
int KTreeWidgetSearchLine_SuperSenderSignalIndex(const KTreeWidgetSearchLine* self);
int KTreeWidgetSearchLine_Receivers(const KTreeWidgetSearchLine* self, const char* signal);
void KTreeWidgetSearchLine_OnReceivers(const KTreeWidgetSearchLine* self, intptr_t slot);
int KTreeWidgetSearchLine_SuperReceivers(const KTreeWidgetSearchLine* self, const char* signal);
bool KTreeWidgetSearchLine_IsSignalConnected(const KTreeWidgetSearchLine* self, const QMetaMethod* signal);
void KTreeWidgetSearchLine_OnIsSignalConnected(const KTreeWidgetSearchLine* self, intptr_t slot);
bool KTreeWidgetSearchLine_SuperIsSignalConnected(const KTreeWidgetSearchLine* self, const QMetaMethod* signal);
double KTreeWidgetSearchLine_GetDecodedMetricF(const KTreeWidgetSearchLine* self, int metricA, int metricB);
void KTreeWidgetSearchLine_OnGetDecodedMetricF(const KTreeWidgetSearchLine* self, intptr_t slot);
double KTreeWidgetSearchLine_SuperGetDecodedMetricF(const KTreeWidgetSearchLine* self, int metricA, int metricB);
void KTreeWidgetSearchLine_Delete(KTreeWidgetSearchLine* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
