#pragma once
#ifndef SRC_OPENGLC_LIBQOPENGLWIDGET_H
#define SRC_OPENGLC_LIBQOPENGLWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QOpenGLContext QOpenGLContext;
typedef struct QOpenGLWidget QOpenGLWidget;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSurfaceFormat QSurfaceFormat;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QOpenGLWidget* QOpenGLWidget_new(QWidget* parent);
QOpenGLWidget* QOpenGLWidget_new2();
QOpenGLWidget* QOpenGLWidget_new3(QWidget* parent, int f);
QMetaObject* QOpenGLWidget_MetaObject(const QOpenGLWidget* self);
void* QOpenGLWidget_Metacast(QOpenGLWidget* self, const char* param1);
int QOpenGLWidget_Metacall(QOpenGLWidget* self, int param1, int param2, void** param3);
void QOpenGLWidget_SetUpdateBehavior(QOpenGLWidget* self, int updateBehavior);
int QOpenGLWidget_UpdateBehavior(const QOpenGLWidget* self);
void QOpenGLWidget_SetFormat(QOpenGLWidget* self, const QSurfaceFormat* format);
QSurfaceFormat* QOpenGLWidget_Format(const QOpenGLWidget* self);
void QOpenGLWidget_SetTextureFormat(QOpenGLWidget* self, uint32_t texFormat);
bool QOpenGLWidget_IsValid(const QOpenGLWidget* self);
void QOpenGLWidget_MakeCurrent(QOpenGLWidget* self);
void QOpenGLWidget_MakeCurrent2(QOpenGLWidget* self, uint8_t targetBuffer);
void QOpenGLWidget_DoneCurrent(QOpenGLWidget* self);
QOpenGLContext* QOpenGLWidget_Context(const QOpenGLWidget* self);
uint32_t QOpenGLWidget_DefaultFramebufferObject(const QOpenGLWidget* self);
uint32_t QOpenGLWidget_DefaultFramebufferObject2(const QOpenGLWidget* self, uint8_t targetBuffer);
QImage* QOpenGLWidget_GrabFramebuffer(QOpenGLWidget* self);
QImage* QOpenGLWidget_GrabFramebuffer2(QOpenGLWidget* self, uint8_t targetBuffer);
uint8_t QOpenGLWidget_CurrentTargetBuffer(const QOpenGLWidget* self);
void QOpenGLWidget_AboutToCompose(QOpenGLWidget* self);
void QOpenGLWidget_Connect_AboutToCompose(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_FrameSwapped(QOpenGLWidget* self);
void QOpenGLWidget_Connect_FrameSwapped(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_AboutToResize(QOpenGLWidget* self);
void QOpenGLWidget_Connect_AboutToResize(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_Resized(QOpenGLWidget* self);
void QOpenGLWidget_Connect_Resized(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_InitializeGL(QOpenGLWidget* self);
void QOpenGLWidget_ResizeGL(QOpenGLWidget* self, int w, int h);
void QOpenGLWidget_PaintGL(QOpenGLWidget* self);
void QOpenGLWidget_PaintEvent(QOpenGLWidget* self, QPaintEvent* e);
void QOpenGLWidget_ResizeEvent(QOpenGLWidget* self, QResizeEvent* e);
bool QOpenGLWidget_Event(QOpenGLWidget* self, QEvent* e);
int QOpenGLWidget_Metric(const QOpenGLWidget* self, int metric);
QPaintDevice* QOpenGLWidget_Redirected(const QOpenGLWidget* self, QPoint* p);
QPaintEngine* QOpenGLWidget_PaintEngine(const QOpenGLWidget* self);
void QOpenGLWidget_OnMetaObject(const QOpenGLWidget* self, intptr_t slot);
QMetaObject* QOpenGLWidget_SuperMetaObject(const QOpenGLWidget* self);
void QOpenGLWidget_OnMetacast(QOpenGLWidget* self, intptr_t slot);
void* QOpenGLWidget_SuperMetacast(QOpenGLWidget* self, const char* param1);
void QOpenGLWidget_OnMetacall(QOpenGLWidget* self, intptr_t slot);
int QOpenGLWidget_SuperMetacall(QOpenGLWidget* self, int param1, int param2, void** param3);
void QOpenGLWidget_OnInitializeGL(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperInitializeGL(QOpenGLWidget* self);
void QOpenGLWidget_OnResizeGL(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperResizeGL(QOpenGLWidget* self, int w, int h);
void QOpenGLWidget_OnPaintGL(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperPaintGL(QOpenGLWidget* self);
void QOpenGLWidget_OnPaintEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperPaintEvent(QOpenGLWidget* self, QPaintEvent* e);
void QOpenGLWidget_OnResizeEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperResizeEvent(QOpenGLWidget* self, QResizeEvent* e);
void QOpenGLWidget_OnEvent(QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperEvent(QOpenGLWidget* self, QEvent* e);
void QOpenGLWidget_OnMetric(const QOpenGLWidget* self, intptr_t slot);
int QOpenGLWidget_SuperMetric(const QOpenGLWidget* self, int metric);
void QOpenGLWidget_OnRedirected(const QOpenGLWidget* self, intptr_t slot);
QPaintDevice* QOpenGLWidget_SuperRedirected(const QOpenGLWidget* self, QPoint* p);
void QOpenGLWidget_OnPaintEngine(const QOpenGLWidget* self, intptr_t slot);
QPaintEngine* QOpenGLWidget_SuperPaintEngine(const QOpenGLWidget* self);
int QOpenGLWidget_DevType(const QOpenGLWidget* self);
void QOpenGLWidget_OnDevType(const QOpenGLWidget* self, intptr_t slot);
int QOpenGLWidget_SuperDevType(const QOpenGLWidget* self);
void QOpenGLWidget_SetVisible(QOpenGLWidget* self, bool visible);
void QOpenGLWidget_OnSetVisible(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperSetVisible(QOpenGLWidget* self, bool visible);
QSize* QOpenGLWidget_SizeHint(const QOpenGLWidget* self);
void QOpenGLWidget_OnSizeHint(const QOpenGLWidget* self, intptr_t slot);
QSize* QOpenGLWidget_SuperSizeHint(const QOpenGLWidget* self);
QSize* QOpenGLWidget_MinimumSizeHint(const QOpenGLWidget* self);
void QOpenGLWidget_OnMinimumSizeHint(const QOpenGLWidget* self, intptr_t slot);
QSize* QOpenGLWidget_SuperMinimumSizeHint(const QOpenGLWidget* self);
int QOpenGLWidget_HeightForWidth(const QOpenGLWidget* self, int param1);
void QOpenGLWidget_OnHeightForWidth(const QOpenGLWidget* self, intptr_t slot);
int QOpenGLWidget_SuperHeightForWidth(const QOpenGLWidget* self, int param1);
bool QOpenGLWidget_HasHeightForWidth(const QOpenGLWidget* self);
void QOpenGLWidget_OnHasHeightForWidth(const QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperHasHeightForWidth(const QOpenGLWidget* self);
void QOpenGLWidget_MousePressEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_OnMousePressEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperMousePressEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_MouseReleaseEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_OnMouseReleaseEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperMouseReleaseEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_MouseDoubleClickEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_OnMouseDoubleClickEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperMouseDoubleClickEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_MouseMoveEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_OnMouseMoveEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperMouseMoveEvent(QOpenGLWidget* self, QMouseEvent* event);
void QOpenGLWidget_WheelEvent(QOpenGLWidget* self, QWheelEvent* event);
void QOpenGLWidget_OnWheelEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperWheelEvent(QOpenGLWidget* self, QWheelEvent* event);
void QOpenGLWidget_KeyPressEvent(QOpenGLWidget* self, QKeyEvent* event);
void QOpenGLWidget_OnKeyPressEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperKeyPressEvent(QOpenGLWidget* self, QKeyEvent* event);
void QOpenGLWidget_KeyReleaseEvent(QOpenGLWidget* self, QKeyEvent* event);
void QOpenGLWidget_OnKeyReleaseEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperKeyReleaseEvent(QOpenGLWidget* self, QKeyEvent* event);
void QOpenGLWidget_FocusInEvent(QOpenGLWidget* self, QFocusEvent* event);
void QOpenGLWidget_OnFocusInEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperFocusInEvent(QOpenGLWidget* self, QFocusEvent* event);
void QOpenGLWidget_FocusOutEvent(QOpenGLWidget* self, QFocusEvent* event);
void QOpenGLWidget_OnFocusOutEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperFocusOutEvent(QOpenGLWidget* self, QFocusEvent* event);
void QOpenGLWidget_EnterEvent(QOpenGLWidget* self, QEnterEvent* event);
void QOpenGLWidget_OnEnterEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperEnterEvent(QOpenGLWidget* self, QEnterEvent* event);
void QOpenGLWidget_LeaveEvent(QOpenGLWidget* self, QEvent* event);
void QOpenGLWidget_OnLeaveEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperLeaveEvent(QOpenGLWidget* self, QEvent* event);
void QOpenGLWidget_MoveEvent(QOpenGLWidget* self, QMoveEvent* event);
void QOpenGLWidget_OnMoveEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperMoveEvent(QOpenGLWidget* self, QMoveEvent* event);
void QOpenGLWidget_CloseEvent(QOpenGLWidget* self, QCloseEvent* event);
void QOpenGLWidget_OnCloseEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperCloseEvent(QOpenGLWidget* self, QCloseEvent* event);
void QOpenGLWidget_ContextMenuEvent(QOpenGLWidget* self, QContextMenuEvent* event);
void QOpenGLWidget_OnContextMenuEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperContextMenuEvent(QOpenGLWidget* self, QContextMenuEvent* event);
void QOpenGLWidget_TabletEvent(QOpenGLWidget* self, QTabletEvent* event);
void QOpenGLWidget_OnTabletEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperTabletEvent(QOpenGLWidget* self, QTabletEvent* event);
void QOpenGLWidget_ActionEvent(QOpenGLWidget* self, QActionEvent* event);
void QOpenGLWidget_OnActionEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperActionEvent(QOpenGLWidget* self, QActionEvent* event);
void QOpenGLWidget_DragEnterEvent(QOpenGLWidget* self, QDragEnterEvent* event);
void QOpenGLWidget_OnDragEnterEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperDragEnterEvent(QOpenGLWidget* self, QDragEnterEvent* event);
void QOpenGLWidget_DragMoveEvent(QOpenGLWidget* self, QDragMoveEvent* event);
void QOpenGLWidget_OnDragMoveEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperDragMoveEvent(QOpenGLWidget* self, QDragMoveEvent* event);
void QOpenGLWidget_DragLeaveEvent(QOpenGLWidget* self, QDragLeaveEvent* event);
void QOpenGLWidget_OnDragLeaveEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperDragLeaveEvent(QOpenGLWidget* self, QDragLeaveEvent* event);
void QOpenGLWidget_DropEvent(QOpenGLWidget* self, QDropEvent* event);
void QOpenGLWidget_OnDropEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperDropEvent(QOpenGLWidget* self, QDropEvent* event);
void QOpenGLWidget_ShowEvent(QOpenGLWidget* self, QShowEvent* event);
void QOpenGLWidget_OnShowEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperShowEvent(QOpenGLWidget* self, QShowEvent* event);
void QOpenGLWidget_HideEvent(QOpenGLWidget* self, QHideEvent* event);
void QOpenGLWidget_OnHideEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperHideEvent(QOpenGLWidget* self, QHideEvent* event);
bool QOpenGLWidget_NativeEvent(QOpenGLWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QOpenGLWidget_OnNativeEvent(QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperNativeEvent(QOpenGLWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QOpenGLWidget_ChangeEvent(QOpenGLWidget* self, QEvent* param1);
void QOpenGLWidget_OnChangeEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperChangeEvent(QOpenGLWidget* self, QEvent* param1);
void QOpenGLWidget_InitPainter(const QOpenGLWidget* self, QPainter* painter);
void QOpenGLWidget_OnInitPainter(const QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperInitPainter(const QOpenGLWidget* self, QPainter* painter);
QPainter* QOpenGLWidget_SharedPainter(const QOpenGLWidget* self);
void QOpenGLWidget_OnSharedPainter(const QOpenGLWidget* self, intptr_t slot);
QPainter* QOpenGLWidget_SuperSharedPainter(const QOpenGLWidget* self);
void QOpenGLWidget_InputMethodEvent(QOpenGLWidget* self, QInputMethodEvent* param1);
void QOpenGLWidget_OnInputMethodEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperInputMethodEvent(QOpenGLWidget* self, QInputMethodEvent* param1);
QVariant* QOpenGLWidget_InputMethodQuery(const QOpenGLWidget* self, int param1);
void QOpenGLWidget_OnInputMethodQuery(const QOpenGLWidget* self, intptr_t slot);
QVariant* QOpenGLWidget_SuperInputMethodQuery(const QOpenGLWidget* self, int param1);
bool QOpenGLWidget_FocusNextPrevChild(QOpenGLWidget* self, bool next);
void QOpenGLWidget_OnFocusNextPrevChild(QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperFocusNextPrevChild(QOpenGLWidget* self, bool next);
bool QOpenGLWidget_EventFilter(QOpenGLWidget* self, QObject* watched, QEvent* event);
void QOpenGLWidget_OnEventFilter(QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperEventFilter(QOpenGLWidget* self, QObject* watched, QEvent* event);
void QOpenGLWidget_TimerEvent(QOpenGLWidget* self, QTimerEvent* event);
void QOpenGLWidget_OnTimerEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperTimerEvent(QOpenGLWidget* self, QTimerEvent* event);
void QOpenGLWidget_ChildEvent(QOpenGLWidget* self, QChildEvent* event);
void QOpenGLWidget_OnChildEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperChildEvent(QOpenGLWidget* self, QChildEvent* event);
void QOpenGLWidget_CustomEvent(QOpenGLWidget* self, QEvent* event);
void QOpenGLWidget_OnCustomEvent(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperCustomEvent(QOpenGLWidget* self, QEvent* event);
void QOpenGLWidget_ConnectNotify(QOpenGLWidget* self, const QMetaMethod* signal);
void QOpenGLWidget_OnConnectNotify(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperConnectNotify(QOpenGLWidget* self, const QMetaMethod* signal);
void QOpenGLWidget_DisconnectNotify(QOpenGLWidget* self, const QMetaMethod* signal);
void QOpenGLWidget_OnDisconnectNotify(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperDisconnectNotify(QOpenGLWidget* self, const QMetaMethod* signal);
void QOpenGLWidget_UpdateMicroFocus(QOpenGLWidget* self);
void QOpenGLWidget_OnUpdateMicroFocus(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperUpdateMicroFocus(QOpenGLWidget* self);
void QOpenGLWidget_Create(QOpenGLWidget* self);
void QOpenGLWidget_OnCreate(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperCreate(QOpenGLWidget* self);
void QOpenGLWidget_Destroy(QOpenGLWidget* self);
void QOpenGLWidget_OnDestroy(QOpenGLWidget* self, intptr_t slot);
void QOpenGLWidget_SuperDestroy(QOpenGLWidget* self);
bool QOpenGLWidget_FocusNextChild(QOpenGLWidget* self);
void QOpenGLWidget_OnFocusNextChild(QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperFocusNextChild(QOpenGLWidget* self);
bool QOpenGLWidget_FocusPreviousChild(QOpenGLWidget* self);
void QOpenGLWidget_OnFocusPreviousChild(QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperFocusPreviousChild(QOpenGLWidget* self);
QObject* QOpenGLWidget_Sender(const QOpenGLWidget* self);
void QOpenGLWidget_OnSender(const QOpenGLWidget* self, intptr_t slot);
QObject* QOpenGLWidget_SuperSender(const QOpenGLWidget* self);
int QOpenGLWidget_SenderSignalIndex(const QOpenGLWidget* self);
void QOpenGLWidget_OnSenderSignalIndex(const QOpenGLWidget* self, intptr_t slot);
int QOpenGLWidget_SuperSenderSignalIndex(const QOpenGLWidget* self);
int QOpenGLWidget_Receivers(const QOpenGLWidget* self, const char* signal);
void QOpenGLWidget_OnReceivers(const QOpenGLWidget* self, intptr_t slot);
int QOpenGLWidget_SuperReceivers(const QOpenGLWidget* self, const char* signal);
bool QOpenGLWidget_IsSignalConnected(const QOpenGLWidget* self, const QMetaMethod* signal);
void QOpenGLWidget_OnIsSignalConnected(const QOpenGLWidget* self, intptr_t slot);
bool QOpenGLWidget_SuperIsSignalConnected(const QOpenGLWidget* self, const QMetaMethod* signal);
double QOpenGLWidget_GetDecodedMetricF(const QOpenGLWidget* self, int metricA, int metricB);
void QOpenGLWidget_OnGetDecodedMetricF(const QOpenGLWidget* self, intptr_t slot);
double QOpenGLWidget_SuperGetDecodedMetricF(const QOpenGLWidget* self, int metricA, int metricB);
void QOpenGLWidget_Delete(QOpenGLWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
