#pragma once
#ifndef SRC_DESIGNERC_LIBABSTRACTOBJECTINSPECTOR_H
#define SRC_DESIGNERC_LIBABSTRACTOBJECTINSPECTOR_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDesignerFormEditorInterface QDesignerFormEditorInterface;
typedef struct QDesignerFormWindowInterface QDesignerFormWindowInterface;
typedef struct QDesignerObjectInspectorInterface QDesignerObjectInspectorInterface;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QDesignerObjectInspectorInterface* QDesignerObjectInspectorInterface_new(QWidget* parent);
QDesignerObjectInspectorInterface* QDesignerObjectInspectorInterface_new2(QWidget* parent, int flags);
QMetaObject* QDesignerObjectInspectorInterface_MetaObject(const QDesignerObjectInspectorInterface* self);
void* QDesignerObjectInspectorInterface_Metacast(QDesignerObjectInspectorInterface* self, const char* param1);
int QDesignerObjectInspectorInterface_Metacall(QDesignerObjectInspectorInterface* self, int param1, int param2, void** param3);
QDesignerFormEditorInterface* QDesignerObjectInspectorInterface_Core(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_SetFormWindow(QDesignerObjectInspectorInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerObjectInspectorInterface_OnMetaObject(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QMetaObject* QDesignerObjectInspectorInterface_QBaseMetaObject(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnMetacast(QDesignerObjectInspectorInterface* self, intptr_t slot);
void* QDesignerObjectInspectorInterface_QBaseMetacast(QDesignerObjectInspectorInterface* self, const char* param1);
void QDesignerObjectInspectorInterface_OnMetacall(QDesignerObjectInspectorInterface* self, intptr_t slot);
int QDesignerObjectInspectorInterface_QBaseMetacall(QDesignerObjectInspectorInterface* self, int param1, int param2, void** param3);
void QDesignerObjectInspectorInterface_OnCore(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QDesignerFormEditorInterface* QDesignerObjectInspectorInterface_QBaseCore(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnSetFormWindow(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseSetFormWindow(QDesignerObjectInspectorInterface* self, QDesignerFormWindowInterface* formWindow);
int QDesignerObjectInspectorInterface_DevType(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnDevType(const QDesignerObjectInspectorInterface* self, intptr_t slot);
int QDesignerObjectInspectorInterface_QBaseDevType(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_SetVisible(QDesignerObjectInspectorInterface* self, bool visible);
void QDesignerObjectInspectorInterface_OnSetVisible(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseSetVisible(QDesignerObjectInspectorInterface* self, bool visible);
QSize* QDesignerObjectInspectorInterface_SizeHint(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnSizeHint(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QSize* QDesignerObjectInspectorInterface_QBaseSizeHint(const QDesignerObjectInspectorInterface* self);
QSize* QDesignerObjectInspectorInterface_MinimumSizeHint(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnMinimumSizeHint(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QSize* QDesignerObjectInspectorInterface_QBaseMinimumSizeHint(const QDesignerObjectInspectorInterface* self);
int QDesignerObjectInspectorInterface_HeightForWidth(const QDesignerObjectInspectorInterface* self, int param1);
void QDesignerObjectInspectorInterface_OnHeightForWidth(const QDesignerObjectInspectorInterface* self, intptr_t slot);
int QDesignerObjectInspectorInterface_QBaseHeightForWidth(const QDesignerObjectInspectorInterface* self, int param1);
bool QDesignerObjectInspectorInterface_HasHeightForWidth(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnHasHeightForWidth(const QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseHasHeightForWidth(const QDesignerObjectInspectorInterface* self);
QPaintEngine* QDesignerObjectInspectorInterface_PaintEngine(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnPaintEngine(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QPaintEngine* QDesignerObjectInspectorInterface_QBasePaintEngine(const QDesignerObjectInspectorInterface* self);
bool QDesignerObjectInspectorInterface_Event(QDesignerObjectInspectorInterface* self, QEvent* event);
void QDesignerObjectInspectorInterface_OnEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseEvent(QDesignerObjectInspectorInterface* self, QEvent* event);
void QDesignerObjectInspectorInterface_MousePressEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_OnMousePressEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseMousePressEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_MouseReleaseEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_OnMouseReleaseEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseMouseReleaseEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_MouseDoubleClickEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_OnMouseDoubleClickEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseMouseDoubleClickEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_MouseMoveEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_OnMouseMoveEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseMouseMoveEvent(QDesignerObjectInspectorInterface* self, QMouseEvent* event);
void QDesignerObjectInspectorInterface_WheelEvent(QDesignerObjectInspectorInterface* self, QWheelEvent* event);
void QDesignerObjectInspectorInterface_OnWheelEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseWheelEvent(QDesignerObjectInspectorInterface* self, QWheelEvent* event);
void QDesignerObjectInspectorInterface_KeyPressEvent(QDesignerObjectInspectorInterface* self, QKeyEvent* event);
void QDesignerObjectInspectorInterface_OnKeyPressEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseKeyPressEvent(QDesignerObjectInspectorInterface* self, QKeyEvent* event);
void QDesignerObjectInspectorInterface_KeyReleaseEvent(QDesignerObjectInspectorInterface* self, QKeyEvent* event);
void QDesignerObjectInspectorInterface_OnKeyReleaseEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseKeyReleaseEvent(QDesignerObjectInspectorInterface* self, QKeyEvent* event);
void QDesignerObjectInspectorInterface_FocusInEvent(QDesignerObjectInspectorInterface* self, QFocusEvent* event);
void QDesignerObjectInspectorInterface_OnFocusInEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseFocusInEvent(QDesignerObjectInspectorInterface* self, QFocusEvent* event);
void QDesignerObjectInspectorInterface_FocusOutEvent(QDesignerObjectInspectorInterface* self, QFocusEvent* event);
void QDesignerObjectInspectorInterface_OnFocusOutEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseFocusOutEvent(QDesignerObjectInspectorInterface* self, QFocusEvent* event);
void QDesignerObjectInspectorInterface_EnterEvent(QDesignerObjectInspectorInterface* self, QEnterEvent* event);
void QDesignerObjectInspectorInterface_OnEnterEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseEnterEvent(QDesignerObjectInspectorInterface* self, QEnterEvent* event);
void QDesignerObjectInspectorInterface_LeaveEvent(QDesignerObjectInspectorInterface* self, QEvent* event);
void QDesignerObjectInspectorInterface_OnLeaveEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseLeaveEvent(QDesignerObjectInspectorInterface* self, QEvent* event);
void QDesignerObjectInspectorInterface_PaintEvent(QDesignerObjectInspectorInterface* self, QPaintEvent* event);
void QDesignerObjectInspectorInterface_OnPaintEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBasePaintEvent(QDesignerObjectInspectorInterface* self, QPaintEvent* event);
void QDesignerObjectInspectorInterface_MoveEvent(QDesignerObjectInspectorInterface* self, QMoveEvent* event);
void QDesignerObjectInspectorInterface_OnMoveEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseMoveEvent(QDesignerObjectInspectorInterface* self, QMoveEvent* event);
void QDesignerObjectInspectorInterface_ResizeEvent(QDesignerObjectInspectorInterface* self, QResizeEvent* event);
void QDesignerObjectInspectorInterface_OnResizeEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseResizeEvent(QDesignerObjectInspectorInterface* self, QResizeEvent* event);
void QDesignerObjectInspectorInterface_CloseEvent(QDesignerObjectInspectorInterface* self, QCloseEvent* event);
void QDesignerObjectInspectorInterface_OnCloseEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseCloseEvent(QDesignerObjectInspectorInterface* self, QCloseEvent* event);
void QDesignerObjectInspectorInterface_ContextMenuEvent(QDesignerObjectInspectorInterface* self, QContextMenuEvent* event);
void QDesignerObjectInspectorInterface_OnContextMenuEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseContextMenuEvent(QDesignerObjectInspectorInterface* self, QContextMenuEvent* event);
void QDesignerObjectInspectorInterface_TabletEvent(QDesignerObjectInspectorInterface* self, QTabletEvent* event);
void QDesignerObjectInspectorInterface_OnTabletEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseTabletEvent(QDesignerObjectInspectorInterface* self, QTabletEvent* event);
void QDesignerObjectInspectorInterface_ActionEvent(QDesignerObjectInspectorInterface* self, QActionEvent* event);
void QDesignerObjectInspectorInterface_OnActionEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseActionEvent(QDesignerObjectInspectorInterface* self, QActionEvent* event);
void QDesignerObjectInspectorInterface_DragEnterEvent(QDesignerObjectInspectorInterface* self, QDragEnterEvent* event);
void QDesignerObjectInspectorInterface_OnDragEnterEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseDragEnterEvent(QDesignerObjectInspectorInterface* self, QDragEnterEvent* event);
void QDesignerObjectInspectorInterface_DragMoveEvent(QDesignerObjectInspectorInterface* self, QDragMoveEvent* event);
void QDesignerObjectInspectorInterface_OnDragMoveEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseDragMoveEvent(QDesignerObjectInspectorInterface* self, QDragMoveEvent* event);
void QDesignerObjectInspectorInterface_DragLeaveEvent(QDesignerObjectInspectorInterface* self, QDragLeaveEvent* event);
void QDesignerObjectInspectorInterface_OnDragLeaveEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseDragLeaveEvent(QDesignerObjectInspectorInterface* self, QDragLeaveEvent* event);
void QDesignerObjectInspectorInterface_DropEvent(QDesignerObjectInspectorInterface* self, QDropEvent* event);
void QDesignerObjectInspectorInterface_OnDropEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseDropEvent(QDesignerObjectInspectorInterface* self, QDropEvent* event);
void QDesignerObjectInspectorInterface_ShowEvent(QDesignerObjectInspectorInterface* self, QShowEvent* event);
void QDesignerObjectInspectorInterface_OnShowEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseShowEvent(QDesignerObjectInspectorInterface* self, QShowEvent* event);
void QDesignerObjectInspectorInterface_HideEvent(QDesignerObjectInspectorInterface* self, QHideEvent* event);
void QDesignerObjectInspectorInterface_OnHideEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseHideEvent(QDesignerObjectInspectorInterface* self, QHideEvent* event);
bool QDesignerObjectInspectorInterface_NativeEvent(QDesignerObjectInspectorInterface* self, const libqt_string eventType, void* message, intptr_t* result);
void QDesignerObjectInspectorInterface_OnNativeEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseNativeEvent(QDesignerObjectInspectorInterface* self, const libqt_string eventType, void* message, intptr_t* result);
void QDesignerObjectInspectorInterface_ChangeEvent(QDesignerObjectInspectorInterface* self, QEvent* param1);
void QDesignerObjectInspectorInterface_OnChangeEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseChangeEvent(QDesignerObjectInspectorInterface* self, QEvent* param1);
int QDesignerObjectInspectorInterface_Metric(const QDesignerObjectInspectorInterface* self, int param1);
void QDesignerObjectInspectorInterface_OnMetric(const QDesignerObjectInspectorInterface* self, intptr_t slot);
int QDesignerObjectInspectorInterface_QBaseMetric(const QDesignerObjectInspectorInterface* self, int param1);
void QDesignerObjectInspectorInterface_InitPainter(const QDesignerObjectInspectorInterface* self, QPainter* painter);
void QDesignerObjectInspectorInterface_OnInitPainter(const QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseInitPainter(const QDesignerObjectInspectorInterface* self, QPainter* painter);
QPaintDevice* QDesignerObjectInspectorInterface_Redirected(const QDesignerObjectInspectorInterface* self, QPoint* offset);
void QDesignerObjectInspectorInterface_OnRedirected(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QPaintDevice* QDesignerObjectInspectorInterface_QBaseRedirected(const QDesignerObjectInspectorInterface* self, QPoint* offset);
QPainter* QDesignerObjectInspectorInterface_SharedPainter(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnSharedPainter(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QPainter* QDesignerObjectInspectorInterface_QBaseSharedPainter(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_InputMethodEvent(QDesignerObjectInspectorInterface* self, QInputMethodEvent* param1);
void QDesignerObjectInspectorInterface_OnInputMethodEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseInputMethodEvent(QDesignerObjectInspectorInterface* self, QInputMethodEvent* param1);
QVariant* QDesignerObjectInspectorInterface_InputMethodQuery(const QDesignerObjectInspectorInterface* self, int param1);
void QDesignerObjectInspectorInterface_OnInputMethodQuery(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QVariant* QDesignerObjectInspectorInterface_QBaseInputMethodQuery(const QDesignerObjectInspectorInterface* self, int param1);
bool QDesignerObjectInspectorInterface_FocusNextPrevChild(QDesignerObjectInspectorInterface* self, bool next);
void QDesignerObjectInspectorInterface_OnFocusNextPrevChild(QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseFocusNextPrevChild(QDesignerObjectInspectorInterface* self, bool next);
bool QDesignerObjectInspectorInterface_EventFilter(QDesignerObjectInspectorInterface* self, QObject* watched, QEvent* event);
void QDesignerObjectInspectorInterface_OnEventFilter(QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseEventFilter(QDesignerObjectInspectorInterface* self, QObject* watched, QEvent* event);
void QDesignerObjectInspectorInterface_TimerEvent(QDesignerObjectInspectorInterface* self, QTimerEvent* event);
void QDesignerObjectInspectorInterface_OnTimerEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseTimerEvent(QDesignerObjectInspectorInterface* self, QTimerEvent* event);
void QDesignerObjectInspectorInterface_ChildEvent(QDesignerObjectInspectorInterface* self, QChildEvent* event);
void QDesignerObjectInspectorInterface_OnChildEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseChildEvent(QDesignerObjectInspectorInterface* self, QChildEvent* event);
void QDesignerObjectInspectorInterface_CustomEvent(QDesignerObjectInspectorInterface* self, QEvent* event);
void QDesignerObjectInspectorInterface_OnCustomEvent(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseCustomEvent(QDesignerObjectInspectorInterface* self, QEvent* event);
void QDesignerObjectInspectorInterface_ConnectNotify(QDesignerObjectInspectorInterface* self, const QMetaMethod* signal);
void QDesignerObjectInspectorInterface_OnConnectNotify(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseConnectNotify(QDesignerObjectInspectorInterface* self, const QMetaMethod* signal);
void QDesignerObjectInspectorInterface_DisconnectNotify(QDesignerObjectInspectorInterface* self, const QMetaMethod* signal);
void QDesignerObjectInspectorInterface_OnDisconnectNotify(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseDisconnectNotify(QDesignerObjectInspectorInterface* self, const QMetaMethod* signal);
void QDesignerObjectInspectorInterface_UpdateMicroFocus(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnUpdateMicroFocus(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseUpdateMicroFocus(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_Create(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnCreate(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseCreate(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_Destroy(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnDestroy(QDesignerObjectInspectorInterface* self, intptr_t slot);
void QDesignerObjectInspectorInterface_QBaseDestroy(QDesignerObjectInspectorInterface* self);
bool QDesignerObjectInspectorInterface_FocusNextChild(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnFocusNextChild(QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseFocusNextChild(QDesignerObjectInspectorInterface* self);
bool QDesignerObjectInspectorInterface_FocusPreviousChild(QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnFocusPreviousChild(QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseFocusPreviousChild(QDesignerObjectInspectorInterface* self);
QObject* QDesignerObjectInspectorInterface_Sender(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnSender(const QDesignerObjectInspectorInterface* self, intptr_t slot);
QObject* QDesignerObjectInspectorInterface_QBaseSender(const QDesignerObjectInspectorInterface* self);
int QDesignerObjectInspectorInterface_SenderSignalIndex(const QDesignerObjectInspectorInterface* self);
void QDesignerObjectInspectorInterface_OnSenderSignalIndex(const QDesignerObjectInspectorInterface* self, intptr_t slot);
int QDesignerObjectInspectorInterface_QBaseSenderSignalIndex(const QDesignerObjectInspectorInterface* self);
int QDesignerObjectInspectorInterface_Receivers(const QDesignerObjectInspectorInterface* self, const char* signal);
void QDesignerObjectInspectorInterface_OnReceivers(const QDesignerObjectInspectorInterface* self, intptr_t slot);
int QDesignerObjectInspectorInterface_QBaseReceivers(const QDesignerObjectInspectorInterface* self, const char* signal);
bool QDesignerObjectInspectorInterface_IsSignalConnected(const QDesignerObjectInspectorInterface* self, const QMetaMethod* signal);
void QDesignerObjectInspectorInterface_OnIsSignalConnected(const QDesignerObjectInspectorInterface* self, intptr_t slot);
bool QDesignerObjectInspectorInterface_QBaseIsSignalConnected(const QDesignerObjectInspectorInterface* self, const QMetaMethod* signal);
double QDesignerObjectInspectorInterface_GetDecodedMetricF(const QDesignerObjectInspectorInterface* self, int metricA, int metricB);
void QDesignerObjectInspectorInterface_OnGetDecodedMetricF(const QDesignerObjectInspectorInterface* self, intptr_t slot);
double QDesignerObjectInspectorInterface_QBaseGetDecodedMetricF(const QDesignerObjectInspectorInterface* self, int metricA, int metricB);
void QDesignerObjectInspectorInterface_Delete(QDesignerObjectInspectorInterface* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
