#pragma once
#ifndef DESIGNER_LIBABSTRACTFORMWINDOWMANAGER_H
#define DESIGNER_LIBABSTRACTFORMWINDOWMANAGER_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QAction QAction;
typedef struct QActionGroup QActionGroup;
typedef struct QChildEvent QChildEvent;
typedef struct QDesignerDnDItemInterface QDesignerDnDItemInterface;
typedef struct QDesignerFormEditorInterface QDesignerFormEditorInterface;
typedef struct QDesignerFormWindowInterface QDesignerFormWindowInterface;
typedef struct QDesignerFormWindowManagerInterface QDesignerFormWindowManagerInterface;
typedef struct QEvent QEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QObject QObject;
typedef struct QPixmap QPixmap;
typedef struct QTimerEvent QTimerEvent;
typedef struct QWidget QWidget;
#endif

QDesignerFormWindowManagerInterface* QDesignerFormWindowManagerInterface_new();
QDesignerFormWindowManagerInterface* QDesignerFormWindowManagerInterface_new2(QObject* parent);
QMetaObject* QDesignerFormWindowManagerInterface_MetaObject(const QDesignerFormWindowManagerInterface* self);
void* QDesignerFormWindowManagerInterface_Metacast(QDesignerFormWindowManagerInterface* self, const char* param1);
int QDesignerFormWindowManagerInterface_Metacall(QDesignerFormWindowManagerInterface* self, int param1, int param2, void** param3);
libqt_string QDesignerFormWindowManagerInterface_Tr(const char* s);
QAction* QDesignerFormWindowManagerInterface_Action(const QDesignerFormWindowManagerInterface* self, int action);
QActionGroup* QDesignerFormWindowManagerInterface_ActionGroup(const QDesignerFormWindowManagerInterface* self, int actionGroup);
QAction* QDesignerFormWindowManagerInterface_ActionCut(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionCopy(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionPaste(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionDelete(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionSelectAll(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionLower(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionRaise(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionUndo(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionRedo(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionHorizontalLayout(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionVerticalLayout(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionSplitHorizontal(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionSplitVertical(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionGridLayout(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionFormLayout(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionBreakLayout(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionAdjustSize(const QDesignerFormWindowManagerInterface* self);
QAction* QDesignerFormWindowManagerInterface_ActionSimplifyLayout(const QDesignerFormWindowManagerInterface* self);
QDesignerFormWindowInterface* QDesignerFormWindowManagerInterface_ActiveFormWindow(const QDesignerFormWindowManagerInterface* self);
int QDesignerFormWindowManagerInterface_FormWindowCount(const QDesignerFormWindowManagerInterface* self);
QDesignerFormWindowInterface* QDesignerFormWindowManagerInterface_FormWindow(const QDesignerFormWindowManagerInterface* self, int index);
QDesignerFormWindowInterface* QDesignerFormWindowManagerInterface_CreateFormWindow(QDesignerFormWindowManagerInterface* self, QWidget* parentWidget, int flags);
QDesignerFormEditorInterface* QDesignerFormWindowManagerInterface_Core(const QDesignerFormWindowManagerInterface* self);
void QDesignerFormWindowManagerInterface_DragItems(QDesignerFormWindowManagerInterface* self, const libqt_list /* of QDesignerDnDItemInterface* */ item_list);
QPixmap* QDesignerFormWindowManagerInterface_CreatePreviewPixmap(const QDesignerFormWindowManagerInterface* self);
void QDesignerFormWindowManagerInterface_FormWindowAdded(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerFormWindowManagerInterface_Connect_FormWindowAdded(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_FormWindowRemoved(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerFormWindowManagerInterface_Connect_FormWindowRemoved(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_ActiveFormWindowChanged(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerFormWindowManagerInterface_Connect_ActiveFormWindowChanged(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_FormWindowSettingsChanged(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* fw);
void QDesignerFormWindowManagerInterface_Connect_FormWindowSettingsChanged(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_AddFormWindow(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerFormWindowManagerInterface_RemoveFormWindow(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerFormWindowManagerInterface_SetActiveFormWindow(QDesignerFormWindowManagerInterface* self, QDesignerFormWindowInterface* formWindow);
void QDesignerFormWindowManagerInterface_ShowPreview(QDesignerFormWindowManagerInterface* self);
void QDesignerFormWindowManagerInterface_CloseAllPreviews(QDesignerFormWindowManagerInterface* self);
void QDesignerFormWindowManagerInterface_ShowPluginDialog(QDesignerFormWindowManagerInterface* self);
libqt_string QDesignerFormWindowManagerInterface_Tr2(const char* s, const char* c);
libqt_string QDesignerFormWindowManagerInterface_Tr3(const char* s, const char* c, int n);
void QDesignerFormWindowManagerInterface_OnMetaObject(QDesignerFormWindowManagerInterface* self, intptr_t slot);
QMetaObject* QDesignerFormWindowManagerInterface_SuperMetaObject(const QDesignerFormWindowManagerInterface* self);
void QDesignerFormWindowManagerInterface_OnMetacast(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void* QDesignerFormWindowManagerInterface_SuperMetacast(QDesignerFormWindowManagerInterface* self, const char* param1);
void QDesignerFormWindowManagerInterface_OnMetacall(QDesignerFormWindowManagerInterface* self, intptr_t slot);
int QDesignerFormWindowManagerInterface_SuperMetacall(QDesignerFormWindowManagerInterface* self, int param1, int param2, void** param3);
void QDesignerFormWindowManagerInterface_OnAction(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnActionGroup(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnActiveFormWindow(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnFormWindowCount(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnFormWindow(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnCreateFormWindow(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnCore(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnDragItems(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnCreatePreviewPixmap(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnAddFormWindow(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnRemoveFormWindow(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnSetActiveFormWindow(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnShowPreview(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnCloseAllPreviews(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_OnShowPluginDialog(QDesignerFormWindowManagerInterface* self, intptr_t slot);
bool QDesignerFormWindowManagerInterface_Event(QDesignerFormWindowManagerInterface* self, QEvent* event);
void QDesignerFormWindowManagerInterface_OnEvent(QDesignerFormWindowManagerInterface* self, intptr_t slot);
bool QDesignerFormWindowManagerInterface_SuperEvent(QDesignerFormWindowManagerInterface* self, QEvent* event);
bool QDesignerFormWindowManagerInterface_EventFilter(QDesignerFormWindowManagerInterface* self, QObject* watched, QEvent* event);
void QDesignerFormWindowManagerInterface_OnEventFilter(QDesignerFormWindowManagerInterface* self, intptr_t slot);
bool QDesignerFormWindowManagerInterface_SuperEventFilter(QDesignerFormWindowManagerInterface* self, QObject* watched, QEvent* event);
void QDesignerFormWindowManagerInterface_TimerEvent(QDesignerFormWindowManagerInterface* self, QTimerEvent* event);
void QDesignerFormWindowManagerInterface_OnTimerEvent(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_SuperTimerEvent(QDesignerFormWindowManagerInterface* self, QTimerEvent* event);
void QDesignerFormWindowManagerInterface_ChildEvent(QDesignerFormWindowManagerInterface* self, QChildEvent* event);
void QDesignerFormWindowManagerInterface_OnChildEvent(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_SuperChildEvent(QDesignerFormWindowManagerInterface* self, QChildEvent* event);
void QDesignerFormWindowManagerInterface_CustomEvent(QDesignerFormWindowManagerInterface* self, QEvent* event);
void QDesignerFormWindowManagerInterface_OnCustomEvent(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_SuperCustomEvent(QDesignerFormWindowManagerInterface* self, QEvent* event);
void QDesignerFormWindowManagerInterface_ConnectNotify(QDesignerFormWindowManagerInterface* self, const QMetaMethod* signal);
void QDesignerFormWindowManagerInterface_OnConnectNotify(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_SuperConnectNotify(QDesignerFormWindowManagerInterface* self, const QMetaMethod* signal);
void QDesignerFormWindowManagerInterface_DisconnectNotify(QDesignerFormWindowManagerInterface* self, const QMetaMethod* signal);
void QDesignerFormWindowManagerInterface_OnDisconnectNotify(QDesignerFormWindowManagerInterface* self, intptr_t slot);
void QDesignerFormWindowManagerInterface_SuperDisconnectNotify(QDesignerFormWindowManagerInterface* self, const QMetaMethod* signal);
QObject* QDesignerFormWindowManagerInterface_Sender(const QDesignerFormWindowManagerInterface* self);
int QDesignerFormWindowManagerInterface_SenderSignalIndex(const QDesignerFormWindowManagerInterface* self);
int QDesignerFormWindowManagerInterface_Receivers(const QDesignerFormWindowManagerInterface* self, const char* signal);
bool QDesignerFormWindowManagerInterface_IsSignalConnected(const QDesignerFormWindowManagerInterface* self, const QMetaMethod* signal);
void QDesignerFormWindowManagerInterface_Delete(QDesignerFormWindowManagerInterface* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
