#pragma once
#ifndef SRC_DESIGNERC_LIBDYNAMICPROPERTYSHEET_H
#define SRC_DESIGNERC_LIBDYNAMICPROPERTYSHEET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QDesignerDynamicPropertySheetExtension QDesignerDynamicPropertySheetExtension;
typedef struct QVariant QVariant;
#endif

QDesignerDynamicPropertySheetExtension* QDesignerDynamicPropertySheetExtension_new();
bool QDesignerDynamicPropertySheetExtension_DynamicPropertiesAllowed(const QDesignerDynamicPropertySheetExtension* self);
int QDesignerDynamicPropertySheetExtension_AddDynamicProperty(QDesignerDynamicPropertySheetExtension* self, const libqt_string propertyName, const QVariant* value);
bool QDesignerDynamicPropertySheetExtension_RemoveDynamicProperty(QDesignerDynamicPropertySheetExtension* self, int index);
bool QDesignerDynamicPropertySheetExtension_IsDynamicProperty(const QDesignerDynamicPropertySheetExtension* self, int index);
bool QDesignerDynamicPropertySheetExtension_CanAddDynamicProperty(const QDesignerDynamicPropertySheetExtension* self, const libqt_string propertyName);
void QDesignerDynamicPropertySheetExtension_OnDynamicPropertiesAllowed(const QDesignerDynamicPropertySheetExtension* self, intptr_t slot);
bool QDesignerDynamicPropertySheetExtension_SuperDynamicPropertiesAllowed(const QDesignerDynamicPropertySheetExtension* self);
void QDesignerDynamicPropertySheetExtension_OnAddDynamicProperty(QDesignerDynamicPropertySheetExtension* self, intptr_t slot);
int QDesignerDynamicPropertySheetExtension_SuperAddDynamicProperty(QDesignerDynamicPropertySheetExtension* self, const libqt_string propertyName, const QVariant* value);
void QDesignerDynamicPropertySheetExtension_OnRemoveDynamicProperty(QDesignerDynamicPropertySheetExtension* self, intptr_t slot);
bool QDesignerDynamicPropertySheetExtension_SuperRemoveDynamicProperty(QDesignerDynamicPropertySheetExtension* self, int index);
void QDesignerDynamicPropertySheetExtension_OnIsDynamicProperty(const QDesignerDynamicPropertySheetExtension* self, intptr_t slot);
bool QDesignerDynamicPropertySheetExtension_SuperIsDynamicProperty(const QDesignerDynamicPropertySheetExtension* self, int index);
void QDesignerDynamicPropertySheetExtension_OnCanAddDynamicProperty(const QDesignerDynamicPropertySheetExtension* self, intptr_t slot);
bool QDesignerDynamicPropertySheetExtension_SuperCanAddDynamicProperty(const QDesignerDynamicPropertySheetExtension* self, const libqt_string propertyName);
void QDesignerDynamicPropertySheetExtension_Delete(QDesignerDynamicPropertySheetExtension* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
