#pragma once
#ifndef SRC_EXTRAS_KIOC_LIBKURLREQUESTERDIALOG_H
#define SRC_EXTRAS_KIOC_LIBKURLREQUESTERDIALOG_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct KUrlRequester KUrlRequester;
typedef struct KUrlRequesterDialog KUrlRequesterDialog;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDialog QDialog;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

KUrlRequesterDialog* KUrlRequesterDialog_new(const QUrl* url);
KUrlRequesterDialog* KUrlRequesterDialog_new2(const QUrl* url, const libqt_string text, QWidget* parent);
KUrlRequesterDialog* KUrlRequesterDialog_new3(const QUrl* url, QWidget* parent);
QMetaObject* KUrlRequesterDialog_MetaObject(const KUrlRequesterDialog* self);
void* KUrlRequesterDialog_Metacast(KUrlRequesterDialog* self, const char* param1);
int KUrlRequesterDialog_Metacall(KUrlRequesterDialog* self, int param1, int param2, void** param3);
QUrl* KUrlRequesterDialog_SelectedUrl(const KUrlRequesterDialog* self);
QUrl* KUrlRequesterDialog_GetUrl();
KUrlRequester* KUrlRequesterDialog_UrlRequester(KUrlRequesterDialog* self);
QUrl* KUrlRequesterDialog_GetUrl1(const QUrl* url);
QUrl* KUrlRequesterDialog_GetUrl2(const QUrl* url, QWidget* parent);
QUrl* KUrlRequesterDialog_GetUrl3(const QUrl* url, QWidget* parent, const libqt_string title);
void KUrlRequesterDialog_OnMetaObject(const KUrlRequesterDialog* self, intptr_t slot);
QMetaObject* KUrlRequesterDialog_SuperMetaObject(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnMetacast(KUrlRequesterDialog* self, intptr_t slot);
void* KUrlRequesterDialog_SuperMetacast(KUrlRequesterDialog* self, const char* param1);
void KUrlRequesterDialog_OnMetacall(KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperMetacall(KUrlRequesterDialog* self, int param1, int param2, void** param3);
void KUrlRequesterDialog_SetVisible(KUrlRequesterDialog* self, bool visible);
void KUrlRequesterDialog_OnSetVisible(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperSetVisible(KUrlRequesterDialog* self, bool visible);
QSize* KUrlRequesterDialog_SizeHint(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnSizeHint(const KUrlRequesterDialog* self, intptr_t slot);
QSize* KUrlRequesterDialog_SuperSizeHint(const KUrlRequesterDialog* self);
QSize* KUrlRequesterDialog_MinimumSizeHint(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnMinimumSizeHint(const KUrlRequesterDialog* self, intptr_t slot);
QSize* KUrlRequesterDialog_SuperMinimumSizeHint(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_Open(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnOpen(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperOpen(KUrlRequesterDialog* self);
int KUrlRequesterDialog_Exec(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnExec(KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperExec(KUrlRequesterDialog* self);
void KUrlRequesterDialog_Done(KUrlRequesterDialog* self, int param1);
void KUrlRequesterDialog_OnDone(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDone(KUrlRequesterDialog* self, int param1);
void KUrlRequesterDialog_Accept(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnAccept(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperAccept(KUrlRequesterDialog* self);
void KUrlRequesterDialog_Reject(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnReject(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperReject(KUrlRequesterDialog* self);
void KUrlRequesterDialog_KeyPressEvent(KUrlRequesterDialog* self, QKeyEvent* param1);
void KUrlRequesterDialog_OnKeyPressEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperKeyPressEvent(KUrlRequesterDialog* self, QKeyEvent* param1);
void KUrlRequesterDialog_CloseEvent(KUrlRequesterDialog* self, QCloseEvent* param1);
void KUrlRequesterDialog_OnCloseEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperCloseEvent(KUrlRequesterDialog* self, QCloseEvent* param1);
void KUrlRequesterDialog_ShowEvent(KUrlRequesterDialog* self, QShowEvent* param1);
void KUrlRequesterDialog_OnShowEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperShowEvent(KUrlRequesterDialog* self, QShowEvent* param1);
void KUrlRequesterDialog_ResizeEvent(KUrlRequesterDialog* self, QResizeEvent* param1);
void KUrlRequesterDialog_OnResizeEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperResizeEvent(KUrlRequesterDialog* self, QResizeEvent* param1);
void KUrlRequesterDialog_ContextMenuEvent(KUrlRequesterDialog* self, QContextMenuEvent* param1);
void KUrlRequesterDialog_OnContextMenuEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperContextMenuEvent(KUrlRequesterDialog* self, QContextMenuEvent* param1);
bool KUrlRequesterDialog_EventFilter(KUrlRequesterDialog* self, QObject* param1, QEvent* param2);
void KUrlRequesterDialog_OnEventFilter(KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperEventFilter(KUrlRequesterDialog* self, QObject* param1, QEvent* param2);
int KUrlRequesterDialog_DevType(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnDevType(const KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperDevType(const KUrlRequesterDialog* self);
int KUrlRequesterDialog_HeightForWidth(const KUrlRequesterDialog* self, int param1);
void KUrlRequesterDialog_OnHeightForWidth(const KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperHeightForWidth(const KUrlRequesterDialog* self, int param1);
bool KUrlRequesterDialog_HasHeightForWidth(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnHasHeightForWidth(const KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperHasHeightForWidth(const KUrlRequesterDialog* self);
QPaintEngine* KUrlRequesterDialog_PaintEngine(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnPaintEngine(const KUrlRequesterDialog* self, intptr_t slot);
QPaintEngine* KUrlRequesterDialog_SuperPaintEngine(const KUrlRequesterDialog* self);
bool KUrlRequesterDialog_Event(KUrlRequesterDialog* self, QEvent* event);
void KUrlRequesterDialog_OnEvent(KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperEvent(KUrlRequesterDialog* self, QEvent* event);
void KUrlRequesterDialog_MousePressEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_OnMousePressEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperMousePressEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_MouseReleaseEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_OnMouseReleaseEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperMouseReleaseEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_MouseDoubleClickEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_OnMouseDoubleClickEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperMouseDoubleClickEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_MouseMoveEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_OnMouseMoveEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperMouseMoveEvent(KUrlRequesterDialog* self, QMouseEvent* event);
void KUrlRequesterDialog_WheelEvent(KUrlRequesterDialog* self, QWheelEvent* event);
void KUrlRequesterDialog_OnWheelEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperWheelEvent(KUrlRequesterDialog* self, QWheelEvent* event);
void KUrlRequesterDialog_KeyReleaseEvent(KUrlRequesterDialog* self, QKeyEvent* event);
void KUrlRequesterDialog_OnKeyReleaseEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperKeyReleaseEvent(KUrlRequesterDialog* self, QKeyEvent* event);
void KUrlRequesterDialog_FocusInEvent(KUrlRequesterDialog* self, QFocusEvent* event);
void KUrlRequesterDialog_OnFocusInEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperFocusInEvent(KUrlRequesterDialog* self, QFocusEvent* event);
void KUrlRequesterDialog_FocusOutEvent(KUrlRequesterDialog* self, QFocusEvent* event);
void KUrlRequesterDialog_OnFocusOutEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperFocusOutEvent(KUrlRequesterDialog* self, QFocusEvent* event);
void KUrlRequesterDialog_EnterEvent(KUrlRequesterDialog* self, QEnterEvent* event);
void KUrlRequesterDialog_OnEnterEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperEnterEvent(KUrlRequesterDialog* self, QEnterEvent* event);
void KUrlRequesterDialog_LeaveEvent(KUrlRequesterDialog* self, QEvent* event);
void KUrlRequesterDialog_OnLeaveEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperLeaveEvent(KUrlRequesterDialog* self, QEvent* event);
void KUrlRequesterDialog_PaintEvent(KUrlRequesterDialog* self, QPaintEvent* event);
void KUrlRequesterDialog_OnPaintEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperPaintEvent(KUrlRequesterDialog* self, QPaintEvent* event);
void KUrlRequesterDialog_MoveEvent(KUrlRequesterDialog* self, QMoveEvent* event);
void KUrlRequesterDialog_OnMoveEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperMoveEvent(KUrlRequesterDialog* self, QMoveEvent* event);
void KUrlRequesterDialog_TabletEvent(KUrlRequesterDialog* self, QTabletEvent* event);
void KUrlRequesterDialog_OnTabletEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperTabletEvent(KUrlRequesterDialog* self, QTabletEvent* event);
void KUrlRequesterDialog_ActionEvent(KUrlRequesterDialog* self, QActionEvent* event);
void KUrlRequesterDialog_OnActionEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperActionEvent(KUrlRequesterDialog* self, QActionEvent* event);
void KUrlRequesterDialog_DragEnterEvent(KUrlRequesterDialog* self, QDragEnterEvent* event);
void KUrlRequesterDialog_OnDragEnterEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDragEnterEvent(KUrlRequesterDialog* self, QDragEnterEvent* event);
void KUrlRequesterDialog_DragMoveEvent(KUrlRequesterDialog* self, QDragMoveEvent* event);
void KUrlRequesterDialog_OnDragMoveEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDragMoveEvent(KUrlRequesterDialog* self, QDragMoveEvent* event);
void KUrlRequesterDialog_DragLeaveEvent(KUrlRequesterDialog* self, QDragLeaveEvent* event);
void KUrlRequesterDialog_OnDragLeaveEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDragLeaveEvent(KUrlRequesterDialog* self, QDragLeaveEvent* event);
void KUrlRequesterDialog_DropEvent(KUrlRequesterDialog* self, QDropEvent* event);
void KUrlRequesterDialog_OnDropEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDropEvent(KUrlRequesterDialog* self, QDropEvent* event);
void KUrlRequesterDialog_HideEvent(KUrlRequesterDialog* self, QHideEvent* event);
void KUrlRequesterDialog_OnHideEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperHideEvent(KUrlRequesterDialog* self, QHideEvent* event);
bool KUrlRequesterDialog_NativeEvent(KUrlRequesterDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KUrlRequesterDialog_OnNativeEvent(KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperNativeEvent(KUrlRequesterDialog* self, const libqt_string eventType, void* message, intptr_t* result);
void KUrlRequesterDialog_ChangeEvent(KUrlRequesterDialog* self, QEvent* param1);
void KUrlRequesterDialog_OnChangeEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperChangeEvent(KUrlRequesterDialog* self, QEvent* param1);
int KUrlRequesterDialog_Metric(const KUrlRequesterDialog* self, int param1);
void KUrlRequesterDialog_OnMetric(const KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperMetric(const KUrlRequesterDialog* self, int param1);
void KUrlRequesterDialog_InitPainter(const KUrlRequesterDialog* self, QPainter* painter);
void KUrlRequesterDialog_OnInitPainter(const KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperInitPainter(const KUrlRequesterDialog* self, QPainter* painter);
QPaintDevice* KUrlRequesterDialog_Redirected(const KUrlRequesterDialog* self, QPoint* offset);
void KUrlRequesterDialog_OnRedirected(const KUrlRequesterDialog* self, intptr_t slot);
QPaintDevice* KUrlRequesterDialog_SuperRedirected(const KUrlRequesterDialog* self, QPoint* offset);
QPainter* KUrlRequesterDialog_SharedPainter(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnSharedPainter(const KUrlRequesterDialog* self, intptr_t slot);
QPainter* KUrlRequesterDialog_SuperSharedPainter(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_InputMethodEvent(KUrlRequesterDialog* self, QInputMethodEvent* param1);
void KUrlRequesterDialog_OnInputMethodEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperInputMethodEvent(KUrlRequesterDialog* self, QInputMethodEvent* param1);
QVariant* KUrlRequesterDialog_InputMethodQuery(const KUrlRequesterDialog* self, int param1);
void KUrlRequesterDialog_OnInputMethodQuery(const KUrlRequesterDialog* self, intptr_t slot);
QVariant* KUrlRequesterDialog_SuperInputMethodQuery(const KUrlRequesterDialog* self, int param1);
bool KUrlRequesterDialog_FocusNextPrevChild(KUrlRequesterDialog* self, bool next);
void KUrlRequesterDialog_OnFocusNextPrevChild(KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperFocusNextPrevChild(KUrlRequesterDialog* self, bool next);
void KUrlRequesterDialog_TimerEvent(KUrlRequesterDialog* self, QTimerEvent* event);
void KUrlRequesterDialog_OnTimerEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperTimerEvent(KUrlRequesterDialog* self, QTimerEvent* event);
void KUrlRequesterDialog_ChildEvent(KUrlRequesterDialog* self, QChildEvent* event);
void KUrlRequesterDialog_OnChildEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperChildEvent(KUrlRequesterDialog* self, QChildEvent* event);
void KUrlRequesterDialog_CustomEvent(KUrlRequesterDialog* self, QEvent* event);
void KUrlRequesterDialog_OnCustomEvent(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperCustomEvent(KUrlRequesterDialog* self, QEvent* event);
void KUrlRequesterDialog_ConnectNotify(KUrlRequesterDialog* self, const QMetaMethod* signal);
void KUrlRequesterDialog_OnConnectNotify(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperConnectNotify(KUrlRequesterDialog* self, const QMetaMethod* signal);
void KUrlRequesterDialog_DisconnectNotify(KUrlRequesterDialog* self, const QMetaMethod* signal);
void KUrlRequesterDialog_OnDisconnectNotify(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDisconnectNotify(KUrlRequesterDialog* self, const QMetaMethod* signal);
void KUrlRequesterDialog_AdjustPosition(KUrlRequesterDialog* self, QWidget* param1);
void KUrlRequesterDialog_OnAdjustPosition(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperAdjustPosition(KUrlRequesterDialog* self, QWidget* param1);
void KUrlRequesterDialog_UpdateMicroFocus(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnUpdateMicroFocus(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperUpdateMicroFocus(KUrlRequesterDialog* self);
void KUrlRequesterDialog_Create(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnCreate(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperCreate(KUrlRequesterDialog* self);
void KUrlRequesterDialog_Destroy(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnDestroy(KUrlRequesterDialog* self, intptr_t slot);
void KUrlRequesterDialog_SuperDestroy(KUrlRequesterDialog* self);
bool KUrlRequesterDialog_FocusNextChild(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnFocusNextChild(KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperFocusNextChild(KUrlRequesterDialog* self);
bool KUrlRequesterDialog_FocusPreviousChild(KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnFocusPreviousChild(KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperFocusPreviousChild(KUrlRequesterDialog* self);
QObject* KUrlRequesterDialog_Sender(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnSender(const KUrlRequesterDialog* self, intptr_t slot);
QObject* KUrlRequesterDialog_SuperSender(const KUrlRequesterDialog* self);
int KUrlRequesterDialog_SenderSignalIndex(const KUrlRequesterDialog* self);
void KUrlRequesterDialog_OnSenderSignalIndex(const KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperSenderSignalIndex(const KUrlRequesterDialog* self);
int KUrlRequesterDialog_Receivers(const KUrlRequesterDialog* self, const char* signal);
void KUrlRequesterDialog_OnReceivers(const KUrlRequesterDialog* self, intptr_t slot);
int KUrlRequesterDialog_SuperReceivers(const KUrlRequesterDialog* self, const char* signal);
bool KUrlRequesterDialog_IsSignalConnected(const KUrlRequesterDialog* self, const QMetaMethod* signal);
void KUrlRequesterDialog_OnIsSignalConnected(const KUrlRequesterDialog* self, intptr_t slot);
bool KUrlRequesterDialog_SuperIsSignalConnected(const KUrlRequesterDialog* self, const QMetaMethod* signal);
double KUrlRequesterDialog_GetDecodedMetricF(const KUrlRequesterDialog* self, int metricA, int metricB);
void KUrlRequesterDialog_OnGetDecodedMetricF(const KUrlRequesterDialog* self, intptr_t slot);
double KUrlRequesterDialog_SuperGetDecodedMetricF(const KUrlRequesterDialog* self, int metricA, int metricB);
void KUrlRequesterDialog_Delete(KUrlRequesterDialog* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
