#pragma once
#ifndef QUICK_LIBQQUICKWIDGET_H
#define QUICK_LIBQQUICKWIDGET_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#else
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QColor QColor;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEnterEvent QEnterEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPoint QPoint;
typedef struct QQmlComponent QQmlComponent;
typedef struct QQmlContext QQmlContext;
typedef struct QQmlEngine QQmlEngine;
typedef struct QQmlError QQmlError;
typedef struct QQuickItem QQuickItem;
typedef struct QQuickWidget QQuickWidget;
typedef struct QQuickWindow QQuickWindow;
typedef struct QResizeEvent QResizeEvent;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QSurfaceFormat QSurfaceFormat;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
#endif

QQuickWidget* QQuickWidget_new(QWidget* parent);
QQuickWidget* QQuickWidget_new2();
QQuickWidget* QQuickWidget_new3(QQmlEngine* engine, QWidget* parent);
QQuickWidget* QQuickWidget_new4(const QUrl* source);
QQuickWidget* QQuickWidget_new5(const QUrl* source, QWidget* parent);
QMetaObject* QQuickWidget_MetaObject(const QQuickWidget* self);
void* QQuickWidget_Metacast(QQuickWidget* self, const char* param1);
int QQuickWidget_Metacall(QQuickWidget* self, int param1, int param2, void** param3);
libqt_string QQuickWidget_Tr(const char* s);
QUrl* QQuickWidget_Source(const QQuickWidget* self);
QQmlEngine* QQuickWidget_Engine(const QQuickWidget* self);
QQmlContext* QQuickWidget_RootContext(const QQuickWidget* self);
QQuickItem* QQuickWidget_RootObject(const QQuickWidget* self);
int QQuickWidget_ResizeMode(const QQuickWidget* self);
void QQuickWidget_SetResizeMode(QQuickWidget* self, int resizeMode);
int QQuickWidget_Status(const QQuickWidget* self);
libqt_list /* of QQmlError* */ QQuickWidget_Errors(const QQuickWidget* self);
QSize* QQuickWidget_SizeHint(const QQuickWidget* self);
QSize* QQuickWidget_InitialSize(const QQuickWidget* self);
void QQuickWidget_SetFormat(QQuickWidget* self, const QSurfaceFormat* format);
QSurfaceFormat* QQuickWidget_Format(const QQuickWidget* self);
QImage* QQuickWidget_GrabFramebuffer(const QQuickWidget* self);
void QQuickWidget_SetClearColor(QQuickWidget* self, const QColor* color);
QQuickWindow* QQuickWidget_QuickWindow(const QQuickWidget* self);
void QQuickWidget_SetSource(QQuickWidget* self, const QUrl* source);
void QQuickWidget_SetContent(QQuickWidget* self, const QUrl* url, QQmlComponent* component, QObject* item);
void QQuickWidget_StatusChanged(QQuickWidget* self, int param1);
void QQuickWidget_Connect_StatusChanged(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SceneGraphError(QQuickWidget* self, int errorVal, const libqt_string message);
void QQuickWidget_Connect_SceneGraphError(QQuickWidget* self, intptr_t slot);
void QQuickWidget_ResizeEvent(QQuickWidget* self, QResizeEvent* param1);
void QQuickWidget_TimerEvent(QQuickWidget* self, QTimerEvent* param1);
void QQuickWidget_KeyPressEvent(QQuickWidget* self, QKeyEvent* param1);
void QQuickWidget_KeyReleaseEvent(QQuickWidget* self, QKeyEvent* param1);
void QQuickWidget_MousePressEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_MouseReleaseEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_MouseMoveEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_MouseDoubleClickEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_ShowEvent(QQuickWidget* self, QShowEvent* param1);
void QQuickWidget_HideEvent(QQuickWidget* self, QHideEvent* param1);
void QQuickWidget_FocusInEvent(QQuickWidget* self, QFocusEvent* event);
void QQuickWidget_FocusOutEvent(QQuickWidget* self, QFocusEvent* event);
void QQuickWidget_WheelEvent(QQuickWidget* self, QWheelEvent* param1);
void QQuickWidget_DragEnterEvent(QQuickWidget* self, QDragEnterEvent* param1);
void QQuickWidget_DragMoveEvent(QQuickWidget* self, QDragMoveEvent* param1);
void QQuickWidget_DragLeaveEvent(QQuickWidget* self, QDragLeaveEvent* param1);
void QQuickWidget_DropEvent(QQuickWidget* self, QDropEvent* param1);
bool QQuickWidget_Event(QQuickWidget* self, QEvent* param1);
void QQuickWidget_PaintEvent(QQuickWidget* self, QPaintEvent* event);
bool QQuickWidget_FocusNextPrevChild(QQuickWidget* self, bool next);
libqt_string QQuickWidget_Tr2(const char* s, const char* c);
libqt_string QQuickWidget_Tr3(const char* s, const char* c, int n);
void QQuickWidget_OnMetaObject(const QQuickWidget* self, intptr_t slot);
QMetaObject* QQuickWidget_SuperMetaObject(const QQuickWidget* self);
void QQuickWidget_OnMetacast(QQuickWidget* self, intptr_t slot);
void* QQuickWidget_SuperMetacast(QQuickWidget* self, const char* param1);
void QQuickWidget_OnMetacall(QQuickWidget* self, intptr_t slot);
int QQuickWidget_SuperMetacall(QQuickWidget* self, int param1, int param2, void** param3);
void QQuickWidget_OnSizeHint(const QQuickWidget* self, intptr_t slot);
QSize* QQuickWidget_SuperSizeHint(const QQuickWidget* self);
void QQuickWidget_OnResizeEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperResizeEvent(QQuickWidget* self, QResizeEvent* param1);
void QQuickWidget_OnTimerEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperTimerEvent(QQuickWidget* self, QTimerEvent* param1);
void QQuickWidget_OnKeyPressEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperKeyPressEvent(QQuickWidget* self, QKeyEvent* param1);
void QQuickWidget_OnKeyReleaseEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperKeyReleaseEvent(QQuickWidget* self, QKeyEvent* param1);
void QQuickWidget_OnMousePressEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperMousePressEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_OnMouseReleaseEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperMouseReleaseEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_OnMouseMoveEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperMouseMoveEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_OnMouseDoubleClickEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperMouseDoubleClickEvent(QQuickWidget* self, QMouseEvent* param1);
void QQuickWidget_OnShowEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperShowEvent(QQuickWidget* self, QShowEvent* param1);
void QQuickWidget_OnHideEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperHideEvent(QQuickWidget* self, QHideEvent* param1);
void QQuickWidget_OnFocusInEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperFocusInEvent(QQuickWidget* self, QFocusEvent* event);
void QQuickWidget_OnFocusOutEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperFocusOutEvent(QQuickWidget* self, QFocusEvent* event);
void QQuickWidget_OnWheelEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperWheelEvent(QQuickWidget* self, QWheelEvent* param1);
void QQuickWidget_OnDragEnterEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperDragEnterEvent(QQuickWidget* self, QDragEnterEvent* param1);
void QQuickWidget_OnDragMoveEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperDragMoveEvent(QQuickWidget* self, QDragMoveEvent* param1);
void QQuickWidget_OnDragLeaveEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperDragLeaveEvent(QQuickWidget* self, QDragLeaveEvent* param1);
void QQuickWidget_OnDropEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperDropEvent(QQuickWidget* self, QDropEvent* param1);
void QQuickWidget_OnEvent(QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperEvent(QQuickWidget* self, QEvent* param1);
void QQuickWidget_OnPaintEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperPaintEvent(QQuickWidget* self, QPaintEvent* event);
void QQuickWidget_OnFocusNextPrevChild(QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperFocusNextPrevChild(QQuickWidget* self, bool next);
int QQuickWidget_DevType(const QQuickWidget* self);
void QQuickWidget_OnDevType(const QQuickWidget* self, intptr_t slot);
int QQuickWidget_SuperDevType(const QQuickWidget* self);
void QQuickWidget_SetVisible(QQuickWidget* self, bool visible);
void QQuickWidget_OnSetVisible(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperSetVisible(QQuickWidget* self, bool visible);
QSize* QQuickWidget_MinimumSizeHint(const QQuickWidget* self);
void QQuickWidget_OnMinimumSizeHint(const QQuickWidget* self, intptr_t slot);
QSize* QQuickWidget_SuperMinimumSizeHint(const QQuickWidget* self);
int QQuickWidget_HeightForWidth(const QQuickWidget* self, int param1);
void QQuickWidget_OnHeightForWidth(const QQuickWidget* self, intptr_t slot);
int QQuickWidget_SuperHeightForWidth(const QQuickWidget* self, int param1);
bool QQuickWidget_HasHeightForWidth(const QQuickWidget* self);
void QQuickWidget_OnHasHeightForWidth(const QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperHasHeightForWidth(const QQuickWidget* self);
QPaintEngine* QQuickWidget_PaintEngine(const QQuickWidget* self);
void QQuickWidget_OnPaintEngine(const QQuickWidget* self, intptr_t slot);
QPaintEngine* QQuickWidget_SuperPaintEngine(const QQuickWidget* self);
void QQuickWidget_EnterEvent(QQuickWidget* self, QEnterEvent* event);
void QQuickWidget_OnEnterEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperEnterEvent(QQuickWidget* self, QEnterEvent* event);
void QQuickWidget_LeaveEvent(QQuickWidget* self, QEvent* event);
void QQuickWidget_OnLeaveEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperLeaveEvent(QQuickWidget* self, QEvent* event);
void QQuickWidget_MoveEvent(QQuickWidget* self, QMoveEvent* event);
void QQuickWidget_OnMoveEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperMoveEvent(QQuickWidget* self, QMoveEvent* event);
void QQuickWidget_CloseEvent(QQuickWidget* self, QCloseEvent* event);
void QQuickWidget_OnCloseEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperCloseEvent(QQuickWidget* self, QCloseEvent* event);
void QQuickWidget_ContextMenuEvent(QQuickWidget* self, QContextMenuEvent* event);
void QQuickWidget_OnContextMenuEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperContextMenuEvent(QQuickWidget* self, QContextMenuEvent* event);
void QQuickWidget_TabletEvent(QQuickWidget* self, QTabletEvent* event);
void QQuickWidget_OnTabletEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperTabletEvent(QQuickWidget* self, QTabletEvent* event);
void QQuickWidget_ActionEvent(QQuickWidget* self, QActionEvent* event);
void QQuickWidget_OnActionEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperActionEvent(QQuickWidget* self, QActionEvent* event);
bool QQuickWidget_NativeEvent(QQuickWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QQuickWidget_OnNativeEvent(QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperNativeEvent(QQuickWidget* self, const libqt_string eventType, void* message, intptr_t* result);
void QQuickWidget_ChangeEvent(QQuickWidget* self, QEvent* param1);
void QQuickWidget_OnChangeEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperChangeEvent(QQuickWidget* self, QEvent* param1);
int QQuickWidget_Metric(const QQuickWidget* self, int param1);
void QQuickWidget_OnMetric(const QQuickWidget* self, intptr_t slot);
int QQuickWidget_SuperMetric(const QQuickWidget* self, int param1);
void QQuickWidget_InitPainter(const QQuickWidget* self, QPainter* painter);
void QQuickWidget_OnInitPainter(const QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperInitPainter(const QQuickWidget* self, QPainter* painter);
QPaintDevice* QQuickWidget_Redirected(const QQuickWidget* self, QPoint* offset);
void QQuickWidget_OnRedirected(const QQuickWidget* self, intptr_t slot);
QPaintDevice* QQuickWidget_SuperRedirected(const QQuickWidget* self, QPoint* offset);
QPainter* QQuickWidget_SharedPainter(const QQuickWidget* self);
void QQuickWidget_OnSharedPainter(const QQuickWidget* self, intptr_t slot);
QPainter* QQuickWidget_SuperSharedPainter(const QQuickWidget* self);
void QQuickWidget_InputMethodEvent(QQuickWidget* self, QInputMethodEvent* param1);
void QQuickWidget_OnInputMethodEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperInputMethodEvent(QQuickWidget* self, QInputMethodEvent* param1);
QVariant* QQuickWidget_InputMethodQuery(const QQuickWidget* self, int param1);
void QQuickWidget_OnInputMethodQuery(const QQuickWidget* self, intptr_t slot);
QVariant* QQuickWidget_SuperInputMethodQuery(const QQuickWidget* self, int param1);
bool QQuickWidget_EventFilter(QQuickWidget* self, QObject* watched, QEvent* event);
void QQuickWidget_OnEventFilter(QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperEventFilter(QQuickWidget* self, QObject* watched, QEvent* event);
void QQuickWidget_ChildEvent(QQuickWidget* self, QChildEvent* event);
void QQuickWidget_OnChildEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperChildEvent(QQuickWidget* self, QChildEvent* event);
void QQuickWidget_CustomEvent(QQuickWidget* self, QEvent* event);
void QQuickWidget_OnCustomEvent(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperCustomEvent(QQuickWidget* self, QEvent* event);
void QQuickWidget_ConnectNotify(QQuickWidget* self, const QMetaMethod* signal);
void QQuickWidget_OnConnectNotify(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperConnectNotify(QQuickWidget* self, const QMetaMethod* signal);
void QQuickWidget_DisconnectNotify(QQuickWidget* self, const QMetaMethod* signal);
void QQuickWidget_OnDisconnectNotify(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperDisconnectNotify(QQuickWidget* self, const QMetaMethod* signal);
void QQuickWidget_UpdateMicroFocus(QQuickWidget* self);
void QQuickWidget_OnUpdateMicroFocus(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperUpdateMicroFocus(QQuickWidget* self);
void QQuickWidget_Create(QQuickWidget* self);
void QQuickWidget_OnCreate(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperCreate(QQuickWidget* self);
void QQuickWidget_Destroy(QQuickWidget* self);
void QQuickWidget_OnDestroy(QQuickWidget* self, intptr_t slot);
void QQuickWidget_SuperDestroy(QQuickWidget* self);
bool QQuickWidget_FocusNextChild(QQuickWidget* self);
void QQuickWidget_OnFocusNextChild(QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperFocusNextChild(QQuickWidget* self);
bool QQuickWidget_FocusPreviousChild(QQuickWidget* self);
void QQuickWidget_OnFocusPreviousChild(QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperFocusPreviousChild(QQuickWidget* self);
QObject* QQuickWidget_Sender(const QQuickWidget* self);
void QQuickWidget_OnSender(const QQuickWidget* self, intptr_t slot);
QObject* QQuickWidget_SuperSender(const QQuickWidget* self);
int QQuickWidget_SenderSignalIndex(const QQuickWidget* self);
void QQuickWidget_OnSenderSignalIndex(const QQuickWidget* self, intptr_t slot);
int QQuickWidget_SuperSenderSignalIndex(const QQuickWidget* self);
int QQuickWidget_Receivers(const QQuickWidget* self, const char* signal);
void QQuickWidget_OnReceivers(const QQuickWidget* self, intptr_t slot);
int QQuickWidget_SuperReceivers(const QQuickWidget* self, const char* signal);
bool QQuickWidget_IsSignalConnected(const QQuickWidget* self, const QMetaMethod* signal);
void QQuickWidget_OnIsSignalConnected(const QQuickWidget* self, intptr_t slot);
bool QQuickWidget_SuperIsSignalConnected(const QQuickWidget* self, const QMetaMethod* signal);
double QQuickWidget_GetDecodedMetricF(const QQuickWidget* self, int metricA, int metricB);
void QQuickWidget_OnGetDecodedMetricF(const QQuickWidget* self, intptr_t slot);
double QQuickWidget_SuperGetDecodedMetricF(const QQuickWidget* self, int metricA, int metricB);
void QQuickWidget_Delete(QQuickWidget* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
