#pragma once
#ifndef QUICK_LIBQQUICKITEM_H
#define QUICK_LIBQQUICKITEM_H

#include <stdbool.h>
#include <stddef.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QQuickItem__ItemChangeData)
typedef QQuickItem::ItemChangeData QQuickItem__ItemChangeData;
#endif
#if defined(WORKAROUND_INNER_CLASS_DEFINITION_QQuickItem__UpdatePaintNodeData)
typedef QQuickItem::UpdatePaintNodeData QQuickItem__UpdatePaintNodeData;
#endif
#else
typedef struct QChildEvent QChildEvent;
typedef struct QCursor QCursor;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QHoverEvent QHoverEvent;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QJSValue QJSValue;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMatrix4x4 QMatrix4x4;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMouseEvent QMouseEvent;
typedef struct QObject QObject;
typedef struct QPointF QPointF;
typedef struct QQmlParserStatus QQmlParserStatus;
typedef struct QQuickItem QQuickItem;
typedef struct QQuickItem__ItemChangeData QQuickItem__ItemChangeData;
typedef struct QQuickItem__UpdatePaintNodeData QQuickItem__UpdatePaintNodeData;
typedef struct QQuickTransform QQuickTransform;
typedef struct QQuickWindow QQuickWindow;
typedef struct QRectF QRectF;
typedef struct QSGNode QSGNode;
typedef struct QSGTextureProvider QSGTextureProvider;
typedef struct QSGTransformNode QSGTransformNode;
typedef struct QSize QSize;
typedef struct QSizeF QSizeF;
typedef struct QTimerEvent QTimerEvent;
typedef struct QTouchEvent QTouchEvent;
typedef struct QTransform QTransform;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
#endif

QQuickTransform* QQuickTransform_new();
QQuickTransform* QQuickTransform_new2(QObject* parent);
QMetaObject* QQuickTransform_MetaObject(const QQuickTransform* self);
void* QQuickTransform_Metacast(QQuickTransform* self, const char* param1);
int QQuickTransform_Metacall(QQuickTransform* self, int param1, int param2, void** param3);
libqt_string QQuickTransform_Tr(const char* s);
void QQuickTransform_AppendToItem(QQuickTransform* self, QQuickItem* param1);
void QQuickTransform_PrependToItem(QQuickTransform* self, QQuickItem* param1);
void QQuickTransform_ApplyTo(const QQuickTransform* self, QMatrix4x4* matrix);
libqt_string QQuickTransform_Tr2(const char* s, const char* c);
libqt_string QQuickTransform_Tr3(const char* s, const char* c, int n);
void QQuickTransform_OnMetaObject(const QQuickTransform* self, intptr_t slot);
QMetaObject* QQuickTransform_SuperMetaObject(const QQuickTransform* self);
void QQuickTransform_OnMetacast(QQuickTransform* self, intptr_t slot);
void* QQuickTransform_SuperMetacast(QQuickTransform* self, const char* param1);
void QQuickTransform_OnMetacall(QQuickTransform* self, intptr_t slot);
int QQuickTransform_SuperMetacall(QQuickTransform* self, int param1, int param2, void** param3);
void QQuickTransform_OnApplyTo(const QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperApplyTo(const QQuickTransform* self, QMatrix4x4* matrix);
bool QQuickTransform_Event(QQuickTransform* self, QEvent* event);
void QQuickTransform_OnEvent(QQuickTransform* self, intptr_t slot);
bool QQuickTransform_SuperEvent(QQuickTransform* self, QEvent* event);
bool QQuickTransform_EventFilter(QQuickTransform* self, QObject* watched, QEvent* event);
void QQuickTransform_OnEventFilter(QQuickTransform* self, intptr_t slot);
bool QQuickTransform_SuperEventFilter(QQuickTransform* self, QObject* watched, QEvent* event);
void QQuickTransform_TimerEvent(QQuickTransform* self, QTimerEvent* event);
void QQuickTransform_OnTimerEvent(QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperTimerEvent(QQuickTransform* self, QTimerEvent* event);
void QQuickTransform_ChildEvent(QQuickTransform* self, QChildEvent* event);
void QQuickTransform_OnChildEvent(QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperChildEvent(QQuickTransform* self, QChildEvent* event);
void QQuickTransform_CustomEvent(QQuickTransform* self, QEvent* event);
void QQuickTransform_OnCustomEvent(QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperCustomEvent(QQuickTransform* self, QEvent* event);
void QQuickTransform_ConnectNotify(QQuickTransform* self, const QMetaMethod* signal);
void QQuickTransform_OnConnectNotify(QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperConnectNotify(QQuickTransform* self, const QMetaMethod* signal);
void QQuickTransform_DisconnectNotify(QQuickTransform* self, const QMetaMethod* signal);
void QQuickTransform_OnDisconnectNotify(QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperDisconnectNotify(QQuickTransform* self, const QMetaMethod* signal);
void QQuickTransform_Update(QQuickTransform* self);
void QQuickTransform_OnUpdate(QQuickTransform* self, intptr_t slot);
void QQuickTransform_SuperUpdate(QQuickTransform* self);
QObject* QQuickTransform_Sender(const QQuickTransform* self);
void QQuickTransform_OnSender(const QQuickTransform* self, intptr_t slot);
QObject* QQuickTransform_SuperSender(const QQuickTransform* self);
int QQuickTransform_SenderSignalIndex(const QQuickTransform* self);
void QQuickTransform_OnSenderSignalIndex(const QQuickTransform* self, intptr_t slot);
int QQuickTransform_SuperSenderSignalIndex(const QQuickTransform* self);
int QQuickTransform_Receivers(const QQuickTransform* self, const char* signal);
void QQuickTransform_OnReceivers(const QQuickTransform* self, intptr_t slot);
int QQuickTransform_SuperReceivers(const QQuickTransform* self, const char* signal);
bool QQuickTransform_IsSignalConnected(const QQuickTransform* self, const QMetaMethod* signal);
void QQuickTransform_OnIsSignalConnected(const QQuickTransform* self, intptr_t slot);
bool QQuickTransform_SuperIsSignalConnected(const QQuickTransform* self, const QMetaMethod* signal);
void QQuickTransform_Delete(QQuickTransform* self);

QQuickItem* QQuickItem_new();
QQuickItem* QQuickItem_new2(QQuickItem* parent);
QQmlParserStatus* QQuickItem_AsQQmlParserStatus(QQuickItem* self);
QQuickItem* QQuickItem_FromQQmlParserStatus(QQmlParserStatus* _qqmlparserstatus);
QMetaObject* QQuickItem_MetaObject(const QQuickItem* self);
void* QQuickItem_Metacast(QQuickItem* self, const char* param1);
int QQuickItem_Metacall(QQuickItem* self, int param1, int param2, void** param3);
libqt_string QQuickItem_Tr(const char* s);
QQuickWindow* QQuickItem_Window(const QQuickItem* self);
QQuickItem* QQuickItem_ParentItem(const QQuickItem* self);
void QQuickItem_SetParentItem(QQuickItem* self, QQuickItem* parent);
void QQuickItem_StackBefore(QQuickItem* self, const QQuickItem* param1);
void QQuickItem_StackAfter(QQuickItem* self, const QQuickItem* param1);
QRectF* QQuickItem_ChildrenRect(QQuickItem* self);
libqt_list /* of QQuickItem* */ QQuickItem_ChildItems(const QQuickItem* self);
bool QQuickItem_Clip(const QQuickItem* self);
void QQuickItem_SetClip(QQuickItem* self, bool clip);
libqt_string QQuickItem_State(const QQuickItem* self);
void QQuickItem_SetState(QQuickItem* self, const libqt_string state);
double QQuickItem_BaselineOffset(const QQuickItem* self);
void QQuickItem_SetBaselineOffset(QQuickItem* self, double baselineOffset);
double QQuickItem_X(const QQuickItem* self);
double QQuickItem_Y(const QQuickItem* self);
QPointF* QQuickItem_Position(const QQuickItem* self);
void QQuickItem_SetX(QQuickItem* self, double x);
void QQuickItem_SetY(QQuickItem* self, double y);
void QQuickItem_SetPosition(QQuickItem* self, const QPointF* position);
double QQuickItem_Width(const QQuickItem* self);
void QQuickItem_SetWidth(QQuickItem* self, double width);
void QQuickItem_ResetWidth(QQuickItem* self);
void QQuickItem_SetImplicitWidth(QQuickItem* self, double implicitWidth);
double QQuickItem_ImplicitWidth(const QQuickItem* self);
double QQuickItem_Height(const QQuickItem* self);
void QQuickItem_SetHeight(QQuickItem* self, double height);
void QQuickItem_ResetHeight(QQuickItem* self);
void QQuickItem_SetImplicitHeight(QQuickItem* self, double implicitHeight);
double QQuickItem_ImplicitHeight(const QQuickItem* self);
QSizeF* QQuickItem_Size(const QQuickItem* self);
void QQuickItem_SetSize(QQuickItem* self, const QSizeF* size);
int QQuickItem_TransformOrigin(const QQuickItem* self);
void QQuickItem_SetTransformOrigin(QQuickItem* self, int transformOrigin);
QPointF* QQuickItem_TransformOriginPoint(const QQuickItem* self);
void QQuickItem_SetTransformOriginPoint(QQuickItem* self, const QPointF* transformOriginPoint);
double QQuickItem_Z(const QQuickItem* self);
void QQuickItem_SetZ(QQuickItem* self, double z);
double QQuickItem_Rotation(const QQuickItem* self);
void QQuickItem_SetRotation(QQuickItem* self, double rotation);
double QQuickItem_Scale(const QQuickItem* self);
void QQuickItem_SetScale(QQuickItem* self, double scale);
double QQuickItem_Opacity(const QQuickItem* self);
void QQuickItem_SetOpacity(QQuickItem* self, double opacity);
bool QQuickItem_IsVisible(const QQuickItem* self);
void QQuickItem_SetVisible(QQuickItem* self, bool visible);
bool QQuickItem_IsEnabled(const QQuickItem* self);
void QQuickItem_SetEnabled(QQuickItem* self, bool enabled);
bool QQuickItem_Smooth(const QQuickItem* self);
void QQuickItem_SetSmooth(QQuickItem* self, bool smooth);
bool QQuickItem_ActiveFocusOnTab(const QQuickItem* self);
void QQuickItem_SetActiveFocusOnTab(QQuickItem* self, bool activeFocusOnTab);
bool QQuickItem_Antialiasing(const QQuickItem* self);
void QQuickItem_SetAntialiasing(QQuickItem* self, bool antialiasing);
void QQuickItem_ResetAntialiasing(QQuickItem* self);
int QQuickItem_Flags(const QQuickItem* self);
void QQuickItem_SetFlag(QQuickItem* self, int flag);
void QQuickItem_SetFlags(QQuickItem* self, int flags);
QRectF* QQuickItem_BoundingRect(const QQuickItem* self);
QRectF* QQuickItem_ClipRect(const QQuickItem* self);
QQuickItem* QQuickItem_ViewportItem(const QQuickItem* self);
bool QQuickItem_HasActiveFocus(const QQuickItem* self);
bool QQuickItem_HasFocus(const QQuickItem* self);
void QQuickItem_SetFocus(QQuickItem* self, bool focus);
void QQuickItem_SetFocus2(QQuickItem* self, bool focus, int reason);
bool QQuickItem_IsFocusScope(const QQuickItem* self);
QQuickItem* QQuickItem_ScopedFocusItem(const QQuickItem* self);
int QQuickItem_FocusPolicy(const QQuickItem* self);
void QQuickItem_SetFocusPolicy(QQuickItem* self, int policy);
bool QQuickItem_IsAncestorOf(const QQuickItem* self, const QQuickItem* child);
int QQuickItem_AcceptedMouseButtons(const QQuickItem* self);
void QQuickItem_SetAcceptedMouseButtons(QQuickItem* self, int buttons);
bool QQuickItem_AcceptHoverEvents(const QQuickItem* self);
void QQuickItem_SetAcceptHoverEvents(QQuickItem* self, bool enabled);
bool QQuickItem_AcceptTouchEvents(const QQuickItem* self);
void QQuickItem_SetAcceptTouchEvents(QQuickItem* self, bool accept);
QCursor* QQuickItem_Cursor(const QQuickItem* self);
void QQuickItem_SetCursor(QQuickItem* self, const QCursor* cursor);
void QQuickItem_UnsetCursor(QQuickItem* self);
bool QQuickItem_IsUnderMouse(const QQuickItem* self);
void QQuickItem_GrabMouse(QQuickItem* self);
void QQuickItem_UngrabMouse(QQuickItem* self);
bool QQuickItem_KeepMouseGrab(const QQuickItem* self);
void QQuickItem_SetKeepMouseGrab(QQuickItem* self, bool keepMouseGrab);
bool QQuickItem_FiltersChildMouseEvents(const QQuickItem* self);
void QQuickItem_SetFiltersChildMouseEvents(QQuickItem* self, bool filter);
void QQuickItem_GrabTouchPoints(QQuickItem* self, const libqt_list /* of int */ ids);
void QQuickItem_UngrabTouchPoints(QQuickItem* self);
bool QQuickItem_KeepTouchGrab(const QQuickItem* self);
void QQuickItem_SetKeepTouchGrab(QQuickItem* self, bool keepTouchGrab);
bool QQuickItem_GrabToImage(QQuickItem* self, const QJSValue* callback);
bool QQuickItem_Contains(const QQuickItem* self, const QPointF* point);
QObject* QQuickItem_ContainmentMask(const QQuickItem* self);
void QQuickItem_SetContainmentMask(QQuickItem* self, QObject* mask);
QTransform* QQuickItem_ItemTransform(const QQuickItem* self, QQuickItem* param1, bool* param2);
QPointF* QQuickItem_MapToScene(const QQuickItem* self, const QPointF* point);
QRectF* QQuickItem_MapRectToItem(const QQuickItem* self, const QQuickItem* item, const QRectF* rect);
QRectF* QQuickItem_MapRectToScene(const QQuickItem* self, const QRectF* rect);
QPointF* QQuickItem_MapFromScene(const QQuickItem* self, const QPointF* point);
QRectF* QQuickItem_MapRectFromItem(const QQuickItem* self, const QQuickItem* item, const QRectF* rect);
QRectF* QQuickItem_MapRectFromScene(const QQuickItem* self, const QRectF* rect);
void QQuickItem_Polish(QQuickItem* self);
QPointF* QQuickItem_MapFromItem2(const QQuickItem* self, const QQuickItem* item, const QPointF* point);
QPointF* QQuickItem_MapFromItem3(QQuickItem* self, const QQuickItem* item, double x, double y);
QRectF* QQuickItem_MapFromItem4(const QQuickItem* self, const QQuickItem* item, const QRectF* rect);
QRectF* QQuickItem_MapFromItem5(const QQuickItem* self, const QQuickItem* item, double x, double y, double width, double height);
QPointF* QQuickItem_MapToItem2(const QQuickItem* self, const QQuickItem* item, const QPointF* point);
QPointF* QQuickItem_MapToItem3(QQuickItem* self, const QQuickItem* item, double x, double y);
QRectF* QQuickItem_MapToItem4(const QQuickItem* self, const QQuickItem* item, const QRectF* rect);
QRectF* QQuickItem_MapToItem5(const QQuickItem* self, const QQuickItem* item, double x, double y, double width, double height);
QPointF* QQuickItem_MapFromGlobal2(const QQuickItem* self, double x, double y);
QPointF* QQuickItem_MapFromGlobal3(const QQuickItem* self, const QPointF* point);
QPointF* QQuickItem_MapToGlobal2(const QQuickItem* self, double x, double y);
QPointF* QQuickItem_MapToGlobal3(const QQuickItem* self, const QPointF* point);
void QQuickItem_ForceActiveFocus(QQuickItem* self);
void QQuickItem_ForceActiveFocus2(QQuickItem* self, int reason);
QQuickItem* QQuickItem_NextItemInFocusChain(QQuickItem* self);
QQuickItem* QQuickItem_ChildAt(const QQuickItem* self, double x, double y);
void QQuickItem_EnsurePolished(QQuickItem* self);
void QQuickItem_DumpItemTree(const QQuickItem* self);
QVariant* QQuickItem_InputMethodQuery(const QQuickItem* self, int query);
bool QQuickItem_IsTextureProvider(const QQuickItem* self);
QSGTextureProvider* QQuickItem_TextureProvider(const QQuickItem* self);
void QQuickItem_Update(QQuickItem* self);
void QQuickItem_ChildrenRectChanged(QQuickItem* self, const QRectF* param1);
void QQuickItem_Connect_ChildrenRectChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_BaselineOffsetChanged(QQuickItem* self, double param1);
void QQuickItem_Connect_BaselineOffsetChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_StateChanged(QQuickItem* self, const libqt_string param1);
void QQuickItem_Connect_StateChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_FocusChanged(QQuickItem* self, bool param1);
void QQuickItem_Connect_FocusChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ActiveFocusChanged(QQuickItem* self, bool param1);
void QQuickItem_Connect_ActiveFocusChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_FocusPolicyChanged(QQuickItem* self, int param1);
void QQuickItem_Connect_FocusPolicyChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ActiveFocusOnTabChanged(QQuickItem* self, bool param1);
void QQuickItem_Connect_ActiveFocusOnTabChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ParentChanged(QQuickItem* self, QQuickItem* param1);
void QQuickItem_Connect_ParentChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_TransformOriginChanged(QQuickItem* self, int param1);
void QQuickItem_Connect_TransformOriginChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_SmoothChanged(QQuickItem* self, bool param1);
void QQuickItem_Connect_SmoothChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_AntialiasingChanged(QQuickItem* self, bool param1);
void QQuickItem_Connect_AntialiasingChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ClipChanged(QQuickItem* self, bool param1);
void QQuickItem_Connect_ClipChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_WindowChanged(QQuickItem* self, QQuickWindow* window);
void QQuickItem_Connect_WindowChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ChildrenChanged(QQuickItem* self);
void QQuickItem_Connect_ChildrenChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_OpacityChanged(QQuickItem* self);
void QQuickItem_Connect_OpacityChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_EnabledChanged(QQuickItem* self);
void QQuickItem_Connect_EnabledChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_VisibleChanged(QQuickItem* self);
void QQuickItem_Connect_VisibleChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_VisibleChildrenChanged(QQuickItem* self);
void QQuickItem_Connect_VisibleChildrenChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_RotationChanged(QQuickItem* self);
void QQuickItem_Connect_RotationChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ScaleChanged(QQuickItem* self);
void QQuickItem_Connect_ScaleChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_XChanged(QQuickItem* self);
void QQuickItem_Connect_XChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_YChanged(QQuickItem* self);
void QQuickItem_Connect_YChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_WidthChanged(QQuickItem* self);
void QQuickItem_Connect_WidthChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_HeightChanged(QQuickItem* self);
void QQuickItem_Connect_HeightChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ZChanged(QQuickItem* self);
void QQuickItem_Connect_ZChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ImplicitWidthChanged(QQuickItem* self);
void QQuickItem_Connect_ImplicitWidthChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ImplicitHeightChanged(QQuickItem* self);
void QQuickItem_Connect_ImplicitHeightChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_ContainmentMaskChanged(QQuickItem* self);
void QQuickItem_Connect_ContainmentMaskChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_PaletteChanged(QQuickItem* self);
void QQuickItem_Connect_PaletteChanged(QQuickItem* self, intptr_t slot);
void QQuickItem_PaletteCreated(QQuickItem* self);
void QQuickItem_Connect_PaletteCreated(QQuickItem* self, intptr_t slot);
bool QQuickItem_Event(QQuickItem* self, QEvent* param1);
void QQuickItem_ItemChange(QQuickItem* self, int param1, const QQuickItem__ItemChangeData* param2);
void QQuickItem_GeometryChange(QQuickItem* self, const QRectF* newGeometry, const QRectF* oldGeometry);
void QQuickItem_ClassBegin(QQuickItem* self);
void QQuickItem_ComponentComplete(QQuickItem* self);
void QQuickItem_KeyPressEvent(QQuickItem* self, QKeyEvent* event);
void QQuickItem_KeyReleaseEvent(QQuickItem* self, QKeyEvent* event);
void QQuickItem_InputMethodEvent(QQuickItem* self, QInputMethodEvent* param1);
void QQuickItem_FocusInEvent(QQuickItem* self, QFocusEvent* param1);
void QQuickItem_FocusOutEvent(QQuickItem* self, QFocusEvent* param1);
void QQuickItem_MousePressEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_MouseMoveEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_MouseReleaseEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_MouseDoubleClickEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_MouseUngrabEvent(QQuickItem* self);
void QQuickItem_TouchUngrabEvent(QQuickItem* self);
void QQuickItem_WheelEvent(QQuickItem* self, QWheelEvent* event);
void QQuickItem_TouchEvent(QQuickItem* self, QTouchEvent* event);
void QQuickItem_HoverEnterEvent(QQuickItem* self, QHoverEvent* event);
void QQuickItem_HoverMoveEvent(QQuickItem* self, QHoverEvent* event);
void QQuickItem_HoverLeaveEvent(QQuickItem* self, QHoverEvent* event);
void QQuickItem_DragEnterEvent(QQuickItem* self, QDragEnterEvent* param1);
void QQuickItem_DragMoveEvent(QQuickItem* self, QDragMoveEvent* param1);
void QQuickItem_DragLeaveEvent(QQuickItem* self, QDragLeaveEvent* param1);
void QQuickItem_DropEvent(QQuickItem* self, QDropEvent* param1);
bool QQuickItem_ChildMouseEventFilter(QQuickItem* self, QQuickItem* param1, QEvent* param2);
QSGNode* QQuickItem_UpdatePaintNode(QQuickItem* self, QSGNode* param1, QQuickItem__UpdatePaintNodeData* param2);
void QQuickItem_ReleaseResources(QQuickItem* self);
void QQuickItem_UpdatePolish(QQuickItem* self);
libqt_string QQuickItem_Tr2(const char* s, const char* c);
libqt_string QQuickItem_Tr3(const char* s, const char* c, int n);
void QQuickItem_SetFlag2(QQuickItem* self, int flag, bool enabled);
bool QQuickItem_GrabToImage22(QQuickItem* self, const QJSValue* callback, const QSize* targetSize);
QQuickItem* QQuickItem_NextItemInFocusChain1(QQuickItem* self, bool forward);
void QQuickItem_OnMetaObject(const QQuickItem* self, intptr_t slot);
QMetaObject* QQuickItem_SuperMetaObject(const QQuickItem* self);
void QQuickItem_OnMetacast(QQuickItem* self, intptr_t slot);
void* QQuickItem_SuperMetacast(QQuickItem* self, const char* param1);
void QQuickItem_OnMetacall(QQuickItem* self, intptr_t slot);
int QQuickItem_SuperMetacall(QQuickItem* self, int param1, int param2, void** param3);
void QQuickItem_OnBoundingRect(const QQuickItem* self, intptr_t slot);
QRectF* QQuickItem_SuperBoundingRect(const QQuickItem* self);
void QQuickItem_OnClipRect(const QQuickItem* self, intptr_t slot);
QRectF* QQuickItem_SuperClipRect(const QQuickItem* self);
void QQuickItem_OnContains(const QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperContains(const QQuickItem* self, const QPointF* point);
void QQuickItem_OnInputMethodQuery(const QQuickItem* self, intptr_t slot);
QVariant* QQuickItem_SuperInputMethodQuery(const QQuickItem* self, int query);
void QQuickItem_OnIsTextureProvider(const QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperIsTextureProvider(const QQuickItem* self);
void QQuickItem_OnTextureProvider(const QQuickItem* self, intptr_t slot);
QSGTextureProvider* QQuickItem_SuperTextureProvider(const QQuickItem* self);
void QQuickItem_OnEvent(QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperEvent(QQuickItem* self, QEvent* param1);
void QQuickItem_OnItemChange(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperItemChange(QQuickItem* self, int param1, const QQuickItem__ItemChangeData* param2);
void QQuickItem_OnGeometryChange(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperGeometryChange(QQuickItem* self, const QRectF* newGeometry, const QRectF* oldGeometry);
void QQuickItem_OnClassBegin(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperClassBegin(QQuickItem* self);
void QQuickItem_OnComponentComplete(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperComponentComplete(QQuickItem* self);
void QQuickItem_OnKeyPressEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperKeyPressEvent(QQuickItem* self, QKeyEvent* event);
void QQuickItem_OnKeyReleaseEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperKeyReleaseEvent(QQuickItem* self, QKeyEvent* event);
void QQuickItem_OnInputMethodEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperInputMethodEvent(QQuickItem* self, QInputMethodEvent* param1);
void QQuickItem_OnFocusInEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperFocusInEvent(QQuickItem* self, QFocusEvent* param1);
void QQuickItem_OnFocusOutEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperFocusOutEvent(QQuickItem* self, QFocusEvent* param1);
void QQuickItem_OnMousePressEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperMousePressEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_OnMouseMoveEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperMouseMoveEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_OnMouseReleaseEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperMouseReleaseEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_OnMouseDoubleClickEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperMouseDoubleClickEvent(QQuickItem* self, QMouseEvent* event);
void QQuickItem_OnMouseUngrabEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperMouseUngrabEvent(QQuickItem* self);
void QQuickItem_OnTouchUngrabEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperTouchUngrabEvent(QQuickItem* self);
void QQuickItem_OnWheelEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperWheelEvent(QQuickItem* self, QWheelEvent* event);
void QQuickItem_OnTouchEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperTouchEvent(QQuickItem* self, QTouchEvent* event);
void QQuickItem_OnHoverEnterEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperHoverEnterEvent(QQuickItem* self, QHoverEvent* event);
void QQuickItem_OnHoverMoveEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperHoverMoveEvent(QQuickItem* self, QHoverEvent* event);
void QQuickItem_OnHoverLeaveEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperHoverLeaveEvent(QQuickItem* self, QHoverEvent* event);
void QQuickItem_OnDragEnterEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperDragEnterEvent(QQuickItem* self, QDragEnterEvent* param1);
void QQuickItem_OnDragMoveEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperDragMoveEvent(QQuickItem* self, QDragMoveEvent* param1);
void QQuickItem_OnDragLeaveEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperDragLeaveEvent(QQuickItem* self, QDragLeaveEvent* param1);
void QQuickItem_OnDropEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperDropEvent(QQuickItem* self, QDropEvent* param1);
void QQuickItem_OnChildMouseEventFilter(QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperChildMouseEventFilter(QQuickItem* self, QQuickItem* param1, QEvent* param2);
void QQuickItem_OnUpdatePaintNode(QQuickItem* self, intptr_t slot);
QSGNode* QQuickItem_SuperUpdatePaintNode(QQuickItem* self, QSGNode* param1, QQuickItem__UpdatePaintNodeData* param2);
void QQuickItem_OnReleaseResources(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperReleaseResources(QQuickItem* self);
void QQuickItem_OnUpdatePolish(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperUpdatePolish(QQuickItem* self);
bool QQuickItem_EventFilter(QQuickItem* self, QObject* watched, QEvent* event);
void QQuickItem_OnEventFilter(QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperEventFilter(QQuickItem* self, QObject* watched, QEvent* event);
void QQuickItem_TimerEvent(QQuickItem* self, QTimerEvent* event);
void QQuickItem_OnTimerEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperTimerEvent(QQuickItem* self, QTimerEvent* event);
void QQuickItem_ChildEvent(QQuickItem* self, QChildEvent* event);
void QQuickItem_OnChildEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperChildEvent(QQuickItem* self, QChildEvent* event);
void QQuickItem_CustomEvent(QQuickItem* self, QEvent* event);
void QQuickItem_OnCustomEvent(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperCustomEvent(QQuickItem* self, QEvent* event);
void QQuickItem_ConnectNotify(QQuickItem* self, const QMetaMethod* signal);
void QQuickItem_OnConnectNotify(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperConnectNotify(QQuickItem* self, const QMetaMethod* signal);
void QQuickItem_DisconnectNotify(QQuickItem* self, const QMetaMethod* signal);
void QQuickItem_OnDisconnectNotify(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperDisconnectNotify(QQuickItem* self, const QMetaMethod* signal);
bool QQuickItem_IsComponentComplete(const QQuickItem* self);
void QQuickItem_OnIsComponentComplete(const QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperIsComponentComplete(const QQuickItem* self);
void QQuickItem_UpdateInputMethod(QQuickItem* self);
void QQuickItem_OnUpdateInputMethod(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperUpdateInputMethod(QQuickItem* self);
bool QQuickItem_WidthValid(const QQuickItem* self);
void QQuickItem_OnWidthValid(const QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperWidthValid(const QQuickItem* self);
bool QQuickItem_HeightValid(const QQuickItem* self);
void QQuickItem_OnHeightValid(const QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperHeightValid(const QQuickItem* self);
void QQuickItem_SetImplicitSize(QQuickItem* self, double param1, double param2);
void QQuickItem_OnSetImplicitSize(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperSetImplicitSize(QQuickItem* self, double param1, double param2);
void QQuickItem_UpdateInputMethod1(QQuickItem* self, int queries);
void QQuickItem_OnUpdateInputMethod1(QQuickItem* self, intptr_t slot);
void QQuickItem_SuperUpdateInputMethod1(QQuickItem* self, int queries);
QObject* QQuickItem_Sender(const QQuickItem* self);
void QQuickItem_OnSender(const QQuickItem* self, intptr_t slot);
QObject* QQuickItem_SuperSender(const QQuickItem* self);
int QQuickItem_SenderSignalIndex(const QQuickItem* self);
void QQuickItem_OnSenderSignalIndex(const QQuickItem* self, intptr_t slot);
int QQuickItem_SuperSenderSignalIndex(const QQuickItem* self);
int QQuickItem_Receivers(const QQuickItem* self, const char* signal);
void QQuickItem_OnReceivers(const QQuickItem* self, intptr_t slot);
int QQuickItem_SuperReceivers(const QQuickItem* self, const char* signal);
bool QQuickItem_IsSignalConnected(const QQuickItem* self, const QMetaMethod* signal);
void QQuickItem_OnIsSignalConnected(const QQuickItem* self, intptr_t slot);
bool QQuickItem_SuperIsSignalConnected(const QQuickItem* self, const QMetaMethod* signal);
void QQuickItem_Delete(QQuickItem* self);

QQuickItem__ItemChangeData* QQuickItem__ItemChangeData_new(const QQuickItem__ItemChangeData* other);
QQuickItem__ItemChangeData* QQuickItem__ItemChangeData_new2(QQuickItem__ItemChangeData* other);
QQuickItem__ItemChangeData* QQuickItem__ItemChangeData_new3(QQuickItem* v);
QQuickItem__ItemChangeData* QQuickItem__ItemChangeData_new4(QQuickWindow* v);
QQuickItem__ItemChangeData* QQuickItem__ItemChangeData_new5(double v);
QQuickItem__ItemChangeData* QQuickItem__ItemChangeData_new6(bool v);
void QQuickItem__ItemChangeData_CopyAssign(QQuickItem__ItemChangeData* self, QQuickItem__ItemChangeData* other);
void QQuickItem__ItemChangeData_MoveAssign(QQuickItem__ItemChangeData* self, QQuickItem__ItemChangeData* other);
QQuickItem* QQuickItem__ItemChangeData_Item(const QQuickItem__ItemChangeData* self);
void QQuickItem__ItemChangeData_SetItem(QQuickItem__ItemChangeData* self, QQuickItem* item);
QQuickWindow* QQuickItem__ItemChangeData_Window(const QQuickItem__ItemChangeData* self);
void QQuickItem__ItemChangeData_SetWindow(QQuickItem__ItemChangeData* self, QQuickWindow* window);
double QQuickItem__ItemChangeData_RealValue(const QQuickItem__ItemChangeData* self);
void QQuickItem__ItemChangeData_SetRealValue(QQuickItem__ItemChangeData* self, double realValue);
bool QQuickItem__ItemChangeData_BoolValue(const QQuickItem__ItemChangeData* self);
void QQuickItem__ItemChangeData_SetBoolValue(QQuickItem__ItemChangeData* self, bool boolValue);
void QQuickItem__ItemChangeData_Delete(QQuickItem__ItemChangeData* self);

QQuickItem__UpdatePaintNodeData* QQuickItem__UpdatePaintNodeData_new(const QQuickItem__UpdatePaintNodeData* other);
QQuickItem__UpdatePaintNodeData* QQuickItem__UpdatePaintNodeData_new2(QQuickItem__UpdatePaintNodeData* other);
void QQuickItem__UpdatePaintNodeData_CopyAssign(QQuickItem__UpdatePaintNodeData* self, QQuickItem__UpdatePaintNodeData* other);
void QQuickItem__UpdatePaintNodeData_MoveAssign(QQuickItem__UpdatePaintNodeData* self, QQuickItem__UpdatePaintNodeData* other);
QSGTransformNode* QQuickItem__UpdatePaintNodeData_TransformNode(const QQuickItem__UpdatePaintNodeData* self);
void QQuickItem__UpdatePaintNodeData_SetTransformNode(QQuickItem__UpdatePaintNodeData* self, QSGTransformNode* transformNode);
void QQuickItem__UpdatePaintNodeData_Delete(QQuickItem__UpdatePaintNodeData* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
